/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.customer.release.tool.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.customer.release.tool.model.JIRAComponent;
import com.liferay.osb.customer.release.tool.model.JIRAComponentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the JIRAComponent service. Represents a row in the &quot;OSBCustomer_JIRAComponent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link JIRAComponentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JIRAComponentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JIRAComponentImpl
 * @see JIRAComponent
 * @see JIRAComponentModel
 * @generated
 */
@ProviderType
public class JIRAComponentModelImpl extends BaseModelImpl<JIRAComponent>
	implements JIRAComponentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jira component model instance should use the {@link JIRAComponent} interface instead.
	 */
	public static final String TABLE_NAME = "OSBCustomer_JIRAComponent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "jiraComponentId", Types.BIGINT },
			{ "remoteId", Types.BIGINT },
			{ "remoteProject", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "visible", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("jiraComponentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remoteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remoteProject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("visible", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table OSBCustomer_JIRAComponent (jiraComponentId LONG not null primary key,remoteId LONG,remoteProject VARCHAR(75) null,name VARCHAR(75) null,visible BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table OSBCustomer_JIRAComponent";
	public static final String ORDER_BY_JPQL = " ORDER BY jiraComponent.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSBCustomer_JIRAComponent.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.release.tool.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.customer.release.tool.model.JIRAComponent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.release.tool.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.customer.release.tool.model.JIRAComponent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.release.tool.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.customer.release.tool.model.JIRAComponent"),
			true);
	public static final long REMOTEID_COLUMN_BITMASK = 1L;
	public static final long REMOTEPROJECT_COLUMN_BITMASK = 2L;
	public static final long VISIBLE_COLUMN_BITMASK = 4L;
	public static final long NAME_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.customer.release.tool.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.customer.release.tool.model.JIRAComponent"));

	public JIRAComponentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _jiraComponentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJiraComponentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _jiraComponentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JIRAComponent.class;
	}

	@Override
	public String getModelClassName() {
		return JIRAComponent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("jiraComponentId", getJiraComponentId());
		attributes.put("remoteId", getRemoteId());
		attributes.put("remoteProject", getRemoteProject());
		attributes.put("name", getName());
		attributes.put("visible", getVisible());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long jiraComponentId = (Long)attributes.get("jiraComponentId");

		if (jiraComponentId != null) {
			setJiraComponentId(jiraComponentId);
		}

		Long remoteId = (Long)attributes.get("remoteId");

		if (remoteId != null) {
			setRemoteId(remoteId);
		}

		String remoteProject = (String)attributes.get("remoteProject");

		if (remoteProject != null) {
			setRemoteProject(remoteProject);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Boolean visible = (Boolean)attributes.get("visible");

		if (visible != null) {
			setVisible(visible);
		}
	}

	@Override
	public long getJiraComponentId() {
		return _jiraComponentId;
	}

	@Override
	public void setJiraComponentId(long jiraComponentId) {
		_jiraComponentId = jiraComponentId;
	}

	@Override
	public long getRemoteId() {
		return _remoteId;
	}

	@Override
	public void setRemoteId(long remoteId) {
		_columnBitmask |= REMOTEID_COLUMN_BITMASK;

		if (!_setOriginalRemoteId) {
			_setOriginalRemoteId = true;

			_originalRemoteId = _remoteId;
		}

		_remoteId = remoteId;
	}

	public long getOriginalRemoteId() {
		return _originalRemoteId;
	}

	@Override
	public String getRemoteProject() {
		if (_remoteProject == null) {
			return StringPool.BLANK;
		}
		else {
			return _remoteProject;
		}
	}

	@Override
	public void setRemoteProject(String remoteProject) {
		_columnBitmask |= REMOTEPROJECT_COLUMN_BITMASK;

		if (_originalRemoteProject == null) {
			_originalRemoteProject = _remoteProject;
		}

		_remoteProject = remoteProject;
	}

	public String getOriginalRemoteProject() {
		return GetterUtil.getString(_originalRemoteProject);
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@Override
	public boolean getVisible() {
		return _visible;
	}

	@Override
	public boolean isVisible() {
		return _visible;
	}

	@Override
	public void setVisible(boolean visible) {
		_columnBitmask |= VISIBLE_COLUMN_BITMASK;

		if (!_setOriginalVisible) {
			_setOriginalVisible = true;

			_originalVisible = _visible;
		}

		_visible = visible;
	}

	public boolean getOriginalVisible() {
		return _originalVisible;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			JIRAComponent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public JIRAComponent toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (JIRAComponent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JIRAComponentImpl jiraComponentImpl = new JIRAComponentImpl();

		jiraComponentImpl.setJiraComponentId(getJiraComponentId());
		jiraComponentImpl.setRemoteId(getRemoteId());
		jiraComponentImpl.setRemoteProject(getRemoteProject());
		jiraComponentImpl.setName(getName());
		jiraComponentImpl.setVisible(getVisible());

		jiraComponentImpl.resetOriginalValues();

		return jiraComponentImpl;
	}

	@Override
	public int compareTo(JIRAComponent jiraComponent) {
		int value = 0;

		value = getName().compareTo(jiraComponent.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof JIRAComponent)) {
			return false;
		}

		JIRAComponent jiraComponent = (JIRAComponent)obj;

		long primaryKey = jiraComponent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		JIRAComponentModelImpl jiraComponentModelImpl = this;

		jiraComponentModelImpl._originalRemoteId = jiraComponentModelImpl._remoteId;

		jiraComponentModelImpl._setOriginalRemoteId = false;

		jiraComponentModelImpl._originalRemoteProject = jiraComponentModelImpl._remoteProject;

		jiraComponentModelImpl._originalVisible = jiraComponentModelImpl._visible;

		jiraComponentModelImpl._setOriginalVisible = false;

		jiraComponentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<JIRAComponent> toCacheModel() {
		JIRAComponentCacheModel jiraComponentCacheModel = new JIRAComponentCacheModel();

		jiraComponentCacheModel.jiraComponentId = getJiraComponentId();

		jiraComponentCacheModel.remoteId = getRemoteId();

		jiraComponentCacheModel.remoteProject = getRemoteProject();

		String remoteProject = jiraComponentCacheModel.remoteProject;

		if ((remoteProject != null) && (remoteProject.length() == 0)) {
			jiraComponentCacheModel.remoteProject = null;
		}

		jiraComponentCacheModel.name = getName();

		String name = jiraComponentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			jiraComponentCacheModel.name = null;
		}

		jiraComponentCacheModel.visible = getVisible();

		return jiraComponentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{jiraComponentId=");
		sb.append(getJiraComponentId());
		sb.append(", remoteId=");
		sb.append(getRemoteId());
		sb.append(", remoteProject=");
		sb.append(getRemoteProject());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", visible=");
		sb.append(getVisible());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.customer.release.tool.model.JIRAComponent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>jiraComponentId</column-name><column-value><![CDATA[");
		sb.append(getJiraComponentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteId</column-name><column-value><![CDATA[");
		sb.append(getRemoteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteProject</column-name><column-value><![CDATA[");
		sb.append(getRemoteProject());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visible</column-name><column-value><![CDATA[");
		sb.append(getVisible());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = JIRAComponent.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			JIRAComponent.class
		};
	private long _jiraComponentId;
	private long _remoteId;
	private long _originalRemoteId;
	private boolean _setOriginalRemoteId;
	private String _remoteProject;
	private String _originalRemoteProject;
	private String _name;
	private boolean _visible;
	private boolean _originalVisible;
	private boolean _setOriginalVisible;
	private long _columnBitmask;
	private JIRAComponent _escapedModel;
}