author=Liferay, Inc.
change-log=
licenses=DXP
liferay-portal-profile-names=DXP
liferay-versions=7.0.10+
long-description=
module-group-id=liferay
module-incremental-version=1
name=OSB Customer
page-url=http://www.liferay.com
resources-importer-append-version=false
resources-importer-developer-mode-enabled=true
resources-importer-target-class-name=com.liferay.portal.kernel.model.Group
resources-importer-target-value=Global
resources-importer-update-mode-enabled=true
short-description=
tags=