include-and-override=portlet-ext.properties

jira.browse.url=${jira.url}/browse/
jira.field.id.qa.test.name=
jira.field.id.qa.test.score=
jira.jql.url=${jira.url}/issues/?jql=
jira.oauth.consumer.key=
jira.oauth.rsa.private.key=
jira.oauth.shared.secret=
jira.oauth.url=${jira.url}/plugins/servlet/oauth/
jira.rest.api.issue.url=${jira.rest.api.url}/issue/
jira.rest.api.link.url=${jira.url}/rest/api/latest/issue/
jira.rest.api.url=${jira.url}/rest/api/latest
jira.url=