/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.pulpo.connector.de.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import com.liferay.pulpo.connector.de.model.ConnectorTransaction;
import com.liferay.pulpo.connector.de.service.ConnectorTransactionLocalService;
import com.liferay.pulpo.connector.de.service.persistence.ConnectorTransactionPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the connector transaction local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.pulpo.connector.de.service.impl.ConnectorTransactionLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.pulpo.connector.de.service.impl.ConnectorTransactionLocalServiceImpl
 * @see com.liferay.pulpo.connector.de.service.ConnectorTransactionLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ConnectorTransactionLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ConnectorTransactionLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.pulpo.connector.de.service.ConnectorTransactionLocalServiceUtil} to access the connector transaction local service.
	 */

	/**
	 * Adds the connector transaction to the database. Also notifies the appropriate model listeners.
	 *
	 * @param connectorTransaction the connector transaction
	 * @return the connector transaction that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ConnectorTransaction addConnectorTransaction(
		ConnectorTransaction connectorTransaction) {
		connectorTransaction.setNew(true);

		return connectorTransactionPersistence.update(connectorTransaction);
	}

	/**
	 * Creates a new connector transaction with the primary key. Does not add the connector transaction to the database.
	 *
	 * @param connectorTransactionId the primary key for the new connector transaction
	 * @return the new connector transaction
	 */
	@Override
	public ConnectorTransaction createConnectorTransaction(
		long connectorTransactionId) {
		return connectorTransactionPersistence.create(connectorTransactionId);
	}

	/**
	 * Deletes the connector transaction with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param connectorTransactionId the primary key of the connector transaction
	 * @return the connector transaction that was removed
	 * @throws PortalException if a connector transaction with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ConnectorTransaction deleteConnectorTransaction(
		long connectorTransactionId) throws PortalException {
		return connectorTransactionPersistence.remove(connectorTransactionId);
	}

	/**
	 * Deletes the connector transaction from the database. Also notifies the appropriate model listeners.
	 *
	 * @param connectorTransaction the connector transaction
	 * @return the connector transaction that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ConnectorTransaction deleteConnectorTransaction(
		ConnectorTransaction connectorTransaction) {
		return connectorTransactionPersistence.remove(connectorTransaction);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ConnectorTransaction.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return connectorTransactionPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.pulpo.connector.de.model.impl.ConnectorTransactionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return connectorTransactionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.pulpo.connector.de.model.impl.ConnectorTransactionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return connectorTransactionPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return connectorTransactionPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return connectorTransactionPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ConnectorTransaction fetchConnectorTransaction(
		long connectorTransactionId) {
		return connectorTransactionPersistence.fetchByPrimaryKey(connectorTransactionId);
	}

	/**
	 * Returns the connector transaction with the primary key.
	 *
	 * @param connectorTransactionId the primary key of the connector transaction
	 * @return the connector transaction
	 * @throws PortalException if a connector transaction with the primary key could not be found
	 */
	@Override
	public ConnectorTransaction getConnectorTransaction(
		long connectorTransactionId) throws PortalException {
		return connectorTransactionPersistence.findByPrimaryKey(connectorTransactionId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(connectorTransactionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ConnectorTransaction.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"connectorTransactionId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(connectorTransactionLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ConnectorTransaction.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"connectorTransactionId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(connectorTransactionLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ConnectorTransaction.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"connectorTransactionId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return connectorTransactionLocalService.deleteConnectorTransaction((ConnectorTransaction)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return connectorTransactionPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the connector transactions.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.pulpo.connector.de.model.impl.ConnectorTransactionModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of connector transactions
	 * @param end the upper bound of the range of connector transactions (not inclusive)
	 * @return the range of connector transactions
	 */
	@Override
	public List<ConnectorTransaction> getConnectorTransactions(int start,
		int end) {
		return connectorTransactionPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of connector transactions.
	 *
	 * @return the number of connector transactions
	 */
	@Override
	public int getConnectorTransactionsCount() {
		return connectorTransactionPersistence.countAll();
	}

	/**
	 * Updates the connector transaction in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param connectorTransaction the connector transaction
	 * @return the connector transaction that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ConnectorTransaction updateConnectorTransaction(
		ConnectorTransaction connectorTransaction) {
		return connectorTransactionPersistence.update(connectorTransaction);
	}

	/**
	 * Returns the connector transaction local service.
	 *
	 * @return the connector transaction local service
	 */
	public ConnectorTransactionLocalService getConnectorTransactionLocalService() {
		return connectorTransactionLocalService;
	}

	/**
	 * Sets the connector transaction local service.
	 *
	 * @param connectorTransactionLocalService the connector transaction local service
	 */
	public void setConnectorTransactionLocalService(
		ConnectorTransactionLocalService connectorTransactionLocalService) {
		this.connectorTransactionLocalService = connectorTransactionLocalService;
	}

	/**
	 * Returns the connector transaction persistence.
	 *
	 * @return the connector transaction persistence
	 */
	public ConnectorTransactionPersistence getConnectorTransactionPersistence() {
		return connectorTransactionPersistence;
	}

	/**
	 * Sets the connector transaction persistence.
	 *
	 * @param connectorTransactionPersistence the connector transaction persistence
	 */
	public void setConnectorTransactionPersistence(
		ConnectorTransactionPersistence connectorTransactionPersistence) {
		this.connectorTransactionPersistence = connectorTransactionPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.pulpo.connector.de.model.ConnectorTransaction",
			connectorTransactionLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.pulpo.connector.de.model.ConnectorTransaction");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ConnectorTransactionLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ConnectorTransaction.class;
	}

	protected String getModelClassName() {
		return ConnectorTransaction.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = connectorTransactionPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ConnectorTransactionLocalService.class)
	protected ConnectorTransactionLocalService connectorTransactionLocalService;
	@BeanReference(type = ConnectorTransactionPersistence.class)
	protected ConnectorTransactionPersistence connectorTransactionPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}