{
 "title": "osb-asah-publisher-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Analytics Events Message - Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{exception=\"None\", job=\"osbasahpublisher\", method=\"POST\", status=\"200\", uri=\"/\"}[5m]) / rate(http_server_requests_seconds_count{exception=\"None\", job=\"osbasahpublisher\", method=\"POST\", status=\"200\", uri=\"/\"}[5m])"
    }
   ]
  },
  {
   "title": "Analytics Events Messages Requests/Sec - Last 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"osbasahpublisher\", uri=\"/\"}[5m])"
    }
   ]
  },
  {
   "title": "Identity Requests/Sec - Last 5min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"osbasahpublisher\", method=\"POST\", uri=\"/identity\"}[5m])"
    }
   ]
  }
 ]
}