create table WatsonActivity (
	watsonActivityId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	typeWatsonListTypeId LONG,
	subtypeWatsonListTypeId LONG,
	watsonIncidentId LONG,
	narrative STRING null,
	reportDate DATE null,
	startDate DATE null,
	status INTEGER
);

create table WatsonAddress (
	watsonAddressId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	countryId LONG,
	districtWatsonListTypeId LONG,
	originalWatsonAddressId LONG,
	provinceWatsonListTypeId LONG,
	subDistrictWatsonListTypeId LONG,
	typeWatsonListTypeId LONG,
	watsonIncidentId LONG,
	name STRING null,
	postalCode VARCHAR(75) null,
	region VARCHAR(75) null,
	street VARCHAR(75) null,
	number_ VARCHAR(75) null,
	building STRING null,
	floor VARCHAR(75) null,
	room VARCHAR(75) null,
	description STRING null,
	imagePayload TEXT null,
	lastSeenDate DATE null,
	latitude DOUBLE,
	longitude DOUBLE,
	status INTEGER
);

create table WatsonChild (
	watsonChildId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	birthCountryId LONG,
	citizenshipWatsonListTypeId LONG,
	countryWatsonListTypeId LONG,
	dischargeWatsonListTypeId LONG,
	ethnicityWatsonListTypeId LONG,
	originalWatsonPersonId LONG,
	sexWatsonListTypeId LONG,
	sourceSubtypeWatsonListTypeId LONG,
	sourceWatsonListTypeId LONG,
	typeWatsonListTypeId LONG,
	dateAccepted DATE null,
	dateDischarged DATE null,
	dateFollowUp DATE null,
	source VARCHAR(75) null,
	status INTEGER
);

create table WatsonDocument (
	watsonDocumentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	parentTypeWatsonListTypeId LONG,
	subtypeWatsonListTypeId LONG,
	typeWatsonListTypeId LONG,
	watsonChildId LONG,
	originalDocument BOOLEAN,
	receivedDate DATE null,
	imagePayload TEXT null,
	status INTEGER
);

create table WatsonHistory (
	watsonHistoryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	watsonParentId LONG,
	classNameId LONG,
	classPK LONG,
	type_ INTEGER,
	status INTEGER
);

create table WatsonIncident (
	watsonIncidentId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	externalCaseWatsonListTypeId LONG,
	sourceWatsonListTypeId LONG,
	typeWatsonListTypeId LONG,
	subtypeWatsonListTypeId LONG,
	audienceAdultCount LONG,
	audienceChildCount LONG,
	victimAdultCount LONG,
	victimChildCount LONG,
	name VARCHAR(75) null,
	description STRING null,
	externalCaseId VARCHAR(75) null,
	otherType VARCHAR(75) null,
	reportDate DATE null,
	startDate DATE null,
	endDate DATE null,
	incidentStatus INTEGER,
	status INTEGER
);

create table WatsonIncidentRel (
	watsonIncidentRelId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	watsonIncidentId1 LONG,
	watsonIncidentId2 LONG,
	type_ VARCHAR(75) null,
	status INTEGER
);

create table WatsonListType (
	watsonListTypeId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	parentWatsonListTypeId LONG,
	name STRING null,
	type_ VARCHAR(100) null,
	status INTEGER
);

create table WatsonListTypeRel (
	watsonListTypeRelId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	watsonListTypeId LONG,
	classNameId LONG,
	classPK LONG,
	primary_ BOOLEAN,
	value STRING null,
	type_ VARCHAR(75) null,
	status INTEGER
);

create table WatsonPerson (
	watsonPersonId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	birthCountryId LONG,
	citizenshipWatsonListTypeId LONG,
	countryWatsonListTypeId LONG,
	ethnicityWatsonListTypeId LONG,
	eyesWatsonListTypeId LONG,
	hairWatsonListTypeId LONG,
	originalWatsonPersonId LONG,
	sexWatsonListTypeId LONG,
	typeWatsonListTypeId LONG,
	watsonIncidentId LONG,
	description STRING null,
	imagePayload TEXT null,
	birthDate DATE null,
	dateAccepted DATE null,
	dateRescued DATE null,
	startAge VARCHAR(75) null,
	endAge VARCHAR(75) null,
	occupation STRING null,
	height VARCHAR(75) null,
	weight VARCHAR(75) null,
	accepted BOOLEAN,
	rescued BOOLEAN,
	status INTEGER
);

create table WatsonRelationship (
	watsonRelationshipId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	watsonIncidentId LONG,
	typeWatsonListTypeId LONG,
	classNameId1 LONG,
	classPK1 LONG,
	classNameId2 LONG,
	classPK2 LONG,
	description STRING null,
	status INTEGER
);

create table WatsonReport (
	watsonReportId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	originalWatsonReportId LONG,
	typeWatsonListTypeId LONG,
	watsonChildId LONG,
	name STRING null,
	description STRING null,
	fullReport STRING null,
	imagePayload TEXT null,
	timeSpent VARCHAR(75) null,
	reportedUser STRING null,
	reportDate DATE null,
	key_ INTEGER,
	status INTEGER
);

create table WatsonResource (
	watsonResourceId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	originalWatsonResourceId LONG,
	typeWatsonListTypeId LONG,
	watsonIncidentId LONG,
	name STRING null,
	description STRING null,
	imagePayload TEXT null,
	status INTEGER
);

create table WatsonVehicle (
	watsonVehicleId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	colorWatsonListTypeId LONG,
	makeWatsonListTypeId LONG,
	modelWatsonListTypeId LONG,
	originalWatsonVehicleId LONG,
	typeWatsonListTypeId LONG,
	yearWatsonListTypeId LONG,
	watsonIncidentId LONG,
	year INTEGER,
	description STRING null,
	imagePayload TEXT null,
	licensePlate VARCHAR(75) null,
	status INTEGER
);