{
 "title": "osbasah-cerebro-metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "publisher - analytics events message (last 5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(publisher_event_request_seconds_count[5m])",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "publisher - analytics events throughput (req /sec last 5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(publisher_event_request_seconds_count[5m]) ",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "extractor - analytics events message queue",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "extractor_analytics_events_message_queue_size",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "publisher - identity requests (last 5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(publisher_identity_request_seconds_count[5m])",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "publisher - identity throughput (req/sec last 5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(publisher_identity_request_seconds_count[5m]) ",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "publisher - identity throughput (req/sec last 5m)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(publisher_identity_request_seconds_count[5m]) ",
     "legendFormat": "a"
    }
   ]
  },
  {
   "title": "Analytics Events Queue Size (Nanites)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "curator_analytics_events_queue_size",
     "legendFormat": "{{nanite}}"
    }
   ]
  },
  {
   "title": "Stream Curator Events Processed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(curator_analytics_events_count[5m])",
     "legendFormat": "{{nanite}}"
    }
   ]
  },
  {
   "title": "backend (graphql) - throughput (req/sec last 5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(operation) (rate(backend_graphql_request_seconds[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}