{
 "title": "osbasah-faro-metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Faro Queue Size (Nanites)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "faro_curator_queue_size", "legendFormat": "{{nanite}}" }
   ]
  },
  {
   "title": "Faro Curator Processed Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(faro_curator_processed_count[5m])",
     "legendFormat": "{{nanite}}"
    }
   ]
  },
  {
   "title": "Faro Backend - throughput (req/sec last 5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(path) (rate(backend_request_seconds_count[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}