{
 "title": "osbasah-system-metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "classes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "classes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "classes_loaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "classes_loaded", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "classes_unloaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "classes_unloaded", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "gc_ps_marksweep_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_marksweep_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "gc_ps_marksweep_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_marksweep_time", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "gc_ps_scavenge_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_scavenge_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "gc_ps_scavenge_time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gc_ps_scavenge_time", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "heap", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "heap_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "heap_init", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "heap_committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "heap_committed", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "heap_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "heap_used", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "httpsessions_active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "httpsessions_active", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "httpsessions_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "httpsessions_max", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "mem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mem", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "mem_free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mem_free", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "nonheap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nonheap", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "nonheap_committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nonheap_committed", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "nonheap_init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nonheap_init", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "nonheap_used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nonheap_used", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "processors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "processors", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "instance_uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "instance_uptime", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "systemload_average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "systemload_average", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "scrape_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "scrape_samples_post_metric_relabeling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_samples_post_metric_relabeling",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "scrape_samples_scraped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "threads_daemon",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "threads_daemon", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "threads_peak",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "threads_peak", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "threads_totalStarted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "threads_totalStarted", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "up",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}