include-and-override=portlet-ext.properties

dossiera.account.link=https://dossiera.liferay.com/home/-/dossiera/account/

lcs.support.admin.link=https://lcs-qa.liferay.com/group/support/admin?p_p_id=com_liferay_osb_lcs_supportadmin_portlet_SupportAdminPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_osb_lcs_supportadmin_portlet_SupportAdminPortlet_mvcPath=%2Fsupportadmin%2Fview.jsp&_com_liferay_osb_lcs_supportadmin_portlet_SupportAdminPortlet_tabs1=&_com_liferay_osb_lcs_supportadmin_portlet_SupportAdminPortlet_corpProjectId=