/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.admin.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.customer.admin.model.AccountEnvironmentAttachment;
import com.liferay.osb.customer.admin.model.AccountEnvironmentAttachmentModel;
import com.liferay.osb.customer.admin.model.AccountEnvironmentAttachmentSoap;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AccountEnvironmentAttachment service. Represents a row in the &quot;OSB_AccountEnvironmentAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AccountEnvironmentAttachmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountEnvironmentAttachmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountEnvironmentAttachmentImpl
 * @generated
 */
@JSON(strict = true)
public class AccountEnvironmentAttachmentModelImpl
	extends BaseModelImpl<AccountEnvironmentAttachment>
	implements AccountEnvironmentAttachmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account environment attachment model instance should use the <code>AccountEnvironmentAttachment</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_AccountEnvironmentAttachment";

	public static final Object[][] TABLE_COLUMNS = {
		{"accountEnvironmentAttachmentId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"accountEnvironmentId", Types.BIGINT}, {"fileName", Types.VARCHAR},
		{"fileSize", Types.BIGINT}, {"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("accountEnvironmentAttachmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountEnvironmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileSize", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_AccountEnvironmentAttachment (accountEnvironmentAttachmentId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,accountEnvironmentId LONG,fileName VARCHAR(75) null,fileSize LONG,type_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table OSB_AccountEnvironmentAttachment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY accountEnvironmentAttachment.accountEnvironmentAttachmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_AccountEnvironmentAttachment.accountEnvironmentAttachmentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.admin.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.customer.admin.model.AccountEnvironmentAttachment"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.admin.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.customer.admin.model.AccountEnvironmentAttachment"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.admin.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.customer.admin.model.AccountEnvironmentAttachment"),
		true);

	public static final long ACCOUNTENVIRONMENTID_COLUMN_BITMASK = 1L;

	public static final long FILENAME_COLUMN_BITMASK = 2L;

	public static final long TYPE_COLUMN_BITMASK = 4L;

	public static final long ACCOUNTENVIRONMENTATTACHMENTID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AccountEnvironmentAttachment toModel(
		AccountEnvironmentAttachmentSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		AccountEnvironmentAttachment model =
			new AccountEnvironmentAttachmentImpl();

		model.setAccountEnvironmentAttachmentId(
			soapModel.getAccountEnvironmentAttachmentId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAccountEnvironmentId(soapModel.getAccountEnvironmentId());
		model.setFileName(soapModel.getFileName());
		model.setFileSize(soapModel.getFileSize());
		model.setType(soapModel.getType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AccountEnvironmentAttachment> toModels(
		AccountEnvironmentAttachmentSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<AccountEnvironmentAttachment> models =
			new ArrayList<AccountEnvironmentAttachment>(soapModels.length);

		for (AccountEnvironmentAttachmentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.customer.admin.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.customer.admin.model.AccountEnvironmentAttachment"));

	public AccountEnvironmentAttachmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _accountEnvironmentAttachmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAccountEnvironmentAttachmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _accountEnvironmentAttachmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AccountEnvironmentAttachment.class;
	}

	@Override
	public String getModelClassName() {
		return AccountEnvironmentAttachment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AccountEnvironmentAttachment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AccountEnvironmentAttachment, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountEnvironmentAttachment, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(AccountEnvironmentAttachment)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AccountEnvironmentAttachment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AccountEnvironmentAttachment, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AccountEnvironmentAttachment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AccountEnvironmentAttachment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AccountEnvironmentAttachment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AccountEnvironmentAttachment>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AccountEnvironmentAttachment.class.getClassLoader(),
			AccountEnvironmentAttachment.class, ModelWrapper.class);

		try {
			Constructor<AccountEnvironmentAttachment> constructor =
				(Constructor<AccountEnvironmentAttachment>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map
		<String, Function<AccountEnvironmentAttachment, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<AccountEnvironmentAttachment, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<AccountEnvironmentAttachment, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AccountEnvironmentAttachment, Object>>();
		Map<String, BiConsumer<AccountEnvironmentAttachment, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<AccountEnvironmentAttachment, ?>>();

		attributeGetterFunctions.put(
			"accountEnvironmentAttachmentId",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.
						getAccountEnvironmentAttachmentId();
				}

			});
		attributeSetterBiConsumers.put(
			"accountEnvironmentAttachmentId",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object accountEnvironmentAttachmentIdObject) {

					accountEnvironmentAttachment.
						setAccountEnvironmentAttachmentId(
							(Long)accountEnvironmentAttachmentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object userIdObject) {

					accountEnvironmentAttachment.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object userNameObject) {

					accountEnvironmentAttachment.setUserName(
						(String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object createDateObject) {

					accountEnvironmentAttachment.setCreateDate(
						(Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object modifiedDateObject) {

					accountEnvironmentAttachment.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"accountEnvironmentId",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.
						getAccountEnvironmentId();
				}

			});
		attributeSetterBiConsumers.put(
			"accountEnvironmentId",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object accountEnvironmentIdObject) {

					accountEnvironmentAttachment.setAccountEnvironmentId(
						(Long)accountEnvironmentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"fileName",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.getFileName();
				}

			});
		attributeSetterBiConsumers.put(
			"fileName",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object fileNameObject) {

					accountEnvironmentAttachment.setFileName(
						(String)fileNameObject);
				}

			});
		attributeGetterFunctions.put(
			"fileSize",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.getFileSize();
				}

			});
		attributeSetterBiConsumers.put(
			"fileSize",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object fileSizeObject) {

					accountEnvironmentAttachment.setFileSize(
						(Long)fileSizeObject);
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<AccountEnvironmentAttachment, Object>() {

				@Override
				public Object apply(
					AccountEnvironmentAttachment accountEnvironmentAttachment) {

					return accountEnvironmentAttachment.getType();
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<AccountEnvironmentAttachment, Object>() {

				@Override
				public void accept(
					AccountEnvironmentAttachment accountEnvironmentAttachment,
					Object typeObject) {

					accountEnvironmentAttachment.setType((Integer)typeObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getAccountEnvironmentAttachmentId() {
		return _accountEnvironmentAttachmentId;
	}

	@Override
	public void setAccountEnvironmentAttachmentId(
		long accountEnvironmentAttachmentId) {

		_accountEnvironmentAttachmentId = accountEnvironmentAttachmentId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAccountEnvironmentId() {
		return _accountEnvironmentId;
	}

	@Override
	public void setAccountEnvironmentId(long accountEnvironmentId) {
		_columnBitmask |= ACCOUNTENVIRONMENTID_COLUMN_BITMASK;

		if (!_setOriginalAccountEnvironmentId) {
			_setOriginalAccountEnvironmentId = true;

			_originalAccountEnvironmentId = _accountEnvironmentId;
		}

		_accountEnvironmentId = accountEnvironmentId;
	}

	public long getOriginalAccountEnvironmentId() {
		return _originalAccountEnvironmentId;
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_columnBitmask |= FILENAME_COLUMN_BITMASK;

		if (_originalFileName == null) {
			_originalFileName = _fileName;
		}

		_fileName = fileName;
	}

	public String getOriginalFileName() {
		return GetterUtil.getString(_originalFileName);
	}

	@JSON
	@Override
	public long getFileSize() {
		return _fileSize;
	}

	@Override
	public void setFileSize(long fileSize) {
		_fileSize = fileSize;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AccountEnvironmentAttachment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AccountEnvironmentAttachment toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AccountEnvironmentAttachment>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AccountEnvironmentAttachmentImpl accountEnvironmentAttachmentImpl =
			new AccountEnvironmentAttachmentImpl();

		accountEnvironmentAttachmentImpl.setAccountEnvironmentAttachmentId(
			getAccountEnvironmentAttachmentId());
		accountEnvironmentAttachmentImpl.setUserId(getUserId());
		accountEnvironmentAttachmentImpl.setUserName(getUserName());
		accountEnvironmentAttachmentImpl.setCreateDate(getCreateDate());
		accountEnvironmentAttachmentImpl.setModifiedDate(getModifiedDate());
		accountEnvironmentAttachmentImpl.setAccountEnvironmentId(
			getAccountEnvironmentId());
		accountEnvironmentAttachmentImpl.setFileName(getFileName());
		accountEnvironmentAttachmentImpl.setFileSize(getFileSize());
		accountEnvironmentAttachmentImpl.setType(getType());

		accountEnvironmentAttachmentImpl.resetOriginalValues();

		return accountEnvironmentAttachmentImpl;
	}

	@Override
	public int compareTo(
		AccountEnvironmentAttachment accountEnvironmentAttachment) {

		long primaryKey = accountEnvironmentAttachment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AccountEnvironmentAttachment)) {
			return false;
		}

		AccountEnvironmentAttachment accountEnvironmentAttachment =
			(AccountEnvironmentAttachment)obj;

		long primaryKey = accountEnvironmentAttachment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AccountEnvironmentAttachmentModelImpl
			accountEnvironmentAttachmentModelImpl = this;

		accountEnvironmentAttachmentModelImpl._setModifiedDate = false;

		accountEnvironmentAttachmentModelImpl._originalAccountEnvironmentId =
			accountEnvironmentAttachmentModelImpl._accountEnvironmentId;

		accountEnvironmentAttachmentModelImpl._setOriginalAccountEnvironmentId =
			false;

		accountEnvironmentAttachmentModelImpl._originalFileName =
			accountEnvironmentAttachmentModelImpl._fileName;

		accountEnvironmentAttachmentModelImpl._originalType =
			accountEnvironmentAttachmentModelImpl._type;

		accountEnvironmentAttachmentModelImpl._setOriginalType = false;

		accountEnvironmentAttachmentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AccountEnvironmentAttachment> toCacheModel() {
		AccountEnvironmentAttachmentCacheModel
			accountEnvironmentAttachmentCacheModel =
				new AccountEnvironmentAttachmentCacheModel();

		accountEnvironmentAttachmentCacheModel.accountEnvironmentAttachmentId =
			getAccountEnvironmentAttachmentId();

		accountEnvironmentAttachmentCacheModel.userId = getUserId();

		accountEnvironmentAttachmentCacheModel.userName = getUserName();

		String userName = accountEnvironmentAttachmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			accountEnvironmentAttachmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			accountEnvironmentAttachmentCacheModel.createDate =
				createDate.getTime();
		}
		else {
			accountEnvironmentAttachmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			accountEnvironmentAttachmentCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			accountEnvironmentAttachmentCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		accountEnvironmentAttachmentCacheModel.accountEnvironmentId =
			getAccountEnvironmentId();

		accountEnvironmentAttachmentCacheModel.fileName = getFileName();

		String fileName = accountEnvironmentAttachmentCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			accountEnvironmentAttachmentCacheModel.fileName = null;
		}

		accountEnvironmentAttachmentCacheModel.fileSize = getFileSize();

		accountEnvironmentAttachmentCacheModel.type = getType();

		return accountEnvironmentAttachmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AccountEnvironmentAttachment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AccountEnvironmentAttachment, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountEnvironmentAttachment, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(AccountEnvironmentAttachment)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AccountEnvironmentAttachment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AccountEnvironmentAttachment, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AccountEnvironmentAttachment, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(AccountEnvironmentAttachment)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, AccountEnvironmentAttachment>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _accountEnvironmentAttachmentId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _accountEnvironmentId;
	private long _originalAccountEnvironmentId;
	private boolean _setOriginalAccountEnvironmentId;
	private String _fileName;
	private String _originalFileName;
	private long _fileSize;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private long _columnBitmask;
	private AccountEnvironmentAttachment _escapedModel;

}