/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.customer.admin.model.impl;

import com.liferay.osb.customer.admin.model.AccountAttachment;
import com.liferay.osb.customer.admin.service.AccountAttachmentLocalServiceUtil;

/**
 * The extended model base implementation for the AccountAttachment service. Represents a row in the &quot;OSB_AccountAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountAttachmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountAttachmentImpl
 * @see AccountAttachment
 * @generated
 */
public abstract class AccountAttachmentBaseImpl
	extends AccountAttachmentModelImpl implements AccountAttachment {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account attachment model instance should use the <code>AccountAttachment</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AccountAttachmentLocalServiceUtil.addAccountAttachment(this);
		}
		else {
			AccountAttachmentLocalServiceUtil.updateAccountAttachment(this);
		}
	}

}