/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.admin.model.impl;

import com.liferay.osb.customer.admin.model.ProjectSolution;
import com.liferay.osb.customer.admin.model.ProjectSolutionModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProjectSolution service. Represents a row in the &quot;OSB_ProjectSolution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectSolutionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectSolutionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectSolutionImpl
 * @generated
 */
public class ProjectSolutionModelImpl
	extends BaseModelImpl<ProjectSolution> implements ProjectSolutionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project solution model instance should use the <code>ProjectSolution</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_ProjectSolution";

	public static final Object[][] TABLE_COLUMNS = {
		{"salesforceProjectKey", Types.VARCHAR}, {"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("salesforceProjectKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_ProjectSolution (salesforceProjectKey VARCHAR(75) not null primary key,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OSB_ProjectSolution";

	public static final String ORDER_BY_JPQL =
		" ORDER BY projectSolution.salesforceProjectKey ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_ProjectSolution.salesforceProjectKey ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.admin.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.customer.admin.model.ProjectSolution"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.admin.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.customer.admin.model.ProjectSolution"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.customer.admin.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.customer.admin.model.ProjectSolution"));

	public ProjectSolutionModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _salesforceProjectKey;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setSalesforceProjectKey(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _salesforceProjectKey;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ProjectSolution.class;
	}

	@Override
	public String getModelClassName() {
		return ProjectSolution.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProjectSolution, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProjectSolution, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectSolution, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProjectSolution)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProjectSolution, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProjectSolution, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProjectSolution)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProjectSolution, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProjectSolution, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ProjectSolution>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ProjectSolution.class.getClassLoader(), ProjectSolution.class,
			ModelWrapper.class);

		try {
			Constructor<ProjectSolution> constructor =
				(Constructor<ProjectSolution>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ProjectSolution, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProjectSolution, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProjectSolution, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ProjectSolution, Object>>();
		Map<String, BiConsumer<ProjectSolution, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ProjectSolution, ?>>();

		attributeGetterFunctions.put(
			"salesforceProjectKey",
			new Function<ProjectSolution, Object>() {

				@Override
				public Object apply(ProjectSolution projectSolution) {
					return projectSolution.getSalesforceProjectKey();
				}

			});
		attributeSetterBiConsumers.put(
			"salesforceProjectKey",
			new BiConsumer<ProjectSolution, Object>() {

				@Override
				public void accept(
					ProjectSolution projectSolution,
					Object salesforceProjectKeyObject) {

					projectSolution.setSalesforceProjectKey(
						(String)salesforceProjectKeyObject);
				}

			});
		attributeGetterFunctions.put(
			"value",
			new Function<ProjectSolution, Object>() {

				@Override
				public Object apply(ProjectSolution projectSolution) {
					return projectSolution.getValue();
				}

			});
		attributeSetterBiConsumers.put(
			"value",
			new BiConsumer<ProjectSolution, Object>() {

				@Override
				public void accept(
					ProjectSolution projectSolution, Object valueObject) {

					projectSolution.setValue((String)valueObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getSalesforceProjectKey() {
		if (_salesforceProjectKey == null) {
			return "";
		}
		else {
			return _salesforceProjectKey;
		}
	}

	@Override
	public void setSalesforceProjectKey(String salesforceProjectKey) {
		_salesforceProjectKey = salesforceProjectKey;
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@Override
	public ProjectSolution toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProjectSolution>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectSolutionImpl projectSolutionImpl = new ProjectSolutionImpl();

		projectSolutionImpl.setSalesforceProjectKey(getSalesforceProjectKey());
		projectSolutionImpl.setValue(getValue());

		projectSolutionImpl.resetOriginalValues();

		return projectSolutionImpl;
	}

	@Override
	public int compareTo(ProjectSolution projectSolution) {
		String primaryKey = projectSolution.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProjectSolution)) {
			return false;
		}

		ProjectSolution projectSolution = (ProjectSolution)object;

		String primaryKey = projectSolution.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ProjectSolution> toCacheModel() {
		ProjectSolutionCacheModel projectSolutionCacheModel =
			new ProjectSolutionCacheModel();

		projectSolutionCacheModel.salesforceProjectKey =
			getSalesforceProjectKey();

		String salesforceProjectKey =
			projectSolutionCacheModel.salesforceProjectKey;

		if ((salesforceProjectKey != null) &&
			(salesforceProjectKey.length() == 0)) {

			projectSolutionCacheModel.salesforceProjectKey = null;
		}

		projectSolutionCacheModel.value = getValue();

		String value = projectSolutionCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			projectSolutionCacheModel.value = null;
		}

		return projectSolutionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProjectSolution, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProjectSolution, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectSolution, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ProjectSolution)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ProjectSolution, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ProjectSolution, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProjectSolution, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ProjectSolution)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProjectSolution>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _salesforceProjectKey;
	private String _value;
	private ProjectSolution _escapedModel;

}