author=Liferay, Inc.
change-log=
licenses=DXP
long-description=
module-group-id=liferay
module-incremental-version=1
name=OSB EE
page-url=http://www.liferay.com
portal-dependency-tlds=c.tld
short-description=
tags=
Export-Package=com.liferay.osb.util