author=Liferay, Inc.
change-log=
Export-Package=\
    com.liferay.osb.exception,\
    com.liferay.osb.util,\
    com.liferay.osb.util.comparator
licenses=DXP
long-description=
module-group-id=liferay
module-incremental-version=1
name=OSB EE
page-url=http://www.liferay.com
portal-dependency-tlds=c.tld
short-description=
tags=