osb-continuous-integration-url=

required-ext=osb-ext

required-fix-packs-files=\
	https://raw.githubusercontent.com/liferay/lfrsite-team-able/master/www/_templates/portal/artifacts/liferay/fix-packs.txt,\
	https://raw.githubusercontent.com/liferay/lfrsite-team-able/master/www/uat/portal/artifacts/liferay/fix-packs.txt