author=Liferay, Inc.
change-log=
licenses=DXP
long-description=
module-group-id=liferay
module-incremental-version=1
name=OSB EE
page-url=http://www.liferay.com
portal-dependency-jars=\
    commons-lang.jar,\
    dom4j.jar,\
    jcommon.jar,\
    jdom.jar,\
    jfreechart.jar,\
    jstl-api.jar,\
    jstl-impl.jar,\
    lucene-core.jar,\
    poi.jar,\
    rome.jar
portal-dependency-tlds=c.tld
short-description=
tags=