author=Liferay, Inc.
change-log=
licenses=DXP
liferay-versions=7.0.0+,7.0.10+
long-description=
module-group-id=liferay
module-incremental-version=1
name=OSB Community
page-url=http://www.liferay.com
short-description=
tags=