#
# Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#

##
## You can override portal.properties by specifying your own settings in this
## file.
##
setup.wizard.enabled=false
portal.ctx=/
locale.default.request=true
plugin.notifications.enabled=false
company.default.web.id=axiell.com
company.security.auth.type=screenName
terms.of.use.required=false
users.reminder.queries.enabled=false
users.reminder.queries.custom.question.enabled=false
locales=en_GB,sv_SE,da_DK,de_DE,fi_FI,pl_PL,fo_FO,kl_GL
company.default.locale=en_GB
company.default.time.zone=GMT

# Must be enabled so the Installer can change its value
web.server.protocol=http

#
# Set this to true to enable the read count for document library files.
#
#dl.file.entry.read.count.enabled=false

#
# Set this to true to enable file rank for document library files.
#
#dl.file.rank.enabled=false

#
# Set the default admin password.
#
default.admin.password=sarenat

#
# Set the default admin screen name prefix.
#
default.admin.screen.name=support

#
# Set the default admin email address prefix.
#
default.admin.email.address.prefix=support

#
# Set the default admin first name.
#
default.admin.first.name=Support

#
# Set the default admin middle name.
#
default.admin.middle.name=

#
# Set the default admin last name.
#
default.admin.last.name=Administrator

#
# Input a list of reserved email addresses separated by \n characters.
#
admin.email.from.name=Nobody
admin.email.from.address=noreplay@axiell.com


company.security.strangers=false

# Set the maximum file size and valid file extensions for documents. A value
# of 0 for the maximum file size can be used to indicate unlimited file
# size. However, the maximum file size allowed is set in the property
# "com.liferay.portal.upload.UploadServletRequestImpl.max.size".
#
dl.file.max.size=4000000

#hibernate.show_sql=true
#
# Hypersonic
#
jdbc.default.driverClassName=org.hsqldb.jdbcDriver
jdbc.default.url=jdbc:hsqldb:${liferay.home}/data/hsqldb/lportal
jdbc.default.username=sa
jdbc.default.password=
#
# Oracle
#
#jdbc.default.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.default.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=arena-portal-db)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=arena-portal)))
#jdbc.default.username=portal1
#jdbc.default.password=parena1

#
# Set the properties used to create the Java Mail session. The property
# prefix "mail.session." will be removed before it is used to create the
# session object. These properties will only be read if the property
# "mail.session.jndi.name" is not set.
#
mail.session.mail.pop3.host=arena-mail-pop3
mail.session.mail.pop3.password=
mail.session.mail.pop3.port=110
mail.session.mail.pop3.user=
mail.session.mail.smtp.auth=false
mail.session.mail.smtp.host=arena-mail-smtp
mail.session.mail.smtp.password=
mail.session.mail.smtp.port=25
mail.session.mail.smtp.user=
mail.session.mail.store.protocol=pop3
mail.session.mail.transport.protocol=smtp

mime.types=\
        application/msword doc,\
        application/pdf pdf,\
        application/vnd.ms-excel xls,\
        application/vnd.ms-powerpoint ppt,\
        application/x-ms-wmp wmv,\
        application/x-shockwave-flash swf flv,\
        text/javascript js,\
        text/css css

mime.types.content.disposition.inline=flv,pdf,swf,wmv,css,txt,html,js,xml,xsl,gif,jpg,png,wmv

#
# Set to true if the Portlet authentication token check should be enabled, see http://www.liferay.com/community/wiki/-/wiki/Main/Authentication+Token
#
portlet.add.default.resource.check.enabled=false

#
# Set to true if the Portal authentication token check should be enabled, http://www.liferay.com/community/wiki/-/wiki/Main/Authentication+Token
#
auth.token.check.enabled=false

theme.css.fast.load=false
theme.images.fast.load=false

javascript.fast.load=false
javascript.log.enabled=false

#layout.template.cache.enabled=false

#combo.check.timestamp=true

#freemarker.engine.cache.storage=soft:1
#freemarker.engine.modification.check.interval=0

#openoffice.cache.enabled=false

#velocity.engine.resource.manager.cache.enabled=false

#com.liferay.portal.servlet.filters.cache.CacheFilter=false
#com.liferay.portal.servlet.filters.etag.ETagFilter=false
#com.liferay.portal.servlet.filters.header.HeaderFilter=false
#com.liferay.portal.servlet.filters.themepreview.ThemePreviewFilter=true