include-and-override=portlet-ext.properties

#
# If debug mode is enabled, consumers will not be attached to their queues.
# Instead, you can manually consume messages one at a time in the RabbitMQ
# admin portlet.
#
rabbitmq.debug.mode.enabled=false

rabbitmq.login.password=
rabbitmq.login.username=
rabbitmq.server.host=
rabbitmq.server.port=