##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        **/osb-loop-web/src/main/resources/META-INF/resources/dist/**

##
## Java Parser
##

    java.parser.enabled=true

##
## Git
##

    git.liferay.portal.branch=7.0.x

##
##  CheckStyle Properties
##

    checkstyle.JSONUtilCheck.enabled=false

    checkstyle.ListUtilCheck.enabled=false

    checkstyle.StaticBlockCheck.enabled=false

    checkstyle.VariableDeclarationAsUsedCheck.enabled=false

##
## Source Check Properties
##

    source.check.BNDSuiteCheck.enabled=false

    source.check.GradleDependenciesCheck.petra.dependencies=false

    source.check.GradleTestDependencyVersionCheck.enabled=false

    source.check.JavaAnonymousInnerClassCheck.enabled=false

    source.check.JavaComponentAnnotationsCheck.enabled=false

    source.check.JavaDeprecatedKernelClassesCheck.enabled=false

    source.check.JavaInternalPackageCheck.enabled=false

    source.check.PropertiesLanguageKeysCheck.enabled=false

    source.check.StringMethodsCheck.enabled=false