INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (1, 1, timestamp '${now-3h}', (SELECT id FROM EventDefinition WHERE name = 'assetClicked'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (2, 1, timestamp '${now-1h}', (SELECT id FROM EventDefinition WHERE name = 'blogClicked'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (3, 1, timestamp '${now-5h}', (SELECT id FROM EventDefinition WHERE name = 'fieldBlurred'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (4, 1, timestamp '${now-2h}', (SELECT id FROM EventDefinition WHERE name = 'formViewed'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (5, 1, timestamp '${now-26h}', (SELECT id FROM EventDefinition WHERE name = 'pageUnloaded'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (6, 1, timestamp '${now-30h}', (SELECT id FROM EventDefinition WHERE name = 'shared'), 1, '1');

INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 1, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 2, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 3, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 4, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 5, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 6, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 1, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 2, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 3, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 4, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 5, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 6, 'Liferay');