INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1001', 1, timestamp_trunc(timestamp '${now-8d}', DAY), 'addedToCart', '1', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1002', 1, timestamp_trunc(timestamp '${now-8d}', DAY), 'addedToCart', '2', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1003', 1, timestamp_trunc(timestamp '${now-7d}', DAY), 'addedToCart', '3', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1004', 1, timestamp_trunc(timestamp '${now-7d}', DAY), 'addedToCart', '4', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1005', 1, timestamp_trunc(timestamp '${now-6d}', DAY), 'addedToCart', '5', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1006', 1, timestamp_trunc(timestamp '${now-6d}', DAY), 'addedToCart', '6', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1007', 1, timestamp_trunc(timestamp '${now-5d}', DAY), 'addedToCart', '7', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1008', 1, timestamp_trunc(timestamp '${now-4d}', DAY), 'addedToCart', '8', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1009', 1, timestamp_trunc(timestamp '${now-3d}', DAY), 'addedToCart', '9', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1010', 1, timestamp_trunc(timestamp '${now-2d}', DAY), 'addedToCart', '10', '1');
INSERT INTO Event (id, channelId, eventDate, eventId, sessionId, userId) VALUES ('1011', 1, timestamp_trunc(timestamp '${now-1d}', DAY), 'addedToCart', '11', '1');

INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-8d}', DAY), '1001', 'itemName', 'Toy Robot');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-8d}', DAY), '1002', 'itemName', 'Cellular Phone');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-7d}', DAY), '1003', 'itemName', 'Cabinet');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-7d}', DAY), '1004', 'itemName', 'Dumbbells');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-6d}', DAY), '1005', 'itemName', 'Books');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-6d}', DAY), '1006', 'itemName', 'Hair Dye');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-5d}', DAY), '1007', 'itemName', 'Apples');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-4d}', DAY), '1008', 'itemName', 'Apples');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-3d}', DAY), '1009', 'itemName', 'Plates');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-2d}', DAY), '1010', 'itemName', 'Wheels');
INSERT INTO EventProperty (eventDate, id, name, value) VALUES(timestamp_trunc(timestamp '${now-1d}', DAY), '1011', 'itemName', 'Windshield Wipers');