INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (10, 1, timestamp '${now-3h}', (SELECT id FROM EventDefinition WHERE name = 'assetClicked'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (20, 1, timestamp '${now-1h}', (SELECT id FROM EventDefinition WHERE name = 'blogClicked'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (30, 1, timestamp '${now-5h}', (SELECT id FROM EventDefinition WHERE name = 'fieldBlurred'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (40, 1, timestamp '${now-2h}', (SELECT id FROM EventDefinition WHERE name = 'formViewed'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (50, 1, timestamp '${now-26h}', (SELECT id FROM EventDefinition WHERE name = 'pageUnloaded'), 1, '1');
INSERT INTO Event (id, channelId, eventDate, eventDefinitionId, individualId, sessionId) VALUES (60, 1, timestamp '${now-30h}', (SELECT id FROM EventDefinition WHERE name = 'shared'), 1, '1');

INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 10, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 20, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 30, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 40, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 50, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'canonicalUrl'), 60, 'http://liferay.com');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 10, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 20, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 30, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 40, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 50, 'Liferay');
INSERT INTO EventAttribute (eventAttributeDefinitionId, eventId, value) VALUES ((SELECT id FROM EventAttributeDefinition WHERE name = 'pageTitle'), 60, 'Liferay');