include-and-override=portlet-ext.properties

asset.entry.set.image.extensions=.gif,.jpeg,.jpg,.png

asset.entry.set.image.max.size[full]=2880x1800
asset.entry.set.image.max.size[mobile]=480x480
asset.entry.set.image.max.size[thumbnail]=128x128
asset.entry.set.image.max.size[web]=960x960

asset.entry.set.image.types=full,mobile,raw,thumbnail,web

asset.entry.set.shared.to.json.object.keys=entityClassNameId,entityClassPK,name,removable

geonames.url=

resource.actions.configs=resource-actions/default.xml