/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.community.meetup.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.community.meetup.model.MeetupGroup;
import com.liferay.osb.community.meetup.model.MeetupGroupModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MeetupGroup service. Represents a row in the &quot;OSBCommunity_MeetupGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MeetupGroupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeetupGroupImpl}.
 * </p>
 *
 * @author Jamie Sammons
 * @see MeetupGroupImpl
 * @see MeetupGroup
 * @see MeetupGroupModel
 * @generated
 */
@ProviderType
public class MeetupGroupModelImpl extends BaseModelImpl<MeetupGroup>
	implements MeetupGroupModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a meetup group model instance should use the {@link MeetupGroup} interface instead.
	 */
	public static final String TABLE_NAME = "OSBCommunity_MeetupGroup";
	public static final Object[][] TABLE_COLUMNS = {
			{ "meetupGroupId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "city", Types.VARCHAR },
			{ "memberCount", Types.INTEGER },
			{ "description", Types.VARCHAR },
			{ "url", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("meetupGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("memberCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OSBCommunity_MeetupGroup (meetupGroupId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,city VARCHAR(75) null,memberCount INTEGER,description VARCHAR(2000) null,url VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OSBCommunity_MeetupGroup";
	public static final String ORDER_BY_JPQL = " ORDER BY meetupGroup.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSBCommunity_MeetupGroup.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.community.meetup.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.community.meetup.model.MeetupGroup"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.community.meetup.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.community.meetup.model.MeetupGroup"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.community.meetup.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.community.meetup.model.MeetupGroup"));

	public MeetupGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _meetupGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMeetupGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _meetupGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MeetupGroup.class;
	}

	@Override
	public String getModelClassName() {
		return MeetupGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("meetupGroupId", getMeetupGroupId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("city", getCity());
		attributes.put("memberCount", getMemberCount());
		attributes.put("description", getDescription());
		attributes.put("url", getUrl());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long meetupGroupId = (Long)attributes.get("meetupGroupId");

		if (meetupGroupId != null) {
			setMeetupGroupId(meetupGroupId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String city = (String)attributes.get("city");

		if (city != null) {
			setCity(city);
		}

		Integer memberCount = (Integer)attributes.get("memberCount");

		if (memberCount != null) {
			setMemberCount(memberCount);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}
	}

	@Override
	public long getMeetupGroupId() {
		return _meetupGroupId;
	}

	@Override
	public void setMeetupGroupId(long meetupGroupId) {
		_meetupGroupId = meetupGroupId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getCity() {
		if (_city == null) {
			return StringPool.BLANK;
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		_city = city;
	}

	@Override
	public int getMemberCount() {
		return _memberCount;
	}

	@Override
	public void setMemberCount(int memberCount) {
		_memberCount = memberCount;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		_url = url;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MeetupGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MeetupGroup toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MeetupGroup)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MeetupGroupImpl meetupGroupImpl = new MeetupGroupImpl();

		meetupGroupImpl.setMeetupGroupId(getMeetupGroupId());
		meetupGroupImpl.setGroupId(getGroupId());
		meetupGroupImpl.setCompanyId(getCompanyId());
		meetupGroupImpl.setCreateDate(getCreateDate());
		meetupGroupImpl.setModifiedDate(getModifiedDate());
		meetupGroupImpl.setName(getName());
		meetupGroupImpl.setCity(getCity());
		meetupGroupImpl.setMemberCount(getMemberCount());
		meetupGroupImpl.setDescription(getDescription());
		meetupGroupImpl.setUrl(getUrl());

		meetupGroupImpl.resetOriginalValues();

		return meetupGroupImpl;
	}

	@Override
	public int compareTo(MeetupGroup meetupGroup) {
		int value = 0;

		value = getName().compareTo(meetupGroup.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MeetupGroup)) {
			return false;
		}

		MeetupGroup meetupGroup = (MeetupGroup)obj;

		long primaryKey = meetupGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MeetupGroupModelImpl meetupGroupModelImpl = this;

		meetupGroupModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<MeetupGroup> toCacheModel() {
		MeetupGroupCacheModel meetupGroupCacheModel = new MeetupGroupCacheModel();

		meetupGroupCacheModel.meetupGroupId = getMeetupGroupId();

		meetupGroupCacheModel.groupId = getGroupId();

		meetupGroupCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			meetupGroupCacheModel.createDate = createDate.getTime();
		}
		else {
			meetupGroupCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			meetupGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			meetupGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		meetupGroupCacheModel.name = getName();

		String name = meetupGroupCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			meetupGroupCacheModel.name = null;
		}

		meetupGroupCacheModel.city = getCity();

		String city = meetupGroupCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			meetupGroupCacheModel.city = null;
		}

		meetupGroupCacheModel.memberCount = getMemberCount();

		meetupGroupCacheModel.description = getDescription();

		String description = meetupGroupCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			meetupGroupCacheModel.description = null;
		}

		meetupGroupCacheModel.url = getUrl();

		String url = meetupGroupCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			meetupGroupCacheModel.url = null;
		}

		return meetupGroupCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{meetupGroupId=");
		sb.append(getMeetupGroupId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", city=");
		sb.append(getCity());
		sb.append(", memberCount=");
		sb.append(getMemberCount());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.community.meetup.model.MeetupGroup");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>meetupGroupId</column-name><column-value><![CDATA[");
		sb.append(getMeetupGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>city</column-name><column-value><![CDATA[");
		sb.append(getCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>memberCount</column-name><column-value><![CDATA[");
		sb.append(getMemberCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MeetupGroup.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MeetupGroup.class
		};
	private long _meetupGroupId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _city;
	private int _memberCount;
	private String _description;
	private String _url;
	private MeetupGroup _escapedModel;
}