/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.community.meetup.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osb.community.meetup.model.MeetupGroup;
import com.liferay.osb.community.meetup.service.MeetupGroupLocalServiceUtil;

/**
 * The extended model base implementation for the MeetupGroup service. Represents a row in the &quot;OSBCommunity_MeetupGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeetupGroupImpl}.
 * </p>
 *
 * @author Jamie Sammons
 * @see MeetupGroupImpl
 * @see MeetupGroup
 * @generated
 */
@ProviderType
public abstract class MeetupGroupBaseImpl extends MeetupGroupModelImpl
	implements MeetupGroup {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a meetup group model instance should use the {@link MeetupGroup} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MeetupGroupLocalServiceUtil.addMeetupGroup(this);
		}
		else {
			MeetupGroupLocalServiceUtil.updateMeetupGroup(this);
		}
	}
}