INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 1, timestamp '${now-1d}', 'USD', 321, 1, timestamp '${now}', timestamp '${now-2d}', null, 2, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (4, 11, timestamp '${now-2d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 2, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (7, 11, timestamp '${now-3d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 2, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 11, timestamp '${now}', 'USD', 123, 1, timestamp '${now}', timestamp '${now}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (2, 11, timestamp '${now}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-1d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 11, timestamp '${now-1d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-2d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 1, timestamp '${now-1d}', 'USD', 321, 1, timestamp '${now}', timestamp '${now-2d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (4, 11, timestamp '${now-2d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (7, 11, timestamp '${now-3d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 1, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 1, timestamp '${now-1d}', 'USD', 321, 1, timestamp '${now}', timestamp '${now-2d}', null, 0, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (4, 11, timestamp '${now-2d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 0, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (7, 11, timestamp '${now-3d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 0, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (10, 11, timestamp '${now-2d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 2, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (17, 11, timestamp '${now-3d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 2, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (10, 11, timestamp '${now-2d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (17, 11, timestamp '${now-3d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 1, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (18, 11, timestamp '${now-2d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 0, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (19, 11, timestamp '${now-3d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 0, '10.0');

INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (3, 11, timestamp '${now-7d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-7d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (3, 11, timestamp '${now-7d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-8d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (8, 11, timestamp '${now-8d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-9d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 11, timestamp '${now-10d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-11d}', null, 1, '10.0');
INSERT INTO `Order` (accountId, channelId, createDate, currencyCode, dataSourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 11, timestamp '${now-11d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-14d}', null, 1, '10.0');