/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.community.meetup.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MeetupGroup service. Represents a row in the &quot;OSBCommunity_MeetupGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.community.meetup.model.impl.MeetupGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.community.meetup.model.impl.MeetupGroupImpl}.
 * </p>
 *
 * @author Jamie Sammons
 * @see MeetupGroup
 * @see com.liferay.osb.community.meetup.model.impl.MeetupGroupImpl
 * @see com.liferay.osb.community.meetup.model.impl.MeetupGroupModelImpl
 * @generated
 */
@ProviderType
public interface MeetupGroupModel extends BaseModel<MeetupGroup>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a meetup group model instance should use the {@link MeetupGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this meetup group.
	 *
	 * @return the primary key of this meetup group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this meetup group.
	 *
	 * @param primaryKey the primary key of this meetup group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the meetup group ID of this meetup group.
	 *
	 * @return the meetup group ID of this meetup group
	 */
	public long getMeetupGroupId();

	/**
	 * Sets the meetup group ID of this meetup group.
	 *
	 * @param meetupGroupId the meetup group ID of this meetup group
	 */
	public void setMeetupGroupId(long meetupGroupId);

	/**
	 * Returns the group ID of this meetup group.
	 *
	 * @return the group ID of this meetup group
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this meetup group.
	 *
	 * @param groupId the group ID of this meetup group
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this meetup group.
	 *
	 * @return the company ID of this meetup group
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this meetup group.
	 *
	 * @param companyId the company ID of this meetup group
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this meetup group.
	 *
	 * @return the create date of this meetup group
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this meetup group.
	 *
	 * @param createDate the create date of this meetup group
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this meetup group.
	 *
	 * @return the modified date of this meetup group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this meetup group.
	 *
	 * @param modifiedDate the modified date of this meetup group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this meetup group.
	 *
	 * @return the name of this meetup group
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this meetup group.
	 *
	 * @param name the name of this meetup group
	 */
	public void setName(String name);

	/**
	 * Returns the city of this meetup group.
	 *
	 * @return the city of this meetup group
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this meetup group.
	 *
	 * @param city the city of this meetup group
	 */
	public void setCity(String city);

	/**
	 * Returns the member count of this meetup group.
	 *
	 * @return the member count of this meetup group
	 */
	public int getMemberCount();

	/**
	 * Sets the member count of this meetup group.
	 *
	 * @param memberCount the member count of this meetup group
	 */
	public void setMemberCount(int memberCount);

	/**
	 * Returns the description of this meetup group.
	 *
	 * @return the description of this meetup group
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this meetup group.
	 *
	 * @param description the description of this meetup group
	 */
	public void setDescription(String description);

	/**
	 * Returns the url of this meetup group.
	 *
	 * @return the url of this meetup group
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this meetup group.
	 *
	 * @param url the url of this meetup group
	 */
	public void setUrl(String url);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MeetupGroup meetupGroup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MeetupGroup> toCacheModel();

	@Override
	public MeetupGroup toEscapedModel();

	@Override
	public MeetupGroup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}