##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    run.outside.portal.excludes=\
        modules/private/apps/fabrica/fabrica-distribution-provider-grpc/src/main/java/com/liferay/fabrica/distribution/provider/grpc/client/ProxyClientBuilder.java