/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.AppPackage;
import com.liferay.osb.model.AppPackageModel;
import com.liferay.osb.model.AppPackageSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AppPackage service. Represents a row in the &quot;OSB_AppPackage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.AppPackageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppPackageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppPackageImpl
 * @see com.liferay.osb.model.AppPackage
 * @see com.liferay.osb.model.AppPackageModel
 * @generated
 */
@JSON(strict = true)
public class AppPackageModelImpl extends BaseModelImpl<AppPackage>
	implements AppPackageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a app package model instance should use the {@link com.liferay.osb.model.AppPackage} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_AppPackage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "appPackageId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "appEntryId", Types.BIGINT },
			{ "appVersionId", Types.BIGINT },
			{ "compatibility", Types.INTEGER },
			{ "compatibilityPlus", Types.BOOLEAN },
			{ "prepackaged", Types.BOOLEAN },
			{ "downloadCount", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_AppPackage (appPackageId LONG not null primary key,createDate DATE null,modifiedDate DATE null,appEntryId LONG,appVersionId LONG,compatibility INTEGER,compatibilityPlus BOOLEAN,prepackaged BOOLEAN,downloadCount INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_AppPackage";
	public static final String ORDER_BY_JPQL = " ORDER BY appPackage.compatibility ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_AppPackage.compatibility ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.AppPackage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.AppPackage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.AppPackage"),
			true);
	public static long APPVERSIONID_COLUMN_BITMASK = 1L;
	public static long COMPATIBILITY_COLUMN_BITMASK = 2L;
	public static long COMPATIBILITYPLUS_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AppPackage toModel(AppPackageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AppPackage model = new AppPackageImpl();

		model.setAppPackageId(soapModel.getAppPackageId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAppEntryId(soapModel.getAppEntryId());
		model.setAppVersionId(soapModel.getAppVersionId());
		model.setCompatibility(soapModel.getCompatibility());
		model.setCompatibilityPlus(soapModel.getCompatibilityPlus());
		model.setPrepackaged(soapModel.getPrepackaged());
		model.setDownloadCount(soapModel.getDownloadCount());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AppPackage> toModels(AppPackageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AppPackage> models = new ArrayList<AppPackage>(soapModels.length);

		for (AppPackageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.AppPackage"));

	public AppPackageModelImpl() {
	}

	public long getPrimaryKey() {
		return _appPackageId;
	}

	public void setPrimaryKey(long primaryKey) {
		setAppPackageId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_appPackageId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return AppPackage.class;
	}

	public String getModelClassName() {
		return AppPackage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("appPackageId", getAppPackageId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("appEntryId", getAppEntryId());
		attributes.put("appVersionId", getAppVersionId());
		attributes.put("compatibility", getCompatibility());
		attributes.put("compatibilityPlus", getCompatibilityPlus());
		attributes.put("prepackaged", getPrepackaged());
		attributes.put("downloadCount", getDownloadCount());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long appPackageId = (Long)attributes.get("appPackageId");

		if (appPackageId != null) {
			setAppPackageId(appPackageId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long appEntryId = (Long)attributes.get("appEntryId");

		if (appEntryId != null) {
			setAppEntryId(appEntryId);
		}

		Long appVersionId = (Long)attributes.get("appVersionId");

		if (appVersionId != null) {
			setAppVersionId(appVersionId);
		}

		Integer compatibility = (Integer)attributes.get("compatibility");

		if (compatibility != null) {
			setCompatibility(compatibility);
		}

		Boolean compatibilityPlus = (Boolean)attributes.get("compatibilityPlus");

		if (compatibilityPlus != null) {
			setCompatibilityPlus(compatibilityPlus);
		}

		Boolean prepackaged = (Boolean)attributes.get("prepackaged");

		if (prepackaged != null) {
			setPrepackaged(prepackaged);
		}

		Integer downloadCount = (Integer)attributes.get("downloadCount");

		if (downloadCount != null) {
			setDownloadCount(downloadCount);
		}
	}

	@JSON
	public long getAppPackageId() {
		return _appPackageId;
	}

	public void setAppPackageId(long appPackageId) {
		_appPackageId = appPackageId;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getAppEntryId() {
		return _appEntryId;
	}

	public void setAppEntryId(long appEntryId) {
		_appEntryId = appEntryId;
	}

	@JSON
	public long getAppVersionId() {
		return _appVersionId;
	}

	public void setAppVersionId(long appVersionId) {
		_columnBitmask |= APPVERSIONID_COLUMN_BITMASK;

		if (!_setOriginalAppVersionId) {
			_setOriginalAppVersionId = true;

			_originalAppVersionId = _appVersionId;
		}

		_appVersionId = appVersionId;
	}

	public long getOriginalAppVersionId() {
		return _originalAppVersionId;
	}

	@JSON
	public int getCompatibility() {
		return _compatibility;
	}

	public void setCompatibility(int compatibility) {
		_columnBitmask = -1L;

		if (!_setOriginalCompatibility) {
			_setOriginalCompatibility = true;

			_originalCompatibility = _compatibility;
		}

		_compatibility = compatibility;
	}

	public int getOriginalCompatibility() {
		return _originalCompatibility;
	}

	@JSON
	public boolean getCompatibilityPlus() {
		return _compatibilityPlus;
	}

	public boolean isCompatibilityPlus() {
		return _compatibilityPlus;
	}

	public void setCompatibilityPlus(boolean compatibilityPlus) {
		_columnBitmask |= COMPATIBILITYPLUS_COLUMN_BITMASK;

		if (!_setOriginalCompatibilityPlus) {
			_setOriginalCompatibilityPlus = true;

			_originalCompatibilityPlus = _compatibilityPlus;
		}

		_compatibilityPlus = compatibilityPlus;
	}

	public boolean getOriginalCompatibilityPlus() {
		return _originalCompatibilityPlus;
	}

	@JSON
	public boolean getPrepackaged() {
		return _prepackaged;
	}

	public boolean isPrepackaged() {
		return _prepackaged;
	}

	public void setPrepackaged(boolean prepackaged) {
		_prepackaged = prepackaged;
	}

	@JSON
	public int getDownloadCount() {
		return _downloadCount;
	}

	public void setDownloadCount(int downloadCount) {
		_downloadCount = downloadCount;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AppPackage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AppPackage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AppPackage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public AppPackage toUnescapedModel() {
		return (AppPackage)this;
	}

	@Override
	public Object clone() {
		AppPackageImpl appPackageImpl = new AppPackageImpl();

		appPackageImpl.setAppPackageId(getAppPackageId());
		appPackageImpl.setCreateDate(getCreateDate());
		appPackageImpl.setModifiedDate(getModifiedDate());
		appPackageImpl.setAppEntryId(getAppEntryId());
		appPackageImpl.setAppVersionId(getAppVersionId());
		appPackageImpl.setCompatibility(getCompatibility());
		appPackageImpl.setCompatibilityPlus(getCompatibilityPlus());
		appPackageImpl.setPrepackaged(getPrepackaged());
		appPackageImpl.setDownloadCount(getDownloadCount());

		appPackageImpl.resetOriginalValues();

		return appPackageImpl;
	}

	public int compareTo(AppPackage appPackage) {
		int value = 0;

		if (getCompatibility() < appPackage.getCompatibility()) {
			value = -1;
		}
		else if (getCompatibility() > appPackage.getCompatibility()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AppPackage)) {
			return false;
		}

		AppPackage appPackage = (AppPackage)obj;

		long primaryKey = appPackage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AppPackageModelImpl appPackageModelImpl = this;

		appPackageModelImpl._originalAppVersionId = appPackageModelImpl._appVersionId;

		appPackageModelImpl._setOriginalAppVersionId = false;

		appPackageModelImpl._originalCompatibility = appPackageModelImpl._compatibility;

		appPackageModelImpl._setOriginalCompatibility = false;

		appPackageModelImpl._originalCompatibilityPlus = appPackageModelImpl._compatibilityPlus;

		appPackageModelImpl._setOriginalCompatibilityPlus = false;

		appPackageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AppPackage> toCacheModel() {
		AppPackageCacheModel appPackageCacheModel = new AppPackageCacheModel();

		appPackageCacheModel.appPackageId = getAppPackageId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			appPackageCacheModel.createDate = createDate.getTime();
		}
		else {
			appPackageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appPackageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appPackageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appPackageCacheModel.appEntryId = getAppEntryId();

		appPackageCacheModel.appVersionId = getAppVersionId();

		appPackageCacheModel.compatibility = getCompatibility();

		appPackageCacheModel.compatibilityPlus = getCompatibilityPlus();

		appPackageCacheModel.prepackaged = getPrepackaged();

		appPackageCacheModel.downloadCount = getDownloadCount();

		return appPackageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{appPackageId=");
		sb.append(getAppPackageId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", appEntryId=");
		sb.append(getAppEntryId());
		sb.append(", appVersionId=");
		sb.append(getAppVersionId());
		sb.append(", compatibility=");
		sb.append(getCompatibility());
		sb.append(", compatibilityPlus=");
		sb.append(getCompatibilityPlus());
		sb.append(", prepackaged=");
		sb.append(getPrepackaged());
		sb.append(", downloadCount=");
		sb.append(getDownloadCount());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.AppPackage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>appPackageId</column-name><column-value><![CDATA[");
		sb.append(getAppPackageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>appEntryId</column-name><column-value><![CDATA[");
		sb.append(getAppEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>appVersionId</column-name><column-value><![CDATA[");
		sb.append(getAppVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>compatibility</column-name><column-value><![CDATA[");
		sb.append(getCompatibility());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>compatibilityPlus</column-name><column-value><![CDATA[");
		sb.append(getCompatibilityPlus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>prepackaged</column-name><column-value><![CDATA[");
		sb.append(getPrepackaged());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>downloadCount</column-name><column-value><![CDATA[");
		sb.append(getDownloadCount());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AppPackage.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			AppPackage.class
		};
	private long _appPackageId;
	private Date _createDate;
	private Date _modifiedDate;
	private long _appEntryId;
	private long _appVersionId;
	private long _originalAppVersionId;
	private boolean _setOriginalAppVersionId;
	private int _compatibility;
	private int _originalCompatibility;
	private boolean _setOriginalCompatibility;
	private boolean _compatibilityPlus;
	private boolean _originalCompatibilityPlus;
	private boolean _setOriginalCompatibilityPlus;
	private boolean _prepackaged;
	private int _downloadCount;
	private long _columnBitmask;
	private AppPackage _escapedModel;
}