/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.AssetStatsMonth;
import com.liferay.osb.model.AssetStatsMonthModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssetStatsMonth service. Represents a row in the &quot;OSB_AssetStatsMonth&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.AssetStatsMonthModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetStatsMonthImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetStatsMonthImpl
 * @see com.liferay.osb.model.AssetStatsMonth
 * @see com.liferay.osb.model.AssetStatsMonthModel
 * @generated
 */
public class AssetStatsMonthModelImpl extends BaseModelImpl<AssetStatsMonth>
	implements AssetStatsMonthModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset stats month model instance should use the {@link com.liferay.osb.model.AssetStatsMonth} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_AssetStatsMonth";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assetStatsMonthId", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "month", Types.INTEGER },
			{ "year", Types.INTEGER },
			{ "viewCount", Types.BIGINT },
			{ "downloadCount", Types.BIGINT },
			{ "purchaseCount", Types.BIGINT },
			{ "currencyCodeRevenues", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_AssetStatsMonth (assetStatsMonthId LONG not null primary key,classNameId LONG,classPK LONG,month INTEGER,year INTEGER,viewCount LONG,downloadCount LONG,purchaseCount LONG,currencyCodeRevenues VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_AssetStatsMonth";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.AssetStatsMonth"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.AssetStatsMonth"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.AssetStatsMonth"),
			true);
	public static long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static long CLASSPK_COLUMN_BITMASK = 2L;
	public static long MONTH_COLUMN_BITMASK = 4L;
	public static long YEAR_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.AssetStatsMonth"));

	public AssetStatsMonthModelImpl() {
	}

	public long getPrimaryKey() {
		return _assetStatsMonthId;
	}

	public void setPrimaryKey(long primaryKey) {
		setAssetStatsMonthId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_assetStatsMonthId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return AssetStatsMonth.class;
	}

	public String getModelClassName() {
		return AssetStatsMonth.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assetStatsMonthId", getAssetStatsMonthId());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("month", getMonth());
		attributes.put("year", getYear());
		attributes.put("viewCount", getViewCount());
		attributes.put("downloadCount", getDownloadCount());
		attributes.put("purchaseCount", getPurchaseCount());
		attributes.put("currencyCodeRevenues", getCurrencyCodeRevenues());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assetStatsMonthId = (Long)attributes.get("assetStatsMonthId");

		if (assetStatsMonthId != null) {
			setAssetStatsMonthId(assetStatsMonthId);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		Integer month = (Integer)attributes.get("month");

		if (month != null) {
			setMonth(month);
		}

		Integer year = (Integer)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		Long viewCount = (Long)attributes.get("viewCount");

		if (viewCount != null) {
			setViewCount(viewCount);
		}

		Long downloadCount = (Long)attributes.get("downloadCount");

		if (downloadCount != null) {
			setDownloadCount(downloadCount);
		}

		Long purchaseCount = (Long)attributes.get("purchaseCount");

		if (purchaseCount != null) {
			setPurchaseCount(purchaseCount);
		}

		String currencyCodeRevenues = (String)attributes.get(
				"currencyCodeRevenues");

		if (currencyCodeRevenues != null) {
			setCurrencyCodeRevenues(currencyCodeRevenues);
		}
	}

	public long getAssetStatsMonthId() {
		return _assetStatsMonthId;
	}

	public void setAssetStatsMonthId(long assetStatsMonthId) {
		_assetStatsMonthId = assetStatsMonthId;
	}

	public String getClassName() {
		if (getClassNameId() <= 0) {
			return StringPool.BLANK;
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	public long getClassNameId() {
		return _classNameId;
	}

	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	public long getClassPK() {
		return _classPK;
	}

	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	public int getMonth() {
		return _month;
	}

	public void setMonth(int month) {
		_columnBitmask |= MONTH_COLUMN_BITMASK;

		if (!_setOriginalMonth) {
			_setOriginalMonth = true;

			_originalMonth = _month;
		}

		_month = month;
	}

	public int getOriginalMonth() {
		return _originalMonth;
	}

	public int getYear() {
		return _year;
	}

	public void setYear(int year) {
		_columnBitmask |= YEAR_COLUMN_BITMASK;

		if (!_setOriginalYear) {
			_setOriginalYear = true;

			_originalYear = _year;
		}

		_year = year;
	}

	public int getOriginalYear() {
		return _originalYear;
	}

	public long getViewCount() {
		return _viewCount;
	}

	public void setViewCount(long viewCount) {
		_viewCount = viewCount;
	}

	public long getDownloadCount() {
		return _downloadCount;
	}

	public void setDownloadCount(long downloadCount) {
		_downloadCount = downloadCount;
	}

	public long getPurchaseCount() {
		return _purchaseCount;
	}

	public void setPurchaseCount(long purchaseCount) {
		_purchaseCount = purchaseCount;
	}

	public String getCurrencyCodeRevenues() {
		if (_currencyCodeRevenues == null) {
			return StringPool.BLANK;
		}
		else {
			return _currencyCodeRevenues;
		}
	}

	public void setCurrencyCodeRevenues(String currencyCodeRevenues) {
		_currencyCodeRevenues = currencyCodeRevenues;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AssetStatsMonth.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetStatsMonth toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssetStatsMonth)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public AssetStatsMonth toUnescapedModel() {
		return (AssetStatsMonth)this;
	}

	@Override
	public Object clone() {
		AssetStatsMonthImpl assetStatsMonthImpl = new AssetStatsMonthImpl();

		assetStatsMonthImpl.setAssetStatsMonthId(getAssetStatsMonthId());
		assetStatsMonthImpl.setClassNameId(getClassNameId());
		assetStatsMonthImpl.setClassPK(getClassPK());
		assetStatsMonthImpl.setMonth(getMonth());
		assetStatsMonthImpl.setYear(getYear());
		assetStatsMonthImpl.setViewCount(getViewCount());
		assetStatsMonthImpl.setDownloadCount(getDownloadCount());
		assetStatsMonthImpl.setPurchaseCount(getPurchaseCount());
		assetStatsMonthImpl.setCurrencyCodeRevenues(getCurrencyCodeRevenues());

		assetStatsMonthImpl.resetOriginalValues();

		return assetStatsMonthImpl;
	}

	public int compareTo(AssetStatsMonth assetStatsMonth) {
		long primaryKey = assetStatsMonth.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssetStatsMonth)) {
			return false;
		}

		AssetStatsMonth assetStatsMonth = (AssetStatsMonth)obj;

		long primaryKey = assetStatsMonth.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AssetStatsMonthModelImpl assetStatsMonthModelImpl = this;

		assetStatsMonthModelImpl._originalClassNameId = assetStatsMonthModelImpl._classNameId;

		assetStatsMonthModelImpl._setOriginalClassNameId = false;

		assetStatsMonthModelImpl._originalClassPK = assetStatsMonthModelImpl._classPK;

		assetStatsMonthModelImpl._setOriginalClassPK = false;

		assetStatsMonthModelImpl._originalMonth = assetStatsMonthModelImpl._month;

		assetStatsMonthModelImpl._setOriginalMonth = false;

		assetStatsMonthModelImpl._originalYear = assetStatsMonthModelImpl._year;

		assetStatsMonthModelImpl._setOriginalYear = false;

		assetStatsMonthModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetStatsMonth> toCacheModel() {
		AssetStatsMonthCacheModel assetStatsMonthCacheModel = new AssetStatsMonthCacheModel();

		assetStatsMonthCacheModel.assetStatsMonthId = getAssetStatsMonthId();

		assetStatsMonthCacheModel.classNameId = getClassNameId();

		assetStatsMonthCacheModel.classPK = getClassPK();

		assetStatsMonthCacheModel.month = getMonth();

		assetStatsMonthCacheModel.year = getYear();

		assetStatsMonthCacheModel.viewCount = getViewCount();

		assetStatsMonthCacheModel.downloadCount = getDownloadCount();

		assetStatsMonthCacheModel.purchaseCount = getPurchaseCount();

		assetStatsMonthCacheModel.currencyCodeRevenues = getCurrencyCodeRevenues();

		String currencyCodeRevenues = assetStatsMonthCacheModel.currencyCodeRevenues;

		if ((currencyCodeRevenues != null) &&
				(currencyCodeRevenues.length() == 0)) {
			assetStatsMonthCacheModel.currencyCodeRevenues = null;
		}

		return assetStatsMonthCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{assetStatsMonthId=");
		sb.append(getAssetStatsMonthId());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", month=");
		sb.append(getMonth());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", viewCount=");
		sb.append(getViewCount());
		sb.append(", downloadCount=");
		sb.append(getDownloadCount());
		sb.append(", purchaseCount=");
		sb.append(getPurchaseCount());
		sb.append(", currencyCodeRevenues=");
		sb.append(getCurrencyCodeRevenues());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.AssetStatsMonth");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assetStatsMonthId</column-name><column-value><![CDATA[");
		sb.append(getAssetStatsMonthId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>month</column-name><column-value><![CDATA[");
		sb.append(getMonth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viewCount</column-name><column-value><![CDATA[");
		sb.append(getViewCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>downloadCount</column-name><column-value><![CDATA[");
		sb.append(getDownloadCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>purchaseCount</column-name><column-value><![CDATA[");
		sb.append(getPurchaseCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currencyCodeRevenues</column-name><column-value><![CDATA[");
		sb.append(getCurrencyCodeRevenues());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AssetStatsMonth.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			AssetStatsMonth.class
		};
	private long _assetStatsMonthId;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private int _month;
	private int _originalMonth;
	private boolean _setOriginalMonth;
	private int _year;
	private int _originalYear;
	private boolean _setOriginalYear;
	private long _viewCount;
	private long _downloadCount;
	private long _purchaseCount;
	private String _currencyCodeRevenues;
	private long _columnBitmask;
	private AssetStatsMonth _escapedModel;
}