/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.ContractAudit;
import com.liferay.osb.model.ContractAuditModel;
import com.liferay.osb.model.ContractAuditSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ContractAudit service. Represents a row in the &quot;OSB_ContractAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.ContractAuditModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContractAuditImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContractAuditImpl
 * @see com.liferay.osb.model.ContractAudit
 * @see com.liferay.osb.model.ContractAuditModel
 * @generated
 */
@JSON(strict = true)
public class ContractAuditModelImpl extends BaseModelImpl<ContractAudit>
	implements ContractAuditModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contract audit model instance should use the {@link com.liferay.osb.model.ContractAudit} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_ContractAudit";
	public static final Object[][] TABLE_COLUMNS = {
			{ "contractAuditId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "userEmailAddress", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "contractEntryId", Types.BIGINT },
			{ "signatoryClassNameId", Types.BIGINT },
			{ "signatoryClassPK", Types.BIGINT },
			{ "productClassNameId", Types.BIGINT },
			{ "productClassPK", Types.BIGINT },
			{ "type_", Types.VARCHAR },
			{ "languageId", Types.VARCHAR },
			{ "version", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_ContractAudit (contractAuditId LONG not null primary key,userId LONG,userName VARCHAR(75) null,userEmailAddress VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,contractEntryId LONG,signatoryClassNameId LONG,signatoryClassPK LONG,productClassNameId LONG,productClassPK LONG,type_ VARCHAR(75) null,languageId VARCHAR(75) null,version INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_ContractAudit";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.ContractAudit"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.ContractAudit"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.ContractAudit"),
			true);
	public static long CONTRACTENTRYID_COLUMN_BITMASK = 1L;
	public static long SIGNATORYCLASSNAMEID_COLUMN_BITMASK = 2L;
	public static long SIGNATORYCLASSPK_COLUMN_BITMASK = 4L;
	public static long USERID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ContractAudit toModel(ContractAuditSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ContractAudit model = new ContractAuditImpl();

		model.setContractAuditId(soapModel.getContractAuditId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setUserEmailAddress(soapModel.getUserEmailAddress());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setContractEntryId(soapModel.getContractEntryId());
		model.setSignatoryClassNameId(soapModel.getSignatoryClassNameId());
		model.setSignatoryClassPK(soapModel.getSignatoryClassPK());
		model.setProductClassNameId(soapModel.getProductClassNameId());
		model.setProductClassPK(soapModel.getProductClassPK());
		model.setType(soapModel.getType());
		model.setLanguageId(soapModel.getLanguageId());
		model.setVersion(soapModel.getVersion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ContractAudit> toModels(ContractAuditSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ContractAudit> models = new ArrayList<ContractAudit>(soapModels.length);

		for (ContractAuditSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.ContractAudit"));

	public ContractAuditModelImpl() {
	}

	public long getPrimaryKey() {
		return _contractAuditId;
	}

	public void setPrimaryKey(long primaryKey) {
		setContractAuditId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_contractAuditId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ContractAudit.class;
	}

	public String getModelClassName() {
		return ContractAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("contractAuditId", getContractAuditId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("userEmailAddress", getUserEmailAddress());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("contractEntryId", getContractEntryId());
		attributes.put("signatoryClassNameId", getSignatoryClassNameId());
		attributes.put("signatoryClassPK", getSignatoryClassPK());
		attributes.put("productClassNameId", getProductClassNameId());
		attributes.put("productClassPK", getProductClassPK());
		attributes.put("type", getType());
		attributes.put("languageId", getLanguageId());
		attributes.put("version", getVersion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long contractAuditId = (Long)attributes.get("contractAuditId");

		if (contractAuditId != null) {
			setContractAuditId(contractAuditId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		String userEmailAddress = (String)attributes.get("userEmailAddress");

		if (userEmailAddress != null) {
			setUserEmailAddress(userEmailAddress);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long contractEntryId = (Long)attributes.get("contractEntryId");

		if (contractEntryId != null) {
			setContractEntryId(contractEntryId);
		}

		Long signatoryClassNameId = (Long)attributes.get("signatoryClassNameId");

		if (signatoryClassNameId != null) {
			setSignatoryClassNameId(signatoryClassNameId);
		}

		Long signatoryClassPK = (Long)attributes.get("signatoryClassPK");

		if (signatoryClassPK != null) {
			setSignatoryClassPK(signatoryClassPK);
		}

		Long productClassNameId = (Long)attributes.get("productClassNameId");

		if (productClassNameId != null) {
			setProductClassNameId(productClassNameId);
		}

		Long productClassPK = (Long)attributes.get("productClassPK");

		if (productClassPK != null) {
			setProductClassPK(productClassPK);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		Integer version = (Integer)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}
	}

	@JSON
	public long getContractAuditId() {
		return _contractAuditId;
	}

	public void setContractAuditId(long contractAuditId) {
		_contractAuditId = contractAuditId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public String getUserEmailAddress() {
		if (_userEmailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _userEmailAddress;
		}
	}

	public void setUserEmailAddress(String userEmailAddress) {
		_userEmailAddress = userEmailAddress;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getContractEntryId() {
		return _contractEntryId;
	}

	public void setContractEntryId(long contractEntryId) {
		_columnBitmask |= CONTRACTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalContractEntryId) {
			_setOriginalContractEntryId = true;

			_originalContractEntryId = _contractEntryId;
		}

		_contractEntryId = contractEntryId;
	}

	public long getOriginalContractEntryId() {
		return _originalContractEntryId;
	}

	@JSON
	public long getSignatoryClassNameId() {
		return _signatoryClassNameId;
	}

	public void setSignatoryClassNameId(long signatoryClassNameId) {
		_columnBitmask |= SIGNATORYCLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalSignatoryClassNameId) {
			_setOriginalSignatoryClassNameId = true;

			_originalSignatoryClassNameId = _signatoryClassNameId;
		}

		_signatoryClassNameId = signatoryClassNameId;
	}

	public long getOriginalSignatoryClassNameId() {
		return _originalSignatoryClassNameId;
	}

	@JSON
	public long getSignatoryClassPK() {
		return _signatoryClassPK;
	}

	public void setSignatoryClassPK(long signatoryClassPK) {
		_columnBitmask |= SIGNATORYCLASSPK_COLUMN_BITMASK;

		if (!_setOriginalSignatoryClassPK) {
			_setOriginalSignatoryClassPK = true;

			_originalSignatoryClassPK = _signatoryClassPK;
		}

		_signatoryClassPK = signatoryClassPK;
	}

	public long getOriginalSignatoryClassPK() {
		return _originalSignatoryClassPK;
	}

	@JSON
	public long getProductClassNameId() {
		return _productClassNameId;
	}

	public void setProductClassNameId(long productClassNameId) {
		_productClassNameId = productClassNameId;
	}

	@JSON
	public long getProductClassPK() {
		return _productClassPK;
	}

	public void setProductClassPK(long productClassPK) {
		_productClassPK = productClassPK;
	}

	@JSON
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	public void setType(String type) {
		_type = type;
	}

	@JSON
	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	public void setLanguageId(String languageId) {
		_languageId = languageId;
	}

	@JSON
	public int getVersion() {
		return _version;
	}

	public void setVersion(int version) {
		_version = version;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ContractAudit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContractAudit toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ContractAudit)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public ContractAudit toUnescapedModel() {
		return (ContractAudit)this;
	}

	@Override
	public Object clone() {
		ContractAuditImpl contractAuditImpl = new ContractAuditImpl();

		contractAuditImpl.setContractAuditId(getContractAuditId());
		contractAuditImpl.setUserId(getUserId());
		contractAuditImpl.setUserName(getUserName());
		contractAuditImpl.setUserEmailAddress(getUserEmailAddress());
		contractAuditImpl.setCreateDate(getCreateDate());
		contractAuditImpl.setModifiedDate(getModifiedDate());
		contractAuditImpl.setContractEntryId(getContractEntryId());
		contractAuditImpl.setSignatoryClassNameId(getSignatoryClassNameId());
		contractAuditImpl.setSignatoryClassPK(getSignatoryClassPK());
		contractAuditImpl.setProductClassNameId(getProductClassNameId());
		contractAuditImpl.setProductClassPK(getProductClassPK());
		contractAuditImpl.setType(getType());
		contractAuditImpl.setLanguageId(getLanguageId());
		contractAuditImpl.setVersion(getVersion());

		contractAuditImpl.resetOriginalValues();

		return contractAuditImpl;
	}

	public int compareTo(ContractAudit contractAudit) {
		long primaryKey = contractAudit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ContractAudit)) {
			return false;
		}

		ContractAudit contractAudit = (ContractAudit)obj;

		long primaryKey = contractAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ContractAuditModelImpl contractAuditModelImpl = this;

		contractAuditModelImpl._originalUserId = contractAuditModelImpl._userId;

		contractAuditModelImpl._setOriginalUserId = false;

		contractAuditModelImpl._originalContractEntryId = contractAuditModelImpl._contractEntryId;

		contractAuditModelImpl._setOriginalContractEntryId = false;

		contractAuditModelImpl._originalSignatoryClassNameId = contractAuditModelImpl._signatoryClassNameId;

		contractAuditModelImpl._setOriginalSignatoryClassNameId = false;

		contractAuditModelImpl._originalSignatoryClassPK = contractAuditModelImpl._signatoryClassPK;

		contractAuditModelImpl._setOriginalSignatoryClassPK = false;

		contractAuditModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ContractAudit> toCacheModel() {
		ContractAuditCacheModel contractAuditCacheModel = new ContractAuditCacheModel();

		contractAuditCacheModel.contractAuditId = getContractAuditId();

		contractAuditCacheModel.userId = getUserId();

		contractAuditCacheModel.userName = getUserName();

		String userName = contractAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contractAuditCacheModel.userName = null;
		}

		contractAuditCacheModel.userEmailAddress = getUserEmailAddress();

		String userEmailAddress = contractAuditCacheModel.userEmailAddress;

		if ((userEmailAddress != null) && (userEmailAddress.length() == 0)) {
			contractAuditCacheModel.userEmailAddress = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			contractAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			contractAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contractAuditCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			contractAuditCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contractAuditCacheModel.contractEntryId = getContractEntryId();

		contractAuditCacheModel.signatoryClassNameId = getSignatoryClassNameId();

		contractAuditCacheModel.signatoryClassPK = getSignatoryClassPK();

		contractAuditCacheModel.productClassNameId = getProductClassNameId();

		contractAuditCacheModel.productClassPK = getProductClassPK();

		contractAuditCacheModel.type = getType();

		String type = contractAuditCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			contractAuditCacheModel.type = null;
		}

		contractAuditCacheModel.languageId = getLanguageId();

		String languageId = contractAuditCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			contractAuditCacheModel.languageId = null;
		}

		contractAuditCacheModel.version = getVersion();

		return contractAuditCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{contractAuditId=");
		sb.append(getContractAuditId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", userEmailAddress=");
		sb.append(getUserEmailAddress());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", contractEntryId=");
		sb.append(getContractEntryId());
		sb.append(", signatoryClassNameId=");
		sb.append(getSignatoryClassNameId());
		sb.append(", signatoryClassPK=");
		sb.append(getSignatoryClassPK());
		sb.append(", productClassNameId=");
		sb.append(getProductClassNameId());
		sb.append(", productClassPK=");
		sb.append(getProductClassPK());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.ContractAudit");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>contractAuditId</column-name><column-value><![CDATA[");
		sb.append(getContractAuditId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userEmailAddress</column-name><column-value><![CDATA[");
		sb.append(getUserEmailAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contractEntryId</column-name><column-value><![CDATA[");
		sb.append(getContractEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signatoryClassNameId</column-name><column-value><![CDATA[");
		sb.append(getSignatoryClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signatoryClassPK</column-name><column-value><![CDATA[");
		sb.append(getSignatoryClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productClassNameId</column-name><column-value><![CDATA[");
		sb.append(getProductClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productClassPK</column-name><column-value><![CDATA[");
		sb.append(getProductClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ContractAudit.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ContractAudit.class
		};
	private long _contractAuditId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private String _userEmailAddress;
	private Date _createDate;
	private Date _modifiedDate;
	private long _contractEntryId;
	private long _originalContractEntryId;
	private boolean _setOriginalContractEntryId;
	private long _signatoryClassNameId;
	private long _originalSignatoryClassNameId;
	private boolean _setOriginalSignatoryClassNameId;
	private long _signatoryClassPK;
	private long _originalSignatoryClassPK;
	private boolean _setOriginalSignatoryClassPK;
	private long _productClassNameId;
	private long _productClassPK;
	private String _type;
	private String _languageId;
	private int _version;
	private long _columnBitmask;
	private ContractAudit _escapedModel;
}