/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.CurrencyEntry;
import com.liferay.osb.model.CurrencyEntryModel;
import com.liferay.osb.model.CurrencyEntrySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CurrencyEntry service. Represents a row in the &quot;OSB_CurrencyEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.CurrencyEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CurrencyEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CurrencyEntryImpl
 * @see com.liferay.osb.model.CurrencyEntry
 * @see com.liferay.osb.model.CurrencyEntryModel
 * @generated
 */
@JSON(strict = true)
public class CurrencyEntryModelImpl extends BaseModelImpl<CurrencyEntry>
	implements CurrencyEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a currency entry model instance should use the {@link com.liferay.osb.model.CurrencyEntry} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_CurrencyEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "currencyEntryId", Types.BIGINT },
			{ "countryId", Types.BIGINT },
			{ "currencyCode", Types.VARCHAR },
			{ "marketplaceEnabled", Types.BOOLEAN },
			{ "marketplaceMinPrice", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_CurrencyEntry (currencyEntryId LONG not null primary key,countryId LONG,currencyCode VARCHAR(75) null,marketplaceEnabled BOOLEAN,marketplaceMinPrice DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table OSB_CurrencyEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY currencyEntry.currencyCode ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_CurrencyEntry.currencyCode ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.CurrencyEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.CurrencyEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.CurrencyEntry"),
			true);
	public static long CURRENCYCODE_COLUMN_BITMASK = 1L;
	public static long MARKETPLACEENABLED_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CurrencyEntry toModel(CurrencyEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CurrencyEntry model = new CurrencyEntryImpl();

		model.setCurrencyEntryId(soapModel.getCurrencyEntryId());
		model.setCountryId(soapModel.getCountryId());
		model.setCurrencyCode(soapModel.getCurrencyCode());
		model.setMarketplaceEnabled(soapModel.getMarketplaceEnabled());
		model.setMarketplaceMinPrice(soapModel.getMarketplaceMinPrice());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CurrencyEntry> toModels(CurrencyEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CurrencyEntry> models = new ArrayList<CurrencyEntry>(soapModels.length);

		for (CurrencyEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.CurrencyEntry"));

	public CurrencyEntryModelImpl() {
	}

	public long getPrimaryKey() {
		return _currencyEntryId;
	}

	public void setPrimaryKey(long primaryKey) {
		setCurrencyEntryId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_currencyEntryId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CurrencyEntry.class;
	}

	public String getModelClassName() {
		return CurrencyEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("currencyEntryId", getCurrencyEntryId());
		attributes.put("countryId", getCountryId());
		attributes.put("currencyCode", getCurrencyCode());
		attributes.put("marketplaceEnabled", getMarketplaceEnabled());
		attributes.put("marketplaceMinPrice", getMarketplaceMinPrice());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long currencyEntryId = (Long)attributes.get("currencyEntryId");

		if (currencyEntryId != null) {
			setCurrencyEntryId(currencyEntryId);
		}

		Long countryId = (Long)attributes.get("countryId");

		if (countryId != null) {
			setCountryId(countryId);
		}

		String currencyCode = (String)attributes.get("currencyCode");

		if (currencyCode != null) {
			setCurrencyCode(currencyCode);
		}

		Boolean marketplaceEnabled = (Boolean)attributes.get(
				"marketplaceEnabled");

		if (marketplaceEnabled != null) {
			setMarketplaceEnabled(marketplaceEnabled);
		}

		Double marketplaceMinPrice = (Double)attributes.get(
				"marketplaceMinPrice");

		if (marketplaceMinPrice != null) {
			setMarketplaceMinPrice(marketplaceMinPrice);
		}
	}

	@JSON
	public long getCurrencyEntryId() {
		return _currencyEntryId;
	}

	public void setCurrencyEntryId(long currencyEntryId) {
		_currencyEntryId = currencyEntryId;
	}

	@JSON
	public long getCountryId() {
		return _countryId;
	}

	public void setCountryId(long countryId) {
		_countryId = countryId;
	}

	@JSON
	public String getCurrencyCode() {
		if (_currencyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _currencyCode;
		}
	}

	public void setCurrencyCode(String currencyCode) {
		_columnBitmask = -1L;

		if (_originalCurrencyCode == null) {
			_originalCurrencyCode = _currencyCode;
		}

		_currencyCode = currencyCode;
	}

	public String getOriginalCurrencyCode() {
		return GetterUtil.getString(_originalCurrencyCode);
	}

	@JSON
	public boolean getMarketplaceEnabled() {
		return _marketplaceEnabled;
	}

	public boolean isMarketplaceEnabled() {
		return _marketplaceEnabled;
	}

	public void setMarketplaceEnabled(boolean marketplaceEnabled) {
		_columnBitmask |= MARKETPLACEENABLED_COLUMN_BITMASK;

		if (!_setOriginalMarketplaceEnabled) {
			_setOriginalMarketplaceEnabled = true;

			_originalMarketplaceEnabled = _marketplaceEnabled;
		}

		_marketplaceEnabled = marketplaceEnabled;
	}

	public boolean getOriginalMarketplaceEnabled() {
		return _originalMarketplaceEnabled;
	}

	@JSON
	public double getMarketplaceMinPrice() {
		return _marketplaceMinPrice;
	}

	public void setMarketplaceMinPrice(double marketplaceMinPrice) {
		_marketplaceMinPrice = marketplaceMinPrice;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CurrencyEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CurrencyEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CurrencyEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public CurrencyEntry toUnescapedModel() {
		return (CurrencyEntry)this;
	}

	@Override
	public Object clone() {
		CurrencyEntryImpl currencyEntryImpl = new CurrencyEntryImpl();

		currencyEntryImpl.setCurrencyEntryId(getCurrencyEntryId());
		currencyEntryImpl.setCountryId(getCountryId());
		currencyEntryImpl.setCurrencyCode(getCurrencyCode());
		currencyEntryImpl.setMarketplaceEnabled(getMarketplaceEnabled());
		currencyEntryImpl.setMarketplaceMinPrice(getMarketplaceMinPrice());

		currencyEntryImpl.resetOriginalValues();

		return currencyEntryImpl;
	}

	public int compareTo(CurrencyEntry currencyEntry) {
		int value = 0;

		value = getCurrencyCode().compareTo(currencyEntry.getCurrencyCode());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CurrencyEntry)) {
			return false;
		}

		CurrencyEntry currencyEntry = (CurrencyEntry)obj;

		long primaryKey = currencyEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CurrencyEntryModelImpl currencyEntryModelImpl = this;

		currencyEntryModelImpl._originalCurrencyCode = currencyEntryModelImpl._currencyCode;

		currencyEntryModelImpl._originalMarketplaceEnabled = currencyEntryModelImpl._marketplaceEnabled;

		currencyEntryModelImpl._setOriginalMarketplaceEnabled = false;

		currencyEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CurrencyEntry> toCacheModel() {
		CurrencyEntryCacheModel currencyEntryCacheModel = new CurrencyEntryCacheModel();

		currencyEntryCacheModel.currencyEntryId = getCurrencyEntryId();

		currencyEntryCacheModel.countryId = getCountryId();

		currencyEntryCacheModel.currencyCode = getCurrencyCode();

		String currencyCode = currencyEntryCacheModel.currencyCode;

		if ((currencyCode != null) && (currencyCode.length() == 0)) {
			currencyEntryCacheModel.currencyCode = null;
		}

		currencyEntryCacheModel.marketplaceEnabled = getMarketplaceEnabled();

		currencyEntryCacheModel.marketplaceMinPrice = getMarketplaceMinPrice();

		return currencyEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{currencyEntryId=");
		sb.append(getCurrencyEntryId());
		sb.append(", countryId=");
		sb.append(getCountryId());
		sb.append(", currencyCode=");
		sb.append(getCurrencyCode());
		sb.append(", marketplaceEnabled=");
		sb.append(getMarketplaceEnabled());
		sb.append(", marketplaceMinPrice=");
		sb.append(getMarketplaceMinPrice());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.CurrencyEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>currencyEntryId</column-name><column-value><![CDATA[");
		sb.append(getCurrencyEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countryId</column-name><column-value><![CDATA[");
		sb.append(getCountryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currencyCode</column-name><column-value><![CDATA[");
		sb.append(getCurrencyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marketplaceEnabled</column-name><column-value><![CDATA[");
		sb.append(getMarketplaceEnabled());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marketplaceMinPrice</column-name><column-value><![CDATA[");
		sb.append(getMarketplaceMinPrice());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CurrencyEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CurrencyEntry.class
		};
	private long _currencyEntryId;
	private long _countryId;
	private String _currencyCode;
	private String _originalCurrencyCode;
	private boolean _marketplaceEnabled;
	private boolean _originalMarketplaceEnabled;
	private boolean _setOriginalMarketplaceEnabled;
	private double _marketplaceMinPrice;
	private long _columnBitmask;
	private CurrencyEntry _escapedModel;
}