/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.LCSSubscriptionEntry;
import com.liferay.osb.model.LCSSubscriptionEntryModel;
import com.liferay.osb.model.LCSSubscriptionEntrySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LCSSubscriptionEntry service. Represents a row in the &quot;OSB_LCSSubscriptionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.LCSSubscriptionEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LCSSubscriptionEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LCSSubscriptionEntryImpl
 * @see com.liferay.osb.model.LCSSubscriptionEntry
 * @see com.liferay.osb.model.LCSSubscriptionEntryModel
 * @generated
 */
@JSON(strict = true)
public class LCSSubscriptionEntryModelImpl extends BaseModelImpl<LCSSubscriptionEntry>
	implements LCSSubscriptionEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a l c s subscription entry model instance should use the {@link com.liferay.osb.model.LCSSubscriptionEntry} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_LCSSubscriptionEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "lcsSubscriptionEntryId", Types.BIGINT },
			{ "lcsProjectId", Types.BIGINT },
			{ "product", Types.VARCHAR },
			{ "productVersion", Types.INTEGER },
			{ "type_", Types.VARCHAR },
			{ "platform", Types.VARCHAR },
			{ "platformVersion", Types.VARCHAR },
			{ "serversAllowed", Types.INTEGER },
			{ "serversUsed", Types.INTEGER },
			{ "instanceSize", Types.INTEGER },
			{ "startDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP },
			{ "supportStartDate", Types.TIMESTAMP },
			{ "supportEndDate", Types.TIMESTAMP },
			{ "actualPrice", Types.DOUBLE },
			{ "currencyCode", Types.VARCHAR },
			{ "active_", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_LCSSubscriptionEntry (lcsSubscriptionEntryId LONG not null primary key,lcsProjectId LONG,product VARCHAR(75) null,productVersion INTEGER,type_ VARCHAR(75) null,platform VARCHAR(75) null,platformVersion VARCHAR(75) null,serversAllowed INTEGER,serversUsed INTEGER,instanceSize INTEGER,startDate DATE null,endDate DATE null,supportStartDate DATE null,supportEndDate DATE null,actualPrice DOUBLE,currencyCode VARCHAR(75) null,active_ BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table OSB_LCSSubscriptionEntry";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.LCSSubscriptionEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.LCSSubscriptionEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LCSSubscriptionEntry toModel(
		LCSSubscriptionEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LCSSubscriptionEntry model = new LCSSubscriptionEntryImpl();

		model.setLcsSubscriptionEntryId(soapModel.getLcsSubscriptionEntryId());
		model.setLcsProjectId(soapModel.getLcsProjectId());
		model.setProduct(soapModel.getProduct());
		model.setProductVersion(soapModel.getProductVersion());
		model.setType(soapModel.getType());
		model.setPlatform(soapModel.getPlatform());
		model.setPlatformVersion(soapModel.getPlatformVersion());
		model.setServersAllowed(soapModel.getServersAllowed());
		model.setServersUsed(soapModel.getServersUsed());
		model.setInstanceSize(soapModel.getInstanceSize());
		model.setStartDate(soapModel.getStartDate());
		model.setEndDate(soapModel.getEndDate());
		model.setSupportStartDate(soapModel.getSupportStartDate());
		model.setSupportEndDate(soapModel.getSupportEndDate());
		model.setActualPrice(soapModel.getActualPrice());
		model.setCurrencyCode(soapModel.getCurrencyCode());
		model.setActive(soapModel.getActive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LCSSubscriptionEntry> toModels(
		LCSSubscriptionEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LCSSubscriptionEntry> models = new ArrayList<LCSSubscriptionEntry>(soapModels.length);

		for (LCSSubscriptionEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.LCSSubscriptionEntry"));

	public LCSSubscriptionEntryModelImpl() {
	}

	public long getPrimaryKey() {
		return _lcsSubscriptionEntryId;
	}

	public void setPrimaryKey(long primaryKey) {
		setLcsSubscriptionEntryId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_lcsSubscriptionEntryId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return LCSSubscriptionEntry.class;
	}

	public String getModelClassName() {
		return LCSSubscriptionEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("lcsSubscriptionEntryId", getLcsSubscriptionEntryId());
		attributes.put("lcsProjectId", getLcsProjectId());
		attributes.put("product", getProduct());
		attributes.put("productVersion", getProductVersion());
		attributes.put("type", getType());
		attributes.put("platform", getPlatform());
		attributes.put("platformVersion", getPlatformVersion());
		attributes.put("serversAllowed", getServersAllowed());
		attributes.put("serversUsed", getServersUsed());
		attributes.put("instanceSize", getInstanceSize());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());
		attributes.put("supportStartDate", getSupportStartDate());
		attributes.put("supportEndDate", getSupportEndDate());
		attributes.put("actualPrice", getActualPrice());
		attributes.put("currencyCode", getCurrencyCode());
		attributes.put("active", getActive());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long lcsSubscriptionEntryId = (Long)attributes.get(
				"lcsSubscriptionEntryId");

		if (lcsSubscriptionEntryId != null) {
			setLcsSubscriptionEntryId(lcsSubscriptionEntryId);
		}

		Long lcsProjectId = (Long)attributes.get("lcsProjectId");

		if (lcsProjectId != null) {
			setLcsProjectId(lcsProjectId);
		}

		String product = (String)attributes.get("product");

		if (product != null) {
			setProduct(product);
		}

		Integer productVersion = (Integer)attributes.get("productVersion");

		if (productVersion != null) {
			setProductVersion(productVersion);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		String platform = (String)attributes.get("platform");

		if (platform != null) {
			setPlatform(platform);
		}

		String platformVersion = (String)attributes.get("platformVersion");

		if (platformVersion != null) {
			setPlatformVersion(platformVersion);
		}

		Integer serversAllowed = (Integer)attributes.get("serversAllowed");

		if (serversAllowed != null) {
			setServersAllowed(serversAllowed);
		}

		Integer serversUsed = (Integer)attributes.get("serversUsed");

		if (serversUsed != null) {
			setServersUsed(serversUsed);
		}

		Integer instanceSize = (Integer)attributes.get("instanceSize");

		if (instanceSize != null) {
			setInstanceSize(instanceSize);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		Date supportStartDate = (Date)attributes.get("supportStartDate");

		if (supportStartDate != null) {
			setSupportStartDate(supportStartDate);
		}

		Date supportEndDate = (Date)attributes.get("supportEndDate");

		if (supportEndDate != null) {
			setSupportEndDate(supportEndDate);
		}

		Double actualPrice = (Double)attributes.get("actualPrice");

		if (actualPrice != null) {
			setActualPrice(actualPrice);
		}

		String currencyCode = (String)attributes.get("currencyCode");

		if (currencyCode != null) {
			setCurrencyCode(currencyCode);
		}

		Boolean active = (Boolean)attributes.get("active");

		if (active != null) {
			setActive(active);
		}
	}

	@JSON
	public long getLcsSubscriptionEntryId() {
		return _lcsSubscriptionEntryId;
	}

	public void setLcsSubscriptionEntryId(long lcsSubscriptionEntryId) {
		_lcsSubscriptionEntryId = lcsSubscriptionEntryId;
	}

	@JSON
	public long getLcsProjectId() {
		return _lcsProjectId;
	}

	public void setLcsProjectId(long lcsProjectId) {
		_lcsProjectId = lcsProjectId;
	}

	@JSON
	public String getProduct() {
		if (_product == null) {
			return StringPool.BLANK;
		}
		else {
			return _product;
		}
	}

	public void setProduct(String product) {
		_product = product;
	}

	@JSON
	public int getProductVersion() {
		return _productVersion;
	}

	public void setProductVersion(int productVersion) {
		_productVersion = productVersion;
	}

	@JSON
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	public void setType(String type) {
		_type = type;
	}

	@JSON
	public String getPlatform() {
		if (_platform == null) {
			return StringPool.BLANK;
		}
		else {
			return _platform;
		}
	}

	public void setPlatform(String platform) {
		_platform = platform;
	}

	@JSON
	public String getPlatformVersion() {
		if (_platformVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _platformVersion;
		}
	}

	public void setPlatformVersion(String platformVersion) {
		_platformVersion = platformVersion;
	}

	@JSON
	public int getServersAllowed() {
		return _serversAllowed;
	}

	public void setServersAllowed(int serversAllowed) {
		_serversAllowed = serversAllowed;
	}

	@JSON
	public int getServersUsed() {
		return _serversUsed;
	}

	public void setServersUsed(int serversUsed) {
		_serversUsed = serversUsed;
	}

	@JSON
	public int getInstanceSize() {
		return _instanceSize;
	}

	public void setInstanceSize(int instanceSize) {
		_instanceSize = instanceSize;
	}

	@JSON
	public Date getStartDate() {
		return _startDate;
	}

	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	public Date getEndDate() {
		return _endDate;
	}

	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@JSON
	public Date getSupportStartDate() {
		return _supportStartDate;
	}

	public void setSupportStartDate(Date supportStartDate) {
		_supportStartDate = supportStartDate;
	}

	@JSON
	public Date getSupportEndDate() {
		return _supportEndDate;
	}

	public void setSupportEndDate(Date supportEndDate) {
		_supportEndDate = supportEndDate;
	}

	@JSON
	public double getActualPrice() {
		return _actualPrice;
	}

	public void setActualPrice(double actualPrice) {
		_actualPrice = actualPrice;
	}

	@JSON
	public String getCurrencyCode() {
		if (_currencyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _currencyCode;
		}
	}

	public void setCurrencyCode(String currencyCode) {
		_currencyCode = currencyCode;
	}

	@JSON
	public boolean getActive() {
		return _active;
	}

	public boolean isActive() {
		return _active;
	}

	public void setActive(boolean active) {
		_active = active;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LCSSubscriptionEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LCSSubscriptionEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LCSSubscriptionEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public LCSSubscriptionEntry toUnescapedModel() {
		return (LCSSubscriptionEntry)this;
	}

	@Override
	public Object clone() {
		LCSSubscriptionEntryImpl lcsSubscriptionEntryImpl = new LCSSubscriptionEntryImpl();

		lcsSubscriptionEntryImpl.setLcsSubscriptionEntryId(getLcsSubscriptionEntryId());
		lcsSubscriptionEntryImpl.setLcsProjectId(getLcsProjectId());
		lcsSubscriptionEntryImpl.setProduct(getProduct());
		lcsSubscriptionEntryImpl.setProductVersion(getProductVersion());
		lcsSubscriptionEntryImpl.setType(getType());
		lcsSubscriptionEntryImpl.setPlatform(getPlatform());
		lcsSubscriptionEntryImpl.setPlatformVersion(getPlatformVersion());
		lcsSubscriptionEntryImpl.setServersAllowed(getServersAllowed());
		lcsSubscriptionEntryImpl.setServersUsed(getServersUsed());
		lcsSubscriptionEntryImpl.setInstanceSize(getInstanceSize());
		lcsSubscriptionEntryImpl.setStartDate(getStartDate());
		lcsSubscriptionEntryImpl.setEndDate(getEndDate());
		lcsSubscriptionEntryImpl.setSupportStartDate(getSupportStartDate());
		lcsSubscriptionEntryImpl.setSupportEndDate(getSupportEndDate());
		lcsSubscriptionEntryImpl.setActualPrice(getActualPrice());
		lcsSubscriptionEntryImpl.setCurrencyCode(getCurrencyCode());
		lcsSubscriptionEntryImpl.setActive(getActive());

		lcsSubscriptionEntryImpl.resetOriginalValues();

		return lcsSubscriptionEntryImpl;
	}

	public int compareTo(LCSSubscriptionEntry lcsSubscriptionEntry) {
		long primaryKey = lcsSubscriptionEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LCSSubscriptionEntry)) {
			return false;
		}

		LCSSubscriptionEntry lcsSubscriptionEntry = (LCSSubscriptionEntry)obj;

		long primaryKey = lcsSubscriptionEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LCSSubscriptionEntry> toCacheModel() {
		LCSSubscriptionEntryCacheModel lcsSubscriptionEntryCacheModel = new LCSSubscriptionEntryCacheModel();

		lcsSubscriptionEntryCacheModel.lcsSubscriptionEntryId = getLcsSubscriptionEntryId();

		lcsSubscriptionEntryCacheModel.lcsProjectId = getLcsProjectId();

		lcsSubscriptionEntryCacheModel.product = getProduct();

		String product = lcsSubscriptionEntryCacheModel.product;

		if ((product != null) && (product.length() == 0)) {
			lcsSubscriptionEntryCacheModel.product = null;
		}

		lcsSubscriptionEntryCacheModel.productVersion = getProductVersion();

		lcsSubscriptionEntryCacheModel.type = getType();

		String type = lcsSubscriptionEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			lcsSubscriptionEntryCacheModel.type = null;
		}

		lcsSubscriptionEntryCacheModel.platform = getPlatform();

		String platform = lcsSubscriptionEntryCacheModel.platform;

		if ((platform != null) && (platform.length() == 0)) {
			lcsSubscriptionEntryCacheModel.platform = null;
		}

		lcsSubscriptionEntryCacheModel.platformVersion = getPlatformVersion();

		String platformVersion = lcsSubscriptionEntryCacheModel.platformVersion;

		if ((platformVersion != null) && (platformVersion.length() == 0)) {
			lcsSubscriptionEntryCacheModel.platformVersion = null;
		}

		lcsSubscriptionEntryCacheModel.serversAllowed = getServersAllowed();

		lcsSubscriptionEntryCacheModel.serversUsed = getServersUsed();

		lcsSubscriptionEntryCacheModel.instanceSize = getInstanceSize();

		Date startDate = getStartDate();

		if (startDate != null) {
			lcsSubscriptionEntryCacheModel.startDate = startDate.getTime();
		}
		else {
			lcsSubscriptionEntryCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			lcsSubscriptionEntryCacheModel.endDate = endDate.getTime();
		}
		else {
			lcsSubscriptionEntryCacheModel.endDate = Long.MIN_VALUE;
		}

		Date supportStartDate = getSupportStartDate();

		if (supportStartDate != null) {
			lcsSubscriptionEntryCacheModel.supportStartDate = supportStartDate.getTime();
		}
		else {
			lcsSubscriptionEntryCacheModel.supportStartDate = Long.MIN_VALUE;
		}

		Date supportEndDate = getSupportEndDate();

		if (supportEndDate != null) {
			lcsSubscriptionEntryCacheModel.supportEndDate = supportEndDate.getTime();
		}
		else {
			lcsSubscriptionEntryCacheModel.supportEndDate = Long.MIN_VALUE;
		}

		lcsSubscriptionEntryCacheModel.actualPrice = getActualPrice();

		lcsSubscriptionEntryCacheModel.currencyCode = getCurrencyCode();

		String currencyCode = lcsSubscriptionEntryCacheModel.currencyCode;

		if ((currencyCode != null) && (currencyCode.length() == 0)) {
			lcsSubscriptionEntryCacheModel.currencyCode = null;
		}

		lcsSubscriptionEntryCacheModel.active = getActive();

		return lcsSubscriptionEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(35);

		sb.append("{lcsSubscriptionEntryId=");
		sb.append(getLcsSubscriptionEntryId());
		sb.append(", lcsProjectId=");
		sb.append(getLcsProjectId());
		sb.append(", product=");
		sb.append(getProduct());
		sb.append(", productVersion=");
		sb.append(getProductVersion());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", platform=");
		sb.append(getPlatform());
		sb.append(", platformVersion=");
		sb.append(getPlatformVersion());
		sb.append(", serversAllowed=");
		sb.append(getServersAllowed());
		sb.append(", serversUsed=");
		sb.append(getServersUsed());
		sb.append(", instanceSize=");
		sb.append(getInstanceSize());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", supportStartDate=");
		sb.append(getSupportStartDate());
		sb.append(", supportEndDate=");
		sb.append(getSupportEndDate());
		sb.append(", actualPrice=");
		sb.append(getActualPrice());
		sb.append(", currencyCode=");
		sb.append(getCurrencyCode());
		sb.append(", active=");
		sb.append(getActive());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(55);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.LCSSubscriptionEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>lcsSubscriptionEntryId</column-name><column-value><![CDATA[");
		sb.append(getLcsSubscriptionEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lcsProjectId</column-name><column-value><![CDATA[");
		sb.append(getLcsProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>product</column-name><column-value><![CDATA[");
		sb.append(getProduct());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productVersion</column-name><column-value><![CDATA[");
		sb.append(getProductVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>platform</column-name><column-value><![CDATA[");
		sb.append(getPlatform());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>platformVersion</column-name><column-value><![CDATA[");
		sb.append(getPlatformVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serversAllowed</column-name><column-value><![CDATA[");
		sb.append(getServersAllowed());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serversUsed</column-name><column-value><![CDATA[");
		sb.append(getServersUsed());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>instanceSize</column-name><column-value><![CDATA[");
		sb.append(getInstanceSize());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportStartDate</column-name><column-value><![CDATA[");
		sb.append(getSupportStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportEndDate</column-name><column-value><![CDATA[");
		sb.append(getSupportEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actualPrice</column-name><column-value><![CDATA[");
		sb.append(getActualPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currencyCode</column-name><column-value><![CDATA[");
		sb.append(getCurrencyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LCSSubscriptionEntry.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LCSSubscriptionEntry.class
		};
	private long _lcsSubscriptionEntryId;
	private long _lcsProjectId;
	private String _product;
	private int _productVersion;
	private String _type;
	private String _platform;
	private String _platformVersion;
	private int _serversAllowed;
	private int _serversUsed;
	private int _instanceSize;
	private Date _startDate;
	private Date _endDate;
	private Date _supportStartDate;
	private Date _supportEndDate;
	private double _actualPrice;
	private String _currencyCode;
	private boolean _active;
	private LCSSubscriptionEntry _escapedModel;
}