/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.LicenseKeySet;
import com.liferay.osb.model.LicenseKeySetModel;
import com.liferay.osb.model.LicenseKeySetSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LicenseKeySet service. Represents a row in the &quot;OSB_LicenseKeySet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.LicenseKeySetModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseKeySetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseKeySetImpl
 * @see com.liferay.osb.model.LicenseKeySet
 * @see com.liferay.osb.model.LicenseKeySetModel
 * @generated
 */
@JSON(strict = true)
public class LicenseKeySetModelImpl extends BaseModelImpl<LicenseKeySet>
	implements LicenseKeySetModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license key set model instance should use the {@link com.liferay.osb.model.LicenseKeySet} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_LicenseKeySet";
	public static final Object[][] TABLE_COLUMNS = {
			{ "licenseKeySetId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "accountEntryId", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_LicenseKeySet (licenseKeySetId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,accountEntryId LONG,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_LicenseKeySet";
	public static final String ORDER_BY_JPQL = " ORDER BY licenseKeySet.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_LicenseKeySet.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.LicenseKeySet"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.LicenseKeySet"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.LicenseKeySet"),
			true);
	public static long ACCOUNTENTRYID_COLUMN_BITMASK = 1L;
	public static long NAME_COLUMN_BITMASK = 2L;
	public static long USERID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LicenseKeySet toModel(LicenseKeySetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LicenseKeySet model = new LicenseKeySetImpl();

		model.setLicenseKeySetId(soapModel.getLicenseKeySetId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAccountEntryId(soapModel.getAccountEntryId());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LicenseKeySet> toModels(LicenseKeySetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LicenseKeySet> models = new ArrayList<LicenseKeySet>(soapModels.length);

		for (LicenseKeySetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.LicenseKeySet"));

	public LicenseKeySetModelImpl() {
	}

	public long getPrimaryKey() {
		return _licenseKeySetId;
	}

	public void setPrimaryKey(long primaryKey) {
		setLicenseKeySetId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_licenseKeySetId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return LicenseKeySet.class;
	}

	public String getModelClassName() {
		return LicenseKeySet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("licenseKeySetId", getLicenseKeySetId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("accountEntryId", getAccountEntryId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long licenseKeySetId = (Long)attributes.get("licenseKeySetId");

		if (licenseKeySetId != null) {
			setLicenseKeySetId(licenseKeySetId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long accountEntryId = (Long)attributes.get("accountEntryId");

		if (accountEntryId != null) {
			setAccountEntryId(accountEntryId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@JSON
	public long getLicenseKeySetId() {
		return _licenseKeySetId;
	}

	public void setLicenseKeySetId(long licenseKeySetId) {
		_licenseKeySetId = licenseKeySetId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getAccountEntryId() {
		return _accountEntryId;
	}

	public void setAccountEntryId(long accountEntryId) {
		_columnBitmask |= ACCOUNTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAccountEntryId) {
			_setOriginalAccountEntryId = true;

			_originalAccountEntryId = _accountEntryId;
		}

		_accountEntryId = accountEntryId;
	}

	public long getOriginalAccountEntryId() {
		return _originalAccountEntryId;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LicenseKeySet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LicenseKeySet toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LicenseKeySet)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public LicenseKeySet toUnescapedModel() {
		return (LicenseKeySet)this;
	}

	@Override
	public Object clone() {
		LicenseKeySetImpl licenseKeySetImpl = new LicenseKeySetImpl();

		licenseKeySetImpl.setLicenseKeySetId(getLicenseKeySetId());
		licenseKeySetImpl.setUserId(getUserId());
		licenseKeySetImpl.setUserName(getUserName());
		licenseKeySetImpl.setCreateDate(getCreateDate());
		licenseKeySetImpl.setModifiedDate(getModifiedDate());
		licenseKeySetImpl.setAccountEntryId(getAccountEntryId());
		licenseKeySetImpl.setName(getName());

		licenseKeySetImpl.resetOriginalValues();

		return licenseKeySetImpl;
	}

	public int compareTo(LicenseKeySet licenseKeySet) {
		int value = 0;

		value = getName().toLowerCase()
					.compareTo(licenseKeySet.getName().toLowerCase());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LicenseKeySet)) {
			return false;
		}

		LicenseKeySet licenseKeySet = (LicenseKeySet)obj;

		long primaryKey = licenseKeySet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		LicenseKeySetModelImpl licenseKeySetModelImpl = this;

		licenseKeySetModelImpl._originalUserId = licenseKeySetModelImpl._userId;

		licenseKeySetModelImpl._setOriginalUserId = false;

		licenseKeySetModelImpl._originalAccountEntryId = licenseKeySetModelImpl._accountEntryId;

		licenseKeySetModelImpl._setOriginalAccountEntryId = false;

		licenseKeySetModelImpl._originalName = licenseKeySetModelImpl._name;

		licenseKeySetModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LicenseKeySet> toCacheModel() {
		LicenseKeySetCacheModel licenseKeySetCacheModel = new LicenseKeySetCacheModel();

		licenseKeySetCacheModel.licenseKeySetId = getLicenseKeySetId();

		licenseKeySetCacheModel.userId = getUserId();

		licenseKeySetCacheModel.userName = getUserName();

		String userName = licenseKeySetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			licenseKeySetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			licenseKeySetCacheModel.createDate = createDate.getTime();
		}
		else {
			licenseKeySetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			licenseKeySetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			licenseKeySetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		licenseKeySetCacheModel.accountEntryId = getAccountEntryId();

		licenseKeySetCacheModel.name = getName();

		String name = licenseKeySetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			licenseKeySetCacheModel.name = null;
		}

		return licenseKeySetCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{licenseKeySetId=");
		sb.append(getLicenseKeySetId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", accountEntryId=");
		sb.append(getAccountEntryId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.LicenseKeySet");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>licenseKeySetId</column-name><column-value><![CDATA[");
		sb.append(getLicenseKeySetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountEntryId</column-name><column-value><![CDATA[");
		sb.append(getAccountEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = LicenseKeySet.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			LicenseKeySet.class
		};
	private long _licenseKeySetId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _accountEntryId;
	private long _originalAccountEntryId;
	private boolean _setOriginalAccountEntryId;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private LicenseKeySet _escapedModel;
}