/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.model.LicenseEntry;
import com.liferay.osb.model.LicenseEntryModel;
import com.liferay.osb.model.LicenseEntrySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LicenseEntry service. Represents a row in the &quot;OSB_LicenseEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LicenseEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LicenseEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LicenseEntryImpl
 * @see LicenseEntry
 * @see LicenseEntryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LicenseEntryModelImpl extends BaseModelImpl<LicenseEntry>
	implements LicenseEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a license entry model instance should use the {@link LicenseEntry} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_LicenseEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "licenseEntryId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "productEntryId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "type_", Types.VARCHAR },
			{ "portalVersionMin", Types.INTEGER },
			{ "portalVersionMax", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("licenseEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("productEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("portalVersionMin", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("portalVersionMax", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_LicenseEntry (licenseEntryId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,productEntryId LONG,name VARCHAR(75) null,type_ VARCHAR(75) null,portalVersionMin INTEGER,portalVersionMax INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_LicenseEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY licenseEntry.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_LicenseEntry.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.LicenseEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.LicenseEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.LicenseEntry"),
			true);
	public static final long PORTALVERSIONMIN_COLUMN_BITMASK = 1L;
	public static final long PRODUCTENTRYID_COLUMN_BITMASK = 2L;
	public static final long TYPE_COLUMN_BITMASK = 4L;
	public static final long NAME_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LicenseEntry toModel(LicenseEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LicenseEntry model = new LicenseEntryImpl();

		model.setLicenseEntryId(soapModel.getLicenseEntryId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProductEntryId(soapModel.getProductEntryId());
		model.setName(soapModel.getName());
		model.setType(soapModel.getType());
		model.setPortalVersionMin(soapModel.getPortalVersionMin());
		model.setPortalVersionMax(soapModel.getPortalVersionMax());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LicenseEntry> toModels(LicenseEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LicenseEntry> models = new ArrayList<LicenseEntry>(soapModels.length);

		for (LicenseEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.LicenseEntry"));

	public LicenseEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _licenseEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLicenseEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _licenseEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LicenseEntry.class;
	}

	@Override
	public String getModelClassName() {
		return LicenseEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("licenseEntryId", getLicenseEntryId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("productEntryId", getProductEntryId());
		attributes.put("name", getName());
		attributes.put("type", getType());
		attributes.put("portalVersionMin", getPortalVersionMin());
		attributes.put("portalVersionMax", getPortalVersionMax());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long licenseEntryId = (Long)attributes.get("licenseEntryId");

		if (licenseEntryId != null) {
			setLicenseEntryId(licenseEntryId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long productEntryId = (Long)attributes.get("productEntryId");

		if (productEntryId != null) {
			setProductEntryId(productEntryId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Integer portalVersionMin = (Integer)attributes.get("portalVersionMin");

		if (portalVersionMin != null) {
			setPortalVersionMin(portalVersionMin);
		}

		Integer portalVersionMax = (Integer)attributes.get("portalVersionMax");

		if (portalVersionMax != null) {
			setPortalVersionMax(portalVersionMax);
		}
	}

	@JSON
	@Override
	public long getLicenseEntryId() {
		return _licenseEntryId;
	}

	@Override
	public void setLicenseEntryId(long licenseEntryId) {
		_licenseEntryId = licenseEntryId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getProductEntryId() {
		return _productEntryId;
	}

	@Override
	public void setProductEntryId(long productEntryId) {
		_columnBitmask |= PRODUCTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalProductEntryId) {
			_setOriginalProductEntryId = true;

			_originalProductEntryId = _productEntryId;
		}

		_productEntryId = productEntryId;
	}

	public long getOriginalProductEntryId() {
		return _originalProductEntryId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		_name = name;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (_originalType == null) {
			_originalType = _type;
		}

		_type = type;
	}

	public String getOriginalType() {
		return GetterUtil.getString(_originalType);
	}

	@JSON
	@Override
	public int getPortalVersionMin() {
		return _portalVersionMin;
	}

	@Override
	public void setPortalVersionMin(int portalVersionMin) {
		_columnBitmask |= PORTALVERSIONMIN_COLUMN_BITMASK;

		if (!_setOriginalPortalVersionMin) {
			_setOriginalPortalVersionMin = true;

			_originalPortalVersionMin = _portalVersionMin;
		}

		_portalVersionMin = portalVersionMin;
	}

	public int getOriginalPortalVersionMin() {
		return _originalPortalVersionMin;
	}

	@JSON
	@Override
	public int getPortalVersionMax() {
		return _portalVersionMax;
	}

	@Override
	public void setPortalVersionMax(int portalVersionMax) {
		_portalVersionMax = portalVersionMax;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LicenseEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LicenseEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LicenseEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LicenseEntryImpl licenseEntryImpl = new LicenseEntryImpl();

		licenseEntryImpl.setLicenseEntryId(getLicenseEntryId());
		licenseEntryImpl.setUserId(getUserId());
		licenseEntryImpl.setUserName(getUserName());
		licenseEntryImpl.setCreateDate(getCreateDate());
		licenseEntryImpl.setModifiedDate(getModifiedDate());
		licenseEntryImpl.setProductEntryId(getProductEntryId());
		licenseEntryImpl.setName(getName());
		licenseEntryImpl.setType(getType());
		licenseEntryImpl.setPortalVersionMin(getPortalVersionMin());
		licenseEntryImpl.setPortalVersionMax(getPortalVersionMax());

		licenseEntryImpl.resetOriginalValues();

		return licenseEntryImpl;
	}

	@Override
	public int compareTo(LicenseEntry licenseEntry) {
		int value = 0;

		value = getName().compareToIgnoreCase(licenseEntry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LicenseEntry)) {
			return false;
		}

		LicenseEntry licenseEntry = (LicenseEntry)obj;

		long primaryKey = licenseEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LicenseEntryModelImpl licenseEntryModelImpl = this;

		licenseEntryModelImpl._setModifiedDate = false;

		licenseEntryModelImpl._originalProductEntryId = licenseEntryModelImpl._productEntryId;

		licenseEntryModelImpl._setOriginalProductEntryId = false;

		licenseEntryModelImpl._originalType = licenseEntryModelImpl._type;

		licenseEntryModelImpl._originalPortalVersionMin = licenseEntryModelImpl._portalVersionMin;

		licenseEntryModelImpl._setOriginalPortalVersionMin = false;

		licenseEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LicenseEntry> toCacheModel() {
		LicenseEntryCacheModel licenseEntryCacheModel = new LicenseEntryCacheModel();

		licenseEntryCacheModel.licenseEntryId = getLicenseEntryId();

		licenseEntryCacheModel.userId = getUserId();

		licenseEntryCacheModel.userName = getUserName();

		String userName = licenseEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			licenseEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			licenseEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			licenseEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			licenseEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			licenseEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		licenseEntryCacheModel.productEntryId = getProductEntryId();

		licenseEntryCacheModel.name = getName();

		String name = licenseEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			licenseEntryCacheModel.name = null;
		}

		licenseEntryCacheModel.type = getType();

		String type = licenseEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			licenseEntryCacheModel.type = null;
		}

		licenseEntryCacheModel.portalVersionMin = getPortalVersionMin();

		licenseEntryCacheModel.portalVersionMax = getPortalVersionMax();

		return licenseEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{licenseEntryId=");
		sb.append(getLicenseEntryId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", productEntryId=");
		sb.append(getProductEntryId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", portalVersionMin=");
		sb.append(getPortalVersionMin());
		sb.append(", portalVersionMax=");
		sb.append(getPortalVersionMax());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.LicenseEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>licenseEntryId</column-name><column-value><![CDATA[");
		sb.append(getLicenseEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productEntryId</column-name><column-value><![CDATA[");
		sb.append(getProductEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portalVersionMin</column-name><column-value><![CDATA[");
		sb.append(getPortalVersionMin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portalVersionMax</column-name><column-value><![CDATA[");
		sb.append(getPortalVersionMax());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LicenseEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LicenseEntry.class
		};
	private long _licenseEntryId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _productEntryId;
	private long _originalProductEntryId;
	private boolean _setOriginalProductEntryId;
	private String _name;
	private String _type;
	private String _originalType;
	private int _portalVersionMin;
	private int _originalPortalVersionMin;
	private boolean _setOriginalPortalVersionMin;
	private int _portalVersionMax;
	private long _columnBitmask;
	private LicenseEntry _escapedModel;
}