/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.model.OfferingEntry;
import com.liferay.osb.model.OfferingEntryModel;
import com.liferay.osb.model.OfferingEntrySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OfferingEntry service. Represents a row in the &quot;OSB_OfferingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link OfferingEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OfferingEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OfferingEntryImpl
 * @see OfferingEntry
 * @see OfferingEntryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class OfferingEntryModelImpl extends BaseModelImpl<OfferingEntry>
	implements OfferingEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a offering entry model instance should use the {@link OfferingEntry} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_OfferingEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "offeringEntryId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "accountEntryId", Types.BIGINT },
			{ "orderEntryId", Types.BIGINT },
			{ "productEntryId", Types.BIGINT },
			{ "supportResponseId", Types.BIGINT },
			{ "productDescription", Types.VARCHAR },
			{ "type_", Types.INTEGER },
			{ "version", Types.INTEGER },
			{ "platform", Types.VARCHAR },
			{ "platformVersion", Types.VARCHAR },
			{ "licenses", Types.BOOLEAN },
			{ "licenseLifetime", Types.BIGINT },
			{ "maxConcurrentUsers", Types.BIGINT },
			{ "maxUsers", Types.BIGINT },
			{ "supportTickets", Types.BOOLEAN },
			{ "supportLifetime", Types.BIGINT },
			{ "supportEndDate", Types.TIMESTAMP },
			{ "sizing", Types.INTEGER },
			{ "quantity", Types.INTEGER },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("offeringEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("orderEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportResponseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("platform", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("platformVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("licenses", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("licenseLifetime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("maxConcurrentUsers", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("maxUsers", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportTickets", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("supportLifetime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportEndDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("sizing", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("quantity", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_OfferingEntry (offeringEntryId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,accountEntryId LONG,orderEntryId LONG,productEntryId LONG,supportResponseId LONG,productDescription VARCHAR(75) null,type_ INTEGER,version INTEGER,platform VARCHAR(75) null,platformVersion VARCHAR(75) null,licenses BOOLEAN,licenseLifetime LONG,maxConcurrentUsers LONG,maxUsers LONG,supportTickets BOOLEAN,supportLifetime LONG,supportEndDate DATE null,sizing INTEGER,quantity INTEGER,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_OfferingEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY offeringEntry.offeringEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_OfferingEntry.offeringEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.OfferingEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.OfferingEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.OfferingEntry"),
			true);
	public static final long ACCOUNTENTRYID_COLUMN_BITMASK = 1L;
	public static final long ORDERENTRYID_COLUMN_BITMASK = 2L;
	public static final long PRODUCTENTRYID_COLUMN_BITMASK = 4L;
	public static final long TYPE_COLUMN_BITMASK = 8L;
	public static final long USERID_COLUMN_BITMASK = 16L;
	public static final long OFFERINGENTRYID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OfferingEntry toModel(OfferingEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OfferingEntry model = new OfferingEntryImpl();

		model.setOfferingEntryId(soapModel.getOfferingEntryId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAccountEntryId(soapModel.getAccountEntryId());
		model.setOrderEntryId(soapModel.getOrderEntryId());
		model.setProductEntryId(soapModel.getProductEntryId());
		model.setSupportResponseId(soapModel.getSupportResponseId());
		model.setProductDescription(soapModel.getProductDescription());
		model.setType(soapModel.getType());
		model.setVersion(soapModel.getVersion());
		model.setPlatform(soapModel.getPlatform());
		model.setPlatformVersion(soapModel.getPlatformVersion());
		model.setLicenses(soapModel.getLicenses());
		model.setLicenseLifetime(soapModel.getLicenseLifetime());
		model.setMaxConcurrentUsers(soapModel.getMaxConcurrentUsers());
		model.setMaxUsers(soapModel.getMaxUsers());
		model.setSupportTickets(soapModel.getSupportTickets());
		model.setSupportLifetime(soapModel.getSupportLifetime());
		model.setSupportEndDate(soapModel.getSupportEndDate());
		model.setSizing(soapModel.getSizing());
		model.setQuantity(soapModel.getQuantity());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OfferingEntry> toModels(OfferingEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OfferingEntry> models = new ArrayList<OfferingEntry>(soapModels.length);

		for (OfferingEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.OfferingEntry"));

	public OfferingEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _offeringEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOfferingEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _offeringEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OfferingEntry.class;
	}

	@Override
	public String getModelClassName() {
		return OfferingEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("offeringEntryId", getOfferingEntryId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("accountEntryId", getAccountEntryId());
		attributes.put("orderEntryId", getOrderEntryId());
		attributes.put("productEntryId", getProductEntryId());
		attributes.put("supportResponseId", getSupportResponseId());
		attributes.put("productDescription", getProductDescription());
		attributes.put("type", getType());
		attributes.put("version", getVersion());
		attributes.put("platform", getPlatform());
		attributes.put("platformVersion", getPlatformVersion());
		attributes.put("licenses", getLicenses());
		attributes.put("licenseLifetime", getLicenseLifetime());
		attributes.put("maxConcurrentUsers", getMaxConcurrentUsers());
		attributes.put("maxUsers", getMaxUsers());
		attributes.put("supportTickets", getSupportTickets());
		attributes.put("supportLifetime", getSupportLifetime());
		attributes.put("supportEndDate", getSupportEndDate());
		attributes.put("sizing", getSizing());
		attributes.put("quantity", getQuantity());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long offeringEntryId = (Long)attributes.get("offeringEntryId");

		if (offeringEntryId != null) {
			setOfferingEntryId(offeringEntryId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long accountEntryId = (Long)attributes.get("accountEntryId");

		if (accountEntryId != null) {
			setAccountEntryId(accountEntryId);
		}

		Long orderEntryId = (Long)attributes.get("orderEntryId");

		if (orderEntryId != null) {
			setOrderEntryId(orderEntryId);
		}

		Long productEntryId = (Long)attributes.get("productEntryId");

		if (productEntryId != null) {
			setProductEntryId(productEntryId);
		}

		Long supportResponseId = (Long)attributes.get("supportResponseId");

		if (supportResponseId != null) {
			setSupportResponseId(supportResponseId);
		}

		String productDescription = (String)attributes.get("productDescription");

		if (productDescription != null) {
			setProductDescription(productDescription);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Integer version = (Integer)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}

		String platform = (String)attributes.get("platform");

		if (platform != null) {
			setPlatform(platform);
		}

		String platformVersion = (String)attributes.get("platformVersion");

		if (platformVersion != null) {
			setPlatformVersion(platformVersion);
		}

		Boolean licenses = (Boolean)attributes.get("licenses");

		if (licenses != null) {
			setLicenses(licenses);
		}

		Long licenseLifetime = (Long)attributes.get("licenseLifetime");

		if (licenseLifetime != null) {
			setLicenseLifetime(licenseLifetime);
		}

		Long maxConcurrentUsers = (Long)attributes.get("maxConcurrentUsers");

		if (maxConcurrentUsers != null) {
			setMaxConcurrentUsers(maxConcurrentUsers);
		}

		Long maxUsers = (Long)attributes.get("maxUsers");

		if (maxUsers != null) {
			setMaxUsers(maxUsers);
		}

		Boolean supportTickets = (Boolean)attributes.get("supportTickets");

		if (supportTickets != null) {
			setSupportTickets(supportTickets);
		}

		Long supportLifetime = (Long)attributes.get("supportLifetime");

		if (supportLifetime != null) {
			setSupportLifetime(supportLifetime);
		}

		Date supportEndDate = (Date)attributes.get("supportEndDate");

		if (supportEndDate != null) {
			setSupportEndDate(supportEndDate);
		}

		Integer sizing = (Integer)attributes.get("sizing");

		if (sizing != null) {
			setSizing(sizing);
		}

		Integer quantity = (Integer)attributes.get("quantity");

		if (quantity != null) {
			setQuantity(quantity);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getOfferingEntryId() {
		return _offeringEntryId;
	}

	@Override
	public void setOfferingEntryId(long offeringEntryId) {
		_columnBitmask = -1L;

		_offeringEntryId = offeringEntryId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAccountEntryId() {
		return _accountEntryId;
	}

	@Override
	public void setAccountEntryId(long accountEntryId) {
		_columnBitmask |= ACCOUNTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAccountEntryId) {
			_setOriginalAccountEntryId = true;

			_originalAccountEntryId = _accountEntryId;
		}

		_accountEntryId = accountEntryId;
	}

	public long getOriginalAccountEntryId() {
		return _originalAccountEntryId;
	}

	@JSON
	@Override
	public long getOrderEntryId() {
		return _orderEntryId;
	}

	@Override
	public void setOrderEntryId(long orderEntryId) {
		_columnBitmask |= ORDERENTRYID_COLUMN_BITMASK;

		if (!_setOriginalOrderEntryId) {
			_setOriginalOrderEntryId = true;

			_originalOrderEntryId = _orderEntryId;
		}

		_orderEntryId = orderEntryId;
	}

	public long getOriginalOrderEntryId() {
		return _originalOrderEntryId;
	}

	@JSON
	@Override
	public long getProductEntryId() {
		return _productEntryId;
	}

	@Override
	public void setProductEntryId(long productEntryId) {
		_columnBitmask |= PRODUCTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalProductEntryId) {
			_setOriginalProductEntryId = true;

			_originalProductEntryId = _productEntryId;
		}

		_productEntryId = productEntryId;
	}

	public long getOriginalProductEntryId() {
		return _originalProductEntryId;
	}

	@JSON
	@Override
	public long getSupportResponseId() {
		return _supportResponseId;
	}

	@Override
	public void setSupportResponseId(long supportResponseId) {
		_supportResponseId = supportResponseId;
	}

	@JSON
	@Override
	public String getProductDescription() {
		if (_productDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _productDescription;
		}
	}

	@Override
	public void setProductDescription(String productDescription) {
		_productDescription = productDescription;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		_version = version;
	}

	@JSON
	@Override
	public String getPlatform() {
		if (_platform == null) {
			return StringPool.BLANK;
		}
		else {
			return _platform;
		}
	}

	@Override
	public void setPlatform(String platform) {
		_platform = platform;
	}

	@JSON
	@Override
	public String getPlatformVersion() {
		if (_platformVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _platformVersion;
		}
	}

	@Override
	public void setPlatformVersion(String platformVersion) {
		_platformVersion = platformVersion;
	}

	@JSON
	@Override
	public boolean getLicenses() {
		return _licenses;
	}

	@JSON
	@Override
	public boolean isLicenses() {
		return _licenses;
	}

	@Override
	public void setLicenses(boolean licenses) {
		_licenses = licenses;
	}

	@JSON
	@Override
	public long getLicenseLifetime() {
		return _licenseLifetime;
	}

	@Override
	public void setLicenseLifetime(long licenseLifetime) {
		_licenseLifetime = licenseLifetime;
	}

	@JSON
	@Override
	public long getMaxConcurrentUsers() {
		return _maxConcurrentUsers;
	}

	@Override
	public void setMaxConcurrentUsers(long maxConcurrentUsers) {
		_maxConcurrentUsers = maxConcurrentUsers;
	}

	@JSON
	@Override
	public long getMaxUsers() {
		return _maxUsers;
	}

	@Override
	public void setMaxUsers(long maxUsers) {
		_maxUsers = maxUsers;
	}

	@JSON
	@Override
	public boolean getSupportTickets() {
		return _supportTickets;
	}

	@JSON
	@Override
	public boolean isSupportTickets() {
		return _supportTickets;
	}

	@Override
	public void setSupportTickets(boolean supportTickets) {
		_supportTickets = supportTickets;
	}

	@JSON
	@Override
	public long getSupportLifetime() {
		return _supportLifetime;
	}

	@Override
	public void setSupportLifetime(long supportLifetime) {
		_supportLifetime = supportLifetime;
	}

	@JSON
	@Override
	public Date getSupportEndDate() {
		return _supportEndDate;
	}

	@Override
	public void setSupportEndDate(Date supportEndDate) {
		_supportEndDate = supportEndDate;
	}

	@JSON
	@Override
	public int getSizing() {
		return _sizing;
	}

	@Override
	public void setSizing(int sizing) {
		_sizing = sizing;
	}

	@JSON
	@Override
	public int getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(int quantity) {
		_quantity = quantity;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			OfferingEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OfferingEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OfferingEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OfferingEntryImpl offeringEntryImpl = new OfferingEntryImpl();

		offeringEntryImpl.setOfferingEntryId(getOfferingEntryId());
		offeringEntryImpl.setUserId(getUserId());
		offeringEntryImpl.setUserName(getUserName());
		offeringEntryImpl.setCreateDate(getCreateDate());
		offeringEntryImpl.setModifiedDate(getModifiedDate());
		offeringEntryImpl.setAccountEntryId(getAccountEntryId());
		offeringEntryImpl.setOrderEntryId(getOrderEntryId());
		offeringEntryImpl.setProductEntryId(getProductEntryId());
		offeringEntryImpl.setSupportResponseId(getSupportResponseId());
		offeringEntryImpl.setProductDescription(getProductDescription());
		offeringEntryImpl.setType(getType());
		offeringEntryImpl.setVersion(getVersion());
		offeringEntryImpl.setPlatform(getPlatform());
		offeringEntryImpl.setPlatformVersion(getPlatformVersion());
		offeringEntryImpl.setLicenses(getLicenses());
		offeringEntryImpl.setLicenseLifetime(getLicenseLifetime());
		offeringEntryImpl.setMaxConcurrentUsers(getMaxConcurrentUsers());
		offeringEntryImpl.setMaxUsers(getMaxUsers());
		offeringEntryImpl.setSupportTickets(getSupportTickets());
		offeringEntryImpl.setSupportLifetime(getSupportLifetime());
		offeringEntryImpl.setSupportEndDate(getSupportEndDate());
		offeringEntryImpl.setSizing(getSizing());
		offeringEntryImpl.setQuantity(getQuantity());
		offeringEntryImpl.setStatus(getStatus());

		offeringEntryImpl.resetOriginalValues();

		return offeringEntryImpl;
	}

	@Override
	public int compareTo(OfferingEntry offeringEntry) {
		int value = 0;

		if (getOfferingEntryId() < offeringEntry.getOfferingEntryId()) {
			value = -1;
		}
		else if (getOfferingEntryId() > offeringEntry.getOfferingEntryId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OfferingEntry)) {
			return false;
		}

		OfferingEntry offeringEntry = (OfferingEntry)obj;

		long primaryKey = offeringEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		OfferingEntryModelImpl offeringEntryModelImpl = this;

		offeringEntryModelImpl._originalUserId = offeringEntryModelImpl._userId;

		offeringEntryModelImpl._setOriginalUserId = false;

		offeringEntryModelImpl._setModifiedDate = false;

		offeringEntryModelImpl._originalAccountEntryId = offeringEntryModelImpl._accountEntryId;

		offeringEntryModelImpl._setOriginalAccountEntryId = false;

		offeringEntryModelImpl._originalOrderEntryId = offeringEntryModelImpl._orderEntryId;

		offeringEntryModelImpl._setOriginalOrderEntryId = false;

		offeringEntryModelImpl._originalProductEntryId = offeringEntryModelImpl._productEntryId;

		offeringEntryModelImpl._setOriginalProductEntryId = false;

		offeringEntryModelImpl._originalType = offeringEntryModelImpl._type;

		offeringEntryModelImpl._setOriginalType = false;

		offeringEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OfferingEntry> toCacheModel() {
		OfferingEntryCacheModel offeringEntryCacheModel = new OfferingEntryCacheModel();

		offeringEntryCacheModel.offeringEntryId = getOfferingEntryId();

		offeringEntryCacheModel.userId = getUserId();

		offeringEntryCacheModel.userName = getUserName();

		String userName = offeringEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			offeringEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			offeringEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			offeringEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			offeringEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			offeringEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		offeringEntryCacheModel.accountEntryId = getAccountEntryId();

		offeringEntryCacheModel.orderEntryId = getOrderEntryId();

		offeringEntryCacheModel.productEntryId = getProductEntryId();

		offeringEntryCacheModel.supportResponseId = getSupportResponseId();

		offeringEntryCacheModel.productDescription = getProductDescription();

		String productDescription = offeringEntryCacheModel.productDescription;

		if ((productDescription != null) && (productDescription.length() == 0)) {
			offeringEntryCacheModel.productDescription = null;
		}

		offeringEntryCacheModel.type = getType();

		offeringEntryCacheModel.version = getVersion();

		offeringEntryCacheModel.platform = getPlatform();

		String platform = offeringEntryCacheModel.platform;

		if ((platform != null) && (platform.length() == 0)) {
			offeringEntryCacheModel.platform = null;
		}

		offeringEntryCacheModel.platformVersion = getPlatformVersion();

		String platformVersion = offeringEntryCacheModel.platformVersion;

		if ((platformVersion != null) && (platformVersion.length() == 0)) {
			offeringEntryCacheModel.platformVersion = null;
		}

		offeringEntryCacheModel.licenses = getLicenses();

		offeringEntryCacheModel.licenseLifetime = getLicenseLifetime();

		offeringEntryCacheModel.maxConcurrentUsers = getMaxConcurrentUsers();

		offeringEntryCacheModel.maxUsers = getMaxUsers();

		offeringEntryCacheModel.supportTickets = getSupportTickets();

		offeringEntryCacheModel.supportLifetime = getSupportLifetime();

		Date supportEndDate = getSupportEndDate();

		if (supportEndDate != null) {
			offeringEntryCacheModel.supportEndDate = supportEndDate.getTime();
		}
		else {
			offeringEntryCacheModel.supportEndDate = Long.MIN_VALUE;
		}

		offeringEntryCacheModel.sizing = getSizing();

		offeringEntryCacheModel.quantity = getQuantity();

		offeringEntryCacheModel.status = getStatus();

		return offeringEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(49);

		sb.append("{offeringEntryId=");
		sb.append(getOfferingEntryId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", accountEntryId=");
		sb.append(getAccountEntryId());
		sb.append(", orderEntryId=");
		sb.append(getOrderEntryId());
		sb.append(", productEntryId=");
		sb.append(getProductEntryId());
		sb.append(", supportResponseId=");
		sb.append(getSupportResponseId());
		sb.append(", productDescription=");
		sb.append(getProductDescription());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append(", platform=");
		sb.append(getPlatform());
		sb.append(", platformVersion=");
		sb.append(getPlatformVersion());
		sb.append(", licenses=");
		sb.append(getLicenses());
		sb.append(", licenseLifetime=");
		sb.append(getLicenseLifetime());
		sb.append(", maxConcurrentUsers=");
		sb.append(getMaxConcurrentUsers());
		sb.append(", maxUsers=");
		sb.append(getMaxUsers());
		sb.append(", supportTickets=");
		sb.append(getSupportTickets());
		sb.append(", supportLifetime=");
		sb.append(getSupportLifetime());
		sb.append(", supportEndDate=");
		sb.append(getSupportEndDate());
		sb.append(", sizing=");
		sb.append(getSizing());
		sb.append(", quantity=");
		sb.append(getQuantity());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(76);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.OfferingEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>offeringEntryId</column-name><column-value><![CDATA[");
		sb.append(getOfferingEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountEntryId</column-name><column-value><![CDATA[");
		sb.append(getAccountEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderEntryId</column-name><column-value><![CDATA[");
		sb.append(getOrderEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productEntryId</column-name><column-value><![CDATA[");
		sb.append(getProductEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportResponseId</column-name><column-value><![CDATA[");
		sb.append(getSupportResponseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productDescription</column-name><column-value><![CDATA[");
		sb.append(getProductDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>platform</column-name><column-value><![CDATA[");
		sb.append(getPlatform());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>platformVersion</column-name><column-value><![CDATA[");
		sb.append(getPlatformVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>licenses</column-name><column-value><![CDATA[");
		sb.append(getLicenses());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>licenseLifetime</column-name><column-value><![CDATA[");
		sb.append(getLicenseLifetime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxConcurrentUsers</column-name><column-value><![CDATA[");
		sb.append(getMaxConcurrentUsers());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxUsers</column-name><column-value><![CDATA[");
		sb.append(getMaxUsers());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportTickets</column-name><column-value><![CDATA[");
		sb.append(getSupportTickets());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportLifetime</column-name><column-value><![CDATA[");
		sb.append(getSupportLifetime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportEndDate</column-name><column-value><![CDATA[");
		sb.append(getSupportEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sizing</column-name><column-value><![CDATA[");
		sb.append(getSizing());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quantity</column-name><column-value><![CDATA[");
		sb.append(getQuantity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = OfferingEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			OfferingEntry.class
		};
	private long _offeringEntryId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _accountEntryId;
	private long _originalAccountEntryId;
	private boolean _setOriginalAccountEntryId;
	private long _orderEntryId;
	private long _originalOrderEntryId;
	private boolean _setOriginalOrderEntryId;
	private long _productEntryId;
	private long _originalProductEntryId;
	private boolean _setOriginalProductEntryId;
	private long _supportResponseId;
	private String _productDescription;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private int _version;
	private String _platform;
	private String _platformVersion;
	private boolean _licenses;
	private long _licenseLifetime;
	private long _maxConcurrentUsers;
	private long _maxUsers;
	private boolean _supportTickets;
	private long _supportLifetime;
	private Date _supportEndDate;
	private int _sizing;
	private int _quantity;
	private int _status;
	private long _columnBitmask;
	private OfferingEntry _escapedModel;
}