/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.model.SupportTeamLanguage;
import com.liferay.osb.model.SupportTeamLanguageModel;
import com.liferay.osb.model.SupportTeamLanguageSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SupportTeamLanguage service. Represents a row in the &quot;OSB_SupportTeamLanguage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SupportTeamLanguageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportTeamLanguageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportTeamLanguageImpl
 * @see SupportTeamLanguage
 * @see SupportTeamLanguageModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SupportTeamLanguageModelImpl extends BaseModelImpl<SupportTeamLanguage>
	implements SupportTeamLanguageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support team language model instance should use the {@link SupportTeamLanguage} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_SupportTeamLanguage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "supportTeamLanguageId", Types.BIGINT },
			{ "supportTeamId", Types.BIGINT },
			{ "languageId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("supportTeamLanguageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportTeamId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_SupportTeamLanguage (supportTeamLanguageId LONG not null primary key,supportTeamId LONG,languageId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_SupportTeamLanguage";
	public static final String ORDER_BY_JPQL = " ORDER BY supportTeamLanguage.languageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_SupportTeamLanguage.languageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.SupportTeamLanguage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.SupportTeamLanguage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.SupportTeamLanguage"),
			true);
	public static final long SUPPORTTEAMID_COLUMN_BITMASK = 1L;
	public static final long LANGUAGEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SupportTeamLanguage toModel(SupportTeamLanguageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SupportTeamLanguage model = new SupportTeamLanguageImpl();

		model.setSupportTeamLanguageId(soapModel.getSupportTeamLanguageId());
		model.setSupportTeamId(soapModel.getSupportTeamId());
		model.setLanguageId(soapModel.getLanguageId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SupportTeamLanguage> toModels(
		SupportTeamLanguageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SupportTeamLanguage> models = new ArrayList<SupportTeamLanguage>(soapModels.length);

		for (SupportTeamLanguageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.SupportTeamLanguage"));

	public SupportTeamLanguageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supportTeamLanguageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupportTeamLanguageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supportTeamLanguageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupportTeamLanguage.class;
	}

	@Override
	public String getModelClassName() {
		return SupportTeamLanguage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("supportTeamLanguageId", getSupportTeamLanguageId());
		attributes.put("supportTeamId", getSupportTeamId());
		attributes.put("languageId", getLanguageId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long supportTeamLanguageId = (Long)attributes.get(
				"supportTeamLanguageId");

		if (supportTeamLanguageId != null) {
			setSupportTeamLanguageId(supportTeamLanguageId);
		}

		Long supportTeamId = (Long)attributes.get("supportTeamId");

		if (supportTeamId != null) {
			setSupportTeamId(supportTeamId);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}
	}

	@JSON
	@Override
	public long getSupportTeamLanguageId() {
		return _supportTeamLanguageId;
	}

	@Override
	public void setSupportTeamLanguageId(long supportTeamLanguageId) {
		_supportTeamLanguageId = supportTeamLanguageId;
	}

	@JSON
	@Override
	public long getSupportTeamId() {
		return _supportTeamId;
	}

	@Override
	public void setSupportTeamId(long supportTeamId) {
		_columnBitmask |= SUPPORTTEAMID_COLUMN_BITMASK;

		if (!_setOriginalSupportTeamId) {
			_setOriginalSupportTeamId = true;

			_originalSupportTeamId = _supportTeamId;
		}

		_supportTeamId = supportTeamId;
	}

	public long getOriginalSupportTeamId() {
		return _originalSupportTeamId;
	}

	@JSON
	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		_columnBitmask = -1L;

		_languageId = languageId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SupportTeamLanguage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupportTeamLanguage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SupportTeamLanguage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupportTeamLanguageImpl supportTeamLanguageImpl = new SupportTeamLanguageImpl();

		supportTeamLanguageImpl.setSupportTeamLanguageId(getSupportTeamLanguageId());
		supportTeamLanguageImpl.setSupportTeamId(getSupportTeamId());
		supportTeamLanguageImpl.setLanguageId(getLanguageId());

		supportTeamLanguageImpl.resetOriginalValues();

		return supportTeamLanguageImpl;
	}

	@Override
	public int compareTo(SupportTeamLanguage supportTeamLanguage) {
		int value = 0;

		value = getLanguageId().compareTo(supportTeamLanguage.getLanguageId());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SupportTeamLanguage)) {
			return false;
		}

		SupportTeamLanguage supportTeamLanguage = (SupportTeamLanguage)obj;

		long primaryKey = supportTeamLanguage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SupportTeamLanguageModelImpl supportTeamLanguageModelImpl = this;

		supportTeamLanguageModelImpl._originalSupportTeamId = supportTeamLanguageModelImpl._supportTeamId;

		supportTeamLanguageModelImpl._setOriginalSupportTeamId = false;

		supportTeamLanguageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SupportTeamLanguage> toCacheModel() {
		SupportTeamLanguageCacheModel supportTeamLanguageCacheModel = new SupportTeamLanguageCacheModel();

		supportTeamLanguageCacheModel.supportTeamLanguageId = getSupportTeamLanguageId();

		supportTeamLanguageCacheModel.supportTeamId = getSupportTeamId();

		supportTeamLanguageCacheModel.languageId = getLanguageId();

		String languageId = supportTeamLanguageCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			supportTeamLanguageCacheModel.languageId = null;
		}

		return supportTeamLanguageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{supportTeamLanguageId=");
		sb.append(getSupportTeamLanguageId());
		sb.append(", supportTeamId=");
		sb.append(getSupportTeamId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.SupportTeamLanguage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>supportTeamLanguageId</column-name><column-value><![CDATA[");
		sb.append(getSupportTeamLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportTeamId</column-name><column-value><![CDATA[");
		sb.append(getSupportTeamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SupportTeamLanguage.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SupportTeamLanguage.class
		};
	private long _supportTeamLanguageId;
	private long _supportTeamId;
	private long _originalSupportTeamId;
	private boolean _setOriginalSupportTeamId;
	private String _languageId;
	private long _columnBitmask;
	private SupportTeamLanguage _escapedModel;
}