/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.model.SupportTeam;
import com.liferay.osb.model.SupportTeamModel;
import com.liferay.osb.model.SupportTeamSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SupportTeam service. Represents a row in the &quot;OSB_SupportTeam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SupportTeamModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportTeamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportTeamImpl
 * @see SupportTeam
 * @see SupportTeamModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SupportTeamModelImpl extends BaseModelImpl<SupportTeam>
	implements SupportTeamModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support team model instance should use the {@link SupportTeam} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_SupportTeam";
	public static final Object[][] TABLE_COLUMNS = {
			{ "supportTeamId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "parentSupportTeamId", Types.BIGINT },
			{ "supportLaborId", Types.BIGINT },
			{ "locationSupportRegionId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "type_", Types.INTEGER },
			{ "assignedWork", Types.DOUBLE },
			{ "maxWork", Types.DOUBLE }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("supportTeamId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentSupportTeamId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportLaborId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("locationSupportRegionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("assignedWork", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("maxWork", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_SupportTeam (supportTeamId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentSupportTeamId LONG,supportLaborId LONG,locationSupportRegionId LONG,name VARCHAR(75) null,description STRING null,type_ INTEGER,assignedWork DOUBLE,maxWork DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table OSB_SupportTeam";
	public static final String ORDER_BY_JPQL = " ORDER BY supportTeam.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_SupportTeam.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.SupportTeam"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.SupportTeam"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.SupportTeam"),
			true);
	public static final long NAME_COLUMN_BITMASK = 1L;
	public static final long PARENTSUPPORTTEAMID_COLUMN_BITMASK = 2L;
	public static final long SUPPORTLABORID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SupportTeam toModel(SupportTeamSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SupportTeam model = new SupportTeamImpl();

		model.setSupportTeamId(soapModel.getSupportTeamId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setParentSupportTeamId(soapModel.getParentSupportTeamId());
		model.setSupportLaborId(soapModel.getSupportLaborId());
		model.setLocationSupportRegionId(soapModel.getLocationSupportRegionId());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setType(soapModel.getType());
		model.setAssignedWork(soapModel.getAssignedWork());
		model.setMaxWork(soapModel.getMaxWork());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SupportTeam> toModels(SupportTeamSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SupportTeam> models = new ArrayList<SupportTeam>(soapModels.length);

		for (SupportTeamSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_OSB_ACCOUNTENTRIES_SUPPORTTEAMS_NAME =
		"OSB_AccountEntries_SupportTeams";
	public static final Object[][] MAPPING_TABLE_OSB_ACCOUNTENTRIES_SUPPORTTEAMS_COLUMNS =
		{
			{ "companyId", Types.BIGINT },
			{ "accountEntryId", Types.BIGINT },
			{ "supportTeamId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_ACCOUNTENTRIES_SUPPORTTEAMS_SQL_CREATE =
		"create table OSB_AccountEntries_SupportTeams (companyId LONG not null,accountEntryId LONG not null,supportTeamId LONG not null,primary key (accountEntryId, supportTeamId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_ACCOUNTENTRIES_SUPPORTTEAMS =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_AccountEntries_SupportTeams"),
			true);
	public static final String MAPPING_TABLE_OSB_SUPPORTTEAMS_SUPPORTREGIONS_NAME =
		"OSB_SupportTeams_SupportRegions";
	public static final Object[][] MAPPING_TABLE_OSB_SUPPORTTEAMS_SUPPORTREGIONS_COLUMNS =
		{
			{ "companyId", Types.BIGINT },
			{ "supportRegionId", Types.BIGINT },
			{ "supportTeamId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_SUPPORTTEAMS_SUPPORTREGIONS_SQL_CREATE =
		"create table OSB_SupportTeams_SupportRegions (companyId LONG not null,supportRegionId LONG not null,supportTeamId LONG not null,primary key (supportRegionId, supportTeamId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_SUPPORTTEAMS_SUPPORTREGIONS =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_SupportTeams_SupportRegions"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.SupportTeam"));

	public SupportTeamModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supportTeamId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupportTeamId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supportTeamId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupportTeam.class;
	}

	@Override
	public String getModelClassName() {
		return SupportTeam.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("supportTeamId", getSupportTeamId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("parentSupportTeamId", getParentSupportTeamId());
		attributes.put("supportLaborId", getSupportLaborId());
		attributes.put("locationSupportRegionId", getLocationSupportRegionId());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("type", getType());
		attributes.put("assignedWork", getAssignedWork());
		attributes.put("maxWork", getMaxWork());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long supportTeamId = (Long)attributes.get("supportTeamId");

		if (supportTeamId != null) {
			setSupportTeamId(supportTeamId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long parentSupportTeamId = (Long)attributes.get("parentSupportTeamId");

		if (parentSupportTeamId != null) {
			setParentSupportTeamId(parentSupportTeamId);
		}

		Long supportLaborId = (Long)attributes.get("supportLaborId");

		if (supportLaborId != null) {
			setSupportLaborId(supportLaborId);
		}

		Long locationSupportRegionId = (Long)attributes.get(
				"locationSupportRegionId");

		if (locationSupportRegionId != null) {
			setLocationSupportRegionId(locationSupportRegionId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Double assignedWork = (Double)attributes.get("assignedWork");

		if (assignedWork != null) {
			setAssignedWork(assignedWork);
		}

		Double maxWork = (Double)attributes.get("maxWork");

		if (maxWork != null) {
			setMaxWork(maxWork);
		}
	}

	@JSON
	@Override
	public long getSupportTeamId() {
		return _supportTeamId;
	}

	@Override
	public void setSupportTeamId(long supportTeamId) {
		_supportTeamId = supportTeamId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getParentSupportTeamId() {
		return _parentSupportTeamId;
	}

	@Override
	public void setParentSupportTeamId(long parentSupportTeamId) {
		_columnBitmask |= PARENTSUPPORTTEAMID_COLUMN_BITMASK;

		if (!_setOriginalParentSupportTeamId) {
			_setOriginalParentSupportTeamId = true;

			_originalParentSupportTeamId = _parentSupportTeamId;
		}

		_parentSupportTeamId = parentSupportTeamId;
	}

	public long getOriginalParentSupportTeamId() {
		return _originalParentSupportTeamId;
	}

	@JSON
	@Override
	public long getSupportLaborId() {
		return _supportLaborId;
	}

	@Override
	public void setSupportLaborId(long supportLaborId) {
		_columnBitmask |= SUPPORTLABORID_COLUMN_BITMASK;

		if (!_setOriginalSupportLaborId) {
			_setOriginalSupportLaborId = true;

			_originalSupportLaborId = _supportLaborId;
		}

		_supportLaborId = supportLaborId;
	}

	public long getOriginalSupportLaborId() {
		return _originalSupportLaborId;
	}

	@JSON
	@Override
	public long getLocationSupportRegionId() {
		return _locationSupportRegionId;
	}

	@Override
	public void setLocationSupportRegionId(long locationSupportRegionId) {
		_locationSupportRegionId = locationSupportRegionId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@JSON
	@Override
	public double getAssignedWork() {
		return _assignedWork;
	}

	@Override
	public void setAssignedWork(double assignedWork) {
		_assignedWork = assignedWork;
	}

	@JSON
	@Override
	public double getMaxWork() {
		return _maxWork;
	}

	@Override
	public void setMaxWork(double maxWork) {
		_maxWork = maxWork;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SupportTeam.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupportTeam toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SupportTeam)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupportTeamImpl supportTeamImpl = new SupportTeamImpl();

		supportTeamImpl.setSupportTeamId(getSupportTeamId());
		supportTeamImpl.setCompanyId(getCompanyId());
		supportTeamImpl.setUserId(getUserId());
		supportTeamImpl.setUserName(getUserName());
		supportTeamImpl.setCreateDate(getCreateDate());
		supportTeamImpl.setModifiedDate(getModifiedDate());
		supportTeamImpl.setParentSupportTeamId(getParentSupportTeamId());
		supportTeamImpl.setSupportLaborId(getSupportLaborId());
		supportTeamImpl.setLocationSupportRegionId(getLocationSupportRegionId());
		supportTeamImpl.setName(getName());
		supportTeamImpl.setDescription(getDescription());
		supportTeamImpl.setType(getType());
		supportTeamImpl.setAssignedWork(getAssignedWork());
		supportTeamImpl.setMaxWork(getMaxWork());

		supportTeamImpl.resetOriginalValues();

		return supportTeamImpl;
	}

	@Override
	public int compareTo(SupportTeam supportTeam) {
		int value = 0;

		value = getName().compareToIgnoreCase(supportTeam.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SupportTeam)) {
			return false;
		}

		SupportTeam supportTeam = (SupportTeam)obj;

		long primaryKey = supportTeam.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SupportTeamModelImpl supportTeamModelImpl = this;

		supportTeamModelImpl._setModifiedDate = false;

		supportTeamModelImpl._originalParentSupportTeamId = supportTeamModelImpl._parentSupportTeamId;

		supportTeamModelImpl._setOriginalParentSupportTeamId = false;

		supportTeamModelImpl._originalSupportLaborId = supportTeamModelImpl._supportLaborId;

		supportTeamModelImpl._setOriginalSupportLaborId = false;

		supportTeamModelImpl._originalName = supportTeamModelImpl._name;

		supportTeamModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SupportTeam> toCacheModel() {
		SupportTeamCacheModel supportTeamCacheModel = new SupportTeamCacheModel();

		supportTeamCacheModel.supportTeamId = getSupportTeamId();

		supportTeamCacheModel.companyId = getCompanyId();

		supportTeamCacheModel.userId = getUserId();

		supportTeamCacheModel.userName = getUserName();

		String userName = supportTeamCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			supportTeamCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			supportTeamCacheModel.createDate = createDate.getTime();
		}
		else {
			supportTeamCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			supportTeamCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			supportTeamCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		supportTeamCacheModel.parentSupportTeamId = getParentSupportTeamId();

		supportTeamCacheModel.supportLaborId = getSupportLaborId();

		supportTeamCacheModel.locationSupportRegionId = getLocationSupportRegionId();

		supportTeamCacheModel.name = getName();

		String name = supportTeamCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			supportTeamCacheModel.name = null;
		}

		supportTeamCacheModel.description = getDescription();

		String description = supportTeamCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			supportTeamCacheModel.description = null;
		}

		supportTeamCacheModel.type = getType();

		supportTeamCacheModel.assignedWork = getAssignedWork();

		supportTeamCacheModel.maxWork = getMaxWork();

		return supportTeamCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{supportTeamId=");
		sb.append(getSupportTeamId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", parentSupportTeamId=");
		sb.append(getParentSupportTeamId());
		sb.append(", supportLaborId=");
		sb.append(getSupportLaborId());
		sb.append(", locationSupportRegionId=");
		sb.append(getLocationSupportRegionId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", assignedWork=");
		sb.append(getAssignedWork());
		sb.append(", maxWork=");
		sb.append(getMaxWork());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.SupportTeam");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>supportTeamId</column-name><column-value><![CDATA[");
		sb.append(getSupportTeamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentSupportTeamId</column-name><column-value><![CDATA[");
		sb.append(getParentSupportTeamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportLaborId</column-name><column-value><![CDATA[");
		sb.append(getSupportLaborId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>locationSupportRegionId</column-name><column-value><![CDATA[");
		sb.append(getLocationSupportRegionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assignedWork</column-name><column-value><![CDATA[");
		sb.append(getAssignedWork());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maxWork</column-name><column-value><![CDATA[");
		sb.append(getMaxWork());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SupportTeam.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SupportTeam.class
		};
	private long _supportTeamId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _parentSupportTeamId;
	private long _originalParentSupportTeamId;
	private boolean _setOriginalParentSupportTeamId;
	private long _supportLaborId;
	private long _originalSupportLaborId;
	private boolean _setOriginalSupportLaborId;
	private long _locationSupportRegionId;
	private String _name;
	private String _originalName;
	private String _description;
	private int _type;
	private double _assignedWork;
	private double _maxWork;
	private long _columnBitmask;
	private SupportTeam _escapedModel;
}