/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.model.SupportWorkerSeverity;
import com.liferay.osb.model.SupportWorkerSeverityModel;
import com.liferay.osb.model.SupportWorkerSeveritySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SupportWorkerSeverity service. Represents a row in the &quot;OSB_SupportWorkerSeverity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SupportWorkerSeverityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportWorkerSeverityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportWorkerSeverityImpl
 * @see SupportWorkerSeverity
 * @see SupportWorkerSeverityModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SupportWorkerSeverityModelImpl extends BaseModelImpl<SupportWorkerSeverity>
	implements SupportWorkerSeverityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support worker severity model instance should use the {@link SupportWorkerSeverity} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_SupportWorkerSeverity";
	public static final Object[][] TABLE_COLUMNS = {
			{ "supportWorkerSeverityId", Types.BIGINT },
			{ "supportWorkerId", Types.BIGINT },
			{ "severity", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("supportWorkerSeverityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportWorkerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("severity", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_SupportWorkerSeverity (supportWorkerSeverityId LONG not null primary key,supportWorkerId LONG,severity INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_SupportWorkerSeverity";
	public static final String ORDER_BY_JPQL = " ORDER BY supportWorkerSeverity.severity ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_SupportWorkerSeverity.severity ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.SupportWorkerSeverity"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.SupportWorkerSeverity"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.SupportWorkerSeverity"),
			true);
	public static final long SUPPORTWORKERID_COLUMN_BITMASK = 1L;
	public static final long SEVERITY_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SupportWorkerSeverity toModel(
		SupportWorkerSeveritySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SupportWorkerSeverity model = new SupportWorkerSeverityImpl();

		model.setSupportWorkerSeverityId(soapModel.getSupportWorkerSeverityId());
		model.setSupportWorkerId(soapModel.getSupportWorkerId());
		model.setSeverity(soapModel.getSeverity());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SupportWorkerSeverity> toModels(
		SupportWorkerSeveritySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SupportWorkerSeverity> models = new ArrayList<SupportWorkerSeverity>(soapModels.length);

		for (SupportWorkerSeveritySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.SupportWorkerSeverity"));

	public SupportWorkerSeverityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supportWorkerSeverityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupportWorkerSeverityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supportWorkerSeverityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupportWorkerSeverity.class;
	}

	@Override
	public String getModelClassName() {
		return SupportWorkerSeverity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("supportWorkerSeverityId", getSupportWorkerSeverityId());
		attributes.put("supportWorkerId", getSupportWorkerId());
		attributes.put("severity", getSeverity());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long supportWorkerSeverityId = (Long)attributes.get(
				"supportWorkerSeverityId");

		if (supportWorkerSeverityId != null) {
			setSupportWorkerSeverityId(supportWorkerSeverityId);
		}

		Long supportWorkerId = (Long)attributes.get("supportWorkerId");

		if (supportWorkerId != null) {
			setSupportWorkerId(supportWorkerId);
		}

		Integer severity = (Integer)attributes.get("severity");

		if (severity != null) {
			setSeverity(severity);
		}
	}

	@JSON
	@Override
	public long getSupportWorkerSeverityId() {
		return _supportWorkerSeverityId;
	}

	@Override
	public void setSupportWorkerSeverityId(long supportWorkerSeverityId) {
		_supportWorkerSeverityId = supportWorkerSeverityId;
	}

	@JSON
	@Override
	public long getSupportWorkerId() {
		return _supportWorkerId;
	}

	@Override
	public void setSupportWorkerId(long supportWorkerId) {
		_columnBitmask |= SUPPORTWORKERID_COLUMN_BITMASK;

		if (!_setOriginalSupportWorkerId) {
			_setOriginalSupportWorkerId = true;

			_originalSupportWorkerId = _supportWorkerId;
		}

		_supportWorkerId = supportWorkerId;
	}

	public long getOriginalSupportWorkerId() {
		return _originalSupportWorkerId;
	}

	@JSON
	@Override
	public int getSeverity() {
		return _severity;
	}

	@Override
	public void setSeverity(int severity) {
		_columnBitmask = -1L;

		_severity = severity;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SupportWorkerSeverity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupportWorkerSeverity toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SupportWorkerSeverity)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupportWorkerSeverityImpl supportWorkerSeverityImpl = new SupportWorkerSeverityImpl();

		supportWorkerSeverityImpl.setSupportWorkerSeverityId(getSupportWorkerSeverityId());
		supportWorkerSeverityImpl.setSupportWorkerId(getSupportWorkerId());
		supportWorkerSeverityImpl.setSeverity(getSeverity());

		supportWorkerSeverityImpl.resetOriginalValues();

		return supportWorkerSeverityImpl;
	}

	@Override
	public int compareTo(SupportWorkerSeverity supportWorkerSeverity) {
		int value = 0;

		if (getSeverity() < supportWorkerSeverity.getSeverity()) {
			value = -1;
		}
		else if (getSeverity() > supportWorkerSeverity.getSeverity()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SupportWorkerSeverity)) {
			return false;
		}

		SupportWorkerSeverity supportWorkerSeverity = (SupportWorkerSeverity)obj;

		long primaryKey = supportWorkerSeverity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SupportWorkerSeverityModelImpl supportWorkerSeverityModelImpl = this;

		supportWorkerSeverityModelImpl._originalSupportWorkerId = supportWorkerSeverityModelImpl._supportWorkerId;

		supportWorkerSeverityModelImpl._setOriginalSupportWorkerId = false;

		supportWorkerSeverityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SupportWorkerSeverity> toCacheModel() {
		SupportWorkerSeverityCacheModel supportWorkerSeverityCacheModel = new SupportWorkerSeverityCacheModel();

		supportWorkerSeverityCacheModel.supportWorkerSeverityId = getSupportWorkerSeverityId();

		supportWorkerSeverityCacheModel.supportWorkerId = getSupportWorkerId();

		supportWorkerSeverityCacheModel.severity = getSeverity();

		return supportWorkerSeverityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{supportWorkerSeverityId=");
		sb.append(getSupportWorkerSeverityId());
		sb.append(", supportWorkerId=");
		sb.append(getSupportWorkerId());
		sb.append(", severity=");
		sb.append(getSeverity());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.SupportWorkerSeverity");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>supportWorkerSeverityId</column-name><column-value><![CDATA[");
		sb.append(getSupportWorkerSeverityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportWorkerId</column-name><column-value><![CDATA[");
		sb.append(getSupportWorkerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>severity</column-name><column-value><![CDATA[");
		sb.append(getSeverity());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SupportWorkerSeverity.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SupportWorkerSeverity.class
		};
	private long _supportWorkerSeverityId;
	private long _supportWorkerId;
	private long _originalSupportWorkerId;
	private boolean _setOriginalSupportWorkerId;
	private int _severity;
	private long _columnBitmask;
	private SupportWorkerSeverity _escapedModel;
}