/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.model.SupportRegion;
import com.liferay.osb.model.SupportRegionModel;
import com.liferay.osb.model.SupportRegionSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SupportRegion service. Represents a row in the &quot;OSB_SupportRegion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SupportRegionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportRegionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportRegionImpl
 * @see SupportRegion
 * @see SupportRegionModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SupportRegionModelImpl extends BaseModelImpl<SupportRegion>
	implements SupportRegionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support region model instance should use the {@link SupportRegion} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_SupportRegion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "supportRegionId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "timeZoneId", Types.VARCHAR },
			{ "managerUserId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("supportRegionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timeZoneId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("managerUserId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_SupportRegion (supportRegionId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description VARCHAR(75) null,timeZoneId VARCHAR(75) null,managerUserId LONG)";
	public static final String TABLE_SQL_DROP = "drop table OSB_SupportRegion";
	public static final String ORDER_BY_JPQL = " ORDER BY supportRegion.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_SupportRegion.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.SupportRegion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.SupportRegion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.SupportRegion"),
			true);
	public static final long NAME_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SupportRegion toModel(SupportRegionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SupportRegion model = new SupportRegionImpl();

		model.setSupportRegionId(soapModel.getSupportRegionId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setTimeZoneId(soapModel.getTimeZoneId());
		model.setManagerUserId(soapModel.getManagerUserId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SupportRegion> toModels(SupportRegionSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SupportRegion> models = new ArrayList<SupportRegion>(soapModels.length);

		for (SupportRegionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_OSB_ACCOUNTENTRIES_SUPPORTREGIONS_NAME =
		"OSB_AccountEntries_SupportRegions";
	public static final Object[][] MAPPING_TABLE_OSB_ACCOUNTENTRIES_SUPPORTREGIONS_COLUMNS =
		{
			{ "companyId", Types.BIGINT },
			{ "accountEntryId", Types.BIGINT },
			{ "supportRegionId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_ACCOUNTENTRIES_SUPPORTREGIONS_SQL_CREATE =
		"create table OSB_AccountEntries_SupportRegions (companyId LONG not null,accountEntryId LONG not null,supportRegionId LONG not null,primary key (accountEntryId, supportRegionId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_ACCOUNTENTRIES_SUPPORTREGIONS =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_AccountEntries_SupportRegions"),
			true);
	public static final String MAPPING_TABLE_OSB_PARTNERENTRIES_SUPPORTREGIONS_NAME =
		"OSB_PartnerEntries_SupportRegions";
	public static final Object[][] MAPPING_TABLE_OSB_PARTNERENTRIES_SUPPORTREGIONS_COLUMNS =
		{
			{ "companyId", Types.BIGINT },
			{ "partnerEntryId", Types.BIGINT },
			{ "supportRegionId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_PARTNERENTRIES_SUPPORTREGIONS_SQL_CREATE =
		"create table OSB_PartnerEntries_SupportRegions (companyId LONG not null,partnerEntryId LONG not null,supportRegionId LONG not null,primary key (partnerEntryId, supportRegionId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_PARTNERENTRIES_SUPPORTREGIONS =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_PartnerEntries_SupportRegions"),
			true);
	public static final String MAPPING_TABLE_OSB_SUPPORTTEAMS_SUPPORTREGIONS_NAME =
		"OSB_SupportTeams_SupportRegions";
	public static final Object[][] MAPPING_TABLE_OSB_SUPPORTTEAMS_SUPPORTREGIONS_COLUMNS =
		{
			{ "companyId", Types.BIGINT },
			{ "supportRegionId", Types.BIGINT },
			{ "supportTeamId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_SUPPORTTEAMS_SUPPORTREGIONS_SQL_CREATE =
		"create table OSB_SupportTeams_SupportRegions (companyId LONG not null,supportRegionId LONG not null,supportTeamId LONG not null,primary key (supportRegionId, supportTeamId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_SUPPORTTEAMS_SUPPORTREGIONS =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_SupportTeams_SupportRegions"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.SupportRegion"));

	public SupportRegionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supportRegionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupportRegionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supportRegionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupportRegion.class;
	}

	@Override
	public String getModelClassName() {
		return SupportRegion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("supportRegionId", getSupportRegionId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("timeZoneId", getTimeZoneId());
		attributes.put("managerUserId", getManagerUserId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long supportRegionId = (Long)attributes.get("supportRegionId");

		if (supportRegionId != null) {
			setSupportRegionId(supportRegionId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String timeZoneId = (String)attributes.get("timeZoneId");

		if (timeZoneId != null) {
			setTimeZoneId(timeZoneId);
		}

		Long managerUserId = (Long)attributes.get("managerUserId");

		if (managerUserId != null) {
			setManagerUserId(managerUserId);
		}
	}

	@JSON
	@Override
	public long getSupportRegionId() {
		return _supportRegionId;
	}

	@Override
	public void setSupportRegionId(long supportRegionId) {
		_supportRegionId = supportRegionId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getTimeZoneId() {
		if (_timeZoneId == null) {
			return StringPool.BLANK;
		}
		else {
			return _timeZoneId;
		}
	}

	@Override
	public void setTimeZoneId(String timeZoneId) {
		_timeZoneId = timeZoneId;
	}

	@JSON
	@Override
	public long getManagerUserId() {
		return _managerUserId;
	}

	@Override
	public void setManagerUserId(long managerUserId) {
		_managerUserId = managerUserId;
	}

	@Override
	public String getManagerUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getManagerUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setManagerUserUuid(String managerUserUuid) {
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SupportRegion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupportRegion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SupportRegion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupportRegionImpl supportRegionImpl = new SupportRegionImpl();

		supportRegionImpl.setSupportRegionId(getSupportRegionId());
		supportRegionImpl.setCompanyId(getCompanyId());
		supportRegionImpl.setUserId(getUserId());
		supportRegionImpl.setUserName(getUserName());
		supportRegionImpl.setCreateDate(getCreateDate());
		supportRegionImpl.setModifiedDate(getModifiedDate());
		supportRegionImpl.setName(getName());
		supportRegionImpl.setDescription(getDescription());
		supportRegionImpl.setTimeZoneId(getTimeZoneId());
		supportRegionImpl.setManagerUserId(getManagerUserId());

		supportRegionImpl.resetOriginalValues();

		return supportRegionImpl;
	}

	@Override
	public int compareTo(SupportRegion supportRegion) {
		int value = 0;

		value = getName().compareToIgnoreCase(supportRegion.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SupportRegion)) {
			return false;
		}

		SupportRegion supportRegion = (SupportRegion)obj;

		long primaryKey = supportRegion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SupportRegionModelImpl supportRegionModelImpl = this;

		supportRegionModelImpl._setModifiedDate = false;

		supportRegionModelImpl._originalName = supportRegionModelImpl._name;

		supportRegionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SupportRegion> toCacheModel() {
		SupportRegionCacheModel supportRegionCacheModel = new SupportRegionCacheModel();

		supportRegionCacheModel.supportRegionId = getSupportRegionId();

		supportRegionCacheModel.companyId = getCompanyId();

		supportRegionCacheModel.userId = getUserId();

		supportRegionCacheModel.userName = getUserName();

		String userName = supportRegionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			supportRegionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			supportRegionCacheModel.createDate = createDate.getTime();
		}
		else {
			supportRegionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			supportRegionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			supportRegionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		supportRegionCacheModel.name = getName();

		String name = supportRegionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			supportRegionCacheModel.name = null;
		}

		supportRegionCacheModel.description = getDescription();

		String description = supportRegionCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			supportRegionCacheModel.description = null;
		}

		supportRegionCacheModel.timeZoneId = getTimeZoneId();

		String timeZoneId = supportRegionCacheModel.timeZoneId;

		if ((timeZoneId != null) && (timeZoneId.length() == 0)) {
			supportRegionCacheModel.timeZoneId = null;
		}

		supportRegionCacheModel.managerUserId = getManagerUserId();

		return supportRegionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{supportRegionId=");
		sb.append(getSupportRegionId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", timeZoneId=");
		sb.append(getTimeZoneId());
		sb.append(", managerUserId=");
		sb.append(getManagerUserId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.SupportRegion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>supportRegionId</column-name><column-value><![CDATA[");
		sb.append(getSupportRegionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timeZoneId</column-name><column-value><![CDATA[");
		sb.append(getTimeZoneId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>managerUserId</column-name><column-value><![CDATA[");
		sb.append(getManagerUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SupportRegion.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SupportRegion.class
		};
	private long _supportRegionId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _description;
	private String _timeZoneId;
	private long _managerUserId;
	private long _columnBitmask;
	private SupportRegion _escapedModel;
}