/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.model.TicketEntry;
import com.liferay.osb.model.TicketEntryModel;
import com.liferay.osb.model.TicketEntrySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TicketEntry service. Represents a row in the &quot;OSB_TicketEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TicketEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TicketEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketEntryImpl
 * @see TicketEntry
 * @see TicketEntryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TicketEntryModelImpl extends BaseModelImpl<TicketEntry>
	implements TicketEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ticket entry model instance should use the {@link TicketEntry} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TicketEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ticketEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "accountEntryId", Types.BIGINT },
			{ "orderEntryId", Types.BIGINT },
			{ "productEntryId", Types.BIGINT },
			{ "supportResponseId", Types.BIGINT },
			{ "offeringEntryId", Types.BIGINT },
			{ "supportRegionId", Types.BIGINT },
			{ "languageId", Types.VARCHAR },
			{ "ticketId", Types.BIGINT },
			{ "subject", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "reproductionSteps", Types.VARCHAR },
			{ "severity", Types.INTEGER },
			{ "status", Types.INTEGER },
			{ "weight", Types.INTEGER },
			{ "escalationLevel", Types.INTEGER },
			{ "envName", Types.VARCHAR },
			{ "envOS", Types.INTEGER },
			{ "envOSCustom", Types.VARCHAR },
			{ "envDB", Types.INTEGER },
			{ "envJVM", Types.INTEGER },
			{ "envAS", Types.INTEGER },
			{ "envLFR", Types.INTEGER },
			{ "envBrowser", Types.INTEGER },
			{ "envBrowserCustom", Types.VARCHAR },
			{ "envCS", Types.INTEGER },
			{ "envSearch", Types.VARCHAR },
			{ "component", Types.INTEGER },
			{ "subcomponent", Types.INTEGER },
			{ "subcomponentCustom", Types.VARCHAR },
			{ "resolution", Types.INTEGER },
			{ "holdDate", Types.TIMESTAMP },
			{ "closedDate", Types.TIMESTAMP },
			{ "dueDate", Types.TIMESTAMP },
			{ "ignoreDueDate", Types.BOOLEAN },
			{ "customerModifiedDate", Types.TIMESTAMP },
			{ "workerModifiedDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ticketEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("orderEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportResponseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("offeringEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("supportRegionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ticketId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reproductionSteps", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("severity", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("weight", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("escalationLevel", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("envOS", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envOSCustom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("envDB", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envJVM", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envAS", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envLFR", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envBrowser", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envBrowserCustom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("envCS", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("envSearch", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("component", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("subcomponent", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("subcomponentCustom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("resolution", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("holdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("closedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ignoreDueDate", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("customerModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("workerModifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_TicketEntry (ticketEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,accountEntryId LONG,orderEntryId LONG,productEntryId LONG,supportResponseId LONG,offeringEntryId LONG,supportRegionId LONG,languageId VARCHAR(75) null,ticketId LONG,subject VARCHAR(255) null,description STRING null,reproductionSteps STRING null,severity INTEGER,status INTEGER,weight INTEGER,escalationLevel INTEGER,envName VARCHAR(75) null,envOS INTEGER,envOSCustom VARCHAR(150) null,envDB INTEGER,envJVM INTEGER,envAS INTEGER,envLFR INTEGER,envBrowser INTEGER,envBrowserCustom VARCHAR(150) null,envCS INTEGER,envSearch VARCHAR(75) null,component INTEGER,subcomponent INTEGER,subcomponentCustom VARCHAR(150) null,resolution INTEGER,holdDate DATE null,closedDate DATE null,dueDate DATE null,ignoreDueDate BOOLEAN,customerModifiedDate DATE null,workerModifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_TicketEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY ticketEntry.modifiedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_TicketEntry.modifiedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.TicketEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.TicketEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.TicketEntry"),
			true);
	public static final long ACCOUNTENTRYID_COLUMN_BITMASK = 1L;
	public static final long COMPANYID_COLUMN_BITMASK = 2L;
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 4L;
	public static final long OFFERINGENTRYID_COLUMN_BITMASK = 8L;
	public static final long RESOLUTION_COLUMN_BITMASK = 16L;
	public static final long TICKETID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TicketEntry toModel(TicketEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TicketEntry model = new TicketEntryImpl();

		model.setTicketEntryId(soapModel.getTicketEntryId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAccountEntryId(soapModel.getAccountEntryId());
		model.setOrderEntryId(soapModel.getOrderEntryId());
		model.setProductEntryId(soapModel.getProductEntryId());
		model.setSupportResponseId(soapModel.getSupportResponseId());
		model.setOfferingEntryId(soapModel.getOfferingEntryId());
		model.setSupportRegionId(soapModel.getSupportRegionId());
		model.setLanguageId(soapModel.getLanguageId());
		model.setTicketId(soapModel.getTicketId());
		model.setSubject(soapModel.getSubject());
		model.setDescription(soapModel.getDescription());
		model.setReproductionSteps(soapModel.getReproductionSteps());
		model.setSeverity(soapModel.getSeverity());
		model.setStatus(soapModel.getStatus());
		model.setWeight(soapModel.getWeight());
		model.setEscalationLevel(soapModel.getEscalationLevel());
		model.setEnvName(soapModel.getEnvName());
		model.setEnvOS(soapModel.getEnvOS());
		model.setEnvOSCustom(soapModel.getEnvOSCustom());
		model.setEnvDB(soapModel.getEnvDB());
		model.setEnvJVM(soapModel.getEnvJVM());
		model.setEnvAS(soapModel.getEnvAS());
		model.setEnvLFR(soapModel.getEnvLFR());
		model.setEnvBrowser(soapModel.getEnvBrowser());
		model.setEnvBrowserCustom(soapModel.getEnvBrowserCustom());
		model.setEnvCS(soapModel.getEnvCS());
		model.setEnvSearch(soapModel.getEnvSearch());
		model.setComponent(soapModel.getComponent());
		model.setSubcomponent(soapModel.getSubcomponent());
		model.setSubcomponentCustom(soapModel.getSubcomponentCustom());
		model.setResolution(soapModel.getResolution());
		model.setHoldDate(soapModel.getHoldDate());
		model.setClosedDate(soapModel.getClosedDate());
		model.setDueDate(soapModel.getDueDate());
		model.setIgnoreDueDate(soapModel.getIgnoreDueDate());
		model.setCustomerModifiedDate(soapModel.getCustomerModifiedDate());
		model.setWorkerModifiedDate(soapModel.getWorkerModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TicketEntry> toModels(TicketEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TicketEntry> models = new ArrayList<TicketEntry>(soapModels.length);

		for (TicketEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.TicketEntry"));

	public TicketEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ticketEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTicketEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ticketEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TicketEntry.class;
	}

	@Override
	public String getModelClassName() {
		return TicketEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ticketEntryId", getTicketEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("accountEntryId", getAccountEntryId());
		attributes.put("orderEntryId", getOrderEntryId());
		attributes.put("productEntryId", getProductEntryId());
		attributes.put("supportResponseId", getSupportResponseId());
		attributes.put("offeringEntryId", getOfferingEntryId());
		attributes.put("supportRegionId", getSupportRegionId());
		attributes.put("languageId", getLanguageId());
		attributes.put("ticketId", getTicketId());
		attributes.put("subject", getSubject());
		attributes.put("description", getDescription());
		attributes.put("reproductionSteps", getReproductionSteps());
		attributes.put("severity", getSeverity());
		attributes.put("status", getStatus());
		attributes.put("weight", getWeight());
		attributes.put("escalationLevel", getEscalationLevel());
		attributes.put("envName", getEnvName());
		attributes.put("envOS", getEnvOS());
		attributes.put("envOSCustom", getEnvOSCustom());
		attributes.put("envDB", getEnvDB());
		attributes.put("envJVM", getEnvJVM());
		attributes.put("envAS", getEnvAS());
		attributes.put("envLFR", getEnvLFR());
		attributes.put("envBrowser", getEnvBrowser());
		attributes.put("envBrowserCustom", getEnvBrowserCustom());
		attributes.put("envCS", getEnvCS());
		attributes.put("envSearch", getEnvSearch());
		attributes.put("component", getComponent());
		attributes.put("subcomponent", getSubcomponent());
		attributes.put("subcomponentCustom", getSubcomponentCustom());
		attributes.put("resolution", getResolution());
		attributes.put("holdDate", getHoldDate());
		attributes.put("closedDate", getClosedDate());
		attributes.put("dueDate", getDueDate());
		attributes.put("ignoreDueDate", getIgnoreDueDate());
		attributes.put("customerModifiedDate", getCustomerModifiedDate());
		attributes.put("workerModifiedDate", getWorkerModifiedDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ticketEntryId = (Long)attributes.get("ticketEntryId");

		if (ticketEntryId != null) {
			setTicketEntryId(ticketEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long accountEntryId = (Long)attributes.get("accountEntryId");

		if (accountEntryId != null) {
			setAccountEntryId(accountEntryId);
		}

		Long orderEntryId = (Long)attributes.get("orderEntryId");

		if (orderEntryId != null) {
			setOrderEntryId(orderEntryId);
		}

		Long productEntryId = (Long)attributes.get("productEntryId");

		if (productEntryId != null) {
			setProductEntryId(productEntryId);
		}

		Long supportResponseId = (Long)attributes.get("supportResponseId");

		if (supportResponseId != null) {
			setSupportResponseId(supportResponseId);
		}

		Long offeringEntryId = (Long)attributes.get("offeringEntryId");

		if (offeringEntryId != null) {
			setOfferingEntryId(offeringEntryId);
		}

		Long supportRegionId = (Long)attributes.get("supportRegionId");

		if (supportRegionId != null) {
			setSupportRegionId(supportRegionId);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		Long ticketId = (Long)attributes.get("ticketId");

		if (ticketId != null) {
			setTicketId(ticketId);
		}

		String subject = (String)attributes.get("subject");

		if (subject != null) {
			setSubject(subject);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String reproductionSteps = (String)attributes.get("reproductionSteps");

		if (reproductionSteps != null) {
			setReproductionSteps(reproductionSteps);
		}

		Integer severity = (Integer)attributes.get("severity");

		if (severity != null) {
			setSeverity(severity);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Integer weight = (Integer)attributes.get("weight");

		if (weight != null) {
			setWeight(weight);
		}

		Integer escalationLevel = (Integer)attributes.get("escalationLevel");

		if (escalationLevel != null) {
			setEscalationLevel(escalationLevel);
		}

		String envName = (String)attributes.get("envName");

		if (envName != null) {
			setEnvName(envName);
		}

		Integer envOS = (Integer)attributes.get("envOS");

		if (envOS != null) {
			setEnvOS(envOS);
		}

		String envOSCustom = (String)attributes.get("envOSCustom");

		if (envOSCustom != null) {
			setEnvOSCustom(envOSCustom);
		}

		Integer envDB = (Integer)attributes.get("envDB");

		if (envDB != null) {
			setEnvDB(envDB);
		}

		Integer envJVM = (Integer)attributes.get("envJVM");

		if (envJVM != null) {
			setEnvJVM(envJVM);
		}

		Integer envAS = (Integer)attributes.get("envAS");

		if (envAS != null) {
			setEnvAS(envAS);
		}

		Integer envLFR = (Integer)attributes.get("envLFR");

		if (envLFR != null) {
			setEnvLFR(envLFR);
		}

		Integer envBrowser = (Integer)attributes.get("envBrowser");

		if (envBrowser != null) {
			setEnvBrowser(envBrowser);
		}

		String envBrowserCustom = (String)attributes.get("envBrowserCustom");

		if (envBrowserCustom != null) {
			setEnvBrowserCustom(envBrowserCustom);
		}

		Integer envCS = (Integer)attributes.get("envCS");

		if (envCS != null) {
			setEnvCS(envCS);
		}

		String envSearch = (String)attributes.get("envSearch");

		if (envSearch != null) {
			setEnvSearch(envSearch);
		}

		Integer component = (Integer)attributes.get("component");

		if (component != null) {
			setComponent(component);
		}

		Integer subcomponent = (Integer)attributes.get("subcomponent");

		if (subcomponent != null) {
			setSubcomponent(subcomponent);
		}

		String subcomponentCustom = (String)attributes.get("subcomponentCustom");

		if (subcomponentCustom != null) {
			setSubcomponentCustom(subcomponentCustom);
		}

		Integer resolution = (Integer)attributes.get("resolution");

		if (resolution != null) {
			setResolution(resolution);
		}

		Date holdDate = (Date)attributes.get("holdDate");

		if (holdDate != null) {
			setHoldDate(holdDate);
		}

		Date closedDate = (Date)attributes.get("closedDate");

		if (closedDate != null) {
			setClosedDate(closedDate);
		}

		Date dueDate = (Date)attributes.get("dueDate");

		if (dueDate != null) {
			setDueDate(dueDate);
		}

		Boolean ignoreDueDate = (Boolean)attributes.get("ignoreDueDate");

		if (ignoreDueDate != null) {
			setIgnoreDueDate(ignoreDueDate);
		}

		Date customerModifiedDate = (Date)attributes.get("customerModifiedDate");

		if (customerModifiedDate != null) {
			setCustomerModifiedDate(customerModifiedDate);
		}

		Date workerModifiedDate = (Date)attributes.get("workerModifiedDate");

		if (workerModifiedDate != null) {
			setWorkerModifiedDate(workerModifiedDate);
		}
	}

	@JSON
	@Override
	public long getTicketEntryId() {
		return _ticketEntryId;
	}

	@Override
	public void setTicketEntryId(long ticketEntryId) {
		_ticketEntryId = ticketEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		if (_originalModifiedDate == null) {
			_originalModifiedDate = _modifiedDate;
		}

		_modifiedDate = modifiedDate;
	}

	public Date getOriginalModifiedDate() {
		return _originalModifiedDate;
	}

	@JSON
	@Override
	public long getAccountEntryId() {
		return _accountEntryId;
	}

	@Override
	public void setAccountEntryId(long accountEntryId) {
		_columnBitmask |= ACCOUNTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAccountEntryId) {
			_setOriginalAccountEntryId = true;

			_originalAccountEntryId = _accountEntryId;
		}

		_accountEntryId = accountEntryId;
	}

	public long getOriginalAccountEntryId() {
		return _originalAccountEntryId;
	}

	@JSON
	@Override
	public long getOrderEntryId() {
		return _orderEntryId;
	}

	@Override
	public void setOrderEntryId(long orderEntryId) {
		_orderEntryId = orderEntryId;
	}

	@JSON
	@Override
	public long getProductEntryId() {
		return _productEntryId;
	}

	@Override
	public void setProductEntryId(long productEntryId) {
		_productEntryId = productEntryId;
	}

	@JSON
	@Override
	public long getSupportResponseId() {
		return _supportResponseId;
	}

	@Override
	public void setSupportResponseId(long supportResponseId) {
		_supportResponseId = supportResponseId;
	}

	@JSON
	@Override
	public long getOfferingEntryId() {
		return _offeringEntryId;
	}

	@Override
	public void setOfferingEntryId(long offeringEntryId) {
		_columnBitmask |= OFFERINGENTRYID_COLUMN_BITMASK;

		if (!_setOriginalOfferingEntryId) {
			_setOriginalOfferingEntryId = true;

			_originalOfferingEntryId = _offeringEntryId;
		}

		_offeringEntryId = offeringEntryId;
	}

	public long getOriginalOfferingEntryId() {
		return _originalOfferingEntryId;
	}

	@JSON
	@Override
	public long getSupportRegionId() {
		return _supportRegionId;
	}

	@Override
	public void setSupportRegionId(long supportRegionId) {
		_supportRegionId = supportRegionId;
	}

	@JSON
	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		_languageId = languageId;
	}

	@JSON
	@Override
	public long getTicketId() {
		return _ticketId;
	}

	@Override
	public void setTicketId(long ticketId) {
		_columnBitmask |= TICKETID_COLUMN_BITMASK;

		if (!_setOriginalTicketId) {
			_setOriginalTicketId = true;

			_originalTicketId = _ticketId;
		}

		_ticketId = ticketId;
	}

	public long getOriginalTicketId() {
		return _originalTicketId;
	}

	@JSON
	@Override
	public String getSubject() {
		if (_subject == null) {
			return StringPool.BLANK;
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		_subject = subject;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getReproductionSteps() {
		if (_reproductionSteps == null) {
			return StringPool.BLANK;
		}
		else {
			return _reproductionSteps;
		}
	}

	@Override
	public void setReproductionSteps(String reproductionSteps) {
		_reproductionSteps = reproductionSteps;
	}

	@JSON
	@Override
	public int getSeverity() {
		return _severity;
	}

	@Override
	public void setSeverity(int severity) {
		_severity = severity;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public int getWeight() {
		return _weight;
	}

	@Override
	public void setWeight(int weight) {
		_weight = weight;
	}

	@JSON
	@Override
	public int getEscalationLevel() {
		return _escalationLevel;
	}

	@Override
	public void setEscalationLevel(int escalationLevel) {
		_escalationLevel = escalationLevel;
	}

	@JSON
	@Override
	public String getEnvName() {
		if (_envName == null) {
			return StringPool.BLANK;
		}
		else {
			return _envName;
		}
	}

	@Override
	public void setEnvName(String envName) {
		_envName = envName;
	}

	@JSON
	@Override
	public int getEnvOS() {
		return _envOS;
	}

	@Override
	public void setEnvOS(int envOS) {
		_envOS = envOS;
	}

	@JSON
	@Override
	public String getEnvOSCustom() {
		if (_envOSCustom == null) {
			return StringPool.BLANK;
		}
		else {
			return _envOSCustom;
		}
	}

	@Override
	public void setEnvOSCustom(String envOSCustom) {
		_envOSCustom = envOSCustom;
	}

	@JSON
	@Override
	public int getEnvDB() {
		return _envDB;
	}

	@Override
	public void setEnvDB(int envDB) {
		_envDB = envDB;
	}

	@JSON
	@Override
	public int getEnvJVM() {
		return _envJVM;
	}

	@Override
	public void setEnvJVM(int envJVM) {
		_envJVM = envJVM;
	}

	@JSON
	@Override
	public int getEnvAS() {
		return _envAS;
	}

	@Override
	public void setEnvAS(int envAS) {
		_envAS = envAS;
	}

	@JSON
	@Override
	public int getEnvLFR() {
		return _envLFR;
	}

	@Override
	public void setEnvLFR(int envLFR) {
		_envLFR = envLFR;
	}

	@JSON
	@Override
	public int getEnvBrowser() {
		return _envBrowser;
	}

	@Override
	public void setEnvBrowser(int envBrowser) {
		_envBrowser = envBrowser;
	}

	@JSON
	@Override
	public String getEnvBrowserCustom() {
		if (_envBrowserCustom == null) {
			return StringPool.BLANK;
		}
		else {
			return _envBrowserCustom;
		}
	}

	@Override
	public void setEnvBrowserCustom(String envBrowserCustom) {
		_envBrowserCustom = envBrowserCustom;
	}

	@JSON
	@Override
	public int getEnvCS() {
		return _envCS;
	}

	@Override
	public void setEnvCS(int envCS) {
		_envCS = envCS;
	}

	@JSON
	@Override
	public String getEnvSearch() {
		if (_envSearch == null) {
			return StringPool.BLANK;
		}
		else {
			return _envSearch;
		}
	}

	@Override
	public void setEnvSearch(String envSearch) {
		_envSearch = envSearch;
	}

	@JSON
	@Override
	public int getComponent() {
		return _component;
	}

	@Override
	public void setComponent(int component) {
		_component = component;
	}

	@JSON
	@Override
	public int getSubcomponent() {
		return _subcomponent;
	}

	@Override
	public void setSubcomponent(int subcomponent) {
		_subcomponent = subcomponent;
	}

	@JSON
	@Override
	public String getSubcomponentCustom() {
		if (_subcomponentCustom == null) {
			return StringPool.BLANK;
		}
		else {
			return _subcomponentCustom;
		}
	}

	@Override
	public void setSubcomponentCustom(String subcomponentCustom) {
		_subcomponentCustom = subcomponentCustom;
	}

	@JSON
	@Override
	public int getResolution() {
		return _resolution;
	}

	@Override
	public void setResolution(int resolution) {
		_columnBitmask |= RESOLUTION_COLUMN_BITMASK;

		if (!_setOriginalResolution) {
			_setOriginalResolution = true;

			_originalResolution = _resolution;
		}

		_resolution = resolution;
	}

	public int getOriginalResolution() {
		return _originalResolution;
	}

	@JSON
	@Override
	public Date getHoldDate() {
		return _holdDate;
	}

	@Override
	public void setHoldDate(Date holdDate) {
		_holdDate = holdDate;
	}

	@JSON
	@Override
	public Date getClosedDate() {
		return _closedDate;
	}

	@Override
	public void setClosedDate(Date closedDate) {
		_closedDate = closedDate;
	}

	@JSON
	@Override
	public Date getDueDate() {
		return _dueDate;
	}

	@Override
	public void setDueDate(Date dueDate) {
		_dueDate = dueDate;
	}

	@JSON
	@Override
	public boolean getIgnoreDueDate() {
		return _ignoreDueDate;
	}

	@JSON
	@Override
	public boolean isIgnoreDueDate() {
		return _ignoreDueDate;
	}

	@Override
	public void setIgnoreDueDate(boolean ignoreDueDate) {
		_ignoreDueDate = ignoreDueDate;
	}

	@JSON
	@Override
	public Date getCustomerModifiedDate() {
		return _customerModifiedDate;
	}

	@Override
	public void setCustomerModifiedDate(Date customerModifiedDate) {
		_customerModifiedDate = customerModifiedDate;
	}

	@JSON
	@Override
	public Date getWorkerModifiedDate() {
		return _workerModifiedDate;
	}

	@Override
	public void setWorkerModifiedDate(Date workerModifiedDate) {
		_workerModifiedDate = workerModifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TicketEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TicketEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TicketEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TicketEntryImpl ticketEntryImpl = new TicketEntryImpl();

		ticketEntryImpl.setTicketEntryId(getTicketEntryId());
		ticketEntryImpl.setCompanyId(getCompanyId());
		ticketEntryImpl.setUserId(getUserId());
		ticketEntryImpl.setUserName(getUserName());
		ticketEntryImpl.setCreateDate(getCreateDate());
		ticketEntryImpl.setModifiedDate(getModifiedDate());
		ticketEntryImpl.setAccountEntryId(getAccountEntryId());
		ticketEntryImpl.setOrderEntryId(getOrderEntryId());
		ticketEntryImpl.setProductEntryId(getProductEntryId());
		ticketEntryImpl.setSupportResponseId(getSupportResponseId());
		ticketEntryImpl.setOfferingEntryId(getOfferingEntryId());
		ticketEntryImpl.setSupportRegionId(getSupportRegionId());
		ticketEntryImpl.setLanguageId(getLanguageId());
		ticketEntryImpl.setTicketId(getTicketId());
		ticketEntryImpl.setSubject(getSubject());
		ticketEntryImpl.setDescription(getDescription());
		ticketEntryImpl.setReproductionSteps(getReproductionSteps());
		ticketEntryImpl.setSeverity(getSeverity());
		ticketEntryImpl.setStatus(getStatus());
		ticketEntryImpl.setWeight(getWeight());
		ticketEntryImpl.setEscalationLevel(getEscalationLevel());
		ticketEntryImpl.setEnvName(getEnvName());
		ticketEntryImpl.setEnvOS(getEnvOS());
		ticketEntryImpl.setEnvOSCustom(getEnvOSCustom());
		ticketEntryImpl.setEnvDB(getEnvDB());
		ticketEntryImpl.setEnvJVM(getEnvJVM());
		ticketEntryImpl.setEnvAS(getEnvAS());
		ticketEntryImpl.setEnvLFR(getEnvLFR());
		ticketEntryImpl.setEnvBrowser(getEnvBrowser());
		ticketEntryImpl.setEnvBrowserCustom(getEnvBrowserCustom());
		ticketEntryImpl.setEnvCS(getEnvCS());
		ticketEntryImpl.setEnvSearch(getEnvSearch());
		ticketEntryImpl.setComponent(getComponent());
		ticketEntryImpl.setSubcomponent(getSubcomponent());
		ticketEntryImpl.setSubcomponentCustom(getSubcomponentCustom());
		ticketEntryImpl.setResolution(getResolution());
		ticketEntryImpl.setHoldDate(getHoldDate());
		ticketEntryImpl.setClosedDate(getClosedDate());
		ticketEntryImpl.setDueDate(getDueDate());
		ticketEntryImpl.setIgnoreDueDate(getIgnoreDueDate());
		ticketEntryImpl.setCustomerModifiedDate(getCustomerModifiedDate());
		ticketEntryImpl.setWorkerModifiedDate(getWorkerModifiedDate());

		ticketEntryImpl.resetOriginalValues();

		return ticketEntryImpl;
	}

	@Override
	public int compareTo(TicketEntry ticketEntry) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(),
				ticketEntry.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TicketEntry)) {
			return false;
		}

		TicketEntry ticketEntry = (TicketEntry)obj;

		long primaryKey = ticketEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TicketEntryModelImpl ticketEntryModelImpl = this;

		ticketEntryModelImpl._originalCompanyId = ticketEntryModelImpl._companyId;

		ticketEntryModelImpl._setOriginalCompanyId = false;

		ticketEntryModelImpl._originalModifiedDate = ticketEntryModelImpl._modifiedDate;

		ticketEntryModelImpl._setModifiedDate = false;

		ticketEntryModelImpl._originalAccountEntryId = ticketEntryModelImpl._accountEntryId;

		ticketEntryModelImpl._setOriginalAccountEntryId = false;

		ticketEntryModelImpl._originalOfferingEntryId = ticketEntryModelImpl._offeringEntryId;

		ticketEntryModelImpl._setOriginalOfferingEntryId = false;

		ticketEntryModelImpl._originalTicketId = ticketEntryModelImpl._ticketId;

		ticketEntryModelImpl._setOriginalTicketId = false;

		ticketEntryModelImpl._originalResolution = ticketEntryModelImpl._resolution;

		ticketEntryModelImpl._setOriginalResolution = false;

		ticketEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TicketEntry> toCacheModel() {
		TicketEntryCacheModel ticketEntryCacheModel = new TicketEntryCacheModel();

		ticketEntryCacheModel.ticketEntryId = getTicketEntryId();

		ticketEntryCacheModel.companyId = getCompanyId();

		ticketEntryCacheModel.userId = getUserId();

		ticketEntryCacheModel.userName = getUserName();

		String userName = ticketEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ticketEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ticketEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			ticketEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ticketEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ticketEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ticketEntryCacheModel.accountEntryId = getAccountEntryId();

		ticketEntryCacheModel.orderEntryId = getOrderEntryId();

		ticketEntryCacheModel.productEntryId = getProductEntryId();

		ticketEntryCacheModel.supportResponseId = getSupportResponseId();

		ticketEntryCacheModel.offeringEntryId = getOfferingEntryId();

		ticketEntryCacheModel.supportRegionId = getSupportRegionId();

		ticketEntryCacheModel.languageId = getLanguageId();

		String languageId = ticketEntryCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			ticketEntryCacheModel.languageId = null;
		}

		ticketEntryCacheModel.ticketId = getTicketId();

		ticketEntryCacheModel.subject = getSubject();

		String subject = ticketEntryCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			ticketEntryCacheModel.subject = null;
		}

		ticketEntryCacheModel.description = getDescription();

		String description = ticketEntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			ticketEntryCacheModel.description = null;
		}

		ticketEntryCacheModel.reproductionSteps = getReproductionSteps();

		String reproductionSteps = ticketEntryCacheModel.reproductionSteps;

		if ((reproductionSteps != null) && (reproductionSteps.length() == 0)) {
			ticketEntryCacheModel.reproductionSteps = null;
		}

		ticketEntryCacheModel.severity = getSeverity();

		ticketEntryCacheModel.status = getStatus();

		ticketEntryCacheModel.weight = getWeight();

		ticketEntryCacheModel.escalationLevel = getEscalationLevel();

		ticketEntryCacheModel.envName = getEnvName();

		String envName = ticketEntryCacheModel.envName;

		if ((envName != null) && (envName.length() == 0)) {
			ticketEntryCacheModel.envName = null;
		}

		ticketEntryCacheModel.envOS = getEnvOS();

		ticketEntryCacheModel.envOSCustom = getEnvOSCustom();

		String envOSCustom = ticketEntryCacheModel.envOSCustom;

		if ((envOSCustom != null) && (envOSCustom.length() == 0)) {
			ticketEntryCacheModel.envOSCustom = null;
		}

		ticketEntryCacheModel.envDB = getEnvDB();

		ticketEntryCacheModel.envJVM = getEnvJVM();

		ticketEntryCacheModel.envAS = getEnvAS();

		ticketEntryCacheModel.envLFR = getEnvLFR();

		ticketEntryCacheModel.envBrowser = getEnvBrowser();

		ticketEntryCacheModel.envBrowserCustom = getEnvBrowserCustom();

		String envBrowserCustom = ticketEntryCacheModel.envBrowserCustom;

		if ((envBrowserCustom != null) && (envBrowserCustom.length() == 0)) {
			ticketEntryCacheModel.envBrowserCustom = null;
		}

		ticketEntryCacheModel.envCS = getEnvCS();

		ticketEntryCacheModel.envSearch = getEnvSearch();

		String envSearch = ticketEntryCacheModel.envSearch;

		if ((envSearch != null) && (envSearch.length() == 0)) {
			ticketEntryCacheModel.envSearch = null;
		}

		ticketEntryCacheModel.component = getComponent();

		ticketEntryCacheModel.subcomponent = getSubcomponent();

		ticketEntryCacheModel.subcomponentCustom = getSubcomponentCustom();

		String subcomponentCustom = ticketEntryCacheModel.subcomponentCustom;

		if ((subcomponentCustom != null) && (subcomponentCustom.length() == 0)) {
			ticketEntryCacheModel.subcomponentCustom = null;
		}

		ticketEntryCacheModel.resolution = getResolution();

		Date holdDate = getHoldDate();

		if (holdDate != null) {
			ticketEntryCacheModel.holdDate = holdDate.getTime();
		}
		else {
			ticketEntryCacheModel.holdDate = Long.MIN_VALUE;
		}

		Date closedDate = getClosedDate();

		if (closedDate != null) {
			ticketEntryCacheModel.closedDate = closedDate.getTime();
		}
		else {
			ticketEntryCacheModel.closedDate = Long.MIN_VALUE;
		}

		Date dueDate = getDueDate();

		if (dueDate != null) {
			ticketEntryCacheModel.dueDate = dueDate.getTime();
		}
		else {
			ticketEntryCacheModel.dueDate = Long.MIN_VALUE;
		}

		ticketEntryCacheModel.ignoreDueDate = getIgnoreDueDate();

		Date customerModifiedDate = getCustomerModifiedDate();

		if (customerModifiedDate != null) {
			ticketEntryCacheModel.customerModifiedDate = customerModifiedDate.getTime();
		}
		else {
			ticketEntryCacheModel.customerModifiedDate = Long.MIN_VALUE;
		}

		Date workerModifiedDate = getWorkerModifiedDate();

		if (workerModifiedDate != null) {
			ticketEntryCacheModel.workerModifiedDate = workerModifiedDate.getTime();
		}
		else {
			ticketEntryCacheModel.workerModifiedDate = Long.MIN_VALUE;
		}

		return ticketEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(85);

		sb.append("{ticketEntryId=");
		sb.append(getTicketEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", accountEntryId=");
		sb.append(getAccountEntryId());
		sb.append(", orderEntryId=");
		sb.append(getOrderEntryId());
		sb.append(", productEntryId=");
		sb.append(getProductEntryId());
		sb.append(", supportResponseId=");
		sb.append(getSupportResponseId());
		sb.append(", offeringEntryId=");
		sb.append(getOfferingEntryId());
		sb.append(", supportRegionId=");
		sb.append(getSupportRegionId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", ticketId=");
		sb.append(getTicketId());
		sb.append(", subject=");
		sb.append(getSubject());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", reproductionSteps=");
		sb.append(getReproductionSteps());
		sb.append(", severity=");
		sb.append(getSeverity());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", weight=");
		sb.append(getWeight());
		sb.append(", escalationLevel=");
		sb.append(getEscalationLevel());
		sb.append(", envName=");
		sb.append(getEnvName());
		sb.append(", envOS=");
		sb.append(getEnvOS());
		sb.append(", envOSCustom=");
		sb.append(getEnvOSCustom());
		sb.append(", envDB=");
		sb.append(getEnvDB());
		sb.append(", envJVM=");
		sb.append(getEnvJVM());
		sb.append(", envAS=");
		sb.append(getEnvAS());
		sb.append(", envLFR=");
		sb.append(getEnvLFR());
		sb.append(", envBrowser=");
		sb.append(getEnvBrowser());
		sb.append(", envBrowserCustom=");
		sb.append(getEnvBrowserCustom());
		sb.append(", envCS=");
		sb.append(getEnvCS());
		sb.append(", envSearch=");
		sb.append(getEnvSearch());
		sb.append(", component=");
		sb.append(getComponent());
		sb.append(", subcomponent=");
		sb.append(getSubcomponent());
		sb.append(", subcomponentCustom=");
		sb.append(getSubcomponentCustom());
		sb.append(", resolution=");
		sb.append(getResolution());
		sb.append(", holdDate=");
		sb.append(getHoldDate());
		sb.append(", closedDate=");
		sb.append(getClosedDate());
		sb.append(", dueDate=");
		sb.append(getDueDate());
		sb.append(", ignoreDueDate=");
		sb.append(getIgnoreDueDate());
		sb.append(", customerModifiedDate=");
		sb.append(getCustomerModifiedDate());
		sb.append(", workerModifiedDate=");
		sb.append(getWorkerModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(130);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.TicketEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ticketEntryId</column-name><column-value><![CDATA[");
		sb.append(getTicketEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountEntryId</column-name><column-value><![CDATA[");
		sb.append(getAccountEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderEntryId</column-name><column-value><![CDATA[");
		sb.append(getOrderEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productEntryId</column-name><column-value><![CDATA[");
		sb.append(getProductEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportResponseId</column-name><column-value><![CDATA[");
		sb.append(getSupportResponseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>offeringEntryId</column-name><column-value><![CDATA[");
		sb.append(getOfferingEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>supportRegionId</column-name><column-value><![CDATA[");
		sb.append(getSupportRegionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ticketId</column-name><column-value><![CDATA[");
		sb.append(getTicketId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subject</column-name><column-value><![CDATA[");
		sb.append(getSubject());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reproductionSteps</column-name><column-value><![CDATA[");
		sb.append(getReproductionSteps());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>severity</column-name><column-value><![CDATA[");
		sb.append(getSeverity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>weight</column-name><column-value><![CDATA[");
		sb.append(getWeight());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>escalationLevel</column-name><column-value><![CDATA[");
		sb.append(getEscalationLevel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envName</column-name><column-value><![CDATA[");
		sb.append(getEnvName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envOS</column-name><column-value><![CDATA[");
		sb.append(getEnvOS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envOSCustom</column-name><column-value><![CDATA[");
		sb.append(getEnvOSCustom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envDB</column-name><column-value><![CDATA[");
		sb.append(getEnvDB());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envJVM</column-name><column-value><![CDATA[");
		sb.append(getEnvJVM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envAS</column-name><column-value><![CDATA[");
		sb.append(getEnvAS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envLFR</column-name><column-value><![CDATA[");
		sb.append(getEnvLFR());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envBrowser</column-name><column-value><![CDATA[");
		sb.append(getEnvBrowser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envBrowserCustom</column-name><column-value><![CDATA[");
		sb.append(getEnvBrowserCustom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envCS</column-name><column-value><![CDATA[");
		sb.append(getEnvCS());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>envSearch</column-name><column-value><![CDATA[");
		sb.append(getEnvSearch());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>component</column-name><column-value><![CDATA[");
		sb.append(getComponent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subcomponent</column-name><column-value><![CDATA[");
		sb.append(getSubcomponent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subcomponentCustom</column-name><column-value><![CDATA[");
		sb.append(getSubcomponentCustom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resolution</column-name><column-value><![CDATA[");
		sb.append(getResolution());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>holdDate</column-name><column-value><![CDATA[");
		sb.append(getHoldDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>closedDate</column-name><column-value><![CDATA[");
		sb.append(getClosedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dueDate</column-name><column-value><![CDATA[");
		sb.append(getDueDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ignoreDueDate</column-name><column-value><![CDATA[");
		sb.append(getIgnoreDueDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getCustomerModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>workerModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getWorkerModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TicketEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TicketEntry.class
		};
	private long _ticketEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private Date _originalModifiedDate;
	private boolean _setModifiedDate;
	private long _accountEntryId;
	private long _originalAccountEntryId;
	private boolean _setOriginalAccountEntryId;
	private long _orderEntryId;
	private long _productEntryId;
	private long _supportResponseId;
	private long _offeringEntryId;
	private long _originalOfferingEntryId;
	private boolean _setOriginalOfferingEntryId;
	private long _supportRegionId;
	private String _languageId;
	private long _ticketId;
	private long _originalTicketId;
	private boolean _setOriginalTicketId;
	private String _subject;
	private String _description;
	private String _reproductionSteps;
	private int _severity;
	private int _status;
	private int _weight;
	private int _escalationLevel;
	private String _envName;
	private int _envOS;
	private String _envOSCustom;
	private int _envDB;
	private int _envJVM;
	private int _envAS;
	private int _envLFR;
	private int _envBrowser;
	private String _envBrowserCustom;
	private int _envCS;
	private String _envSearch;
	private int _component;
	private int _subcomponent;
	private String _subcomponentCustom;
	private int _resolution;
	private int _originalResolution;
	private boolean _setOriginalResolution;
	private Date _holdDate;
	private Date _closedDate;
	private Date _dueDate;
	private boolean _ignoreDueDate;
	private Date _customerModifiedDate;
	private Date _workerModifiedDate;
	private long _columnBitmask;
	private TicketEntry _escapedModel;
}