/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.TicketCannedResponse;
import com.liferay.osb.model.TicketCannedResponseModel;
import com.liferay.osb.model.TicketCannedResponseSoap;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * The base model implementation for the TicketCannedResponse service. Represents a row in the &quot;OSB_TicketCannedResponse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.TicketCannedResponseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TicketCannedResponseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketCannedResponseImpl
 * @see com.liferay.osb.model.TicketCannedResponse
 * @see com.liferay.osb.model.TicketCannedResponseModel
 * @generated
 */
@JSON(strict = true)
public class TicketCannedResponseModelImpl extends BaseModelImpl<TicketCannedResponse>
	implements TicketCannedResponseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ticket canned response model instance should use the {@link com.liferay.osb.model.TicketCannedResponse} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TicketCannedResponse";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ticketCannedResponseId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "content", Types.VARCHAR },
			{ "useCount", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_TicketCannedResponse (ticketCannedResponseId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name STRING null,content STRING null,useCount INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_TicketCannedResponse";
	public static final String ORDER_BY_JPQL = " ORDER BY ticketCannedResponse.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_TicketCannedResponse.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.TicketCannedResponse"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.TicketCannedResponse"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TicketCannedResponse toModel(
		TicketCannedResponseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TicketCannedResponse model = new TicketCannedResponseImpl();

		model.setTicketCannedResponseId(soapModel.getTicketCannedResponseId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setContent(soapModel.getContent());
		model.setUseCount(soapModel.getUseCount());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TicketCannedResponse> toModels(
		TicketCannedResponseSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TicketCannedResponse> models = new ArrayList<TicketCannedResponse>(soapModels.length);

		for (TicketCannedResponseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.TicketCannedResponse"));

	public TicketCannedResponseModelImpl() {
	}

	public long getPrimaryKey() {
		return _ticketCannedResponseId;
	}

	public void setPrimaryKey(long primaryKey) {
		setTicketCannedResponseId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_ticketCannedResponseId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TicketCannedResponse.class;
	}

	public String getModelClassName() {
		return TicketCannedResponse.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ticketCannedResponseId", getTicketCannedResponseId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("content", getContent());
		attributes.put("useCount", getUseCount());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ticketCannedResponseId = (Long)attributes.get(
				"ticketCannedResponseId");

		if (ticketCannedResponseId != null) {
			setTicketCannedResponseId(ticketCannedResponseId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		Integer useCount = (Integer)attributes.get("useCount");

		if (useCount != null) {
			setUseCount(useCount);
		}
	}

	@JSON
	public long getTicketCannedResponseId() {
		return _ticketCannedResponseId;
	}

	public void setTicketCannedResponseId(long ticketCannedResponseId) {
		_ticketCannedResponseId = ticketCannedResponseId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getName(), languageId,
			useDefault);
	}

	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	public void setName(String name) {
		_name = name;
	}

	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getDefault());
	}

	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(LocalizationUtil.updateLocalization(getName(), "Name",
					name, languageId, defaultLanguageId));
		}
		else {
			setName(LocalizationUtil.removeLocalization(getName(), "Name",
					languageId));
		}
	}

	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getDefault());
	}

	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String name = nameMap.get(locale);

			setName(name, locale, defaultLocale);
		}
	}

	@JSON
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public String getContent(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getContent(languageId);
	}

	public String getContent(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getContent(languageId, useDefault);
	}

	public String getContent(String languageId) {
		return LocalizationUtil.getLocalization(getContent(), languageId);
	}

	public String getContent(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getContent(), languageId,
			useDefault);
	}

	public String getContentCurrentLanguageId() {
		return _contentCurrentLanguageId;
	}

	@JSON
	public String getContentCurrentValue() {
		Locale locale = getLocale(_contentCurrentLanguageId);

		return getContent(locale);
	}

	public Map<Locale, String> getContentMap() {
		return LocalizationUtil.getLocalizationMap(getContent());
	}

	public void setContent(String content) {
		_content = content;
	}

	public void setContent(String content, Locale locale) {
		setContent(content, locale, LocaleUtil.getDefault());
	}

	public void setContent(String content, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(content)) {
			setContent(LocalizationUtil.updateLocalization(getContent(),
					"Content", content, languageId, defaultLanguageId));
		}
		else {
			setContent(LocalizationUtil.removeLocalization(getContent(),
					"Content", languageId));
		}
	}

	public void setContentCurrentLanguageId(String languageId) {
		_contentCurrentLanguageId = languageId;
	}

	public void setContentMap(Map<Locale, String> contentMap) {
		setContentMap(contentMap, LocaleUtil.getDefault());
	}

	public void setContentMap(Map<Locale, String> contentMap,
		Locale defaultLocale) {
		if (contentMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String content = contentMap.get(locale);

			setContent(content, locale, defaultLocale);
		}
	}

	@JSON
	public int getUseCount() {
		return _useCount;
	}

	public void setUseCount(int useCount) {
		_useCount = useCount;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TicketCannedResponse.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		setName(getName(defaultImportLocale), defaultImportLocale,
			defaultImportLocale);
		setContent(getContent(defaultImportLocale), defaultImportLocale,
			defaultImportLocale);
	}

	@Override
	public TicketCannedResponse toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TicketCannedResponse)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public TicketCannedResponse toUnescapedModel() {
		return (TicketCannedResponse)this;
	}

	@Override
	public Object clone() {
		TicketCannedResponseImpl ticketCannedResponseImpl = new TicketCannedResponseImpl();

		ticketCannedResponseImpl.setTicketCannedResponseId(getTicketCannedResponseId());
		ticketCannedResponseImpl.setUserId(getUserId());
		ticketCannedResponseImpl.setUserName(getUserName());
		ticketCannedResponseImpl.setCreateDate(getCreateDate());
		ticketCannedResponseImpl.setModifiedDate(getModifiedDate());
		ticketCannedResponseImpl.setName(getName());
		ticketCannedResponseImpl.setContent(getContent());
		ticketCannedResponseImpl.setUseCount(getUseCount());

		ticketCannedResponseImpl.resetOriginalValues();

		return ticketCannedResponseImpl;
	}

	public int compareTo(TicketCannedResponse ticketCannedResponse) {
		int value = 0;

		value = getName().toLowerCase()
					.compareTo(ticketCannedResponse.getName().toLowerCase());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TicketCannedResponse)) {
			return false;
		}

		TicketCannedResponse ticketCannedResponse = (TicketCannedResponse)obj;

		long primaryKey = ticketCannedResponse.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TicketCannedResponse> toCacheModel() {
		TicketCannedResponseCacheModel ticketCannedResponseCacheModel = new TicketCannedResponseCacheModel();

		ticketCannedResponseCacheModel.ticketCannedResponseId = getTicketCannedResponseId();

		ticketCannedResponseCacheModel.userId = getUserId();

		ticketCannedResponseCacheModel.userName = getUserName();

		String userName = ticketCannedResponseCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ticketCannedResponseCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ticketCannedResponseCacheModel.createDate = createDate.getTime();
		}
		else {
			ticketCannedResponseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ticketCannedResponseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ticketCannedResponseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ticketCannedResponseCacheModel.name = getName();

		String name = ticketCannedResponseCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			ticketCannedResponseCacheModel.name = null;
		}

		ticketCannedResponseCacheModel.content = getContent();

		String content = ticketCannedResponseCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			ticketCannedResponseCacheModel.content = null;
		}

		ticketCannedResponseCacheModel.useCount = getUseCount();

		return ticketCannedResponseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{ticketCannedResponseId=");
		sb.append(getTicketCannedResponseId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", useCount=");
		sb.append(getUseCount());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.TicketCannedResponse");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ticketCannedResponseId</column-name><column-value><![CDATA[");
		sb.append(getTicketCannedResponseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>useCount</column-name><column-value><![CDATA[");
		sb.append(getUseCount());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TicketCannedResponse.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TicketCannedResponse.class
		};
	private long _ticketCannedResponseId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _content;
	private String _contentCurrentLanguageId;
	private int _useCount;
	private TicketCannedResponse _escapedModel;
}