/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.TrainingExamResult;
import com.liferay.osb.model.TrainingExamResultModel;
import com.liferay.osb.model.TrainingExamResultSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TrainingExamResult service. Represents a row in the &quot;OSB_TrainingExamResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.TrainingExamResultModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingExamResultImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingExamResultImpl
 * @see com.liferay.osb.model.TrainingExamResult
 * @see com.liferay.osb.model.TrainingExamResultModel
 * @generated
 */
@JSON(strict = true)
public class TrainingExamResultModelImpl extends BaseModelImpl<TrainingExamResult>
	implements TrainingExamResultModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training exam result model instance should use the {@link com.liferay.osb.model.TrainingExamResult} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TrainingExamResult";
	public static final Object[][] TABLE_COLUMNS = {
			{ "trainingExamResultId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "trainingExamId", Types.BIGINT },
			{ "recordType", Types.INTEGER },
			{ "registrationNumber", Types.VARCHAR },
			{ "formKey", Types.VARCHAR },
			{ "startDate", Types.TIMESTAMP },
			{ "testScore", Types.VARCHAR },
			{ "correctCount", Types.INTEGER },
			{ "incorrectCount", Types.INTEGER },
			{ "skippedCount", Types.INTEGER },
			{ "grade", Types.INTEGER },
			{ "status", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_TrainingExamResult (trainingExamResultId LONG not null primary key,createDate DATE null,trainingExamId LONG,recordType INTEGER,registrationNumber VARCHAR(75) null,formKey VARCHAR(75) null,startDate DATE null,testScore VARCHAR(75) null,correctCount INTEGER,incorrectCount INTEGER,skippedCount INTEGER,grade INTEGER,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_TrainingExamResult";
	public static final String ORDER_BY_JPQL = " ORDER BY trainingExamResult.startDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_TrainingExamResult.startDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.TrainingExamResult"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.TrainingExamResult"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.TrainingExamResult"),
			true);
	public static long CREATEDATE_COLUMN_BITMASK = 1L;
	public static long GRADE_COLUMN_BITMASK = 2L;
	public static long REGISTRATIONNUMBER_COLUMN_BITMASK = 4L;
	public static long STARTDATE_COLUMN_BITMASK = 8L;
	public static long STATUS_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TrainingExamResult toModel(TrainingExamResultSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TrainingExamResult model = new TrainingExamResultImpl();

		model.setTrainingExamResultId(soapModel.getTrainingExamResultId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setTrainingExamId(soapModel.getTrainingExamId());
		model.setRecordType(soapModel.getRecordType());
		model.setRegistrationNumber(soapModel.getRegistrationNumber());
		model.setFormKey(soapModel.getFormKey());
		model.setStartDate(soapModel.getStartDate());
		model.setTestScore(soapModel.getTestScore());
		model.setCorrectCount(soapModel.getCorrectCount());
		model.setIncorrectCount(soapModel.getIncorrectCount());
		model.setSkippedCount(soapModel.getSkippedCount());
		model.setGrade(soapModel.getGrade());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TrainingExamResult> toModels(
		TrainingExamResultSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TrainingExamResult> models = new ArrayList<TrainingExamResult>(soapModels.length);

		for (TrainingExamResultSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.TrainingExamResult"));

	public TrainingExamResultModelImpl() {
	}

	public long getPrimaryKey() {
		return _trainingExamResultId;
	}

	public void setPrimaryKey(long primaryKey) {
		setTrainingExamResultId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_trainingExamResultId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TrainingExamResult.class;
	}

	public String getModelClassName() {
		return TrainingExamResult.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("trainingExamResultId", getTrainingExamResultId());
		attributes.put("createDate", getCreateDate());
		attributes.put("trainingExamId", getTrainingExamId());
		attributes.put("recordType", getRecordType());
		attributes.put("registrationNumber", getRegistrationNumber());
		attributes.put("formKey", getFormKey());
		attributes.put("startDate", getStartDate());
		attributes.put("testScore", getTestScore());
		attributes.put("correctCount", getCorrectCount());
		attributes.put("incorrectCount", getIncorrectCount());
		attributes.put("skippedCount", getSkippedCount());
		attributes.put("grade", getGrade());
		attributes.put("status", getStatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long trainingExamResultId = (Long)attributes.get("trainingExamResultId");

		if (trainingExamResultId != null) {
			setTrainingExamResultId(trainingExamResultId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long trainingExamId = (Long)attributes.get("trainingExamId");

		if (trainingExamId != null) {
			setTrainingExamId(trainingExamId);
		}

		Integer recordType = (Integer)attributes.get("recordType");

		if (recordType != null) {
			setRecordType(recordType);
		}

		String registrationNumber = (String)attributes.get("registrationNumber");

		if (registrationNumber != null) {
			setRegistrationNumber(registrationNumber);
		}

		String formKey = (String)attributes.get("formKey");

		if (formKey != null) {
			setFormKey(formKey);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		String testScore = (String)attributes.get("testScore");

		if (testScore != null) {
			setTestScore(testScore);
		}

		Integer correctCount = (Integer)attributes.get("correctCount");

		if (correctCount != null) {
			setCorrectCount(correctCount);
		}

		Integer incorrectCount = (Integer)attributes.get("incorrectCount");

		if (incorrectCount != null) {
			setIncorrectCount(incorrectCount);
		}

		Integer skippedCount = (Integer)attributes.get("skippedCount");

		if (skippedCount != null) {
			setSkippedCount(skippedCount);
		}

		Integer grade = (Integer)attributes.get("grade");

		if (grade != null) {
			setGrade(grade);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	public long getTrainingExamResultId() {
		return _trainingExamResultId;
	}

	public void setTrainingExamResultId(long trainingExamResultId) {
		_trainingExamResultId = trainingExamResultId;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_columnBitmask |= CREATEDATE_COLUMN_BITMASK;

		if (_originalCreateDate == null) {
			_originalCreateDate = _createDate;
		}

		_createDate = createDate;
	}

	public Date getOriginalCreateDate() {
		return _originalCreateDate;
	}

	@JSON
	public long getTrainingExamId() {
		return _trainingExamId;
	}

	public void setTrainingExamId(long trainingExamId) {
		_trainingExamId = trainingExamId;
	}

	@JSON
	public int getRecordType() {
		return _recordType;
	}

	public void setRecordType(int recordType) {
		_recordType = recordType;
	}

	@JSON
	public String getRegistrationNumber() {
		if (_registrationNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _registrationNumber;
		}
	}

	public void setRegistrationNumber(String registrationNumber) {
		_columnBitmask |= REGISTRATIONNUMBER_COLUMN_BITMASK;

		if (_originalRegistrationNumber == null) {
			_originalRegistrationNumber = _registrationNumber;
		}

		_registrationNumber = registrationNumber;
	}

	public String getOriginalRegistrationNumber() {
		return GetterUtil.getString(_originalRegistrationNumber);
	}

	@JSON
	public String getFormKey() {
		if (_formKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _formKey;
		}
	}

	public void setFormKey(String formKey) {
		_formKey = formKey;
	}

	@JSON
	public Date getStartDate() {
		return _startDate;
	}

	public void setStartDate(Date startDate) {
		_columnBitmask = -1L;

		if (_originalStartDate == null) {
			_originalStartDate = _startDate;
		}

		_startDate = startDate;
	}

	public Date getOriginalStartDate() {
		return _originalStartDate;
	}

	@JSON
	public String getTestScore() {
		if (_testScore == null) {
			return StringPool.BLANK;
		}
		else {
			return _testScore;
		}
	}

	public void setTestScore(String testScore) {
		_testScore = testScore;
	}

	@JSON
	public int getCorrectCount() {
		return _correctCount;
	}

	public void setCorrectCount(int correctCount) {
		_correctCount = correctCount;
	}

	@JSON
	public int getIncorrectCount() {
		return _incorrectCount;
	}

	public void setIncorrectCount(int incorrectCount) {
		_incorrectCount = incorrectCount;
	}

	@JSON
	public int getSkippedCount() {
		return _skippedCount;
	}

	public void setSkippedCount(int skippedCount) {
		_skippedCount = skippedCount;
	}

	@JSON
	public int getGrade() {
		return _grade;
	}

	public void setGrade(int grade) {
		_columnBitmask |= GRADE_COLUMN_BITMASK;

		if (!_setOriginalGrade) {
			_setOriginalGrade = true;

			_originalGrade = _grade;
		}

		_grade = grade;
	}

	public int getOriginalGrade() {
		return _originalGrade;
	}

	@JSON
	public int getStatus() {
		return _status;
	}

	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TrainingExamResult.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TrainingExamResult toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TrainingExamResult)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public TrainingExamResult toUnescapedModel() {
		return (TrainingExamResult)this;
	}

	@Override
	public Object clone() {
		TrainingExamResultImpl trainingExamResultImpl = new TrainingExamResultImpl();

		trainingExamResultImpl.setTrainingExamResultId(getTrainingExamResultId());
		trainingExamResultImpl.setCreateDate(getCreateDate());
		trainingExamResultImpl.setTrainingExamId(getTrainingExamId());
		trainingExamResultImpl.setRecordType(getRecordType());
		trainingExamResultImpl.setRegistrationNumber(getRegistrationNumber());
		trainingExamResultImpl.setFormKey(getFormKey());
		trainingExamResultImpl.setStartDate(getStartDate());
		trainingExamResultImpl.setTestScore(getTestScore());
		trainingExamResultImpl.setCorrectCount(getCorrectCount());
		trainingExamResultImpl.setIncorrectCount(getIncorrectCount());
		trainingExamResultImpl.setSkippedCount(getSkippedCount());
		trainingExamResultImpl.setGrade(getGrade());
		trainingExamResultImpl.setStatus(getStatus());

		trainingExamResultImpl.resetOriginalValues();

		return trainingExamResultImpl;
	}

	public int compareTo(TrainingExamResult trainingExamResult) {
		int value = 0;

		value = DateUtil.compareTo(getStartDate(),
				trainingExamResult.getStartDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TrainingExamResult)) {
			return false;
		}

		TrainingExamResult trainingExamResult = (TrainingExamResult)obj;

		long primaryKey = trainingExamResult.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TrainingExamResultModelImpl trainingExamResultModelImpl = this;

		trainingExamResultModelImpl._originalCreateDate = trainingExamResultModelImpl._createDate;

		trainingExamResultModelImpl._originalRegistrationNumber = trainingExamResultModelImpl._registrationNumber;

		trainingExamResultModelImpl._originalStartDate = trainingExamResultModelImpl._startDate;

		trainingExamResultModelImpl._originalGrade = trainingExamResultModelImpl._grade;

		trainingExamResultModelImpl._setOriginalGrade = false;

		trainingExamResultModelImpl._originalStatus = trainingExamResultModelImpl._status;

		trainingExamResultModelImpl._setOriginalStatus = false;

		trainingExamResultModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TrainingExamResult> toCacheModel() {
		TrainingExamResultCacheModel trainingExamResultCacheModel = new TrainingExamResultCacheModel();

		trainingExamResultCacheModel.trainingExamResultId = getTrainingExamResultId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			trainingExamResultCacheModel.createDate = createDate.getTime();
		}
		else {
			trainingExamResultCacheModel.createDate = Long.MIN_VALUE;
		}

		trainingExamResultCacheModel.trainingExamId = getTrainingExamId();

		trainingExamResultCacheModel.recordType = getRecordType();

		trainingExamResultCacheModel.registrationNumber = getRegistrationNumber();

		String registrationNumber = trainingExamResultCacheModel.registrationNumber;

		if ((registrationNumber != null) && (registrationNumber.length() == 0)) {
			trainingExamResultCacheModel.registrationNumber = null;
		}

		trainingExamResultCacheModel.formKey = getFormKey();

		String formKey = trainingExamResultCacheModel.formKey;

		if ((formKey != null) && (formKey.length() == 0)) {
			trainingExamResultCacheModel.formKey = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			trainingExamResultCacheModel.startDate = startDate.getTime();
		}
		else {
			trainingExamResultCacheModel.startDate = Long.MIN_VALUE;
		}

		trainingExamResultCacheModel.testScore = getTestScore();

		String testScore = trainingExamResultCacheModel.testScore;

		if ((testScore != null) && (testScore.length() == 0)) {
			trainingExamResultCacheModel.testScore = null;
		}

		trainingExamResultCacheModel.correctCount = getCorrectCount();

		trainingExamResultCacheModel.incorrectCount = getIncorrectCount();

		trainingExamResultCacheModel.skippedCount = getSkippedCount();

		trainingExamResultCacheModel.grade = getGrade();

		trainingExamResultCacheModel.status = getStatus();

		return trainingExamResultCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{trainingExamResultId=");
		sb.append(getTrainingExamResultId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", trainingExamId=");
		sb.append(getTrainingExamId());
		sb.append(", recordType=");
		sb.append(getRecordType());
		sb.append(", registrationNumber=");
		sb.append(getRegistrationNumber());
		sb.append(", formKey=");
		sb.append(getFormKey());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", testScore=");
		sb.append(getTestScore());
		sb.append(", correctCount=");
		sb.append(getCorrectCount());
		sb.append(", incorrectCount=");
		sb.append(getIncorrectCount());
		sb.append(", skippedCount=");
		sb.append(getSkippedCount());
		sb.append(", grade=");
		sb.append(getGrade());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.TrainingExamResult");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>trainingExamResultId</column-name><column-value><![CDATA[");
		sb.append(getTrainingExamResultId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trainingExamId</column-name><column-value><![CDATA[");
		sb.append(getTrainingExamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>recordType</column-name><column-value><![CDATA[");
		sb.append(getRecordType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registrationNumber</column-name><column-value><![CDATA[");
		sb.append(getRegistrationNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>formKey</column-name><column-value><![CDATA[");
		sb.append(getFormKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testScore</column-name><column-value><![CDATA[");
		sb.append(getTestScore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>correctCount</column-name><column-value><![CDATA[");
		sb.append(getCorrectCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>incorrectCount</column-name><column-value><![CDATA[");
		sb.append(getIncorrectCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>skippedCount</column-name><column-value><![CDATA[");
		sb.append(getSkippedCount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grade</column-name><column-value><![CDATA[");
		sb.append(getGrade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TrainingExamResult.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TrainingExamResult.class
		};
	private long _trainingExamResultId;
	private Date _createDate;
	private Date _originalCreateDate;
	private long _trainingExamId;
	private int _recordType;
	private String _registrationNumber;
	private String _originalRegistrationNumber;
	private String _formKey;
	private Date _startDate;
	private Date _originalStartDate;
	private String _testScore;
	private int _correctCount;
	private int _incorrectCount;
	private int _skippedCount;
	private int _grade;
	private int _originalGrade;
	private boolean _setOriginalGrade;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _columnBitmask;
	private TrainingExamResult _escapedModel;
}