/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.TrainingExam;
import com.liferay.osb.model.TrainingExamModel;
import com.liferay.osb.model.TrainingExamSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TrainingExam service. Represents a row in the &quot;OSB_TrainingExam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.model.TrainingExamModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingExamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingExamImpl
 * @see com.liferay.osb.model.TrainingExam
 * @see com.liferay.osb.model.TrainingExamModel
 * @generated
 */
@JSON(strict = true)
public class TrainingExamModelImpl extends BaseModelImpl<TrainingExam>
	implements TrainingExamModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training exam model instance should use the {@link com.liferay.osb.model.TrainingExam} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TrainingExam";
	public static final Object[][] TABLE_COLUMNS = {
			{ "trainingExamId", Types.BIGINT },
			{ "trainingCertificateTemplateId", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_TrainingExam (trainingExamId LONG not null primary key,trainingCertificateTemplateId LONG,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_TrainingExam";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.model.TrainingExam"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.model.TrainingExam"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.model.TrainingExam"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long TRAININGCERTIFICATETEMPLATEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TrainingExam toModel(TrainingExamSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TrainingExam model = new TrainingExamImpl();

		model.setTrainingExamId(soapModel.getTrainingExamId());
		model.setTrainingCertificateTemplateId(soapModel.getTrainingCertificateTemplateId());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TrainingExam> toModels(TrainingExamSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TrainingExam> models = new ArrayList<TrainingExam>(soapModels.length);

		for (TrainingExamSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.model.TrainingExam"));

	public TrainingExamModelImpl() {
	}

	public long getPrimaryKey() {
		return _trainingExamId;
	}

	public void setPrimaryKey(long primaryKey) {
		setTrainingExamId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_trainingExamId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TrainingExam.class;
	}

	public String getModelClassName() {
		return TrainingExam.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("trainingExamId", getTrainingExamId());
		attributes.put("trainingCertificateTemplateId",
			getTrainingCertificateTemplateId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long trainingExamId = (Long)attributes.get("trainingExamId");

		if (trainingExamId != null) {
			setTrainingExamId(trainingExamId);
		}

		Long trainingCertificateTemplateId = (Long)attributes.get(
				"trainingCertificateTemplateId");

		if (trainingCertificateTemplateId != null) {
			setTrainingCertificateTemplateId(trainingCertificateTemplateId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@JSON
	public long getTrainingExamId() {
		return _trainingExamId;
	}

	public void setTrainingExamId(long trainingExamId) {
		_trainingExamId = trainingExamId;
	}

	@JSON
	public long getTrainingCertificateTemplateId() {
		return _trainingCertificateTemplateId;
	}

	public void setTrainingCertificateTemplateId(
		long trainingCertificateTemplateId) {
		_columnBitmask |= TRAININGCERTIFICATETEMPLATEID_COLUMN_BITMASK;

		if (!_setOriginalTrainingCertificateTemplateId) {
			_setOriginalTrainingCertificateTemplateId = true;

			_originalTrainingCertificateTemplateId = _trainingCertificateTemplateId;
		}

		_trainingCertificateTemplateId = trainingCertificateTemplateId;
	}

	public long getOriginalTrainingCertificateTemplateId() {
		return _originalTrainingCertificateTemplateId;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TrainingExam.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TrainingExam toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TrainingExam)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public TrainingExam toUnescapedModel() {
		return (TrainingExam)this;
	}

	@Override
	public Object clone() {
		TrainingExamImpl trainingExamImpl = new TrainingExamImpl();

		trainingExamImpl.setTrainingExamId(getTrainingExamId());
		trainingExamImpl.setTrainingCertificateTemplateId(getTrainingCertificateTemplateId());
		trainingExamImpl.setName(getName());

		trainingExamImpl.resetOriginalValues();

		return trainingExamImpl;
	}

	public int compareTo(TrainingExam trainingExam) {
		long primaryKey = trainingExam.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TrainingExam)) {
			return false;
		}

		TrainingExam trainingExam = (TrainingExam)obj;

		long primaryKey = trainingExam.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TrainingExamModelImpl trainingExamModelImpl = this;

		trainingExamModelImpl._originalTrainingCertificateTemplateId = trainingExamModelImpl._trainingCertificateTemplateId;

		trainingExamModelImpl._setOriginalTrainingCertificateTemplateId = false;

		trainingExamModelImpl._originalName = trainingExamModelImpl._name;

		trainingExamModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TrainingExam> toCacheModel() {
		TrainingExamCacheModel trainingExamCacheModel = new TrainingExamCacheModel();

		trainingExamCacheModel.trainingExamId = getTrainingExamId();

		trainingExamCacheModel.trainingCertificateTemplateId = getTrainingCertificateTemplateId();

		trainingExamCacheModel.name = getName();

		String name = trainingExamCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			trainingExamCacheModel.name = null;
		}

		return trainingExamCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{trainingExamId=");
		sb.append(getTrainingExamId());
		sb.append(", trainingCertificateTemplateId=");
		sb.append(getTrainingCertificateTemplateId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.model.TrainingExam");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>trainingExamId</column-name><column-value><![CDATA[");
		sb.append(getTrainingExamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trainingCertificateTemplateId</column-name><column-value><![CDATA[");
		sb.append(getTrainingCertificateTemplateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TrainingExam.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TrainingExam.class
		};
	private long _trainingExamId;
	private long _trainingCertificateTemplateId;
	private long _originalTrainingCertificateTemplateId;
	private boolean _setOriginalTrainingCertificateTemplateId;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private TrainingExam _escapedModel;
}