/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model.impl;

import com.liferay.osb.model.TrainingCertificateTemplate;
import com.liferay.osb.service.TrainingCertificateTemplateLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the TrainingCertificateTemplate service. Represents a row in the &quot;OSB_TrainingCertificateTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingCertificateTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingCertificateTemplateImpl
 * @see com.liferay.osb.model.TrainingCertificateTemplate
 * @generated
 */
public abstract class TrainingCertificateTemplateBaseImpl
	extends TrainingCertificateTemplateModelImpl
	implements TrainingCertificateTemplate {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training certificate template model instance should use the {@link TrainingCertificateTemplate} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			TrainingCertificateTemplateLocalServiceUtil.addTrainingCertificateTemplate(this);
		}
		else {
			TrainingCertificateTemplateLocalServiceUtil.updateTrainingCertificateTemplate(this);
		}
	}
}