/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.social.networking.model.impl;

import com.liferay.social.networking.model.MeetupsRegistration;
import com.liferay.social.networking.service.MeetupsRegistrationLocalServiceUtil;

/**
 * The extended model base implementation for the MeetupsRegistration service. Represents a row in the &quot;SN_MeetupsRegistration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeetupsRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MeetupsRegistrationImpl
 * @see MeetupsRegistration
 * @generated
 */
public abstract class MeetupsRegistrationBaseImpl
	extends MeetupsRegistrationModelImpl implements MeetupsRegistration {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a meetups registration model instance should use the <code>MeetupsRegistration</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MeetupsRegistrationLocalServiceUtil.addMeetupsRegistration(this);
		}
		else {
			MeetupsRegistrationLocalServiceUtil.updateMeetupsRegistration(this);
		}
	}

}