before_cache:
    - rm -f ${HOME}/.gradle/caches/modules-2/modules-2.lock
    - rm -fr ${HOME}/.gradle/caches/*/plugin-resolution/
before_install:
    - TMP_DAEMON=$(mktemp)
    - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io", "https://registry.access.redhat.com"]' /etc/docker/daemon.json > ${TMP_DAEMON}
    - sudo mv ${TMP_DAEMON} /etc/docker/daemon.json
    - sudo systemctl daemon-reload
    - sudo systemctl restart docker
cache:
    directories:
        - ${HOME}/.gradle/caches/
        - ${HOME}/.gradle/wrapper/
        - docker_images
    timeout: 600
dist: bionic
env:
    global:
        - _JAVA_OPTIONS=-Xmx3g
jdk: openjdk8
jobs:
    include:
        - name: "Analysis"
          script:
              - ./gradlew checkSourceFormatting pmdMain pmdTest pmdTestIntegration spotbugsMain spotbugsTest spotbugsTestIntegration --configure-on-demand --continue --parallel
        - name: "Tests"
          after_script:
              - docker-compose -f docker-compose.integration-test.yml down
          after_success:
              - test ${TRAVIS_BRANCH} = "7.0.x" &&
                test ${TRAVIS_EVENT_TYPE} = "push" &&
                test ${TRAVIS_REPO_SLUG} = "liferay/com-liferay-osb-asah-private" &&
                ./gradlew coveralls
          before_script:
              - docker load -i docker_images/images.tar || true
              - docker-compose -f docker-compose.integration-test.yml up -d
              - docker save -o docker_images/images.tar $(docker images -a -q)
          script:
              - ./gradlew test --configure-on-demand --continue --parallel
              - ./gradlew testIntegration --configure-on-demand --continue
              - ./gradlew jacocoTestCoverageVerification
language: java
os: linux
services:
    - docker