before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
    timeout: 600
dist: bionic
env:
    global:
        - _JAVA_OPTIONS=-Xmx3g
jdk: openjdk8
jobs:
    include:
        - stage: "Analysis"
          script:
              - ./gradlew checkSourceFormatting pmdMain pmdTest pmdTestIntegration spotbugsMain spotbugsTest spotbugsTestIntegration --configure-on-demand --continue --parallel
        - stage: "Tests"
          after_script:
              - docker-compose -f docker-compose.integration-test.yml down
          after_success:
              - test $TRAVIS_BRANCH = "7.0.x" &&
                test $TRAVIS_EVENT_TYPE = "push" &&
                test $TRAVIS_REPO_SLUG = "liferay/com-liferay-osb-asah-private" &&
                ./gradlew coveralls
          before_script:
              - docker-compose -f docker-compose.integration-test.yml up -d
          script:
              - ./gradlew test --configure-on-demand --continue --parallel
              - ./gradlew testIntegration --configure-on-demand --continue
              - ./gradlew jacocoTestCoverageVerification
language: java
os: linux
services:
    - docker