##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        **/osb-asah-common/src/main/java/com/liferay/osb/asah/common/model/AnalyticsEventsMessage.java,\
        **/osb-asah-composer/**/.pytest_cache/**,\
        **/osb-asah-filter-expression-parser/src/main/java/com/liferay/osb/asah/common/filter/expression/parser/**,\
        **/osb-asah-publisher/**/analytics_events_message_invalid_syntax.json,\
        **/osb-asah-spark-python/**/.pytest_cache/**,\
        **/osb-asah-stream-curator/src/main/resources/profile/**

    checkstyle.ChainingCheck.allowedClassNames=\
        AggregationBuilder,\
        BoolQueryBuilderUtil,\
        Create,\
        DataFrameWriter,\
        DataStreamReader,\
        DoubleTensor,\
        DSL,\
        DStream,\
        FileIO,\
        functions,\
        JSONArrayIterator,\
        JSONUtil,\
        KeyValueGroupedDataset,\
        PAssert,\
        PubsubIO,\
        TextIO

    checkstyle.ChainingCheck.allowedMethodNames=\
        apply,\
        delete,\
        deleteFrom,\
        fromArgs,\
        greaterThanOrEqual,\
        into,\
        jsonExtractScalar,\
        logProb,\
        minus,\
        of,\
        partition,\
        pastEndOfWindow,\
        pastFirstElementInPane,\
        plus,\
        prob,\
        put,\
        regexpExtract,\
        select,\
        selectCount,\
        selectDistinct,\
        terms,\
        that,\
        times,\
        toGreaterThanOrEqualToMask,\
        topHits,\
        writeTableRows

    run.outside.portal.excludes=**

##
## Git
##

    git.liferay.portal.branch=7.0.x

##
## Source Check Properties
##

    source.check.JavaDeprecatedJavadocCheck.enabled=false

    source.check.JavaExceptionCheck.enabled=false

    source.check.JSONLineBreakCheck.enabled=false

    source.check.YMLLongLinesCheck.enabled=false

    source.check.YMLStylingCheck.enabled=false

    source.check.YMLWhitespaceCheck.enabled=false