##
## Properties Override
##

    #
    # Specify where to get the overridden properties. Updates should not be made
    # on this file but on the overridden version of this file.
    #
    include-and-override=portlet-ext.properties

##
## JIRA
##

    #
    # Input a list of comma separated JIRA component filters.
    #
    jira.component.filters=\
        com.liferay.osb.customer.release.notes.util.filter.LPE_5_1_JIRAComponentFilter,\
        com.liferay.osb.customer.release.notes.util.filter.LPE_5_2_JIRAComponentFilter,\
        com.liferay.osb.customer.release.notes.util.filter.LPE_6_0_JIRAComponentFilter

    #
    # Input a list of comma separated JIRA project keys that are available to
    # generate release notes.
    #
    jira.project.keys.allowed=AUI,CLDSVCS,FACES,LPE,LPS,MAVEN,MOBILE,SOS,STUDIO,SYNC

##
## Template
##

    #
    # Enter the main velocity template file.
    #
    template.velocity=/template/main.vm

    #
    # Input a list of comma separated CSS files.
    #
    template.css=\
        /template/css/reset.css,\
        /template/css/main.css,\
        /template/css/api-changes.css,\
        /template/css/change-log.css,\
        /template/css/ticket-viewer.css,\
        /template/css/upgrade-notes.css

    #
    # Input a list of comma separated JavaScript files.
    #
    template.js.bottom=\
        /template/js/change-page.js,\
        /template/js/ticket-viewer.js
    template.js.top=

##
## Images
##

    image.logo=/template/images/logo.png

    image.icon.bug=/template/images/bug.png
    image.icon.improvement=/template/images/improvement.png
    image.icon.new.feature=/template/images/new-feature.png
    image.icon.other=/template/images/other.png