include-and-override=portlet-ext.properties

resource.actions.configs=resource-actions/default.xml

testray.automation.attachment.expiration.age.days=30
testray.automation.attachment.url=/reports/development/${testray.automation.attachment.subdirectory}