include-and-override=portlet-ext.properties

image.extensions=.gif,.jpeg,.jpg,.png

resource.actions.configs=resource-actions/default.xml

testray.automated.archiving.threshold.hours=1440

testray.automation.archives.path=
testray.automation.attachment.expiration.age.days=30
testray.automation.attachment.minimum.case.results.count=1000
testray.automation.attachment.path=${testray.automation.results.path}/${testray.automation.attachment.subdirectory}
testray.automation.attachment.subdirectory=/logs
testray.automation.attachment.url=/reports/development/${testray.automation.attachment.subdirectory}
testray.automation.computer.names=
testray.automation.results.path=
testray.automation.thread.count=6

testray.case.reindex.threshold.hours=24
testray.case.result.errors.truncated.char.count=500

testray.cron.trigger.builds.controller=0 0 5 * * ? *
testray.cron.trigger.case.results.controller=0 0/5 * * * ? *
testray.cron.trigger.cases.controller=0 0 2 * * ? *
testray.cron.trigger.requirements.controller=0 0 1 * * ? *

testray.delete.tree.enabled=false

testray.github.compare.urls.enabled=false

testray.simplified.cases=true

testray.subscriber.email.addresses=