INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now}' ), 'blogViewed', '1');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-1d}'), 'blogViewed', '2' );
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-2d}'), 'blogViewed', '3');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-6d}'), 'blogViewed', '4');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-8d}'), 'blogViewed', '5');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-8d}'), 'blogViewed', '6');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-9d}'), 'blogViewed', '7');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-12d}'), 'blogViewed', '8');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-14d}'), 'blogViewed', '9');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Blog', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-15d}'), 'blogViewed', '10');