INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now}'), 1);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-1d}'), 4);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-2d}'), 2);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-6d}'), 2);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-8d}'), 7);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-9d}'), 1);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-12d}'), 4);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-14d}'), 2);
INSERT INTO BQCustomAsset (assetPrimaryKey, channelId, eventDate, views) VALUES ('e131fabc', 1, date_trunc('HOUR', timestamp '${now-15d}'), 6);