INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now}' ), 'formViewed', '1');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-1d}'), 'formViewed', '2' );
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-2d}'), 'formViewed', '3');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-6d}'), 'formViewed', '4');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-8d}'), 'formViewed', '5');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-8d}'), 'formViewed', '6');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-9d}'), 'formViewed', '7');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-12d}'), 'formViewed', '8');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-14d}'), 'formViewed', '9');
INSERT INTO BQEvent (applicationId, assetId, channelId, eventDate, eventId, id) VALUES ('Form', 'e131fabc', 1, date_trunc('HOUR', timestamp '${now-15d}'), 'formViewed', '10');