INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', CAST(TIMESTAMP  '${today-400d}' AS DATE), '1');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', CAST(TIMESTAMP '${today-387d}' AS DATE), '2');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', CAST(TIMESTAMP '${today-366d}' AS DATE), '3');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', CAST(TIMESTAMP '${today-364d}' AS DATE), '4');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', CAST(TIMESTAMP '${today-333d}' AS DATE), '5');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'compelling action-items', CAST(TIMESTAMP '${today-3d}' AS DATE), '6');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'holistic roi', CAST(TIMESTAMP '${today}' AS DATE), '7');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'engineer', CAST(TIMESTAMP '${today}' AS DATE), '8');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, FALSE, 'error', CAST(TIMESTAMP '${today}' AS DATE), '8');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'intuitive', CAST(TIMESTAMP '${today}' AS DATE), '8');
INSERT INTO SessionInterestScore(channelId, interested, keyword, recordedDate, sessionId) VALUES (1, TRUE, 'models', CAST(TIMESTAMP '${today}' AS DATE), '8');