INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-2d}', 'assetClicked', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-2d}', 'blogClicked', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-20d}', 'assetDownloaded', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-20d}', 'assetDownloaded', '2', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-20d}', 'assetDownloaded', '3', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-35d}', 'assetClicked', '2', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-10d}', 'blogClicked', '2', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-10d}', 'blogClicked', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${today-10d}', 'blogClicked', '1', '1');