INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-1h}', 'assetClicked', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-1h}', 'assetClicked', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-3h}', 'blogClicked', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-3h}', 'fieldBlurred', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-3h}', 'assetClicked', '2', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-10h}', 'blogClicked', '1', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-10h}', 'blogClicked', '2', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-10h}', 'blogClicked', '2', '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, sessionId, userId) VALUES (1, timestamp '${now-10h}', 'blogClicked', '3', '1');