INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-1h}', 'assetClicked', 1, '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-1h}', 'assetClicked', 1, '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-3h}', 'blogClicked', 1, '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-3h}', 'fieldBlurred', 1, '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-3h}', 'assetClicked', 1, '2');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-10h}', 'blogClicked', 1, '1');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-10h}', 'blogClicked', 1, '2');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-10h}', 'blogClicked', 1, '2');
INSERT INTO BQEvent (channelId, eventDate, eventId, individualId, sessionId) VALUES (1, timestamp '${now-10h}', 'blogClicked', 1, '3');