/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.watson.login.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.liferay.watson.login.model.WatsonTokenAuthEntry;
import com.liferay.watson.login.model.WatsonTokenAuthEntryModel;
import com.liferay.watson.login.model.WatsonTokenAuthEntrySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the WatsonTokenAuthEntry service. Represents a row in the &quot;WatsonTokenAuthEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link WatsonTokenAuthEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonTokenAuthEntryImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonTokenAuthEntryImpl
 * @see WatsonTokenAuthEntry
 * @see WatsonTokenAuthEntryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class WatsonTokenAuthEntryModelImpl extends BaseModelImpl<WatsonTokenAuthEntry>
	implements WatsonTokenAuthEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson token auth entry model instance should use the {@link WatsonTokenAuthEntry} interface instead.
	 */
	public static final String TABLE_NAME = "WatsonTokenAuthEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "watsonTokenAuthEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "active_", Types.BOOLEAN },
			{ "token", Types.VARCHAR },
			{ "expirationDate", Types.TIMESTAMP },
			{ "loginDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonTokenAuthEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("token", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("loginDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table WatsonTokenAuthEntry (watsonTokenAuthEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,active_ BOOLEAN,token VARCHAR(75) null,expirationDate DATE null,loginDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table WatsonTokenAuthEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY watsonTokenAuthEntry.watsonTokenAuthEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY WatsonTokenAuthEntry.watsonTokenAuthEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.watson.login.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.watson.login.model.WatsonTokenAuthEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.watson.login.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.watson.login.model.WatsonTokenAuthEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.watson.login.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.watson.login.model.WatsonTokenAuthEntry"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long USERID_COLUMN_BITMASK = 2L;
	public static final long WATSONTOKENAUTHENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static WatsonTokenAuthEntry toModel(
		WatsonTokenAuthEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		WatsonTokenAuthEntry model = new WatsonTokenAuthEntryImpl();

		model.setWatsonTokenAuthEntryId(soapModel.getWatsonTokenAuthEntryId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setActive(soapModel.isActive());
		model.setToken(soapModel.getToken());
		model.setExpirationDate(soapModel.getExpirationDate());
		model.setLoginDate(soapModel.getLoginDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<WatsonTokenAuthEntry> toModels(
		WatsonTokenAuthEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<WatsonTokenAuthEntry> models = new ArrayList<WatsonTokenAuthEntry>(soapModels.length);

		for (WatsonTokenAuthEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.watson.login.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.watson.login.model.WatsonTokenAuthEntry"));

	public WatsonTokenAuthEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonTokenAuthEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonTokenAuthEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonTokenAuthEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonTokenAuthEntry.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonTokenAuthEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("watsonTokenAuthEntryId", getWatsonTokenAuthEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("active", isActive());
		attributes.put("token", getToken());
		attributes.put("expirationDate", getExpirationDate());
		attributes.put("loginDate", getLoginDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long watsonTokenAuthEntryId = (Long)attributes.get(
				"watsonTokenAuthEntryId");

		if (watsonTokenAuthEntryId != null) {
			setWatsonTokenAuthEntryId(watsonTokenAuthEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Boolean active = (Boolean)attributes.get("active");

		if (active != null) {
			setActive(active);
		}

		String token = (String)attributes.get("token");

		if (token != null) {
			setToken(token);
		}

		Date expirationDate = (Date)attributes.get("expirationDate");

		if (expirationDate != null) {
			setExpirationDate(expirationDate);
		}

		Date loginDate = (Date)attributes.get("loginDate");

		if (loginDate != null) {
			setLoginDate(loginDate);
		}
	}

	@JSON
	@Override
	public long getWatsonTokenAuthEntryId() {
		return _watsonTokenAuthEntryId;
	}

	@Override
	public void setWatsonTokenAuthEntryId(long watsonTokenAuthEntryId) {
		_watsonTokenAuthEntryId = watsonTokenAuthEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	@JSON
	@Override
	public String getToken() {
		if (_token == null) {
			return "";
		}
		else {
			return _token;
		}
	}

	@Override
	public void setToken(String token) {
		_token = token;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		_expirationDate = expirationDate;
	}

	@JSON
	@Override
	public Date getLoginDate() {
		return _loginDate;
	}

	@Override
	public void setLoginDate(Date loginDate) {
		_loginDate = loginDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			WatsonTokenAuthEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WatsonTokenAuthEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WatsonTokenAuthEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonTokenAuthEntryImpl watsonTokenAuthEntryImpl = new WatsonTokenAuthEntryImpl();

		watsonTokenAuthEntryImpl.setWatsonTokenAuthEntryId(getWatsonTokenAuthEntryId());
		watsonTokenAuthEntryImpl.setCompanyId(getCompanyId());
		watsonTokenAuthEntryImpl.setUserId(getUserId());
		watsonTokenAuthEntryImpl.setUserName(getUserName());
		watsonTokenAuthEntryImpl.setCreateDate(getCreateDate());
		watsonTokenAuthEntryImpl.setActive(isActive());
		watsonTokenAuthEntryImpl.setToken(getToken());
		watsonTokenAuthEntryImpl.setExpirationDate(getExpirationDate());
		watsonTokenAuthEntryImpl.setLoginDate(getLoginDate());

		watsonTokenAuthEntryImpl.resetOriginalValues();

		return watsonTokenAuthEntryImpl;
	}

	@Override
	public int compareTo(WatsonTokenAuthEntry watsonTokenAuthEntry) {
		long primaryKey = watsonTokenAuthEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WatsonTokenAuthEntry)) {
			return false;
		}

		WatsonTokenAuthEntry watsonTokenAuthEntry = (WatsonTokenAuthEntry)obj;

		long primaryKey = watsonTokenAuthEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		WatsonTokenAuthEntryModelImpl watsonTokenAuthEntryModelImpl = this;

		watsonTokenAuthEntryModelImpl._originalCompanyId = watsonTokenAuthEntryModelImpl._companyId;

		watsonTokenAuthEntryModelImpl._setOriginalCompanyId = false;

		watsonTokenAuthEntryModelImpl._originalUserId = watsonTokenAuthEntryModelImpl._userId;

		watsonTokenAuthEntryModelImpl._setOriginalUserId = false;

		watsonTokenAuthEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<WatsonTokenAuthEntry> toCacheModel() {
		WatsonTokenAuthEntryCacheModel watsonTokenAuthEntryCacheModel = new WatsonTokenAuthEntryCacheModel();

		watsonTokenAuthEntryCacheModel.watsonTokenAuthEntryId = getWatsonTokenAuthEntryId();

		watsonTokenAuthEntryCacheModel.companyId = getCompanyId();

		watsonTokenAuthEntryCacheModel.userId = getUserId();

		watsonTokenAuthEntryCacheModel.userName = getUserName();

		String userName = watsonTokenAuthEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonTokenAuthEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonTokenAuthEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonTokenAuthEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		watsonTokenAuthEntryCacheModel.active = isActive();

		watsonTokenAuthEntryCacheModel.token = getToken();

		String token = watsonTokenAuthEntryCacheModel.token;

		if ((token != null) && (token.length() == 0)) {
			watsonTokenAuthEntryCacheModel.token = null;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			watsonTokenAuthEntryCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			watsonTokenAuthEntryCacheModel.expirationDate = Long.MIN_VALUE;
		}

		Date loginDate = getLoginDate();

		if (loginDate != null) {
			watsonTokenAuthEntryCacheModel.loginDate = loginDate.getTime();
		}
		else {
			watsonTokenAuthEntryCacheModel.loginDate = Long.MIN_VALUE;
		}

		return watsonTokenAuthEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{watsonTokenAuthEntryId=");
		sb.append(getWatsonTokenAuthEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", active=");
		sb.append(isActive());
		sb.append(", token=");
		sb.append(getToken());
		sb.append(", expirationDate=");
		sb.append(getExpirationDate());
		sb.append(", loginDate=");
		sb.append(getLoginDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.watson.login.model.WatsonTokenAuthEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>watsonTokenAuthEntryId</column-name><column-value><![CDATA[");
		sb.append(getWatsonTokenAuthEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(isActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>token</column-name><column-value><![CDATA[");
		sb.append(getToken());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>expirationDate</column-name><column-value><![CDATA[");
		sb.append(getExpirationDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loginDate</column-name><column-value><![CDATA[");
		sb.append(getLoginDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = WatsonTokenAuthEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			WatsonTokenAuthEntry.class
		};
	private long _watsonTokenAuthEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private boolean _active;
	private String _token;
	private Date _expirationDate;
	private Date _loginDate;
	private long _columnBitmask;
	private WatsonTokenAuthEntry _escapedModel;
}