IX_F1A6D304=OSB_AccountAttachment.AEI_API
IX_1B961F96=OSB_AccountAttachment.AEI_API_FN_T
IX_D44EEA51=OSB_AccountAttachment.AEI_API_T
IX_20B2A5A9=OSB_AccountAttachment.AccountEntryId

IX_B268D724=OSB_AccountCall.AccountEntryId

IX_54FF6074=OSB_AccountCustomer.AEI_NotN
IX_B590328E=OSB_AccountCustomer.AEI_NotR
IX_5D6036A4=OSB_AccountCustomer.AccountEntryId
IX_F9BEADE=OSB_AccountCustomer.U_AEI
IX_A47A5E94=OSB_AccountCustomer.U_R
IX_A2455F2A=OSB_AccountCustomer.UserId

IX_E9054065=OSB_AccountEntries_SupportRegions.accountEntryId
IX_B9459F3D=OSB_AccountEntries_SupportRegions.supportRegionId

IX_1910ED5C=OSB_AccountEntries_SupportTeams.accountEntryId
IX_7AF62D4F=OSB_AccountEntries_SupportTeams.supportTeamId

IX_32214056=OSB_AccountEntry.Code
IX_6AA361CE=OSB_AccountEntry.CorpProjectId
IX_142E34C7=OSB_AccountEntry.HighestSupportResponseId
IX_2FB47967=OSB_AccountEntry.N_C_RAEI
IX_7EFCE72B=OSB_AccountEntry.Name
IX_1DCDCBE5=OSB_AccountEntry.PartnerEntryId
IX_77FBC39=OSB_AccountEntry.RAEI_NotT
IX_E57EB21F=OSB_AccountEntry.RAEI_NotT_S
IX_5F5D3902=OSB_AccountEntry.RAEI_S
IX_C2D8D61C=OSB_AccountEntry.RedirectAccountEntryId
IX_31DB3E6F=OSB_AccountEntry.U_T

IX_8B166398=OSB_AccountEntryLanguage.AccountEntryId

IX_CC4721B3=OSB_AccountEnvironment.AEI_PEI
IX_4A401F32=OSB_AccountEnvironment.AEI_PEI_N
IX_EE986C81=OSB_AccountEnvironment.AccountEntryId

IX_8CAAC4C0=OSB_AccountEnvironmentAttachment.AEI_FN
IX_23139A90=OSB_AccountEnvironmentAttachment.AEI_T
IX_20765BA5=OSB_AccountEnvironmentAttachment.AccountEnvironmentId

IX_3B5CFE75=OSB_AccountInformation.AEI_API
IX_9644DED0=OSB_AccountInformation.AEI_API_FI
IX_3B5CFE75=OSB_AccountInformation.AEI_NotAPI

IX_D37D5DC0=OSB_AccountLink.AccountEntryId

IX_E16E8A07=OSB_AccountProject.AccountEntryId

IX_640DDD4=OSB_AccountWorker.AEI_NotN
IX_9D0A292E=OSB_AccountWorker.AEI_R
IX_ABFA544=OSB_AccountWorker.AccountEntryId
IX_72B97E=OSB_AccountWorker.U_AEI
IX_1224F534=OSB_AccountWorker.U_R
IX_EECD6DCA=OSB_AccountWorker.UserId

IX_6291B647=OSB_AppAudit.AppVersionId
IX_4DEC1EF3=OSB_AppAudit.Uuid

IX_8DB55D79=OSB_AppEntry.DEI_LikeT
IX_E706B295=OSB_AppEntry.DEI_S
IX_CEB292AF=OSB_AppEntry.DeveloperEntryId
IX_AE78CD5E=OSB_AppEntry.Status
IX_83A04590=OSB_AppEntry.Title
IX_CC61EC3C=OSB_AppEntry.Uuid

IX_7B497867=OSB_AppEntryRel.AEI1_AEI2_T
IX_C31738ED=OSB_AppEntryRel.AEI1_T
IX_AD86FF07=OSB_AppEntryRel.Uuid

IX_A49D947D=OSB_AppFlag.AVI_T
IX_35580258=OSB_AppFlag.AppVersionId
IX_1671D402=OSB_AppFlag.Uuid

IX_5EA83F2E=OSB_AppPackage.AVI_C
IX_8A6F5C68=OSB_AppPackage.AVI_CP
IX_477468B2=OSB_AppPackage.AppVersionId

IX_3AC2FB26=OSB_AppPackagePlugin.API_BSN
IX_C3DF7540=OSB_AppPackagePlugin.API_BSN_BV
IX_B3515777=OSB_AppPackagePlugin.API_CN
IX_C26FF18E=OSB_AppPackagePlugin.API_FN
IX_FA6AAB24=OSB_AppPackagePlugin.API_PE
IX_24E0179F=OSB_AppPackagePlugin.API_PRR
IX_ED5891F3=OSB_AppPackagePlugin.AppPackageId
IX_11140D1F=OSB_AppPackagePlugin.AssetAttachmentId
IX_8970EE92=OSB_AppPackagePlugin.BundleSymbolicName
IX_C8B7258B=OSB_AppPackagePlugin.ContextName
IX_79A3A0CB=OSB_AppPackagePlugin.NotAEI_CN

IX_B380D432=OSB_AppPricing.AppVersionId

IX_EE718AF3=OSB_AppPricingItem.API_ALI
IX_45C8A653=OSB_AppPricingItem.AppPricingId
IX_BEE670DF=OSB_AppPricingItem.AssetLicenseId

IX_9ECC20E8=OSB_AppVersion.AEI_GtVO
IX_38D38CF3=OSB_AppVersion.AEI_RT
IX_B7266084=OSB_AppVersion.AEI_S
IX_552C882A=OSB_AppVersion.AEI_V
IX_85BA9F9E=OSB_AppVersion.AppEntryId
IX_B0B86A44=OSB_AppVersion.Status

IX_49DF404D=OSB_AssetAttachment.C_C
IX_653ECD6D=OSB_AssetAttachment.C_C_F_T
IX_CC67A8E8=OSB_AssetAttachment.C_C_T
IX_C9B1988B=OSB_AssetAttachment.LtC_C_C

IX_5F11F887=OSB_AssetAudit.C_C
IX_42980870=OSB_AssetAudit.C_C_C_T
IX_63E33774=OSB_AssetAudit.U_C_C_T

IX_80CBCEAD=OSB_AssetLicense.C_C
IX_519B1093=OSB_AssetLicense.C_C_S
IX_B13824AD=OSB_AssetLicense.C_C_UT_LT
IX_D674436A=OSB_AssetLicense.C_C_UT_LT_LTA
IX_F8157850=OSB_AssetLicense.C_C_UT_LT_LTA_S
IX_53516693=OSB_AssetLicense.C_C_UT_LT_S

IX_64A6D5EF=OSB_AssetList.ACI_T
IX_339F9D26=OSB_AssetList.AssetCategoryId

IX_99B4BA95=OSB_AssetListAssetEntry.ALI_AEI
IX_A9BE68C6=OSB_AssetListAssetEntry.AssetEntryId
IX_5ED7CEC4=OSB_AssetListAssetEntry.AssetListId

IX_964E6720=OSB_AssetReceipt.AssetEntryId
IX_9CB20B7D=OSB_AssetReceipt.OCNI_OCPK_PCNI_PCPK
IX_A7D5FC24=OSB_AssetReceipt.UI_PCNI_PCPK

IX_F0A1AA0=OSB_AssetReceiptLicense.ARI_GtSD_UT
IX_E6EEB68E=OSB_AssetReceiptLicense.ARI_LtSD_GtED
IX_DC4E821D=OSB_AssetReceiptLicense.ARI_LtSD_GtED_UT
IX_86274F5E=OSB_AssetReceiptLicense.AssetLicenseId
IX_259369D5=OSB_AssetReceiptLicense.AssetReceiptId
IX_59371C34=OSB_AssetReceiptLicense.OCN_OCP_PCN
IX_98252929=OSB_AssetReceiptLicense.OCN_OCP_PI
IX_5C2F0818=OSB_AssetReceiptLicense.OCN_OCP_PI_LT_LL
IX_F61CD736=OSB_AssetReceiptLicense.Uuid

IX_183FDF00=OSB_AssetReceiptRedeemToken.REA_RD
IX_2605E56F=OSB_AssetReceiptRedeemToken.Token

IX_4C8CF02E=OSB_AssetReceiptSupport.ARI_GtSD_UT
IX_4CE80C4F=OSB_AssetReceiptSupport.ARI_LtSD_GtED_UT
IX_F1BA813E=OSB_AssetReceiptSupport.ARI_PCNI_PCPK
IX_260FF77=OSB_AssetReceiptSupport.ARI_PCNI_PCPK_LtSD_GtED
IX_512EDDE3=OSB_AssetReceiptSupport.AssetReceiptId
IX_D261FB68=OSB_AssetReceiptSupport.Uuid

IX_BB00C4ED=OSB_AssetRecommendationEntry.ARSI_C_C
IX_89CAB4EE=OSB_AssetRecommendationEntry.ARSI_GtPAPC
IX_827847E3=OSB_AssetRecommendationEntry.ARSI_GtVAPC
IX_695A7525=OSB_AssetRecommendationEntry.C_C

IX_723EBF15=OSB_AssetRecommendationSet.C_C

IX_C4415F67=OSB_AssetStatsDay.C_C
IX_D2F824F6=OSB_AssetStatsDay.C_C_D_Y

IX_757AC64B=OSB_AssetStatsMonth.C_C
IX_C8BB39B6=OSB_AssetStatsMonth.C_C_M_Y

IX_2431D55F=OSB_AssetStatsWeek.C_C
IX_5E9668B8=OSB_AssetStatsWeek.C_C_W_Y

IX_2194BE84=OSB_AuditAction.C_C_MC
IX_EA525690=OSB_AuditAction.GtMD_C_GtMC_A
IX_EA525690=OSB_AuditAction.GtMD_C_MC_A
IX_1A167D81=OSB_AuditAction.LtModifiedDate
IX_6E655F39=OSB_AuditAction.MD_C_C_MC_A

IX_56D6EFE1=OSB_AuditEntry.C_C_F_A
IX_6DC23F99=OSB_AuditEntry.C_C_V
IX_A70C3087=OSB_AuditEntry.FC_FC_F
IX_558935D2=OSB_AuditEntry.GtCD_C

IX_4772426A=OSB_ContractAudit.CEI_SCN_SCP
IX_10AD3D03=OSB_ContractAudit.U_CEI

IX_E089E53B=OSB_ContractEntry.CN_CP_T

IX_ADDCEB29=OSB_CorpEntry.DossieraAccountKey
IX_A1DFC2AC=OSB_CorpEntry.Name
IX_391B724F=OSB_CorpEntry.OrganizationId

IX_2F99E8B0=OSB_CorpEntry_CorpGroup.corpEntryId
IX_F3C8083D=OSB_CorpEntry_CorpGroup.corpGroupId

IX_5BA953B9=OSB_CorpGroup.Name
IX_2480D71C=OSB_CorpGroup.OrganizationId

IX_72919D25=OSB_CorpMembershipRequest.CEI_S
IX_F0B813A8=OSB_CorpMembershipRequest.Key
IX_E927212B=OSB_CorpMembershipRequest.U_CEI_S

IX_B1E34FE4=OSB_CorpProject.DossieraProjectKey
IX_C2AF513=OSB_CorpProject.Name
IX_14940FF6=OSB_CorpProject.OrganizationId

IX_F22B253A=OSB_CorpProjectMessage.C_T
IX_80F71C3B=OSB_CorpProjectMessage.CorpProjectId
IX_73BC3756=OSB_CorpProjectMessage.Type

IX_1DDA55FB=OSB_CountryAppPricing.AVI_CI
IX_C7A9B0F4=OSB_CountryAppPricing.AppPricingId
IX_93DD5506=OSB_CountryAppPricing.AppVersionId
IX_CBEE1A21=OSB_CountryAppPricing.CountryId

IX_64FD3078=OSB_CurrencyEntry.CurrencyCode
IX_671B950=OSB_CurrencyEntry.MarketplaceEnabled

IX_4256345C=OSB_DeveloperEntry.DN_DS
IX_B0F6096B=OSB_DeveloperEntry.DossieraAccountKey
IX_C19D5AB3=OSB_DeveloperEntry.LEN_T_S
IX_F1259BD5=OSB_DeveloperEntry.Status
IX_147C0BEC=OSB_DeveloperEntry.T_S
IX_59DA448C=OSB_DeveloperEntry.UI_T
IX_AB013772=OSB_DeveloperEntry.UI_T_S
IX_92A4B529=OSB_DeveloperEntry.UserId

IX_AC757523=OSB_ExternalIdMapper.C_C
IX_86A7752=OSB_ExternalIdMapper.C_C_T
IX_8FBE42CF=OSB_ExternalIdMapper.C_T_EI

IX_1738CAF1=OSB_HolidayCalendarRel.HC_U
IX_AB919B7=OSB_HolidayCalendarRel.HolidayCalendarId
IX_B2BCBD24=OSB_HolidayCalendarRel.UserId

IX_8D6F9B60=OSB_HolidayEntry.HolidayCalendar

IX_8B5D7FE4=OSB_LicenseEntry.PEI_PV
IX_7576438B=OSB_LicenseEntry.PEI_T
IX_244070A=OSB_LicenseEntry.ProductEntryId
IX_12886FD=OSB_LicenseEntry.Type

IX_EB731F6A=OSB_LicenseKey.ARLI_A
IX_A1F1451A=OSB_LicenseKey.ARLI_C_A
IX_F44DE07C=OSB_LicenseKey.ARLI_PI_SI_A
IX_D9E7AC39=OSB_LicenseKey.AccountEntryId
IX_3B9F5AEA=OSB_LicenseKey.LicenseKeySetId
IX_2D8DAA13=OSB_LicenseKey.OEI_CI
IX_AEC46A56=OSB_LicenseKey.OEI_CI_A
IX_34C23F6D=OSB_LicenseKey.OEI_C_A
IX_8472FBAC=OSB_LicenseKey.OEI_LET_C_A
IX_8472FBAC=OSB_LicenseKey.OEI_NotLET_C_A
IX_4C3397AB=OSB_LicenseKey.OEI_O
IX_E09031D2=OSB_LicenseKey.OfferingEntryId
IX_80A769F8=OSB_LicenseKey.OrderEntryId
IX_DE309610=OSB_LicenseKey.PEN_SI_A
IX_AFB6E8E7=OSB_LicenseKey.PI_SI
IX_A7B2FB73=OSB_LicenseKey.U_AEI
IX_FED7DC75=OSB_LicenseKey.U_ARLI_PI
IX_787239BF=OSB_LicenseKey.UserId

IX_AA77CE1D=OSB_LicenseKeySet.AccountEntryId
IX_62FEABD6=OSB_LicenseKeySet.U_AEI_N

IX_EED5EFA6=OSB_MarketingEvent.GlobalRegion
IX_F81473A=OSB_MarketingEvent.Type

IX_DC1ECDCE=OSB_OfferingBundle.Name

IX_480DB8E2=OSB_OfferingBundles_OfferingDefinitions.offeringBundleId
IX_5CB2DBB3=OSB_OfferingBundles_OfferingDefinitions.offeringDefinitionId

IX_28E3AE89=OSB_OfferingDefinition.PEI_SRI
IX_CFDC51BF=OSB_OfferingDefinition.PEI_SRI_PD_L_UL_ST
IX_BA1F0592=OSB_OfferingDefinition.ProductEntryId
IX_99AA46FB=OSB_OfferingDefinition.SupportResponseId

IX_ACC7D8EB=OSB_OfferingEntry.AEI_S
IX_C5126F05=OSB_OfferingEntry.AccountEntryId
IX_2CFC6FC4=OSB_OfferingEntry.OrderEntryId
IX_91C36F37=OSB_OfferingEntry.Status
IX_E0CF6A9F=OSB_OfferingEntry.SupportEndDate
IX_6455D563=OSB_OfferingEntry.U_AEI_OEI_T
IX_CE314FD7=OSB_OfferingEntry.Version

IX_CF95221F=OSB_OrderEntry.AccountEntryId
IX_9903B2E9=OSB_OrderEntry.Uuid

IX_A39907C5=OSB_PartnerEntries_SupportRegions.partnerEntryId
IX_A1C7B702=OSB_PartnerEntries_SupportRegions.supportRegionId

IX_2D2C67B1=OSB_PartnerEntry.Code
IX_E567A9ED=OSB_PartnerEntry.DossieraAccountKey
IX_5665A174=OSB_PartnerEntry.ParentPartnerEntryId

IX_6F521474=OSB_PartnerWorker.PEI_NotN
IX_15A2FE8E=OSB_PartnerWorker.PEI_R
IX_C67C02A4=OSB_PartnerWorker.PartnerEntryId
IX_8D1D4BDE=OSB_PartnerWorker.U_PEI
IX_F36C918F=OSB_PartnerWorker.U_R
IX_53AC2A65=OSB_PartnerWorker.UserId

IX_86585E47=OSB_PortalRelease.BuildNumber
IX_3F851494=OSB_PortalRelease.EE
IX_2D2FADF8=OSB_PortalRelease.MarketplaceSupport
IX_8515A999=OSB_PortalRelease.OSGiSupport
IX_726497C5=OSB_PortalRelease.PACLSupport

IX_190AFA9=OSB_ProductEntry.Name

IX_A84DAB0D=OSB_SearchFilter.U_C
IX_889263E1=OSB_SearchFilter.UserId

IX_18BFB3A4=OSB_SecurityPatch.AEI_PI
IX_36A4B1D8=OSB_SecurityPatch.PortletId

IX_DC67F8E7=OSB_SupportRegion.Name

IX_9A2345B4=OSB_SupportResponse.Name
IX_21D8E69E=OSB_SupportResponse.SupportLevel

IX_CB537ED0=OSB_SupportTeam.Name
IX_259AEC3C=OSB_SupportTeam.ParentSupportTeamId
IX_92D16E1=OSB_SupportTeam.SupportLaborId

IX_45C068E=OSB_SupportTeamLanguage.SupportTeamId

IX_F1DB9001=OSB_SupportTeams_SupportRegions.supportRegionId
IX_E33A26EA=OSB_SupportTeams_SupportRegions.supportTeamId

IX_C3CFE42=OSB_SupportWorker.SupportLaborId
IX_5B76AC85=OSB_SupportWorker.SupportTeamId
IX_211496C3=OSB_SupportWorker.U_MW_R
IX_C4442B0B=OSB_SupportWorker.U_STI
IX_6760DF6C=OSB_SupportWorker.UserId

IX_749683CF=OSB_SupportWorkerAccountTier.SupportWorkerId

IX_9FADBCC1=OSB_SupportWorkerComponent.SupportWorkerId

IX_58971029=OSB_SupportWorkerSeverity.SupportWorkerId

IX_C5D75521=OSB_TicketAttachment.CD_T
IX_61FA03D=OSB_TicketAttachment.CD_TEI
IX_26149242=OSB_TicketAttachment.TEI_FN_V_S
IX_CFC835A1=OSB_TicketAttachment.TEI_S
IX_46E45E8F=OSB_TicketAttachment.TEI_TSI
IX_36DB14A0=OSB_TicketAttachment.TEI_T_S
IX_B8D980A6=OSB_TicketAttachment.TEI_T_V_S
IX_47FFB24C=OSB_TicketAttachment.T_DD
IX_8415F49F=OSB_TicketAttachment.Type
IX_6EAF2BAD=OSB_TicketAttachment.U_TEI_V_S

IX_3225AAFC=OSB_TicketComment.TEI_T
IX_304B8825=OSB_TicketComment.TEI_V_S
IX_EF2EACB9=OSB_TicketComment.TicketEntryId
IX_1C71ADAB=OSB_TicketComment.U_TEI_V_S
IX_565F15CA=OSB_TicketComment.U_TEI_V_S_T

IX_854674BA=OSB_TicketEntry.AEI_TI
IX_CE03A0FF=OSB_TicketEntry.AccountEntryId
IX_E0167256=OSB_TicketEntry.GtModifiedDate
IX_A5B233EC=OSB_TicketEntry.OEI_NotR
IX_6FF2D5CC=OSB_TicketEntry.OfferingEntryId

IX_61173523=OSB_TicketFeedback.TEI_S
IX_52ABA109=OSB_TicketFeedback.TEI_S_NotS
IX_52ABA109=OSB_TicketFeedback.TEI_S_S
IX_5BB30859=OSB_TicketFeedback.TicketEntryId
IX_55467943=OSB_TicketFeedback.U_TEI_S_NotS

IX_34D48682=OSB_TicketFlag.AEI_T
IX_21EF78C3=OSB_TicketFlag.TEI_T
IX_415DBAE3=OSB_TicketFlag.TEI_T_F
IX_A43C0D2=OSB_TicketFlag.TicketEntryId
IX_FC942931=OSB_TicketFlag.U_AEI_TEI_T

IX_C15F4C19=OSB_TicketInformation.TEI_FI
IX_539CB0C=OSB_TicketInformation.TicketEntryId

IX_90EFDA98=OSB_TicketLink.TEI_TSI
IX_F493310A=OSB_TicketLink.TEI_V
IX_22E27E04=OSB_TicketLink.TicketEntryId

IX_F1F54CE5=OSB_TicketSolution.TicketEntryId

IX_1D95DF06=OSB_TicketWorker.SCNI_SCPK
IX_26AF5491=OSB_TicketWorker.TEI_P
IX_CFAE8A40=OSB_TicketWorker.TicketEntryId
IX_B8E7B7C6=OSB_TicketWorker.U_TEI
IX_C09CD9CB=OSB_TicketWorker.UserId

IX_2F6A1E76=OSB_TrainingCertificate.Key
IX_940016E9=OSB_TrainingCertificate.TrainingCustomerId

IX_7E1FDA19=OSB_TrainingCertificateTemplate.Type

IX_B8FB20D4=OSB_TrainingCustomer.C_C
IX_6CC54BBA=OSB_TrainingCustomer.C_C_S
IX_27854F5=OSB_TrainingCustomer.U_C
IX_2248428E=OSB_TrainingCustomer.U_C_C
IX_6BD1C0F9=OSB_TrainingCustomer.UserId

IX_CD618D79=OSB_TrainingEvent.DDLRecordSetId
IX_7D10E314=OSB_TrainingEvent.TC_T_SD
IX_3773B4D0=OSB_TrainingEvent.T_SD
IX_DFBDC0DD=OSB_TrainingEvent.TrainingCertificateTemplateId
IX_192EB969=OSB_TrainingEvent.TrainingCourseId
IX_44DDD7C3=OSB_TrainingEvent.TrainingLocationId

IX_B1D428FF=OSB_TrainingExam.Name
IX_C2119662=OSB_TrainingExam.TrainingCertificateTemplateId

IX_359F9FB=OSB_TrainingExamResult.GtCreateDate
IX_CD97224A=OSB_TrainingExamResult.GtSD_G_NotS
IX_ED881F93=OSB_TrainingExamResult.RegistrationNumber

IX_51323EB5=OSB_TrainingExamResultItem.TrainingExamResultId
IX_41864BEA=OSB_TrainingExamResultItem.TrainingExamResultSectionId

IX_FF29C879=OSB_TrainingExamResultSection.TrainingExamResultId

IX_FE8EC56B=OSB_TrainingImportLog.Type

IX_64CA91D3=OSB_TrainingLinkedUser.PrimaryUserId
IX_DEA7805F=OSB_TrainingLinkedUser.UserId

IX_930AF34=OSB_TrainingWorker.C_C
IX_FCB970EE=OSB_TrainingWorker.U_C_C
IX_F855F759=OSB_TrainingWorker.UserId

IX_86ECAD1D=OSB_UserProfile.UserId

IX_154A2B12=OSB_UserProfileHistory.C_C
IX_BB200AF7=OSB_UserProfileHistory.U_C