insert into ListType (listTypeId, name, type_) values (20000, '4.4', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20001, '5.1', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20002, '5.1 SP1', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20003, '5.1 SP2', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20004, '5.1 SP3', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20005, '5.1 SP4', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20006, '5.1 SP5', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20020, '5.2', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20021, '5.2 SP1', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20022, '5.2 SP2', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20023, '5.2 SP3', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20024, '5.2 SP4', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20025, '5.2 SP5', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20040, '6.0', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20041, '6.0 SP1', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20042, '6.0 SP2', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20060, '6.1 GA1', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20061, '6.1 GA2', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20062, '6.1 GA3', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20080, '6.2 EE', 'com.liferay.osb.model.ProductEntry.portalAllVersions');
insert into ListType (listTypeId, name, type_) values (20999, 'other', 'com.liferay.osb.model.ProductEntry.portalAllVersions');

insert into ListType (listTypeId, name, type_) values (21000, '5', 'com.liferay.osb.model.ProductEntry.portalMajorVersions');
insert into ListType (listTypeId, name, type_) values (21001, '6', 'com.liferay.osb.model.ProductEntry.portalMajorVersions');

insert into ListType (listTypeId, name, type_) values (22000, '5.1', 'com.liferay.osb.model.ProductEntry.portalMinorVersions');
insert into ListType (listTypeId, name, type_) values (22001, '5.2', 'com.liferay.osb.model.ProductEntry.portalMinorVersions');
insert into ListType (listTypeId, name, type_) values (22002, '6.0', 'com.liferay.osb.model.ProductEntry.portalMinorVersions');
insert into ListType (listTypeId, name, type_) values (22003, '6.1', 'com.liferay.osb.model.ProductEntry.portalMinorVersions');
insert into ListType (listTypeId, name, type_) values (22004, '6.2', 'com.liferay.osb.model.ProductEntry.portalMinorVersions');

insert into ListType (listTypeId, name, type_) values (23000, '1.5', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23001, '1.6', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23002, '2.0.3', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23003, '2.0.4', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23004, '2.0.5', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23020, '2.1.0', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23040, '3.0.0', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23041, '3.0.1', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23042, '3.0.2', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23060, '3.1.0', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23061, '3.1.1', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');
insert into ListType (listTypeId, name, type_) values (23999, 'other', 'com.liferay.osb.model.ProductEntry.socialOfficeAllVersions');

insert into ListType (listTypeId, name, type_) values (24000, '1', 'com.liferay.osb.model.ProductEntry.socialOfficeMajorVersions');
insert into ListType (listTypeId, name, type_) values (24001, '2', 'com.liferay.osb.model.ProductEntry.socialOfficeMajorVersions');
insert into ListType (listTypeId, name, type_) values (24002, '3', 'com.liferay.osb.model.ProductEntry.socialOfficeMajorVersions');

insert into ListType (listTypeId, name, type_) values (25000, '1.5', 'com.liferay.osb.model.ProductEntry.socialOfficeMinorVersions');
insert into ListType (listTypeId, name, type_) values (25001, '1.6', 'com.liferay.osb.model.ProductEntry.socialOfficeMinorVersions');
insert into ListType (listTypeId, name, type_) values (25002, '2.0', 'com.liferay.osb.model.ProductEntry.socialOfficeMinorVersions');
insert into ListType (listTypeId, name, type_) values (25003, '2.1', 'com.liferay.osb.model.ProductEntry.socialOfficeMinorVersions');
insert into ListType (listTypeId, name, type_) values (25004, '3.0', 'com.liferay.osb.model.ProductEntry.socialOfficeMinorVersions');
insert into ListType (listTypeId, name, type_) values (25005, '3.1', 'com.liferay.osb.model.ProductEntry.socialOfficeMinorVersions');

insert into ListType (listTypeId, name, type_) values (27000, 'glassfish-2.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27001, 'glassfish-3.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27002, 'jboss-4.2.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27003, 'jboss-5.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27004, 'other', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27005, 'tomcat-5.5.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27006, 'tomcat-6.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27007, 'weblogic-9.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27008, 'weblogic-10.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27009, 'websphere-6.1.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27010, 'websphere-7.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27011, 'tcat', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27012, 'jboss-7.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27013, 'tomcat-7.0.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27014, 'tcat-6.4', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27015, 'weblogic-11.x', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27016, 'glassfish-2.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27017, 'glassfish-3', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27018, 'glassfish-3.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27019, 'jboss-5.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27020, 'jboss-as-7.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27021, 'jboss-tomcat-4.2', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27022, 'jboss-tomcat-5.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27023, 'jonas-5.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27024, 'jonas-5.2', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27025, 'jonas-6.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27026, 'jonas-tomcat-4.10', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27027, 'oracleas-10.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27028, 'resin-3.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27029, 'resin-4', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27030, 'tomcat-5.5', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27031, 'tomcat-6.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27032, 'weblogic-9.2', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27033, 'weblogic-10.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27034, 'weblogic-10.3', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27035, 'weblogic-11', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27036, 'websphere-6.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27037, 'websphere-7.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27038, 'websphere-8', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27039, 'tomcat-7.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27040, 'jboss-eap-6.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27041, 'tcServer-2.6', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27042, 'jboss-eap-5.2', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27043, 'tcat-7.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27044, 'tcServer-2.9', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27045, 'weblogic-11.g', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27046, 'weblogic-12c-r1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27047, 'websphere-8.5', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27048, 'glassfish-4.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27049, 'jboss-eap-6.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27050, 'jboss-eap-5.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27051, 'jboss-eap-6.2', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27052, 'jboss-eap-6.3', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27053, 'jboss-eap-6.4', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27054, 'tcServer-3.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27055, 'tomcat-8.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27056, 'weblogic-12c-r2', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27057, 'wildfly-10.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27058, 'jboss-eap-7.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27059, 'tomcat-8.5', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27060, 'tcServer-3.2', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27061, 'jboss-eap-7.1', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27062, 'tcServer-4.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27063, 'tomcat-9.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27064, 'websphere-9.0', 'com.liferay.osb.model.AccountEnvironment.envAS');
insert into ListType (listTypeId, name, type_) values (27065, 'wildfly-11.0', 'com.liferay.osb.model.AccountEnvironment.envAS');

insert into ListType (listTypeId, name, type_) values (28000, 'db2-8.2', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28002, 'hypersonic', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28003, 'mysql-5.0', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28004, 'mysql-5.1', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28005, 'oracle-9i', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28006, 'oracle-10g', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28007, 'oracle-11g', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28008, 'other', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28009, 'postgresql', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28010, 'sql-server-2000', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28011, 'sql-server-2005', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28012, 'sql-server-2008', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28013, 'db2-9.7', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28014, 'mysql-5.5', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28015, 'sybase-ase-15.5', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28016, 'db2-8.1', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28017, 'oracle-10g-release-2', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28018, 'oracle-11g-release-1', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28019, 'oracle-11g-release-2', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28020, 'postgresql-8.4', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28021, 'postgresql-9.0', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28022, 'sql-server-2008-r2', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28023, 'sybase-ase-15.0', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28024, 'db2-10.1', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28025, 'mysql-5.6', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28026, 'postgresql-9.1', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28027, 'postgresql-9.2', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28028, 'sql-server-2012', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28029, 'sybase-ase-15.7', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28030, 'oracle-12c-release-1', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28031, 'postgresql-9.3', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28032, 'sql-server-2014', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28033, 'mariadb-10', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28034, 'postgresql-9.4', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28035, 'sybase-ase-16', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28036, 'mysql-5.7', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28037, 'sql-server-2016', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28038, 'db2-10.5', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28039, 'postgresql-9.6', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28040, 'oracle-12c-release-2', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28041, 'amazon-aurora', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28042, 'db2-11.1', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28043, 'mariadb-10.2', 'com.liferay.osb.model.AccountEnvironment.envDB');
insert into ListType (listTypeId, name, type_) values (28044, 'postgresql-10', 'com.liferay.osb.model.AccountEnvironment.envDB');

insert into ListType (listTypeId, name, type_) values (29000, 'oracle-sun-jdk-5', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29001, 'oracle-sun-jdk-6', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29002, 'oracle-sun-jdk-7', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29003, 'ibm-jdk-6', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29004, 'ibm-jdk-7', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29005, 'jrocket-jdk-6', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29006, 'oracle-sun-jdk-8', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29007, 'ibm-jdk-8', 'com.liferay.osb.model.AccountEnvironment.envJVM');
insert into ListType (listTypeId, name, type_) values (29008, 'openjdk-8', 'com.liferay.osb.model.AccountEnvironment.envJVM');

insert into ListType (listTypeId, name, type_) values (30000, 'linux', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30001, 'mac-os-x', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30002, 'windows-7', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30003, 'windows-xp', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30004, 'windows-server-2003', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30005, 'windows-server-2008', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30006, 'other', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30007, 'red-hat', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30008, 'windows-server-2008-r2', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30009, 'aix', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30010, 'aix-6.1', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30011, 'aix-7.1', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30012, 'centos-4', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30013, 'centos-5', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30014, 'centos-6', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30015, 'hp-ux', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30016, 'oracle-linux', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30017, 'oracle-linux-6', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30018, 'other-linux-distribution', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30019, 'red-hat-enterprise-4', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30020, 'red-hat-enterprise-5', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30021, 'red-hat-enterprise-6', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30022, 'solaris-10', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30023, 'ubuntu', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30024, 'mac-os-x-10.5+', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30025, 'solaris-express-11', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30026, 'ubuntu-10', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30027, 'ubuntu-11', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30028, 'ubuntu-12', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30029, 'ubuntu-13', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30030, 'windows-server-2012', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30031, 'solaris-11', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30032, 'opensuse-13.1', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30033, 'suse-enterprise-linux-11', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30034, 'debian-6.0', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30035, 'red-hat-enterprise-7', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30036, 'centos-7', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30037, 'debian-8', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30038, 'oracle-linux-7', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30039, 'suse-enterprise-linux-12', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30040, 'ubuntu-lts-14.04', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30041, 'debian-7', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30042, 'ubuntu-lts-16.04', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30043, 'windows-server-2016', 'com.liferay.osb.model.AccountEnvironment.envOS');
insert into ListType (listTypeId, name, type_) values (30044, 'debian-9', 'com.liferay.osb.model.AccountEnvironment.envOS');

insert into ListType (listTypeId, name, type_) values (34001, 'application-server', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34004, 'database', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34009, 'file', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34010, 'java-virtual-machine', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34011, 'liferay-version', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34012, 'operating-system', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34015, 'role', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34017, 'status', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34020, 'url', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34021, 'user', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34025, 'renew-count', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34028, 'environment-name', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34029, 'primary-browser', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34035, 'primary', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34037, 'replicate', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34051, 'support-region', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34054, 'tier', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34055, 'partner', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34056, 'cloud-services', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34057, 'search', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34058, 'corp-project', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34059, 'corp-entry-name', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34060, 'name', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34061, 'code', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34062, 'type', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34063, 'industry', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34064, 'partner-managed-support', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34065, 'instructions', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34066, 'notes', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34067, 'renewal-contact-user', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34068, 'status-message', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34069, 'address', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34070, 'languages', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34071, 'support-regions', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34072, 'not-applicable', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34073, 'offerings', 'com.liferay.osb.model.AuditEntry.field');
insert into ListType (listTypeId, name, type_) values (34078, 'dossiera-account-key', 'com.liferay.osb.model.AuditEntry.field');

insert into ListType (listTypeId, name, type_) values (35000, 'aerospace-and-defense', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35001, 'agriculture', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35002, 'automotive', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35003, 'consulting-market-research', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35004, 'retail-consumer-products', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35005, 'education', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35006, 'energy', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35007, 'financial-services', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35009, 'healthcare', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35010, 'hospitality-leisure', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35011, 'insurance', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35012, 'manufacturing', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35013, 'media-entertainment', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35014, 'not-for-profit-ngo', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35015, 'other', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35016, 'pharmaceuticals', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35018, 'technology', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35019, 'telecommunications', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35020, 'transportation', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35022, 'utilities', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35023, 'engineering', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35024, 'government-federal', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35025, 'government-state-local', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35026, 'professional-services-agency-business', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35027, 'professional-services-technical-web-it', 'com.liferay.osb.model.AccountEntry.industry');
insert into ListType (listTypeId, name, type_) values (35028, 'food-services', 'com.liferay.osb.model.AccountEntry.industry');

insert into ListType (listTypeId, name, type_) values (36000, 'business', 'com.liferay.osb.model.PartnerEntry.phone');
insert into ListType (listTypeId, name, type_) values (36001, 'business-fax', 'com.liferay.osb.model.PartnerEntry.phone');
insert into ListType (listTypeId, name, type_) values (36002, 'other', 'com.liferay.osb.model.PartnerEntry.phone');

insert into ListType (listTypeId, name, type_) values (37000, 'chrome', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37001, 'firefox', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37002, 'ie-6', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37003, 'ie-7', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37004, 'ie-8', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37005, 'ie-9', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37006, 'ie-10', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37007, 'safari-5', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37008, 'safari-6', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37009, 'ie-11', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37010, 'android-browser-4.3+', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37012, 'ios-safari', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37013, 'edge', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37014, 'firefox-esr-45', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37015, 'safari-9', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37016, 'safari-8', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37017, 'mobile-chrome', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37018, 'safari-10', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37019, 'firefox-esr-52', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37020, 'safari-11', 'com.liferay.osb.model.AccountEnvironment.envBrowser');
insert into ListType (listTypeId, name, type_) values (37999, 'other', 'com.liferay.osb.model.AccountEnvironment.envBrowser');

insert into ListType (listTypeId, name, type_) values (38000, 'e-mail', 'com.liferay.osb.model.SalesPartnership.emailAddress');

insert into ListType (listTypeId, name, type_) values (39000, 'aws-elastic-compute-cloud', 'com.liferay.osb.model.AccountEnvironment.envCS');
insert into ListType (listTypeId, name, type_) values (39001, 'aws-relational-database-service', 'com.liferay.osb.model.AccountEnvironment.envCS');
insert into ListType (listTypeId, name, type_) values (39002, 'aws-s3', 'com.liferay.osb.model.AccountEnvironment.envCS');
insert into ListType (listTypeId, name, type_) values (39003, 'azure-files', 'com.liferay.osb.model.AccountEnvironment.envCS');
insert into ListType (listTypeId, name, type_) values (39004, 'azure-sql-databases', 'com.liferay.osb.model.AccountEnvironment.envCS');
insert into ListType (listTypeId, name, type_) values (39005, 'azure-virtual-machines', 'com.liferay.osb.model.AccountEnvironment.envCS');
insert into ListType (listTypeId, name, type_) values (39006, 'aws-aurora', 'com.liferay.osb.model.AccountEnvironment.envCS');

insert into ListType (listTypeId, name, type_) values (40000, 'elasticsearch-2.x', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40001, 'kibana-4.x', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40002, 'marvel-2.x', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40003, 'shield-2.x', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40004, 'solr', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40005, 'solrcloud', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40006, 'elasticsearch-6.x', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40007, 'kibana-6.x', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40008, 'x-pack-6.x', 'com.liferay.osb.model.AccountEnvironment.envSearch');
insert into ListType (listTypeId, name, type_) values (40009, 'solr-5', 'com.liferay.osb.model.AccountEnvironment.envSearch');

insert into ListType (listTypeId, name, type_) values (41000, '7.0', 'com.liferay.osb.model.ProductEntry.digitalEnterpriseAllVersions');
insert into ListType (listTypeId, name, type_) values (41100, '7.1', 'com.liferay.osb.model.ProductEntry.digitalEnterpriseAllVersions');

insert into ListType (listTypeId, name, type_) values (42000, '7', 'com.liferay.osb.model.ProductEntry.digitalEnterpriseMajorVersions');

insert into ListType (listTypeId, name, type_) values (43000, '7.0', 'com.liferay.osb.model.ProductEntry.digitalEnterpriseMinorVersions');
insert into ListType (listTypeId, name, type_) values (43001, '7.1', 'com.liferay.osb.model.ProductEntry.digitalEnterpriseMinorVersions');