create table OSB_LCSSubscriptionEntry (
	lcsSubscriptionEntryId LONG not null primary key,
	lcsProjectId LONG,
	product VARCHAR(75) null,
	productVersion INTEGER,
	type_ VARCHAR(75) null,
	platform VARCHAR(75) null,
	platformVersion VARCHAR(75) null,
	serversAllowed INTEGER,
	serversUsed INTEGER,
	quantity INTEGER,
	instanceSize INTEGER,
	startDate DATE null,
	endDate DATE null,
	supportStartDate DATE null,
	supportEndDate DATE null,
	actualPrice DOUBLE,
	currencyCode VARCHAR(75) null,
	active_ BOOLEAN
);

create table OSB_LicenseEntry (
	licenseEntryId LONG not null primary key,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	productEntryId LONG,
	name VARCHAR(75) null,
	type_ VARCHAR(75) null,
	versionMin INTEGER,
	versionMax INTEGER
);

create table OSB_LicenseKey (
	uuid_ VARCHAR(75) null,
	licenseKeyId LONG not null primary key,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedUserId LONG,
	modifiedUserName VARCHAR(75) null,
	modifiedDate DATE null,
	licenseKeySetId LONG,
	assetReceiptLicenseUuid VARCHAR(75) null,
	accountEntryId LONG,
	orderEntryId LONG,
	offeringEntryId LONG,
	licenseEntryId LONG,
	productEntryId LONG,
	supportResponseId LONG,
	accountEntryName VARCHAR(500) null,
	licenseEntryName VARCHAR(75) null,
	licenseEntryType VARCHAR(75) null,
	licenseVersion INTEGER,
	productEntryName VARCHAR(75) null,
	productId VARCHAR(75) null,
	productVersion INTEGER,
	productVersionLabel VARCHAR(75) null,
	clusterId LONG,
	owner VARCHAR(75) null,
	maxServers INTEGER,
	maxConcurrentUsers LONG,
	maxUsers LONG,
	maxHttpSessions INTEGER,
	sizing INTEGER,
	description VARCHAR(255) null,
	hostName VARCHAR(75) null,
	ipAddresses STRING null,
	macAddresses STRING null,
	serverId STRING null,
	key_ STRING null,
	startDate DATE null,
	expirationDate DATE null,
	additionalInfo STRING null,
	complimentary BOOLEAN,
	active_ BOOLEAN
);

create table OSB_LicenseKeySet (
	licenseKeySetId LONG not null primary key,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	accountEntryId LONG,
	name VARCHAR(75) null
);