##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.check.JavaModuleComponentCheck.allowedClassNames=\
        com.liferay.osb.testray.issue.engine.util.TestrayIssueEngineUtil

##
## Git
##

    git.liferay.portal.branch=7.0.x

##
## Checkstyle Properties
##

    checkstyle.JSONUtilCheck.enabled=false

    checkstyle.ListUtilCheck.enabled=false

    checkstyle.StaticBlockCheck.enabled=false

    checkstyle.VariableDeclarationAsUsedCheck.enabled=false

    checkstyle.VariableNameCheck.enabled=false

##
## Source Check Properties
##

    source.check.BNDSuiteCheck.enabled=false

    source.check.GradleDependenciesCheck.petra.dependencies=false

    source.check.GradleTestDependencyVersionCheck.enabled=false

    source.check.JavaAnonymousInnerClassCheck.enabled=false

    source.check.JavaAPISignatureCheck.enabled=false

    source.check.JavaComponentAnnotationsCheck.enabled=false

    source.check.JavaDeprecatedKernelClassesCheck.enabled=false

    source.check.JavaInternalPackageCheck.enabled=false

    source.check.JavaProviderTypeAnnotationCheck.enabled=true

    source.check.JSPStringMethodsCheck.enabled=false

    source.check.PropertiesLanguageKeysCheck.enabled=false

    source.check.StringMethodsCheck.enabled=false