##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.check.java.module.component.check.allowedClassNames=\
        com.liferay.osb.testray.issue.engine.util.TestrayIssueEngineUtil

##
## Git
##

    git.liferay.portal.branch=7.0.x

##
## Checkstyle Properties
##

    checkstyle.variable.name.check.enabled=false

##
## Source Check Properties
##

    source.check.java.api.signature.check.enabled=false

    source.check.java.deprecated.kernel.classes.check.enabled=false

    source.check.bnd.suite.check.enabled=false

    source.check.properties.language.keys.check.enabled=false