##
## Git
##

    git.liferay.portal.branch=7.0.x

##
## Source Check Properties
##

    source.check.JavaModuleComponentCheck.allowedClassNames=\
        com.liferay.osb.testray.issue.engine.util.TestrayIssueEngineUtil