/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.loop.asset.entry.set.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.osb.loop.asset.entry.set.service.persistence.AssetEntrySetLikePK;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AssetEntrySetLike service. Represents a row in the &quot;AssetEntrySetLike&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.loop.asset.entry.set.model.impl.AssetEntrySetLikeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.loop.asset.entry.set.model.impl.AssetEntrySetLikeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntrySetLike
 * @see com.liferay.osb.loop.asset.entry.set.model.impl.AssetEntrySetLikeImpl
 * @see com.liferay.osb.loop.asset.entry.set.model.impl.AssetEntrySetLikeModelImpl
 * @generated
 */
@ProviderType
public interface AssetEntrySetLikeModel extends AttachedModel,
	BaseModel<AssetEntrySetLike> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset entry set like model instance should use the {@link AssetEntrySetLike} interface instead.
	 */

	/**
	 * Returns the primary key of this asset entry set like.
	 *
	 * @return the primary key of this asset entry set like
	 */
	public AssetEntrySetLikePK getPrimaryKey();

	/**
	 * Sets the primary key of this asset entry set like.
	 *
	 * @param primaryKey the primary key of this asset entry set like
	 */
	public void setPrimaryKey(AssetEntrySetLikePK primaryKey);

	/**
	 * Returns the asset entry set ID of this asset entry set like.
	 *
	 * @return the asset entry set ID of this asset entry set like
	 */
	public long getAssetEntrySetId();

	/**
	 * Sets the asset entry set ID of this asset entry set like.
	 *
	 * @param assetEntrySetId the asset entry set ID of this asset entry set like
	 */
	public void setAssetEntrySetId(long assetEntrySetId);

	/**
	 * Returns the fully qualified class name of this asset entry set like.
	 *
	 * @return the fully qualified class name of this asset entry set like
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset entry set like.
	 *
	 * @return the class name ID of this asset entry set like
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset entry set like.
	 *
	 * @param classNameId the class name ID of this asset entry set like
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this asset entry set like.
	 *
	 * @return the class pk of this asset entry set like
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this asset entry set like.
	 *
	 * @param classPK the class pk of this asset entry set like
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetEntrySetLike assetEntrySetLike);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetEntrySetLike> toCacheModel();

	@Override
	public AssetEntrySetLike toEscapedModel();

	@Override
	public AssetEntrySetLike toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}