INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, NULL, DATETIME_TRUNC(TIMESTAMP '${now-1d}', HOUR), 1);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'United States', DATETIME_TRUNC(TIMESTAMP '${now-1d}', HOUR), 1);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'Japan', DATETIME_TRUNC(TIMESTAMP '${now-5d}', HOUR), 2);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'France', DATETIME_TRUNC(TIMESTAMP '${now-10d}', HOUR), 3);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'United States', DATETIME_TRUNC(TIMESTAMP '${now-15d}', HOUR), 4);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'Japan', DATETIME_TRUNC(TIMESTAMP '${now-20d}', HOUR), 5);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'France', DATETIME_TRUNC(TIMESTAMP '${now-29d}', HOUR), 6);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'United States', DATETIME_TRUNC(TIMESTAMP '${now-31d}', HOUR), 7);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'Japan', DATETIME_TRUNC(TIMESTAMP '${now-40d}', HOUR), 8);
INSERT INTO BlogDaily (assetId, channelId, country, eventDate, views) VALUES ('e131fabc', 1, 'France', DATETIME_TRUNC(TIMESTAMP '${now-45d}', HOUR), 9);