INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now}' ), 'blogViewed', '1');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'blogViewed', '2');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'blogViewed', '3');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'blogViewed', '4');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'blogViewed', '5');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'blogViewed', '6');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'blogViewed', '7');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'blogViewed', '8');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'blogViewed', '9');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'blogViewed', '10');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'blogViewed', '11');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'blogViewed', '12');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'blogViewed', '13');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'blogViewed', '14');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'blogViewed', '15');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'blogViewed', '16');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'blogViewed', '17');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'blogViewed', '18');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'blogViewed', '19');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'blogViewed', '20');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'blogViewed', '21');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'blogViewed', '22');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'blogViewed', '23');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'blogViewed', '24');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'blogViewed', '25');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Blog', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'blogViewed', '26');

INSERT INTO BQEventProperty (id, name, value) VALUES ('1', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('2', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('3', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('4', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('5', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('6', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('7', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('8', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('9', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('10', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('11', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('12', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('13', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('14', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('15', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('16', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('17', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('18', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('19', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('20', 'entryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('21', 'entryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('22', 'entryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('23', 'entryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('24', 'entryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('25', 'entryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('26', 'entryId', 'a73ihsy9');