INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', NULL, 1, DATETIME_TRUNC(timestamp '${now-15d}', HOUR), 1);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Chrome', 1, DATETIME_TRUNC(timestamp '${now-15d}', HOUR), 4);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Chrome', 1, DATETIME_TRUNC(timestamp '${now-35d}', HOUR), 6);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Chrome', 1, DATETIME_TRUNC(timestamp '${now-4d}', HOUR), 3);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Chrome', 1, DATETIME_TRUNC(timestamp '${now-5d}', HOUR), 2);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Firefox',  1, DATETIME_TRUNC(timestamp '${now-10d}', HOUR), 3);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Firefox', 1, DATETIME_TRUNC(timestamp '${now-12d}', HOUR), 1);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Firefox', 1, DATETIME_TRUNC(timestamp '${now-1d}', HOUR), 5);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Firefox', 1, DATETIME_TRUNC(timestamp '${today-1h}', HOUR), 5);
INSERT INTO BlogDaily (assetId, browserName, channelId, eventDate, views) VALUES ('e131fabc', 'Opera Desktop', 1, DATETIME_TRUNC(timestamp '${now-18d}', HOUR), 3);