INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-4h}', 'assetViewed', '1');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-7h}', 'assetViewed', '2');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-7h}', 'assetViewed', '3');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-10h}', 'assetViewed', '4');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-10h}', 'assetViewed', '5');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-10h}', 'assetViewed', '6');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-10h}', 'assetViewed', '7');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-29h}', 'assetViewed', '8');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-29h}', 'assetViewed', '9');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-29h}', 'assetViewed', '10');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-29h}', 'assetViewed', '11');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-30h}', 'assetViewed', '12');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-30h}', 'assetViewed', '13');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-8h}', 'assetViewed', '14');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-8h}', 'assetViewed', '15');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-8h}', 'assetViewed', '16');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-8h}', 'assetViewed', '17');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-8h}', 'assetViewed', '18');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-8h}', 'assetViewed', '19');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 1, timestamp '${now-8h}', 'assetViewed', '20');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 2, timestamp '${now-8h}', 'assetViewed', '21');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Custom', 2, timestamp '${now-8h}', 'assetViewed', '22');


INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '1', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '2', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '3', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '4', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '5', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '6', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '7', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '8', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '9', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '10', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '11', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '12', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '13', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '14', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '15', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '16', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '17', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '18', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '19', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (1, '20', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (2, '21', 'assetId', 'A');
INSERT INTO BQEventProperty (channelId, id, name, value) VALUES (2, '22', 'assetId', 'A');