INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now}' ), 'documentPreviewed', '1');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'documentPreviewed', '2');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'documentPreviewed', '3');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'documentPreviewed', '4');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'documentPreviewed', '5');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'documentPreviewed', '6');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'documentPreviewed', '7');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'documentPreviewed', '8');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'documentPreviewed', '9');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'documentPreviewed', '10');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'documentPreviewed', '11');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'documentPreviewed', '12');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'documentPreviewed', '13');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'documentPreviewed', '14');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'documentPreviewed', '15');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'documentPreviewed', '16');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'documentPreviewed', '17');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'documentPreviewed', '18');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'documentPreviewed', '19');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'documentPreviewed', '20');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'documentPreviewed', '21');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'documentPreviewed', '22');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'documentPreviewed', '23');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'documentPreviewed', '24');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'documentPreviewed', '25');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Document', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'documentPreviewed', '26');

INSERT INTO BQEventProperty (id, name, value) VALUES ('1', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('2', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('3', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('4', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('5', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('6', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('7', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('8', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('9', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('10', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('11', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('12', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('13', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('14', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('15', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('16', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('17', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('18', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('19', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('20', 'fileEntryId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('21', 'fileEntryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('22', 'fileEntryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('23', 'fileEntryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('24', 'fileEntryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('25', 'fileEntryId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('26', 'fileEntryId', 'a73ihsy9');