INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now}' ), 'formViewed', '1');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'formViewed', '2');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'formViewed', '3');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'formViewed', '4');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'formViewed', '5');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'formViewed', '6');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'formViewed', '7');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'formViewed', '8');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'formViewed', '9');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'formViewed', '10');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'formViewed', '11');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'formViewed', '12');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'formViewed', '13');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'formViewed', '14');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'formViewed', '15');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'formViewed', '16');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'formViewed', '17');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'formViewed', '18');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'formViewed', '19');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'formViewed', '20');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'formViewed', '21');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'formViewed', '22');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'formViewed', '23');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'formViewed', '24');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'formViewed', '25');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('Form', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'formViewed', '26');

INSERT INTO BQEventProperty (id, name, value) VALUES ('1', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('2', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('3', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('4', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('5', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('6', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('7', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('8', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('9', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('10', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('11', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('12', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('13', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('14', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('15', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('16', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('17', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('18', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('19', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('20', 'formId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('21', 'formId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('22', 'formId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('23', 'formId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('24', 'formId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('25', 'formId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('26', 'formId', 'a73ihsy9');