INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now}' ), 'webContentViewed', '1');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'webContentViewed', '2');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'webContentViewed', '3');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'webContentViewed', '4');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-10h}'), 'webContentViewed', '5');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'webContentViewed', '6');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-7h}'), 'webContentViewed', '7');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'webContentViewed', '8');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'webContentViewed', '9');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'webContentViewed', '10');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'webContentViewed', '11');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 2, date_trunc('HOUR', timestamp '${now-8h}'), 'webContentViewed', '12');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'webContentViewed', '13');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'webContentViewed', '14');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'webContentViewed', '15');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-25h}'), 'webContentViewed', '16');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'webContentViewed', '17');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'webContentViewed', '18');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'webContentViewed', '19');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-26h}'), 'webContentViewed', '20');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'webContentViewed', '21');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'webContentViewed', '22');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'webContentViewed', '23');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-5h}'), 'webContentViewed', '24');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'webContentViewed', '25');
INSERT INTO BQEvent (applicationId, channelId, eventDate, eventId, id) VALUES ('WebContent', 1, date_trunc('HOUR', timestamp '${now-6h}'), 'webContentViewed', '26');

INSERT INTO BQEventProperty (id, name, value) VALUES ('1', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('2', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('3', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('4', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('5', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('6', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('7', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('8', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('9', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('10', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('11', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('12', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('13', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('14', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('15', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('16', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('17', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('18', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('19', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('20', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('21', 'articleId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('22', 'articleId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('23', 'articleId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('24', 'articleId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('25', 'articleId', 'a73ihsy9');
INSERT INTO BQEventProperty (id, name, value) VALUES ('26', 'articleId', 'a73ihsy9');