INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-15d}'), 'webContentViewed', '1');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-15d}'), 'webContentViewed', '2');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-15d}'), 'webContentViewed', '3');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-15d}'), 'webContentViewed', '4');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-35d}'), 'webContentViewed', '5');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-35d}'), 'webContentViewed', '6');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-35d}'), 'webContentViewed', '7');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-35d}'), 'webContentViewed', '8');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-35d}'), 'webContentViewed', '9');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-35d}'), 'webContentViewed', '10');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-4d}'), 'webContentViewed', '11');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-4d}'), 'webContentViewed', '12');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-4d}'), 'webContentViewed', '13');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-5d}'), 'webContentViewed', '14');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Chrome', 1, date_trunc('HOUR', timestamp '${now-5d}'), 'webContentViewed', '15');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-10d}'), 'webContentViewed', '16');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-10d}'), 'webContentViewed', '17');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-10d}'), 'webContentViewed', '18');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-12d}'), 'webContentViewed', '19');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-1d}'), 'webContentViewed', '20');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-1d}'), 'webContentViewed', '21');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-1d}'), 'webContentViewed', '22');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-1d}'), 'webContentViewed', '23');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${now-1d}'), 'webContentViewed', '24');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${today-1h}'), 'webContentViewed', '25');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${today-1h}'), 'webContentViewed', '26');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${today-1h}'), 'webContentViewed', '27');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${today-1h}'), 'webContentViewed', '28');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', 'Firefox', 1, date_trunc('HOUR', timestamp '${today-1h}'), 'webContentViewed', '29');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', NULL, 1, date_trunc('HOUR', timestamp '${now-18d}'), 'webContentViewed', '30');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', NULL, 1, date_trunc('HOUR', timestamp '${now-18d}'), 'webContentViewed', '31');
INSERT INTO BQEvent (applicationId, browserName, channelId, eventDate, eventId, id) VALUES ('WebContent', NULL, 1, date_trunc('HOUR', timestamp '${now-18d}'), 'webContentViewed', '32');

INSERT INTO BQEventProperty (id, name, value) VALUES ('1', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('2', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('3', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('4', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('5', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('6', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('7', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('8', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('9', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('10', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('11', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('12', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('13', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('14', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('15', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('16', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('17', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('18', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('19', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('20', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('21', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('22', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('23', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('24', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('25', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('26', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('27', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('28', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('29', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('30', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('31', 'articleId', 'e131fabc');
INSERT INTO BQEventProperty (id, name, value) VALUES ('32', 'articleId', 'e131fabc');