

liferay.home=/home/jaimeleon/Desktop/master/master-portal/../bundles

jdbc.default.jndi.name=

jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.default.username=root
jdbc.default.password=

enterprise.product.notification.enabled=false

company.security.strangers.verify=false

default.admin.password=test

browser.launcher.url=

setup.wizard.enabled=false

passwords.default.policy.change.required=false

mail.send.blacklist=

mail.session.jndi.name=

memory.scheduler.org.quartz.threadPool.threadCount=1

persisted.scheduler.org.quartz.threadPool.threadCount=1

virtual.hosts.default.site.name=

com.liferay.portal.servlet.filters.strip.StripFilter=true

web.server.http.port=8080

admin.email.from.address=test@liferay.com

announcements.email.to.address=noreply@liferay.com

login.secure.forgot.password=false

module.framework.properties.blacklist.portal.profile.names=opensocial-portlet