/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.community.github.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.community.github.model.GitHubContributor;
import com.liferay.osb.community.github.model.GitHubContributorModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GitHubContributor service. Represents a row in the &quot;OSBCommunity_GitHubContributor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GitHubContributorModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GitHubContributorImpl}.
 * </p>
 *
 * @author Haote Chou
 * @see GitHubContributorImpl
 * @generated
 */
public class GitHubContributorModelImpl
	extends BaseModelImpl<GitHubContributor> implements GitHubContributorModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a git hub contributor model instance should use the <code>GitHubContributor</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSBCommunity_GitHubContributor";

	public static final Object[][] TABLE_COLUMNS = {
		{"gitHubContributorId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"gitHubRepositoryId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"avatarURL", Types.VARCHAR}, {"contributions", Types.INTEGER},
		{"profileURL", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("gitHubContributorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("gitHubRepositoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("avatarURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contributions", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("profileURL", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSBCommunity_GitHubContributor (gitHubContributorId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,gitHubRepositoryId LONG,name VARCHAR(75) null,avatarURL VARCHAR(75) null,contributions INTEGER,profileURL VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OSBCommunity_GitHubContributor";

	public static final String ORDER_BY_JPQL =
		" ORDER BY gitHubContributor.contributions DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSBCommunity_GitHubContributor.contributions DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.community.github.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.community.github.model.GitHubContributor"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.community.github.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.community.github.model.GitHubContributor"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.community.github.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.community.github.model.GitHubContributor"),
		true);

	public static final long GITHUBREPOSITORYID_COLUMN_BITMASK = 1L;

	public static final long CONTRIBUTIONS_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.community.github.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.community.github.model.GitHubContributor"));

	public GitHubContributorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _gitHubContributorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGitHubContributorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _gitHubContributorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GitHubContributor.class;
	}

	@Override
	public String getModelClassName() {
		return GitHubContributor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GitHubContributor, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GitHubContributor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GitHubContributor, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GitHubContributor)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GitHubContributor, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GitHubContributor, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GitHubContributor)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GitHubContributor, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GitHubContributor, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GitHubContributor>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GitHubContributor.class.getClassLoader(), GitHubContributor.class,
			ModelWrapper.class);

		try {
			Constructor<GitHubContributor> constructor =
				(Constructor<GitHubContributor>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GitHubContributor, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GitHubContributor, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GitHubContributor, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<GitHubContributor, Object>>();
		Map<String, BiConsumer<GitHubContributor, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<GitHubContributor, ?>>();

		attributeGetterFunctions.put(
			"gitHubContributorId",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getGitHubContributorId();
				}

			});
		attributeSetterBiConsumers.put(
			"gitHubContributorId",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object gitHubContributorIdObject) {

					gitHubContributor.setGitHubContributorId(
						(Long)gitHubContributorIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object companyIdObject) {

					gitHubContributor.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor, Object userIdObject) {

					gitHubContributor.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object userNameObject) {

					gitHubContributor.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object createDateObject) {

					gitHubContributor.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object modifiedDateObject) {

					gitHubContributor.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"gitHubRepositoryId",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getGitHubRepositoryId();
				}

			});
		attributeSetterBiConsumers.put(
			"gitHubRepositoryId",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object gitHubRepositoryIdObject) {

					gitHubContributor.setGitHubRepositoryId(
						(Long)gitHubRepositoryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor, Object nameObject) {

					gitHubContributor.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"avatarURL",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getAvatarURL();
				}

			});
		attributeSetterBiConsumers.put(
			"avatarURL",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object avatarURLObject) {

					gitHubContributor.setAvatarURL((String)avatarURLObject);
				}

			});
		attributeGetterFunctions.put(
			"contributions",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getContributions();
				}

			});
		attributeSetterBiConsumers.put(
			"contributions",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object contributionsObject) {

					gitHubContributor.setContributions(
						(Integer)contributionsObject);
				}

			});
		attributeGetterFunctions.put(
			"profileURL",
			new Function<GitHubContributor, Object>() {

				@Override
				public Object apply(GitHubContributor gitHubContributor) {
					return gitHubContributor.getProfileURL();
				}

			});
		attributeSetterBiConsumers.put(
			"profileURL",
			new BiConsumer<GitHubContributor, Object>() {

				@Override
				public void accept(
					GitHubContributor gitHubContributor,
					Object profileURLObject) {

					gitHubContributor.setProfileURL((String)profileURLObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getGitHubContributorId() {
		return _gitHubContributorId;
	}

	@Override
	public void setGitHubContributorId(long gitHubContributorId) {
		_gitHubContributorId = gitHubContributorId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getGitHubRepositoryId() {
		return _gitHubRepositoryId;
	}

	@Override
	public void setGitHubRepositoryId(long gitHubRepositoryId) {
		_columnBitmask |= GITHUBREPOSITORYID_COLUMN_BITMASK;

		if (!_setOriginalGitHubRepositoryId) {
			_setOriginalGitHubRepositoryId = true;

			_originalGitHubRepositoryId = _gitHubRepositoryId;
		}

		_gitHubRepositoryId = gitHubRepositoryId;
	}

	public long getOriginalGitHubRepositoryId() {
		return _originalGitHubRepositoryId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getAvatarURL() {
		if (_avatarURL == null) {
			return "";
		}
		else {
			return _avatarURL;
		}
	}

	@Override
	public void setAvatarURL(String avatarURL) {
		_avatarURL = avatarURL;
	}

	@Override
	public int getContributions() {
		return _contributions;
	}

	@Override
	public void setContributions(int contributions) {
		_contributions = contributions;
	}

	@Override
	public String getProfileURL() {
		if (_profileURL == null) {
			return "";
		}
		else {
			return _profileURL;
		}
	}

	@Override
	public void setProfileURL(String profileURL) {
		_profileURL = profileURL;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GitHubContributor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GitHubContributor toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GitHubContributor>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GitHubContributorImpl gitHubContributorImpl =
			new GitHubContributorImpl();

		gitHubContributorImpl.setGitHubContributorId(getGitHubContributorId());
		gitHubContributorImpl.setCompanyId(getCompanyId());
		gitHubContributorImpl.setUserId(getUserId());
		gitHubContributorImpl.setUserName(getUserName());
		gitHubContributorImpl.setCreateDate(getCreateDate());
		gitHubContributorImpl.setModifiedDate(getModifiedDate());
		gitHubContributorImpl.setGitHubRepositoryId(getGitHubRepositoryId());
		gitHubContributorImpl.setName(getName());
		gitHubContributorImpl.setAvatarURL(getAvatarURL());
		gitHubContributorImpl.setContributions(getContributions());
		gitHubContributorImpl.setProfileURL(getProfileURL());

		gitHubContributorImpl.resetOriginalValues();

		return gitHubContributorImpl;
	}

	@Override
	public int compareTo(GitHubContributor gitHubContributor) {
		int value = 0;

		if (getContributions() < gitHubContributor.getContributions()) {
			value = -1;
		}
		else if (getContributions() > gitHubContributor.getContributions()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GitHubContributor)) {
			return false;
		}

		GitHubContributor gitHubContributor = (GitHubContributor)object;

		long primaryKey = gitHubContributor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
		_originalGitHubRepositoryId = _gitHubRepositoryId;

		_setOriginalGitHubRepositoryId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GitHubContributor> toCacheModel() {
		GitHubContributorCacheModel gitHubContributorCacheModel =
			new GitHubContributorCacheModel();

		gitHubContributorCacheModel.gitHubContributorId =
			getGitHubContributorId();

		gitHubContributorCacheModel.companyId = getCompanyId();

		gitHubContributorCacheModel.userId = getUserId();

		gitHubContributorCacheModel.userName = getUserName();

		String userName = gitHubContributorCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			gitHubContributorCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			gitHubContributorCacheModel.createDate = createDate.getTime();
		}
		else {
			gitHubContributorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			gitHubContributorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			gitHubContributorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		gitHubContributorCacheModel.gitHubRepositoryId =
			getGitHubRepositoryId();

		gitHubContributorCacheModel.name = getName();

		String name = gitHubContributorCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			gitHubContributorCacheModel.name = null;
		}

		gitHubContributorCacheModel.avatarURL = getAvatarURL();

		String avatarURL = gitHubContributorCacheModel.avatarURL;

		if ((avatarURL != null) && (avatarURL.length() == 0)) {
			gitHubContributorCacheModel.avatarURL = null;
		}

		gitHubContributorCacheModel.contributions = getContributions();

		gitHubContributorCacheModel.profileURL = getProfileURL();

		String profileURL = gitHubContributorCacheModel.profileURL;

		if ((profileURL != null) && (profileURL.length() == 0)) {
			gitHubContributorCacheModel.profileURL = null;
		}

		return gitHubContributorCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GitHubContributor, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GitHubContributor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GitHubContributor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GitHubContributor)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GitHubContributor, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GitHubContributor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GitHubContributor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GitHubContributor)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GitHubContributor>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _gitHubContributorId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _gitHubRepositoryId;
	private long _originalGitHubRepositoryId;
	private boolean _setOriginalGitHubRepositoryId;
	private String _name;
	private String _avatarURL;
	private int _contributions;
	private String _profileURL;
	private long _columnBitmask;
	private GitHubContributor _escapedModel;

}