javascript.single.page.application.enabled=false

terms.of.use.required=false

locale.prepend.friendly.url.style=0

session.timeout.redirect.on.expire=true

dl.file.max.size=20971520

counter.increment.com.liferay.watson.model.WatsonIncident=1