javascript.single.page.application.enabled=false

locale.prepend.friendly.url.style=0

dl.file.max.size=20971520

counter.increment.com.liferay.watson.model.WatsonIncident=1

session.timeout.redirect.on.expire=true