release.info.build.number=103

upgrade.processes=\
    com.liferay.watson.hook.upgrade.UpgradeProcess_1_0_0,\
    com.liferay.watson.hook.upgrade.UpgradeProcess_1_0_1,\
    com.liferay.watson.hook.upgrade.UpgradeProcess_1_0_2,\
    com.liferay.watson.hook.upgrade.UpgradeProcess_1_0_3