include-and-override=portlet-ext.properties

osb.qa.user[kb.qa.content.creator@liferay.com.broken][first-name]=QATest
osb.qa.user[kb.qa.content.creator@liferay.com.broken][last-name]=Content
osb.qa.user[kb.qa.content.creator@liferay.com.broken][password]=test
osb.qa.user[kb.qa.content.creator@liferay.com.broken][role-ids]=10168,122571
osb.qa.user[kb.qa.content.creator@liferay.com.broken][screen-name]=kb-qa-content-creator
osb.qa.user[kb.qa.content.creator@liferay.com.broken][site-id]=10738
osb.qa.user[kb.qa.content.creator@liferay.com.broken][user-group]=80690
osb.qa.user[kb.qa.content.creator@liferay.com.broken][uuid]=c943b5d2-7bf0-11e8-adc0-fa7ae01bbebc

osb.qa.user[kb.qa.trial@test.com.broken][first-name]=QATest
osb.qa.user[kb.qa.trial@test.com.broken][last-name]=Trial
osb.qa.user[kb.qa.trial@test.com.broken][password]=test
osb.qa.user[kb.qa.trial@test.com.broken][role-ids]=10168
osb.qa.user[kb.qa.trial@test.com.broken][screen-name]=kb-qa-trial
osb.qa.user[kb.qa.trial@test.com.broken][site-id]=10738
osb.qa.user[kb.qa.trial@test.com.broken][user-group]=214315
osb.qa.user[kb.qa.trial@test.com.broken][uuid]=cda5225a-7bf0-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.admin@liferay.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.admin@liferay.com.broken][last-name]=Admin
osb.qa.user[lesa.qa.admin@liferay.com.broken][password]=test
osb.qa.user[lesa.qa.admin@liferay.com.broken][role-ids]=10164,10168
osb.qa.user[lesa.qa.admin@liferay.com.broken][screen-name]=lesa-qa-admin
osb.qa.user[lesa.qa.admin@liferay.com.broken][site-id]=10738
osb.qa.user[lesa.qa.admin@liferay.com.broken][user-group]=80690
osb.qa.user[lesa.qa.admin@liferay.com.broken][uuid]=1c8d14ce-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.cse.1@liferay.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][last-name]=CSE1
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][password]=test
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][role-ids]=10168
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][screen-name]=lesa-qa-cse-1
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][site-id]=10738
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][user-group]=80690
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][uuid]=3c8d1b54-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.customer@test.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.customer@test.com.broken][last-name]=Customer
osb.qa.user[lesa.qa.customer@test.com.broken][password]=test
osb.qa.user[lesa.qa.customer@test.com.broken][role-ids]=10168
osb.qa.user[lesa.qa.customer@test.com.broken][screen-name]=lesa-qa-customer
osb.qa.user[lesa.qa.customer@test.com.broken][site-id]=10738
osb.qa.user[lesa.qa.customer@test.com.broken][user-group]=84013
osb.qa.user[lesa.qa.customer@test.com.broken][uuid]=5c8d1da2-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.partner@test.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.partner@test.com.broken][last-name]=Partner
osb.qa.user[lesa.qa.partner@test.com.broken][password]=test
osb.qa.user[lesa.qa.partner@test.com.broken][role-ids]=10168
osb.qa.user[lesa.qa.partner@test.com.broken][screen-name]=lesa-qa-partner
osb.qa.user[lesa.qa.partner@test.com.broken][site-id]=10738
osb.qa.user[lesa.qa.partner@test.com.broken][user-group]=84039
osb.qa.user[lesa.qa.partner@test.com.broken][uuid]=8c8d20ea-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user.email.addresses=\
    kb.qa.content.creator@liferay.com.broken,\
    kb.qa.trial@test.com.broken,\
    lesa.qa.admin@liferay.com.broken,\
    lesa.qa.cse.1@liferay.com.broken,\
    lesa.qa.customer@test.com.broken,\
    lesa.qa.partner@test.com.broken