/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WatsonIncidentRelAudit service. Represents a row in the &quot;WatsonIncidentRelAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.watson.model.impl.WatsonIncidentRelAuditModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.watson.model.impl.WatsonIncidentRelAuditImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonIncidentRelAudit
 * @see com.liferay.watson.model.impl.WatsonIncidentRelAuditImpl
 * @see com.liferay.watson.model.impl.WatsonIncidentRelAuditModelImpl
 * @generated
 */
@ProviderType
public interface WatsonIncidentRelAuditModel extends BaseModel<WatsonIncidentRelAudit>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a watson incident rel audit model instance should use the {@link WatsonIncidentRelAudit} interface instead.
	 */

	/**
	 * Returns the primary key of this watson incident rel audit.
	 *
	 * @return the primary key of this watson incident rel audit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this watson incident rel audit.
	 *
	 * @param primaryKey the primary key of this watson incident rel audit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the watson incident rel audit ID of this watson incident rel audit.
	 *
	 * @return the watson incident rel audit ID of this watson incident rel audit
	 */
	public long getWatsonIncidentRelAuditId();

	/**
	 * Sets the watson incident rel audit ID of this watson incident rel audit.
	 *
	 * @param watsonIncidentRelAuditId the watson incident rel audit ID of this watson incident rel audit
	 */
	public void setWatsonIncidentRelAuditId(long watsonIncidentRelAuditId);

	/**
	 * Returns the group ID of this watson incident rel audit.
	 *
	 * @return the group ID of this watson incident rel audit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this watson incident rel audit.
	 *
	 * @param groupId the group ID of this watson incident rel audit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this watson incident rel audit.
	 *
	 * @return the company ID of this watson incident rel audit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this watson incident rel audit.
	 *
	 * @param companyId the company ID of this watson incident rel audit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this watson incident rel audit.
	 *
	 * @return the user ID of this watson incident rel audit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this watson incident rel audit.
	 *
	 * @param userId the user ID of this watson incident rel audit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this watson incident rel audit.
	 *
	 * @return the user uuid of this watson incident rel audit
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this watson incident rel audit.
	 *
	 * @param userUuid the user uuid of this watson incident rel audit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this watson incident rel audit.
	 *
	 * @return the user name of this watson incident rel audit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this watson incident rel audit.
	 *
	 * @param userName the user name of this watson incident rel audit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this watson incident rel audit.
	 *
	 * @return the create date of this watson incident rel audit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this watson incident rel audit.
	 *
	 * @param createDate the create date of this watson incident rel audit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this watson incident rel audit.
	 *
	 * @return the modified date of this watson incident rel audit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this watson incident rel audit.
	 *
	 * @param modifiedDate the modified date of this watson incident rel audit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the watson incident id1 of this watson incident rel audit.
	 *
	 * @return the watson incident id1 of this watson incident rel audit
	 */
	public long getWatsonIncidentId1();

	/**
	 * Sets the watson incident id1 of this watson incident rel audit.
	 *
	 * @param watsonIncidentId1 the watson incident id1 of this watson incident rel audit
	 */
	public void setWatsonIncidentId1(long watsonIncidentId1);

	/**
	 * Returns the watson incident id2 of this watson incident rel audit.
	 *
	 * @return the watson incident id2 of this watson incident rel audit
	 */
	public long getWatsonIncidentId2();

	/**
	 * Sets the watson incident id2 of this watson incident rel audit.
	 *
	 * @param watsonIncidentId2 the watson incident id2 of this watson incident rel audit
	 */
	public void setWatsonIncidentId2(long watsonIncidentId2);

	/**
	 * Returns the watson incident rel ID of this watson incident rel audit.
	 *
	 * @return the watson incident rel ID of this watson incident rel audit
	 */
	public long getWatsonIncidentRelId();

	/**
	 * Sets the watson incident rel ID of this watson incident rel audit.
	 *
	 * @param watsonIncidentRelId the watson incident rel ID of this watson incident rel audit
	 */
	public void setWatsonIncidentRelId(long watsonIncidentRelId);

	/**
	 * Returns the type of this watson incident rel audit.
	 *
	 * @return the type of this watson incident rel audit
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this watson incident rel audit.
	 *
	 * @param type the type of this watson incident rel audit
	 */
	public void setType(String type);

	/**
	 * Returns the status of this watson incident rel audit.
	 *
	 * @return the status of this watson incident rel audit
	 */
	public int getStatus();

	/**
	 * Sets the status of this watson incident rel audit.
	 *
	 * @param status the status of this watson incident rel audit
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WatsonIncidentRelAudit watsonIncidentRelAudit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WatsonIncidentRelAudit> toCacheModel();

	@Override
	public WatsonIncidentRelAudit toEscapedModel();

	@Override
	public WatsonIncidentRelAudit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}