/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the WatsonReportAudit service. Represents a row in the &quot;WatsonReportAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.watson.model.impl.WatsonReportAuditModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.watson.model.impl.WatsonReportAuditImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonReportAudit
 * @see com.liferay.watson.model.impl.WatsonReportAuditImpl
 * @see com.liferay.watson.model.impl.WatsonReportAuditModelImpl
 * @generated
 */
@ProviderType
public interface WatsonReportAuditModel extends BaseModel<WatsonReportAudit>,
	GroupedModel, LocalizedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a watson report audit model instance should use the {@link WatsonReportAudit} interface instead.
	 */

	/**
	 * Returns the primary key of this watson report audit.
	 *
	 * @return the primary key of this watson report audit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this watson report audit.
	 *
	 * @param primaryKey the primary key of this watson report audit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the watson report audit ID of this watson report audit.
	 *
	 * @return the watson report audit ID of this watson report audit
	 */
	public long getWatsonReportAuditId();

	/**
	 * Sets the watson report audit ID of this watson report audit.
	 *
	 * @param watsonReportAuditId the watson report audit ID of this watson report audit
	 */
	public void setWatsonReportAuditId(long watsonReportAuditId);

	/**
	 * Returns the group ID of this watson report audit.
	 *
	 * @return the group ID of this watson report audit
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this watson report audit.
	 *
	 * @param groupId the group ID of this watson report audit
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this watson report audit.
	 *
	 * @return the company ID of this watson report audit
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this watson report audit.
	 *
	 * @param companyId the company ID of this watson report audit
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this watson report audit.
	 *
	 * @return the user ID of this watson report audit
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this watson report audit.
	 *
	 * @param userId the user ID of this watson report audit
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this watson report audit.
	 *
	 * @return the user uuid of this watson report audit
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this watson report audit.
	 *
	 * @param userUuid the user uuid of this watson report audit
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this watson report audit.
	 *
	 * @return the user name of this watson report audit
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this watson report audit.
	 *
	 * @param userName the user name of this watson report audit
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this watson report audit.
	 *
	 * @return the create date of this watson report audit
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this watson report audit.
	 *
	 * @param createDate the create date of this watson report audit
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this watson report audit.
	 *
	 * @return the modified date of this watson report audit
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this watson report audit.
	 *
	 * @param modifiedDate the modified date of this watson report audit
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the original watson report ID of this watson report audit.
	 *
	 * @return the original watson report ID of this watson report audit
	 */
	public long getOriginalWatsonReportId();

	/**
	 * Sets the original watson report ID of this watson report audit.
	 *
	 * @param originalWatsonReportId the original watson report ID of this watson report audit
	 */
	public void setOriginalWatsonReportId(long originalWatsonReportId);

	/**
	 * Returns the type watson list type ID of this watson report audit.
	 *
	 * @return the type watson list type ID of this watson report audit
	 */
	public long getTypeWatsonListTypeId();

	/**
	 * Sets the type watson list type ID of this watson report audit.
	 *
	 * @param typeWatsonListTypeId the type watson list type ID of this watson report audit
	 */
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId);

	/**
	 * Returns the watson child ID of this watson report audit.
	 *
	 * @return the watson child ID of this watson report audit
	 */
	public long getWatsonChildId();

	/**
	 * Sets the watson child ID of this watson report audit.
	 *
	 * @param watsonChildId the watson child ID of this watson report audit
	 */
	public void setWatsonChildId(long watsonChildId);

	/**
	 * Returns the watson report ID of this watson report audit.
	 *
	 * @return the watson report ID of this watson report audit
	 */
	public long getWatsonReportId();

	/**
	 * Sets the watson report ID of this watson report audit.
	 *
	 * @param watsonReportId the watson report ID of this watson report audit
	 */
	public void setWatsonReportId(long watsonReportId);

	/**
	 * Returns the name of this watson report audit.
	 *
	 * @return the name of this watson report audit
	 */
	public String getName();

	/**
	 * Returns the localized name of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this watson report audit
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this watson report audit. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this watson report audit
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this watson report audit
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this watson report audit.
	 *
	 * @return the locales and localized names of this watson report audit
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this watson report audit.
	 *
	 * @param name the name of this watson report audit
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this watson report audit in the language.
	 *
	 * @param name the localized name of this watson report audit
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this watson report audit in the language, and sets the default locale.
	 *
	 * @param name the localized name of this watson report audit
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this watson report audit from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this watson report audit
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this watson report audit from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this watson report audit
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the description of this watson report audit.
	 *
	 * @return the description of this watson report audit
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this watson report audit
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this watson report audit. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this watson report audit
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this watson report audit
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this watson report audit.
	 *
	 * @return the locales and localized descriptions of this watson report audit
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this watson report audit.
	 *
	 * @param description the description of this watson report audit
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this watson report audit in the language.
	 *
	 * @param description the localized description of this watson report audit
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this watson report audit in the language, and sets the default locale.
	 *
	 * @param description the localized description of this watson report audit
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this watson report audit from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this watson report audit
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this watson report audit from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this watson report audit
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the full report of this watson report audit.
	 *
	 * @return the full report of this watson report audit
	 */
	public String getFullReport();

	/**
	 * Returns the localized full report of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized full report of this watson report audit
	 */
	@AutoEscape
	public String getFullReport(Locale locale);

	/**
	 * Returns the localized full report of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized full report of this watson report audit. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getFullReport(Locale locale, boolean useDefault);

	/**
	 * Returns the localized full report of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized full report of this watson report audit
	 */
	@AutoEscape
	public String getFullReport(String languageId);

	/**
	 * Returns the localized full report of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized full report of this watson report audit
	 */
	@AutoEscape
	public String getFullReport(String languageId, boolean useDefault);

	@AutoEscape
	public String getFullReportCurrentLanguageId();

	@AutoEscape
	public String getFullReportCurrentValue();

	/**
	 * Returns a map of the locales and localized full reports of this watson report audit.
	 *
	 * @return the locales and localized full reports of this watson report audit
	 */
	public Map<Locale, String> getFullReportMap();

	/**
	 * Sets the full report of this watson report audit.
	 *
	 * @param fullReport the full report of this watson report audit
	 */
	public void setFullReport(String fullReport);

	/**
	 * Sets the localized full report of this watson report audit in the language.
	 *
	 * @param fullReport the localized full report of this watson report audit
	 * @param locale the locale of the language
	 */
	public void setFullReport(String fullReport, Locale locale);

	/**
	 * Sets the localized full report of this watson report audit in the language, and sets the default locale.
	 *
	 * @param fullReport the localized full report of this watson report audit
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setFullReport(String fullReport, Locale locale,
		Locale defaultLocale);

	public void setFullReportCurrentLanguageId(String languageId);

	/**
	 * Sets the localized full reports of this watson report audit from the map of locales and localized full reports.
	 *
	 * @param fullReportMap the locales and localized full reports of this watson report audit
	 */
	public void setFullReportMap(Map<Locale, String> fullReportMap);

	/**
	 * Sets the localized full reports of this watson report audit from the map of locales and localized full reports, and sets the default locale.
	 *
	 * @param fullReportMap the locales and localized full reports of this watson report audit
	 * @param defaultLocale the default locale
	 */
	public void setFullReportMap(Map<Locale, String> fullReportMap,
		Locale defaultLocale);

	/**
	 * Returns the image payload of this watson report audit.
	 *
	 * @return the image payload of this watson report audit
	 */
	@AutoEscape
	public String getImagePayload();

	/**
	 * Sets the image payload of this watson report audit.
	 *
	 * @param imagePayload the image payload of this watson report audit
	 */
	public void setImagePayload(String imagePayload);

	/**
	 * Returns the time spent of this watson report audit.
	 *
	 * @return the time spent of this watson report audit
	 */
	@AutoEscape
	public String getTimeSpent();

	/**
	 * Sets the time spent of this watson report audit.
	 *
	 * @param timeSpent the time spent of this watson report audit
	 */
	public void setTimeSpent(String timeSpent);

	/**
	 * Returns the reported user of this watson report audit.
	 *
	 * @return the reported user of this watson report audit
	 */
	public String getReportedUser();

	/**
	 * Returns the localized reported user of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized reported user of this watson report audit
	 */
	@AutoEscape
	public String getReportedUser(Locale locale);

	/**
	 * Returns the localized reported user of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized reported user of this watson report audit. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getReportedUser(Locale locale, boolean useDefault);

	/**
	 * Returns the localized reported user of this watson report audit in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized reported user of this watson report audit
	 */
	@AutoEscape
	public String getReportedUser(String languageId);

	/**
	 * Returns the localized reported user of this watson report audit in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized reported user of this watson report audit
	 */
	@AutoEscape
	public String getReportedUser(String languageId, boolean useDefault);

	@AutoEscape
	public String getReportedUserCurrentLanguageId();

	@AutoEscape
	public String getReportedUserCurrentValue();

	/**
	 * Returns a map of the locales and localized reported users of this watson report audit.
	 *
	 * @return the locales and localized reported users of this watson report audit
	 */
	public Map<Locale, String> getReportedUserMap();

	/**
	 * Sets the reported user of this watson report audit.
	 *
	 * @param reportedUser the reported user of this watson report audit
	 */
	public void setReportedUser(String reportedUser);

	/**
	 * Sets the localized reported user of this watson report audit in the language.
	 *
	 * @param reportedUser the localized reported user of this watson report audit
	 * @param locale the locale of the language
	 */
	public void setReportedUser(String reportedUser, Locale locale);

	/**
	 * Sets the localized reported user of this watson report audit in the language, and sets the default locale.
	 *
	 * @param reportedUser the localized reported user of this watson report audit
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setReportedUser(String reportedUser, Locale locale,
		Locale defaultLocale);

	public void setReportedUserCurrentLanguageId(String languageId);

	/**
	 * Sets the localized reported users of this watson report audit from the map of locales and localized reported users.
	 *
	 * @param reportedUserMap the locales and localized reported users of this watson report audit
	 */
	public void setReportedUserMap(Map<Locale, String> reportedUserMap);

	/**
	 * Sets the localized reported users of this watson report audit from the map of locales and localized reported users, and sets the default locale.
	 *
	 * @param reportedUserMap the locales and localized reported users of this watson report audit
	 * @param defaultLocale the default locale
	 */
	public void setReportedUserMap(Map<Locale, String> reportedUserMap,
		Locale defaultLocale);

	/**
	 * Returns the report date of this watson report audit.
	 *
	 * @return the report date of this watson report audit
	 */
	public Date getReportDate();

	/**
	 * Sets the report date of this watson report audit.
	 *
	 * @param reportDate the report date of this watson report audit
	 */
	public void setReportDate(Date reportDate);

	/**
	 * Returns the key of this watson report audit.
	 *
	 * @return the key of this watson report audit
	 */
	public int getKey();

	/**
	 * Sets the key of this watson report audit.
	 *
	 * @param key the key of this watson report audit
	 */
	public void setKey(int key);

	/**
	 * Returns the status of this watson report audit.
	 *
	 * @return the status of this watson report audit
	 */
	public int getStatus();

	/**
	 * Sets the status of this watson report audit.
	 *
	 * @param status the status of this watson report audit
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(WatsonReportAudit watsonReportAudit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WatsonReportAudit> toCacheModel();

	@Override
	public WatsonReportAudit toEscapedModel();

	@Override
	public WatsonReportAudit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}