/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the WatsonResource service. Represents a row in the &quot;WatsonResource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.watson.model.impl.WatsonResourceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.watson.model.impl.WatsonResourceImpl</code>.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonResource
 * @generated
 */
@ProviderType
public interface WatsonResourceModel
	extends BaseModel<WatsonResource>, GroupedModel, LocalizedModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a watson resource model instance should use the {@link WatsonResource} interface instead.
	 */

	/**
	 * Returns the primary key of this watson resource.
	 *
	 * @return the primary key of this watson resource
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this watson resource.
	 *
	 * @param primaryKey the primary key of this watson resource
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the watson resource ID of this watson resource.
	 *
	 * @return the watson resource ID of this watson resource
	 */
	public long getWatsonResourceId();

	/**
	 * Sets the watson resource ID of this watson resource.
	 *
	 * @param watsonResourceId the watson resource ID of this watson resource
	 */
	public void setWatsonResourceId(long watsonResourceId);

	/**
	 * Returns the group ID of this watson resource.
	 *
	 * @return the group ID of this watson resource
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this watson resource.
	 *
	 * @param groupId the group ID of this watson resource
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this watson resource.
	 *
	 * @return the company ID of this watson resource
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this watson resource.
	 *
	 * @param companyId the company ID of this watson resource
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this watson resource.
	 *
	 * @return the user ID of this watson resource
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this watson resource.
	 *
	 * @param userId the user ID of this watson resource
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this watson resource.
	 *
	 * @return the user uuid of this watson resource
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this watson resource.
	 *
	 * @param userUuid the user uuid of this watson resource
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this watson resource.
	 *
	 * @return the user name of this watson resource
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this watson resource.
	 *
	 * @param userName the user name of this watson resource
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this watson resource.
	 *
	 * @return the create date of this watson resource
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this watson resource.
	 *
	 * @param createDate the create date of this watson resource
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this watson resource.
	 *
	 * @return the modified date of this watson resource
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this watson resource.
	 *
	 * @param modifiedDate the modified date of this watson resource
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the original watson resource ID of this watson resource.
	 *
	 * @return the original watson resource ID of this watson resource
	 */
	public long getOriginalWatsonResourceId();

	/**
	 * Sets the original watson resource ID of this watson resource.
	 *
	 * @param originalWatsonResourceId the original watson resource ID of this watson resource
	 */
	public void setOriginalWatsonResourceId(long originalWatsonResourceId);

	/**
	 * Returns the type watson list type ID of this watson resource.
	 *
	 * @return the type watson list type ID of this watson resource
	 */
	public long getTypeWatsonListTypeId();

	/**
	 * Sets the type watson list type ID of this watson resource.
	 *
	 * @param typeWatsonListTypeId the type watson list type ID of this watson resource
	 */
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId);

	/**
	 * Returns the watson incident ID of this watson resource.
	 *
	 * @return the watson incident ID of this watson resource
	 */
	public long getWatsonIncidentId();

	/**
	 * Sets the watson incident ID of this watson resource.
	 *
	 * @param watsonIncidentId the watson incident ID of this watson resource
	 */
	public void setWatsonIncidentId(long watsonIncidentId);

	/**
	 * Returns the name of this watson resource.
	 *
	 * @return the name of this watson resource
	 */
	public String getName();

	/**
	 * Returns the localized name of this watson resource in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this watson resource
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this watson resource in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this watson resource. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this watson resource in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this watson resource
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this watson resource in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this watson resource
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this watson resource.
	 *
	 * @return the locales and localized names of this watson resource
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this watson resource.
	 *
	 * @param name the name of this watson resource
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this watson resource in the language.
	 *
	 * @param name the localized name of this watson resource
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this watson resource in the language, and sets the default locale.
	 *
	 * @param name the localized name of this watson resource
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this watson resource from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this watson resource
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this watson resource from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this watson resource
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the description of this watson resource.
	 *
	 * @return the description of this watson resource
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this watson resource in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this watson resource
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this watson resource in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this watson resource. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this watson resource in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this watson resource
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this watson resource in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this watson resource
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this watson resource.
	 *
	 * @return the locales and localized descriptions of this watson resource
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this watson resource.
	 *
	 * @param description the description of this watson resource
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this watson resource in the language.
	 *
	 * @param description the localized description of this watson resource
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this watson resource in the language, and sets the default locale.
	 *
	 * @param description the localized description of this watson resource
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this watson resource from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this watson resource
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this watson resource from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this watson resource
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the image payload of this watson resource.
	 *
	 * @return the image payload of this watson resource
	 */
	@AutoEscape
	public String getImagePayload();

	/**
	 * Sets the image payload of this watson resource.
	 *
	 * @param imagePayload the image payload of this watson resource
	 */
	public void setImagePayload(String imagePayload);

	/**
	 * Returns the status of this watson resource.
	 *
	 * @return the status of this watson resource
	 */
	public int getStatus();

	/**
	 * Sets the status of this watson resource.
	 *
	 * @param status the status of this watson resource
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(WatsonResource watsonResource);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WatsonResource> toCacheModel();

	@Override
	public WatsonResource toEscapedModel();

	@Override
	public WatsonResource toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}