/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.watson.model.WatsonReportAudit;
import com.liferay.watson.model.WatsonReportAuditModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonReportAudit service. Represents a row in the &quot;WatsonReportAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonReportAuditModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonReportAuditImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonReportAuditImpl
 * @generated
 */
public class WatsonReportAuditModelImpl
	extends BaseModelImpl<WatsonReportAudit> implements WatsonReportAuditModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson report audit model instance should use the <code>WatsonReportAudit</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonReportAudit";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonReportAuditId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"originalWatsonReportId", Types.BIGINT},
		{"typeWatsonListTypeId", Types.BIGINT}, {"watsonChildId", Types.BIGINT},
		{"watsonReportId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"fullReport", Types.VARCHAR},
		{"imagePayload", Types.CLOB}, {"timeSpent", Types.VARCHAR},
		{"reportedUser", Types.VARCHAR}, {"reportDate", Types.TIMESTAMP},
		{"key_", Types.INTEGER}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonReportAuditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("originalWatsonReportId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonChildId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonReportId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fullReport", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imagePayload", Types.CLOB);
		TABLE_COLUMNS_MAP.put("timeSpent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reportedUser", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reportDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("key_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonReportAudit (watsonReportAuditId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,originalWatsonReportId LONG,typeWatsonListTypeId LONG,watsonChildId LONG,watsonReportId LONG,name STRING null,description STRING null,fullReport STRING null,imagePayload TEXT null,timeSpent VARCHAR(75) null,reportedUser STRING null,reportDate DATE null,key_ INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonReportAudit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonReportAudit.watsonReportAuditId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonReportAudit.watsonReportAuditId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonReportAudit"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonReportAudit"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonReportAudit"));

	public WatsonReportAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonReportAuditId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonReportAuditId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonReportAuditId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonReportAudit.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonReportAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonReportAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonReportAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonReportAudit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonReportAudit)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonReportAudit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonReportAudit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonReportAudit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonReportAudit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonReportAudit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonReportAudit>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonReportAudit.class.getClassLoader(), WatsonReportAudit.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonReportAudit> constructor =
				(Constructor<WatsonReportAudit>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonReportAudit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonReportAudit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonReportAudit, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<WatsonReportAudit, Object>>();
		Map<String, BiConsumer<WatsonReportAudit, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<WatsonReportAudit, ?>>();

		attributeGetterFunctions.put(
			"watsonReportAuditId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getWatsonReportAuditId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonReportAuditId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object watsonReportAuditIdObject) {

					watsonReportAudit.setWatsonReportAuditId(
						(Long)watsonReportAuditIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit, Object groupIdObject) {

					watsonReportAudit.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object companyIdObject) {

					watsonReportAudit.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit, Object userIdObject) {

					watsonReportAudit.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object userNameObject) {

					watsonReportAudit.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object createDateObject) {

					watsonReportAudit.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object modifiedDateObject) {

					watsonReportAudit.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"originalWatsonReportId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getOriginalWatsonReportId();
				}

			});
		attributeSetterBiConsumers.put(
			"originalWatsonReportId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object originalWatsonReportIdObject) {

					watsonReportAudit.setOriginalWatsonReportId(
						(Long)originalWatsonReportIdObject);
				}

			});
		attributeGetterFunctions.put(
			"typeWatsonListTypeId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"typeWatsonListTypeId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object typeWatsonListTypeIdObject) {

					watsonReportAudit.setTypeWatsonListTypeId(
						(Long)typeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonChildId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getWatsonChildId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonChildId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object watsonChildIdObject) {

					watsonReportAudit.setWatsonChildId(
						(Long)watsonChildIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonReportId",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getWatsonReportId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonReportId",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object watsonReportIdObject) {

					watsonReportAudit.setWatsonReportId(
						(Long)watsonReportIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit, Object nameObject) {

					watsonReportAudit.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object descriptionObject) {

					watsonReportAudit.setDescription((String)descriptionObject);
				}

			});
		attributeGetterFunctions.put(
			"fullReport",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getFullReport();
				}

			});
		attributeSetterBiConsumers.put(
			"fullReport",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object fullReportObject) {

					watsonReportAudit.setFullReport((String)fullReportObject);
				}

			});
		attributeGetterFunctions.put(
			"imagePayload",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getImagePayload();
				}

			});
		attributeSetterBiConsumers.put(
			"imagePayload",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object imagePayloadObject) {

					watsonReportAudit.setImagePayload(
						(String)imagePayloadObject);
				}

			});
		attributeGetterFunctions.put(
			"timeSpent",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getTimeSpent();
				}

			});
		attributeSetterBiConsumers.put(
			"timeSpent",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object timeSpentObject) {

					watsonReportAudit.setTimeSpent((String)timeSpentObject);
				}

			});
		attributeGetterFunctions.put(
			"reportedUser",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getReportedUser();
				}

			});
		attributeSetterBiConsumers.put(
			"reportedUser",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object reportedUserObject) {

					watsonReportAudit.setReportedUser(
						(String)reportedUserObject);
				}

			});
		attributeGetterFunctions.put(
			"reportDate",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getReportDate();
				}

			});
		attributeSetterBiConsumers.put(
			"reportDate",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit,
					Object reportDateObject) {

					watsonReportAudit.setReportDate((Date)reportDateObject);
				}

			});
		attributeGetterFunctions.put(
			"key",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getKey();
				}

			});
		attributeSetterBiConsumers.put(
			"key",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit, Object keyObject) {

					watsonReportAudit.setKey((Integer)keyObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonReportAudit, Object>() {

				@Override
				public Object apply(WatsonReportAudit watsonReportAudit) {
					return watsonReportAudit.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonReportAudit, Object>() {

				@Override
				public void accept(
					WatsonReportAudit watsonReportAudit, Object statusObject) {

					watsonReportAudit.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonReportAuditId() {
		return _watsonReportAuditId;
	}

	@Override
	public void setWatsonReportAuditId(long watsonReportAuditId) {
		_watsonReportAuditId = watsonReportAuditId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getOriginalWatsonReportId() {
		return _originalWatsonReportId;
	}

	@Override
	public void setOriginalWatsonReportId(long originalWatsonReportId) {
		_originalWatsonReportId = originalWatsonReportId;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getWatsonChildId() {
		return _watsonChildId;
	}

	@Override
	public void setWatsonChildId(long watsonChildId) {
		_watsonChildId = watsonChildId;
	}

	@Override
	public long getWatsonReportId() {
		return _watsonReportId;
	}

	@Override
	public void setWatsonReportId(long watsonReportId) {
		_watsonReportId = watsonReportId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getFullReport() {
		if (_fullReport == null) {
			return "";
		}
		else {
			return _fullReport;
		}
	}

	@Override
	public String getFullReport(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFullReport(languageId);
	}

	@Override
	public String getFullReport(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getFullReport(languageId, useDefault);
	}

	@Override
	public String getFullReport(String languageId) {
		return LocalizationUtil.getLocalization(getFullReport(), languageId);
	}

	@Override
	public String getFullReport(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getFullReport(), languageId, useDefault);
	}

	@Override
	public String getFullReportCurrentLanguageId() {
		return _fullReportCurrentLanguageId;
	}

	@JSON
	@Override
	public String getFullReportCurrentValue() {
		Locale locale = getLocale(_fullReportCurrentLanguageId);

		return getFullReport(locale);
	}

	@Override
	public Map<Locale, String> getFullReportMap() {
		return LocalizationUtil.getLocalizationMap(getFullReport());
	}

	@Override
	public void setFullReport(String fullReport) {
		_fullReport = fullReport;
	}

	@Override
	public void setFullReport(String fullReport, Locale locale) {
		setFullReport(fullReport, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setFullReport(
		String fullReport, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(fullReport)) {
			setFullReport(
				LocalizationUtil.updateLocalization(
					getFullReport(), "FullReport", fullReport, languageId,
					defaultLanguageId));
		}
		else {
			setFullReport(
				LocalizationUtil.removeLocalization(
					getFullReport(), "FullReport", languageId));
		}
	}

	@Override
	public void setFullReportCurrentLanguageId(String languageId) {
		_fullReportCurrentLanguageId = languageId;
	}

	@Override
	public void setFullReportMap(Map<Locale, String> fullReportMap) {
		setFullReportMap(fullReportMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setFullReportMap(
		Map<Locale, String> fullReportMap, Locale defaultLocale) {

		if (fullReportMap == null) {
			return;
		}

		setFullReport(
			LocalizationUtil.updateLocalization(
				fullReportMap, getFullReport(), "FullReport",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getImagePayload() {
		if (_imagePayload == null) {
			return "";
		}
		else {
			return _imagePayload;
		}
	}

	@Override
	public void setImagePayload(String imagePayload) {
		_imagePayload = imagePayload;
	}

	@Override
	public String getTimeSpent() {
		if (_timeSpent == null) {
			return "";
		}
		else {
			return _timeSpent;
		}
	}

	@Override
	public void setTimeSpent(String timeSpent) {
		_timeSpent = timeSpent;
	}

	@Override
	public String getReportedUser() {
		if (_reportedUser == null) {
			return "";
		}
		else {
			return _reportedUser;
		}
	}

	@Override
	public String getReportedUser(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getReportedUser(languageId);
	}

	@Override
	public String getReportedUser(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getReportedUser(languageId, useDefault);
	}

	@Override
	public String getReportedUser(String languageId) {
		return LocalizationUtil.getLocalization(getReportedUser(), languageId);
	}

	@Override
	public String getReportedUser(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getReportedUser(), languageId, useDefault);
	}

	@Override
	public String getReportedUserCurrentLanguageId() {
		return _reportedUserCurrentLanguageId;
	}

	@JSON
	@Override
	public String getReportedUserCurrentValue() {
		Locale locale = getLocale(_reportedUserCurrentLanguageId);

		return getReportedUser(locale);
	}

	@Override
	public Map<Locale, String> getReportedUserMap() {
		return LocalizationUtil.getLocalizationMap(getReportedUser());
	}

	@Override
	public void setReportedUser(String reportedUser) {
		_reportedUser = reportedUser;
	}

	@Override
	public void setReportedUser(String reportedUser, Locale locale) {
		setReportedUser(reportedUser, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setReportedUser(
		String reportedUser, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(reportedUser)) {
			setReportedUser(
				LocalizationUtil.updateLocalization(
					getReportedUser(), "ReportedUser", reportedUser, languageId,
					defaultLanguageId));
		}
		else {
			setReportedUser(
				LocalizationUtil.removeLocalization(
					getReportedUser(), "ReportedUser", languageId));
		}
	}

	@Override
	public void setReportedUserCurrentLanguageId(String languageId) {
		_reportedUserCurrentLanguageId = languageId;
	}

	@Override
	public void setReportedUserMap(Map<Locale, String> reportedUserMap) {
		setReportedUserMap(reportedUserMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setReportedUserMap(
		Map<Locale, String> reportedUserMap, Locale defaultLocale) {

		if (reportedUserMap == null) {
			return;
		}

		setReportedUser(
			LocalizationUtil.updateLocalization(
				reportedUserMap, getReportedUser(), "ReportedUser",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Date getReportDate() {
		return _reportDate;
	}

	@Override
	public void setReportDate(Date reportDate) {
		_reportDate = reportDate;
	}

	@Override
	public int getKey() {
		return _key;
	}

	@Override
	public void setKey(int key) {
		_key = key;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonReportAudit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> fullReportMap = getFullReportMap();

		for (Map.Entry<Locale, String> entry : fullReportMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> reportedUserMap = getReportedUserMap();

		for (Map.Entry<Locale, String> entry : reportedUserMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			WatsonReportAudit.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}

		String fullReport = getFullReport(defaultLocale);

		if (Validator.isNull(fullReport)) {
			setFullReport(getFullReport(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setFullReport(
				getFullReport(defaultLocale), defaultLocale, defaultLocale);
		}

		String reportedUser = getReportedUser(defaultLocale);

		if (Validator.isNull(reportedUser)) {
			setReportedUser(
				getReportedUser(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setReportedUser(
				getReportedUser(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WatsonReportAudit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonReportAudit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonReportAuditImpl watsonReportAuditImpl =
			new WatsonReportAuditImpl();

		watsonReportAuditImpl.setWatsonReportAuditId(getWatsonReportAuditId());
		watsonReportAuditImpl.setGroupId(getGroupId());
		watsonReportAuditImpl.setCompanyId(getCompanyId());
		watsonReportAuditImpl.setUserId(getUserId());
		watsonReportAuditImpl.setUserName(getUserName());
		watsonReportAuditImpl.setCreateDate(getCreateDate());
		watsonReportAuditImpl.setModifiedDate(getModifiedDate());
		watsonReportAuditImpl.setOriginalWatsonReportId(
			getOriginalWatsonReportId());
		watsonReportAuditImpl.setTypeWatsonListTypeId(
			getTypeWatsonListTypeId());
		watsonReportAuditImpl.setWatsonChildId(getWatsonChildId());
		watsonReportAuditImpl.setWatsonReportId(getWatsonReportId());
		watsonReportAuditImpl.setName(getName());
		watsonReportAuditImpl.setDescription(getDescription());
		watsonReportAuditImpl.setFullReport(getFullReport());
		watsonReportAuditImpl.setImagePayload(getImagePayload());
		watsonReportAuditImpl.setTimeSpent(getTimeSpent());
		watsonReportAuditImpl.setReportedUser(getReportedUser());
		watsonReportAuditImpl.setReportDate(getReportDate());
		watsonReportAuditImpl.setKey(getKey());
		watsonReportAuditImpl.setStatus(getStatus());

		watsonReportAuditImpl.resetOriginalValues();

		return watsonReportAuditImpl;
	}

	@Override
	public int compareTo(WatsonReportAudit watsonReportAudit) {
		long primaryKey = watsonReportAudit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonReportAudit)) {
			return false;
		}

		WatsonReportAudit watsonReportAudit = (WatsonReportAudit)object;

		long primaryKey = watsonReportAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonReportAudit> toCacheModel() {
		WatsonReportAuditCacheModel watsonReportAuditCacheModel =
			new WatsonReportAuditCacheModel();

		watsonReportAuditCacheModel.watsonReportAuditId =
			getWatsonReportAuditId();

		watsonReportAuditCacheModel.groupId = getGroupId();

		watsonReportAuditCacheModel.companyId = getCompanyId();

		watsonReportAuditCacheModel.userId = getUserId();

		watsonReportAuditCacheModel.userName = getUserName();

		String userName = watsonReportAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonReportAuditCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonReportAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonReportAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonReportAuditCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonReportAuditCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonReportAuditCacheModel.originalWatsonReportId =
			getOriginalWatsonReportId();

		watsonReportAuditCacheModel.typeWatsonListTypeId =
			getTypeWatsonListTypeId();

		watsonReportAuditCacheModel.watsonChildId = getWatsonChildId();

		watsonReportAuditCacheModel.watsonReportId = getWatsonReportId();

		watsonReportAuditCacheModel.name = getName();

		String name = watsonReportAuditCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			watsonReportAuditCacheModel.name = null;
		}

		watsonReportAuditCacheModel.description = getDescription();

		String description = watsonReportAuditCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			watsonReportAuditCacheModel.description = null;
		}

		watsonReportAuditCacheModel.fullReport = getFullReport();

		String fullReport = watsonReportAuditCacheModel.fullReport;

		if ((fullReport != null) && (fullReport.length() == 0)) {
			watsonReportAuditCacheModel.fullReport = null;
		}

		watsonReportAuditCacheModel.imagePayload = getImagePayload();

		String imagePayload = watsonReportAuditCacheModel.imagePayload;

		if ((imagePayload != null) && (imagePayload.length() == 0)) {
			watsonReportAuditCacheModel.imagePayload = null;
		}

		watsonReportAuditCacheModel.timeSpent = getTimeSpent();

		String timeSpent = watsonReportAuditCacheModel.timeSpent;

		if ((timeSpent != null) && (timeSpent.length() == 0)) {
			watsonReportAuditCacheModel.timeSpent = null;
		}

		watsonReportAuditCacheModel.reportedUser = getReportedUser();

		String reportedUser = watsonReportAuditCacheModel.reportedUser;

		if ((reportedUser != null) && (reportedUser.length() == 0)) {
			watsonReportAuditCacheModel.reportedUser = null;
		}

		Date reportDate = getReportDate();

		if (reportDate != null) {
			watsonReportAuditCacheModel.reportDate = reportDate.getTime();
		}
		else {
			watsonReportAuditCacheModel.reportDate = Long.MIN_VALUE;
		}

		watsonReportAuditCacheModel.key = getKey();

		watsonReportAuditCacheModel.status = getStatus();

		return watsonReportAuditCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonReportAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonReportAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonReportAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonReportAudit)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonReportAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonReportAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonReportAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonReportAudit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonReportAudit>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonReportAuditId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _originalWatsonReportId;
	private long _typeWatsonListTypeId;
	private long _watsonChildId;
	private long _watsonReportId;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _fullReport;
	private String _fullReportCurrentLanguageId;
	private String _imagePayload;
	private String _timeSpent;
	private String _reportedUser;
	private String _reportedUserCurrentLanguageId;
	private Date _reportDate;
	private int _key;
	private int _status;
	private WatsonReportAudit _escapedModel;

}