/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.watson.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import com.liferay.watson.model.WatsonPersonAudit;
import com.liferay.watson.model.WatsonPersonAuditModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the WatsonPersonAudit service. Represents a row in the &quot;WatsonPersonAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link WatsonPersonAuditModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonPersonAuditImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonPersonAuditImpl
 * @see WatsonPersonAudit
 * @see WatsonPersonAuditModel
 * @generated
 */
@ProviderType
public class WatsonPersonAuditModelImpl extends BaseModelImpl<WatsonPersonAudit>
	implements WatsonPersonAuditModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson person audit model instance should use the {@link WatsonPersonAudit} interface instead.
	 */
	public static final String TABLE_NAME = "WatsonPersonAudit";
	public static final Object[][] TABLE_COLUMNS = {
			{ "watsonPersonAuditId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "birthCountryId", Types.BIGINT },
			{ "citizenshipWatsonListTypeId", Types.BIGINT },
			{ "countryWatsonListTypeId", Types.BIGINT },
			{ "ethnicityWatsonListTypeId", Types.BIGINT },
			{ "eyesWatsonListTypeId", Types.BIGINT },
			{ "hairWatsonListTypeId", Types.BIGINT },
			{ "originalWatsonPersonId", Types.BIGINT },
			{ "sexWatsonListTypeId", Types.BIGINT },
			{ "typeWatsonListTypeId", Types.BIGINT },
			{ "watsonIncidentId", Types.BIGINT },
			{ "watsonPersonId", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "imagePayload", Types.CLOB },
			{ "birthDate", Types.TIMESTAMP },
			{ "dateAccepted", Types.TIMESTAMP },
			{ "dateRescued", Types.TIMESTAMP },
			{ "startAge", Types.VARCHAR },
			{ "endAge", Types.VARCHAR },
			{ "occupation", Types.VARCHAR },
			{ "height", Types.VARCHAR },
			{ "weight", Types.VARCHAR },
			{ "accepted", Types.BOOLEAN },
			{ "rescued", Types.BOOLEAN },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonPersonAuditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("birthCountryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("citizenshipWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("countryWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ethnicityWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("eyesWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hairWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("originalWatsonPersonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sexWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonIncidentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonPersonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imagePayload", Types.CLOB);
		TABLE_COLUMNS_MAP.put("birthDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dateAccepted", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dateRescued", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startAge", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("endAge", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("occupation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("height", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("weight", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("accepted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("rescued", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table WatsonPersonAudit (watsonPersonAuditId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,birthCountryId LONG,citizenshipWatsonListTypeId LONG,countryWatsonListTypeId LONG,ethnicityWatsonListTypeId LONG,eyesWatsonListTypeId LONG,hairWatsonListTypeId LONG,originalWatsonPersonId LONG,sexWatsonListTypeId LONG,typeWatsonListTypeId LONG,watsonIncidentId LONG,watsonPersonId LONG,description STRING null,imagePayload TEXT null,birthDate DATE null,dateAccepted DATE null,dateRescued DATE null,startAge VARCHAR(75) null,endAge VARCHAR(75) null,occupation STRING null,height VARCHAR(75) null,weight VARCHAR(75) null,accepted BOOLEAN,rescued BOOLEAN,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table WatsonPersonAudit";
	public static final String ORDER_BY_JPQL = " ORDER BY watsonPersonAudit.watsonPersonAuditId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY WatsonPersonAudit.watsonPersonAuditId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.watson.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonPersonAudit"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.watson.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonPersonAudit"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.watson.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.watson.model.WatsonPersonAudit"));

	public WatsonPersonAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonPersonAuditId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonPersonAuditId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonPersonAuditId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonPersonAudit.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonPersonAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("watsonPersonAuditId", getWatsonPersonAuditId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("birthCountryId", getBirthCountryId());
		attributes.put("citizenshipWatsonListTypeId",
			getCitizenshipWatsonListTypeId());
		attributes.put("countryWatsonListTypeId", getCountryWatsonListTypeId());
		attributes.put("ethnicityWatsonListTypeId",
			getEthnicityWatsonListTypeId());
		attributes.put("eyesWatsonListTypeId", getEyesWatsonListTypeId());
		attributes.put("hairWatsonListTypeId", getHairWatsonListTypeId());
		attributes.put("originalWatsonPersonId", getOriginalWatsonPersonId());
		attributes.put("sexWatsonListTypeId", getSexWatsonListTypeId());
		attributes.put("typeWatsonListTypeId", getTypeWatsonListTypeId());
		attributes.put("watsonIncidentId", getWatsonIncidentId());
		attributes.put("watsonPersonId", getWatsonPersonId());
		attributes.put("description", getDescription());
		attributes.put("imagePayload", getImagePayload());
		attributes.put("birthDate", getBirthDate());
		attributes.put("dateAccepted", getDateAccepted());
		attributes.put("dateRescued", getDateRescued());
		attributes.put("startAge", getStartAge());
		attributes.put("endAge", getEndAge());
		attributes.put("occupation", getOccupation());
		attributes.put("height", getHeight());
		attributes.put("weight", getWeight());
		attributes.put("accepted", isAccepted());
		attributes.put("rescued", isRescued());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long watsonPersonAuditId = (Long)attributes.get("watsonPersonAuditId");

		if (watsonPersonAuditId != null) {
			setWatsonPersonAuditId(watsonPersonAuditId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long birthCountryId = (Long)attributes.get("birthCountryId");

		if (birthCountryId != null) {
			setBirthCountryId(birthCountryId);
		}

		Long citizenshipWatsonListTypeId = (Long)attributes.get(
				"citizenshipWatsonListTypeId");

		if (citizenshipWatsonListTypeId != null) {
			setCitizenshipWatsonListTypeId(citizenshipWatsonListTypeId);
		}

		Long countryWatsonListTypeId = (Long)attributes.get(
				"countryWatsonListTypeId");

		if (countryWatsonListTypeId != null) {
			setCountryWatsonListTypeId(countryWatsonListTypeId);
		}

		Long ethnicityWatsonListTypeId = (Long)attributes.get(
				"ethnicityWatsonListTypeId");

		if (ethnicityWatsonListTypeId != null) {
			setEthnicityWatsonListTypeId(ethnicityWatsonListTypeId);
		}

		Long eyesWatsonListTypeId = (Long)attributes.get("eyesWatsonListTypeId");

		if (eyesWatsonListTypeId != null) {
			setEyesWatsonListTypeId(eyesWatsonListTypeId);
		}

		Long hairWatsonListTypeId = (Long)attributes.get("hairWatsonListTypeId");

		if (hairWatsonListTypeId != null) {
			setHairWatsonListTypeId(hairWatsonListTypeId);
		}

		Long originalWatsonPersonId = (Long)attributes.get(
				"originalWatsonPersonId");

		if (originalWatsonPersonId != null) {
			setOriginalWatsonPersonId(originalWatsonPersonId);
		}

		Long sexWatsonListTypeId = (Long)attributes.get("sexWatsonListTypeId");

		if (sexWatsonListTypeId != null) {
			setSexWatsonListTypeId(sexWatsonListTypeId);
		}

		Long typeWatsonListTypeId = (Long)attributes.get("typeWatsonListTypeId");

		if (typeWatsonListTypeId != null) {
			setTypeWatsonListTypeId(typeWatsonListTypeId);
		}

		Long watsonIncidentId = (Long)attributes.get("watsonIncidentId");

		if (watsonIncidentId != null) {
			setWatsonIncidentId(watsonIncidentId);
		}

		Long watsonPersonId = (Long)attributes.get("watsonPersonId");

		if (watsonPersonId != null) {
			setWatsonPersonId(watsonPersonId);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String imagePayload = (String)attributes.get("imagePayload");

		if (imagePayload != null) {
			setImagePayload(imagePayload);
		}

		Date birthDate = (Date)attributes.get("birthDate");

		if (birthDate != null) {
			setBirthDate(birthDate);
		}

		Date dateAccepted = (Date)attributes.get("dateAccepted");

		if (dateAccepted != null) {
			setDateAccepted(dateAccepted);
		}

		Date dateRescued = (Date)attributes.get("dateRescued");

		if (dateRescued != null) {
			setDateRescued(dateRescued);
		}

		String startAge = (String)attributes.get("startAge");

		if (startAge != null) {
			setStartAge(startAge);
		}

		String endAge = (String)attributes.get("endAge");

		if (endAge != null) {
			setEndAge(endAge);
		}

		String occupation = (String)attributes.get("occupation");

		if (occupation != null) {
			setOccupation(occupation);
		}

		String height = (String)attributes.get("height");

		if (height != null) {
			setHeight(height);
		}

		String weight = (String)attributes.get("weight");

		if (weight != null) {
			setWeight(weight);
		}

		Boolean accepted = (Boolean)attributes.get("accepted");

		if (accepted != null) {
			setAccepted(accepted);
		}

		Boolean rescued = (Boolean)attributes.get("rescued");

		if (rescued != null) {
			setRescued(rescued);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@Override
	public long getWatsonPersonAuditId() {
		return _watsonPersonAuditId;
	}

	@Override
	public void setWatsonPersonAuditId(long watsonPersonAuditId) {
		_watsonPersonAuditId = watsonPersonAuditId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getBirthCountryId() {
		return _birthCountryId;
	}

	@Override
	public void setBirthCountryId(long birthCountryId) {
		_birthCountryId = birthCountryId;
	}

	@Override
	public long getCitizenshipWatsonListTypeId() {
		return _citizenshipWatsonListTypeId;
	}

	@Override
	public void setCitizenshipWatsonListTypeId(long citizenshipWatsonListTypeId) {
		_citizenshipWatsonListTypeId = citizenshipWatsonListTypeId;
	}

	@Override
	public long getCountryWatsonListTypeId() {
		return _countryWatsonListTypeId;
	}

	@Override
	public void setCountryWatsonListTypeId(long countryWatsonListTypeId) {
		_countryWatsonListTypeId = countryWatsonListTypeId;
	}

	@Override
	public long getEthnicityWatsonListTypeId() {
		return _ethnicityWatsonListTypeId;
	}

	@Override
	public void setEthnicityWatsonListTypeId(long ethnicityWatsonListTypeId) {
		_ethnicityWatsonListTypeId = ethnicityWatsonListTypeId;
	}

	@Override
	public long getEyesWatsonListTypeId() {
		return _eyesWatsonListTypeId;
	}

	@Override
	public void setEyesWatsonListTypeId(long eyesWatsonListTypeId) {
		_eyesWatsonListTypeId = eyesWatsonListTypeId;
	}

	@Override
	public long getHairWatsonListTypeId() {
		return _hairWatsonListTypeId;
	}

	@Override
	public void setHairWatsonListTypeId(long hairWatsonListTypeId) {
		_hairWatsonListTypeId = hairWatsonListTypeId;
	}

	@Override
	public long getOriginalWatsonPersonId() {
		return _originalWatsonPersonId;
	}

	@Override
	public void setOriginalWatsonPersonId(long originalWatsonPersonId) {
		_originalWatsonPersonId = originalWatsonPersonId;
	}

	@Override
	public long getSexWatsonListTypeId() {
		return _sexWatsonListTypeId;
	}

	@Override
	public void setSexWatsonListTypeId(long sexWatsonListTypeId) {
		_sexWatsonListTypeId = sexWatsonListTypeId;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getWatsonIncidentId() {
		return _watsonIncidentId;
	}

	@Override
	public void setWatsonIncidentId(long watsonIncidentId) {
		_watsonIncidentId = watsonIncidentId;
	}

	@Override
	public long getWatsonPersonId() {
		return _watsonPersonId;
	}

	@Override
	public void setWatsonPersonId(long watsonPersonId) {
		_watsonPersonId = watsonPersonId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDescription(), languageId,
			useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(String description, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale) {
		if (descriptionMap == null) {
			return;
		}

		setDescription(LocalizationUtil.updateLocalization(descriptionMap,
				getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getImagePayload() {
		if (_imagePayload == null) {
			return "";
		}
		else {
			return _imagePayload;
		}
	}

	@Override
	public void setImagePayload(String imagePayload) {
		_imagePayload = imagePayload;
	}

	@Override
	public Date getBirthDate() {
		return _birthDate;
	}

	@Override
	public void setBirthDate(Date birthDate) {
		_birthDate = birthDate;
	}

	@Override
	public Date getDateAccepted() {
		return _dateAccepted;
	}

	@Override
	public void setDateAccepted(Date dateAccepted) {
		_dateAccepted = dateAccepted;
	}

	@Override
	public Date getDateRescued() {
		return _dateRescued;
	}

	@Override
	public void setDateRescued(Date dateRescued) {
		_dateRescued = dateRescued;
	}

	@Override
	public String getStartAge() {
		if (_startAge == null) {
			return "";
		}
		else {
			return _startAge;
		}
	}

	@Override
	public void setStartAge(String startAge) {
		_startAge = startAge;
	}

	@Override
	public String getEndAge() {
		if (_endAge == null) {
			return "";
		}
		else {
			return _endAge;
		}
	}

	@Override
	public void setEndAge(String endAge) {
		_endAge = endAge;
	}

	@Override
	public String getOccupation() {
		if (_occupation == null) {
			return "";
		}
		else {
			return _occupation;
		}
	}

	@Override
	public String getOccupation(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOccupation(languageId);
	}

	@Override
	public String getOccupation(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getOccupation(languageId, useDefault);
	}

	@Override
	public String getOccupation(String languageId) {
		return LocalizationUtil.getLocalization(getOccupation(), languageId);
	}

	@Override
	public String getOccupation(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getOccupation(), languageId,
			useDefault);
	}

	@Override
	public String getOccupationCurrentLanguageId() {
		return _occupationCurrentLanguageId;
	}

	@JSON
	@Override
	public String getOccupationCurrentValue() {
		Locale locale = getLocale(_occupationCurrentLanguageId);

		return getOccupation(locale);
	}

	@Override
	public Map<Locale, String> getOccupationMap() {
		return LocalizationUtil.getLocalizationMap(getOccupation());
	}

	@Override
	public void setOccupation(String occupation) {
		_occupation = occupation;
	}

	@Override
	public void setOccupation(String occupation, Locale locale) {
		setOccupation(occupation, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setOccupation(String occupation, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(occupation)) {
			setOccupation(LocalizationUtil.updateLocalization(getOccupation(),
					"Occupation", occupation, languageId, defaultLanguageId));
		}
		else {
			setOccupation(LocalizationUtil.removeLocalization(getOccupation(),
					"Occupation", languageId));
		}
	}

	@Override
	public void setOccupationCurrentLanguageId(String languageId) {
		_occupationCurrentLanguageId = languageId;
	}

	@Override
	public void setOccupationMap(Map<Locale, String> occupationMap) {
		setOccupationMap(occupationMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setOccupationMap(Map<Locale, String> occupationMap,
		Locale defaultLocale) {
		if (occupationMap == null) {
			return;
		}

		setOccupation(LocalizationUtil.updateLocalization(occupationMap,
				getOccupation(), "Occupation",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getHeight() {
		if (_height == null) {
			return "";
		}
		else {
			return _height;
		}
	}

	@Override
	public void setHeight(String height) {
		_height = height;
	}

	@Override
	public String getWeight() {
		if (_weight == null) {
			return "";
		}
		else {
			return _weight;
		}
	}

	@Override
	public void setWeight(String weight) {
		_weight = weight;
	}

	@Override
	public boolean getAccepted() {
		return _accepted;
	}

	@Override
	public boolean isAccepted() {
		return _accepted;
	}

	@Override
	public void setAccepted(boolean accepted) {
		_accepted = accepted;
	}

	@Override
	public boolean getRescued() {
		return _rescued;
	}

	@Override
	public boolean isRescued() {
		return _rescued;
	}

	@Override
	public void setRescued(boolean rescued) {
		_rescued = rescued;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			WatsonPersonAudit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> occupationMap = getOccupationMap();

		for (Map.Entry<Locale, String> entry : occupationMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDescription();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(WatsonPersonAudit.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(getDescription(defaultLocale), defaultLocale,
				defaultLocale);
		}

		String occupation = getOccupation(defaultLocale);

		if (Validator.isNull(occupation)) {
			setOccupation(getOccupation(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setOccupation(getOccupation(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public WatsonPersonAudit toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WatsonPersonAudit)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonPersonAuditImpl watsonPersonAuditImpl = new WatsonPersonAuditImpl();

		watsonPersonAuditImpl.setWatsonPersonAuditId(getWatsonPersonAuditId());
		watsonPersonAuditImpl.setGroupId(getGroupId());
		watsonPersonAuditImpl.setCompanyId(getCompanyId());
		watsonPersonAuditImpl.setUserId(getUserId());
		watsonPersonAuditImpl.setUserName(getUserName());
		watsonPersonAuditImpl.setCreateDate(getCreateDate());
		watsonPersonAuditImpl.setModifiedDate(getModifiedDate());
		watsonPersonAuditImpl.setBirthCountryId(getBirthCountryId());
		watsonPersonAuditImpl.setCitizenshipWatsonListTypeId(getCitizenshipWatsonListTypeId());
		watsonPersonAuditImpl.setCountryWatsonListTypeId(getCountryWatsonListTypeId());
		watsonPersonAuditImpl.setEthnicityWatsonListTypeId(getEthnicityWatsonListTypeId());
		watsonPersonAuditImpl.setEyesWatsonListTypeId(getEyesWatsonListTypeId());
		watsonPersonAuditImpl.setHairWatsonListTypeId(getHairWatsonListTypeId());
		watsonPersonAuditImpl.setOriginalWatsonPersonId(getOriginalWatsonPersonId());
		watsonPersonAuditImpl.setSexWatsonListTypeId(getSexWatsonListTypeId());
		watsonPersonAuditImpl.setTypeWatsonListTypeId(getTypeWatsonListTypeId());
		watsonPersonAuditImpl.setWatsonIncidentId(getWatsonIncidentId());
		watsonPersonAuditImpl.setWatsonPersonId(getWatsonPersonId());
		watsonPersonAuditImpl.setDescription(getDescription());
		watsonPersonAuditImpl.setImagePayload(getImagePayload());
		watsonPersonAuditImpl.setBirthDate(getBirthDate());
		watsonPersonAuditImpl.setDateAccepted(getDateAccepted());
		watsonPersonAuditImpl.setDateRescued(getDateRescued());
		watsonPersonAuditImpl.setStartAge(getStartAge());
		watsonPersonAuditImpl.setEndAge(getEndAge());
		watsonPersonAuditImpl.setOccupation(getOccupation());
		watsonPersonAuditImpl.setHeight(getHeight());
		watsonPersonAuditImpl.setWeight(getWeight());
		watsonPersonAuditImpl.setAccepted(isAccepted());
		watsonPersonAuditImpl.setRescued(isRescued());
		watsonPersonAuditImpl.setStatus(getStatus());

		watsonPersonAuditImpl.resetOriginalValues();

		return watsonPersonAuditImpl;
	}

	@Override
	public int compareTo(WatsonPersonAudit watsonPersonAudit) {
		long primaryKey = watsonPersonAudit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WatsonPersonAudit)) {
			return false;
		}

		WatsonPersonAudit watsonPersonAudit = (WatsonPersonAudit)obj;

		long primaryKey = watsonPersonAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		WatsonPersonAuditModelImpl watsonPersonAuditModelImpl = this;

		watsonPersonAuditModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonPersonAudit> toCacheModel() {
		WatsonPersonAuditCacheModel watsonPersonAuditCacheModel = new WatsonPersonAuditCacheModel();

		watsonPersonAuditCacheModel.watsonPersonAuditId = getWatsonPersonAuditId();

		watsonPersonAuditCacheModel.groupId = getGroupId();

		watsonPersonAuditCacheModel.companyId = getCompanyId();

		watsonPersonAuditCacheModel.userId = getUserId();

		watsonPersonAuditCacheModel.userName = getUserName();

		String userName = watsonPersonAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonPersonAuditCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonPersonAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonPersonAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonPersonAuditCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonPersonAuditCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonPersonAuditCacheModel.birthCountryId = getBirthCountryId();

		watsonPersonAuditCacheModel.citizenshipWatsonListTypeId = getCitizenshipWatsonListTypeId();

		watsonPersonAuditCacheModel.countryWatsonListTypeId = getCountryWatsonListTypeId();

		watsonPersonAuditCacheModel.ethnicityWatsonListTypeId = getEthnicityWatsonListTypeId();

		watsonPersonAuditCacheModel.eyesWatsonListTypeId = getEyesWatsonListTypeId();

		watsonPersonAuditCacheModel.hairWatsonListTypeId = getHairWatsonListTypeId();

		watsonPersonAuditCacheModel.originalWatsonPersonId = getOriginalWatsonPersonId();

		watsonPersonAuditCacheModel.sexWatsonListTypeId = getSexWatsonListTypeId();

		watsonPersonAuditCacheModel.typeWatsonListTypeId = getTypeWatsonListTypeId();

		watsonPersonAuditCacheModel.watsonIncidentId = getWatsonIncidentId();

		watsonPersonAuditCacheModel.watsonPersonId = getWatsonPersonId();

		watsonPersonAuditCacheModel.description = getDescription();

		String description = watsonPersonAuditCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			watsonPersonAuditCacheModel.description = null;
		}

		watsonPersonAuditCacheModel.imagePayload = getImagePayload();

		String imagePayload = watsonPersonAuditCacheModel.imagePayload;

		if ((imagePayload != null) && (imagePayload.length() == 0)) {
			watsonPersonAuditCacheModel.imagePayload = null;
		}

		Date birthDate = getBirthDate();

		if (birthDate != null) {
			watsonPersonAuditCacheModel.birthDate = birthDate.getTime();
		}
		else {
			watsonPersonAuditCacheModel.birthDate = Long.MIN_VALUE;
		}

		Date dateAccepted = getDateAccepted();

		if (dateAccepted != null) {
			watsonPersonAuditCacheModel.dateAccepted = dateAccepted.getTime();
		}
		else {
			watsonPersonAuditCacheModel.dateAccepted = Long.MIN_VALUE;
		}

		Date dateRescued = getDateRescued();

		if (dateRescued != null) {
			watsonPersonAuditCacheModel.dateRescued = dateRescued.getTime();
		}
		else {
			watsonPersonAuditCacheModel.dateRescued = Long.MIN_VALUE;
		}

		watsonPersonAuditCacheModel.startAge = getStartAge();

		String startAge = watsonPersonAuditCacheModel.startAge;

		if ((startAge != null) && (startAge.length() == 0)) {
			watsonPersonAuditCacheModel.startAge = null;
		}

		watsonPersonAuditCacheModel.endAge = getEndAge();

		String endAge = watsonPersonAuditCacheModel.endAge;

		if ((endAge != null) && (endAge.length() == 0)) {
			watsonPersonAuditCacheModel.endAge = null;
		}

		watsonPersonAuditCacheModel.occupation = getOccupation();

		String occupation = watsonPersonAuditCacheModel.occupation;

		if ((occupation != null) && (occupation.length() == 0)) {
			watsonPersonAuditCacheModel.occupation = null;
		}

		watsonPersonAuditCacheModel.height = getHeight();

		String height = watsonPersonAuditCacheModel.height;

		if ((height != null) && (height.length() == 0)) {
			watsonPersonAuditCacheModel.height = null;
		}

		watsonPersonAuditCacheModel.weight = getWeight();

		String weight = watsonPersonAuditCacheModel.weight;

		if ((weight != null) && (weight.length() == 0)) {
			watsonPersonAuditCacheModel.weight = null;
		}

		watsonPersonAuditCacheModel.accepted = isAccepted();

		watsonPersonAuditCacheModel.rescued = isRescued();

		watsonPersonAuditCacheModel.status = getStatus();

		return watsonPersonAuditCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(63);

		sb.append("{watsonPersonAuditId=");
		sb.append(getWatsonPersonAuditId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", birthCountryId=");
		sb.append(getBirthCountryId());
		sb.append(", citizenshipWatsonListTypeId=");
		sb.append(getCitizenshipWatsonListTypeId());
		sb.append(", countryWatsonListTypeId=");
		sb.append(getCountryWatsonListTypeId());
		sb.append(", ethnicityWatsonListTypeId=");
		sb.append(getEthnicityWatsonListTypeId());
		sb.append(", eyesWatsonListTypeId=");
		sb.append(getEyesWatsonListTypeId());
		sb.append(", hairWatsonListTypeId=");
		sb.append(getHairWatsonListTypeId());
		sb.append(", originalWatsonPersonId=");
		sb.append(getOriginalWatsonPersonId());
		sb.append(", sexWatsonListTypeId=");
		sb.append(getSexWatsonListTypeId());
		sb.append(", typeWatsonListTypeId=");
		sb.append(getTypeWatsonListTypeId());
		sb.append(", watsonIncidentId=");
		sb.append(getWatsonIncidentId());
		sb.append(", watsonPersonId=");
		sb.append(getWatsonPersonId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", imagePayload=");
		sb.append(getImagePayload());
		sb.append(", birthDate=");
		sb.append(getBirthDate());
		sb.append(", dateAccepted=");
		sb.append(getDateAccepted());
		sb.append(", dateRescued=");
		sb.append(getDateRescued());
		sb.append(", startAge=");
		sb.append(getStartAge());
		sb.append(", endAge=");
		sb.append(getEndAge());
		sb.append(", occupation=");
		sb.append(getOccupation());
		sb.append(", height=");
		sb.append(getHeight());
		sb.append(", weight=");
		sb.append(getWeight());
		sb.append(", accepted=");
		sb.append(isAccepted());
		sb.append(", rescued=");
		sb.append(isRescued());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(97);

		sb.append("<model><model-name>");
		sb.append("com.liferay.watson.model.WatsonPersonAudit");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>watsonPersonAuditId</column-name><column-value><![CDATA[");
		sb.append(getWatsonPersonAuditId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birthCountryId</column-name><column-value><![CDATA[");
		sb.append(getBirthCountryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>citizenshipWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getCitizenshipWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countryWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getCountryWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ethnicityWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getEthnicityWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eyesWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getEyesWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hairWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getHairWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>originalWatsonPersonId</column-name><column-value><![CDATA[");
		sb.append(getOriginalWatsonPersonId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sexWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getSexWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typeWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getTypeWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>watsonIncidentId</column-name><column-value><![CDATA[");
		sb.append(getWatsonIncidentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>watsonPersonId</column-name><column-value><![CDATA[");
		sb.append(getWatsonPersonId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imagePayload</column-name><column-value><![CDATA[");
		sb.append(getImagePayload());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>birthDate</column-name><column-value><![CDATA[");
		sb.append(getBirthDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateAccepted</column-name><column-value><![CDATA[");
		sb.append(getDateAccepted());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateRescued</column-name><column-value><![CDATA[");
		sb.append(getDateRescued());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startAge</column-name><column-value><![CDATA[");
		sb.append(getStartAge());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endAge</column-name><column-value><![CDATA[");
		sb.append(getEndAge());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>occupation</column-name><column-value><![CDATA[");
		sb.append(getOccupation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>height</column-name><column-value><![CDATA[");
		sb.append(getHeight());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>weight</column-name><column-value><![CDATA[");
		sb.append(getWeight());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accepted</column-name><column-value><![CDATA[");
		sb.append(isAccepted());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rescued</column-name><column-value><![CDATA[");
		sb.append(isRescued());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = WatsonPersonAudit.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			WatsonPersonAudit.class, ModelWrapper.class
		};
	private long _watsonPersonAuditId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _birthCountryId;
	private long _citizenshipWatsonListTypeId;
	private long _countryWatsonListTypeId;
	private long _ethnicityWatsonListTypeId;
	private long _eyesWatsonListTypeId;
	private long _hairWatsonListTypeId;
	private long _originalWatsonPersonId;
	private long _sexWatsonListTypeId;
	private long _typeWatsonListTypeId;
	private long _watsonIncidentId;
	private long _watsonPersonId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _imagePayload;
	private Date _birthDate;
	private Date _dateAccepted;
	private Date _dateRescued;
	private String _startAge;
	private String _endAge;
	private String _occupation;
	private String _occupationCurrentLanguageId;
	private String _height;
	private String _weight;
	private boolean _accepted;
	private boolean _rescued;
	private int _status;
	private WatsonPersonAudit _escapedModel;
}