/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.watson.model.WatsonHistoryAudit;
import com.liferay.watson.model.WatsonHistoryAuditModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonHistoryAudit service. Represents a row in the &quot;WatsonHistoryAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonHistoryAuditModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonHistoryAuditImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonHistoryAuditImpl
 * @generated
 */
public class WatsonHistoryAuditModelImpl
	extends BaseModelImpl<WatsonHistoryAudit>
	implements WatsonHistoryAuditModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson history audit model instance should use the <code>WatsonHistoryAudit</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonHistoryAudit";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonHistoryAuditId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"watsonHistoryId", Types.BIGINT},
		{"watsonParentId", Types.BIGINT}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"type_", Types.INTEGER},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonHistoryAuditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("watsonHistoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonParentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonHistoryAudit (watsonHistoryAuditId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,watsonHistoryId LONG,watsonParentId LONG,classNameId LONG,classPK LONG,type_ INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonHistoryAudit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonHistoryAudit.watsonHistoryAuditId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonHistoryAudit.watsonHistoryAuditId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonHistoryAudit"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonHistoryAudit"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonHistoryAudit"));

	public WatsonHistoryAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonHistoryAuditId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonHistoryAuditId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonHistoryAuditId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonHistoryAudit.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonHistoryAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonHistoryAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonHistoryAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonHistoryAudit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonHistoryAudit)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonHistoryAudit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonHistoryAudit, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonHistoryAudit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonHistoryAudit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonHistoryAudit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonHistoryAudit>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonHistoryAudit.class.getClassLoader(), WatsonHistoryAudit.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonHistoryAudit> constructor =
				(Constructor<WatsonHistoryAudit>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonHistoryAudit, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonHistoryAudit, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonHistoryAudit, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<WatsonHistoryAudit, Object>>();
		Map<String, BiConsumer<WatsonHistoryAudit, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<WatsonHistoryAudit, ?>>();

		attributeGetterFunctions.put(
			"watsonHistoryAuditId",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getWatsonHistoryAuditId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonHistoryAuditId",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object watsonHistoryAuditIdObject) {

					watsonHistoryAudit.setWatsonHistoryAuditId(
						(Long)watsonHistoryAuditIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object groupIdObject) {

					watsonHistoryAudit.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object companyIdObject) {

					watsonHistoryAudit.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object userIdObject) {

					watsonHistoryAudit.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object userNameObject) {

					watsonHistoryAudit.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object createDateObject) {

					watsonHistoryAudit.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object modifiedDateObject) {

					watsonHistoryAudit.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonHistoryId",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getWatsonHistoryId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonHistoryId",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object watsonHistoryIdObject) {

					watsonHistoryAudit.setWatsonHistoryId(
						(Long)watsonHistoryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonParentId",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getWatsonParentId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonParentId",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object watsonParentIdObject) {

					watsonHistoryAudit.setWatsonParentId(
						(Long)watsonParentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"classNameId",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getClassNameId();
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object classNameIdObject) {

					watsonHistoryAudit.setClassNameId((Long)classNameIdObject);
				}

			});
		attributeGetterFunctions.put(
			"classPK",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getClassPK();
				}

			});
		attributeSetterBiConsumers.put(
			"classPK",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object classPKObject) {

					watsonHistoryAudit.setClassPK((Long)classPKObject);
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getType();
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit, Object typeObject) {

					watsonHistoryAudit.setType((Integer)typeObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonHistoryAudit, Object>() {

				@Override
				public Object apply(WatsonHistoryAudit watsonHistoryAudit) {
					return watsonHistoryAudit.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonHistoryAudit, Object>() {

				@Override
				public void accept(
					WatsonHistoryAudit watsonHistoryAudit,
					Object statusObject) {

					watsonHistoryAudit.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonHistoryAuditId() {
		return _watsonHistoryAuditId;
	}

	@Override
	public void setWatsonHistoryAuditId(long watsonHistoryAuditId) {
		_watsonHistoryAuditId = watsonHistoryAuditId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getWatsonHistoryId() {
		return _watsonHistoryId;
	}

	@Override
	public void setWatsonHistoryId(long watsonHistoryId) {
		_watsonHistoryId = watsonHistoryId;
	}

	@Override
	public long getWatsonParentId() {
		return _watsonParentId;
	}

	@Override
	public void setWatsonParentId(long watsonParentId) {
		_watsonParentId = watsonParentId;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonHistoryAudit.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WatsonHistoryAudit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonHistoryAudit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonHistoryAuditImpl watsonHistoryAuditImpl =
			new WatsonHistoryAuditImpl();

		watsonHistoryAuditImpl.setWatsonHistoryAuditId(
			getWatsonHistoryAuditId());
		watsonHistoryAuditImpl.setGroupId(getGroupId());
		watsonHistoryAuditImpl.setCompanyId(getCompanyId());
		watsonHistoryAuditImpl.setUserId(getUserId());
		watsonHistoryAuditImpl.setUserName(getUserName());
		watsonHistoryAuditImpl.setCreateDate(getCreateDate());
		watsonHistoryAuditImpl.setModifiedDate(getModifiedDate());
		watsonHistoryAuditImpl.setWatsonHistoryId(getWatsonHistoryId());
		watsonHistoryAuditImpl.setWatsonParentId(getWatsonParentId());
		watsonHistoryAuditImpl.setClassNameId(getClassNameId());
		watsonHistoryAuditImpl.setClassPK(getClassPK());
		watsonHistoryAuditImpl.setType(getType());
		watsonHistoryAuditImpl.setStatus(getStatus());

		watsonHistoryAuditImpl.resetOriginalValues();

		return watsonHistoryAuditImpl;
	}

	@Override
	public int compareTo(WatsonHistoryAudit watsonHistoryAudit) {
		long primaryKey = watsonHistoryAudit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonHistoryAudit)) {
			return false;
		}

		WatsonHistoryAudit watsonHistoryAudit = (WatsonHistoryAudit)object;

		long primaryKey = watsonHistoryAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonHistoryAudit> toCacheModel() {
		WatsonHistoryAuditCacheModel watsonHistoryAuditCacheModel =
			new WatsonHistoryAuditCacheModel();

		watsonHistoryAuditCacheModel.watsonHistoryAuditId =
			getWatsonHistoryAuditId();

		watsonHistoryAuditCacheModel.groupId = getGroupId();

		watsonHistoryAuditCacheModel.companyId = getCompanyId();

		watsonHistoryAuditCacheModel.userId = getUserId();

		watsonHistoryAuditCacheModel.userName = getUserName();

		String userName = watsonHistoryAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonHistoryAuditCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonHistoryAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonHistoryAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonHistoryAuditCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonHistoryAuditCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonHistoryAuditCacheModel.watsonHistoryId = getWatsonHistoryId();

		watsonHistoryAuditCacheModel.watsonParentId = getWatsonParentId();

		watsonHistoryAuditCacheModel.classNameId = getClassNameId();

		watsonHistoryAuditCacheModel.classPK = getClassPK();

		watsonHistoryAuditCacheModel.type = getType();

		watsonHistoryAuditCacheModel.status = getStatus();

		return watsonHistoryAuditCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonHistoryAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonHistoryAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonHistoryAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonHistoryAudit)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonHistoryAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonHistoryAudit, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonHistoryAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonHistoryAudit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonHistoryAudit>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonHistoryAuditId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _watsonHistoryId;
	private long _watsonParentId;
	private long _classNameId;
	private long _classPK;
	private int _type;
	private int _status;
	private WatsonHistoryAudit _escapedModel;

}