/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.watson.model.WatsonListType;
import com.liferay.watson.model.WatsonListTypeModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonListType service. Represents a row in the &quot;WatsonListType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonListTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonListTypeImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonListTypeImpl
 * @generated
 */
public class WatsonListTypeModelImpl
	extends BaseModelImpl<WatsonListType> implements WatsonListTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson list type model instance should use the <code>WatsonListType</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonListType";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonListTypeId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"parentWatsonListTypeId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"type_", Types.VARCHAR}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonListType (watsonListTypeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentWatsonListTypeId LONG,name STRING null,type_ VARCHAR(100) null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonListType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonListType.watsonListTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonListType.watsonListTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonListType"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonListType"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonListType"));

	public WatsonListTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonListTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonListTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonListTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonListType.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonListType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonListType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonListType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonListType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonListType)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonListType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonListType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonListType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonListType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonListType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonListType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonListType.class.getClassLoader(), WatsonListType.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonListType> constructor =
				(Constructor<WatsonListType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonListType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonListType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonListType, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<WatsonListType, Object>>();
		Map<String, BiConsumer<WatsonListType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<WatsonListType, ?>>();

		attributeGetterFunctions.put(
			"watsonListTypeId",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonListTypeId",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType,
					Object watsonListTypeIdObject) {

					watsonListType.setWatsonListTypeId(
						(Long)watsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object groupIdObject) {

					watsonListType.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object companyIdObject) {

					watsonListType.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object userIdObject) {

					watsonListType.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object userNameObject) {

					watsonListType.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object createDateObject) {

					watsonListType.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object modifiedDateObject) {

					watsonListType.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"parentWatsonListTypeId",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getParentWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"parentWatsonListTypeId",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType,
					Object parentWatsonListTypeIdObject) {

					watsonListType.setParentWatsonListTypeId(
						(Long)parentWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object nameObject) {

					watsonListType.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getType();
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object typeObject) {

					watsonListType.setType((String)typeObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonListType, Object>() {

				@Override
				public Object apply(WatsonListType watsonListType) {
					return watsonListType.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonListType, Object>() {

				@Override
				public void accept(
					WatsonListType watsonListType, Object statusObject) {

					watsonListType.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonListTypeId() {
		return _watsonListTypeId;
	}

	@Override
	public void setWatsonListTypeId(long watsonListTypeId) {
		_watsonListTypeId = watsonListTypeId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getParentWatsonListTypeId() {
		return _parentWatsonListTypeId;
	}

	@Override
	public void setParentWatsonListTypeId(long parentWatsonListTypeId) {
		_parentWatsonListTypeId = parentWatsonListTypeId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonListType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			WatsonListType.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WatsonListType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonListType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonListTypeImpl watsonListTypeImpl = new WatsonListTypeImpl();

		watsonListTypeImpl.setWatsonListTypeId(getWatsonListTypeId());
		watsonListTypeImpl.setGroupId(getGroupId());
		watsonListTypeImpl.setCompanyId(getCompanyId());
		watsonListTypeImpl.setUserId(getUserId());
		watsonListTypeImpl.setUserName(getUserName());
		watsonListTypeImpl.setCreateDate(getCreateDate());
		watsonListTypeImpl.setModifiedDate(getModifiedDate());
		watsonListTypeImpl.setParentWatsonListTypeId(
			getParentWatsonListTypeId());
		watsonListTypeImpl.setName(getName());
		watsonListTypeImpl.setType(getType());
		watsonListTypeImpl.setStatus(getStatus());

		watsonListTypeImpl.resetOriginalValues();

		return watsonListTypeImpl;
	}

	@Override
	public int compareTo(WatsonListType watsonListType) {
		long primaryKey = watsonListType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonListType)) {
			return false;
		}

		WatsonListType watsonListType = (WatsonListType)object;

		long primaryKey = watsonListType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonListType> toCacheModel() {
		WatsonListTypeCacheModel watsonListTypeCacheModel =
			new WatsonListTypeCacheModel();

		watsonListTypeCacheModel.watsonListTypeId = getWatsonListTypeId();

		watsonListTypeCacheModel.groupId = getGroupId();

		watsonListTypeCacheModel.companyId = getCompanyId();

		watsonListTypeCacheModel.userId = getUserId();

		watsonListTypeCacheModel.userName = getUserName();

		String userName = watsonListTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonListTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonListTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonListTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonListTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonListTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonListTypeCacheModel.parentWatsonListTypeId =
			getParentWatsonListTypeId();

		watsonListTypeCacheModel.name = getName();

		String name = watsonListTypeCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			watsonListTypeCacheModel.name = null;
		}

		watsonListTypeCacheModel.type = getType();

		String type = watsonListTypeCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			watsonListTypeCacheModel.type = null;
		}

		watsonListTypeCacheModel.status = getStatus();

		return watsonListTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonListType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonListType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonListType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonListType)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonListType, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonListType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonListType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonListType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonListType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonListTypeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _parentWatsonListTypeId;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _type;
	private int _status;
	private WatsonListType _escapedModel;

}