/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import com.liferay.watson.model.WatsonListTypeAudit;
import com.liferay.watson.model.WatsonListTypeAuditModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the WatsonListTypeAudit service. Represents a row in the &quot;WatsonListTypeAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link WatsonListTypeAuditModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonListTypeAuditImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonListTypeAuditImpl
 * @see WatsonListTypeAudit
 * @see WatsonListTypeAuditModel
 * @generated
 */
@ProviderType
public class WatsonListTypeAuditModelImpl extends BaseModelImpl<WatsonListTypeAudit>
	implements WatsonListTypeAuditModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson list type audit model instance should use the {@link WatsonListTypeAudit} interface instead.
	 */
	public static final String TABLE_NAME = "WatsonListTypeAudit";
	public static final Object[][] TABLE_COLUMNS = {
			{ "watsonListTypeAuditId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "parentWatsonListTypeId", Types.BIGINT },
			{ "watsonListTypeId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "type_", Types.VARCHAR },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonListTypeAuditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table WatsonListTypeAudit (watsonListTypeAuditId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentWatsonListTypeId LONG,watsonListTypeId LONG,name STRING null,type_ VARCHAR(100) null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table WatsonListTypeAudit";
	public static final String ORDER_BY_JPQL = " ORDER BY watsonListTypeAudit.watsonListTypeAuditId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY WatsonListTypeAudit.watsonListTypeAuditId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.watson.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonListTypeAudit"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.watson.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonListTypeAudit"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.watson.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.watson.model.WatsonListTypeAudit"));

	public WatsonListTypeAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonListTypeAuditId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonListTypeAuditId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonListTypeAuditId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonListTypeAudit.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonListTypeAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("watsonListTypeAuditId", getWatsonListTypeAuditId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("parentWatsonListTypeId", getParentWatsonListTypeId());
		attributes.put("watsonListTypeId", getWatsonListTypeId());
		attributes.put("name", getName());
		attributes.put("type", getType());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long watsonListTypeAuditId = (Long)attributes.get(
				"watsonListTypeAuditId");

		if (watsonListTypeAuditId != null) {
			setWatsonListTypeAuditId(watsonListTypeAuditId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long parentWatsonListTypeId = (Long)attributes.get(
				"parentWatsonListTypeId");

		if (parentWatsonListTypeId != null) {
			setParentWatsonListTypeId(parentWatsonListTypeId);
		}

		Long watsonListTypeId = (Long)attributes.get("watsonListTypeId");

		if (watsonListTypeId != null) {
			setWatsonListTypeId(watsonListTypeId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@Override
	public long getWatsonListTypeAuditId() {
		return _watsonListTypeAuditId;
	}

	@Override
	public void setWatsonListTypeAuditId(long watsonListTypeAuditId) {
		_watsonListTypeAuditId = watsonListTypeAuditId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getParentWatsonListTypeId() {
		return _parentWatsonListTypeId;
	}

	@Override
	public void setParentWatsonListTypeId(long parentWatsonListTypeId) {
		_parentWatsonListTypeId = parentWatsonListTypeId;
	}

	@Override
	public long getWatsonListTypeId() {
		return _watsonListTypeId;
	}

	@Override
	public void setWatsonListTypeId(long watsonListTypeId) {
		_watsonListTypeId = watsonListTypeId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getName(), languageId,
			useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(LocalizationUtil.updateLocalization(getName(), "Name",
					name, languageId, defaultLanguageId));
		}
		else {
			setName(LocalizationUtil.removeLocalization(getName(), "Name",
					languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(LocalizationUtil.updateLocalization(nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			WatsonListTypeAudit.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(WatsonListTypeAudit.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WatsonListTypeAudit toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WatsonListTypeAudit)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonListTypeAuditImpl watsonListTypeAuditImpl = new WatsonListTypeAuditImpl();

		watsonListTypeAuditImpl.setWatsonListTypeAuditId(getWatsonListTypeAuditId());
		watsonListTypeAuditImpl.setGroupId(getGroupId());
		watsonListTypeAuditImpl.setCompanyId(getCompanyId());
		watsonListTypeAuditImpl.setUserId(getUserId());
		watsonListTypeAuditImpl.setUserName(getUserName());
		watsonListTypeAuditImpl.setCreateDate(getCreateDate());
		watsonListTypeAuditImpl.setModifiedDate(getModifiedDate());
		watsonListTypeAuditImpl.setParentWatsonListTypeId(getParentWatsonListTypeId());
		watsonListTypeAuditImpl.setWatsonListTypeId(getWatsonListTypeId());
		watsonListTypeAuditImpl.setName(getName());
		watsonListTypeAuditImpl.setType(getType());
		watsonListTypeAuditImpl.setStatus(getStatus());

		watsonListTypeAuditImpl.resetOriginalValues();

		return watsonListTypeAuditImpl;
	}

	@Override
	public int compareTo(WatsonListTypeAudit watsonListTypeAudit) {
		long primaryKey = watsonListTypeAudit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WatsonListTypeAudit)) {
			return false;
		}

		WatsonListTypeAudit watsonListTypeAudit = (WatsonListTypeAudit)obj;

		long primaryKey = watsonListTypeAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		WatsonListTypeAuditModelImpl watsonListTypeAuditModelImpl = this;

		watsonListTypeAuditModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonListTypeAudit> toCacheModel() {
		WatsonListTypeAuditCacheModel watsonListTypeAuditCacheModel = new WatsonListTypeAuditCacheModel();

		watsonListTypeAuditCacheModel.watsonListTypeAuditId = getWatsonListTypeAuditId();

		watsonListTypeAuditCacheModel.groupId = getGroupId();

		watsonListTypeAuditCacheModel.companyId = getCompanyId();

		watsonListTypeAuditCacheModel.userId = getUserId();

		watsonListTypeAuditCacheModel.userName = getUserName();

		String userName = watsonListTypeAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonListTypeAuditCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonListTypeAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonListTypeAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonListTypeAuditCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonListTypeAuditCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonListTypeAuditCacheModel.parentWatsonListTypeId = getParentWatsonListTypeId();

		watsonListTypeAuditCacheModel.watsonListTypeId = getWatsonListTypeId();

		watsonListTypeAuditCacheModel.name = getName();

		String name = watsonListTypeAuditCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			watsonListTypeAuditCacheModel.name = null;
		}

		watsonListTypeAuditCacheModel.type = getType();

		String type = watsonListTypeAuditCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			watsonListTypeAuditCacheModel.type = null;
		}

		watsonListTypeAuditCacheModel.status = getStatus();

		return watsonListTypeAuditCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{watsonListTypeAuditId=");
		sb.append(getWatsonListTypeAuditId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", parentWatsonListTypeId=");
		sb.append(getParentWatsonListTypeId());
		sb.append(", watsonListTypeId=");
		sb.append(getWatsonListTypeId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.liferay.watson.model.WatsonListTypeAudit");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>watsonListTypeAuditId</column-name><column-value><![CDATA[");
		sb.append(getWatsonListTypeAuditId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentWatsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getParentWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>watsonListTypeId</column-name><column-value><![CDATA[");
		sb.append(getWatsonListTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = WatsonListTypeAudit.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			WatsonListTypeAudit.class, ModelWrapper.class
		};
	private long _watsonListTypeAuditId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _parentWatsonListTypeId;
	private long _watsonListTypeId;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _type;
	private int _status;
	private WatsonListTypeAudit _escapedModel;
}