/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.watson.model.WatsonResource;
import com.liferay.watson.model.WatsonResourceModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonResource service. Represents a row in the &quot;WatsonResource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonResourceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonResourceImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonResourceImpl
 * @generated
 */
public class WatsonResourceModelImpl
	extends BaseModelImpl<WatsonResource> implements WatsonResourceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson resource model instance should use the <code>WatsonResource</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonResource";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonResourceId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"originalWatsonResourceId", Types.BIGINT},
		{"typeWatsonListTypeId", Types.BIGINT},
		{"watsonIncidentId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"imagePayload", Types.CLOB},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("originalWatsonResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonIncidentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imagePayload", Types.CLOB);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonResource (watsonResourceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,originalWatsonResourceId LONG,typeWatsonListTypeId LONG,watsonIncidentId LONG,name STRING null,description STRING null,imagePayload TEXT null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonResource";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonResource.watsonResourceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonResource.watsonResourceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonResource"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonResource"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonResource"));

	public WatsonResourceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonResourceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonResourceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonResourceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonResource.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonResource.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonResource, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonResource, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonResource, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonResource)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonResource, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonResource, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonResource)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonResource, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonResource, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonResource>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonResource.class.getClassLoader(), WatsonResource.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonResource> constructor =
				(Constructor<WatsonResource>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonResource, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonResource, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonResource, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<WatsonResource, Object>>();
		Map<String, BiConsumer<WatsonResource, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<WatsonResource, ?>>();

		attributeGetterFunctions.put(
			"watsonResourceId",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getWatsonResourceId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonResourceId",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource,
					Object watsonResourceIdObject) {

					watsonResource.setWatsonResourceId(
						(Long)watsonResourceIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object groupIdObject) {

					watsonResource.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object companyIdObject) {

					watsonResource.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object userIdObject) {

					watsonResource.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object userNameObject) {

					watsonResource.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object createDateObject) {

					watsonResource.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object modifiedDateObject) {

					watsonResource.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"originalWatsonResourceId",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getOriginalWatsonResourceId();
				}

			});
		attributeSetterBiConsumers.put(
			"originalWatsonResourceId",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource,
					Object originalWatsonResourceIdObject) {

					watsonResource.setOriginalWatsonResourceId(
						(Long)originalWatsonResourceIdObject);
				}

			});
		attributeGetterFunctions.put(
			"typeWatsonListTypeId",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"typeWatsonListTypeId",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource,
					Object typeWatsonListTypeIdObject) {

					watsonResource.setTypeWatsonListTypeId(
						(Long)typeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonIncidentId",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getWatsonIncidentId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentId",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource,
					Object watsonIncidentIdObject) {

					watsonResource.setWatsonIncidentId(
						(Long)watsonIncidentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object nameObject) {

					watsonResource.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object descriptionObject) {

					watsonResource.setDescription((String)descriptionObject);
				}

			});
		attributeGetterFunctions.put(
			"imagePayload",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getImagePayload();
				}

			});
		attributeSetterBiConsumers.put(
			"imagePayload",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object imagePayloadObject) {

					watsonResource.setImagePayload((String)imagePayloadObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonResource, Object>() {

				@Override
				public Object apply(WatsonResource watsonResource) {
					return watsonResource.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonResource, Object>() {

				@Override
				public void accept(
					WatsonResource watsonResource, Object statusObject) {

					watsonResource.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonResourceId() {
		return _watsonResourceId;
	}

	@Override
	public void setWatsonResourceId(long watsonResourceId) {
		_watsonResourceId = watsonResourceId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getOriginalWatsonResourceId() {
		return _originalWatsonResourceId;
	}

	@Override
	public void setOriginalWatsonResourceId(long originalWatsonResourceId) {
		_originalWatsonResourceId = originalWatsonResourceId;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getWatsonIncidentId() {
		return _watsonIncidentId;
	}

	@Override
	public void setWatsonIncidentId(long watsonIncidentId) {
		_watsonIncidentId = watsonIncidentId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getImagePayload() {
		if (_imagePayload == null) {
			return "";
		}
		else {
			return _imagePayload;
		}
	}

	@Override
	public void setImagePayload(String imagePayload) {
		_imagePayload = imagePayload;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonResource.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			WatsonResource.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WatsonResource toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonResource>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonResourceImpl watsonResourceImpl = new WatsonResourceImpl();

		watsonResourceImpl.setWatsonResourceId(getWatsonResourceId());
		watsonResourceImpl.setGroupId(getGroupId());
		watsonResourceImpl.setCompanyId(getCompanyId());
		watsonResourceImpl.setUserId(getUserId());
		watsonResourceImpl.setUserName(getUserName());
		watsonResourceImpl.setCreateDate(getCreateDate());
		watsonResourceImpl.setModifiedDate(getModifiedDate());
		watsonResourceImpl.setOriginalWatsonResourceId(
			getOriginalWatsonResourceId());
		watsonResourceImpl.setTypeWatsonListTypeId(getTypeWatsonListTypeId());
		watsonResourceImpl.setWatsonIncidentId(getWatsonIncidentId());
		watsonResourceImpl.setName(getName());
		watsonResourceImpl.setDescription(getDescription());
		watsonResourceImpl.setImagePayload(getImagePayload());
		watsonResourceImpl.setStatus(getStatus());

		watsonResourceImpl.resetOriginalValues();

		return watsonResourceImpl;
	}

	@Override
	public int compareTo(WatsonResource watsonResource) {
		long primaryKey = watsonResource.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonResource)) {
			return false;
		}

		WatsonResource watsonResource = (WatsonResource)object;

		long primaryKey = watsonResource.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonResource> toCacheModel() {
		WatsonResourceCacheModel watsonResourceCacheModel =
			new WatsonResourceCacheModel();

		watsonResourceCacheModel.watsonResourceId = getWatsonResourceId();

		watsonResourceCacheModel.groupId = getGroupId();

		watsonResourceCacheModel.companyId = getCompanyId();

		watsonResourceCacheModel.userId = getUserId();

		watsonResourceCacheModel.userName = getUserName();

		String userName = watsonResourceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonResourceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonResourceCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonResourceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonResourceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonResourceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonResourceCacheModel.originalWatsonResourceId =
			getOriginalWatsonResourceId();

		watsonResourceCacheModel.typeWatsonListTypeId =
			getTypeWatsonListTypeId();

		watsonResourceCacheModel.watsonIncidentId = getWatsonIncidentId();

		watsonResourceCacheModel.name = getName();

		String name = watsonResourceCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			watsonResourceCacheModel.name = null;
		}

		watsonResourceCacheModel.description = getDescription();

		String description = watsonResourceCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			watsonResourceCacheModel.description = null;
		}

		watsonResourceCacheModel.imagePayload = getImagePayload();

		String imagePayload = watsonResourceCacheModel.imagePayload;

		if ((imagePayload != null) && (imagePayload.length() == 0)) {
			watsonResourceCacheModel.imagePayload = null;
		}

		watsonResourceCacheModel.status = getStatus();

		return watsonResourceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonResource, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonResource, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonResource, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonResource)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonResource, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonResource, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonResource, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonResource)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonResource>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonResourceId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _originalWatsonResourceId;
	private long _typeWatsonListTypeId;
	private long _watsonIncidentId;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _imagePayload;
	private int _status;
	private WatsonResource _escapedModel;

}