/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.watson.model.WatsonRelationshipAudit;
import com.liferay.watson.model.WatsonRelationshipAuditModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonRelationshipAudit service. Represents a row in the &quot;WatsonRelationshipAudit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonRelationshipAuditModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonRelationshipAuditImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonRelationshipAuditImpl
 * @generated
 */
public class WatsonRelationshipAuditModelImpl
	extends BaseModelImpl<WatsonRelationshipAudit>
	implements WatsonRelationshipAuditModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson relationship audit model instance should use the <code>WatsonRelationshipAudit</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonRelationshipAudit";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonRelationshipAuditId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"watsonIncidentId", Types.BIGINT},
		{"watsonRelationshipId", Types.BIGINT},
		{"typeWatsonListTypeId", Types.BIGINT}, {"classNameId1", Types.BIGINT},
		{"classPK1", Types.BIGINT}, {"classNameId2", Types.BIGINT},
		{"classPK2", Types.BIGINT}, {"description", Types.VARCHAR},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonRelationshipAuditId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("watsonIncidentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonRelationshipId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId1", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK1", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId2", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK2", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonRelationshipAudit (watsonRelationshipAuditId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,watsonIncidentId LONG,watsonRelationshipId LONG,typeWatsonListTypeId LONG,classNameId1 LONG,classPK1 LONG,classNameId2 LONG,classPK2 LONG,description STRING null,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table WatsonRelationshipAudit";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonRelationshipAudit.watsonRelationshipAuditId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonRelationshipAudit.watsonRelationshipAuditId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonRelationshipAudit"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonRelationshipAudit"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonRelationshipAudit"));

	public WatsonRelationshipAuditModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonRelationshipAuditId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonRelationshipAuditId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonRelationshipAuditId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonRelationshipAudit.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonRelationshipAudit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonRelationshipAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonRelationshipAudit, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonRelationshipAudit, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonRelationshipAudit)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonRelationshipAudit, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonRelationshipAudit, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonRelationshipAudit)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonRelationshipAudit, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonRelationshipAudit, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonRelationshipAudit>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonRelationshipAudit.class.getClassLoader(),
			WatsonRelationshipAudit.class, ModelWrapper.class);

		try {
			Constructor<WatsonRelationshipAudit> constructor =
				(Constructor<WatsonRelationshipAudit>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonRelationshipAudit, Object>>
		_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<WatsonRelationshipAudit, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonRelationshipAudit, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<WatsonRelationshipAudit, Object>>();
		Map<String, BiConsumer<WatsonRelationshipAudit, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<WatsonRelationshipAudit, ?>>();

		attributeGetterFunctions.put(
			"watsonRelationshipAuditId",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.
						getWatsonRelationshipAuditId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonRelationshipAuditId",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object watsonRelationshipAuditIdObject) {

					watsonRelationshipAudit.setWatsonRelationshipAuditId(
						(Long)watsonRelationshipAuditIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object groupIdObject) {

					watsonRelationshipAudit.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object companyIdObject) {

					watsonRelationshipAudit.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object userIdObject) {

					watsonRelationshipAudit.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object userNameObject) {

					watsonRelationshipAudit.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object createDateObject) {

					watsonRelationshipAudit.setCreateDate(
						(Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object modifiedDateObject) {

					watsonRelationshipAudit.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonIncidentId",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getWatsonIncidentId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentId",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object watsonIncidentIdObject) {

					watsonRelationshipAudit.setWatsonIncidentId(
						(Long)watsonIncidentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonRelationshipId",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getWatsonRelationshipId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonRelationshipId",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object watsonRelationshipIdObject) {

					watsonRelationshipAudit.setWatsonRelationshipId(
						(Long)watsonRelationshipIdObject);
				}

			});
		attributeGetterFunctions.put(
			"typeWatsonListTypeId",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"typeWatsonListTypeId",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object typeWatsonListTypeIdObject) {

					watsonRelationshipAudit.setTypeWatsonListTypeId(
						(Long)typeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"classNameId1",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getClassNameId1();
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId1",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object classNameId1Object) {

					watsonRelationshipAudit.setClassNameId1(
						(Long)classNameId1Object);
				}

			});
		attributeGetterFunctions.put(
			"classPK1",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getClassPK1();
				}

			});
		attributeSetterBiConsumers.put(
			"classPK1",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object classPK1Object) {

					watsonRelationshipAudit.setClassPK1((Long)classPK1Object);
				}

			});
		attributeGetterFunctions.put(
			"classNameId2",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getClassNameId2();
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId2",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object classNameId2Object) {

					watsonRelationshipAudit.setClassNameId2(
						(Long)classNameId2Object);
				}

			});
		attributeGetterFunctions.put(
			"classPK2",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getClassPK2();
				}

			});
		attributeSetterBiConsumers.put(
			"classPK2",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object classPK2Object) {

					watsonRelationshipAudit.setClassPK2((Long)classPK2Object);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object descriptionObject) {

					watsonRelationshipAudit.setDescription(
						(String)descriptionObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonRelationshipAudit, Object>() {

				@Override
				public Object apply(
					WatsonRelationshipAudit watsonRelationshipAudit) {

					return watsonRelationshipAudit.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonRelationshipAudit, Object>() {

				@Override
				public void accept(
					WatsonRelationshipAudit watsonRelationshipAudit,
					Object statusObject) {

					watsonRelationshipAudit.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonRelationshipAuditId() {
		return _watsonRelationshipAuditId;
	}

	@Override
	public void setWatsonRelationshipAuditId(long watsonRelationshipAuditId) {
		_watsonRelationshipAuditId = watsonRelationshipAuditId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getWatsonIncidentId() {
		return _watsonIncidentId;
	}

	@Override
	public void setWatsonIncidentId(long watsonIncidentId) {
		_watsonIncidentId = watsonIncidentId;
	}

	@Override
	public long getWatsonRelationshipId() {
		return _watsonRelationshipId;
	}

	@Override
	public void setWatsonRelationshipId(long watsonRelationshipId) {
		_watsonRelationshipId = watsonRelationshipId;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getClassNameId1() {
		return _classNameId1;
	}

	@Override
	public void setClassNameId1(long classNameId1) {
		_classNameId1 = classNameId1;
	}

	@Override
	public long getClassPK1() {
		return _classPK1;
	}

	@Override
	public void setClassPK1(long classPK1) {
		_classPK1 = classPK1;
	}

	@Override
	public long getClassNameId2() {
		return _classNameId2;
	}

	@Override
	public void setClassNameId2(long classNameId2) {
		_classNameId2 = classNameId2;
	}

	@Override
	public long getClassPK2() {
		return _classPK2;
	}

	@Override
	public void setClassPK2(long classPK2) {
		_classPK2 = classPK2;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonRelationshipAudit.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WatsonRelationshipAudit toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonRelationshipAudit>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonRelationshipAuditImpl watsonRelationshipAuditImpl =
			new WatsonRelationshipAuditImpl();

		watsonRelationshipAuditImpl.setWatsonRelationshipAuditId(
			getWatsonRelationshipAuditId());
		watsonRelationshipAuditImpl.setGroupId(getGroupId());
		watsonRelationshipAuditImpl.setCompanyId(getCompanyId());
		watsonRelationshipAuditImpl.setUserId(getUserId());
		watsonRelationshipAuditImpl.setUserName(getUserName());
		watsonRelationshipAuditImpl.setCreateDate(getCreateDate());
		watsonRelationshipAuditImpl.setModifiedDate(getModifiedDate());
		watsonRelationshipAuditImpl.setWatsonIncidentId(getWatsonIncidentId());
		watsonRelationshipAuditImpl.setWatsonRelationshipId(
			getWatsonRelationshipId());
		watsonRelationshipAuditImpl.setTypeWatsonListTypeId(
			getTypeWatsonListTypeId());
		watsonRelationshipAuditImpl.setClassNameId1(getClassNameId1());
		watsonRelationshipAuditImpl.setClassPK1(getClassPK1());
		watsonRelationshipAuditImpl.setClassNameId2(getClassNameId2());
		watsonRelationshipAuditImpl.setClassPK2(getClassPK2());
		watsonRelationshipAuditImpl.setDescription(getDescription());
		watsonRelationshipAuditImpl.setStatus(getStatus());

		watsonRelationshipAuditImpl.resetOriginalValues();

		return watsonRelationshipAuditImpl;
	}

	@Override
	public int compareTo(WatsonRelationshipAudit watsonRelationshipAudit) {
		long primaryKey = watsonRelationshipAudit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonRelationshipAudit)) {
			return false;
		}

		WatsonRelationshipAudit watsonRelationshipAudit =
			(WatsonRelationshipAudit)object;

		long primaryKey = watsonRelationshipAudit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonRelationshipAudit> toCacheModel() {
		WatsonRelationshipAuditCacheModel watsonRelationshipAuditCacheModel =
			new WatsonRelationshipAuditCacheModel();

		watsonRelationshipAuditCacheModel.watsonRelationshipAuditId =
			getWatsonRelationshipAuditId();

		watsonRelationshipAuditCacheModel.groupId = getGroupId();

		watsonRelationshipAuditCacheModel.companyId = getCompanyId();

		watsonRelationshipAuditCacheModel.userId = getUserId();

		watsonRelationshipAuditCacheModel.userName = getUserName();

		String userName = watsonRelationshipAuditCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonRelationshipAuditCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonRelationshipAuditCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonRelationshipAuditCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonRelationshipAuditCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			watsonRelationshipAuditCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonRelationshipAuditCacheModel.watsonIncidentId =
			getWatsonIncidentId();

		watsonRelationshipAuditCacheModel.watsonRelationshipId =
			getWatsonRelationshipId();

		watsonRelationshipAuditCacheModel.typeWatsonListTypeId =
			getTypeWatsonListTypeId();

		watsonRelationshipAuditCacheModel.classNameId1 = getClassNameId1();

		watsonRelationshipAuditCacheModel.classPK1 = getClassPK1();

		watsonRelationshipAuditCacheModel.classNameId2 = getClassNameId2();

		watsonRelationshipAuditCacheModel.classPK2 = getClassPK2();

		watsonRelationshipAuditCacheModel.description = getDescription();

		String description = watsonRelationshipAuditCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			watsonRelationshipAuditCacheModel.description = null;
		}

		watsonRelationshipAuditCacheModel.status = getStatus();

		return watsonRelationshipAuditCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonRelationshipAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonRelationshipAudit, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonRelationshipAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((WatsonRelationshipAudit)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonRelationshipAudit, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonRelationshipAudit, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonRelationshipAudit, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((WatsonRelationshipAudit)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, WatsonRelationshipAudit>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _watsonRelationshipAuditId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _watsonIncidentId;
	private long _watsonRelationshipId;
	private long _typeWatsonListTypeId;
	private long _classNameId1;
	private long _classPK1;
	private long _classNameId2;
	private long _classPK2;
	private String _description;
	private int _status;
	private WatsonRelationshipAudit _escapedModel;

}