/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.watson.model.WatsonIncidentRel;
import com.liferay.watson.model.WatsonIncidentRelModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonIncidentRel service. Represents a row in the &quot;WatsonIncidentRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonIncidentRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonIncidentRelImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonIncidentRelImpl
 * @generated
 */
public class WatsonIncidentRelModelImpl
	extends BaseModelImpl<WatsonIncidentRel> implements WatsonIncidentRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson incident rel model instance should use the <code>WatsonIncidentRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonIncidentRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonIncidentRelId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"watsonIncidentId1", Types.BIGINT},
		{"watsonIncidentId2", Types.BIGINT}, {"type_", Types.VARCHAR},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonIncidentRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("watsonIncidentId1", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonIncidentId2", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonIncidentRel (watsonIncidentRelId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,watsonIncidentId1 LONG,watsonIncidentId2 LONG,type_ VARCHAR(75) null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonIncidentRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonIncidentRel.watsonIncidentRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonIncidentRel.watsonIncidentRelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonIncidentRel"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonIncidentRel"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonIncidentRel"));

	public WatsonIncidentRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonIncidentRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonIncidentRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonIncidentRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonIncidentRel.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonIncidentRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonIncidentRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonIncidentRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonIncidentRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonIncidentRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonIncidentRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonIncidentRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonIncidentRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonIncidentRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonIncidentRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonIncidentRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonIncidentRel.class.getClassLoader(), WatsonIncidentRel.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonIncidentRel> constructor =
				(Constructor<WatsonIncidentRel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonIncidentRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonIncidentRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonIncidentRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<WatsonIncidentRel, Object>>();
		Map<String, BiConsumer<WatsonIncidentRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<WatsonIncidentRel, ?>>();

		attributeGetterFunctions.put(
			"watsonIncidentRelId",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getWatsonIncidentRelId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentRelId",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel,
					Object watsonIncidentRelIdObject) {

					watsonIncidentRel.setWatsonIncidentRelId(
						(Long)watsonIncidentRelIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel, Object groupIdObject) {

					watsonIncidentRel.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel,
					Object companyIdObject) {

					watsonIncidentRel.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel, Object userIdObject) {

					watsonIncidentRel.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel,
					Object userNameObject) {

					watsonIncidentRel.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel,
					Object createDateObject) {

					watsonIncidentRel.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel,
					Object modifiedDateObject) {

					watsonIncidentRel.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonIncidentId1",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getWatsonIncidentId1();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentId1",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel,
					Object watsonIncidentId1Object) {

					watsonIncidentRel.setWatsonIncidentId1(
						(Long)watsonIncidentId1Object);
				}

			});
		attributeGetterFunctions.put(
			"watsonIncidentId2",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getWatsonIncidentId2();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentId2",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel,
					Object watsonIncidentId2Object) {

					watsonIncidentRel.setWatsonIncidentId2(
						(Long)watsonIncidentId2Object);
				}

			});
		attributeGetterFunctions.put(
			"type",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getType();
				}

			});
		attributeSetterBiConsumers.put(
			"type",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel, Object typeObject) {

					watsonIncidentRel.setType((String)typeObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonIncidentRel, Object>() {

				@Override
				public Object apply(WatsonIncidentRel watsonIncidentRel) {
					return watsonIncidentRel.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonIncidentRel, Object>() {

				@Override
				public void accept(
					WatsonIncidentRel watsonIncidentRel, Object statusObject) {

					watsonIncidentRel.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonIncidentRelId() {
		return _watsonIncidentRelId;
	}

	@Override
	public void setWatsonIncidentRelId(long watsonIncidentRelId) {
		_watsonIncidentRelId = watsonIncidentRelId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getWatsonIncidentId1() {
		return _watsonIncidentId1;
	}

	@Override
	public void setWatsonIncidentId1(long watsonIncidentId1) {
		_watsonIncidentId1 = watsonIncidentId1;
	}

	@Override
	public long getWatsonIncidentId2() {
		return _watsonIncidentId2;
	}

	@Override
	public void setWatsonIncidentId2(long watsonIncidentId2) {
		_watsonIncidentId2 = watsonIncidentId2;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonIncidentRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WatsonIncidentRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonIncidentRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonIncidentRelImpl watsonIncidentRelImpl =
			new WatsonIncidentRelImpl();

		watsonIncidentRelImpl.setWatsonIncidentRelId(getWatsonIncidentRelId());
		watsonIncidentRelImpl.setGroupId(getGroupId());
		watsonIncidentRelImpl.setCompanyId(getCompanyId());
		watsonIncidentRelImpl.setUserId(getUserId());
		watsonIncidentRelImpl.setUserName(getUserName());
		watsonIncidentRelImpl.setCreateDate(getCreateDate());
		watsonIncidentRelImpl.setModifiedDate(getModifiedDate());
		watsonIncidentRelImpl.setWatsonIncidentId1(getWatsonIncidentId1());
		watsonIncidentRelImpl.setWatsonIncidentId2(getWatsonIncidentId2());
		watsonIncidentRelImpl.setType(getType());
		watsonIncidentRelImpl.setStatus(getStatus());

		watsonIncidentRelImpl.resetOriginalValues();

		return watsonIncidentRelImpl;
	}

	@Override
	public int compareTo(WatsonIncidentRel watsonIncidentRel) {
		long primaryKey = watsonIncidentRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonIncidentRel)) {
			return false;
		}

		WatsonIncidentRel watsonIncidentRel = (WatsonIncidentRel)object;

		long primaryKey = watsonIncidentRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonIncidentRel> toCacheModel() {
		WatsonIncidentRelCacheModel watsonIncidentRelCacheModel =
			new WatsonIncidentRelCacheModel();

		watsonIncidentRelCacheModel.watsonIncidentRelId =
			getWatsonIncidentRelId();

		watsonIncidentRelCacheModel.groupId = getGroupId();

		watsonIncidentRelCacheModel.companyId = getCompanyId();

		watsonIncidentRelCacheModel.userId = getUserId();

		watsonIncidentRelCacheModel.userName = getUserName();

		String userName = watsonIncidentRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonIncidentRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonIncidentRelCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonIncidentRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonIncidentRelCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonIncidentRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonIncidentRelCacheModel.watsonIncidentId1 = getWatsonIncidentId1();

		watsonIncidentRelCacheModel.watsonIncidentId2 = getWatsonIncidentId2();

		watsonIncidentRelCacheModel.type = getType();

		String type = watsonIncidentRelCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			watsonIncidentRelCacheModel.type = null;
		}

		watsonIncidentRelCacheModel.status = getStatus();

		return watsonIncidentRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonIncidentRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonIncidentRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonIncidentRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonIncidentRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonIncidentRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonIncidentRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonIncidentRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonIncidentRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonIncidentRel>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonIncidentRelId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _watsonIncidentId1;
	private long _watsonIncidentId2;
	private String _type;
	private int _status;
	private WatsonIncidentRel _escapedModel;

}