/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.watson.model.WatsonActivity;
import com.liferay.watson.model.WatsonActivityModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonActivity service. Represents a row in the &quot;WatsonActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonActivityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonActivityImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonActivityImpl
 * @generated
 */
public class WatsonActivityModelImpl
	extends BaseModelImpl<WatsonActivity> implements WatsonActivityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson activity model instance should use the <code>WatsonActivity</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonActivity";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonActivityId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"typeWatsonListTypeId", Types.BIGINT},
		{"subtypeWatsonListTypeId", Types.BIGINT},
		{"watsonIncidentId", Types.BIGINT}, {"narrative", Types.VARCHAR},
		{"reportDate", Types.TIMESTAMP}, {"startDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonActivityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subtypeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonIncidentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("narrative", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reportDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonActivity (watsonActivityId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,typeWatsonListTypeId LONG,subtypeWatsonListTypeId LONG,watsonIncidentId LONG,narrative STRING null,reportDate DATE null,startDate DATE null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonActivity";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonActivity.watsonActivityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonActivity.watsonActivityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonActivity"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonActivity"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonActivity"));

	public WatsonActivityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonActivityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonActivityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonActivityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonActivity.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonActivity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonActivity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonActivity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonActivity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonActivity)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonActivity, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonActivity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonActivity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonActivity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonActivity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonActivity>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonActivity.class.getClassLoader(), WatsonActivity.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonActivity> constructor =
				(Constructor<WatsonActivity>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonActivity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonActivity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonActivity, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<WatsonActivity, Object>>();
		Map<String, BiConsumer<WatsonActivity, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<WatsonActivity, ?>>();

		attributeGetterFunctions.put(
			"watsonActivityId",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getWatsonActivityId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonActivityId",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity,
					Object watsonActivityIdObject) {

					watsonActivity.setWatsonActivityId(
						(Long)watsonActivityIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object groupIdObject) {

					watsonActivity.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object companyIdObject) {

					watsonActivity.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object userIdObject) {

					watsonActivity.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object userNameObject) {

					watsonActivity.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object createDateObject) {

					watsonActivity.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object modifiedDateObject) {

					watsonActivity.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"typeWatsonListTypeId",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"typeWatsonListTypeId",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity,
					Object typeWatsonListTypeIdObject) {

					watsonActivity.setTypeWatsonListTypeId(
						(Long)typeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"subtypeWatsonListTypeId",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getSubtypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"subtypeWatsonListTypeId",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity,
					Object subtypeWatsonListTypeIdObject) {

					watsonActivity.setSubtypeWatsonListTypeId(
						(Long)subtypeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonIncidentId",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getWatsonIncidentId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentId",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity,
					Object watsonIncidentIdObject) {

					watsonActivity.setWatsonIncidentId(
						(Long)watsonIncidentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"narrative",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getNarrative();
				}

			});
		attributeSetterBiConsumers.put(
			"narrative",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object narrativeObject) {

					watsonActivity.setNarrative((String)narrativeObject);
				}

			});
		attributeGetterFunctions.put(
			"reportDate",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getReportDate();
				}

			});
		attributeSetterBiConsumers.put(
			"reportDate",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object reportDateObject) {

					watsonActivity.setReportDate((Date)reportDateObject);
				}

			});
		attributeGetterFunctions.put(
			"startDate",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"startDate",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object startDateObject) {

					watsonActivity.setStartDate((Date)startDateObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonActivity, Object>() {

				@Override
				public Object apply(WatsonActivity watsonActivity) {
					return watsonActivity.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonActivity, Object>() {

				@Override
				public void accept(
					WatsonActivity watsonActivity, Object statusObject) {

					watsonActivity.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonActivityId() {
		return _watsonActivityId;
	}

	@Override
	public void setWatsonActivityId(long watsonActivityId) {
		_watsonActivityId = watsonActivityId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getSubtypeWatsonListTypeId() {
		return _subtypeWatsonListTypeId;
	}

	@Override
	public void setSubtypeWatsonListTypeId(long subtypeWatsonListTypeId) {
		_subtypeWatsonListTypeId = subtypeWatsonListTypeId;
	}

	@Override
	public long getWatsonIncidentId() {
		return _watsonIncidentId;
	}

	@Override
	public void setWatsonIncidentId(long watsonIncidentId) {
		_watsonIncidentId = watsonIncidentId;
	}

	@Override
	public String getNarrative() {
		if (_narrative == null) {
			return "";
		}
		else {
			return _narrative;
		}
	}

	@Override
	public String getNarrative(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getNarrative(languageId);
	}

	@Override
	public String getNarrative(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getNarrative(languageId, useDefault);
	}

	@Override
	public String getNarrative(String languageId) {
		return LocalizationUtil.getLocalization(getNarrative(), languageId);
	}

	@Override
	public String getNarrative(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getNarrative(), languageId, useDefault);
	}

	@Override
	public String getNarrativeCurrentLanguageId() {
		return _narrativeCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNarrativeCurrentValue() {
		Locale locale = getLocale(_narrativeCurrentLanguageId);

		return getNarrative(locale);
	}

	@Override
	public Map<Locale, String> getNarrativeMap() {
		return LocalizationUtil.getLocalizationMap(getNarrative());
	}

	@Override
	public void setNarrative(String narrative) {
		_narrative = narrative;
	}

	@Override
	public void setNarrative(String narrative, Locale locale) {
		setNarrative(narrative, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNarrative(
		String narrative, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(narrative)) {
			setNarrative(
				LocalizationUtil.updateLocalization(
					getNarrative(), "Narrative", narrative, languageId,
					defaultLanguageId));
		}
		else {
			setNarrative(
				LocalizationUtil.removeLocalization(
					getNarrative(), "Narrative", languageId));
		}
	}

	@Override
	public void setNarrativeCurrentLanguageId(String languageId) {
		_narrativeCurrentLanguageId = languageId;
	}

	@Override
	public void setNarrativeMap(Map<Locale, String> narrativeMap) {
		setNarrativeMap(narrativeMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNarrativeMap(
		Map<Locale, String> narrativeMap, Locale defaultLocale) {

		if (narrativeMap == null) {
			return;
		}

		setNarrative(
			LocalizationUtil.updateLocalization(
				narrativeMap, getNarrative(), "Narrative",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Date getReportDate() {
		return _reportDate;
	}

	@Override
	public void setReportDate(Date reportDate) {
		_reportDate = reportDate;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonActivity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> narrativeMap = getNarrativeMap();

		for (Map.Entry<Locale, String> entry : narrativeMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getNarrative();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			WatsonActivity.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String narrative = getNarrative(defaultLocale);

		if (Validator.isNull(narrative)) {
			setNarrative(getNarrative(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setNarrative(
				getNarrative(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WatsonActivity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonActivity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonActivityImpl watsonActivityImpl = new WatsonActivityImpl();

		watsonActivityImpl.setWatsonActivityId(getWatsonActivityId());
		watsonActivityImpl.setGroupId(getGroupId());
		watsonActivityImpl.setCompanyId(getCompanyId());
		watsonActivityImpl.setUserId(getUserId());
		watsonActivityImpl.setUserName(getUserName());
		watsonActivityImpl.setCreateDate(getCreateDate());
		watsonActivityImpl.setModifiedDate(getModifiedDate());
		watsonActivityImpl.setTypeWatsonListTypeId(getTypeWatsonListTypeId());
		watsonActivityImpl.setSubtypeWatsonListTypeId(
			getSubtypeWatsonListTypeId());
		watsonActivityImpl.setWatsonIncidentId(getWatsonIncidentId());
		watsonActivityImpl.setNarrative(getNarrative());
		watsonActivityImpl.setReportDate(getReportDate());
		watsonActivityImpl.setStartDate(getStartDate());
		watsonActivityImpl.setStatus(getStatus());

		watsonActivityImpl.resetOriginalValues();

		return watsonActivityImpl;
	}

	@Override
	public int compareTo(WatsonActivity watsonActivity) {
		long primaryKey = watsonActivity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonActivity)) {
			return false;
		}

		WatsonActivity watsonActivity = (WatsonActivity)object;

		long primaryKey = watsonActivity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonActivity> toCacheModel() {
		WatsonActivityCacheModel watsonActivityCacheModel =
			new WatsonActivityCacheModel();

		watsonActivityCacheModel.watsonActivityId = getWatsonActivityId();

		watsonActivityCacheModel.groupId = getGroupId();

		watsonActivityCacheModel.companyId = getCompanyId();

		watsonActivityCacheModel.userId = getUserId();

		watsonActivityCacheModel.userName = getUserName();

		String userName = watsonActivityCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonActivityCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonActivityCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonActivityCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonActivityCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonActivityCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonActivityCacheModel.typeWatsonListTypeId =
			getTypeWatsonListTypeId();

		watsonActivityCacheModel.subtypeWatsonListTypeId =
			getSubtypeWatsonListTypeId();

		watsonActivityCacheModel.watsonIncidentId = getWatsonIncidentId();

		watsonActivityCacheModel.narrative = getNarrative();

		String narrative = watsonActivityCacheModel.narrative;

		if ((narrative != null) && (narrative.length() == 0)) {
			watsonActivityCacheModel.narrative = null;
		}

		Date reportDate = getReportDate();

		if (reportDate != null) {
			watsonActivityCacheModel.reportDate = reportDate.getTime();
		}
		else {
			watsonActivityCacheModel.reportDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			watsonActivityCacheModel.startDate = startDate.getTime();
		}
		else {
			watsonActivityCacheModel.startDate = Long.MIN_VALUE;
		}

		watsonActivityCacheModel.status = getStatus();

		return watsonActivityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonActivity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonActivity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonActivity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonActivity)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonActivity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonActivity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonActivity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonActivity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonActivity>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonActivityId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _typeWatsonListTypeId;
	private long _subtypeWatsonListTypeId;
	private long _watsonIncidentId;
	private String _narrative;
	private String _narrativeCurrentLanguageId;
	private Date _reportDate;
	private Date _startDate;
	private int _status;
	private WatsonActivity _escapedModel;

}