/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.watson.model.WatsonIncident;
import com.liferay.watson.model.WatsonIncidentModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonIncident service. Represents a row in the &quot;WatsonIncident&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>WatsonIncidentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonIncidentImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonIncidentImpl
 * @generated
 */
@ProviderType
public class WatsonIncidentModelImpl
	extends BaseModelImpl<WatsonIncident> implements WatsonIncidentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson incident model instance should use the <code>WatsonIncident</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonIncident";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonIncidentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"externalCaseWatsonListTypeId", Types.BIGINT},
		{"sourceWatsonListTypeId", Types.BIGINT},
		{"typeWatsonListTypeId", Types.BIGINT},
		{"subtypeWatsonListTypeId", Types.BIGINT},
		{"audienceAdultCount", Types.BIGINT},
		{"audienceChildCount", Types.BIGINT},
		{"victimAdultCount", Types.BIGINT}, {"victimChildCount", Types.BIGINT},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"externalCaseId", Types.VARCHAR}, {"reportDate", Types.TIMESTAMP},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"expenses", Types.DOUBLE}, {"incidentStatus", Types.INTEGER},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonIncidentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("externalCaseWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sourceWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subtypeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("audienceAdultCount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("audienceChildCount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("victimAdultCount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("victimChildCount", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalCaseId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reportDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expenses", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("incidentStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonIncident (watsonIncidentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,externalCaseWatsonListTypeId LONG,sourceWatsonListTypeId LONG,typeWatsonListTypeId LONG,subtypeWatsonListTypeId LONG,audienceAdultCount LONG,audienceChildCount LONG,victimAdultCount LONG,victimChildCount LONG,name VARCHAR(75) null,description STRING null,externalCaseId VARCHAR(75) null,reportDate DATE null,startDate DATE null,endDate DATE null,expenses DOUBLE,incidentStatus INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonIncident";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonIncident.watsonIncidentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonIncident.watsonIncidentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonIncident"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonIncident"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonIncident"));

	public WatsonIncidentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonIncidentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonIncidentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonIncidentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonIncident.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonIncident.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonIncident, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonIncident, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonIncident, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonIncident)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonIncident, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonIncident, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonIncident)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonIncident, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonIncident, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<WatsonIncident, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonIncident, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonIncident, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<WatsonIncident, Object>>();
		Map<String, BiConsumer<WatsonIncident, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<WatsonIncident, ?>>();

		attributeGetterFunctions.put(
			"watsonIncidentId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getWatsonIncidentId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object watsonIncidentId) {

					watsonIncident.setWatsonIncidentId((Long)watsonIncidentId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object groupId) {

					watsonIncident.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object companyId) {

					watsonIncident.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object userId) {

					watsonIncident.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object userName) {

					watsonIncident.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object createDate) {

					watsonIncident.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object modifiedDate) {

					watsonIncident.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"externalCaseWatsonListTypeId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getExternalCaseWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"externalCaseWatsonListTypeId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident,
					Object externalCaseWatsonListTypeId) {

					watsonIncident.setExternalCaseWatsonListTypeId(
						(Long)externalCaseWatsonListTypeId);
				}

			});
		attributeGetterFunctions.put(
			"sourceWatsonListTypeId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getSourceWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"sourceWatsonListTypeId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident,
					Object sourceWatsonListTypeId) {

					watsonIncident.setSourceWatsonListTypeId(
						(Long)sourceWatsonListTypeId);
				}

			});
		attributeGetterFunctions.put(
			"typeWatsonListTypeId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"typeWatsonListTypeId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident,
					Object typeWatsonListTypeId) {

					watsonIncident.setTypeWatsonListTypeId(
						(Long)typeWatsonListTypeId);
				}

			});
		attributeGetterFunctions.put(
			"subtypeWatsonListTypeId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getSubtypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"subtypeWatsonListTypeId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident,
					Object subtypeWatsonListTypeId) {

					watsonIncident.setSubtypeWatsonListTypeId(
						(Long)subtypeWatsonListTypeId);
				}

			});
		attributeGetterFunctions.put(
			"audienceAdultCount",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getAudienceAdultCount();
				}

			});
		attributeSetterBiConsumers.put(
			"audienceAdultCount",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object audienceAdultCount) {

					watsonIncident.setAudienceAdultCount(
						(Long)audienceAdultCount);
				}

			});
		attributeGetterFunctions.put(
			"audienceChildCount",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getAudienceChildCount();
				}

			});
		attributeSetterBiConsumers.put(
			"audienceChildCount",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object audienceChildCount) {

					watsonIncident.setAudienceChildCount(
						(Long)audienceChildCount);
				}

			});
		attributeGetterFunctions.put(
			"victimAdultCount",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getVictimAdultCount();
				}

			});
		attributeSetterBiConsumers.put(
			"victimAdultCount",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object victimAdultCount) {

					watsonIncident.setVictimAdultCount((Long)victimAdultCount);
				}

			});
		attributeGetterFunctions.put(
			"victimChildCount",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getVictimChildCount();
				}

			});
		attributeSetterBiConsumers.put(
			"victimChildCount",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object victimChildCount) {

					watsonIncident.setVictimChildCount((Long)victimChildCount);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(WatsonIncident watsonIncident, Object name) {
					watsonIncident.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object description) {

					watsonIncident.setDescription((String)description);
				}

			});
		attributeGetterFunctions.put(
			"externalCaseId",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getExternalCaseId();
				}

			});
		attributeSetterBiConsumers.put(
			"externalCaseId",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object externalCaseId) {

					watsonIncident.setExternalCaseId((String)externalCaseId);
				}

			});
		attributeGetterFunctions.put(
			"reportDate",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getReportDate();
				}

			});
		attributeSetterBiConsumers.put(
			"reportDate",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object reportDate) {

					watsonIncident.setReportDate((Date)reportDate);
				}

			});
		attributeGetterFunctions.put(
			"startDate",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"startDate",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object startDate) {

					watsonIncident.setStartDate((Date)startDate);
				}

			});
		attributeGetterFunctions.put(
			"endDate",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getEndDate();
				}

			});
		attributeSetterBiConsumers.put(
			"endDate",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object endDate) {

					watsonIncident.setEndDate((Date)endDate);
				}

			});
		attributeGetterFunctions.put(
			"expenses",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getExpenses();
				}

			});
		attributeSetterBiConsumers.put(
			"expenses",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object expenses) {

					watsonIncident.setExpenses((Double)expenses);
				}

			});
		attributeGetterFunctions.put(
			"incidentStatus",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getIncidentStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"incidentStatus",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object incidentStatus) {

					watsonIncident.setIncidentStatus((Integer)incidentStatus);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonIncident, Object>() {

				@Override
				public Object apply(WatsonIncident watsonIncident) {
					return watsonIncident.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonIncident, Object>() {

				@Override
				public void accept(
					WatsonIncident watsonIncident, Object status) {

					watsonIncident.setStatus((Integer)status);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonIncidentId() {
		return _watsonIncidentId;
	}

	@Override
	public void setWatsonIncidentId(long watsonIncidentId) {
		_watsonIncidentId = watsonIncidentId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getExternalCaseWatsonListTypeId() {
		return _externalCaseWatsonListTypeId;
	}

	@Override
	public void setExternalCaseWatsonListTypeId(
		long externalCaseWatsonListTypeId) {

		_externalCaseWatsonListTypeId = externalCaseWatsonListTypeId;
	}

	@Override
	public long getSourceWatsonListTypeId() {
		return _sourceWatsonListTypeId;
	}

	@Override
	public void setSourceWatsonListTypeId(long sourceWatsonListTypeId) {
		_sourceWatsonListTypeId = sourceWatsonListTypeId;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getSubtypeWatsonListTypeId() {
		return _subtypeWatsonListTypeId;
	}

	@Override
	public void setSubtypeWatsonListTypeId(long subtypeWatsonListTypeId) {
		_subtypeWatsonListTypeId = subtypeWatsonListTypeId;
	}

	@Override
	public long getAudienceAdultCount() {
		return _audienceAdultCount;
	}

	@Override
	public void setAudienceAdultCount(long audienceAdultCount) {
		_audienceAdultCount = audienceAdultCount;
	}

	@Override
	public long getAudienceChildCount() {
		return _audienceChildCount;
	}

	@Override
	public void setAudienceChildCount(long audienceChildCount) {
		_audienceChildCount = audienceChildCount;
	}

	@Override
	public long getVictimAdultCount() {
		return _victimAdultCount;
	}

	@Override
	public void setVictimAdultCount(long victimAdultCount) {
		_victimAdultCount = victimAdultCount;
	}

	@Override
	public long getVictimChildCount() {
		return _victimChildCount;
	}

	@Override
	public void setVictimChildCount(long victimChildCount) {
		_victimChildCount = victimChildCount;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getExternalCaseId() {
		if (_externalCaseId == null) {
			return "";
		}
		else {
			return _externalCaseId;
		}
	}

	@Override
	public void setExternalCaseId(String externalCaseId) {
		_externalCaseId = externalCaseId;
	}

	@Override
	public Date getReportDate() {
		return _reportDate;
	}

	@Override
	public void setReportDate(Date reportDate) {
		_reportDate = reportDate;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@Override
	public double getExpenses() {
		return _expenses;
	}

	@Override
	public void setExpenses(double expenses) {
		_expenses = expenses;
	}

	@Override
	public int getIncidentStatus() {
		return _incidentStatus;
	}

	@Override
	public void setIncidentStatus(int incidentStatus) {
		_incidentStatus = incidentStatus;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonIncident.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getDescription();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			WatsonIncident.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WatsonIncident toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WatsonIncident)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonIncidentImpl watsonIncidentImpl = new WatsonIncidentImpl();

		watsonIncidentImpl.setWatsonIncidentId(getWatsonIncidentId());
		watsonIncidentImpl.setGroupId(getGroupId());
		watsonIncidentImpl.setCompanyId(getCompanyId());
		watsonIncidentImpl.setUserId(getUserId());
		watsonIncidentImpl.setUserName(getUserName());
		watsonIncidentImpl.setCreateDate(getCreateDate());
		watsonIncidentImpl.setModifiedDate(getModifiedDate());
		watsonIncidentImpl.setExternalCaseWatsonListTypeId(
			getExternalCaseWatsonListTypeId());
		watsonIncidentImpl.setSourceWatsonListTypeId(
			getSourceWatsonListTypeId());
		watsonIncidentImpl.setTypeWatsonListTypeId(getTypeWatsonListTypeId());
		watsonIncidentImpl.setSubtypeWatsonListTypeId(
			getSubtypeWatsonListTypeId());
		watsonIncidentImpl.setAudienceAdultCount(getAudienceAdultCount());
		watsonIncidentImpl.setAudienceChildCount(getAudienceChildCount());
		watsonIncidentImpl.setVictimAdultCount(getVictimAdultCount());
		watsonIncidentImpl.setVictimChildCount(getVictimChildCount());
		watsonIncidentImpl.setName(getName());
		watsonIncidentImpl.setDescription(getDescription());
		watsonIncidentImpl.setExternalCaseId(getExternalCaseId());
		watsonIncidentImpl.setReportDate(getReportDate());
		watsonIncidentImpl.setStartDate(getStartDate());
		watsonIncidentImpl.setEndDate(getEndDate());
		watsonIncidentImpl.setExpenses(getExpenses());
		watsonIncidentImpl.setIncidentStatus(getIncidentStatus());
		watsonIncidentImpl.setStatus(getStatus());

		watsonIncidentImpl.resetOriginalValues();

		return watsonIncidentImpl;
	}

	@Override
	public int compareTo(WatsonIncident watsonIncident) {
		long primaryKey = watsonIncident.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WatsonIncident)) {
			return false;
		}

		WatsonIncident watsonIncident = (WatsonIncident)obj;

		long primaryKey = watsonIncident.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		WatsonIncidentModelImpl watsonIncidentModelImpl = this;

		watsonIncidentModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonIncident> toCacheModel() {
		WatsonIncidentCacheModel watsonIncidentCacheModel =
			new WatsonIncidentCacheModel();

		watsonIncidentCacheModel.watsonIncidentId = getWatsonIncidentId();

		watsonIncidentCacheModel.groupId = getGroupId();

		watsonIncidentCacheModel.companyId = getCompanyId();

		watsonIncidentCacheModel.userId = getUserId();

		watsonIncidentCacheModel.userName = getUserName();

		String userName = watsonIncidentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonIncidentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonIncidentCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonIncidentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonIncidentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonIncidentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonIncidentCacheModel.externalCaseWatsonListTypeId =
			getExternalCaseWatsonListTypeId();

		watsonIncidentCacheModel.sourceWatsonListTypeId =
			getSourceWatsonListTypeId();

		watsonIncidentCacheModel.typeWatsonListTypeId =
			getTypeWatsonListTypeId();

		watsonIncidentCacheModel.subtypeWatsonListTypeId =
			getSubtypeWatsonListTypeId();

		watsonIncidentCacheModel.audienceAdultCount = getAudienceAdultCount();

		watsonIncidentCacheModel.audienceChildCount = getAudienceChildCount();

		watsonIncidentCacheModel.victimAdultCount = getVictimAdultCount();

		watsonIncidentCacheModel.victimChildCount = getVictimChildCount();

		watsonIncidentCacheModel.name = getName();

		String name = watsonIncidentCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			watsonIncidentCacheModel.name = null;
		}

		watsonIncidentCacheModel.description = getDescription();

		String description = watsonIncidentCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			watsonIncidentCacheModel.description = null;
		}

		watsonIncidentCacheModel.externalCaseId = getExternalCaseId();

		String externalCaseId = watsonIncidentCacheModel.externalCaseId;

		if ((externalCaseId != null) && (externalCaseId.length() == 0)) {
			watsonIncidentCacheModel.externalCaseId = null;
		}

		Date reportDate = getReportDate();

		if (reportDate != null) {
			watsonIncidentCacheModel.reportDate = reportDate.getTime();
		}
		else {
			watsonIncidentCacheModel.reportDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			watsonIncidentCacheModel.startDate = startDate.getTime();
		}
		else {
			watsonIncidentCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			watsonIncidentCacheModel.endDate = endDate.getTime();
		}
		else {
			watsonIncidentCacheModel.endDate = Long.MIN_VALUE;
		}

		watsonIncidentCacheModel.expenses = getExpenses();

		watsonIncidentCacheModel.incidentStatus = getIncidentStatus();

		watsonIncidentCacheModel.status = getStatus();

		return watsonIncidentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonIncident, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonIncident, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonIncident, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonIncident)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonIncident, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonIncident, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonIncident, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonIncident)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		WatsonIncident.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		WatsonIncident.class, ModelWrapper.class
	};

	private long _watsonIncidentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _externalCaseWatsonListTypeId;
	private long _sourceWatsonListTypeId;
	private long _typeWatsonListTypeId;
	private long _subtypeWatsonListTypeId;
	private long _audienceAdultCount;
	private long _audienceChildCount;
	private long _victimAdultCount;
	private long _victimChildCount;
	private String _name;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _externalCaseId;
	private Date _reportDate;
	private Date _startDate;
	private Date _endDate;
	private double _expenses;
	private int _incidentStatus;
	private int _status;
	private WatsonIncident _escapedModel;

}