/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.watson.model.WatsonAddress;
import com.liferay.watson.model.WatsonAddressModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonAddress service. Represents a row in the &quot;WatsonAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonAddressModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonAddressImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonAddressImpl
 * @generated
 */
public class WatsonAddressModelImpl
	extends BaseModelImpl<WatsonAddress> implements WatsonAddressModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson address model instance should use the <code>WatsonAddress</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonAddress";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonAddressId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"countryId", Types.BIGINT},
		{"districtWatsonListTypeId", Types.BIGINT},
		{"originalWatsonAddressId", Types.BIGINT},
		{"provinceWatsonListTypeId", Types.BIGINT},
		{"subDistrictWatsonListTypeId", Types.BIGINT},
		{"typeWatsonListTypeId", Types.BIGINT},
		{"watsonIncidentId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"postalCode", Types.VARCHAR}, {"region", Types.VARCHAR},
		{"street", Types.VARCHAR}, {"number_", Types.VARCHAR},
		{"building", Types.VARCHAR}, {"floor", Types.VARCHAR},
		{"room", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"imagePayload", Types.CLOB}, {"otherType", Types.VARCHAR},
		{"lastSeenDate", Types.TIMESTAMP}, {"latitude", Types.DOUBLE},
		{"longitude", Types.DOUBLE}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonAddressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("countryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("districtWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("originalWatsonAddressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("provinceWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subDistrictWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonIncidentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postalCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("region", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("street", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("number_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("building", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("floor", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("room", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imagePayload", Types.CLOB);
		TABLE_COLUMNS_MAP.put("otherType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastSeenDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("latitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("longitude", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonAddress (watsonAddressId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,countryId LONG,districtWatsonListTypeId LONG,originalWatsonAddressId LONG,provinceWatsonListTypeId LONG,subDistrictWatsonListTypeId LONG,typeWatsonListTypeId LONG,watsonIncidentId LONG,name STRING null,postalCode VARCHAR(75) null,region VARCHAR(75) null,street VARCHAR(75) null,number_ VARCHAR(75) null,building STRING null,floor VARCHAR(75) null,room VARCHAR(75) null,description STRING null,imagePayload TEXT null,otherType VARCHAR(75) null,lastSeenDate DATE null,latitude DOUBLE,longitude DOUBLE,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonAddress";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonAddress.watsonAddressId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonAddress.watsonAddressId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonAddress"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonAddress"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonAddress"));

	public WatsonAddressModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonAddressId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonAddressId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonAddressId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonAddress.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonAddress.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonAddress, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonAddress, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonAddress, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonAddress)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonAddress, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonAddress, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonAddress)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonAddress, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonAddress, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonAddress>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonAddress.class.getClassLoader(), WatsonAddress.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonAddress> constructor =
				(Constructor<WatsonAddress>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonAddress, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonAddress, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonAddress, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<WatsonAddress, Object>>();
		Map<String, BiConsumer<WatsonAddress, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<WatsonAddress, ?>>();

		attributeGetterFunctions.put(
			"watsonAddressId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getWatsonAddressId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonAddressId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object watsonAddressIdObject) {

					watsonAddress.setWatsonAddressId(
						(Long)watsonAddressIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object groupIdObject) {

					watsonAddress.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object companyIdObject) {

					watsonAddress.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object userIdObject) {

					watsonAddress.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object userNameObject) {

					watsonAddress.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object createDateObject) {

					watsonAddress.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object modifiedDateObject) {

					watsonAddress.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"countryId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getCountryId();
				}

			});
		attributeSetterBiConsumers.put(
			"countryId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object countryIdObject) {

					watsonAddress.setCountryId((Long)countryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"districtWatsonListTypeId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getDistrictWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"districtWatsonListTypeId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress,
					Object districtWatsonListTypeIdObject) {

					watsonAddress.setDistrictWatsonListTypeId(
						(Long)districtWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"originalWatsonAddressId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getOriginalWatsonAddressId();
				}

			});
		attributeSetterBiConsumers.put(
			"originalWatsonAddressId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress,
					Object originalWatsonAddressIdObject) {

					watsonAddress.setOriginalWatsonAddressId(
						(Long)originalWatsonAddressIdObject);
				}

			});
		attributeGetterFunctions.put(
			"provinceWatsonListTypeId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getProvinceWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"provinceWatsonListTypeId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress,
					Object provinceWatsonListTypeIdObject) {

					watsonAddress.setProvinceWatsonListTypeId(
						(Long)provinceWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"subDistrictWatsonListTypeId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getSubDistrictWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"subDistrictWatsonListTypeId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress,
					Object subDistrictWatsonListTypeIdObject) {

					watsonAddress.setSubDistrictWatsonListTypeId(
						(Long)subDistrictWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"typeWatsonListTypeId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"typeWatsonListTypeId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress,
					Object typeWatsonListTypeIdObject) {

					watsonAddress.setTypeWatsonListTypeId(
						(Long)typeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonIncidentId",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getWatsonIncidentId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonIncidentId",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress,
					Object watsonIncidentIdObject) {

					watsonAddress.setWatsonIncidentId(
						(Long)watsonIncidentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object nameObject) {

					watsonAddress.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"postalCode",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getPostalCode();
				}

			});
		attributeSetterBiConsumers.put(
			"postalCode",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object postalCodeObject) {

					watsonAddress.setPostalCode((String)postalCodeObject);
				}

			});
		attributeGetterFunctions.put(
			"region",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getRegion();
				}

			});
		attributeSetterBiConsumers.put(
			"region",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object regionObject) {

					watsonAddress.setRegion((String)regionObject);
				}

			});
		attributeGetterFunctions.put(
			"street",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getStreet();
				}

			});
		attributeSetterBiConsumers.put(
			"street",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object streetObject) {

					watsonAddress.setStreet((String)streetObject);
				}

			});
		attributeGetterFunctions.put(
			"number",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getNumber();
				}

			});
		attributeSetterBiConsumers.put(
			"number",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object numberObject) {

					watsonAddress.setNumber((String)numberObject);
				}

			});
		attributeGetterFunctions.put(
			"building",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getBuilding();
				}

			});
		attributeSetterBiConsumers.put(
			"building",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object buildingObject) {

					watsonAddress.setBuilding((String)buildingObject);
				}

			});
		attributeGetterFunctions.put(
			"floor",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getFloor();
				}

			});
		attributeSetterBiConsumers.put(
			"floor",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object floorObject) {

					watsonAddress.setFloor((String)floorObject);
				}

			});
		attributeGetterFunctions.put(
			"room",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getRoom();
				}

			});
		attributeSetterBiConsumers.put(
			"room",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object roomObject) {

					watsonAddress.setRoom((String)roomObject);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object descriptionObject) {

					watsonAddress.setDescription((String)descriptionObject);
				}

			});
		attributeGetterFunctions.put(
			"imagePayload",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getImagePayload();
				}

			});
		attributeSetterBiConsumers.put(
			"imagePayload",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object imagePayloadObject) {

					watsonAddress.setImagePayload((String)imagePayloadObject);
				}

			});
		attributeGetterFunctions.put(
			"otherType",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getOtherType();
				}

			});
		attributeSetterBiConsumers.put(
			"otherType",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object otherTypeObject) {

					watsonAddress.setOtherType((String)otherTypeObject);
				}

			});
		attributeGetterFunctions.put(
			"lastSeenDate",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getLastSeenDate();
				}

			});
		attributeSetterBiConsumers.put(
			"lastSeenDate",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object lastSeenDateObject) {

					watsonAddress.setLastSeenDate((Date)lastSeenDateObject);
				}

			});
		attributeGetterFunctions.put(
			"latitude",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getLatitude();
				}

			});
		attributeSetterBiConsumers.put(
			"latitude",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object latitudeObject) {

					watsonAddress.setLatitude((Double)latitudeObject);
				}

			});
		attributeGetterFunctions.put(
			"longitude",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getLongitude();
				}

			});
		attributeSetterBiConsumers.put(
			"longitude",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object longitudeObject) {

					watsonAddress.setLongitude((Double)longitudeObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonAddress, Object>() {

				@Override
				public Object apply(WatsonAddress watsonAddress) {
					return watsonAddress.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonAddress, Object>() {

				@Override
				public void accept(
					WatsonAddress watsonAddress, Object statusObject) {

					watsonAddress.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonAddressId() {
		return _watsonAddressId;
	}

	@Override
	public void setWatsonAddressId(long watsonAddressId) {
		_watsonAddressId = watsonAddressId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCountryId() {
		return _countryId;
	}

	@Override
	public void setCountryId(long countryId) {
		_countryId = countryId;
	}

	@Override
	public long getDistrictWatsonListTypeId() {
		return _districtWatsonListTypeId;
	}

	@Override
	public void setDistrictWatsonListTypeId(long districtWatsonListTypeId) {
		_districtWatsonListTypeId = districtWatsonListTypeId;
	}

	@Override
	public long getOriginalWatsonAddressId() {
		return _originalWatsonAddressId;
	}

	@Override
	public void setOriginalWatsonAddressId(long originalWatsonAddressId) {
		_originalWatsonAddressId = originalWatsonAddressId;
	}

	@Override
	public long getProvinceWatsonListTypeId() {
		return _provinceWatsonListTypeId;
	}

	@Override
	public void setProvinceWatsonListTypeId(long provinceWatsonListTypeId) {
		_provinceWatsonListTypeId = provinceWatsonListTypeId;
	}

	@Override
	public long getSubDistrictWatsonListTypeId() {
		return _subDistrictWatsonListTypeId;
	}

	@Override
	public void setSubDistrictWatsonListTypeId(
		long subDistrictWatsonListTypeId) {

		_subDistrictWatsonListTypeId = subDistrictWatsonListTypeId;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getWatsonIncidentId() {
		return _watsonIncidentId;
	}

	@Override
	public void setWatsonIncidentId(long watsonIncidentId) {
		_watsonIncidentId = watsonIncidentId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getPostalCode() {
		if (_postalCode == null) {
			return "";
		}
		else {
			return _postalCode;
		}
	}

	@Override
	public void setPostalCode(String postalCode) {
		_postalCode = postalCode;
	}

	@Override
	public String getRegion() {
		if (_region == null) {
			return "";
		}
		else {
			return _region;
		}
	}

	@Override
	public void setRegion(String region) {
		_region = region;
	}

	@Override
	public String getStreet() {
		if (_street == null) {
			return "";
		}
		else {
			return _street;
		}
	}

	@Override
	public void setStreet(String street) {
		_street = street;
	}

	@Override
	public String getNumber() {
		if (_number == null) {
			return "";
		}
		else {
			return _number;
		}
	}

	@Override
	public void setNumber(String number) {
		_number = number;
	}

	@Override
	public String getBuilding() {
		if (_building == null) {
			return "";
		}
		else {
			return _building;
		}
	}

	@Override
	public String getBuilding(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBuilding(languageId);
	}

	@Override
	public String getBuilding(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getBuilding(languageId, useDefault);
	}

	@Override
	public String getBuilding(String languageId) {
		return LocalizationUtil.getLocalization(getBuilding(), languageId);
	}

	@Override
	public String getBuilding(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getBuilding(), languageId, useDefault);
	}

	@Override
	public String getBuildingCurrentLanguageId() {
		return _buildingCurrentLanguageId;
	}

	@JSON
	@Override
	public String getBuildingCurrentValue() {
		Locale locale = getLocale(_buildingCurrentLanguageId);

		return getBuilding(locale);
	}

	@Override
	public Map<Locale, String> getBuildingMap() {
		return LocalizationUtil.getLocalizationMap(getBuilding());
	}

	@Override
	public void setBuilding(String building) {
		_building = building;
	}

	@Override
	public void setBuilding(String building, Locale locale) {
		setBuilding(building, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setBuilding(
		String building, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(building)) {
			setBuilding(
				LocalizationUtil.updateLocalization(
					getBuilding(), "Building", building, languageId,
					defaultLanguageId));
		}
		else {
			setBuilding(
				LocalizationUtil.removeLocalization(
					getBuilding(), "Building", languageId));
		}
	}

	@Override
	public void setBuildingCurrentLanguageId(String languageId) {
		_buildingCurrentLanguageId = languageId;
	}

	@Override
	public void setBuildingMap(Map<Locale, String> buildingMap) {
		setBuildingMap(buildingMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setBuildingMap(
		Map<Locale, String> buildingMap, Locale defaultLocale) {

		if (buildingMap == null) {
			return;
		}

		setBuilding(
			LocalizationUtil.updateLocalization(
				buildingMap, getBuilding(), "Building",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getFloor() {
		if (_floor == null) {
			return "";
		}
		else {
			return _floor;
		}
	}

	@Override
	public void setFloor(String floor) {
		_floor = floor;
	}

	@Override
	public String getRoom() {
		if (_room == null) {
			return "";
		}
		else {
			return _room;
		}
	}

	@Override
	public void setRoom(String room) {
		_room = room;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getImagePayload() {
		if (_imagePayload == null) {
			return "";
		}
		else {
			return _imagePayload;
		}
	}

	@Override
	public void setImagePayload(String imagePayload) {
		_imagePayload = imagePayload;
	}

	@Override
	public String getOtherType() {
		if (_otherType == null) {
			return "";
		}
		else {
			return _otherType;
		}
	}

	@Override
	public void setOtherType(String otherType) {
		_otherType = otherType;
	}

	@Override
	public Date getLastSeenDate() {
		return _lastSeenDate;
	}

	@Override
	public void setLastSeenDate(Date lastSeenDate) {
		_lastSeenDate = lastSeenDate;
	}

	@Override
	public double getLatitude() {
		return _latitude;
	}

	@Override
	public void setLatitude(double latitude) {
		_latitude = latitude;
	}

	@Override
	public double getLongitude() {
		return _longitude;
	}

	@Override
	public void setLongitude(double longitude) {
		_longitude = longitude;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonAddress.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> buildingMap = getBuildingMap();

		for (Map.Entry<Locale, String> entry : buildingMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			WatsonAddress.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}

		String building = getBuilding(defaultLocale);

		if (Validator.isNull(building)) {
			setBuilding(getBuilding(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setBuilding(
				getBuilding(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WatsonAddress toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonAddress>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonAddressImpl watsonAddressImpl = new WatsonAddressImpl();

		watsonAddressImpl.setWatsonAddressId(getWatsonAddressId());
		watsonAddressImpl.setGroupId(getGroupId());
		watsonAddressImpl.setCompanyId(getCompanyId());
		watsonAddressImpl.setUserId(getUserId());
		watsonAddressImpl.setUserName(getUserName());
		watsonAddressImpl.setCreateDate(getCreateDate());
		watsonAddressImpl.setModifiedDate(getModifiedDate());
		watsonAddressImpl.setCountryId(getCountryId());
		watsonAddressImpl.setDistrictWatsonListTypeId(
			getDistrictWatsonListTypeId());
		watsonAddressImpl.setOriginalWatsonAddressId(
			getOriginalWatsonAddressId());
		watsonAddressImpl.setProvinceWatsonListTypeId(
			getProvinceWatsonListTypeId());
		watsonAddressImpl.setSubDistrictWatsonListTypeId(
			getSubDistrictWatsonListTypeId());
		watsonAddressImpl.setTypeWatsonListTypeId(getTypeWatsonListTypeId());
		watsonAddressImpl.setWatsonIncidentId(getWatsonIncidentId());
		watsonAddressImpl.setName(getName());
		watsonAddressImpl.setPostalCode(getPostalCode());
		watsonAddressImpl.setRegion(getRegion());
		watsonAddressImpl.setStreet(getStreet());
		watsonAddressImpl.setNumber(getNumber());
		watsonAddressImpl.setBuilding(getBuilding());
		watsonAddressImpl.setFloor(getFloor());
		watsonAddressImpl.setRoom(getRoom());
		watsonAddressImpl.setDescription(getDescription());
		watsonAddressImpl.setImagePayload(getImagePayload());
		watsonAddressImpl.setOtherType(getOtherType());
		watsonAddressImpl.setLastSeenDate(getLastSeenDate());
		watsonAddressImpl.setLatitude(getLatitude());
		watsonAddressImpl.setLongitude(getLongitude());
		watsonAddressImpl.setStatus(getStatus());

		watsonAddressImpl.resetOriginalValues();

		return watsonAddressImpl;
	}

	@Override
	public int compareTo(WatsonAddress watsonAddress) {
		long primaryKey = watsonAddress.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonAddress)) {
			return false;
		}

		WatsonAddress watsonAddress = (WatsonAddress)object;

		long primaryKey = watsonAddress.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonAddress> toCacheModel() {
		WatsonAddressCacheModel watsonAddressCacheModel =
			new WatsonAddressCacheModel();

		watsonAddressCacheModel.watsonAddressId = getWatsonAddressId();

		watsonAddressCacheModel.groupId = getGroupId();

		watsonAddressCacheModel.companyId = getCompanyId();

		watsonAddressCacheModel.userId = getUserId();

		watsonAddressCacheModel.userName = getUserName();

		String userName = watsonAddressCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonAddressCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonAddressCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonAddressCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonAddressCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonAddressCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonAddressCacheModel.countryId = getCountryId();

		watsonAddressCacheModel.districtWatsonListTypeId =
			getDistrictWatsonListTypeId();

		watsonAddressCacheModel.originalWatsonAddressId =
			getOriginalWatsonAddressId();

		watsonAddressCacheModel.provinceWatsonListTypeId =
			getProvinceWatsonListTypeId();

		watsonAddressCacheModel.subDistrictWatsonListTypeId =
			getSubDistrictWatsonListTypeId();

		watsonAddressCacheModel.typeWatsonListTypeId =
			getTypeWatsonListTypeId();

		watsonAddressCacheModel.watsonIncidentId = getWatsonIncidentId();

		watsonAddressCacheModel.name = getName();

		String name = watsonAddressCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			watsonAddressCacheModel.name = null;
		}

		watsonAddressCacheModel.postalCode = getPostalCode();

		String postalCode = watsonAddressCacheModel.postalCode;

		if ((postalCode != null) && (postalCode.length() == 0)) {
			watsonAddressCacheModel.postalCode = null;
		}

		watsonAddressCacheModel.region = getRegion();

		String region = watsonAddressCacheModel.region;

		if ((region != null) && (region.length() == 0)) {
			watsonAddressCacheModel.region = null;
		}

		watsonAddressCacheModel.street = getStreet();

		String street = watsonAddressCacheModel.street;

		if ((street != null) && (street.length() == 0)) {
			watsonAddressCacheModel.street = null;
		}

		watsonAddressCacheModel.number = getNumber();

		String number = watsonAddressCacheModel.number;

		if ((number != null) && (number.length() == 0)) {
			watsonAddressCacheModel.number = null;
		}

		watsonAddressCacheModel.building = getBuilding();

		String building = watsonAddressCacheModel.building;

		if ((building != null) && (building.length() == 0)) {
			watsonAddressCacheModel.building = null;
		}

		watsonAddressCacheModel.floor = getFloor();

		String floor = watsonAddressCacheModel.floor;

		if ((floor != null) && (floor.length() == 0)) {
			watsonAddressCacheModel.floor = null;
		}

		watsonAddressCacheModel.room = getRoom();

		String room = watsonAddressCacheModel.room;

		if ((room != null) && (room.length() == 0)) {
			watsonAddressCacheModel.room = null;
		}

		watsonAddressCacheModel.description = getDescription();

		String description = watsonAddressCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			watsonAddressCacheModel.description = null;
		}

		watsonAddressCacheModel.imagePayload = getImagePayload();

		String imagePayload = watsonAddressCacheModel.imagePayload;

		if ((imagePayload != null) && (imagePayload.length() == 0)) {
			watsonAddressCacheModel.imagePayload = null;
		}

		watsonAddressCacheModel.otherType = getOtherType();

		String otherType = watsonAddressCacheModel.otherType;

		if ((otherType != null) && (otherType.length() == 0)) {
			watsonAddressCacheModel.otherType = null;
		}

		Date lastSeenDate = getLastSeenDate();

		if (lastSeenDate != null) {
			watsonAddressCacheModel.lastSeenDate = lastSeenDate.getTime();
		}
		else {
			watsonAddressCacheModel.lastSeenDate = Long.MIN_VALUE;
		}

		watsonAddressCacheModel.latitude = getLatitude();

		watsonAddressCacheModel.longitude = getLongitude();

		watsonAddressCacheModel.status = getStatus();

		return watsonAddressCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonAddress, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonAddress, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonAddress, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonAddress)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonAddress, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonAddress, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonAddress, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonAddress)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonAddress>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonAddressId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _countryId;
	private long _districtWatsonListTypeId;
	private long _originalWatsonAddressId;
	private long _provinceWatsonListTypeId;
	private long _subDistrictWatsonListTypeId;
	private long _typeWatsonListTypeId;
	private long _watsonIncidentId;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _postalCode;
	private String _region;
	private String _street;
	private String _number;
	private String _building;
	private String _buildingCurrentLanguageId;
	private String _floor;
	private String _room;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _imagePayload;
	private String _otherType;
	private Date _lastSeenDate;
	private double _latitude;
	private double _longitude;
	private int _status;
	private WatsonAddress _escapedModel;

}