/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.watson.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.watson.model.WatsonDocument;
import com.liferay.watson.model.WatsonDocumentModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the WatsonDocument service. Represents a row in the &quot;WatsonDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WatsonDocumentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WatsonDocumentImpl}.
 * </p>
 *
 * @author Steven Smith
 * @see WatsonDocumentImpl
 * @generated
 */
public class WatsonDocumentModelImpl
	extends BaseModelImpl<WatsonDocument> implements WatsonDocumentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a watson document model instance should use the <code>WatsonDocument</code> interface instead.
	 */
	public static final String TABLE_NAME = "WatsonDocument";

	public static final Object[][] TABLE_COLUMNS = {
		{"watsonDocumentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"parentTypeWatsonListTypeId", Types.BIGINT},
		{"subtypeWatsonListTypeId", Types.BIGINT},
		{"typeWatsonListTypeId", Types.BIGINT}, {"watsonChildId", Types.BIGINT},
		{"originalDocument", Types.BOOLEAN}, {"receivedDate", Types.TIMESTAMP},
		{"imagePayload", Types.CLOB}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("watsonDocumentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentTypeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("subtypeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeWatsonListTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("watsonChildId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("originalDocument", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("receivedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imagePayload", Types.CLOB);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table WatsonDocument (watsonDocumentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,parentTypeWatsonListTypeId LONG,subtypeWatsonListTypeId LONG,typeWatsonListTypeId LONG,watsonChildId LONG,originalDocument BOOLEAN,receivedDate DATE null,imagePayload TEXT null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table WatsonDocument";

	public static final String ORDER_BY_JPQL =
		" ORDER BY watsonDocument.watsonDocumentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY WatsonDocument.watsonDocumentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.watson.model.WatsonDocument"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.watson.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.watson.model.WatsonDocument"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.watson.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.watson.model.WatsonDocument"));

	public WatsonDocumentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _watsonDocumentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWatsonDocumentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _watsonDocumentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WatsonDocument.class;
	}

	@Override
	public String getModelClassName() {
		return WatsonDocument.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<WatsonDocument, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<WatsonDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonDocument, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((WatsonDocument)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<WatsonDocument, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<WatsonDocument, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(WatsonDocument)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<WatsonDocument, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<WatsonDocument, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, WatsonDocument>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			WatsonDocument.class.getClassLoader(), WatsonDocument.class,
			ModelWrapper.class);

		try {
			Constructor<WatsonDocument> constructor =
				(Constructor<WatsonDocument>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<WatsonDocument, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<WatsonDocument, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<WatsonDocument, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<WatsonDocument, Object>>();
		Map<String, BiConsumer<WatsonDocument, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<WatsonDocument, ?>>();

		attributeGetterFunctions.put(
			"watsonDocumentId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getWatsonDocumentId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonDocumentId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument,
					Object watsonDocumentIdObject) {

					watsonDocument.setWatsonDocumentId(
						(Long)watsonDocumentIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object groupIdObject) {

					watsonDocument.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object companyIdObject) {

					watsonDocument.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object userIdObject) {

					watsonDocument.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object userNameObject) {

					watsonDocument.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object createDateObject) {

					watsonDocument.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object modifiedDateObject) {

					watsonDocument.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"parentTypeWatsonListTypeId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getParentTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"parentTypeWatsonListTypeId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument,
					Object parentTypeWatsonListTypeIdObject) {

					watsonDocument.setParentTypeWatsonListTypeId(
						(Long)parentTypeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"subtypeWatsonListTypeId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getSubtypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"subtypeWatsonListTypeId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument,
					Object subtypeWatsonListTypeIdObject) {

					watsonDocument.setSubtypeWatsonListTypeId(
						(Long)subtypeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"typeWatsonListTypeId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getTypeWatsonListTypeId();
				}

			});
		attributeSetterBiConsumers.put(
			"typeWatsonListTypeId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument,
					Object typeWatsonListTypeIdObject) {

					watsonDocument.setTypeWatsonListTypeId(
						(Long)typeWatsonListTypeIdObject);
				}

			});
		attributeGetterFunctions.put(
			"watsonChildId",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getWatsonChildId();
				}

			});
		attributeSetterBiConsumers.put(
			"watsonChildId",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object watsonChildIdObject) {

					watsonDocument.setWatsonChildId((Long)watsonChildIdObject);
				}

			});
		attributeGetterFunctions.put(
			"originalDocument",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getOriginalDocument();
				}

			});
		attributeSetterBiConsumers.put(
			"originalDocument",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument,
					Object originalDocumentObject) {

					watsonDocument.setOriginalDocument(
						(Boolean)originalDocumentObject);
				}

			});
		attributeGetterFunctions.put(
			"receivedDate",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getReceivedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"receivedDate",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object receivedDateObject) {

					watsonDocument.setReceivedDate((Date)receivedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"imagePayload",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getImagePayload();
				}

			});
		attributeSetterBiConsumers.put(
			"imagePayload",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object imagePayloadObject) {

					watsonDocument.setImagePayload((String)imagePayloadObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<WatsonDocument, Object>() {

				@Override
				public Object apply(WatsonDocument watsonDocument) {
					return watsonDocument.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<WatsonDocument, Object>() {

				@Override
				public void accept(
					WatsonDocument watsonDocument, Object statusObject) {

					watsonDocument.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getWatsonDocumentId() {
		return _watsonDocumentId;
	}

	@Override
	public void setWatsonDocumentId(long watsonDocumentId) {
		_watsonDocumentId = watsonDocumentId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getParentTypeWatsonListTypeId() {
		return _parentTypeWatsonListTypeId;
	}

	@Override
	public void setParentTypeWatsonListTypeId(long parentTypeWatsonListTypeId) {
		_parentTypeWatsonListTypeId = parentTypeWatsonListTypeId;
	}

	@Override
	public long getSubtypeWatsonListTypeId() {
		return _subtypeWatsonListTypeId;
	}

	@Override
	public void setSubtypeWatsonListTypeId(long subtypeWatsonListTypeId) {
		_subtypeWatsonListTypeId = subtypeWatsonListTypeId;
	}

	@Override
	public long getTypeWatsonListTypeId() {
		return _typeWatsonListTypeId;
	}

	@Override
	public void setTypeWatsonListTypeId(long typeWatsonListTypeId) {
		_typeWatsonListTypeId = typeWatsonListTypeId;
	}

	@Override
	public long getWatsonChildId() {
		return _watsonChildId;
	}

	@Override
	public void setWatsonChildId(long watsonChildId) {
		_watsonChildId = watsonChildId;
	}

	@Override
	public boolean getOriginalDocument() {
		return _originalDocument;
	}

	@Override
	public boolean isOriginalDocument() {
		return _originalDocument;
	}

	@Override
	public void setOriginalDocument(boolean originalDocument) {
		_originalDocument = originalDocument;
	}

	@Override
	public Date getReceivedDate() {
		return _receivedDate;
	}

	@Override
	public void setReceivedDate(Date receivedDate) {
		_receivedDate = receivedDate;
	}

	@Override
	public String getImagePayload() {
		if (_imagePayload == null) {
			return "";
		}
		else {
			return _imagePayload;
		}
	}

	@Override
	public void setImagePayload(String imagePayload) {
		_imagePayload = imagePayload;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), WatsonDocument.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public WatsonDocument toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, WatsonDocument>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WatsonDocumentImpl watsonDocumentImpl = new WatsonDocumentImpl();

		watsonDocumentImpl.setWatsonDocumentId(getWatsonDocumentId());
		watsonDocumentImpl.setGroupId(getGroupId());
		watsonDocumentImpl.setCompanyId(getCompanyId());
		watsonDocumentImpl.setUserId(getUserId());
		watsonDocumentImpl.setUserName(getUserName());
		watsonDocumentImpl.setCreateDate(getCreateDate());
		watsonDocumentImpl.setModifiedDate(getModifiedDate());
		watsonDocumentImpl.setParentTypeWatsonListTypeId(
			getParentTypeWatsonListTypeId());
		watsonDocumentImpl.setSubtypeWatsonListTypeId(
			getSubtypeWatsonListTypeId());
		watsonDocumentImpl.setTypeWatsonListTypeId(getTypeWatsonListTypeId());
		watsonDocumentImpl.setWatsonChildId(getWatsonChildId());
		watsonDocumentImpl.setOriginalDocument(isOriginalDocument());
		watsonDocumentImpl.setReceivedDate(getReceivedDate());
		watsonDocumentImpl.setImagePayload(getImagePayload());
		watsonDocumentImpl.setStatus(getStatus());

		watsonDocumentImpl.resetOriginalValues();

		return watsonDocumentImpl;
	}

	@Override
	public int compareTo(WatsonDocument watsonDocument) {
		long primaryKey = watsonDocument.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof WatsonDocument)) {
			return false;
		}

		WatsonDocument watsonDocument = (WatsonDocument)object;

		long primaryKey = watsonDocument.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<WatsonDocument> toCacheModel() {
		WatsonDocumentCacheModel watsonDocumentCacheModel =
			new WatsonDocumentCacheModel();

		watsonDocumentCacheModel.watsonDocumentId = getWatsonDocumentId();

		watsonDocumentCacheModel.groupId = getGroupId();

		watsonDocumentCacheModel.companyId = getCompanyId();

		watsonDocumentCacheModel.userId = getUserId();

		watsonDocumentCacheModel.userName = getUserName();

		String userName = watsonDocumentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			watsonDocumentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			watsonDocumentCacheModel.createDate = createDate.getTime();
		}
		else {
			watsonDocumentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			watsonDocumentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			watsonDocumentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		watsonDocumentCacheModel.parentTypeWatsonListTypeId =
			getParentTypeWatsonListTypeId();

		watsonDocumentCacheModel.subtypeWatsonListTypeId =
			getSubtypeWatsonListTypeId();

		watsonDocumentCacheModel.typeWatsonListTypeId =
			getTypeWatsonListTypeId();

		watsonDocumentCacheModel.watsonChildId = getWatsonChildId();

		watsonDocumentCacheModel.originalDocument = isOriginalDocument();

		Date receivedDate = getReceivedDate();

		if (receivedDate != null) {
			watsonDocumentCacheModel.receivedDate = receivedDate.getTime();
		}
		else {
			watsonDocumentCacheModel.receivedDate = Long.MIN_VALUE;
		}

		watsonDocumentCacheModel.imagePayload = getImagePayload();

		String imagePayload = watsonDocumentCacheModel.imagePayload;

		if ((imagePayload != null) && (imagePayload.length() == 0)) {
			watsonDocumentCacheModel.imagePayload = null;
		}

		watsonDocumentCacheModel.status = getStatus();

		return watsonDocumentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<WatsonDocument, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<WatsonDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonDocument, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((WatsonDocument)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<WatsonDocument, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<WatsonDocument, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<WatsonDocument, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((WatsonDocument)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, WatsonDocument>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _watsonDocumentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _parentTypeWatsonListTypeId;
	private long _subtypeWatsonListTypeId;
	private long _typeWatsonListTypeId;
	private long _watsonChildId;
	private boolean _originalDocument;
	private Date _receivedDate;
	private String _imagePayload;
	private int _status;
	private WatsonDocument _escapedModel;

}