/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.customer.zendesk.documentation.sync.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticle;
import com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticleModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the ZendeskArticle service. Represents a row in the &quot;OSBCustomer_ZendeskArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ZendeskArticleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ZendeskArticleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ZendeskArticleImpl
 * @see ZendeskArticle
 * @see ZendeskArticleModel
 * @generated
 */
@ProviderType
public class ZendeskArticleModelImpl extends BaseModelImpl<ZendeskArticle>
	implements ZendeskArticleModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a zendesk article model instance should use the {@link ZendeskArticle} interface instead.
	 */
	public static final String TABLE_NAME = "OSBCustomer_ZendeskArticle";
	public static final Object[][] TABLE_COLUMNS = {
			{ "zendeskArticleId", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "zendeskCategoryId", Types.BIGINT },
			{ "zendeskSectionId", Types.BIGINT },
			{ "documentationKey", Types.VARCHAR },
			{ "documentationOriginalURL", Types.VARCHAR },
			{ "previousArticleDocumentationKey", Types.VARCHAR },
			{ "nextArticleDocumentationKey", Types.VARCHAR },
			{ "remoteId", Types.BIGINT },
			{ "remoteHtmlURL", Types.VARCHAR },
			{ "remoteTitle", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("zendeskArticleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("zendeskCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("zendeskSectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentationKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("documentationOriginalURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("previousArticleDocumentationKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nextArticleDocumentationKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("remoteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remoteHtmlURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("remoteTitle", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OSBCustomer_ZendeskArticle (zendeskArticleId LONG not null primary key,modifiedDate DATE null,zendeskCategoryId LONG,zendeskSectionId LONG,documentationKey VARCHAR(150) null,documentationOriginalURL VARCHAR(255) null,previousArticleDocumentationKey VARCHAR(75) null,nextArticleDocumentationKey VARCHAR(75) null,remoteId LONG,remoteHtmlURL STRING null,remoteTitle STRING null)";
	public static final String TABLE_SQL_DROP = "drop table OSBCustomer_ZendeskArticle";
	public static final String ORDER_BY_JPQL = " ORDER BY zendeskArticle.zendeskArticleId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSBCustomer_ZendeskArticle.zendeskArticleId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticle"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticle"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticle"),
			true);
	public static final long DOCUMENTATIONKEY_COLUMN_BITMASK = 1L;
	public static final long DOCUMENTATIONORIGINALURL_COLUMN_BITMASK = 2L;
	public static final long ZENDESKCATEGORYID_COLUMN_BITMASK = 4L;
	public static final long ZENDESKSECTIONID_COLUMN_BITMASK = 8L;
	public static final long ZENDESKARTICLEID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticle"));

	public ZendeskArticleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _zendeskArticleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setZendeskArticleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _zendeskArticleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ZendeskArticle.class;
	}

	@Override
	public String getModelClassName() {
		return ZendeskArticle.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("zendeskArticleId", getZendeskArticleId());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("zendeskCategoryId", getZendeskCategoryId());
		attributes.put("zendeskSectionId", getZendeskSectionId());
		attributes.put("documentationKey", getDocumentationKey());
		attributes.put("documentationOriginalURL", getDocumentationOriginalURL());
		attributes.put("previousArticleDocumentationKey",
			getPreviousArticleDocumentationKey());
		attributes.put("nextArticleDocumentationKey",
			getNextArticleDocumentationKey());
		attributes.put("remoteId", getRemoteId());
		attributes.put("remoteHtmlURL", getRemoteHtmlURL());
		attributes.put("remoteTitle", getRemoteTitle());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long zendeskArticleId = (Long)attributes.get("zendeskArticleId");

		if (zendeskArticleId != null) {
			setZendeskArticleId(zendeskArticleId);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long zendeskCategoryId = (Long)attributes.get("zendeskCategoryId");

		if (zendeskCategoryId != null) {
			setZendeskCategoryId(zendeskCategoryId);
		}

		Long zendeskSectionId = (Long)attributes.get("zendeskSectionId");

		if (zendeskSectionId != null) {
			setZendeskSectionId(zendeskSectionId);
		}

		String documentationKey = (String)attributes.get("documentationKey");

		if (documentationKey != null) {
			setDocumentationKey(documentationKey);
		}

		String documentationOriginalURL = (String)attributes.get(
				"documentationOriginalURL");

		if (documentationOriginalURL != null) {
			setDocumentationOriginalURL(documentationOriginalURL);
		}

		String previousArticleDocumentationKey = (String)attributes.get(
				"previousArticleDocumentationKey");

		if (previousArticleDocumentationKey != null) {
			setPreviousArticleDocumentationKey(previousArticleDocumentationKey);
		}

		String nextArticleDocumentationKey = (String)attributes.get(
				"nextArticleDocumentationKey");

		if (nextArticleDocumentationKey != null) {
			setNextArticleDocumentationKey(nextArticleDocumentationKey);
		}

		Long remoteId = (Long)attributes.get("remoteId");

		if (remoteId != null) {
			setRemoteId(remoteId);
		}

		String remoteHtmlURL = (String)attributes.get("remoteHtmlURL");

		if (remoteHtmlURL != null) {
			setRemoteHtmlURL(remoteHtmlURL);
		}

		String remoteTitle = (String)attributes.get("remoteTitle");

		if (remoteTitle != null) {
			setRemoteTitle(remoteTitle);
		}
	}

	@Override
	public long getZendeskArticleId() {
		return _zendeskArticleId;
	}

	@Override
	public void setZendeskArticleId(long zendeskArticleId) {
		_zendeskArticleId = zendeskArticleId;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getZendeskCategoryId() {
		return _zendeskCategoryId;
	}

	@Override
	public void setZendeskCategoryId(long zendeskCategoryId) {
		_columnBitmask |= ZENDESKCATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalZendeskCategoryId) {
			_setOriginalZendeskCategoryId = true;

			_originalZendeskCategoryId = _zendeskCategoryId;
		}

		_zendeskCategoryId = zendeskCategoryId;
	}

	public long getOriginalZendeskCategoryId() {
		return _originalZendeskCategoryId;
	}

	@Override
	public long getZendeskSectionId() {
		return _zendeskSectionId;
	}

	@Override
	public void setZendeskSectionId(long zendeskSectionId) {
		_columnBitmask |= ZENDESKSECTIONID_COLUMN_BITMASK;

		if (!_setOriginalZendeskSectionId) {
			_setOriginalZendeskSectionId = true;

			_originalZendeskSectionId = _zendeskSectionId;
		}

		_zendeskSectionId = zendeskSectionId;
	}

	public long getOriginalZendeskSectionId() {
		return _originalZendeskSectionId;
	}

	@Override
	public String getDocumentationKey() {
		if (_documentationKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _documentationKey;
		}
	}

	@Override
	public void setDocumentationKey(String documentationKey) {
		_columnBitmask |= DOCUMENTATIONKEY_COLUMN_BITMASK;

		if (_originalDocumentationKey == null) {
			_originalDocumentationKey = _documentationKey;
		}

		_documentationKey = documentationKey;
	}

	public String getOriginalDocumentationKey() {
		return GetterUtil.getString(_originalDocumentationKey);
	}

	@Override
	public String getDocumentationOriginalURL() {
		if (_documentationOriginalURL == null) {
			return StringPool.BLANK;
		}
		else {
			return _documentationOriginalURL;
		}
	}

	@Override
	public void setDocumentationOriginalURL(String documentationOriginalURL) {
		_columnBitmask |= DOCUMENTATIONORIGINALURL_COLUMN_BITMASK;

		if (_originalDocumentationOriginalURL == null) {
			_originalDocumentationOriginalURL = _documentationOriginalURL;
		}

		_documentationOriginalURL = documentationOriginalURL;
	}

	public String getOriginalDocumentationOriginalURL() {
		return GetterUtil.getString(_originalDocumentationOriginalURL);
	}

	@Override
	public String getPreviousArticleDocumentationKey() {
		if (_previousArticleDocumentationKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _previousArticleDocumentationKey;
		}
	}

	@Override
	public void setPreviousArticleDocumentationKey(
		String previousArticleDocumentationKey) {
		_previousArticleDocumentationKey = previousArticleDocumentationKey;
	}

	@Override
	public String getNextArticleDocumentationKey() {
		if (_nextArticleDocumentationKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _nextArticleDocumentationKey;
		}
	}

	@Override
	public void setNextArticleDocumentationKey(
		String nextArticleDocumentationKey) {
		_nextArticleDocumentationKey = nextArticleDocumentationKey;
	}

	@Override
	public long getRemoteId() {
		return _remoteId;
	}

	@Override
	public void setRemoteId(long remoteId) {
		_remoteId = remoteId;
	}

	@Override
	public String getRemoteHtmlURL() {
		if (_remoteHtmlURL == null) {
			return StringPool.BLANK;
		}
		else {
			return _remoteHtmlURL;
		}
	}

	@Override
	public void setRemoteHtmlURL(String remoteHtmlURL) {
		_remoteHtmlURL = remoteHtmlURL;
	}

	@Override
	public String getRemoteTitle() {
		if (_remoteTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _remoteTitle;
		}
	}

	@Override
	public String getRemoteTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getRemoteTitle(languageId);
	}

	@Override
	public String getRemoteTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getRemoteTitle(languageId, useDefault);
	}

	@Override
	public String getRemoteTitle(String languageId) {
		return LocalizationUtil.getLocalization(getRemoteTitle(), languageId);
	}

	@Override
	public String getRemoteTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getRemoteTitle(), languageId,
			useDefault);
	}

	@Override
	public String getRemoteTitleCurrentLanguageId() {
		return _remoteTitleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getRemoteTitleCurrentValue() {
		Locale locale = getLocale(_remoteTitleCurrentLanguageId);

		return getRemoteTitle(locale);
	}

	@Override
	public Map<Locale, String> getRemoteTitleMap() {
		return LocalizationUtil.getLocalizationMap(getRemoteTitle());
	}

	@Override
	public void setRemoteTitle(String remoteTitle) {
		_remoteTitle = remoteTitle;
	}

	@Override
	public void setRemoteTitle(String remoteTitle, Locale locale) {
		setRemoteTitle(remoteTitle, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setRemoteTitle(String remoteTitle, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(remoteTitle)) {
			setRemoteTitle(LocalizationUtil.updateLocalization(
					getRemoteTitle(), "RemoteTitle", remoteTitle, languageId,
					defaultLanguageId));
		}
		else {
			setRemoteTitle(LocalizationUtil.removeLocalization(
					getRemoteTitle(), "RemoteTitle", languageId));
		}
	}

	@Override
	public void setRemoteTitleCurrentLanguageId(String languageId) {
		_remoteTitleCurrentLanguageId = languageId;
	}

	@Override
	public void setRemoteTitleMap(Map<Locale, String> remoteTitleMap) {
		setRemoteTitleMap(remoteTitleMap, LocaleUtil.getDefault());
	}

	@Override
	public void setRemoteTitleMap(Map<Locale, String> remoteTitleMap,
		Locale defaultLocale) {
		if (remoteTitleMap == null) {
			return;
		}

		setRemoteTitle(LocalizationUtil.updateLocalization(remoteTitleMap,
				getRemoteTitle(), "RemoteTitle",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ZendeskArticle.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> remoteTitleMap = getRemoteTitleMap();

		for (Map.Entry<Locale, String> entry : remoteTitleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getRemoteTitle();

		if (xml == null) {
			return StringPool.BLANK;
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(ZendeskArticle.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String remoteTitle = getRemoteTitle(defaultLocale);

		if (Validator.isNull(remoteTitle)) {
			setRemoteTitle(getRemoteTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setRemoteTitle(getRemoteTitle(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public ZendeskArticle toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ZendeskArticle)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ZendeskArticleImpl zendeskArticleImpl = new ZendeskArticleImpl();

		zendeskArticleImpl.setZendeskArticleId(getZendeskArticleId());
		zendeskArticleImpl.setModifiedDate(getModifiedDate());
		zendeskArticleImpl.setZendeskCategoryId(getZendeskCategoryId());
		zendeskArticleImpl.setZendeskSectionId(getZendeskSectionId());
		zendeskArticleImpl.setDocumentationKey(getDocumentationKey());
		zendeskArticleImpl.setDocumentationOriginalURL(getDocumentationOriginalURL());
		zendeskArticleImpl.setPreviousArticleDocumentationKey(getPreviousArticleDocumentationKey());
		zendeskArticleImpl.setNextArticleDocumentationKey(getNextArticleDocumentationKey());
		zendeskArticleImpl.setRemoteId(getRemoteId());
		zendeskArticleImpl.setRemoteHtmlURL(getRemoteHtmlURL());
		zendeskArticleImpl.setRemoteTitle(getRemoteTitle());

		zendeskArticleImpl.resetOriginalValues();

		return zendeskArticleImpl;
	}

	@Override
	public int compareTo(ZendeskArticle zendeskArticle) {
		long primaryKey = zendeskArticle.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ZendeskArticle)) {
			return false;
		}

		ZendeskArticle zendeskArticle = (ZendeskArticle)obj;

		long primaryKey = zendeskArticle.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ZendeskArticleModelImpl zendeskArticleModelImpl = this;

		zendeskArticleModelImpl._originalZendeskCategoryId = zendeskArticleModelImpl._zendeskCategoryId;

		zendeskArticleModelImpl._setOriginalZendeskCategoryId = false;

		zendeskArticleModelImpl._originalZendeskSectionId = zendeskArticleModelImpl._zendeskSectionId;

		zendeskArticleModelImpl._setOriginalZendeskSectionId = false;

		zendeskArticleModelImpl._originalDocumentationKey = zendeskArticleModelImpl._documentationKey;

		zendeskArticleModelImpl._originalDocumentationOriginalURL = zendeskArticleModelImpl._documentationOriginalURL;

		zendeskArticleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ZendeskArticle> toCacheModel() {
		ZendeskArticleCacheModel zendeskArticleCacheModel = new ZendeskArticleCacheModel();

		zendeskArticleCacheModel.zendeskArticleId = getZendeskArticleId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			zendeskArticleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			zendeskArticleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		zendeskArticleCacheModel.zendeskCategoryId = getZendeskCategoryId();

		zendeskArticleCacheModel.zendeskSectionId = getZendeskSectionId();

		zendeskArticleCacheModel.documentationKey = getDocumentationKey();

		String documentationKey = zendeskArticleCacheModel.documentationKey;

		if ((documentationKey != null) && (documentationKey.length() == 0)) {
			zendeskArticleCacheModel.documentationKey = null;
		}

		zendeskArticleCacheModel.documentationOriginalURL = getDocumentationOriginalURL();

		String documentationOriginalURL = zendeskArticleCacheModel.documentationOriginalURL;

		if ((documentationOriginalURL != null) &&
				(documentationOriginalURL.length() == 0)) {
			zendeskArticleCacheModel.documentationOriginalURL = null;
		}

		zendeskArticleCacheModel.previousArticleDocumentationKey = getPreviousArticleDocumentationKey();

		String previousArticleDocumentationKey = zendeskArticleCacheModel.previousArticleDocumentationKey;

		if ((previousArticleDocumentationKey != null) &&
				(previousArticleDocumentationKey.length() == 0)) {
			zendeskArticleCacheModel.previousArticleDocumentationKey = null;
		}

		zendeskArticleCacheModel.nextArticleDocumentationKey = getNextArticleDocumentationKey();

		String nextArticleDocumentationKey = zendeskArticleCacheModel.nextArticleDocumentationKey;

		if ((nextArticleDocumentationKey != null) &&
				(nextArticleDocumentationKey.length() == 0)) {
			zendeskArticleCacheModel.nextArticleDocumentationKey = null;
		}

		zendeskArticleCacheModel.remoteId = getRemoteId();

		zendeskArticleCacheModel.remoteHtmlURL = getRemoteHtmlURL();

		String remoteHtmlURL = zendeskArticleCacheModel.remoteHtmlURL;

		if ((remoteHtmlURL != null) && (remoteHtmlURL.length() == 0)) {
			zendeskArticleCacheModel.remoteHtmlURL = null;
		}

		zendeskArticleCacheModel.remoteTitle = getRemoteTitle();

		String remoteTitle = zendeskArticleCacheModel.remoteTitle;

		if ((remoteTitle != null) && (remoteTitle.length() == 0)) {
			zendeskArticleCacheModel.remoteTitle = null;
		}

		return zendeskArticleCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{zendeskArticleId=");
		sb.append(getZendeskArticleId());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", zendeskCategoryId=");
		sb.append(getZendeskCategoryId());
		sb.append(", zendeskSectionId=");
		sb.append(getZendeskSectionId());
		sb.append(", documentationKey=");
		sb.append(getDocumentationKey());
		sb.append(", documentationOriginalURL=");
		sb.append(getDocumentationOriginalURL());
		sb.append(", previousArticleDocumentationKey=");
		sb.append(getPreviousArticleDocumentationKey());
		sb.append(", nextArticleDocumentationKey=");
		sb.append(getNextArticleDocumentationKey());
		sb.append(", remoteId=");
		sb.append(getRemoteId());
		sb.append(", remoteHtmlURL=");
		sb.append(getRemoteHtmlURL());
		sb.append(", remoteTitle=");
		sb.append(getRemoteTitle());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticle");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>zendeskArticleId</column-name><column-value><![CDATA[");
		sb.append(getZendeskArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zendeskCategoryId</column-name><column-value><![CDATA[");
		sb.append(getZendeskCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zendeskSectionId</column-name><column-value><![CDATA[");
		sb.append(getZendeskSectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentationKey</column-name><column-value><![CDATA[");
		sb.append(getDocumentationKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentationOriginalURL</column-name><column-value><![CDATA[");
		sb.append(getDocumentationOriginalURL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>previousArticleDocumentationKey</column-name><column-value><![CDATA[");
		sb.append(getPreviousArticleDocumentationKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nextArticleDocumentationKey</column-name><column-value><![CDATA[");
		sb.append(getNextArticleDocumentationKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteId</column-name><column-value><![CDATA[");
		sb.append(getRemoteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteHtmlURL</column-name><column-value><![CDATA[");
		sb.append(getRemoteHtmlURL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteTitle</column-name><column-value><![CDATA[");
		sb.append(getRemoteTitle());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ZendeskArticle.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ZendeskArticle.class
		};
	private long _zendeskArticleId;
	private Date _modifiedDate;
	private long _zendeskCategoryId;
	private long _originalZendeskCategoryId;
	private boolean _setOriginalZendeskCategoryId;
	private long _zendeskSectionId;
	private long _originalZendeskSectionId;
	private boolean _setOriginalZendeskSectionId;
	private String _documentationKey;
	private String _originalDocumentationKey;
	private String _documentationOriginalURL;
	private String _originalDocumentationOriginalURL;
	private String _previousArticleDocumentationKey;
	private String _nextArticleDocumentationKey;
	private long _remoteId;
	private String _remoteHtmlURL;
	private String _remoteTitle;
	private String _remoteTitleCurrentLanguageId;
	private long _columnBitmask;
	private ZendeskArticle _escapedModel;
}