/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.customer.zendesk.documentation.sync.model.impl;

import com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskArticle;
import com.liferay.osb.customer.zendesk.documentation.sync.service.ZendeskArticleLocalServiceUtil;

/**
 * The extended model base implementation for the ZendeskArticle service. Represents a row in the &quot;OSBCustomer_ZendeskArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ZendeskArticleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ZendeskArticleImpl
 * @see ZendeskArticle
 * @generated
 */
public abstract class ZendeskArticleBaseImpl
	extends ZendeskArticleModelImpl implements ZendeskArticle {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a zendesk article model instance should use the <code>ZendeskArticle</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ZendeskArticleLocalServiceUtil.addZendeskArticle(this);
		}
		else {
			ZendeskArticleLocalServiceUtil.updateZendeskArticle(this);
		}
	}

}