#LOCAL
#osb.lcs.gateway.web.host.name=localhost
#osb.lcs.gateway.web.host.port=8080
#osb.lcs.gateway.web.protocol=http
#
#osb.lcs.portlet.host.name=localhost
#osb.lcs.portlet.host.port=8080
#osb.lcs.portlet.protocol=http
#
#osb.lcs.portlet.oauth.consumer.key=9b1dea2f-ca69-4d49-8aaf-ac7e8275f68a
#osb.lcs.portlet.oauth.consumer.secret=fe8691a9fbc1ff95c2b65f0f4faa1e61

#QA
osb.lcs.gateway.web.host.name=osblcsgatewaywebqa-267525078.us-east-1.elb.amazonaws.com
osb.lcs.gateway.web.host.port=80
osb.lcs.gateway.web.protocol=http

osb.lcs.portlet.host.name=lcs-qa.liferay.com
osb.lcs.portlet.host.port=443

osb.lcs.portlet.oauth.consumer.key=e2a653a6-f36c-4416-81f3-df41dcecf07b
osb.lcs.portlet.oauth.consumer.secret=fc075c03b57de24ca93d98ff69da3346
osb.lcs.portlet.protocol=https

#NODE SETUP S VISE DXP/EE instances

#osb.lcs.gateway.web.host.name=localhost
#osb.lcs.gateway.web.host.port=8091
#osb.lcs.gateway.web.protocol=http
#
#osb.lcs.portlet.host.name=localhost
#osb.lcs.portlet.host.port=8080
#osb.lcs.portlet.oauth.consumer.key=9b1dea2f-ca69-4d49-8aaf-ac7e8275f68a
#osb.lcs.portlet.oauth.consumer.secret=fe8691a9fbc1ff95c2b65f0f4faa1e61
#osb.lcs.portlet.protocol=http