author=Liferay, Inc.
change-log=
licenses=DXP
liferay-portal-profile-names=DXP
liferay-versions=7.0.10+,7.1.0+
long-description=
module-group-id=liferay
module-incremental-version=1
name=Watson EE
page-url=http://www.liferay.com
portal-dependency-jars=\
    jstl-api.jar,\
    jstl-impl.jar
portal-dependency-tlds=\
    c.tld,\
    fmt.tld,\
    fn.tld
short-description=
tags=