##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/dxp/apps/osb/osb-community/**,\
        modules/dxp/apps/osb/osb-email-blacklist/**