include-and-override=portlet-ext.properties

commerce.trial.expired.page=https://www.liferay.com/products/commerce/30-day-trial/key-expired
commerce.trial.versions=1

dxp.trial.expired.page=https://www.liferay.com/products/dxp/30-day-trial/key-expired
dxp.trial.versions=7.2,7.3,7.4