include-and-override=portlet-ext.properties

remote.rest.service.api.dxp.cloud.host=localhost
remote.rest.service.api.dxp.cloud.page.id=
remote.rest.service.api.dxp.cloud.port=80
remote.rest.service.api.dxp.cloud.protocol=http
remote.rest.service.api.dxp.cloud.token=

remote.rest.service.api.training.host=tma-uat.liferay.com
remote.rest.service.api.training.token=