include-and-override=portlet-ext.properties

exclude.github.team.slugs=dxp-committers,portal-ee-developers,dxp-developers
exclude.github.usernames=

github.feature.enabled=false

remote.rest.service.api.github.host=api.github.com
remote.rest.service.api.github.port=443
remote.rest.service.api.github.protocol=https
remote.rest.service.api.github.repository.name=
remote.rest.service.api.github.repository.owner=
remote.rest.service.api.github.token=