##
## Git
##

    git.liferay.portal.branch=7.0.x

##
## Source Check Properties
##

    source.check.JavaModuleComponentCheck.allowedClassNames=\
        com.liferay.osb.community.doc.project.util.DocProjectTypeSettingsFactoryUtil,\
        com.liferay.osb.training.search.CourseClassIndexer,\
        com.liferay.saml.runtime.configuration.SamlKeystoreManagerMetaTypeRegistrator