/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.email.blacklist.model.impl;

import com.liferay.osb.email.blacklist.model.BlacklistEntry;
import com.liferay.osb.email.blacklist.service.BlacklistEntryLocalServiceUtil;

/**
 * The extended model base implementation for the BlacklistEntry service. Represents a row in the &quot;OSB_BlacklistEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BlacklistEntryImpl}.
 * </p>
 *
 * @author Jamie Sammons
 * @see BlacklistEntryImpl
 * @see BlacklistEntry
 * @generated
 */
public abstract class BlacklistEntryBaseImpl
	extends BlacklistEntryModelImpl implements BlacklistEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a blacklist entry model instance should use the <code>BlacklistEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BlacklistEntryLocalServiceUtil.addBlacklistEntry(this);
		}
		else {
			BlacklistEntryLocalServiceUtil.updateBlacklistEntry(this);
		}
	}

}