/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.email.blacklist.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.email.blacklist.model.BlacklistEntry;
import com.liferay.osb.email.blacklist.model.BlacklistEntryModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BlacklistEntry service. Represents a row in the &quot;OSB_BlacklistEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link BlacklistEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BlacklistEntryImpl}.
 * </p>
 *
 * @author Jamie Sammons
 * @see BlacklistEntryImpl
 * @see BlacklistEntry
 * @see BlacklistEntryModel
 * @generated
 */
@ProviderType
public class BlacklistEntryModelImpl extends BaseModelImpl<BlacklistEntry>
	implements BlacklistEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a blacklist entry model instance should use the {@link BlacklistEntry} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_BlacklistEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "blacklistEntryId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "emailAddress", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("blacklistEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_BlacklistEntry (blacklistEntryId LONG not null primary key,createDate DATE null,emailAddress VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_BlacklistEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY blacklistEntry.blacklistEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_BlacklistEntry.blacklistEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.email.blacklist.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.email.blacklist.model.BlacklistEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.email.blacklist.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.email.blacklist.model.BlacklistEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.email.blacklist.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.email.blacklist.model.BlacklistEntry"),
			true);
	public static final long EMAILADDRESS_COLUMN_BITMASK = 1L;
	public static final long BLACKLISTENTRYID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.email.blacklist.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.email.blacklist.model.BlacklistEntry"));

	public BlacklistEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _blacklistEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBlacklistEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _blacklistEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BlacklistEntry.class;
	}

	@Override
	public String getModelClassName() {
		return BlacklistEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("blacklistEntryId", getBlacklistEntryId());
		attributes.put("createDate", getCreateDate());
		attributes.put("emailAddress", getEmailAddress());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long blacklistEntryId = (Long)attributes.get("blacklistEntryId");

		if (blacklistEntryId != null) {
			setBlacklistEntryId(blacklistEntryId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		String emailAddress = (String)attributes.get("emailAddress");

		if (emailAddress != null) {
			setEmailAddress(emailAddress);
		}
	}

	@Override
	public long getBlacklistEntryId() {
		return _blacklistEntryId;
	}

	@Override
	public void setBlacklistEntryId(long blacklistEntryId) {
		_blacklistEntryId = blacklistEntryId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		_columnBitmask |= EMAILADDRESS_COLUMN_BITMASK;

		if (_originalEmailAddress == null) {
			_originalEmailAddress = _emailAddress;
		}

		_emailAddress = emailAddress;
	}

	public String getOriginalEmailAddress() {
		return GetterUtil.getString(_originalEmailAddress);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BlacklistEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BlacklistEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BlacklistEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BlacklistEntryImpl blacklistEntryImpl = new BlacklistEntryImpl();

		blacklistEntryImpl.setBlacklistEntryId(getBlacklistEntryId());
		blacklistEntryImpl.setCreateDate(getCreateDate());
		blacklistEntryImpl.setEmailAddress(getEmailAddress());

		blacklistEntryImpl.resetOriginalValues();

		return blacklistEntryImpl;
	}

	@Override
	public int compareTo(BlacklistEntry blacklistEntry) {
		long primaryKey = blacklistEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BlacklistEntry)) {
			return false;
		}

		BlacklistEntry blacklistEntry = (BlacklistEntry)obj;

		long primaryKey = blacklistEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		BlacklistEntryModelImpl blacklistEntryModelImpl = this;

		blacklistEntryModelImpl._originalEmailAddress = blacklistEntryModelImpl._emailAddress;

		blacklistEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BlacklistEntry> toCacheModel() {
		BlacklistEntryCacheModel blacklistEntryCacheModel = new BlacklistEntryCacheModel();

		blacklistEntryCacheModel.blacklistEntryId = getBlacklistEntryId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			blacklistEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			blacklistEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		blacklistEntryCacheModel.emailAddress = getEmailAddress();

		String emailAddress = blacklistEntryCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			blacklistEntryCacheModel.emailAddress = null;
		}

		return blacklistEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{blacklistEntryId=");
		sb.append(getBlacklistEntryId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", emailAddress=");
		sb.append(getEmailAddress());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.email.blacklist.model.BlacklistEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>blacklistEntryId</column-name><column-value><![CDATA[");
		sb.append(getBlacklistEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailAddress</column-name><column-value><![CDATA[");
		sb.append(getEmailAddress());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = BlacklistEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			BlacklistEntry.class
		};
	private long _blacklistEntryId;
	private Date _createDate;
	private String _emailAddress;
	private String _originalEmailAddress;
	private long _columnBitmask;
	private BlacklistEntry _escapedModel;
}