/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.loop.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LoopPersonRel service. Represents a row in the &quot;LoopPersonRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.loop.model.impl.LoopPersonRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.loop.model.impl.LoopPersonRelImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopPersonRel
 * @see com.liferay.osb.loop.model.impl.LoopPersonRelImpl
 * @see com.liferay.osb.loop.model.impl.LoopPersonRelModelImpl
 * @generated
 */
@ProviderType
public interface LoopPersonRelModel extends BaseModel<LoopPersonRel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loop person rel model instance should use the {@link LoopPersonRel} interface instead.
	 */

	/**
	 * Returns the primary key of this loop person rel.
	 *
	 * @return the primary key of this loop person rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loop person rel.
	 *
	 * @param primaryKey the primary key of this loop person rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loop person rel ID of this loop person rel.
	 *
	 * @return the loop person rel ID of this loop person rel
	 */
	public long getLoopPersonRelId();

	/**
	 * Sets the loop person rel ID of this loop person rel.
	 *
	 * @param loopPersonRelId the loop person rel ID of this loop person rel
	 */
	public void setLoopPersonRelId(long loopPersonRelId);

	/**
	 * Returns the child loop person ID of this loop person rel.
	 *
	 * @return the child loop person ID of this loop person rel
	 */
	public long getChildLoopPersonId();

	/**
	 * Sets the child loop person ID of this loop person rel.
	 *
	 * @param childLoopPersonId the child loop person ID of this loop person rel
	 */
	public void setChildLoopPersonId(long childLoopPersonId);

	/**
	 * Returns the parent loop person ID of this loop person rel.
	 *
	 * @return the parent loop person ID of this loop person rel
	 */
	public long getParentLoopPersonId();

	/**
	 * Sets the parent loop person ID of this loop person rel.
	 *
	 * @param parentLoopPersonId the parent loop person ID of this loop person rel
	 */
	public void setParentLoopPersonId(long parentLoopPersonId);

	/**
	 * Returns the type of this loop person rel.
	 *
	 * @return the type of this loop person rel
	 */
	public int getType();

	/**
	 * Sets the type of this loop person rel.
	 *
	 * @param type the type of this loop person rel
	 */
	public void setType(int type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LoopPersonRel loopPersonRel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LoopPersonRel> toCacheModel();

	@Override
	public LoopPersonRel toEscapedModel();

	@Override
	public LoopPersonRel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}