/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.loop.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LoopJobTitle service. Represents a row in the &quot;LoopJobTitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.loop.model.impl.LoopJobTitleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.loop.model.impl.LoopJobTitleImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopJobTitle
 * @see com.liferay.osb.loop.model.impl.LoopJobTitleImpl
 * @see com.liferay.osb.loop.model.impl.LoopJobTitleModelImpl
 * @generated
 */
@ProviderType
public interface LoopJobTitleModel extends AuditedModel, BaseModel<LoopJobTitle>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loop job title model instance should use the {@link LoopJobTitle} interface instead.
	 */

	/**
	 * Returns the primary key of this loop job title.
	 *
	 * @return the primary key of this loop job title
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loop job title.
	 *
	 * @param primaryKey the primary key of this loop job title
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loop job title ID of this loop job title.
	 *
	 * @return the loop job title ID of this loop job title
	 */
	public long getLoopJobTitleId();

	/**
	 * Sets the loop job title ID of this loop job title.
	 *
	 * @param loopJobTitleId the loop job title ID of this loop job title
	 */
	public void setLoopJobTitleId(long loopJobTitleId);

	/**
	 * Returns the company ID of this loop job title.
	 *
	 * @return the company ID of this loop job title
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this loop job title.
	 *
	 * @param companyId the company ID of this loop job title
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this loop job title.
	 *
	 * @return the user ID of this loop job title
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this loop job title.
	 *
	 * @param userId the user ID of this loop job title
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this loop job title.
	 *
	 * @return the user uuid of this loop job title
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this loop job title.
	 *
	 * @param userUuid the user uuid of this loop job title
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this loop job title.
	 *
	 * @return the user name of this loop job title
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this loop job title.
	 *
	 * @param userName the user name of this loop job title
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this loop job title.
	 *
	 * @return the create date of this loop job title
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this loop job title.
	 *
	 * @param createDate the create date of this loop job title
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this loop job title.
	 *
	 * @return the modified date of this loop job title
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this loop job title.
	 *
	 * @param modifiedDate the modified date of this loop job title
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this loop job title.
	 *
	 * @return the name of this loop job title
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this loop job title.
	 *
	 * @param name the name of this loop job title
	 */
	public void setName(String name);

	/**
	 * Returns the description of this loop job title.
	 *
	 * @return the description of this loop job title
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this loop job title.
	 *
	 * @param description the description of this loop job title
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this loop job title.
	 *
	 * @return the status of this loop job title
	 */
	public int getStatus();

	/**
	 * Sets the status of this loop job title.
	 *
	 * @param status the status of this loop job title
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LoopJobTitle loopJobTitle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LoopJobTitle> toCacheModel();

	@Override
	public LoopJobTitle toEscapedModel();

	@Override
	public LoopJobTitle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}