release.info.build.number=500

login.events.post=com.liferay.osb.hook.events.LoginPostAction

upgrade.processes=\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_0

value.object.listener.com.liferay.portal.kernel.model.User=com.liferay.osb.model.UserListener