include-and-override=portlet-ext.properties

json.service.api.ac.token=lwn8C5iAlUi2bvaqSm
json.service.api.lcs.token=ke8eJgsT2nla73NsRe
json.service.api.patcher.token=lakIw83Ha2vbapqz3j
json.service.api.web.token=vuH6GaVgwkueqmxsR3
json.service.api.wedeploy.token=sP3Ujen2h1kfMeRWkx