include-and-override=portlet-ext.properties

audit.action.models=\
    /com.liferay.portal.kernel.model.Address,\
    /com.liferay.portal.kernel.model.Layout,\
    /com.liferay.portal.kernel.model.Organization,\
    /com.liferay.portal.kernel.model.PortletPreferences,\
    /com.liferay.portal.kernel.model.User,\
    /com.liferay.asset.kernel.model.AssetCategory,\
    /com.liferay.asset.kernel.model.AssetEntry,\
    /com.liferay.asset.kernel.model.AssetTag,\
    /com.liferay.asset.kernel.model.AssetTagStats,\
    /com.liferay.asset.kernel.model.AssetVocabulary,\
    /com.liferay.expando.kernel.model.ExpandoValue,\
    osb-portlet/com.liferay.osb.model.AccountAttachment,\
    osb-portlet/com.liferay.osb.model.AccountCall,\
    osb-portlet/com.liferay.osb.model.AccountCustomer,\
    osb-portlet/com.liferay.osb.model.AccountEntry,\
    osb-portlet/com.liferay.osb.model.AccountEntryLanguage,\
    osb-portlet/com.liferay.osb.model.AccountEnvironment,\
    osb-portlet/com.liferay.osb.model.AccountEnvironmentAttachment,\
    osb-portlet/com.liferay.osb.model.AccountInformation,\
    osb-portlet/com.liferay.osb.model.AccountLink,\
    osb-portlet/com.liferay.osb.model.AccountProject,\
    osb-portlet/com.liferay.osb.model.AccountWorker,\
    osb-portlet/com.liferay.osb.model.AuditEntry,\
    osb-portlet/com.liferay.osb.model.FeedbackEntry,\
    osb-portlet/com.liferay.osb.model.HolidayCalendar,\
    osb-portlet/com.liferay.osb.model.HolidayCalendarRel,\
    osb-portlet/com.liferay.osb.model.HolidayEntry,\
    osb-portlet/com.liferay.osb.model.LicenseEntry,\
    osb-portlet/com.liferay.osb.model.LicenseKey,\
    osb-portlet/com.liferay.osb.model.LicenseKeySet,\
    osb-portlet/com.liferay.osb.model.OfferingDefinition,\
    osb-portlet/com.liferay.osb.model.OfferingEntry,\
    osb-portlet/com.liferay.osb.model.OrderEntry,\
    osb-portlet/com.liferay.osb.model.PartnerEntry,\
    osb-portlet/com.liferay.osb.model.PartnerWorker,\
    osb-portlet/com.liferay.osb.model.ProductEntry,\
    osb-portlet/com.liferay.osb.model.SupportLabor,\
    osb-portlet/com.liferay.osb.model.SupportRegion,\
    osb-portlet/com.liferay.osb.model.SupportResponse,\
    osb-portlet/com.liferay.osb.model.SupportTeam,\
    osb-portlet/com.liferay.osb.model.SupportTeamLanguage,\
    osb-portlet/com.liferay.osb.model.SupportWorker,\
    osb-portlet/com.liferay.osb.model.SupportWorkerComponent,\
    osb-portlet/com.liferay.osb.model.SupportWorkerSeverity,\
    osb-portlet/com.liferay.osb.model.TicketAttachment,\
    osb-portlet/com.liferay.osb.model.TicketCall,\
    osb-portlet/com.liferay.osb.model.TicketComment,\
    osb-portlet/com.liferay.osb.model.TicketEntry,\
    osb-portlet/com.liferay.osb.model.TicketFeedback,\
    osb-portlet/com.liferay.osb.model.TicketFlag,\
    osb-portlet/com.liferay.osb.model.TicketLink,\
    osb-portlet/com.liferay.osb.model.TicketSolution,\
    osb-portlet/com.liferay.osb.model.TicketWorker

developer.mode.enabled=false
developer.upgrade.enabled=true

file.repository.host[server-1]=http://127.0.0.1:8080
file.repository.host[server-2]=http://127.0.0.1:8081
file.repository.ids=server-1,server-2
file.repository.name[server-1]=server-west
file.repository.name[server-2]=server-east
file.repository.support.region.ids[server-1]=
file.repository.support.region.ids[server-2]=

json.service.api.gs.token=cy3t3upM2M7eTMtFef
json.service.api.lcs.token=ke8eJgsT2nla73NsRe

provisioning.email.address[Australia]=provisioning-apac-uat@liferay.com
provisioning.email.address[Brazil]=provisioning-br-uat@liferay.com
provisioning.email.address[China]=provisioning-apac-uat@liferay.com
provisioning.email.address[Global]=provisioning-uat@liferay.com
provisioning.email.address[Hungary]=provisioning-emea-uat@liferay.com
provisioning.email.address[India]=provisioning-in-uat@liferay.com
provisioning.email.address[Japan]=provisioning-apac-uat@liferay.com
provisioning.email.address[Spain]=provisioning-es-uat@liferay.com
provisioning.email.address[US]=provisioning-na-uat@liferay.com

qa.infrastructure.enabled=false

rabbitmq.message.dead.letter.queue.name=
rabbitmq.message.queue.name=

remote.json.service.api.lcs.enabled=false
remote.json.service.api.lcs.host=localhost
remote.json.service.api.lcs.port=80
remote.json.service.api.lcs.protocol=http
remote.json.service.api.lcs.token=

remote.rest.service.api.dossiera.enabled=false
remote.rest.service.api.dossiera.host=localhost
remote.rest.service.api.dossiera.port=80
remote.rest.service.api.dossiera.protocol=http
remote.rest.service.api.dossiera.token=

remote.rest.service.api.web.enabled=false
remote.rest.service.api.web.host=localhost
remote.rest.service.api.web.port=80
remote.rest.service.api.web.protocol=http
remote.rest.service.api.web.token=

resource.actions.configs=resource-actions/default.xml

support.email.address.from=no-reply-uat@liferay.com
support.version.2.email.address.feedback=lesa-support-uat@liferay.com

ticket.attachment.indexing.extensions=.doc,.docx,.log,.out,.rtf,.txt
ticket.attachment.indexing.max.size=10485760
ticket.attachment.preview.extensions=flv,gif,jpg,log,pdf,png,swf,txt,wmv

ticket.entry.indexing.interval=10

web.api.token=k3pVa0gF4RwzkJ2dWa
web.domain.name=localhost