release.info.build.number=515

login.events.post=com.liferay.osb.hook.events.LoginPostAction

upgrade.processes=\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_0,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_1,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_2,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_3,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_4,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_5,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_6,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_7,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_8,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_9,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_1_0,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_1_1,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_1_2,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_1_3,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_1_4,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_1_5

value.object.listener.com.liferay.portal.kernel.model.User=com.liferay.osb.model.UserListener