release.info.build.number=502

login.events.post=com.liferay.osb.hook.events.LoginPostAction

upgrade.processes=\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_0,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_1,\
    com.liferay.osb.hook.upgrade.UpgradeProcess_5_0_2

value.object.listener.com.liferay.portal.kernel.model.User=com.liferay.osb.model.UserListener