include-and-override=portlet-qa-ext.properties

osb.qa.account.customer[lesa.qa.customer@test.com.broken][account-entry-code]=QAPROJECT1
osb.qa.account.customer[lesa.qa.customer@test.com.broken][notifications]=1
osb.qa.account.customer[lesa.qa.customer@test.com.broken][role]=2

osb.qa.account.customer[lesa.qa.customerwatcher@test.com.broken][account-entry-code]=QAPROJECT1
osb.qa.account.customer[lesa.qa.customerwatcher@test.com.broken][notifications]=1
osb.qa.account.customer[lesa.qa.customerwatcher@test.com.broken][role]=4

osb.qa.account.customer.email.addresses=\
    lesa.qa.customer@test.com.broken,\
    lesa.qa.customerwatcher@test.com.broken

osb.qa.account.entry[QAPROJECT1][max-customers]=50
osb.qa.account.entry[QAPROJECT1][name]=QA Test Project 1
osb.qa.account.entry[QAPROJECT1][partner-entry-code]=QA Test Partner
osb.qa.account.entry[QAPROJECT1][partner-managed]=true

osb.qa.account.entry[QAPROJECT2][max-customers]=50
osb.qa.account.entry[QAPROJECT2][name]=QA Test Project 2
osb.qa.account.entry[QAPROJECT2][partner-entry-code]=
osb.qa.account.entry[QAPROJECT2][partner-managed]=false

osb.qa.account.entry.codes=\
    QAPROJECT1,\
    QAPROJECT2

osb.qa.account.environment[QAConfig6.2][account-entry-code]=QAPROJECT1
osb.qa.account.environment[QAConfig6.2][envAS]=27013
osb.qa.account.environment[QAConfig6.2][envDB]=28025
osb.qa.account.environment[QAConfig6.2][envJVM]=29006
osb.qa.account.environment[QAConfig6.2][envLFR]=20080
osb.qa.account.environment[QAConfig6.2][envOS]=30029
osb.qa.account.environment[QAConfig6.2][envOSCustom]=
osb.qa.account.environment[QAConfig6.2][productEntryId]=5968276

osb.qa.account.environment[QAConfig7.0][account-entry-code]=QAPROJECT1
osb.qa.account.environment[QAConfig7.0][envAS]=27013
osb.qa.account.environment[QAConfig7.0][envDB]=28025
osb.qa.account.environment[QAConfig7.0][envJVM]=29006
osb.qa.account.environment[QAConfig7.0][envLFR]=41000
osb.qa.account.environment[QAConfig7.0][envOS]=30029
osb.qa.account.environment[QAConfig7.0][envOSCustom]=
osb.qa.account.environment[QAConfig7.0][productEntryId]=81815285

osb.qa.account.environment.names=\
    QA Config 6.2,\
    QA Config 7.0

osb.qa.account.worker[lesa.qa.cas@liferay.com.broken][account-entry-code]=QAPROJECT1
osb.qa.account.worker[lesa.qa.cas@liferay.com.broken][notifications]=1
osb.qa.account.worker[lesa.qa.cas@liferay.com.broken][role]=4

osb.qa.account.worker.email.addresses=\
    lesa.qa.cas@liferay.com.broken

osb.qa.offering.entry[QAPROJECT1][product-entry-ids]=4841187,5968272,5968274,5968276,29145766,68113296,73790417,73790419,73790421,81815273,81815281,81815285
osb.qa.offering.entry[QAPROJECT1][quantities]=1,1,1,1,1,1,1,1,1,1,1,1
osb.qa.offering.entry[QAPROJECT1][support-response-ids]=77672068,77672068,77672068,77672068,77672068,77672068,77672068,77672068,77672068,77672068,77672068,77672068
osb.qa.offering.entry[QAPROJECT1][types]=1,1,1,1,1,1,1,1,1,1,1,1
osb.qa.offering.entry[QAPROJECT1][versions]=23061,21001,21001,21001,0,0,0,0,0,42000,42000,42000

osb.qa.offering.entry[QAPROJECT2][product-entry-ids]=5968276
osb.qa.offering.entry[QAPROJECT2][quantities]=1
osb.qa.offering.entry[QAPROJECT2][support-response-ids]=77672068
osb.qa.offering.entry[QAPROJECT2][types]=1
osb.qa.offering.entry[QAPROJECT2][versions]=21001

osb.qa.partner.entry[QATestPartner][dossiera-account-key]=123456789012345678
osb.qa.partner.entry[QATestPartner][support-region-ids]=42356488

osb.qa.partner.entry.codes=\
    QA Test Partner

osb.qa.partner.worker[lesa.qa.partner@test.com.broken][notifications]=1
osb.qa.partner.worker[lesa.qa.partner@test.com.broken][partner-entry-code]=QA Test Partner
osb.qa.partner.worker[lesa.qa.partner@test.com.broken][role]=1

osb.qa.partner.worker[lesa.qa.partnerwatcher@test.com.broken][notifications]=1
osb.qa.partner.worker[lesa.qa.partnerwatcher@test.com.broken][partner-entry-code]=QA Test Partner
osb.qa.partner.worker[lesa.qa.partnerwatcher@test.com.broken][role]=3

osb.qa.partner.worker.email.addresses=\
      lesa.qa.partner@test.com.broken,\
      lesa.qa.partnerwatcher@test.com.broken

osb.qa.support.regions[QAPROJECT1][support-region-ids]=42356488
osb.qa.support.regions[QAPROJECT2][support-region-ids]=42356488

osb.qa.user[lesa.qa.admin@liferay.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.admin@liferay.com.broken][last-name]=Admin
osb.qa.user[lesa.qa.admin@liferay.com.broken][organization-ids]=1747318
osb.qa.user[lesa.qa.admin@liferay.com.broken][password]=test
osb.qa.user[lesa.qa.admin@liferay.com.broken][role-ids]=10164,10168
osb.qa.user[lesa.qa.admin@liferay.com.broken][screen-name]=lesa-qa-admin
osb.qa.user[lesa.qa.admin@liferay.com.broken][site-id]=10738
osb.qa.user[lesa.qa.admin@liferay.com.broken][user-group]=80690
osb.qa.user[lesa.qa.admin@liferay.com.broken][uuid]=1c8d14ce-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.cas@liferay.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.cas@liferay.com.broken][last-name]=CAS
osb.qa.user[lesa.qa.cas@liferay.com.broken][organization-ids]=1747318
osb.qa.user[lesa.qa.cas@liferay.com.broken][password]=test
osb.qa.user[lesa.qa.cas@liferay.com.broken][role-ids]=10168,10946,1546562,1546563
osb.qa.user[lesa.qa.cas@liferay.com.broken][screen-name]=lesa-qa-cas
osb.qa.user[lesa.qa.cas@liferay.com.broken][site-id]=10738
osb.qa.user[lesa.qa.cas@liferay.com.broken][user-group]=80690
osb.qa.user[lesa.qa.cas@liferay.com.broken][uuid]=2c8d19ec-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.cse.1@liferay.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][last-name]=CSE1
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][organization-ids]=1747318
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][password]=test
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][role-ids]=10168,10946
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][screen-name]=lesa-qa-cse-1
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][site-id]=10738
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][user-group]=80690
osb.qa.user[lesa.qa.cse.1@liferay.com.broken][uuid]=3c8d1b54-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.cse.2@liferay.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][last-name]=CSE2
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][organization-ids]=1747318
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][password]=test
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][role-ids]=10168,10946
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][screen-name]=lesa-qa-cse-2
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][site-id]=10738
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][user-group]=80690
osb.qa.user[lesa.qa.cse.2@liferay.com.broken][uuid]=4c8d1c80-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.customer@test.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.customer@test.com.broken][last-name]=Customer
osb.qa.user[lesa.qa.customer@test.com.broken][organization-ids]=1747330
osb.qa.user[lesa.qa.customer@test.com.broken][password]=test
osb.qa.user[lesa.qa.customer@test.com.broken][role-ids]=10168,1546579
osb.qa.user[lesa.qa.customer@test.com.broken][screen-name]=lesa-qa-customer
osb.qa.user[lesa.qa.customer@test.com.broken][site-id]=10738
osb.qa.user[lesa.qa.customer@test.com.broken][user-group]=84013
osb.qa.user[lesa.qa.customer@test.com.broken][uuid]=5c8d1da2-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.customerwatcher@test.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][last-name]=CWatcher
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][organization-ids]=1747330
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][password]=test
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][role-ids]=10168,1546579
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][screen-name]=lesa-qa-cwatcher
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][site-id]=10738
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][user-group]=84013
osb.qa.user[lesa.qa.customerwatcher@test.com.broken][uuid]=6c8d1eba-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.manager@liferay.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.manager@liferay.com.broken][last-name]=Manager
osb.qa.user[lesa.qa.manager@liferay.com.broken][organization-ids]=1747318
osb.qa.user[lesa.qa.manager@liferay.com.broken][password]=test
osb.qa.user[lesa.qa.manager@liferay.com.broken][role-ids]=10168,10946,1546564
osb.qa.user[lesa.qa.manager@liferay.com.broken][screen-name]=lesa-qa-manager
osb.qa.user[lesa.qa.manager@liferay.com.broken][site-id]=10738
osb.qa.user[lesa.qa.manager@liferay.com.broken][user-group]=80690
osb.qa.user[lesa.qa.manager@liferay.com.broken][uuid]=7c8d1fd2-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.partner@test.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.partner@test.com.broken][last-name]=Partner
osb.qa.user[lesa.qa.partner@test.com.broken][organization-ids]=1747324
osb.qa.user[lesa.qa.partner@test.com.broken][password]=test
osb.qa.user[lesa.qa.partner@test.com.broken][role-ids]=10168,1546579
osb.qa.user[lesa.qa.partner@test.com.broken][screen-name]=lesa-qa-partner
osb.qa.user[lesa.qa.partner@test.com.broken][site-id]=10738
osb.qa.user[lesa.qa.partner@test.com.broken][user-group]=84039
osb.qa.user[lesa.qa.partner@test.com.broken][uuid]=8c8d20ea-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][first-name]=QATest
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][last-name]=PWatcher
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][organization-ids]=1747324
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][password]=test
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][role-ids]=10168,1546579
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][screen-name]=lesa-qa-pwatcher
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][site-id]=10738
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][user-group]=84039
osb.qa.user[lesa.qa.partnerwatcher@test.com.broken][uuid]=9c8d245a-7bed-11e8-adc0-fa7ae01bbebc

osb.qa.user.email.addresses=\
    lesa.qa.admin@liferay.com.broken,\
    lesa.qa.cas@liferay.com.broken,\
    lesa.qa.cse.1@liferay.com.broken,\
    lesa.qa.cse.2@liferay.com.broken,\
    lesa.qa.customer@test.com.broken,\
    lesa.qa.customerwatcher@test.com.broken,\
    lesa.qa.manager@liferay.com.broken,\
    lesa.qa.partner@test.com.broken,\
    lesa.qa.partnerwatcher@test.com.broken