include-and-override=portlet-ext.properties

automatic.provisioning.error.email.address=automatic-provisioning-error-uat@liferay.com

corp.project.link=https://web-uat.liferay.com/group/control_panel/manage?p_p_id=31_WAR_osbportlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_31_WAR_osbportlet_mvcPath=%2Fcorp_project_admin%2Fview_corp_project.jsp&_31_WAR_osbportlet_corpProjectId=

developer.mode.enabled=false
developer.upgrade.enabled=true

json.service.api.ac.token=lwn8C5iAlUi2bvaqSm
json.service.api.lcs.token=ke8eJgsT2nla73NsRe
json.service.api.web.token=vuH6GaVgwkueqmxsR3
json.service.api.wedeploy.token=sP3Ujen2h1kfMeRWkx

provisioning.email.address[Australia]=provisioning-apac-uat@liferay.com
provisioning.email.address[Brazil]=provisioning-br-uat@liferay.com
provisioning.email.address[China]=provisioning-apac-uat@liferay.com
provisioning.email.address[Global]=provisioning-uat@liferay.com
provisioning.email.address[Hungary]=provisioning-emea-uat@liferay.com
provisioning.email.address[India]=provisioning-in-uat@liferay.com
provisioning.email.address[Japan]=provisioning-jp-uat@liferay.com
provisioning.email.address[Spain]=provisioning-es-uat@liferay.com
provisioning.email.address[US]=provisioning-na-uat@liferay.com
provisioning.opportunity.product.family.tokens=E,S

qa.infrastructure.enabled=false

remote.json.service.api.lcs.enabled=false
remote.json.service.api.lcs.host=localhost
remote.json.service.api.lcs.port=80
remote.json.service.api.lcs.protocol=http
remote.json.service.api.lcs.token=

remote.rest.service.api.dossiera.enabled=false
remote.rest.service.api.dossiera.host=localhost
remote.rest.service.api.dossiera.port=80
remote.rest.service.api.dossiera.protocol=http
remote.rest.service.api.dossiera.token=

remote.rest.service.api.web.enabled=false
remote.rest.service.api.web.error.email.address=is-lrsd-uat@liferay.com
remote.rest.service.api.web.host=localhost
remote.rest.service.api.web.port=80
remote.rest.service.api.web.protocol=http
remote.rest.service.api.web.token=

resource.actions.configs=resource-actions/default.xml

support.email.address.from=no-reply-uat@liferay.com

synchronize.users.enabled=false