data.source.id=
data.source.status=ACTIVE
salesforce.auth.endpoint=
salesforce.oauth.access.token=
salesforce.oauth.client.id=
salesforce.oauth.client.secret=
salesforce.oauth.refresh.token=
salesforce.password=
salesforce.service.endpoint=
salesforce.url=
salesforce.user.name=