/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.portal.workflow.kaleo.designer.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.workflow.kaleo.designer.model.KaleoDraftDefinition;
import com.liferay.portal.workflow.kaleo.designer.model.KaleoDraftDefinitionModel;
import com.liferay.portal.workflow.kaleo.designer.model.KaleoDraftDefinitionSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the KaleoDraftDefinition service. Represents a row in the &quot;KaleoDraftDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>KaleoDraftDefinitionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KaleoDraftDefinitionImpl}.
 * </p>
 *
 * @author Eduardo Lundgren
 * @see KaleoDraftDefinitionImpl
 * @generated
 */
@JSON(strict = true)
public class KaleoDraftDefinitionModelImpl
	extends BaseModelImpl<KaleoDraftDefinition>
	implements KaleoDraftDefinitionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a kaleo draft definition model instance should use the <code>KaleoDraftDefinition</code> interface instead.
	 */
	public static final String TABLE_NAME = "KaleoDraftDefinition";

	public static final Object[][] TABLE_COLUMNS = {
		{"kaleoDraftDefinitionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"title", Types.VARCHAR}, {"content", Types.CLOB},
		{"version", Types.INTEGER}, {"draftVersion", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("kaleoDraftDefinitionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.CLOB);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("draftVersion", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table KaleoDraftDefinition (kaleoDraftDefinitionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,title STRING null,content TEXT null,version INTEGER,draftVersion INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table KaleoDraftDefinition";

	public static final String ORDER_BY_JPQL =
		" ORDER BY kaleoDraftDefinition.draftVersion DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY KaleoDraftDefinition.draftVersion DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.workflow.kaleo.designer.service.util.ServiceProps.
			get(
				"value.object.entity.cache.enabled.com.liferay.portal.workflow.kaleo.designer.model.KaleoDraftDefinition"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.workflow.kaleo.designer.service.util.ServiceProps.
			get(
				"value.object.finder.cache.enabled.com.liferay.portal.workflow.kaleo.designer.model.KaleoDraftDefinition"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.portal.workflow.kaleo.designer.service.util.ServiceProps.
			get(
				"value.object.column.bitmask.enabled.com.liferay.portal.workflow.kaleo.designer.model.KaleoDraftDefinition"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long DRAFTVERSION_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long VERSION_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static KaleoDraftDefinition toModel(
		KaleoDraftDefinitionSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		KaleoDraftDefinition model = new KaleoDraftDefinitionImpl();

		model.setKaleoDraftDefinitionId(soapModel.getKaleoDraftDefinitionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setTitle(soapModel.getTitle());
		model.setContent(soapModel.getContent());
		model.setVersion(soapModel.getVersion());
		model.setDraftVersion(soapModel.getDraftVersion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<KaleoDraftDefinition> toModels(
		KaleoDraftDefinitionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<KaleoDraftDefinition> models = new ArrayList<KaleoDraftDefinition>(
			soapModels.length);

		for (KaleoDraftDefinitionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.workflow.kaleo.designer.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.workflow.kaleo.designer.model.KaleoDraftDefinition"));

	public KaleoDraftDefinitionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _kaleoDraftDefinitionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setKaleoDraftDefinitionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _kaleoDraftDefinitionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KaleoDraftDefinition.class;
	}

	@Override
	public String getModelClassName() {
		return KaleoDraftDefinition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<KaleoDraftDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<KaleoDraftDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KaleoDraftDefinition, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((KaleoDraftDefinition)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<KaleoDraftDefinition, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<KaleoDraftDefinition, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(KaleoDraftDefinition)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<KaleoDraftDefinition, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<KaleoDraftDefinition, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, KaleoDraftDefinition>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			KaleoDraftDefinition.class.getClassLoader(),
			KaleoDraftDefinition.class, ModelWrapper.class);

		try {
			Constructor<KaleoDraftDefinition> constructor =
				(Constructor<KaleoDraftDefinition>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<KaleoDraftDefinition, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<KaleoDraftDefinition, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<KaleoDraftDefinition, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<KaleoDraftDefinition, Object>>();
		Map<String, BiConsumer<KaleoDraftDefinition, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<KaleoDraftDefinition, ?>>();

		attributeGetterFunctions.put(
			"kaleoDraftDefinitionId",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getKaleoDraftDefinitionId();
				}

			});
		attributeSetterBiConsumers.put(
			"kaleoDraftDefinitionId",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object kaleoDraftDefinitionIdObject) {

					kaleoDraftDefinition.setKaleoDraftDefinitionId(
						(Long)kaleoDraftDefinitionIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object groupIdObject) {

					kaleoDraftDefinition.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object companyIdObject) {

					kaleoDraftDefinition.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object userIdObject) {

					kaleoDraftDefinition.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object userNameObject) {

					kaleoDraftDefinition.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object createDateObject) {

					kaleoDraftDefinition.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object modifiedDateObject) {

					kaleoDraftDefinition.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object nameObject) {

					kaleoDraftDefinition.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"title",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getTitle();
				}

			});
		attributeSetterBiConsumers.put(
			"title",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object titleObject) {

					kaleoDraftDefinition.setTitle((String)titleObject);
				}

			});
		attributeGetterFunctions.put(
			"content",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getContent();
				}

			});
		attributeSetterBiConsumers.put(
			"content",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object contentObject) {

					kaleoDraftDefinition.setContent((String)contentObject);
				}

			});
		attributeGetterFunctions.put(
			"version",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getVersion();
				}

			});
		attributeSetterBiConsumers.put(
			"version",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object versionObject) {

					kaleoDraftDefinition.setVersion((Integer)versionObject);
				}

			});
		attributeGetterFunctions.put(
			"draftVersion",
			new Function<KaleoDraftDefinition, Object>() {

				@Override
				public Object apply(KaleoDraftDefinition kaleoDraftDefinition) {
					return kaleoDraftDefinition.getDraftVersion();
				}

			});
		attributeSetterBiConsumers.put(
			"draftVersion",
			new BiConsumer<KaleoDraftDefinition, Object>() {

				@Override
				public void accept(
					KaleoDraftDefinition kaleoDraftDefinition,
					Object draftVersionObject) {

					kaleoDraftDefinition.setDraftVersion(
						(Integer)draftVersionObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getKaleoDraftDefinitionId() {
		return _kaleoDraftDefinitionId;
	}

	@Override
	public void setKaleoDraftDefinitionId(long kaleoDraftDefinitionId) {
		_kaleoDraftDefinitionId = kaleoDraftDefinitionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return "";
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@JSON
	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		_columnBitmask |= VERSION_COLUMN_BITMASK;

		if (!_setOriginalVersion) {
			_setOriginalVersion = true;

			_originalVersion = _version;
		}

		_version = version;
	}

	public int getOriginalVersion() {
		return _originalVersion;
	}

	@JSON
	@Override
	public int getDraftVersion() {
		return _draftVersion;
	}

	@Override
	public void setDraftVersion(int draftVersion) {
		_columnBitmask |= DRAFTVERSION_COLUMN_BITMASK;

		if (!_setOriginalDraftVersion) {
			_setOriginalDraftVersion = true;

			_originalDraftVersion = _draftVersion;
		}

		_draftVersion = draftVersion;
	}

	public int getOriginalDraftVersion() {
		return _originalDraftVersion;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), KaleoDraftDefinition.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			KaleoDraftDefinition.class.getName(), getPrimaryKey(),
			defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public KaleoDraftDefinition toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, KaleoDraftDefinition>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KaleoDraftDefinitionImpl kaleoDraftDefinitionImpl =
			new KaleoDraftDefinitionImpl();

		kaleoDraftDefinitionImpl.setKaleoDraftDefinitionId(
			getKaleoDraftDefinitionId());
		kaleoDraftDefinitionImpl.setGroupId(getGroupId());
		kaleoDraftDefinitionImpl.setCompanyId(getCompanyId());
		kaleoDraftDefinitionImpl.setUserId(getUserId());
		kaleoDraftDefinitionImpl.setUserName(getUserName());
		kaleoDraftDefinitionImpl.setCreateDate(getCreateDate());
		kaleoDraftDefinitionImpl.setModifiedDate(getModifiedDate());
		kaleoDraftDefinitionImpl.setName(getName());
		kaleoDraftDefinitionImpl.setTitle(getTitle());
		kaleoDraftDefinitionImpl.setContent(getContent());
		kaleoDraftDefinitionImpl.setVersion(getVersion());
		kaleoDraftDefinitionImpl.setDraftVersion(getDraftVersion());

		kaleoDraftDefinitionImpl.resetOriginalValues();

		return kaleoDraftDefinitionImpl;
	}

	@Override
	public int compareTo(KaleoDraftDefinition kaleoDraftDefinition) {
		int value = 0;

		if (getDraftVersion() < kaleoDraftDefinition.getDraftVersion()) {
			value = -1;
		}
		else if (getDraftVersion() > kaleoDraftDefinition.getDraftVersion()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof KaleoDraftDefinition)) {
			return false;
		}

		KaleoDraftDefinition kaleoDraftDefinition =
			(KaleoDraftDefinition)object;

		long primaryKey = kaleoDraftDefinition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_setModifiedDate = false;
		_originalName = _name;

		_originalVersion = _version;

		_setOriginalVersion = false;

		_originalDraftVersion = _draftVersion;

		_setOriginalDraftVersion = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<KaleoDraftDefinition> toCacheModel() {
		KaleoDraftDefinitionCacheModel kaleoDraftDefinitionCacheModel =
			new KaleoDraftDefinitionCacheModel();

		kaleoDraftDefinitionCacheModel.kaleoDraftDefinitionId =
			getKaleoDraftDefinitionId();

		kaleoDraftDefinitionCacheModel.groupId = getGroupId();

		kaleoDraftDefinitionCacheModel.companyId = getCompanyId();

		kaleoDraftDefinitionCacheModel.userId = getUserId();

		kaleoDraftDefinitionCacheModel.userName = getUserName();

		String userName = kaleoDraftDefinitionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			kaleoDraftDefinitionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			kaleoDraftDefinitionCacheModel.createDate = createDate.getTime();
		}
		else {
			kaleoDraftDefinitionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			kaleoDraftDefinitionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			kaleoDraftDefinitionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		kaleoDraftDefinitionCacheModel.name = getName();

		String name = kaleoDraftDefinitionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			kaleoDraftDefinitionCacheModel.name = null;
		}

		kaleoDraftDefinitionCacheModel.title = getTitle();

		String title = kaleoDraftDefinitionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			kaleoDraftDefinitionCacheModel.title = null;
		}

		kaleoDraftDefinitionCacheModel.content = getContent();

		String content = kaleoDraftDefinitionCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			kaleoDraftDefinitionCacheModel.content = null;
		}

		kaleoDraftDefinitionCacheModel.version = getVersion();

		kaleoDraftDefinitionCacheModel.draftVersion = getDraftVersion();

		return kaleoDraftDefinitionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<KaleoDraftDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<KaleoDraftDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KaleoDraftDefinition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((KaleoDraftDefinition)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<KaleoDraftDefinition, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<KaleoDraftDefinition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KaleoDraftDefinition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((KaleoDraftDefinition)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, KaleoDraftDefinition>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _kaleoDraftDefinitionId;
	private long _groupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _content;
	private int _version;
	private int _originalVersion;
	private boolean _setOriginalVersion;
	private int _draftVersion;
	private int _originalDraftVersion;
	private boolean _setOriginalDraftVersion;
	private long _columnBitmask;
	private KaleoDraftDefinition _escapedModel;

}