bootstrap.memory_lock: false
cluster.name: es-cluster
discovery:
    zen:
        fd:
            ping_retries: 5
            ping_timeout: 120s
        ping.unicast.hosts: esmaster--cluster,esdata--cluster
http.cors.enabled: false
network.host: 0.0.0.0
node:
    data: true
    ingest: true
    master: false
    max_local_storage_nodes: 1
    name: "${HOSTNAME}"
xpack:
    security:
        authc:
            anonymous:
                roles: healthcheck_user
                username: anonymous_user
        enabled: true
        http:
            ssl:
                enabled: false
        transport:
            ssl:
                certificate: /usr/share/elasticsearch/config/certificates/${HOSTNAME}/${HOSTNAME}.crt
                certificate_authorities: /usr/share/elasticsearch/config/certificates/ca/ca.crt
                enabled: true
                key: /usr/share/elasticsearch/config/certificates/${HOSTNAME}/${HOSTNAME}.key
                verification_mode: certificate