/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.release.notes.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.customer.release.notes.model.ReleaseNotes;
import com.liferay.osb.customer.release.notes.model.ReleaseNotesModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ReleaseNotes service. Represents a row in the &quot;RN_ReleaseNotes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReleaseNotesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReleaseNotesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReleaseNotesImpl
 * @generated
 */
public class ReleaseNotesModelImpl
	extends BaseModelImpl<ReleaseNotes> implements ReleaseNotesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a release notes model instance should use the <code>ReleaseNotes</code> interface instead.
	 */
	public static final String TABLE_NAME = "RN_ReleaseNotes";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"releaseNotesId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"jiraIssueKeys", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("releaseNotesId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jiraIssueKeys", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table RN_ReleaseNotes (uuid_ VARCHAR(75) null,releaseNotesId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,jiraIssueKeys TEXT null)";

	public static final String TABLE_SQL_DROP = "drop table RN_ReleaseNotes";

	public static final String ORDER_BY_JPQL =
		" ORDER BY releaseNotes.releaseNotesId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY RN_ReleaseNotes.releaseNotesId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.release.notes.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.customer.release.notes.model.ReleaseNotes"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.release.notes.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.customer.release.notes.model.ReleaseNotes"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.customer.release.notes.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.customer.release.notes.model.ReleaseNotes"),
		true);

	public static final long JIRAISSUEKEYS_COLUMN_BITMASK = 1L;

	public static final long NAME_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long RELEASENOTESID_COLUMN_BITMASK = 8L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.customer.release.notes.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.customer.release.notes.model.ReleaseNotes"));

	public ReleaseNotesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _releaseNotesId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setReleaseNotesId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _releaseNotesId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReleaseNotes.class;
	}

	@Override
	public String getModelClassName() {
		return ReleaseNotes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReleaseNotes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReleaseNotes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReleaseNotes, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ReleaseNotes)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReleaseNotes, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReleaseNotes, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReleaseNotes)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReleaseNotes, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReleaseNotes, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ReleaseNotes>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ReleaseNotes.class.getClassLoader(), ReleaseNotes.class,
			ModelWrapper.class);

		try {
			Constructor<ReleaseNotes> constructor =
				(Constructor<ReleaseNotes>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ReleaseNotes, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReleaseNotes, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReleaseNotes, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ReleaseNotes, Object>>();
		Map<String, BiConsumer<ReleaseNotes, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ReleaseNotes, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object uuidObject) {

					releaseNotes.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"releaseNotesId",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getReleaseNotesId();
				}

			});
		attributeSetterBiConsumers.put(
			"releaseNotesId",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object releaseNotesIdObject) {

					releaseNotes.setReleaseNotesId((Long)releaseNotesIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object userIdObject) {

					releaseNotes.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object userNameObject) {

					releaseNotes.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object createDateObject) {

					releaseNotes.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object modifiedDateObject) {

					releaseNotes.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object nameObject) {

					releaseNotes.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"jiraIssueKeys",
			new Function<ReleaseNotes, Object>() {

				@Override
				public Object apply(ReleaseNotes releaseNotes) {
					return releaseNotes.getJiraIssueKeys();
				}

			});
		attributeSetterBiConsumers.put(
			"jiraIssueKeys",
			new BiConsumer<ReleaseNotes, Object>() {

				@Override
				public void accept(
					ReleaseNotes releaseNotes, Object jiraIssueKeysObject) {

					releaseNotes.setJiraIssueKeys((String)jiraIssueKeysObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getReleaseNotesId() {
		return _releaseNotesId;
	}

	@Override
	public void setReleaseNotesId(long releaseNotesId) {
		_releaseNotesId = releaseNotesId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public String getJiraIssueKeys() {
		if (_jiraIssueKeys == null) {
			return "";
		}
		else {
			return _jiraIssueKeys;
		}
	}

	@Override
	public void setJiraIssueKeys(String jiraIssueKeys) {
		_columnBitmask |= JIRAISSUEKEYS_COLUMN_BITMASK;

		if (_originalJiraIssueKeys == null) {
			_originalJiraIssueKeys = _jiraIssueKeys;
		}

		_jiraIssueKeys = jiraIssueKeys;
	}

	public String getOriginalJiraIssueKeys() {
		return GetterUtil.getString(_originalJiraIssueKeys);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ReleaseNotes.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReleaseNotes toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReleaseNotes>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReleaseNotesImpl releaseNotesImpl = new ReleaseNotesImpl();

		releaseNotesImpl.setUuid(getUuid());
		releaseNotesImpl.setReleaseNotesId(getReleaseNotesId());
		releaseNotesImpl.setUserId(getUserId());
		releaseNotesImpl.setUserName(getUserName());
		releaseNotesImpl.setCreateDate(getCreateDate());
		releaseNotesImpl.setModifiedDate(getModifiedDate());
		releaseNotesImpl.setName(getName());
		releaseNotesImpl.setJiraIssueKeys(getJiraIssueKeys());

		releaseNotesImpl.resetOriginalValues();

		return releaseNotesImpl;
	}

	@Override
	public int compareTo(ReleaseNotes releaseNotes) {
		int value = 0;

		if (getReleaseNotesId() < releaseNotes.getReleaseNotesId()) {
			value = -1;
		}
		else if (getReleaseNotesId() > releaseNotes.getReleaseNotesId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReleaseNotes)) {
			return false;
		}

		ReleaseNotes releaseNotes = (ReleaseNotes)object;

		long primaryKey = releaseNotes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_setModifiedDate = false;
		_originalName = _name;

		_originalJiraIssueKeys = _jiraIssueKeys;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReleaseNotes> toCacheModel() {
		ReleaseNotesCacheModel releaseNotesCacheModel =
			new ReleaseNotesCacheModel();

		releaseNotesCacheModel.uuid = getUuid();

		String uuid = releaseNotesCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			releaseNotesCacheModel.uuid = null;
		}

		releaseNotesCacheModel.releaseNotesId = getReleaseNotesId();

		releaseNotesCacheModel.userId = getUserId();

		releaseNotesCacheModel.userName = getUserName();

		String userName = releaseNotesCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			releaseNotesCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			releaseNotesCacheModel.createDate = createDate.getTime();
		}
		else {
			releaseNotesCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			releaseNotesCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			releaseNotesCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		releaseNotesCacheModel.name = getName();

		String name = releaseNotesCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			releaseNotesCacheModel.name = null;
		}

		releaseNotesCacheModel.jiraIssueKeys = getJiraIssueKeys();

		String jiraIssueKeys = releaseNotesCacheModel.jiraIssueKeys;

		if ((jiraIssueKeys != null) && (jiraIssueKeys.length() == 0)) {
			releaseNotesCacheModel.jiraIssueKeys = null;
		}

		return releaseNotesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReleaseNotes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReleaseNotes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReleaseNotes, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ReleaseNotes)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ReleaseNotes, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ReleaseNotes, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReleaseNotes, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ReleaseNotes)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReleaseNotes>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _releaseNotesId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _jiraIssueKeys;
	private String _originalJiraIssueKeys;
	private long _columnBitmask;
	private ReleaseNotes _escapedModel;

}