endpoints.enabled=false
endpoints.health.enabled=true
endpoints.prometheus.enabled=true
management.security.enabled=false
osb.asah.security.token=9ZPgFSdEntvRPjgRcstSgkUCBzKyjz4hbuaGbdW9h3BHcJbZLuuSqd6BpFLhRErS
osb.asah.seo.semrush.api.key=1fca48a102e9832ce67f564330b135ac
osb.asah.seo.semrush.databases.limit=5
osb.asah.seo.semrush.url.adwords.display.limit=10
osb.asah.seo.semrush.url.organic.display.limit=5