endpoints.enabled=false
endpoints.health.enabled=true
endpoints.prometheus.enabled=true
management.security.enabled=false
osb.asah.security.token=9ZPgFSdEntvRPjgRcstSgkUCBzKyjz4hbuaGbdW9h3BHcJbZLuuSqd6BpFLhRErS
osb.asah.seo.semrush.url.organic.display.limit=25
osb.asah.seo.semrush.url.adwords.display.limit=10