##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/source-formatter.properties
## for available properties.
##

    language.keys.check.excludes=\
        modules/dxp/apps/osb/osb-customer/osb-customer-web/**