/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.loop.asset.entry.set.model.impl;

import com.liferay.osb.loop.asset.entry.set.model.AssetEntrySet;
import com.liferay.osb.loop.asset.entry.set.service.AssetEntrySetLocalServiceUtil;

/**
 * The extended model base implementation for the AssetEntrySet service. Represents a row in the &quot;AssetEntrySet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetEntrySetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntrySetImpl
 * @see AssetEntrySet
 * @generated
 */
public abstract class AssetEntrySetBaseImpl
	extends AssetEntrySetModelImpl implements AssetEntrySet {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset entry set model instance should use the <code>AssetEntrySet</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AssetEntrySetLocalServiceUtil.addAssetEntrySet(this);
		}
		else {
			AssetEntrySetLocalServiceUtil.updateAssetEntrySet(this);
		}
	}

}