##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    language.keys.check.excludes=\
        modules/private/apps/watson/watson-web/**

    source.formatter.excludes=\
        modules/private/apps/watson/watson-web/src/main/resources/META-INF/resources/js/dist/**,\
        modules/private/apps/watson/watson-web/src/main/resources/alloy_mvc/jsp/util/init.jsp,\
        modules/private/apps/watson/watson-web/src/main/resources/alloy_mvc/jsp/watson/views/init.jsp,\
        modules/private/apps/watson/watson-web/src/main/resources/alloy_mvc/jsp/watson/views/config/_input_config.jsp,\
        modules/private/apps/watson/watson-web/src/main/resources/alloy_mvc/jsp/watson/models/base**