/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.pulpo.connector.de.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import com.liferay.pulpo.connector.de.model.ConnectorTransaction;
import com.liferay.pulpo.connector.de.model.ConnectorTransactionModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ConnectorTransaction service. Represents a row in the &quot;PULPO_ConnectorTransaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ConnectorTransactionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConnectorTransactionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConnectorTransactionImpl
 * @see ConnectorTransaction
 * @see ConnectorTransactionModel
 * @generated
 */
@ProviderType
public class ConnectorTransactionModelImpl extends BaseModelImpl<ConnectorTransaction>
	implements ConnectorTransactionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a connector transaction model instance should use the {@link ConnectorTransaction} interface instead.
	 */
	public static final String TABLE_NAME = "PULPO_ConnectorTransaction";
	public static final Object[][] TABLE_COLUMNS = {
			{ "connectorTransactionId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "connectorTransactionUuid", Types.VARCHAR },
			{ "operation", Types.VARCHAR },
			{ "status", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("connectorTransactionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("connectorTransactionUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("operation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table PULPO_ConnectorTransaction (connectorTransactionId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,connectorTransactionUuid VARCHAR(75) null,operation VARCHAR(75) null,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table PULPO_ConnectorTransaction";
	public static final String ORDER_BY_JPQL = " ORDER BY connectorTransaction.connectorTransactionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY PULPO_ConnectorTransaction.connectorTransactionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.pulpo.connector.de.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.pulpo.connector.de.model.ConnectorTransaction"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.pulpo.connector.de.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.pulpo.connector.de.model.ConnectorTransaction"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.pulpo.connector.de.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.pulpo.connector.de.model.ConnectorTransaction"),
			true);
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;
	public static final long CLASSPK_COLUMN_BITMASK = 2L;
	public static final long CONNECTORTRANSACTIONUUID_COLUMN_BITMASK = 4L;
	public static final long CONNECTORTRANSACTIONID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.pulpo.connector.de.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.pulpo.connector.de.model.ConnectorTransaction"));

	public ConnectorTransactionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _connectorTransactionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setConnectorTransactionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _connectorTransactionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConnectorTransaction.class;
	}

	@Override
	public String getModelClassName() {
		return ConnectorTransaction.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("connectorTransactionId", getConnectorTransactionId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("connectorTransactionUuid", getConnectorTransactionUuid());
		attributes.put("operation", getOperation());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long connectorTransactionId = (Long)attributes.get(
				"connectorTransactionId");

		if (connectorTransactionId != null) {
			setConnectorTransactionId(connectorTransactionId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		String connectorTransactionUuid = (String)attributes.get(
				"connectorTransactionUuid");

		if (connectorTransactionUuid != null) {
			setConnectorTransactionUuid(connectorTransactionUuid);
		}

		String operation = (String)attributes.get("operation");

		if (operation != null) {
			setOperation(operation);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@Override
	public long getConnectorTransactionId() {
		return _connectorTransactionId;
	}

	@Override
	public void setConnectorTransactionId(long connectorTransactionId) {
		_columnBitmask = -1L;

		_connectorTransactionId = connectorTransactionId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!_setOriginalClassNameId) {
			_setOriginalClassNameId = true;

			_originalClassNameId = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		return _originalClassNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	@Override
	public String getConnectorTransactionUuid() {
		if (_connectorTransactionUuid == null) {
			return "";
		}
		else {
			return _connectorTransactionUuid;
		}
	}

	@Override
	public void setConnectorTransactionUuid(String connectorTransactionUuid) {
		_columnBitmask |= CONNECTORTRANSACTIONUUID_COLUMN_BITMASK;

		if (_originalConnectorTransactionUuid == null) {
			_originalConnectorTransactionUuid = _connectorTransactionUuid;
		}

		_connectorTransactionUuid = connectorTransactionUuid;
	}

	public String getOriginalConnectorTransactionUuid() {
		return GetterUtil.getString(_originalConnectorTransactionUuid);
	}

	@Override
	public String getOperation() {
		if (_operation == null) {
			return "";
		}
		else {
			return _operation;
		}
	}

	@Override
	public void setOperation(String operation) {
		_operation = operation;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ConnectorTransaction.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConnectorTransaction toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ConnectorTransaction)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConnectorTransactionImpl connectorTransactionImpl = new ConnectorTransactionImpl();

		connectorTransactionImpl.setConnectorTransactionId(getConnectorTransactionId());
		connectorTransactionImpl.setCompanyId(getCompanyId());
		connectorTransactionImpl.setUserId(getUserId());
		connectorTransactionImpl.setUserName(getUserName());
		connectorTransactionImpl.setCreateDate(getCreateDate());
		connectorTransactionImpl.setModifiedDate(getModifiedDate());
		connectorTransactionImpl.setClassNameId(getClassNameId());
		connectorTransactionImpl.setClassPK(getClassPK());
		connectorTransactionImpl.setConnectorTransactionUuid(getConnectorTransactionUuid());
		connectorTransactionImpl.setOperation(getOperation());
		connectorTransactionImpl.setStatus(getStatus());

		connectorTransactionImpl.resetOriginalValues();

		return connectorTransactionImpl;
	}

	@Override
	public int compareTo(ConnectorTransaction connectorTransaction) {
		int value = 0;

		if (getConnectorTransactionId() < connectorTransaction.getConnectorTransactionId()) {
			value = -1;
		}
		else if (getConnectorTransactionId() > connectorTransaction.getConnectorTransactionId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ConnectorTransaction)) {
			return false;
		}

		ConnectorTransaction connectorTransaction = (ConnectorTransaction)obj;

		long primaryKey = connectorTransaction.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ConnectorTransactionModelImpl connectorTransactionModelImpl = this;

		connectorTransactionModelImpl._setModifiedDate = false;

		connectorTransactionModelImpl._originalClassNameId = connectorTransactionModelImpl._classNameId;

		connectorTransactionModelImpl._setOriginalClassNameId = false;

		connectorTransactionModelImpl._originalClassPK = connectorTransactionModelImpl._classPK;

		connectorTransactionModelImpl._setOriginalClassPK = false;

		connectorTransactionModelImpl._originalConnectorTransactionUuid = connectorTransactionModelImpl._connectorTransactionUuid;

		connectorTransactionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ConnectorTransaction> toCacheModel() {
		ConnectorTransactionCacheModel connectorTransactionCacheModel = new ConnectorTransactionCacheModel();

		connectorTransactionCacheModel.connectorTransactionId = getConnectorTransactionId();

		connectorTransactionCacheModel.companyId = getCompanyId();

		connectorTransactionCacheModel.userId = getUserId();

		connectorTransactionCacheModel.userName = getUserName();

		String userName = connectorTransactionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			connectorTransactionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			connectorTransactionCacheModel.createDate = createDate.getTime();
		}
		else {
			connectorTransactionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			connectorTransactionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			connectorTransactionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		connectorTransactionCacheModel.classNameId = getClassNameId();

		connectorTransactionCacheModel.classPK = getClassPK();

		connectorTransactionCacheModel.connectorTransactionUuid = getConnectorTransactionUuid();

		String connectorTransactionUuid = connectorTransactionCacheModel.connectorTransactionUuid;

		if ((connectorTransactionUuid != null) &&
				(connectorTransactionUuid.length() == 0)) {
			connectorTransactionCacheModel.connectorTransactionUuid = null;
		}

		connectorTransactionCacheModel.operation = getOperation();

		String operation = connectorTransactionCacheModel.operation;

		if ((operation != null) && (operation.length() == 0)) {
			connectorTransactionCacheModel.operation = null;
		}

		connectorTransactionCacheModel.status = getStatus();

		String status = connectorTransactionCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			connectorTransactionCacheModel.status = null;
		}

		return connectorTransactionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{connectorTransactionId=");
		sb.append(getConnectorTransactionId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", connectorTransactionUuid=");
		sb.append(getConnectorTransactionUuid());
		sb.append(", operation=");
		sb.append(getOperation());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.pulpo.connector.de.model.ConnectorTransaction");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>connectorTransactionId</column-name><column-value><![CDATA[");
		sb.append(getConnectorTransactionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>connectorTransactionUuid</column-name><column-value><![CDATA[");
		sb.append(getConnectorTransactionUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>operation</column-name><column-value><![CDATA[");
		sb.append(getOperation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ConnectorTransaction.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ConnectorTransaction.class
		};
	private long _connectorTransactionId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _originalClassNameId;
	private boolean _setOriginalClassNameId;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private String _connectorTransactionUuid;
	private String _originalConnectorTransactionUuid;
	private String _operation;
	private String _status;
	private long _columnBitmask;
	private ConnectorTransaction _escapedModel;
}