##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

##
## Git
##

    git.liferay.portal.branch=7.0.x

##
## Checkstyle Properties
##

    checkstyle.JSONUtilCheck.enabled=false

    checkstyle.UnprocessedExceptionCheck.enabled=false

    checkstyle.VariableDeclarationAsUsedCheck.enabled=false

    checkstyle.VariableNameCheck.enabled=false

##
## Source Check Properties
##

    source.check.BNDSuiteCheck.enabled=false

    source.check.GradleDependencyArtifactsCheck.enabled=false

    source.check.JavaAPISignatureCheck.enabled=false

    source.check.JavaDeprecatedKernelClassesCheck.enabled=false

    source.check.JavaServiceTrackerFactoryCheck.enabled=false

    source.check.PropertiesLanguageKeysCheck.enabled=false