##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

##
## Git
##

    git.liferay.portal.branch=7.0.x

##
## Source Check Properties
##

    source.check.bnd.suite.check.enabled=false

    source.check.java.api.signature.check.enabled=false

    source.check.java.deprecated.kernel.classes.check.enabled=false

    source.check.java.service.tracker.factory.check.enabled=false

    source.check.properties.language.keys.check.enabled=false