/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.customer.release.notes.jira.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the JIRAProjectVersion service. Represents a row in the &quot;projectversion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.customer.release.notes.jira.model.impl.JIRAProjectVersionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.customer.release.notes.jira.model.impl.JIRAProjectVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JIRAProjectVersion
 * @see com.liferay.osb.customer.release.notes.jira.model.impl.JIRAProjectVersionImpl
 * @see com.liferay.osb.customer.release.notes.jira.model.impl.JIRAProjectVersionModelImpl
 * @generated
 */
@ProviderType
public interface JIRAProjectVersionModel extends BaseModel<JIRAProjectVersion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira project version model instance should use the {@link JIRAProjectVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this jira project version.
	 *
	 * @return the primary key of this jira project version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira project version.
	 *
	 * @param primaryKey the primary key of this jira project version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira project version ID of this jira project version.
	 *
	 * @return the jira project version ID of this jira project version
	 */
	public long getJiraProjectVersionId();

	/**
	 * Sets the jira project version ID of this jira project version.
	 *
	 * @param jiraProjectVersionId the jira project version ID of this jira project version
	 */
	public void setJiraProjectVersionId(long jiraProjectVersionId);

	/**
	 * Returns the jira project ID of this jira project version.
	 *
	 * @return the jira project ID of this jira project version
	 */
	public long getJiraProjectId();

	/**
	 * Sets the jira project ID of this jira project version.
	 *
	 * @param jiraProjectId the jira project ID of this jira project version
	 */
	public void setJiraProjectId(long jiraProjectId);

	/**
	 * Returns the name of this jira project version.
	 *
	 * @return the name of this jira project version
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this jira project version.
	 *
	 * @param name the name of this jira project version
	 */
	public void setName(String name);

	/**
	 * Returns the released of this jira project version.
	 *
	 * @return the released of this jira project version
	 */
	@AutoEscape
	public String getReleased();

	/**
	 * Sets the released of this jira project version.
	 *
	 * @param released the released of this jira project version
	 */
	public void setReleased(String released);

	/**
	 * Returns the archived of this jira project version.
	 *
	 * @return the archived of this jira project version
	 */
	@AutoEscape
	public String getArchived();

	/**
	 * Sets the archived of this jira project version.
	 *
	 * @param archived the archived of this jira project version
	 */
	public void setArchived(String archived);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JIRAProjectVersion jiraProjectVersion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JIRAProjectVersion> toCacheModel();

	@Override
	public JIRAProjectVersion toEscapedModel();

	@Override
	public JIRAProjectVersion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}