/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.release.notes.jira.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the JIRAProject service. Represents a row in the &quot;project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.customer.release.notes.jira.model.impl.JIRAProjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.customer.release.notes.jira.model.impl.JIRAProjectImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JIRAProject
 * @generated
 */
@ProviderType
public interface JIRAProjectModel extends BaseModel<JIRAProject> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira project model instance should use the {@link JIRAProject} interface instead.
	 */

	/**
	 * Returns the primary key of this jira project.
	 *
	 * @return the primary key of this jira project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira project.
	 *
	 * @param primaryKey the primary key of this jira project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira project ID of this jira project.
	 *
	 * @return the jira project ID of this jira project
	 */
	public long getJiraProjectId();

	/**
	 * Sets the jira project ID of this jira project.
	 *
	 * @param jiraProjectId the jira project ID of this jira project
	 */
	public void setJiraProjectId(long jiraProjectId);

	/**
	 * Returns the key of this jira project.
	 *
	 * @return the key of this jira project
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this jira project.
	 *
	 * @param key the key of this jira project
	 */
	public void setKey(String key);

	/**
	 * Returns the name of this jira project.
	 *
	 * @return the name of this jira project
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this jira project.
	 *
	 * @param name the name of this jira project
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JIRAProject jiraProject);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JIRAProject> toCacheModel();

	@Override
	public JIRAProject toEscapedModel();

	@Override
	public JIRAProject toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}