/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.customer.release.notes.jira.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the JIRAIssue service. Represents a row in the &quot;jiraissue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.customer.release.notes.jira.model.impl.JIRAIssueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.customer.release.notes.jira.model.impl.JIRAIssueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JIRAIssue
 * @see com.liferay.osb.customer.release.notes.jira.model.impl.JIRAIssueImpl
 * @see com.liferay.osb.customer.release.notes.jira.model.impl.JIRAIssueModelImpl
 * @generated
 */
@ProviderType
public interface JIRAIssueModel extends BaseModel<JIRAIssue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jira issue model instance should use the {@link JIRAIssue} interface instead.
	 */

	/**
	 * Returns the primary key of this jira issue.
	 *
	 * @return the primary key of this jira issue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this jira issue.
	 *
	 * @param primaryKey the primary key of this jira issue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the jira issue ID of this jira issue.
	 *
	 * @return the jira issue ID of this jira issue
	 */
	public long getJiraIssueId();

	/**
	 * Sets the jira issue ID of this jira issue.
	 *
	 * @param jiraIssueId the jira issue ID of this jira issue
	 */
	public void setJiraIssueId(long jiraIssueId);

	/**
	 * Returns the jira project ID of this jira issue.
	 *
	 * @return the jira project ID of this jira issue
	 */
	public long getJiraProjectId();

	/**
	 * Sets the jira project ID of this jira issue.
	 *
	 * @param jiraProjectId the jira project ID of this jira issue
	 */
	public void setJiraProjectId(long jiraProjectId);

	/**
	 * Returns the issue number of this jira issue.
	 *
	 * @return the issue number of this jira issue
	 */
	public long getIssueNumber();

	/**
	 * Sets the issue number of this jira issue.
	 *
	 * @param issueNumber the issue number of this jira issue
	 */
	public void setIssueNumber(long issueNumber);

	/**
	 * Returns the type of this jira issue.
	 *
	 * @return the type of this jira issue
	 */
	public int getType();

	/**
	 * Sets the type of this jira issue.
	 *
	 * @param type the type of this jira issue
	 */
	public void setType(int type);

	/**
	 * Returns the summary of this jira issue.
	 *
	 * @return the summary of this jira issue
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this jira issue.
	 *
	 * @param summary the summary of this jira issue
	 */
	public void setSummary(String summary);

	/**
	 * Returns the description of this jira issue.
	 *
	 * @return the description of this jira issue
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this jira issue.
	 *
	 * @param description the description of this jira issue
	 */
	public void setDescription(String description);

	/**
	 * Returns the priority of this jira issue.
	 *
	 * @return the priority of this jira issue
	 */
	public int getPriority();

	/**
	 * Sets the priority of this jira issue.
	 *
	 * @param priority the priority of this jira issue
	 */
	public void setPriority(int priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JIRAIssue jiraIssue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JIRAIssue> toCacheModel();

	@Override
	public JIRAIssue toEscapedModel();

	@Override
	public JIRAIssue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}