include-and-override=portlet-ext.properties

zendesk.article.permission.group.id=

zendesk.documentation.translator[global]=support-content-uat@liferay.com
zendesk.documentation.translator[ja]=support-content-jp-uat@liferay.com

zendesk.section.user.segment.id=