addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable

jdk: oraclejdk8

language: java

services:
    - docker

sudo: required

before_install:
    - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] && [ "$TRAVIS_BRANCH" != "7.0.x-private" ]; then
          echo "Terminating build since there is also a pull request build running.";
          travis_terminate 0;
       fi'

    - export CHROME_BIN=/usr/bin/google-chrome
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

    # Install Catch Reports

    - curl -O https://liferay-labs.github.io/reports-catcher/catch-reports.sh
    - chmod +x catch-reports.sh

    # moreutils (to be able to use sponge command)

    - sudo apt-get install moreutils

    # Install update_deployment_repository script

    - curl -O https://raw.githubusercontent.com/liferay-labs/sepia-deployment-scripts/master/travis/update_deployment_repository.sh
    - chmod +x update_deployment_repository.sh

install: true

before_script:

    # Quick checks

    - ./gradlew checkSourceFormatting pmdMain pmdTest pmdTestIntegration test

   # Check deployed structure

    - ./gradlew deploy

    - ls pulpo-connector-de-docker/deploy

    # Build Docker Image
    - ./gradlew buildAppDockerImage

script:
    # Fail when a line fails
    - set pipefail

    # Run Docker Image
    - export PULPO_ASSET_CONNECTOR_ENVIRONMENT_UNIQUENAME=dev
    - export PULPO_CONTACT_CONNECTOR_ENVIRONMENT_UNIQUENAME=dev
    - travis_wait ./gradlew runDocker

    - ./gradlew testIntegration

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
    - ./gradlew dumpJacoco
    - ./gradlew coveralls

    - 'if [ "$TRAVIS_EVENT_TYPE" = "push" ] && [ "$TRAVIS_BRANCH" = "7.0.x-private" ]; then
           ./gradlew pushAppDockerImage;
           ./update_deployment_repository.sh -p $TRAVIS_BUILD_DIR/pulpo-connector-de-deployment/travis/update_deployment_repository.env;
       fi'

after_script:
    - ./catch-reports.sh

    - docker logs com-liferay-pulpo-connector-de-private