include.directories=\
    pulpo-connector-de-assets-api/src,\
    pulpo-connector-de-assets-impl/src,\
    pulpo-connector-de-assets-properties-provider/src,\
    pulpo-connector-de-assets-url-provider/src,\
    pulpo-connector-de-contacts-api/src,\
    pulpo-connector-de-contacts-impl/src

report.title=Assets Connector