include-and-override=portlet-ext.properties

auto.deployer.email.from.address=no-reply@liferay.com
auto.deployer.email.to.address=kb@liferay.com
auto.deployer.email.to.name=Knowledge Base Team

liferay.docs.build.script=