/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.zendesk.documentation.sync.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the ZendeskSection service. Represents a row in the &quot;OSBCustomer_ZendeskSection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.customer.zendesk.documentation.sync.model.impl.ZendeskSectionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.customer.zendesk.documentation.sync.model.impl.ZendeskSectionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ZendeskSection
 * @generated
 */
@ProviderType
public interface ZendeskSectionModel
	extends BaseModel<ZendeskSection>, LocalizedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a zendesk section model instance should use the {@link ZendeskSection} interface instead.
	 */

	/**
	 * Returns the primary key of this zendesk section.
	 *
	 * @return the primary key of this zendesk section
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this zendesk section.
	 *
	 * @param primaryKey the primary key of this zendesk section
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the zendesk section ID of this zendesk section.
	 *
	 * @return the zendesk section ID of this zendesk section
	 */
	public long getZendeskSectionId();

	/**
	 * Sets the zendesk section ID of this zendesk section.
	 *
	 * @param zendeskSectionId the zendesk section ID of this zendesk section
	 */
	public void setZendeskSectionId(long zendeskSectionId);

	/**
	 * Returns the modified date of this zendesk section.
	 *
	 * @return the modified date of this zendesk section
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this zendesk section.
	 *
	 * @param modifiedDate the modified date of this zendesk section
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the zendesk category ID of this zendesk section.
	 *
	 * @return the zendesk category ID of this zendesk section
	 */
	public long getZendeskCategoryId();

	/**
	 * Sets the zendesk category ID of this zendesk section.
	 *
	 * @param zendeskCategoryId the zendesk category ID of this zendesk section
	 */
	public void setZendeskCategoryId(long zendeskCategoryId);

	/**
	 * Returns the documentation key of this zendesk section.
	 *
	 * @return the documentation key of this zendesk section
	 */
	@AutoEscape
	public String getDocumentationKey();

	/**
	 * Sets the documentation key of this zendesk section.
	 *
	 * @param documentationKey the documentation key of this zendesk section
	 */
	public void setDocumentationKey(String documentationKey);

	/**
	 * Returns the remote ID of this zendesk section.
	 *
	 * @return the remote ID of this zendesk section
	 */
	public long getRemoteId();

	/**
	 * Sets the remote ID of this zendesk section.
	 *
	 * @param remoteId the remote ID of this zendesk section
	 */
	public void setRemoteId(long remoteId);

	/**
	 * Returns the remote html url of this zendesk section.
	 *
	 * @return the remote html url of this zendesk section
	 */
	@AutoEscape
	public String getRemoteHtmlURL();

	/**
	 * Sets the remote html url of this zendesk section.
	 *
	 * @param remoteHtmlURL the remote html url of this zendesk section
	 */
	public void setRemoteHtmlURL(String remoteHtmlURL);

	/**
	 * Returns the remote name of this zendesk section.
	 *
	 * @return the remote name of this zendesk section
	 */
	public String getRemoteName();

	/**
	 * Returns the localized remote name of this zendesk section in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized remote name of this zendesk section
	 */
	@AutoEscape
	public String getRemoteName(Locale locale);

	/**
	 * Returns the localized remote name of this zendesk section in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized remote name of this zendesk section. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getRemoteName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized remote name of this zendesk section in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized remote name of this zendesk section
	 */
	@AutoEscape
	public String getRemoteName(String languageId);

	/**
	 * Returns the localized remote name of this zendesk section in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized remote name of this zendesk section
	 */
	@AutoEscape
	public String getRemoteName(String languageId, boolean useDefault);

	@AutoEscape
	public String getRemoteNameCurrentLanguageId();

	@AutoEscape
	public String getRemoteNameCurrentValue();

	/**
	 * Returns a map of the locales and localized remote names of this zendesk section.
	 *
	 * @return the locales and localized remote names of this zendesk section
	 */
	public Map<Locale, String> getRemoteNameMap();

	/**
	 * Sets the remote name of this zendesk section.
	 *
	 * @param remoteName the remote name of this zendesk section
	 */
	public void setRemoteName(String remoteName);

	/**
	 * Sets the localized remote name of this zendesk section in the language.
	 *
	 * @param remoteName the localized remote name of this zendesk section
	 * @param locale the locale of the language
	 */
	public void setRemoteName(String remoteName, Locale locale);

	/**
	 * Sets the localized remote name of this zendesk section in the language, and sets the default locale.
	 *
	 * @param remoteName the localized remote name of this zendesk section
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setRemoteName(
		String remoteName, Locale locale, Locale defaultLocale);

	public void setRemoteNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized remote names of this zendesk section from the map of locales and localized remote names.
	 *
	 * @param remoteNameMap the locales and localized remote names of this zendesk section
	 */
	public void setRemoteNameMap(Map<Locale, String> remoteNameMap);

	/**
	 * Sets the localized remote names of this zendesk section from the map of locales and localized remote names, and sets the default locale.
	 *
	 * @param remoteNameMap the locales and localized remote names of this zendesk section
	 * @param defaultLocale the default locale
	 */
	public void setRemoteNameMap(
		Map<Locale, String> remoteNameMap, Locale defaultLocale);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(ZendeskSection zendeskSection);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ZendeskSection> toCacheModel();

	@Override
	public ZendeskSection toEscapedModel();

	@Override
	public ZendeskSection toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}