/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.ticket.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.customer.ticket.model.TicketAttachment;
import com.liferay.osb.customer.ticket.model.TicketAttachmentModel;
import com.liferay.osb.customer.ticket.model.TicketAttachmentSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TicketAttachment service. Represents a row in the &quot;OSBCustomer_TicketAttachment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TicketAttachmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TicketAttachmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketAttachmentImpl
 * @see TicketAttachment
 * @see TicketAttachmentModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TicketAttachmentModelImpl extends BaseModelImpl<TicketAttachment>
	implements TicketAttachmentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ticket attachment model instance should use the {@link TicketAttachment} interface instead.
	 */
	public static final String TABLE_NAME = "OSBCustomer_TicketAttachment";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ticketAttachmentId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "accountEntryId", Types.BIGINT },
			{ "zendeskTicketId", Types.BIGINT },
			{ "fileRepositoryId", Types.VARCHAR },
			{ "fileName", Types.VARCHAR },
			{ "fileSize", Types.BIGINT },
			{ "type_", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ticketAttachmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accountEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("zendeskTicketId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileRepositoryId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileSize", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table OSBCustomer_TicketAttachment (ticketAttachmentId LONG not null primary key,userId LONG,userName VARCHAR(75) null,createDate DATE null,accountEntryId LONG,zendeskTicketId LONG,fileRepositoryId VARCHAR(75) null,fileName VARCHAR(255) null,fileSize LONG,type_ INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSBCustomer_TicketAttachment";
	public static final String ORDER_BY_JPQL = " ORDER BY ticketAttachment.ticketAttachmentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSBCustomer_TicketAttachment.ticketAttachmentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.ticket.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.customer.ticket.model.TicketAttachment"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.ticket.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.customer.ticket.model.TicketAttachment"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.ticket.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.customer.ticket.model.TicketAttachment"),
			true);
	public static final long TYPE_COLUMN_BITMASK = 1L;
	public static final long ZENDESKTICKETID_COLUMN_BITMASK = 2L;
	public static final long TICKETATTACHMENTID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TicketAttachment toModel(TicketAttachmentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TicketAttachment model = new TicketAttachmentImpl();

		model.setTicketAttachmentId(soapModel.getTicketAttachmentId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setAccountEntryId(soapModel.getAccountEntryId());
		model.setZendeskTicketId(soapModel.getZendeskTicketId());
		model.setFileRepositoryId(soapModel.getFileRepositoryId());
		model.setFileName(soapModel.getFileName());
		model.setFileSize(soapModel.getFileSize());
		model.setType(soapModel.getType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TicketAttachment> toModels(
		TicketAttachmentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TicketAttachment> models = new ArrayList<TicketAttachment>(soapModels.length);

		for (TicketAttachmentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.customer.ticket.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.customer.ticket.model.TicketAttachment"));

	public TicketAttachmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ticketAttachmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTicketAttachmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ticketAttachmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TicketAttachment.class;
	}

	@Override
	public String getModelClassName() {
		return TicketAttachment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ticketAttachmentId", getTicketAttachmentId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("accountEntryId", getAccountEntryId());
		attributes.put("zendeskTicketId", getZendeskTicketId());
		attributes.put("fileRepositoryId", getFileRepositoryId());
		attributes.put("fileName", getFileName());
		attributes.put("fileSize", getFileSize());
		attributes.put("type", getType());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ticketAttachmentId = (Long)attributes.get("ticketAttachmentId");

		if (ticketAttachmentId != null) {
			setTicketAttachmentId(ticketAttachmentId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long accountEntryId = (Long)attributes.get("accountEntryId");

		if (accountEntryId != null) {
			setAccountEntryId(accountEntryId);
		}

		Long zendeskTicketId = (Long)attributes.get("zendeskTicketId");

		if (zendeskTicketId != null) {
			setZendeskTicketId(zendeskTicketId);
		}

		String fileRepositoryId = (String)attributes.get("fileRepositoryId");

		if (fileRepositoryId != null) {
			setFileRepositoryId(fileRepositoryId);
		}

		String fileName = (String)attributes.get("fileName");

		if (fileName != null) {
			setFileName(fileName);
		}

		Long fileSize = (Long)attributes.get("fileSize");

		if (fileSize != null) {
			setFileSize(fileSize);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}
	}

	@JSON
	@Override
	public long getTicketAttachmentId() {
		return _ticketAttachmentId;
	}

	@Override
	public void setTicketAttachmentId(long ticketAttachmentId) {
		_ticketAttachmentId = ticketAttachmentId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public long getAccountEntryId() {
		return _accountEntryId;
	}

	@Override
	public void setAccountEntryId(long accountEntryId) {
		_accountEntryId = accountEntryId;
	}

	@JSON
	@Override
	public long getZendeskTicketId() {
		return _zendeskTicketId;
	}

	@Override
	public void setZendeskTicketId(long zendeskTicketId) {
		_columnBitmask |= ZENDESKTICKETID_COLUMN_BITMASK;

		if (!_setOriginalZendeskTicketId) {
			_setOriginalZendeskTicketId = true;

			_originalZendeskTicketId = _zendeskTicketId;
		}

		_zendeskTicketId = zendeskTicketId;
	}

	public long getOriginalZendeskTicketId() {
		return _originalZendeskTicketId;
	}

	@JSON
	@Override
	public String getFileRepositoryId() {
		if (_fileRepositoryId == null) {
			return "";
		}
		else {
			return _fileRepositoryId;
		}
	}

	@Override
	public void setFileRepositoryId(String fileRepositoryId) {
		_fileRepositoryId = fileRepositoryId;
	}

	@JSON
	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		_fileName = fileName;
	}

	@JSON
	@Override
	public long getFileSize() {
		return _fileSize;
	}

	@Override
	public void setFileSize(long fileSize) {
		_fileSize = fileSize;
	}

	@JSON
	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!_setOriginalType) {
			_setOriginalType = true;

			_originalType = _type;
		}

		_type = type;
	}

	public int getOriginalType() {
		return _originalType;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TicketAttachment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TicketAttachment toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TicketAttachment)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TicketAttachmentImpl ticketAttachmentImpl = new TicketAttachmentImpl();

		ticketAttachmentImpl.setTicketAttachmentId(getTicketAttachmentId());
		ticketAttachmentImpl.setUserId(getUserId());
		ticketAttachmentImpl.setUserName(getUserName());
		ticketAttachmentImpl.setCreateDate(getCreateDate());
		ticketAttachmentImpl.setAccountEntryId(getAccountEntryId());
		ticketAttachmentImpl.setZendeskTicketId(getZendeskTicketId());
		ticketAttachmentImpl.setFileRepositoryId(getFileRepositoryId());
		ticketAttachmentImpl.setFileName(getFileName());
		ticketAttachmentImpl.setFileSize(getFileSize());
		ticketAttachmentImpl.setType(getType());

		ticketAttachmentImpl.resetOriginalValues();

		return ticketAttachmentImpl;
	}

	@Override
	public int compareTo(TicketAttachment ticketAttachment) {
		long primaryKey = ticketAttachment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TicketAttachment)) {
			return false;
		}

		TicketAttachment ticketAttachment = (TicketAttachment)obj;

		long primaryKey = ticketAttachment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TicketAttachmentModelImpl ticketAttachmentModelImpl = this;

		ticketAttachmentModelImpl._originalZendeskTicketId = ticketAttachmentModelImpl._zendeskTicketId;

		ticketAttachmentModelImpl._setOriginalZendeskTicketId = false;

		ticketAttachmentModelImpl._originalType = ticketAttachmentModelImpl._type;

		ticketAttachmentModelImpl._setOriginalType = false;

		ticketAttachmentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TicketAttachment> toCacheModel() {
		TicketAttachmentCacheModel ticketAttachmentCacheModel = new TicketAttachmentCacheModel();

		ticketAttachmentCacheModel.ticketAttachmentId = getTicketAttachmentId();

		ticketAttachmentCacheModel.userId = getUserId();

		ticketAttachmentCacheModel.userName = getUserName();

		String userName = ticketAttachmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ticketAttachmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ticketAttachmentCacheModel.createDate = createDate.getTime();
		}
		else {
			ticketAttachmentCacheModel.createDate = Long.MIN_VALUE;
		}

		ticketAttachmentCacheModel.accountEntryId = getAccountEntryId();

		ticketAttachmentCacheModel.zendeskTicketId = getZendeskTicketId();

		ticketAttachmentCacheModel.fileRepositoryId = getFileRepositoryId();

		String fileRepositoryId = ticketAttachmentCacheModel.fileRepositoryId;

		if ((fileRepositoryId != null) && (fileRepositoryId.length() == 0)) {
			ticketAttachmentCacheModel.fileRepositoryId = null;
		}

		ticketAttachmentCacheModel.fileName = getFileName();

		String fileName = ticketAttachmentCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			ticketAttachmentCacheModel.fileName = null;
		}

		ticketAttachmentCacheModel.fileSize = getFileSize();

		ticketAttachmentCacheModel.type = getType();

		return ticketAttachmentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{ticketAttachmentId=");
		sb.append(getTicketAttachmentId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", accountEntryId=");
		sb.append(getAccountEntryId());
		sb.append(", zendeskTicketId=");
		sb.append(getZendeskTicketId());
		sb.append(", fileRepositoryId=");
		sb.append(getFileRepositoryId());
		sb.append(", fileName=");
		sb.append(getFileName());
		sb.append(", fileSize=");
		sb.append(getFileSize());
		sb.append(", type=");
		sb.append(getType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.customer.ticket.model.TicketAttachment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ticketAttachmentId</column-name><column-value><![CDATA[");
		sb.append(getTicketAttachmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accountEntryId</column-name><column-value><![CDATA[");
		sb.append(getAccountEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zendeskTicketId</column-name><column-value><![CDATA[");
		sb.append(getZendeskTicketId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileRepositoryId</column-name><column-value><![CDATA[");
		sb.append(getFileRepositoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileName</column-name><column-value><![CDATA[");
		sb.append(getFileName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileSize</column-name><column-value><![CDATA[");
		sb.append(getFileSize());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TicketAttachment.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TicketAttachment.class, ModelWrapper.class
		};
	private long _ticketAttachmentId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private long _accountEntryId;
	private long _zendeskTicketId;
	private long _originalZendeskTicketId;
	private boolean _setOriginalZendeskTicketId;
	private String _fileRepositoryId;
	private String _fileName;
	private long _fileSize;
	private int _type;
	private int _originalType;
	private boolean _setOriginalType;
	private long _columnBitmask;
	private TicketAttachment _escapedModel;
}