/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestraySubtask service. Represents a row in the &quot;OSB_TestraySubtask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.testray.model.impl.TestraySubtaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.testray.model.impl.TestraySubtaskImpl</code>.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestraySubtask
 * @generated
 */
@ProviderType
public interface TestraySubtaskModel
	extends BaseModel<TestraySubtask>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a testray subtask model instance should use the {@link TestraySubtask} interface instead.
	 */

	/**
	 * Returns the primary key of this testray subtask.
	 *
	 * @return the primary key of this testray subtask
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this testray subtask.
	 *
	 * @param primaryKey the primary key of this testray subtask
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the testray subtask ID of this testray subtask.
	 *
	 * @return the testray subtask ID of this testray subtask
	 */
	public long getTestraySubtaskId();

	/**
	 * Sets the testray subtask ID of this testray subtask.
	 *
	 * @param testraySubtaskId the testray subtask ID of this testray subtask
	 */
	public void setTestraySubtaskId(long testraySubtaskId);

	/**
	 * Returns the group ID of this testray subtask.
	 *
	 * @return the group ID of this testray subtask
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this testray subtask.
	 *
	 * @param groupId the group ID of this testray subtask
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this testray subtask.
	 *
	 * @return the company ID of this testray subtask
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this testray subtask.
	 *
	 * @param companyId the company ID of this testray subtask
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this testray subtask.
	 *
	 * @return the user ID of this testray subtask
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this testray subtask.
	 *
	 * @param userId the user ID of this testray subtask
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this testray subtask.
	 *
	 * @return the user uuid of this testray subtask
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this testray subtask.
	 *
	 * @param userUuid the user uuid of this testray subtask
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this testray subtask.
	 *
	 * @return the user name of this testray subtask
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this testray subtask.
	 *
	 * @param userName the user name of this testray subtask
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this testray subtask.
	 *
	 * @return the create date of this testray subtask
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this testray subtask.
	 *
	 * @param createDate the create date of this testray subtask
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this testray subtask.
	 *
	 * @return the modified date of this testray subtask
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this testray subtask.
	 *
	 * @param modifiedDate the modified date of this testray subtask
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the comment mb message ID of this testray subtask.
	 *
	 * @return the comment mb message ID of this testray subtask
	 */
	public long getCommentMBMessageId();

	/**
	 * Sets the comment mb message ID of this testray subtask.
	 *
	 * @param commentMBMessageId the comment mb message ID of this testray subtask
	 */
	public void setCommentMBMessageId(long commentMBMessageId);

	/**
	 * Returns the merged to testray subtask ID of this testray subtask.
	 *
	 * @return the merged to testray subtask ID of this testray subtask
	 */
	public long getMergedToTestraySubtaskId();

	/**
	 * Sets the merged to testray subtask ID of this testray subtask.
	 *
	 * @param mergedToTestraySubtaskId the merged to testray subtask ID of this testray subtask
	 */
	public void setMergedToTestraySubtaskId(long mergedToTestraySubtaskId);

	/**
	 * Returns the split from testray subtask ID of this testray subtask.
	 *
	 * @return the split from testray subtask ID of this testray subtask
	 */
	public long getSplitFromTestraySubtaskId();

	/**
	 * Sets the split from testray subtask ID of this testray subtask.
	 *
	 * @param splitFromTestraySubtaskId the split from testray subtask ID of this testray subtask
	 */
	public void setSplitFromTestraySubtaskId(long splitFromTestraySubtaskId);

	/**
	 * Returns the testray task ID of this testray subtask.
	 *
	 * @return the testray task ID of this testray subtask
	 */
	public long getTestrayTaskId();

	/**
	 * Sets the testray task ID of this testray subtask.
	 *
	 * @param testrayTaskId the testray task ID of this testray subtask
	 */
	public void setTestrayTaskId(long testrayTaskId);

	/**
	 * Returns the name of this testray subtask.
	 *
	 * @return the name of this testray subtask
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this testray subtask.
	 *
	 * @param name the name of this testray subtask
	 */
	public void setName(String name);

	/**
	 * Returns the score of this testray subtask.
	 *
	 * @return the score of this testray subtask
	 */
	public int getScore();

	/**
	 * Sets the score of this testray subtask.
	 *
	 * @param score the score of this testray subtask
	 */
	public void setScore(int score);

	/**
	 * Returns the status of this testray subtask.
	 *
	 * @return the status of this testray subtask
	 */
	public int getStatus();

	/**
	 * Sets the status of this testray subtask.
	 *
	 * @param status the status of this testray subtask
	 */
	public void setStatus(int status);

	/**
	 * Returns the status update date of this testray subtask.
	 *
	 * @return the status update date of this testray subtask
	 */
	public Date getStatusUpdateDate();

	/**
	 * Sets the status update date of this testray subtask.
	 *
	 * @param statusUpdateDate the status update date of this testray subtask
	 */
	public void setStatusUpdateDate(Date statusUpdateDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TestraySubtask testraySubtask);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TestraySubtask> toCacheModel();

	@Override
	public TestraySubtask toEscapedModel();

	@Override
	public TestraySubtask toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}