/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestrayCaseResult service. Represents a row in the &quot;OSB_TestrayCaseResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.testray.model.impl.TestrayCaseResultModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.testray.model.impl.TestrayCaseResultImpl</code>.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayCaseResult
 * @generated
 */
@ProviderType
public interface TestrayCaseResultModel
	extends BaseModel<TestrayCaseResult>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a testray case result model instance should use the {@link TestrayCaseResult} interface instead.
	 */

	/**
	 * Returns the primary key of this testray case result.
	 *
	 * @return the primary key of this testray case result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this testray case result.
	 *
	 * @param primaryKey the primary key of this testray case result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the testray case result ID of this testray case result.
	 *
	 * @return the testray case result ID of this testray case result
	 */
	public long getTestrayCaseResultId();

	/**
	 * Sets the testray case result ID of this testray case result.
	 *
	 * @param testrayCaseResultId the testray case result ID of this testray case result
	 */
	public void setTestrayCaseResultId(long testrayCaseResultId);

	/**
	 * Returns the group ID of this testray case result.
	 *
	 * @return the group ID of this testray case result
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this testray case result.
	 *
	 * @param groupId the group ID of this testray case result
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this testray case result.
	 *
	 * @return the company ID of this testray case result
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this testray case result.
	 *
	 * @param companyId the company ID of this testray case result
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this testray case result.
	 *
	 * @return the user ID of this testray case result
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this testray case result.
	 *
	 * @param userId the user ID of this testray case result
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this testray case result.
	 *
	 * @return the user uuid of this testray case result
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this testray case result.
	 *
	 * @param userUuid the user uuid of this testray case result
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this testray case result.
	 *
	 * @return the user name of this testray case result
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this testray case result.
	 *
	 * @param userName the user name of this testray case result
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this testray case result.
	 *
	 * @return the create date of this testray case result
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this testray case result.
	 *
	 * @param createDate the create date of this testray case result
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this testray case result.
	 *
	 * @return the modified date of this testray case result
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this testray case result.
	 *
	 * @param modifiedDate the modified date of this testray case result
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the comment mb message ID of this testray case result.
	 *
	 * @return the comment mb message ID of this testray case result
	 */
	public long getCommentMBMessageId();

	/**
	 * Sets the comment mb message ID of this testray case result.
	 *
	 * @param commentMBMessageId the comment mb message ID of this testray case result
	 */
	public void setCommentMBMessageId(long commentMBMessageId);

	/**
	 * Returns the testray build ID of this testray case result.
	 *
	 * @return the testray build ID of this testray case result
	 */
	public long getTestrayBuildId();

	/**
	 * Sets the testray build ID of this testray case result.
	 *
	 * @param testrayBuildId the testray build ID of this testray case result
	 */
	public void setTestrayBuildId(long testrayBuildId);

	/**
	 * Returns the testray case ID of this testray case result.
	 *
	 * @return the testray case ID of this testray case result
	 */
	public long getTestrayCaseId();

	/**
	 * Sets the testray case ID of this testray case result.
	 *
	 * @param testrayCaseId the testray case ID of this testray case result
	 */
	public void setTestrayCaseId(long testrayCaseId);

	/**
	 * Returns the testray component ID of this testray case result.
	 *
	 * @return the testray component ID of this testray case result
	 */
	public long getTestrayComponentId();

	/**
	 * Sets the testray component ID of this testray case result.
	 *
	 * @param testrayComponentId the testray component ID of this testray case result
	 */
	public void setTestrayComponentId(long testrayComponentId);

	/**
	 * Returns the testray run ID of this testray case result.
	 *
	 * @return the testray run ID of this testray case result
	 */
	public long getTestrayRunId();

	/**
	 * Sets the testray run ID of this testray case result.
	 *
	 * @param testrayRunId the testray run ID of this testray case result
	 */
	public void setTestrayRunId(long testrayRunId);

	/**
	 * Returns the assigned user ID of this testray case result.
	 *
	 * @return the assigned user ID of this testray case result
	 */
	public long getAssignedUserId();

	/**
	 * Sets the assigned user ID of this testray case result.
	 *
	 * @param assignedUserId the assigned user ID of this testray case result
	 */
	public void setAssignedUserId(long assignedUserId);

	/**
	 * Returns the assigned user uuid of this testray case result.
	 *
	 * @return the assigned user uuid of this testray case result
	 */
	public String getAssignedUserUuid();

	/**
	 * Sets the assigned user uuid of this testray case result.
	 *
	 * @param assignedUserUuid the assigned user uuid of this testray case result
	 */
	public void setAssignedUserUuid(String assignedUserUuid);

	/**
	 * Returns the start date of this testray case result.
	 *
	 * @return the start date of this testray case result
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this testray case result.
	 *
	 * @param startDate the start date of this testray case result
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the closed date of this testray case result.
	 *
	 * @return the closed date of this testray case result
	 */
	public Date getClosedDate();

	/**
	 * Sets the closed date of this testray case result.
	 *
	 * @param closedDate the closed date of this testray case result
	 */
	public void setClosedDate(Date closedDate);

	/**
	 * Returns the attachments of this testray case result.
	 *
	 * @return the attachments of this testray case result
	 */
	@AutoEscape
	public String getAttachments();

	/**
	 * Sets the attachments of this testray case result.
	 *
	 * @param attachments the attachments of this testray case result
	 */
	public void setAttachments(String attachments);

	/**
	 * Returns the errors of this testray case result.
	 *
	 * @return the errors of this testray case result
	 */
	@AutoEscape
	public String getErrors();

	/**
	 * Sets the errors of this testray case result.
	 *
	 * @param errors the errors of this testray case result
	 */
	public void setErrors(String errors);

	/**
	 * Returns the status of this testray case result.
	 *
	 * @return the status of this testray case result
	 */
	public int getStatus();

	/**
	 * Sets the status of this testray case result.
	 *
	 * @param status the status of this testray case result
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TestrayCaseResult testrayCaseResult);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TestrayCaseResult> toCacheModel();

	@Override
	public TestrayCaseResult toEscapedModel();

	@Override
	public TestrayCaseResult toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}