/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestrayCase service. Represents a row in the &quot;OSB_TestrayCase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.testray.model.impl.TestrayCaseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.testray.model.impl.TestrayCaseImpl</code>.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayCase
 * @generated
 */
@ProviderType
public interface TestrayCaseModel
	extends BaseModel<TestrayCase>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a testray case model instance should use the {@link TestrayCase} interface instead.
	 */

	/**
	 * Returns the primary key of this testray case.
	 *
	 * @return the primary key of this testray case
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this testray case.
	 *
	 * @param primaryKey the primary key of this testray case
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the testray case ID of this testray case.
	 *
	 * @return the testray case ID of this testray case
	 */
	public long getTestrayCaseId();

	/**
	 * Sets the testray case ID of this testray case.
	 *
	 * @param testrayCaseId the testray case ID of this testray case
	 */
	public void setTestrayCaseId(long testrayCaseId);

	/**
	 * Returns the group ID of this testray case.
	 *
	 * @return the group ID of this testray case
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this testray case.
	 *
	 * @param groupId the group ID of this testray case
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this testray case.
	 *
	 * @return the company ID of this testray case
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this testray case.
	 *
	 * @param companyId the company ID of this testray case
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this testray case.
	 *
	 * @return the user ID of this testray case
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this testray case.
	 *
	 * @param userId the user ID of this testray case
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this testray case.
	 *
	 * @return the user uuid of this testray case
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this testray case.
	 *
	 * @param userUuid the user uuid of this testray case
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this testray case.
	 *
	 * @return the user name of this testray case
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this testray case.
	 *
	 * @param userName the user name of this testray case
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this testray case.
	 *
	 * @return the create date of this testray case
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this testray case.
	 *
	 * @param createDate the create date of this testray case
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this testray case.
	 *
	 * @return the modified date of this testray case
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this testray case.
	 *
	 * @param modifiedDate the modified date of this testray case
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the testray case type ID of this testray case.
	 *
	 * @return the testray case type ID of this testray case
	 */
	public long getTestrayCaseTypeId();

	/**
	 * Sets the testray case type ID of this testray case.
	 *
	 * @param testrayCaseTypeId the testray case type ID of this testray case
	 */
	public void setTestrayCaseTypeId(long testrayCaseTypeId);

	/**
	 * Returns the testray component ID of this testray case.
	 *
	 * @return the testray component ID of this testray case
	 */
	public long getTestrayComponentId();

	/**
	 * Sets the testray component ID of this testray case.
	 *
	 * @param testrayComponentId the testray component ID of this testray case
	 */
	public void setTestrayComponentId(long testrayComponentId);

	/**
	 * Returns the testray project ID of this testray case.
	 *
	 * @return the testray project ID of this testray case
	 */
	public long getTestrayProjectId();

	/**
	 * Sets the testray project ID of this testray case.
	 *
	 * @param testrayProjectId the testray project ID of this testray case
	 */
	public void setTestrayProjectId(long testrayProjectId);

	/**
	 * Returns the name of this testray case.
	 *
	 * @return the name of this testray case
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this testray case.
	 *
	 * @param name the name of this testray case
	 */
	public void setName(String name);

	/**
	 * Returns the description of this testray case.
	 *
	 * @return the description of this testray case
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this testray case.
	 *
	 * @param description the description of this testray case
	 */
	public void setDescription(String description);

	/**
	 * Returns the description type of this testray case.
	 *
	 * @return the description type of this testray case
	 */
	@AutoEscape
	public String getDescriptionType();

	/**
	 * Sets the description type of this testray case.
	 *
	 * @param descriptionType the description type of this testray case
	 */
	public void setDescriptionType(String descriptionType);

	/**
	 * Returns the origination key of this testray case.
	 *
	 * @return the origination key of this testray case
	 */
	public long getOriginationKey();

	/**
	 * Sets the origination key of this testray case.
	 *
	 * @param originationKey the origination key of this testray case
	 */
	public void setOriginationKey(long originationKey);

	/**
	 * Returns the priority of this testray case.
	 *
	 * @return the priority of this testray case
	 */
	public int getPriority();

	/**
	 * Sets the priority of this testray case.
	 *
	 * @param priority the priority of this testray case
	 */
	public void setPriority(int priority);

	/**
	 * Returns the estimated duration of this testray case.
	 *
	 * @return the estimated duration of this testray case
	 */
	public int getEstimatedDuration();

	/**
	 * Sets the estimated duration of this testray case.
	 *
	 * @param estimatedDuration the estimated duration of this testray case
	 */
	public void setEstimatedDuration(int estimatedDuration);

	/**
	 * Returns the steps of this testray case.
	 *
	 * @return the steps of this testray case
	 */
	@AutoEscape
	public String getSteps();

	/**
	 * Sets the steps of this testray case.
	 *
	 * @param steps the steps of this testray case
	 */
	public void setSteps(String steps);

	/**
	 * Returns the steps type of this testray case.
	 *
	 * @return the steps type of this testray case
	 */
	@AutoEscape
	public String getStepsType();

	/**
	 * Sets the steps type of this testray case.
	 *
	 * @param stepsType the steps type of this testray case
	 */
	public void setStepsType(String stepsType);

	/**
	 * Returns the case number of this testray case.
	 *
	 * @return the case number of this testray case
	 */
	public long getCaseNumber();

	/**
	 * Sets the case number of this testray case.
	 *
	 * @param caseNumber the case number of this testray case
	 */
	public void setCaseNumber(long caseNumber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TestrayCase testrayCase);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TestrayCase> toCacheModel();

	@Override
	public TestrayCase toEscapedModel();

	@Override
	public TestrayCase toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}