/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TestrayProductVersion service. Represents a row in the &quot;OSB_TestrayProductVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.testray.model.impl.TestrayProductVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.testray.model.impl.TestrayProductVersionImpl</code>.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayProductVersion
 * @generated
 */
@ProviderType
public interface TestrayProductVersionModel
	extends BaseModel<TestrayProductVersion>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a testray product version model instance should use the {@link TestrayProductVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this testray product version.
	 *
	 * @return the primary key of this testray product version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this testray product version.
	 *
	 * @param primaryKey the primary key of this testray product version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the testray product version ID of this testray product version.
	 *
	 * @return the testray product version ID of this testray product version
	 */
	public long getTestrayProductVersionId();

	/**
	 * Sets the testray product version ID of this testray product version.
	 *
	 * @param testrayProductVersionId the testray product version ID of this testray product version
	 */
	public void setTestrayProductVersionId(long testrayProductVersionId);

	/**
	 * Returns the group ID of this testray product version.
	 *
	 * @return the group ID of this testray product version
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this testray product version.
	 *
	 * @param groupId the group ID of this testray product version
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this testray product version.
	 *
	 * @return the company ID of this testray product version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this testray product version.
	 *
	 * @param companyId the company ID of this testray product version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this testray product version.
	 *
	 * @return the user ID of this testray product version
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this testray product version.
	 *
	 * @param userId the user ID of this testray product version
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this testray product version.
	 *
	 * @return the user uuid of this testray product version
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this testray product version.
	 *
	 * @param userUuid the user uuid of this testray product version
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this testray product version.
	 *
	 * @return the user name of this testray product version
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this testray product version.
	 *
	 * @param userName the user name of this testray product version
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this testray product version.
	 *
	 * @return the create date of this testray product version
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this testray product version.
	 *
	 * @param createDate the create date of this testray product version
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this testray product version.
	 *
	 * @return the modified date of this testray product version
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this testray product version.
	 *
	 * @param modifiedDate the modified date of this testray product version
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the testray project ID of this testray product version.
	 *
	 * @return the testray project ID of this testray product version
	 */
	public long getTestrayProjectId();

	/**
	 * Sets the testray project ID of this testray product version.
	 *
	 * @param testrayProjectId the testray project ID of this testray product version
	 */
	public void setTestrayProjectId(long testrayProjectId);

	/**
	 * Returns the name of this testray product version.
	 *
	 * @return the name of this testray product version
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this testray product version.
	 *
	 * @param name the name of this testray product version
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TestrayProductVersion testrayProductVersion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TestrayProductVersion> toCacheModel();

	@Override
	public TestrayProductVersion toEscapedModel();

	@Override
	public TestrayProductVersion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}