/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AccountWorker service. Represents a row in the &quot;OSB_AccountWorker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AccountWorkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AccountWorkerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountWorker
 * @see com.liferay.osb.model.impl.AccountWorkerImpl
 * @see com.liferay.osb.model.impl.AccountWorkerModelImpl
 * @generated
 */
@ProviderType
public interface AccountWorkerModel extends BaseModel<AccountWorker> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account worker model instance should use the {@link AccountWorker} interface instead.
	 */

	/**
	 * Returns the primary key of this account worker.
	 *
	 * @return the primary key of this account worker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account worker.
	 *
	 * @param primaryKey the primary key of this account worker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the account worker ID of this account worker.
	 *
	 * @return the account worker ID of this account worker
	 */
	public long getAccountWorkerId();

	/**
	 * Sets the account worker ID of this account worker.
	 *
	 * @param accountWorkerId the account worker ID of this account worker
	 */
	public void setAccountWorkerId(long accountWorkerId);

	/**
	 * Returns the user ID of this account worker.
	 *
	 * @return the user ID of this account worker
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this account worker.
	 *
	 * @param userId the user ID of this account worker
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this account worker.
	 *
	 * @return the user uuid of this account worker
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this account worker.
	 *
	 * @param userUuid the user uuid of this account worker
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the account entry ID of this account worker.
	 *
	 * @return the account entry ID of this account worker
	 */
	public long getAccountEntryId();

	/**
	 * Sets the account entry ID of this account worker.
	 *
	 * @param accountEntryId the account entry ID of this account worker
	 */
	public void setAccountEntryId(long accountEntryId);

	/**
	 * Returns the role of this account worker.
	 *
	 * @return the role of this account worker
	 */
	public int getRole();

	/**
	 * Sets the role of this account worker.
	 *
	 * @param role the role of this account worker
	 */
	public void setRole(int role);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AccountWorker accountWorker);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AccountWorker> toCacheModel();

	@Override
	public AccountWorker toEscapedModel();

	@Override
	public AccountWorker toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}