/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccountInformation service. Represents a row in the &quot;OSB_AccountInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AccountInformationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AccountInformationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountInformation
 * @see com.liferay.osb.model.impl.AccountInformationImpl
 * @see com.liferay.osb.model.impl.AccountInformationModelImpl
 * @generated
 */
public interface AccountInformationModel extends BaseModel<AccountInformation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account information model instance should use the {@link AccountInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this account information.
	 *
	 * @return the primary key of this account information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account information.
	 *
	 * @param primaryKey the primary key of this account information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the account information ID of this account information.
	 *
	 * @return the account information ID of this account information
	 */
	public long getAccountInformationId();

	/**
	 * Sets the account information ID of this account information.
	 *
	 * @param accountInformationId the account information ID of this account information
	 */
	public void setAccountInformationId(long accountInformationId);

	/**
	 * Returns the modified user ID of this account information.
	 *
	 * @return the modified user ID of this account information
	 */
	public long getModifiedUserId();

	/**
	 * Sets the modified user ID of this account information.
	 *
	 * @param modifiedUserId the modified user ID of this account information
	 */
	public void setModifiedUserId(long modifiedUserId);

	/**
	 * Returns the modified user uuid of this account information.
	 *
	 * @return the modified user uuid of this account information
	 * @throws SystemException if a system exception occurred
	 */
	public String getModifiedUserUuid() throws SystemException;

	/**
	 * Sets the modified user uuid of this account information.
	 *
	 * @param modifiedUserUuid the modified user uuid of this account information
	 */
	public void setModifiedUserUuid(String modifiedUserUuid);

	/**
	 * Returns the modified user name of this account information.
	 *
	 * @return the modified user name of this account information
	 */
	@AutoEscape
	public String getModifiedUserName();

	/**
	 * Sets the modified user name of this account information.
	 *
	 * @param modifiedUserName the modified user name of this account information
	 */
	public void setModifiedUserName(String modifiedUserName);

	/**
	 * Returns the modified date of this account information.
	 *
	 * @return the modified date of this account information
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account information.
	 *
	 * @param modifiedDate the modified date of this account information
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account entry ID of this account information.
	 *
	 * @return the account entry ID of this account information
	 */
	public long getAccountEntryId();

	/**
	 * Sets the account entry ID of this account information.
	 *
	 * @param accountEntryId the account entry ID of this account information
	 */
	public void setAccountEntryId(long accountEntryId);

	/**
	 * Returns the account project ID of this account information.
	 *
	 * @return the account project ID of this account information
	 */
	public long getAccountProjectId();

	/**
	 * Sets the account project ID of this account information.
	 *
	 * @param accountProjectId the account project ID of this account information
	 */
	public void setAccountProjectId(long accountProjectId);

	/**
	 * Returns the field ID of this account information.
	 *
	 * @return the field ID of this account information
	 */
	public int getFieldId();

	/**
	 * Sets the field ID of this account information.
	 *
	 * @param fieldId the field ID of this account information
	 */
	public void setFieldId(int fieldId);

	/**
	 * Returns the data of this account information.
	 *
	 * @return the data of this account information
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this account information.
	 *
	 * @param data the data of this account information
	 */
	public void setData(String data);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AccountInformation accountInformation);

	public int hashCode();

	public CacheModel<AccountInformation> toCacheModel();

	public AccountInformation toEscapedModel();

	public AccountInformation toUnescapedModel();

	public String toString();

	public String toXmlString();
}