/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppPricing service. Represents a row in the &quot;OSB_AppPricing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AppPricingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AppPricingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppPricing
 * @see com.liferay.osb.model.impl.AppPricingImpl
 * @see com.liferay.osb.model.impl.AppPricingModelImpl
 * @generated
 */
public interface AppPricingModel extends BaseModel<AppPricing> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app pricing model instance should use the {@link AppPricing} interface instead.
	 */

	/**
	 * Returns the primary key of this app pricing.
	 *
	 * @return the primary key of this app pricing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app pricing.
	 *
	 * @param primaryKey the primary key of this app pricing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app pricing ID of this app pricing.
	 *
	 * @return the app pricing ID of this app pricing
	 */
	public long getAppPricingId();

	/**
	 * Sets the app pricing ID of this app pricing.
	 *
	 * @param appPricingId the app pricing ID of this app pricing
	 */
	public void setAppPricingId(long appPricingId);

	/**
	 * Returns the user ID of this app pricing.
	 *
	 * @return the user ID of this app pricing
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this app pricing.
	 *
	 * @param userId the user ID of this app pricing
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this app pricing.
	 *
	 * @return the user uuid of this app pricing
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this app pricing.
	 *
	 * @param userUuid the user uuid of this app pricing
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this app pricing.
	 *
	 * @return the user name of this app pricing
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this app pricing.
	 *
	 * @param userName the user name of this app pricing
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this app pricing.
	 *
	 * @return the create date of this app pricing
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this app pricing.
	 *
	 * @param createDate the create date of this app pricing
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this app pricing.
	 *
	 * @return the modified date of this app pricing
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this app pricing.
	 *
	 * @param modifiedDate the modified date of this app pricing
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the app entry ID of this app pricing.
	 *
	 * @return the app entry ID of this app pricing
	 */
	public long getAppEntryId();

	/**
	 * Sets the app entry ID of this app pricing.
	 *
	 * @param appEntryId the app entry ID of this app pricing
	 */
	public void setAppEntryId(long appEntryId);

	/**
	 * Returns the app version ID of this app pricing.
	 *
	 * @return the app version ID of this app pricing
	 */
	public long getAppVersionId();

	/**
	 * Sets the app version ID of this app pricing.
	 *
	 * @param appVersionId the app version ID of this app pricing
	 */
	public void setAppVersionId(long appVersionId);

	/**
	 * Returns the name of this app pricing.
	 *
	 * @return the name of this app pricing
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this app pricing.
	 *
	 * @param name the name of this app pricing
	 */
	public void setName(String name);

	/**
	 * Returns the currency entry ID of this app pricing.
	 *
	 * @return the currency entry ID of this app pricing
	 */
	public long getCurrencyEntryId();

	/**
	 * Sets the currency entry ID of this app pricing.
	 *
	 * @param currencyEntryId the currency entry ID of this app pricing
	 */
	public void setCurrencyEntryId(long currencyEntryId);

	/**
	 * Returns the standard support price of this app pricing.
	 *
	 * @return the standard support price of this app pricing
	 */
	public double getStandardSupportPrice();

	/**
	 * Sets the standard support price of this app pricing.
	 *
	 * @param standardSupportPrice the standard support price of this app pricing
	 */
	public void setStandardSupportPrice(double standardSupportPrice);

	/**
	 * Returns the developer support price of this app pricing.
	 *
	 * @return the developer support price of this app pricing
	 */
	public double getDeveloperSupportPrice();

	/**
	 * Sets the developer support price of this app pricing.
	 *
	 * @param developerSupportPrice the developer support price of this app pricing
	 */
	public void setDeveloperSupportPrice(double developerSupportPrice);

	/**
	 * Returns the rank of this app pricing.
	 *
	 * @return the rank of this app pricing
	 */
	public int getRank();

	/**
	 * Sets the rank of this app pricing.
	 *
	 * @param rank the rank of this app pricing
	 */
	public void setRank(int rank);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AppPricing appPricing);

	public int hashCode();

	public CacheModel<AppPricing> toCacheModel();

	public AppPricing toEscapedModel();

	public AppPricing toUnescapedModel();

	public String toString();

	public String toXmlString();
}