/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppPackage service. Represents a row in the &quot;OSB_AppPackage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AppPackageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AppPackageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppPackage
 * @see com.liferay.osb.model.impl.AppPackageImpl
 * @see com.liferay.osb.model.impl.AppPackageModelImpl
 * @generated
 */
public interface AppPackageModel extends BaseModel<AppPackage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app package model instance should use the {@link AppPackage} interface instead.
	 */

	/**
	 * Returns the primary key of this app package.
	 *
	 * @return the primary key of this app package
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app package.
	 *
	 * @param primaryKey the primary key of this app package
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the app package ID of this app package.
	 *
	 * @return the app package ID of this app package
	 */
	public long getAppPackageId();

	/**
	 * Sets the app package ID of this app package.
	 *
	 * @param appPackageId the app package ID of this app package
	 */
	public void setAppPackageId(long appPackageId);

	/**
	 * Returns the create date of this app package.
	 *
	 * @return the create date of this app package
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this app package.
	 *
	 * @param createDate the create date of this app package
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this app package.
	 *
	 * @return the modified date of this app package
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this app package.
	 *
	 * @param modifiedDate the modified date of this app package
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the app entry ID of this app package.
	 *
	 * @return the app entry ID of this app package
	 */
	public long getAppEntryId();

	/**
	 * Sets the app entry ID of this app package.
	 *
	 * @param appEntryId the app entry ID of this app package
	 */
	public void setAppEntryId(long appEntryId);

	/**
	 * Returns the app version ID of this app package.
	 *
	 * @return the app version ID of this app package
	 */
	public long getAppVersionId();

	/**
	 * Sets the app version ID of this app package.
	 *
	 * @param appVersionId the app version ID of this app package
	 */
	public void setAppVersionId(long appVersionId);

	/**
	 * Returns the compatibility of this app package.
	 *
	 * @return the compatibility of this app package
	 */
	public int getCompatibility();

	/**
	 * Sets the compatibility of this app package.
	 *
	 * @param compatibility the compatibility of this app package
	 */
	public void setCompatibility(int compatibility);

	/**
	 * Returns the compatibility plus of this app package.
	 *
	 * @return the compatibility plus of this app package
	 */
	public boolean getCompatibilityPlus();

	/**
	 * Returns <code>true</code> if this app package is compatibility plus.
	 *
	 * @return <code>true</code> if this app package is compatibility plus; <code>false</code> otherwise
	 */
	public boolean isCompatibilityPlus();

	/**
	 * Sets whether this app package is compatibility plus.
	 *
	 * @param compatibilityPlus the compatibility plus of this app package
	 */
	public void setCompatibilityPlus(boolean compatibilityPlus);

	/**
	 * Returns the prepackaged of this app package.
	 *
	 * @return the prepackaged of this app package
	 */
	public boolean getPrepackaged();

	/**
	 * Returns <code>true</code> if this app package is prepackaged.
	 *
	 * @return <code>true</code> if this app package is prepackaged; <code>false</code> otherwise
	 */
	public boolean isPrepackaged();

	/**
	 * Sets whether this app package is prepackaged.
	 *
	 * @param prepackaged the prepackaged of this app package
	 */
	public void setPrepackaged(boolean prepackaged);

	/**
	 * Returns the download count of this app package.
	 *
	 * @return the download count of this app package
	 */
	public int getDownloadCount();

	/**
	 * Sets the download count of this app package.
	 *
	 * @param downloadCount the download count of this app package
	 */
	public void setDownloadCount(int downloadCount);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AppPackage appPackage);

	public int hashCode();

	public CacheModel<AppPackage> toCacheModel();

	public AppPackage toEscapedModel();

	public AppPackage toUnescapedModel();

	public String toString();

	public String toXmlString();
}