/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetReceipt service. Represents a row in the &quot;OSB_AssetReceipt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AssetReceiptModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AssetReceiptImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetReceipt
 * @see com.liferay.osb.model.impl.AssetReceiptImpl
 * @see com.liferay.osb.model.impl.AssetReceiptModelImpl
 * @generated
 */
public interface AssetReceiptModel extends BaseModel<AssetReceipt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset receipt model instance should use the {@link AssetReceipt} interface instead.
	 */

	/**
	 * Returns the primary key of this asset receipt.
	 *
	 * @return the primary key of this asset receipt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset receipt.
	 *
	 * @param primaryKey the primary key of this asset receipt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset receipt ID of this asset receipt.
	 *
	 * @return the asset receipt ID of this asset receipt
	 */
	public long getAssetReceiptId();

	/**
	 * Sets the asset receipt ID of this asset receipt.
	 *
	 * @param assetReceiptId the asset receipt ID of this asset receipt
	 */
	public void setAssetReceiptId(long assetReceiptId);

	/**
	 * Returns the user ID of this asset receipt.
	 *
	 * @return the user ID of this asset receipt
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this asset receipt.
	 *
	 * @param userId the user ID of this asset receipt
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset receipt.
	 *
	 * @return the user uuid of this asset receipt
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this asset receipt.
	 *
	 * @param userUuid the user uuid of this asset receipt
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this asset receipt.
	 *
	 * @return the user name of this asset receipt
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this asset receipt.
	 *
	 * @param userName the user name of this asset receipt
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this asset receipt.
	 *
	 * @return the create date of this asset receipt
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset receipt.
	 *
	 * @param createDate the create date of this asset receipt
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the asset entry ID of this asset receipt.
	 *
	 * @return the asset entry ID of this asset receipt
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset receipt.
	 *
	 * @param assetEntryId the asset entry ID of this asset receipt
	 */
	public void setAssetEntryId(long assetEntryId);

	/**
	 * Returns the owner class name ID of this asset receipt.
	 *
	 * @return the owner class name ID of this asset receipt
	 */
	public long getOwnerClassNameId();

	/**
	 * Sets the owner class name ID of this asset receipt.
	 *
	 * @param ownerClassNameId the owner class name ID of this asset receipt
	 */
	public void setOwnerClassNameId(long ownerClassNameId);

	/**
	 * Returns the owner class p k of this asset receipt.
	 *
	 * @return the owner class p k of this asset receipt
	 */
	public long getOwnerClassPK();

	/**
	 * Sets the owner class p k of this asset receipt.
	 *
	 * @param ownerClassPK the owner class p k of this asset receipt
	 */
	public void setOwnerClassPK(long ownerClassPK);

	/**
	 * Returns the legal entity name of this asset receipt.
	 *
	 * @return the legal entity name of this asset receipt
	 */
	@AutoEscape
	public String getLegalEntityName();

	/**
	 * Sets the legal entity name of this asset receipt.
	 *
	 * @param legalEntityName the legal entity name of this asset receipt
	 */
	public void setLegalEntityName(String legalEntityName);

	/**
	 * Returns the product class name ID of this asset receipt.
	 *
	 * @return the product class name ID of this asset receipt
	 */
	public long getProductClassNameId();

	/**
	 * Sets the product class name ID of this asset receipt.
	 *
	 * @param productClassNameId the product class name ID of this asset receipt
	 */
	public void setProductClassNameId(long productClassNameId);

	/**
	 * Returns the product class p k of this asset receipt.
	 *
	 * @return the product class p k of this asset receipt
	 */
	public long getProductClassPK();

	/**
	 * Sets the product class p k of this asset receipt.
	 *
	 * @param productClassPK the product class p k of this asset receipt
	 */
	public void setProductClassPK(long productClassPK);

	/**
	 * Returns the type of this asset receipt.
	 *
	 * @return the type of this asset receipt
	 */
	public long getType();

	/**
	 * Sets the type of this asset receipt.
	 *
	 * @param type the type of this asset receipt
	 */
	public void setType(long type);

	/**
	 * Returns the currency entry ID of this asset receipt.
	 *
	 * @return the currency entry ID of this asset receipt
	 */
	public long getCurrencyEntryId();

	/**
	 * Sets the currency entry ID of this asset receipt.
	 *
	 * @param currencyEntryId the currency entry ID of this asset receipt
	 */
	public void setCurrencyEntryId(long currencyEntryId);

	/**
	 * Returns the actual price of this asset receipt.
	 *
	 * @return the actual price of this asset receipt
	 */
	public double getActualPrice();

	/**
	 * Sets the actual price of this asset receipt.
	 *
	 * @param actualPrice the actual price of this asset receipt
	 */
	public void setActualPrice(double actualPrice);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AssetReceipt assetReceipt);

	public int hashCode();

	public CacheModel<AssetReceipt> toCacheModel();

	public AssetReceipt toEscapedModel();

	public AssetReceipt toUnescapedModel();

	public String toString();

	public String toXmlString();
}