/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AssetListAssetEntry service. Represents a row in the &quot;OSB_AssetListAssetEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AssetListAssetEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AssetListAssetEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetListAssetEntry
 * @see com.liferay.osb.model.impl.AssetListAssetEntryImpl
 * @see com.liferay.osb.model.impl.AssetListAssetEntryModelImpl
 * @generated
 */
public interface AssetListAssetEntryModel extends BaseModel<AssetListAssetEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset list asset entry model instance should use the {@link AssetListAssetEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this asset list asset entry.
	 *
	 * @return the primary key of this asset list asset entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset list asset entry.
	 *
	 * @param primaryKey the primary key of this asset list asset entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset list asset entry ID of this asset list asset entry.
	 *
	 * @return the asset list asset entry ID of this asset list asset entry
	 */
	public long getAssetListAssetEntryId();

	/**
	 * Sets the asset list asset entry ID of this asset list asset entry.
	 *
	 * @param assetListAssetEntryId the asset list asset entry ID of this asset list asset entry
	 */
	public void setAssetListAssetEntryId(long assetListAssetEntryId);

	/**
	 * Returns the asset list ID of this asset list asset entry.
	 *
	 * @return the asset list ID of this asset list asset entry
	 */
	public long getAssetListId();

	/**
	 * Sets the asset list ID of this asset list asset entry.
	 *
	 * @param assetListId the asset list ID of this asset list asset entry
	 */
	public void setAssetListId(long assetListId);

	/**
	 * Returns the asset entry ID of this asset list asset entry.
	 *
	 * @return the asset entry ID of this asset list asset entry
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset list asset entry.
	 *
	 * @param assetEntryId the asset entry ID of this asset list asset entry
	 */
	public void setAssetEntryId(long assetEntryId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AssetListAssetEntry assetListAssetEntry);

	public int hashCode();

	public CacheModel<AssetListAssetEntry> toCacheModel();

	public AssetListAssetEntry toEscapedModel();

	public AssetListAssetEntry toUnescapedModel();

	public String toString();

	public String toXmlString();
}