/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetReceiptLicense service. Represents a row in the &quot;OSB_AssetReceiptLicense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AssetReceiptLicenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AssetReceiptLicenseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetReceiptLicense
 * @see com.liferay.osb.model.impl.AssetReceiptLicenseImpl
 * @see com.liferay.osb.model.impl.AssetReceiptLicenseModelImpl
 * @generated
 */
@ProviderType
public interface AssetReceiptLicenseModel extends BaseModel<AssetReceiptLicense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset receipt license model instance should use the {@link AssetReceiptLicense} interface instead.
	 */

	/**
	 * Returns the primary key of this asset receipt license.
	 *
	 * @return the primary key of this asset receipt license
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset receipt license.
	 *
	 * @param primaryKey the primary key of this asset receipt license
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this asset receipt license.
	 *
	 * @return the uuid of this asset receipt license
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this asset receipt license.
	 *
	 * @param uuid the uuid of this asset receipt license
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the asset receipt license ID of this asset receipt license.
	 *
	 * @return the asset receipt license ID of this asset receipt license
	 */
	public long getAssetReceiptLicenseId();

	/**
	 * Sets the asset receipt license ID of this asset receipt license.
	 *
	 * @param assetReceiptLicenseId the asset receipt license ID of this asset receipt license
	 */
	public void setAssetReceiptLicenseId(long assetReceiptLicenseId);

	/**
	 * Returns the user ID of this asset receipt license.
	 *
	 * @return the user ID of this asset receipt license
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this asset receipt license.
	 *
	 * @param userId the user ID of this asset receipt license
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset receipt license.
	 *
	 * @return the user uuid of this asset receipt license
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this asset receipt license.
	 *
	 * @param userUuid the user uuid of this asset receipt license
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this asset receipt license.
	 *
	 * @return the user name of this asset receipt license
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this asset receipt license.
	 *
	 * @param userName the user name of this asset receipt license
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this asset receipt license.
	 *
	 * @return the create date of this asset receipt license
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset receipt license.
	 *
	 * @param createDate the create date of this asset receipt license
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this asset receipt license.
	 *
	 * @return the modified date of this asset receipt license
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this asset receipt license.
	 *
	 * @param modifiedDate the modified date of this asset receipt license
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the asset receipt ID of this asset receipt license.
	 *
	 * @return the asset receipt ID of this asset receipt license
	 */
	public long getAssetReceiptId();

	/**
	 * Sets the asset receipt ID of this asset receipt license.
	 *
	 * @param assetReceiptId the asset receipt ID of this asset receipt license
	 */
	public void setAssetReceiptId(long assetReceiptId);

	/**
	 * Returns the asset license ID of this asset receipt license.
	 *
	 * @return the asset license ID of this asset receipt license
	 */
	public long getAssetLicenseId();

	/**
	 * Sets the asset license ID of this asset receipt license.
	 *
	 * @param assetLicenseId the asset license ID of this asset receipt license
	 */
	public void setAssetLicenseId(long assetLicenseId);

	/**
	 * Returns the asset entry ID of this asset receipt license.
	 *
	 * @return the asset entry ID of this asset receipt license
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset receipt license.
	 *
	 * @param assetEntryId the asset entry ID of this asset receipt license
	 */
	public void setAssetEntryId(long assetEntryId);

	/**
	 * Returns the owner class name ID of this asset receipt license.
	 *
	 * @return the owner class name ID of this asset receipt license
	 */
	public long getOwnerClassNameId();

	/**
	 * Sets the owner class name ID of this asset receipt license.
	 *
	 * @param ownerClassNameId the owner class name ID of this asset receipt license
	 */
	public void setOwnerClassNameId(long ownerClassNameId);

	/**
	 * Returns the owner class pk of this asset receipt license.
	 *
	 * @return the owner class pk of this asset receipt license
	 */
	public long getOwnerClassPK();

	/**
	 * Sets the owner class pk of this asset receipt license.
	 *
	 * @param ownerClassPK the owner class pk of this asset receipt license
	 */
	public void setOwnerClassPK(long ownerClassPK);

	/**
	 * Returns the product class name ID of this asset receipt license.
	 *
	 * @return the product class name ID of this asset receipt license
	 */
	public long getProductClassNameId();

	/**
	 * Sets the product class name ID of this asset receipt license.
	 *
	 * @param productClassNameId the product class name ID of this asset receipt license
	 */
	public void setProductClassNameId(long productClassNameId);

	/**
	 * Returns the product class pk of this asset receipt license.
	 *
	 * @return the product class pk of this asset receipt license
	 */
	public long getProductClassPK();

	/**
	 * Sets the product class pk of this asset receipt license.
	 *
	 * @param productClassPK the product class pk of this asset receipt license
	 */
	public void setProductClassPK(long productClassPK);

	/**
	 * Returns the product ID of this asset receipt license.
	 *
	 * @return the product ID of this asset receipt license
	 */
	@AutoEscape
	public String getProductId();

	/**
	 * Sets the product ID of this asset receipt license.
	 *
	 * @param productId the product ID of this asset receipt license
	 */
	public void setProductId(String productId);

	/**
	 * Returns the start date of this asset receipt license.
	 *
	 * @return the start date of this asset receipt license
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this asset receipt license.
	 *
	 * @param startDate the start date of this asset receipt license
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this asset receipt license.
	 *
	 * @return the end date of this asset receipt license
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this asset receipt license.
	 *
	 * @param endDate the end date of this asset receipt license
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the usage type of this asset receipt license.
	 *
	 * @return the usage type of this asset receipt license
	 */
	public int getUsageType();

	/**
	 * Sets the usage type of this asset receipt license.
	 *
	 * @param usageType the usage type of this asset receipt license
	 */
	public void setUsageType(int usageType);

	/**
	 * Returns the license type of this asset receipt license.
	 *
	 * @return the license type of this asset receipt license
	 */
	public int getLicenseType();

	/**
	 * Sets the license type of this asset receipt license.
	 *
	 * @param licenseType the license type of this asset receipt license
	 */
	public void setLicenseType(int licenseType);

	/**
	 * Returns the license type allotment of this asset receipt license.
	 *
	 * @return the license type allotment of this asset receipt license
	 */
	public long getLicenseTypeAllotment();

	/**
	 * Sets the license type allotment of this asset receipt license.
	 *
	 * @param licenseTypeAllotment the license type allotment of this asset receipt license
	 */
	public void setLicenseTypeAllotment(long licenseTypeAllotment);

	/**
	 * Returns the license lifetime of this asset receipt license.
	 *
	 * @return the license lifetime of this asset receipt license
	 */
	public long getLicenseLifetime();

	/**
	 * Sets the license lifetime of this asset receipt license.
	 *
	 * @param licenseLifetime the license lifetime of this asset receipt license
	 */
	public void setLicenseLifetime(long licenseLifetime);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetReceiptLicense assetReceiptLicense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetReceiptLicense> toCacheModel();

	@Override
	public AssetReceiptLicense toEscapedModel();

	@Override
	public AssetReceiptLicense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}