/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AssetStatsWeek service. Represents a row in the &quot;OSB_AssetStatsWeek&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AssetStatsWeekModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AssetStatsWeekImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetStatsWeek
 * @see com.liferay.osb.model.impl.AssetStatsWeekImpl
 * @see com.liferay.osb.model.impl.AssetStatsWeekModelImpl
 * @generated
 */
public interface AssetStatsWeekModel extends AttachedModel,
	BaseModel<AssetStatsWeek> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset stats week model instance should use the {@link AssetStatsWeek} interface instead.
	 */

	/**
	 * Returns the primary key of this asset stats week.
	 *
	 * @return the primary key of this asset stats week
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset stats week.
	 *
	 * @param primaryKey the primary key of this asset stats week
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset stats week ID of this asset stats week.
	 *
	 * @return the asset stats week ID of this asset stats week
	 */
	public long getAssetStatsWeekId();

	/**
	 * Sets the asset stats week ID of this asset stats week.
	 *
	 * @param assetStatsWeekId the asset stats week ID of this asset stats week
	 */
	public void setAssetStatsWeekId(long assetStatsWeekId);

	/**
	 * Returns the fully qualified class name of this asset stats week.
	 *
	 * @return the fully qualified class name of this asset stats week
	 */
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset stats week.
	 *
	 * @return the class name ID of this asset stats week
	 */
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset stats week.
	 *
	 * @param classNameId the class name ID of this asset stats week
	 */
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this asset stats week.
	 *
	 * @return the class p k of this asset stats week
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this asset stats week.
	 *
	 * @param classPK the class p k of this asset stats week
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the week of this asset stats week.
	 *
	 * @return the week of this asset stats week
	 */
	public int getWeek();

	/**
	 * Sets the week of this asset stats week.
	 *
	 * @param week the week of this asset stats week
	 */
	public void setWeek(int week);

	/**
	 * Returns the year of this asset stats week.
	 *
	 * @return the year of this asset stats week
	 */
	public int getYear();

	/**
	 * Sets the year of this asset stats week.
	 *
	 * @param year the year of this asset stats week
	 */
	public void setYear(int year);

	/**
	 * Returns the view count of this asset stats week.
	 *
	 * @return the view count of this asset stats week
	 */
	public long getViewCount();

	/**
	 * Sets the view count of this asset stats week.
	 *
	 * @param viewCount the view count of this asset stats week
	 */
	public void setViewCount(long viewCount);

	/**
	 * Returns the download count of this asset stats week.
	 *
	 * @return the download count of this asset stats week
	 */
	public long getDownloadCount();

	/**
	 * Sets the download count of this asset stats week.
	 *
	 * @param downloadCount the download count of this asset stats week
	 */
	public void setDownloadCount(long downloadCount);

	/**
	 * Returns the purchase count of this asset stats week.
	 *
	 * @return the purchase count of this asset stats week
	 */
	public long getPurchaseCount();

	/**
	 * Sets the purchase count of this asset stats week.
	 *
	 * @param purchaseCount the purchase count of this asset stats week
	 */
	public void setPurchaseCount(long purchaseCount);

	/**
	 * Returns the currency code revenues of this asset stats week.
	 *
	 * @return the currency code revenues of this asset stats week
	 */
	@AutoEscape
	public String getCurrencyCodeRevenues();

	/**
	 * Sets the currency code revenues of this asset stats week.
	 *
	 * @param currencyCodeRevenues the currency code revenues of this asset stats week
	 */
	public void setCurrencyCodeRevenues(String currencyCodeRevenues);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AssetStatsWeek assetStatsWeek);

	public int hashCode();

	public CacheModel<AssetStatsWeek> toCacheModel();

	public AssetStatsWeek toEscapedModel();

	public AssetStatsWeek toUnescapedModel();

	public String toString();

	public String toXmlString();
}