/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetLicense service. Represents a row in the &quot;OSB_AssetLicense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.AssetLicenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.AssetLicenseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetLicense
 * @see com.liferay.osb.model.impl.AssetLicenseImpl
 * @see com.liferay.osb.model.impl.AssetLicenseModelImpl
 * @generated
 */
@ProviderType
public interface AssetLicenseModel extends AttachedModel, BaseModel<AssetLicense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset license model instance should use the {@link AssetLicense} interface instead.
	 */

	/**
	 * Returns the primary key of this asset license.
	 *
	 * @return the primary key of this asset license
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset license.
	 *
	 * @param primaryKey the primary key of this asset license
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset license ID of this asset license.
	 *
	 * @return the asset license ID of this asset license
	 */
	public long getAssetLicenseId();

	/**
	 * Sets the asset license ID of this asset license.
	 *
	 * @param assetLicenseId the asset license ID of this asset license
	 */
	public void setAssetLicenseId(long assetLicenseId);

	/**
	 * Returns the user ID of this asset license.
	 *
	 * @return the user ID of this asset license
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this asset license.
	 *
	 * @param userId the user ID of this asset license
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset license.
	 *
	 * @return the user uuid of this asset license
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this asset license.
	 *
	 * @param userUuid the user uuid of this asset license
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this asset license.
	 *
	 * @return the create date of this asset license
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset license.
	 *
	 * @param createDate the create date of this asset license
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this asset license.
	 *
	 * @return the modified date of this asset license
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this asset license.
	 *
	 * @param modifiedDate the modified date of this asset license
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this asset license.
	 *
	 * @return the fully qualified class name of this asset license
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset license.
	 *
	 * @return the class name ID of this asset license
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset license.
	 *
	 * @param classNameId the class name ID of this asset license
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this asset license.
	 *
	 * @return the class pk of this asset license
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this asset license.
	 *
	 * @param classPK the class pk of this asset license
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the license ID of this asset license.
	 *
	 * @return the license ID of this asset license
	 */
	@AutoEscape
	public String getLicenseId();

	/**
	 * Sets the license ID of this asset license.
	 *
	 * @param licenseId the license ID of this asset license
	 */
	public void setLicenseId(String licenseId);

	/**
	 * Returns the name of this asset license.
	 *
	 * @return the name of this asset license
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this asset license.
	 *
	 * @param name the name of this asset license
	 */
	public void setName(String name);

	/**
	 * Returns the required version of this asset license.
	 *
	 * @return the required version of this asset license
	 */
	public double getRequiredVersion();

	/**
	 * Sets the required version of this asset license.
	 *
	 * @param requiredVersion the required version of this asset license
	 */
	public void setRequiredVersion(double requiredVersion);

	/**
	 * Returns the usage type of this asset license.
	 *
	 * @return the usage type of this asset license
	 */
	public int getUsageType();

	/**
	 * Sets the usage type of this asset license.
	 *
	 * @param usageType the usage type of this asset license
	 */
	public void setUsageType(int usageType);

	/**
	 * Returns the license type of this asset license.
	 *
	 * @return the license type of this asset license
	 */
	public int getLicenseType();

	/**
	 * Sets the license type of this asset license.
	 *
	 * @param licenseType the license type of this asset license
	 */
	public void setLicenseType(int licenseType);

	/**
	 * Returns the license type allotment of this asset license.
	 *
	 * @return the license type allotment of this asset license
	 */
	public long getLicenseTypeAllotment();

	/**
	 * Sets the license type allotment of this asset license.
	 *
	 * @param licenseTypeAllotment the license type allotment of this asset license
	 */
	public void setLicenseTypeAllotment(long licenseTypeAllotment);

	/**
	 * Returns the lifetime of this asset license.
	 *
	 * @return the lifetime of this asset license
	 */
	public long getLifetime();

	/**
	 * Sets the lifetime of this asset license.
	 *
	 * @param lifetime the lifetime of this asset license
	 */
	public void setLifetime(long lifetime);

	/**
	 * Returns the status of this asset license.
	 *
	 * @return the status of this asset license
	 */
	public int getStatus();

	/**
	 * Sets the status of this asset license.
	 *
	 * @param status the status of this asset license
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetLicense assetLicense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetLicense> toCacheModel();

	@Override
	public AssetLicense toEscapedModel();

	@Override
	public AssetLicense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}