/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CorpProjectMessage service. Represents a row in the &quot;OSB_CorpProjectMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.CorpProjectMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.CorpProjectMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CorpProjectMessage
 * @see com.liferay.osb.model.impl.CorpProjectMessageImpl
 * @see com.liferay.osb.model.impl.CorpProjectMessageModelImpl
 * @generated
 */
@ProviderType
public interface CorpProjectMessageModel extends BaseModel<CorpProjectMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a corp project message model instance should use the {@link CorpProjectMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this corp project message.
	 *
	 * @return the primary key of this corp project message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this corp project message.
	 *
	 * @param primaryKey the primary key of this corp project message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this corp project message.
	 *
	 * @return the uuid of this corp project message
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this corp project message.
	 *
	 * @param uuid the uuid of this corp project message
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the corp project message ID of this corp project message.
	 *
	 * @return the corp project message ID of this corp project message
	 */
	public long getCorpProjectMessageId();

	/**
	 * Sets the corp project message ID of this corp project message.
	 *
	 * @param corpProjectMessageId the corp project message ID of this corp project message
	 */
	public void setCorpProjectMessageId(long corpProjectMessageId);

	/**
	 * Returns the user ID of this corp project message.
	 *
	 * @return the user ID of this corp project message
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this corp project message.
	 *
	 * @param userId the user ID of this corp project message
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this corp project message.
	 *
	 * @return the user uuid of this corp project message
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this corp project message.
	 *
	 * @param userUuid the user uuid of this corp project message
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this corp project message.
	 *
	 * @return the user name of this corp project message
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this corp project message.
	 *
	 * @param userName the user name of this corp project message
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this corp project message.
	 *
	 * @return the create date of this corp project message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this corp project message.
	 *
	 * @param createDate the create date of this corp project message
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this corp project message.
	 *
	 * @return the modified date of this corp project message
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this corp project message.
	 *
	 * @param modifiedDate the modified date of this corp project message
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the corp project ID of this corp project message.
	 *
	 * @return the corp project ID of this corp project message
	 */
	public long getCorpProjectId();

	/**
	 * Sets the corp project ID of this corp project message.
	 *
	 * @param corpProjectId the corp project ID of this corp project message
	 */
	public void setCorpProjectId(long corpProjectId);

	/**
	 * Returns the type of this corp project message.
	 *
	 * @return the type of this corp project message
	 */
	public int getType();

	/**
	 * Sets the type of this corp project message.
	 *
	 * @param type the type of this corp project message
	 */
	public void setType(int type);

	/**
	 * Returns the severity level of this corp project message.
	 *
	 * @return the severity level of this corp project message
	 */
	public int getSeverityLevel();

	/**
	 * Sets the severity level of this corp project message.
	 *
	 * @param severityLevel the severity level of this corp project message
	 */
	public void setSeverityLevel(int severityLevel);

	/**
	 * Returns the title of this corp project message.
	 *
	 * @return the title of this corp project message
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this corp project message.
	 *
	 * @param title the title of this corp project message
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this corp project message.
	 *
	 * @return the content of this corp project message
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this corp project message.
	 *
	 * @param content the content of this corp project message
	 */
	public void setContent(String content);

	/**
	 * Returns the display cp of this corp project message.
	 *
	 * @return the display cp of this corp project message
	 */
	public boolean getDisplayCP();

	/**
	 * Returns <code>true</code> if this corp project message is display cp.
	 *
	 * @return <code>true</code> if this corp project message is display cp; <code>false</code> otherwise
	 */
	public boolean isDisplayCP();

	/**
	 * Sets whether this corp project message is display cp.
	 *
	 * @param displayCP the display cp of this corp project message
	 */
	public void setDisplayCP(boolean displayCP);

	/**
	 * Returns the display lcs of this corp project message.
	 *
	 * @return the display lcs of this corp project message
	 */
	public boolean getDisplayLCS();

	/**
	 * Returns <code>true</code> if this corp project message is display lcs.
	 *
	 * @return <code>true</code> if this corp project message is display lcs; <code>false</code> otherwise
	 */
	public boolean isDisplayLCS();

	/**
	 * Sets whether this corp project message is display lcs.
	 *
	 * @param displayLCS the display lcs of this corp project message
	 */
	public void setDisplayLCS(boolean displayLCS);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CorpProjectMessage corpProjectMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CorpProjectMessage> toCacheModel();

	@Override
	public CorpProjectMessage toEscapedModel();

	@Override
	public CorpProjectMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}