/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExternalIdMapper service. Represents a row in the &quot;OSB_ExternalIdMapper&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.ExternalIdMapperModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.ExternalIdMapperImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExternalIdMapper
 * @see com.liferay.osb.model.impl.ExternalIdMapperImpl
 * @see com.liferay.osb.model.impl.ExternalIdMapperModelImpl
 * @generated
 */
public interface ExternalIdMapperModel extends AttachedModel,
	BaseModel<ExternalIdMapper> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a external ID mapper model instance should use the {@link ExternalIdMapper} interface instead.
	 */

	/**
	 * Returns the primary key of this external ID mapper.
	 *
	 * @return the primary key of this external ID mapper
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this external ID mapper.
	 *
	 * @param primaryKey the primary key of this external ID mapper
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the external ID mapper ID of this external ID mapper.
	 *
	 * @return the external ID mapper ID of this external ID mapper
	 */
	public long getExternalIdMapperId();

	/**
	 * Sets the external ID mapper ID of this external ID mapper.
	 *
	 * @param externalIdMapperId the external ID mapper ID of this external ID mapper
	 */
	public void setExternalIdMapperId(long externalIdMapperId);

	/**
	 * Returns the create date of this external ID mapper.
	 *
	 * @return the create date of this external ID mapper
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this external ID mapper.
	 *
	 * @param createDate the create date of this external ID mapper
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this external ID mapper.
	 *
	 * @return the modified date of this external ID mapper
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this external ID mapper.
	 *
	 * @param modifiedDate the modified date of this external ID mapper
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this external ID mapper.
	 *
	 * @return the fully qualified class name of this external ID mapper
	 */
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this external ID mapper.
	 *
	 * @return the class name ID of this external ID mapper
	 */
	public long getClassNameId();

	/**
	 * Sets the class name ID of this external ID mapper.
	 *
	 * @param classNameId the class name ID of this external ID mapper
	 */
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this external ID mapper.
	 *
	 * @return the class p k of this external ID mapper
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this external ID mapper.
	 *
	 * @param classPK the class p k of this external ID mapper
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the type of this external ID mapper.
	 *
	 * @return the type of this external ID mapper
	 */
	public int getType();

	/**
	 * Sets the type of this external ID mapper.
	 *
	 * @param type the type of this external ID mapper
	 */
	public void setType(int type);

	/**
	 * Returns the external ID of this external ID mapper.
	 *
	 * @return the external ID of this external ID mapper
	 */
	@AutoEscape
	public String getExternalId();

	/**
	 * Sets the external ID of this external ID mapper.
	 *
	 * @param externalId the external ID of this external ID mapper
	 */
	public void setExternalId(String externalId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ExternalIdMapper externalIdMapper);

	public int hashCode();

	public CacheModel<ExternalIdMapper> toCacheModel();

	public ExternalIdMapper toEscapedModel();

	public ExternalIdMapper toUnescapedModel();

	public String toString();

	public String toXmlString();
}