/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the HolidayCalendarRel service. Represents a row in the &quot;OSB_HolidayCalendarRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.HolidayCalendarRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.HolidayCalendarRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HolidayCalendarRel
 * @see com.liferay.osb.model.impl.HolidayCalendarRelImpl
 * @see com.liferay.osb.model.impl.HolidayCalendarRelModelImpl
 * @generated
 */
@ProviderType
public interface HolidayCalendarRelModel extends BaseModel<HolidayCalendarRel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a holiday calendar rel model instance should use the {@link HolidayCalendarRel} interface instead.
	 */

	/**
	 * Returns the primary key of this holiday calendar rel.
	 *
	 * @return the primary key of this holiday calendar rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this holiday calendar rel.
	 *
	 * @param primaryKey the primary key of this holiday calendar rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the holiday calendar rel ID of this holiday calendar rel.
	 *
	 * @return the holiday calendar rel ID of this holiday calendar rel
	 */
	public long getHolidayCalendarRelId();

	/**
	 * Sets the holiday calendar rel ID of this holiday calendar rel.
	 *
	 * @param holidayCalendarRelId the holiday calendar rel ID of this holiday calendar rel
	 */
	public void setHolidayCalendarRelId(long holidayCalendarRelId);

	/**
	 * Returns the holiday calendar ID of this holiday calendar rel.
	 *
	 * @return the holiday calendar ID of this holiday calendar rel
	 */
	public long getHolidayCalendarId();

	/**
	 * Sets the holiday calendar ID of this holiday calendar rel.
	 *
	 * @param holidayCalendarId the holiday calendar ID of this holiday calendar rel
	 */
	public void setHolidayCalendarId(long holidayCalendarId);

	/**
	 * Returns the user ID of this holiday calendar rel.
	 *
	 * @return the user ID of this holiday calendar rel
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this holiday calendar rel.
	 *
	 * @param userId the user ID of this holiday calendar rel
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this holiday calendar rel.
	 *
	 * @return the user uuid of this holiday calendar rel
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this holiday calendar rel.
	 *
	 * @param userUuid the user uuid of this holiday calendar rel
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HolidayCalendarRel holidayCalendarRel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HolidayCalendarRel> toCacheModel();

	@Override
	public HolidayCalendarRel toEscapedModel();

	@Override
	public HolidayCalendarRel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}