/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LCSSubscriptionEntry service. Represents a row in the &quot;OSB_LCSSubscriptionEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.LCSSubscriptionEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.LCSSubscriptionEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LCSSubscriptionEntry
 * @see com.liferay.osb.model.impl.LCSSubscriptionEntryImpl
 * @see com.liferay.osb.model.impl.LCSSubscriptionEntryModelImpl
 * @generated
 */
@ProviderType
public interface LCSSubscriptionEntryModel extends BaseModel<LCSSubscriptionEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lcs subscription entry model instance should use the {@link LCSSubscriptionEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this lcs subscription entry.
	 *
	 * @return the primary key of this lcs subscription entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lcs subscription entry.
	 *
	 * @param primaryKey the primary key of this lcs subscription entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lcs subscription entry ID of this lcs subscription entry.
	 *
	 * @return the lcs subscription entry ID of this lcs subscription entry
	 */
	public long getLcsSubscriptionEntryId();

	/**
	 * Sets the lcs subscription entry ID of this lcs subscription entry.
	 *
	 * @param lcsSubscriptionEntryId the lcs subscription entry ID of this lcs subscription entry
	 */
	public void setLcsSubscriptionEntryId(long lcsSubscriptionEntryId);

	/**
	 * Returns the lcs project ID of this lcs subscription entry.
	 *
	 * @return the lcs project ID of this lcs subscription entry
	 */
	public long getLcsProjectId();

	/**
	 * Sets the lcs project ID of this lcs subscription entry.
	 *
	 * @param lcsProjectId the lcs project ID of this lcs subscription entry
	 */
	public void setLcsProjectId(long lcsProjectId);

	/**
	 * Returns the product of this lcs subscription entry.
	 *
	 * @return the product of this lcs subscription entry
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this lcs subscription entry.
	 *
	 * @param product the product of this lcs subscription entry
	 */
	public void setProduct(String product);

	/**
	 * Returns the product version of this lcs subscription entry.
	 *
	 * @return the product version of this lcs subscription entry
	 */
	public int getProductVersion();

	/**
	 * Sets the product version of this lcs subscription entry.
	 *
	 * @param productVersion the product version of this lcs subscription entry
	 */
	public void setProductVersion(int productVersion);

	/**
	 * Returns the type of this lcs subscription entry.
	 *
	 * @return the type of this lcs subscription entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this lcs subscription entry.
	 *
	 * @param type the type of this lcs subscription entry
	 */
	public void setType(String type);

	/**
	 * Returns the platform of this lcs subscription entry.
	 *
	 * @return the platform of this lcs subscription entry
	 */
	@AutoEscape
	public String getPlatform();

	/**
	 * Sets the platform of this lcs subscription entry.
	 *
	 * @param platform the platform of this lcs subscription entry
	 */
	public void setPlatform(String platform);

	/**
	 * Returns the platform version of this lcs subscription entry.
	 *
	 * @return the platform version of this lcs subscription entry
	 */
	@AutoEscape
	public String getPlatformVersion();

	/**
	 * Sets the platform version of this lcs subscription entry.
	 *
	 * @param platformVersion the platform version of this lcs subscription entry
	 */
	public void setPlatformVersion(String platformVersion);

	/**
	 * Returns the servers allowed of this lcs subscription entry.
	 *
	 * @return the servers allowed of this lcs subscription entry
	 */
	public int getServersAllowed();

	/**
	 * Sets the servers allowed of this lcs subscription entry.
	 *
	 * @param serversAllowed the servers allowed of this lcs subscription entry
	 */
	public void setServersAllowed(int serversAllowed);

	/**
	 * Returns the servers used of this lcs subscription entry.
	 *
	 * @return the servers used of this lcs subscription entry
	 */
	public int getServersUsed();

	/**
	 * Sets the servers used of this lcs subscription entry.
	 *
	 * @param serversUsed the servers used of this lcs subscription entry
	 */
	public void setServersUsed(int serversUsed);

	/**
	 * Returns the quantity of this lcs subscription entry.
	 *
	 * @return the quantity of this lcs subscription entry
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this lcs subscription entry.
	 *
	 * @param quantity the quantity of this lcs subscription entry
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the instance size of this lcs subscription entry.
	 *
	 * @return the instance size of this lcs subscription entry
	 */
	public int getInstanceSize();

	/**
	 * Sets the instance size of this lcs subscription entry.
	 *
	 * @param instanceSize the instance size of this lcs subscription entry
	 */
	public void setInstanceSize(int instanceSize);

	/**
	 * Returns the start date of this lcs subscription entry.
	 *
	 * @return the start date of this lcs subscription entry
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this lcs subscription entry.
	 *
	 * @param startDate the start date of this lcs subscription entry
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this lcs subscription entry.
	 *
	 * @return the end date of this lcs subscription entry
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this lcs subscription entry.
	 *
	 * @param endDate the end date of this lcs subscription entry
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the support start date of this lcs subscription entry.
	 *
	 * @return the support start date of this lcs subscription entry
	 */
	public Date getSupportStartDate();

	/**
	 * Sets the support start date of this lcs subscription entry.
	 *
	 * @param supportStartDate the support start date of this lcs subscription entry
	 */
	public void setSupportStartDate(Date supportStartDate);

	/**
	 * Returns the support end date of this lcs subscription entry.
	 *
	 * @return the support end date of this lcs subscription entry
	 */
	public Date getSupportEndDate();

	/**
	 * Sets the support end date of this lcs subscription entry.
	 *
	 * @param supportEndDate the support end date of this lcs subscription entry
	 */
	public void setSupportEndDate(Date supportEndDate);

	/**
	 * Returns the actual price of this lcs subscription entry.
	 *
	 * @return the actual price of this lcs subscription entry
	 */
	public double getActualPrice();

	/**
	 * Sets the actual price of this lcs subscription entry.
	 *
	 * @param actualPrice the actual price of this lcs subscription entry
	 */
	public void setActualPrice(double actualPrice);

	/**
	 * Returns the currency code of this lcs subscription entry.
	 *
	 * @return the currency code of this lcs subscription entry
	 */
	@AutoEscape
	public String getCurrencyCode();

	/**
	 * Sets the currency code of this lcs subscription entry.
	 *
	 * @param currencyCode the currency code of this lcs subscription entry
	 */
	public void setCurrencyCode(String currencyCode);

	/**
	 * Returns the active of this lcs subscription entry.
	 *
	 * @return the active of this lcs subscription entry
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this lcs subscription entry is active.
	 *
	 * @return <code>true</code> if this lcs subscription entry is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this lcs subscription entry is active.
	 *
	 * @param active the active of this lcs subscription entry
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(LCSSubscriptionEntry lcsSubscriptionEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<LCSSubscriptionEntry> toCacheModel();

	@Override
	public LCSSubscriptionEntry toEscapedModel();

	@Override
	public LCSSubscriptionEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}