/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OfferingEntry service. Represents a row in the &quot;OSB_OfferingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.OfferingEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.OfferingEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OfferingEntry
 * @see com.liferay.osb.model.impl.OfferingEntryImpl
 * @see com.liferay.osb.model.impl.OfferingEntryModelImpl
 * @generated
 */
public interface OfferingEntryModel extends BaseModel<OfferingEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a offering entry model instance should use the {@link OfferingEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this offering entry.
	 *
	 * @return the primary key of this offering entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this offering entry.
	 *
	 * @param primaryKey the primary key of this offering entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the offering entry ID of this offering entry.
	 *
	 * @return the offering entry ID of this offering entry
	 */
	public long getOfferingEntryId();

	/**
	 * Sets the offering entry ID of this offering entry.
	 *
	 * @param offeringEntryId the offering entry ID of this offering entry
	 */
	public void setOfferingEntryId(long offeringEntryId);

	/**
	 * Returns the user ID of this offering entry.
	 *
	 * @return the user ID of this offering entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this offering entry.
	 *
	 * @param userId the user ID of this offering entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this offering entry.
	 *
	 * @return the user uuid of this offering entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this offering entry.
	 *
	 * @param userUuid the user uuid of this offering entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this offering entry.
	 *
	 * @return the user name of this offering entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this offering entry.
	 *
	 * @param userName the user name of this offering entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this offering entry.
	 *
	 * @return the create date of this offering entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this offering entry.
	 *
	 * @param createDate the create date of this offering entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this offering entry.
	 *
	 * @return the modified date of this offering entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this offering entry.
	 *
	 * @param modifiedDate the modified date of this offering entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account entry ID of this offering entry.
	 *
	 * @return the account entry ID of this offering entry
	 */
	public long getAccountEntryId();

	/**
	 * Sets the account entry ID of this offering entry.
	 *
	 * @param accountEntryId the account entry ID of this offering entry
	 */
	public void setAccountEntryId(long accountEntryId);

	/**
	 * Returns the order entry ID of this offering entry.
	 *
	 * @return the order entry ID of this offering entry
	 */
	public long getOrderEntryId();

	/**
	 * Sets the order entry ID of this offering entry.
	 *
	 * @param orderEntryId the order entry ID of this offering entry
	 */
	public void setOrderEntryId(long orderEntryId);

	/**
	 * Returns the product entry ID of this offering entry.
	 *
	 * @return the product entry ID of this offering entry
	 */
	public long getProductEntryId();

	/**
	 * Sets the product entry ID of this offering entry.
	 *
	 * @param productEntryId the product entry ID of this offering entry
	 */
	public void setProductEntryId(long productEntryId);

	/**
	 * Returns the support response ID of this offering entry.
	 *
	 * @return the support response ID of this offering entry
	 */
	public long getSupportResponseId();

	/**
	 * Sets the support response ID of this offering entry.
	 *
	 * @param supportResponseId the support response ID of this offering entry
	 */
	public void setSupportResponseId(long supportResponseId);

	/**
	 * Returns the product description of this offering entry.
	 *
	 * @return the product description of this offering entry
	 */
	@AutoEscape
	public String getProductDescription();

	/**
	 * Sets the product description of this offering entry.
	 *
	 * @param productDescription the product description of this offering entry
	 */
	public void setProductDescription(String productDescription);

	/**
	 * Returns the type of this offering entry.
	 *
	 * @return the type of this offering entry
	 */
	public int getType();

	/**
	 * Sets the type of this offering entry.
	 *
	 * @param type the type of this offering entry
	 */
	public void setType(int type);

	/**
	 * Returns the version of this offering entry.
	 *
	 * @return the version of this offering entry
	 */
	public int getVersion();

	/**
	 * Sets the version of this offering entry.
	 *
	 * @param version the version of this offering entry
	 */
	public void setVersion(int version);

	/**
	 * Returns the platform of this offering entry.
	 *
	 * @return the platform of this offering entry
	 */
	@AutoEscape
	public String getPlatform();

	/**
	 * Sets the platform of this offering entry.
	 *
	 * @param platform the platform of this offering entry
	 */
	public void setPlatform(String platform);

	/**
	 * Returns the platform version of this offering entry.
	 *
	 * @return the platform version of this offering entry
	 */
	@AutoEscape
	public String getPlatformVersion();

	/**
	 * Sets the platform version of this offering entry.
	 *
	 * @param platformVersion the platform version of this offering entry
	 */
	public void setPlatformVersion(String platformVersion);

	/**
	 * Returns the licenses of this offering entry.
	 *
	 * @return the licenses of this offering entry
	 */
	public boolean getLicenses();

	/**
	 * Returns <code>true</code> if this offering entry is licenses.
	 *
	 * @return <code>true</code> if this offering entry is licenses; <code>false</code> otherwise
	 */
	public boolean isLicenses();

	/**
	 * Sets whether this offering entry is licenses.
	 *
	 * @param licenses the licenses of this offering entry
	 */
	public void setLicenses(boolean licenses);

	/**
	 * Returns the license lifetime of this offering entry.
	 *
	 * @return the license lifetime of this offering entry
	 */
	public long getLicenseLifetime();

	/**
	 * Sets the license lifetime of this offering entry.
	 *
	 * @param licenseLifetime the license lifetime of this offering entry
	 */
	public void setLicenseLifetime(long licenseLifetime);

	/**
	 * Returns the max concurrent users of this offering entry.
	 *
	 * @return the max concurrent users of this offering entry
	 */
	public long getMaxConcurrentUsers();

	/**
	 * Sets the max concurrent users of this offering entry.
	 *
	 * @param maxConcurrentUsers the max concurrent users of this offering entry
	 */
	public void setMaxConcurrentUsers(long maxConcurrentUsers);

	/**
	 * Returns the max users of this offering entry.
	 *
	 * @return the max users of this offering entry
	 */
	public long getMaxUsers();

	/**
	 * Sets the max users of this offering entry.
	 *
	 * @param maxUsers the max users of this offering entry
	 */
	public void setMaxUsers(long maxUsers);

	/**
	 * Returns the support tickets of this offering entry.
	 *
	 * @return the support tickets of this offering entry
	 */
	public boolean getSupportTickets();

	/**
	 * Returns <code>true</code> if this offering entry is support tickets.
	 *
	 * @return <code>true</code> if this offering entry is support tickets; <code>false</code> otherwise
	 */
	public boolean isSupportTickets();

	/**
	 * Sets whether this offering entry is support tickets.
	 *
	 * @param supportTickets the support tickets of this offering entry
	 */
	public void setSupportTickets(boolean supportTickets);

	/**
	 * Returns the support lifetime of this offering entry.
	 *
	 * @return the support lifetime of this offering entry
	 */
	public long getSupportLifetime();

	/**
	 * Sets the support lifetime of this offering entry.
	 *
	 * @param supportLifetime the support lifetime of this offering entry
	 */
	public void setSupportLifetime(long supportLifetime);

	/**
	 * Returns the support end date of this offering entry.
	 *
	 * @return the support end date of this offering entry
	 */
	public Date getSupportEndDate();

	/**
	 * Sets the support end date of this offering entry.
	 *
	 * @param supportEndDate the support end date of this offering entry
	 */
	public void setSupportEndDate(Date supportEndDate);

	/**
	 * Returns the sizing of this offering entry.
	 *
	 * @return the sizing of this offering entry
	 */
	public int getSizing();

	/**
	 * Sets the sizing of this offering entry.
	 *
	 * @param sizing the sizing of this offering entry
	 */
	public void setSizing(int sizing);

	/**
	 * Returns the quantity of this offering entry.
	 *
	 * @return the quantity of this offering entry
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this offering entry.
	 *
	 * @param quantity the quantity of this offering entry
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the status of this offering entry.
	 *
	 * @return the status of this offering entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this offering entry.
	 *
	 * @param status the status of this offering entry
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(OfferingEntry offeringEntry);

	public int hashCode();

	public CacheModel<OfferingEntry> toCacheModel();

	public OfferingEntry toEscapedModel();

	public OfferingEntry toUnescapedModel();

	public String toString();

	public String toXmlString();
}