/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.TypedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SearchFilter service. Represents a row in the &quot;OSB_SearchFilter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.SearchFilterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.SearchFilterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SearchFilter
 * @see com.liferay.osb.model.impl.SearchFilterImpl
 * @see com.liferay.osb.model.impl.SearchFilterModelImpl
 * @generated
 */
@ProviderType
public interface SearchFilterModel extends BaseModel<SearchFilter>, TypedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a search filter model instance should use the {@link SearchFilter} interface instead.
	 */

	/**
	 * Returns the primary key of this search filter.
	 *
	 * @return the primary key of this search filter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this search filter.
	 *
	 * @param primaryKey the primary key of this search filter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the search filter ID of this search filter.
	 *
	 * @return the search filter ID of this search filter
	 */
	public long getSearchFilterId();

	/**
	 * Sets the search filter ID of this search filter.
	 *
	 * @param searchFilterId the search filter ID of this search filter
	 */
	public void setSearchFilterId(long searchFilterId);

	/**
	 * Returns the user ID of this search filter.
	 *
	 * @return the user ID of this search filter
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this search filter.
	 *
	 * @param userId the user ID of this search filter
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this search filter.
	 *
	 * @return the user uuid of this search filter
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this search filter.
	 *
	 * @param userUuid the user uuid of this search filter
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this search filter.
	 *
	 * @return the user name of this search filter
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this search filter.
	 *
	 * @param userName the user name of this search filter
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this search filter.
	 *
	 * @return the create date of this search filter
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this search filter.
	 *
	 * @param createDate the create date of this search filter
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this search filter.
	 *
	 * @return the modified date of this search filter
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this search filter.
	 *
	 * @param modifiedDate the modified date of this search filter
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this search filter.
	 *
	 * @return the fully qualified class name of this search filter
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this search filter.
	 *
	 * @return the class name ID of this search filter
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this search filter.
	 *
	 * @param classNameId the class name ID of this search filter
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the name of this search filter.
	 *
	 * @return the name of this search filter
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this search filter.
	 *
	 * @param name the name of this search filter
	 */
	public void setName(String name);

	/**
	 * Returns the filter of this search filter.
	 *
	 * @return the filter of this search filter
	 */
	@AutoEscape
	public String getFilter();

	/**
	 * Sets the filter of this search filter.
	 *
	 * @param filter the filter of this search filter
	 */
	public void setFilter(String filter);

	/**
	 * Returns the visibility of this search filter.
	 *
	 * @return the visibility of this search filter
	 */
	public int getVisibility();

	/**
	 * Sets the visibility of this search filter.
	 *
	 * @param visibility the visibility of this search filter
	 */
	public void setVisibility(int visibility);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SearchFilter searchFilter);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SearchFilter> toCacheModel();

	@Override
	public SearchFilter toEscapedModel();

	@Override
	public SearchFilter toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}