/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SupportTeam service. Represents a row in the &quot;OSB_SupportTeam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.SupportTeamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.SupportTeamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportTeam
 * @see com.liferay.osb.model.impl.SupportTeamImpl
 * @see com.liferay.osb.model.impl.SupportTeamModelImpl
 * @generated
 */
public interface SupportTeamModel extends BaseModel<SupportTeam> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support team model instance should use the {@link SupportTeam} interface instead.
	 */

	/**
	 * Returns the primary key of this support team.
	 *
	 * @return the primary key of this support team
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support team.
	 *
	 * @param primaryKey the primary key of this support team
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the support team ID of this support team.
	 *
	 * @return the support team ID of this support team
	 */
	public long getSupportTeamId();

	/**
	 * Sets the support team ID of this support team.
	 *
	 * @param supportTeamId the support team ID of this support team
	 */
	public void setSupportTeamId(long supportTeamId);

	/**
	 * Returns the user ID of this support team.
	 *
	 * @return the user ID of this support team
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this support team.
	 *
	 * @param userId the user ID of this support team
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this support team.
	 *
	 * @return the user uuid of this support team
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this support team.
	 *
	 * @param userUuid the user uuid of this support team
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this support team.
	 *
	 * @return the user name of this support team
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this support team.
	 *
	 * @param userName the user name of this support team
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this support team.
	 *
	 * @return the create date of this support team
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this support team.
	 *
	 * @param createDate the create date of this support team
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this support team.
	 *
	 * @return the modified date of this support team
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this support team.
	 *
	 * @param modifiedDate the modified date of this support team
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the parent support team ID of this support team.
	 *
	 * @return the parent support team ID of this support team
	 */
	public long getParentSupportTeamId();

	/**
	 * Sets the parent support team ID of this support team.
	 *
	 * @param parentSupportTeamId the parent support team ID of this support team
	 */
	public void setParentSupportTeamId(long parentSupportTeamId);

	/**
	 * Returns the support labor ID of this support team.
	 *
	 * @return the support labor ID of this support team
	 */
	public long getSupportLaborId();

	/**
	 * Sets the support labor ID of this support team.
	 *
	 * @param supportLaborId the support labor ID of this support team
	 */
	public void setSupportLaborId(long supportLaborId);

	/**
	 * Returns the location support region ID of this support team.
	 *
	 * @return the location support region ID of this support team
	 */
	public long getLocationSupportRegionId();

	/**
	 * Sets the location support region ID of this support team.
	 *
	 * @param locationSupportRegionId the location support region ID of this support team
	 */
	public void setLocationSupportRegionId(long locationSupportRegionId);

	/**
	 * Returns the name of this support team.
	 *
	 * @return the name of this support team
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this support team.
	 *
	 * @param name the name of this support team
	 */
	public void setName(String name);

	/**
	 * Returns the description of this support team.
	 *
	 * @return the description of this support team
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this support team.
	 *
	 * @param description the description of this support team
	 */
	public void setDescription(String description);

	/**
	 * Returns the type of this support team.
	 *
	 * @return the type of this support team
	 */
	public int getType();

	/**
	 * Sets the type of this support team.
	 *
	 * @param type the type of this support team
	 */
	public void setType(int type);

	/**
	 * Returns the assigned work of this support team.
	 *
	 * @return the assigned work of this support team
	 */
	public double getAssignedWork();

	/**
	 * Sets the assigned work of this support team.
	 *
	 * @param assignedWork the assigned work of this support team
	 */
	public void setAssignedWork(double assignedWork);

	/**
	 * Returns the max work of this support team.
	 *
	 * @return the max work of this support team
	 */
	public double getMaxWork();

	/**
	 * Sets the max work of this support team.
	 *
	 * @param maxWork the max work of this support team
	 */
	public void setMaxWork(double maxWork);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SupportTeam supportTeam);

	public int hashCode();

	public CacheModel<SupportTeam> toCacheModel();

	public SupportTeam toEscapedModel();

	public SupportTeam toUnescapedModel();

	public String toString();

	public String toXmlString();
}