/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SupportLabor service. Represents a row in the &quot;OSB_SupportLabor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.SupportLaborModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.SupportLaborImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportLabor
 * @see com.liferay.osb.model.impl.SupportLaborImpl
 * @see com.liferay.osb.model.impl.SupportLaborModelImpl
 * @generated
 */
@ProviderType
public interface SupportLaborModel extends BaseModel<SupportLabor> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support labor model instance should use the {@link SupportLabor} interface instead.
	 */

	/**
	 * Returns the primary key of this support labor.
	 *
	 * @return the primary key of this support labor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support labor.
	 *
	 * @param primaryKey the primary key of this support labor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the support labor ID of this support labor.
	 *
	 * @return the support labor ID of this support labor
	 */
	public long getSupportLaborId();

	/**
	 * Sets the support labor ID of this support labor.
	 *
	 * @param supportLaborId the support labor ID of this support labor
	 */
	public void setSupportLaborId(long supportLaborId);

	/**
	 * Returns the name of this support labor.
	 *
	 * @return the name of this support labor
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this support labor.
	 *
	 * @param name the name of this support labor
	 */
	public void setName(String name);

	/**
	 * Returns the description of this support labor.
	 *
	 * @return the description of this support labor
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this support labor.
	 *
	 * @param description the description of this support labor
	 */
	public void setDescription(String description);

	/**
	 * Returns the time zone ID of this support labor.
	 *
	 * @return the time zone ID of this support labor
	 */
	@AutoEscape
	public String getTimeZoneId();

	/**
	 * Sets the time zone ID of this support labor.
	 *
	 * @param timeZoneId the time zone ID of this support labor
	 */
	public void setTimeZoneId(String timeZoneId);

	/**
	 * Returns the sun open of this support labor.
	 *
	 * @return the sun open of this support labor
	 */
	public int getSunOpen();

	/**
	 * Sets the sun open of this support labor.
	 *
	 * @param sunOpen the sun open of this support labor
	 */
	public void setSunOpen(int sunOpen);

	/**
	 * Returns the sun close of this support labor.
	 *
	 * @return the sun close of this support labor
	 */
	public int getSunClose();

	/**
	 * Sets the sun close of this support labor.
	 *
	 * @param sunClose the sun close of this support labor
	 */
	public void setSunClose(int sunClose);

	/**
	 * Returns the mon open of this support labor.
	 *
	 * @return the mon open of this support labor
	 */
	public int getMonOpen();

	/**
	 * Sets the mon open of this support labor.
	 *
	 * @param monOpen the mon open of this support labor
	 */
	public void setMonOpen(int monOpen);

	/**
	 * Returns the mon close of this support labor.
	 *
	 * @return the mon close of this support labor
	 */
	public int getMonClose();

	/**
	 * Sets the mon close of this support labor.
	 *
	 * @param monClose the mon close of this support labor
	 */
	public void setMonClose(int monClose);

	/**
	 * Returns the tue open of this support labor.
	 *
	 * @return the tue open of this support labor
	 */
	public int getTueOpen();

	/**
	 * Sets the tue open of this support labor.
	 *
	 * @param tueOpen the tue open of this support labor
	 */
	public void setTueOpen(int tueOpen);

	/**
	 * Returns the tue close of this support labor.
	 *
	 * @return the tue close of this support labor
	 */
	public int getTueClose();

	/**
	 * Sets the tue close of this support labor.
	 *
	 * @param tueClose the tue close of this support labor
	 */
	public void setTueClose(int tueClose);

	/**
	 * Returns the wed open of this support labor.
	 *
	 * @return the wed open of this support labor
	 */
	public int getWedOpen();

	/**
	 * Sets the wed open of this support labor.
	 *
	 * @param wedOpen the wed open of this support labor
	 */
	public void setWedOpen(int wedOpen);

	/**
	 * Returns the wed close of this support labor.
	 *
	 * @return the wed close of this support labor
	 */
	public int getWedClose();

	/**
	 * Sets the wed close of this support labor.
	 *
	 * @param wedClose the wed close of this support labor
	 */
	public void setWedClose(int wedClose);

	/**
	 * Returns the thu open of this support labor.
	 *
	 * @return the thu open of this support labor
	 */
	public int getThuOpen();

	/**
	 * Sets the thu open of this support labor.
	 *
	 * @param thuOpen the thu open of this support labor
	 */
	public void setThuOpen(int thuOpen);

	/**
	 * Returns the thu close of this support labor.
	 *
	 * @return the thu close of this support labor
	 */
	public int getThuClose();

	/**
	 * Sets the thu close of this support labor.
	 *
	 * @param thuClose the thu close of this support labor
	 */
	public void setThuClose(int thuClose);

	/**
	 * Returns the fri open of this support labor.
	 *
	 * @return the fri open of this support labor
	 */
	public int getFriOpen();

	/**
	 * Sets the fri open of this support labor.
	 *
	 * @param friOpen the fri open of this support labor
	 */
	public void setFriOpen(int friOpen);

	/**
	 * Returns the fri close of this support labor.
	 *
	 * @return the fri close of this support labor
	 */
	public int getFriClose();

	/**
	 * Sets the fri close of this support labor.
	 *
	 * @param friClose the fri close of this support labor
	 */
	public void setFriClose(int friClose);

	/**
	 * Returns the sat open of this support labor.
	 *
	 * @return the sat open of this support labor
	 */
	public int getSatOpen();

	/**
	 * Sets the sat open of this support labor.
	 *
	 * @param satOpen the sat open of this support labor
	 */
	public void setSatOpen(int satOpen);

	/**
	 * Returns the sat close of this support labor.
	 *
	 * @return the sat close of this support labor
	 */
	public int getSatClose();

	/**
	 * Sets the sat close of this support labor.
	 *
	 * @param satClose the sat close of this support labor
	 */
	public void setSatClose(int satClose);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SupportLabor supportLabor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SupportLabor> toCacheModel();

	@Override
	public SupportLabor toEscapedModel();

	@Override
	public SupportLabor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}