/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SupportTeamLanguage service. Represents a row in the &quot;OSB_SupportTeamLanguage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.SupportTeamLanguageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.SupportTeamLanguageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportTeamLanguage
 * @see com.liferay.osb.model.impl.SupportTeamLanguageImpl
 * @see com.liferay.osb.model.impl.SupportTeamLanguageModelImpl
 * @generated
 */
public interface SupportTeamLanguageModel extends BaseModel<SupportTeamLanguage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support team language model instance should use the {@link SupportTeamLanguage} interface instead.
	 */

	/**
	 * Returns the primary key of this support team language.
	 *
	 * @return the primary key of this support team language
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support team language.
	 *
	 * @param primaryKey the primary key of this support team language
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the support team language ID of this support team language.
	 *
	 * @return the support team language ID of this support team language
	 */
	public long getSupportTeamLanguageId();

	/**
	 * Sets the support team language ID of this support team language.
	 *
	 * @param supportTeamLanguageId the support team language ID of this support team language
	 */
	public void setSupportTeamLanguageId(long supportTeamLanguageId);

	/**
	 * Returns the support team ID of this support team language.
	 *
	 * @return the support team ID of this support team language
	 */
	public long getSupportTeamId();

	/**
	 * Sets the support team ID of this support team language.
	 *
	 * @param supportTeamId the support team ID of this support team language
	 */
	public void setSupportTeamId(long supportTeamId);

	/**
	 * Returns the language ID of this support team language.
	 *
	 * @return the language ID of this support team language
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this support team language.
	 *
	 * @param languageId the language ID of this support team language
	 */
	public void setLanguageId(String languageId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SupportTeamLanguage supportTeamLanguage);

	public int hashCode();

	public CacheModel<SupportTeamLanguage> toCacheModel();

	public SupportTeamLanguage toEscapedModel();

	public SupportTeamLanguage toUnescapedModel();

	public String toString();

	public String toXmlString();
}