/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SupportWorker service. Represents a row in the &quot;OSB_SupportWorker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.SupportWorkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.SupportWorkerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportWorker
 * @see com.liferay.osb.model.impl.SupportWorkerImpl
 * @see com.liferay.osb.model.impl.SupportWorkerModelImpl
 * @generated
 */
@ProviderType
public interface SupportWorkerModel extends BaseModel<SupportWorker> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support worker model instance should use the {@link SupportWorker} interface instead.
	 */

	/**
	 * Returns the primary key of this support worker.
	 *
	 * @return the primary key of this support worker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support worker.
	 *
	 * @param primaryKey the primary key of this support worker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the support worker ID of this support worker.
	 *
	 * @return the support worker ID of this support worker
	 */
	public long getSupportWorkerId();

	/**
	 * Sets the support worker ID of this support worker.
	 *
	 * @param supportWorkerId the support worker ID of this support worker
	 */
	public void setSupportWorkerId(long supportWorkerId);

	/**
	 * Returns the user ID of this support worker.
	 *
	 * @return the user ID of this support worker
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this support worker.
	 *
	 * @param userId the user ID of this support worker
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this support worker.
	 *
	 * @return the user uuid of this support worker
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this support worker.
	 *
	 * @param userUuid the user uuid of this support worker
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the support team ID of this support worker.
	 *
	 * @return the support team ID of this support worker
	 */
	public long getSupportTeamId();

	/**
	 * Sets the support team ID of this support worker.
	 *
	 * @param supportTeamId the support team ID of this support worker
	 */
	public void setSupportTeamId(long supportTeamId);

	/**
	 * Returns the support labor ID of this support worker.
	 *
	 * @return the support labor ID of this support worker
	 */
	public long getSupportLaborId();

	/**
	 * Sets the support labor ID of this support worker.
	 *
	 * @param supportLaborId the support labor ID of this support worker
	 */
	public void setSupportLaborId(long supportLaborId);

	/**
	 * Returns the auto assign of this support worker.
	 *
	 * @return the auto assign of this support worker
	 */
	public boolean getAutoAssign();

	/**
	 * Returns <code>true</code> if this support worker is auto assign.
	 *
	 * @return <code>true</code> if this support worker is auto assign; <code>false</code> otherwise
	 */
	public boolean isAutoAssign();

	/**
	 * Sets whether this support worker is auto assign.
	 *
	 * @param autoAssign the auto assign of this support worker
	 */
	public void setAutoAssign(boolean autoAssign);

	/**
	 * Returns the assigned work of this support worker.
	 *
	 * @return the assigned work of this support worker
	 */
	public double getAssignedWork();

	/**
	 * Sets the assigned work of this support worker.
	 *
	 * @param assignedWork the assigned work of this support worker
	 */
	public void setAssignedWork(double assignedWork);

	/**
	 * Returns the max work of this support worker.
	 *
	 * @return the max work of this support worker
	 */
	public double getMaxWork();

	/**
	 * Sets the max work of this support worker.
	 *
	 * @param maxWork the max work of this support worker
	 */
	public void setMaxWork(double maxWork);

	/**
	 * Returns the escalation level of this support worker.
	 *
	 * @return the escalation level of this support worker
	 */
	public int getEscalationLevel();

	/**
	 * Sets the escalation level of this support worker.
	 *
	 * @param escalationLevel the escalation level of this support worker
	 */
	public void setEscalationLevel(int escalationLevel);

	/**
	 * Returns the role of this support worker.
	 *
	 * @return the role of this support worker
	 */
	public int getRole();

	/**
	 * Sets the role of this support worker.
	 *
	 * @param role the role of this support worker
	 */
	public void setRole(int role);

	/**
	 * Returns the escalation level2 role of this support worker.
	 *
	 * @return the escalation level2 role of this support worker
	 */
	public int getEscalationLevel2Role();

	/**
	 * Sets the escalation level2 role of this support worker.
	 *
	 * @param escalationLevel2Role the escalation level2 role of this support worker
	 */
	public void setEscalationLevel2Role(int escalationLevel2Role);

	/**
	 * Returns the notifications of this support worker.
	 *
	 * @return the notifications of this support worker
	 */
	public int getNotifications();

	/**
	 * Sets the notifications of this support worker.
	 *
	 * @param notifications the notifications of this support worker
	 */
	public void setNotifications(int notifications);

	/**
	 * Returns the clocked in of this support worker.
	 *
	 * @return the clocked in of this support worker
	 */
	public boolean getClockedIn();

	/**
	 * Returns <code>true</code> if this support worker is clocked in.
	 *
	 * @return <code>true</code> if this support worker is clocked in; <code>false</code> otherwise
	 */
	public boolean isClockedIn();

	/**
	 * Sets whether this support worker is clocked in.
	 *
	 * @param clockedIn the clocked in of this support worker
	 */
	public void setClockedIn(boolean clockedIn);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SupportWorker supportWorker);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SupportWorker> toCacheModel();

	@Override
	public SupportWorker toEscapedModel();

	@Override
	public SupportWorker toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}