/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TicketWorker service. Represents a row in the &quot;OSB_TicketWorker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.TicketWorkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.TicketWorkerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketWorker
 * @see com.liferay.osb.model.impl.TicketWorkerImpl
 * @see com.liferay.osb.model.impl.TicketWorkerModelImpl
 * @generated
 */
public interface TicketWorkerModel extends BaseModel<TicketWorker> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket worker model instance should use the {@link TicketWorker} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket worker.
	 *
	 * @return the primary key of this ticket worker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket worker.
	 *
	 * @param primaryKey the primary key of this ticket worker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket worker ID of this ticket worker.
	 *
	 * @return the ticket worker ID of this ticket worker
	 */
	public long getTicketWorkerId();

	/**
	 * Sets the ticket worker ID of this ticket worker.
	 *
	 * @param ticketWorkerId the ticket worker ID of this ticket worker
	 */
	public void setTicketWorkerId(long ticketWorkerId);

	/**
	 * Returns the user ID of this ticket worker.
	 *
	 * @return the user ID of this ticket worker
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ticket worker.
	 *
	 * @param userId the user ID of this ticket worker
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ticket worker.
	 *
	 * @return the user uuid of this ticket worker
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this ticket worker.
	 *
	 * @param userUuid the user uuid of this ticket worker
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ticket entry ID of this ticket worker.
	 *
	 * @return the ticket entry ID of this ticket worker
	 */
	public long getTicketEntryId();

	/**
	 * Sets the ticket entry ID of this ticket worker.
	 *
	 * @param ticketEntryId the ticket entry ID of this ticket worker
	 */
	public void setTicketEntryId(long ticketEntryId);

	/**
	 * Returns the source class name ID of this ticket worker.
	 *
	 * @return the source class name ID of this ticket worker
	 */
	public long getSourceClassNameId();

	/**
	 * Sets the source class name ID of this ticket worker.
	 *
	 * @param sourceClassNameId the source class name ID of this ticket worker
	 */
	public void setSourceClassNameId(long sourceClassNameId);

	/**
	 * Returns the source class p k of this ticket worker.
	 *
	 * @return the source class p k of this ticket worker
	 */
	public long getSourceClassPK();

	/**
	 * Sets the source class p k of this ticket worker.
	 *
	 * @param sourceClassPK the source class p k of this ticket worker
	 */
	public void setSourceClassPK(long sourceClassPK);

	/**
	 * Returns the role of this ticket worker.
	 *
	 * @return the role of this ticket worker
	 */
	public int getRole();

	/**
	 * Sets the role of this ticket worker.
	 *
	 * @param role the role of this ticket worker
	 */
	public void setRole(int role);

	/**
	 * Returns the primary of this ticket worker.
	 *
	 * @return the primary of this ticket worker
	 */
	public boolean getPrimary();

	/**
	 * Returns <code>true</code> if this ticket worker is primary.
	 *
	 * @return <code>true</code> if this ticket worker is primary; <code>false</code> otherwise
	 */
	public boolean isPrimary();

	/**
	 * Sets whether this ticket worker is primary.
	 *
	 * @param primary the primary of this ticket worker
	 */
	public void setPrimary(boolean primary);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TicketWorker ticketWorker);

	public int hashCode();

	public CacheModel<TicketWorker> toCacheModel();

	public TicketWorker toEscapedModel();

	public TicketWorker toUnescapedModel();

	public String toString();

	public String toXmlString();
}