/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TrainingLocation service. Represents a row in the &quot;OSB_TrainingLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.TrainingLocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.TrainingLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingLocation
 * @see com.liferay.osb.model.impl.TrainingLocationImpl
 * @see com.liferay.osb.model.impl.TrainingLocationModelImpl
 * @generated
 */
public interface TrainingLocationModel extends BaseModel<TrainingLocation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training location model instance should use the {@link TrainingLocation} interface instead.
	 */

	/**
	 * Returns the primary key of this training location.
	 *
	 * @return the primary key of this training location
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this training location.
	 *
	 * @param primaryKey the primary key of this training location
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the training location ID of this training location.
	 *
	 * @return the training location ID of this training location
	 */
	public long getTrainingLocationId();

	/**
	 * Sets the training location ID of this training location.
	 *
	 * @param trainingLocationId the training location ID of this training location
	 */
	public void setTrainingLocationId(long trainingLocationId);

	/**
	 * Returns the user ID of this training location.
	 *
	 * @return the user ID of this training location
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this training location.
	 *
	 * @param userId the user ID of this training location
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this training location.
	 *
	 * @return the user uuid of this training location
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this training location.
	 *
	 * @param userUuid the user uuid of this training location
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this training location.
	 *
	 * @return the user name of this training location
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this training location.
	 *
	 * @param userName the user name of this training location
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this training location.
	 *
	 * @return the create date of this training location
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this training location.
	 *
	 * @param createDate the create date of this training location
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this training location.
	 *
	 * @return the modified date of this training location
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this training location.
	 *
	 * @param modifiedDate the modified date of this training location
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this training location.
	 *
	 * @return the name of this training location
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this training location.
	 *
	 * @param name the name of this training location
	 */
	public void setName(String name);

	/**
	 * Returns the address ID of this training location.
	 *
	 * @return the address ID of this training location
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this training location.
	 *
	 * @param addressId the address ID of this training location
	 */
	public void setAddressId(long addressId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TrainingLocation trainingLocation);

	public int hashCode();

	public CacheModel<TrainingLocation> toCacheModel();

	public TrainingLocation toEscapedModel();

	public TrainingLocation toUnescapedModel();

	public String toString();

	public String toXmlString();
}