/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TrainingCustomer service. Represents a row in the &quot;OSB_TrainingCustomer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.TrainingCustomerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.TrainingCustomerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingCustomer
 * @see com.liferay.osb.model.impl.TrainingCustomerImpl
 * @see com.liferay.osb.model.impl.TrainingCustomerModelImpl
 * @generated
 */
public interface TrainingCustomerModel extends AttachedModel,
	BaseModel<TrainingCustomer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training customer model instance should use the {@link TrainingCustomer} interface instead.
	 */

	/**
	 * Returns the primary key of this training customer.
	 *
	 * @return the primary key of this training customer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this training customer.
	 *
	 * @param primaryKey the primary key of this training customer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the training customer ID of this training customer.
	 *
	 * @return the training customer ID of this training customer
	 */
	public long getTrainingCustomerId();

	/**
	 * Sets the training customer ID of this training customer.
	 *
	 * @param trainingCustomerId the training customer ID of this training customer
	 */
	public void setTrainingCustomerId(long trainingCustomerId);

	/**
	 * Returns the user ID of this training customer.
	 *
	 * @return the user ID of this training customer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this training customer.
	 *
	 * @param userId the user ID of this training customer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this training customer.
	 *
	 * @return the user uuid of this training customer
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this training customer.
	 *
	 * @param userUuid the user uuid of this training customer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the fully qualified class name of this training customer.
	 *
	 * @return the fully qualified class name of this training customer
	 */
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this training customer.
	 *
	 * @return the class name ID of this training customer
	 */
	public long getClassNameId();

	/**
	 * Sets the class name ID of this training customer.
	 *
	 * @param classNameId the class name ID of this training customer
	 */
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this training customer.
	 *
	 * @return the class p k of this training customer
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this training customer.
	 *
	 * @param classPK the class p k of this training customer
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the user profile history ID of this training customer.
	 *
	 * @return the user profile history ID of this training customer
	 */
	public long getUserProfileHistoryId();

	/**
	 * Sets the user profile history ID of this training customer.
	 *
	 * @param userProfileHistoryId the user profile history ID of this training customer
	 */
	public void setUserProfileHistoryId(long userProfileHistoryId);

	/**
	 * Returns the comments of this training customer.
	 *
	 * @return the comments of this training customer
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this training customer.
	 *
	 * @param comments the comments of this training customer
	 */
	public void setComments(String comments);

	/**
	 * Returns the status of this training customer.
	 *
	 * @return the status of this training customer
	 */
	public int getStatus();

	/**
	 * Sets the status of this training customer.
	 *
	 * @param status the status of this training customer
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TrainingCustomer trainingCustomer);

	public int hashCode();

	public CacheModel<TrainingCustomer> toCacheModel();

	public TrainingCustomer toEscapedModel();

	public TrainingCustomer toUnescapedModel();

	public String toString();

	public String toXmlString();
}