/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserProfile service. Represents a row in the &quot;OSB_UserProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.model.impl.UserProfileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.model.impl.UserProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserProfile
 * @see com.liferay.osb.model.impl.UserProfileImpl
 * @see com.liferay.osb.model.impl.UserProfileModelImpl
 * @generated
 */
public interface UserProfileModel extends BaseModel<UserProfile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user profile model instance should use the {@link UserProfile} interface instead.
	 */

	/**
	 * Returns the primary key of this user profile.
	 *
	 * @return the primary key of this user profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user profile.
	 *
	 * @param primaryKey the primary key of this user profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user profile ID of this user profile.
	 *
	 * @return the user profile ID of this user profile
	 */
	public long getUserProfileId();

	/**
	 * Sets the user profile ID of this user profile.
	 *
	 * @param userProfileId the user profile ID of this user profile
	 */
	public void setUserProfileId(long userProfileId);

	/**
	 * Returns the user ID of this user profile.
	 *
	 * @return the user ID of this user profile
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user profile.
	 *
	 * @param userId the user ID of this user profile
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user profile.
	 *
	 * @return the user uuid of this user profile
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user profile.
	 *
	 * @param userUuid the user uuid of this user profile
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the email address of this user profile.
	 *
	 * @return the email address of this user profile
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this user profile.
	 *
	 * @param emailAddress the email address of this user profile
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the first name of this user profile.
	 *
	 * @return the first name of this user profile
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this user profile.
	 *
	 * @param firstName the first name of this user profile
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this user profile.
	 *
	 * @return the last name of this user profile
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this user profile.
	 *
	 * @param lastName the last name of this user profile
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the legal entity name of this user profile.
	 *
	 * @return the legal entity name of this user profile
	 */
	@AutoEscape
	public String getLegalEntityName();

	/**
	 * Sets the legal entity name of this user profile.
	 *
	 * @param legalEntityName the legal entity name of this user profile
	 */
	public void setLegalEntityName(String legalEntityName);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(UserProfile userProfile);

	public int hashCode();

	public CacheModel<UserProfile> toCacheModel();

	public UserProfile toEscapedModel();

	public UserProfile toUnescapedModel();

	public String toString();

	public String toXmlString();
}