/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.loop.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.loop.model.LoopPerson;
import com.liferay.osb.loop.model.LoopPersonModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LoopPerson service. Represents a row in the &quot;LoopPerson&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LoopPersonModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoopPersonImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopPersonImpl
 * @generated
 */
public class LoopPersonModelImpl
	extends BaseModelImpl<LoopPerson> implements LoopPersonModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loop person model instance should use the <code>LoopPerson</code> interface instead.
	 */
	public static final String TABLE_NAME = "LoopPerson";

	public static final Object[][] TABLE_COLUMNS = {
		{"loopPersonId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"loopJobTitleId", Types.BIGINT}, {"managerLoopPersonId", Types.BIGINT},
		{"personUserId", Types.BIGINT}, {"extraData", Types.VARCHAR},
		{"groupedUserNotificationEventsCount", Types.INTEGER},
		{"imagePayload", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("loopPersonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("loopJobTitleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("managerLoopPersonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("personUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("extraData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put(
			"groupedUserNotificationEventsCount", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("imagePayload", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LoopPerson (loopPersonId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,loopJobTitleId LONG,managerLoopPersonId LONG,personUserId LONG,extraData STRING null,groupedUserNotificationEventsCount INTEGER,imagePayload STRING null)";

	public static final String TABLE_SQL_DROP = "drop table LoopPerson";

	public static final String ORDER_BY_JPQL =
		" ORDER BY loopPerson.loopPersonId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LoopPerson.loopPersonId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.loop.model.LoopPerson"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.loop.model.LoopPerson"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.loop.model.LoopPerson"),
		true);

	public static final long PERSONUSERID_COLUMN_BITMASK = 1L;

	public static final long LOOPPERSONID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.loop.model.LoopPerson"));

	public LoopPersonModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loopPersonId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoopPersonId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loopPersonId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoopPerson.class;
	}

	@Override
	public String getModelClassName() {
		return LoopPerson.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LoopPerson, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LoopPerson, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoopPerson, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LoopPerson)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LoopPerson, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LoopPerson, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LoopPerson)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LoopPerson, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LoopPerson, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LoopPerson>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LoopPerson.class.getClassLoader(), LoopPerson.class,
			ModelWrapper.class);

		try {
			Constructor<LoopPerson> constructor =
				(Constructor<LoopPerson>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LoopPerson, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<LoopPerson, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LoopPerson, Object>>();

		attributeGetterFunctions.put(
			"loopPersonId",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getLoopPersonId();
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getCompanyId();
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getUserId();
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getUserName();
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getCreateDate();
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getModifiedDate();
				}

			});
		attributeGetterFunctions.put(
			"loopJobTitleId",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getLoopJobTitleId();
				}

			});
		attributeGetterFunctions.put(
			"managerLoopPersonId",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getManagerLoopPersonId();
				}

			});
		attributeGetterFunctions.put(
			"personUserId",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getPersonUserId();
				}

			});
		attributeGetterFunctions.put(
			"extraData",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getExtraData();
				}

			});
		attributeGetterFunctions.put(
			"groupedUserNotificationEventsCount",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getGroupedUserNotificationEventsCount();
				}

			});
		attributeGetterFunctions.put(
			"imagePayload",
			new Function<LoopPerson, Object>() {

				@Override
				public Object apply(LoopPerson loopPerson) {
					return loopPerson.getImagePayload();
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<LoopPerson, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<LoopPerson, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LoopPerson, ?>>();

		attributeSetterBiConsumers.put(
			"loopPersonId",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object loopPersonIdObject) {

					loopPerson.setLoopPersonId((Long)loopPersonIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object companyIdObject) {

					loopPerson.setCompanyId((Long)companyIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(LoopPerson loopPerson, Object userIdObject) {
					loopPerson.setUserId((Long)userIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object userNameObject) {

					loopPerson.setUserName((String)userNameObject);
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object createDateObject) {

					loopPerson.setCreateDate((Date)createDateObject);
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object modifiedDateObject) {

					loopPerson.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeSetterBiConsumers.put(
			"loopJobTitleId",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object loopJobTitleIdObject) {

					loopPerson.setLoopJobTitleId((Long)loopJobTitleIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"managerLoopPersonId",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object managerLoopPersonIdObject) {

					loopPerson.setManagerLoopPersonId(
						(Long)managerLoopPersonIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"personUserId",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object personUserIdObject) {

					loopPerson.setPersonUserId((Long)personUserIdObject);
				}

			});
		attributeSetterBiConsumers.put(
			"extraData",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object extraDataObject) {

					loopPerson.setExtraData((String)extraDataObject);
				}

			});
		attributeSetterBiConsumers.put(
			"groupedUserNotificationEventsCount",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson,
					Object groupedUserNotificationEventsCountObject) {

					loopPerson.setGroupedUserNotificationEventsCount(
						(Integer)groupedUserNotificationEventsCountObject);
				}

			});
		attributeSetterBiConsumers.put(
			"imagePayload",
			new BiConsumer<LoopPerson, Object>() {

				@Override
				public void accept(
					LoopPerson loopPerson, Object imagePayloadObject) {

					loopPerson.setImagePayload((String)imagePayloadObject);
				}

			});

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLoopPersonId() {
		return _loopPersonId;
	}

	@Override
	public void setLoopPersonId(long loopPersonId) {
		_loopPersonId = loopPersonId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getLoopJobTitleId() {
		return _loopJobTitleId;
	}

	@Override
	public void setLoopJobTitleId(long loopJobTitleId) {
		_loopJobTitleId = loopJobTitleId;
	}

	@Override
	public long getManagerLoopPersonId() {
		return _managerLoopPersonId;
	}

	@Override
	public void setManagerLoopPersonId(long managerLoopPersonId) {
		_managerLoopPersonId = managerLoopPersonId;
	}

	@Override
	public long getPersonUserId() {
		return _personUserId;
	}

	@Override
	public void setPersonUserId(long personUserId) {
		_columnBitmask |= PERSONUSERID_COLUMN_BITMASK;

		if (!_setOriginalPersonUserId) {
			_setOriginalPersonUserId = true;

			_originalPersonUserId = _personUserId;
		}

		_personUserId = personUserId;
	}

	@Override
	public String getPersonUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getPersonUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setPersonUserUuid(String personUserUuid) {
	}

	public long getOriginalPersonUserId() {
		return _originalPersonUserId;
	}

	@Override
	public String getExtraData() {
		if (_extraData == null) {
			return "";
		}
		else {
			return _extraData;
		}
	}

	@Override
	public void setExtraData(String extraData) {
		_extraData = extraData;
	}

	@Override
	public int getGroupedUserNotificationEventsCount() {
		return _groupedUserNotificationEventsCount;
	}

	@Override
	public void setGroupedUserNotificationEventsCount(
		int groupedUserNotificationEventsCount) {

		_groupedUserNotificationEventsCount =
			groupedUserNotificationEventsCount;
	}

	@Override
	public String getImagePayload() {
		if (_imagePayload == null) {
			return "";
		}
		else {
			return _imagePayload;
		}
	}

	@Override
	public void setImagePayload(String imagePayload) {
		_imagePayload = imagePayload;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LoopPerson.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoopPerson toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LoopPerson>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoopPersonImpl loopPersonImpl = new LoopPersonImpl();

		loopPersonImpl.setLoopPersonId(getLoopPersonId());
		loopPersonImpl.setCompanyId(getCompanyId());
		loopPersonImpl.setUserId(getUserId());
		loopPersonImpl.setUserName(getUserName());
		loopPersonImpl.setCreateDate(getCreateDate());
		loopPersonImpl.setModifiedDate(getModifiedDate());
		loopPersonImpl.setLoopJobTitleId(getLoopJobTitleId());
		loopPersonImpl.setManagerLoopPersonId(getManagerLoopPersonId());
		loopPersonImpl.setPersonUserId(getPersonUserId());
		loopPersonImpl.setExtraData(getExtraData());
		loopPersonImpl.setGroupedUserNotificationEventsCount(
			getGroupedUserNotificationEventsCount());
		loopPersonImpl.setImagePayload(getImagePayload());

		loopPersonImpl.resetOriginalValues();

		return loopPersonImpl;
	}

	@Override
	public int compareTo(LoopPerson loopPerson) {
		long primaryKey = loopPerson.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LoopPerson)) {
			return false;
		}

		LoopPerson loopPerson = (LoopPerson)object;

		long primaryKey = loopPerson.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;

		_originalPersonUserId = _personUserId;

		_setOriginalPersonUserId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LoopPerson> toCacheModel() {
		LoopPersonCacheModel loopPersonCacheModel = new LoopPersonCacheModel();

		loopPersonCacheModel.loopPersonId = getLoopPersonId();

		loopPersonCacheModel.companyId = getCompanyId();

		loopPersonCacheModel.userId = getUserId();

		loopPersonCacheModel.userName = getUserName();

		String userName = loopPersonCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loopPersonCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			loopPersonCacheModel.createDate = createDate.getTime();
		}
		else {
			loopPersonCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			loopPersonCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			loopPersonCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		loopPersonCacheModel.loopJobTitleId = getLoopJobTitleId();

		loopPersonCacheModel.managerLoopPersonId = getManagerLoopPersonId();

		loopPersonCacheModel.personUserId = getPersonUserId();

		loopPersonCacheModel.extraData = getExtraData();

		String extraData = loopPersonCacheModel.extraData;

		if ((extraData != null) && (extraData.length() == 0)) {
			loopPersonCacheModel.extraData = null;
		}

		loopPersonCacheModel.groupedUserNotificationEventsCount =
			getGroupedUserNotificationEventsCount();

		loopPersonCacheModel.imagePayload = getImagePayload();

		String imagePayload = loopPersonCacheModel.imagePayload;

		if ((imagePayload != null) && (imagePayload.length() == 0)) {
			loopPersonCacheModel.imagePayload = null;
		}

		return loopPersonCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LoopPerson, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LoopPerson, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoopPerson, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((LoopPerson)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LoopPerson, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LoopPerson, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoopPerson, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LoopPerson)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LoopPerson>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _loopPersonId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _loopJobTitleId;
	private long _managerLoopPersonId;
	private long _personUserId;
	private long _originalPersonUserId;
	private boolean _setOriginalPersonUserId;
	private String _extraData;
	private int _groupedUserNotificationEventsCount;
	private String _imagePayload;
	private long _columnBitmask;
	private LoopPerson _escapedModel;

}