/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.loop.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.loop.model.LoopUserNotificationRecord;
import com.liferay.osb.loop.model.LoopUserNotificationRecordModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LoopUserNotificationRecord service. Represents a row in the &quot;LoopUserNotificationRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LoopUserNotificationRecordModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoopUserNotificationRecordImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopUserNotificationRecordImpl
 * @see LoopUserNotificationRecord
 * @see LoopUserNotificationRecordModel
 * @generated
 */
@ProviderType
public class LoopUserNotificationRecordModelImpl extends BaseModelImpl<LoopUserNotificationRecord>
	implements LoopUserNotificationRecordModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loop user notification record model instance should use the {@link LoopUserNotificationRecord} interface instead.
	 */
	public static final String TABLE_NAME = "LoopUserNotificationRecord";
	public static final Object[][] TABLE_COLUMNS = {
			{ "loopUserNotificationRecordId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createTime", Types.BIGINT },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "deliveryType", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("loopUserNotificationRecordId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("deliveryType", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table LoopUserNotificationRecord (loopUserNotificationRecordId LONG not null primary key,userId LONG,createTime LONG,classNameId LONG,classPK LONG,deliveryType INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table LoopUserNotificationRecord";
	public static final String ORDER_BY_JPQL = " ORDER BY loopUserNotificationRecord.loopUserNotificationRecordId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LoopUserNotificationRecord.loopUserNotificationRecordId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.loop.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.loop.model.LoopUserNotificationRecord"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.loop.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.loop.model.LoopUserNotificationRecord"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.loop.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.loop.model.LoopUserNotificationRecord"));

	public LoopUserNotificationRecordModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loopUserNotificationRecordId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoopUserNotificationRecordId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loopUserNotificationRecordId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoopUserNotificationRecord.class;
	}

	@Override
	public String getModelClassName() {
		return LoopUserNotificationRecord.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("loopUserNotificationRecordId",
			getLoopUserNotificationRecordId());
		attributes.put("userId", getUserId());
		attributes.put("createTime", getCreateTime());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("deliveryType", getDeliveryType());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long loopUserNotificationRecordId = (Long)attributes.get(
				"loopUserNotificationRecordId");

		if (loopUserNotificationRecordId != null) {
			setLoopUserNotificationRecordId(loopUserNotificationRecordId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long createTime = (Long)attributes.get("createTime");

		if (createTime != null) {
			setCreateTime(createTime);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		Integer deliveryType = (Integer)attributes.get("deliveryType");

		if (deliveryType != null) {
			setDeliveryType(deliveryType);
		}
	}

	@Override
	public long getLoopUserNotificationRecordId() {
		return _loopUserNotificationRecordId;
	}

	@Override
	public void setLoopUserNotificationRecordId(
		long loopUserNotificationRecordId) {
		_loopUserNotificationRecordId = loopUserNotificationRecordId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(long createTime) {
		_createTime = createTime;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@Override
	public int getDeliveryType() {
		return _deliveryType;
	}

	@Override
	public void setDeliveryType(int deliveryType) {
		_deliveryType = deliveryType;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LoopUserNotificationRecord.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoopUserNotificationRecord toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LoopUserNotificationRecord)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoopUserNotificationRecordImpl loopUserNotificationRecordImpl = new LoopUserNotificationRecordImpl();

		loopUserNotificationRecordImpl.setLoopUserNotificationRecordId(getLoopUserNotificationRecordId());
		loopUserNotificationRecordImpl.setUserId(getUserId());
		loopUserNotificationRecordImpl.setCreateTime(getCreateTime());
		loopUserNotificationRecordImpl.setClassNameId(getClassNameId());
		loopUserNotificationRecordImpl.setClassPK(getClassPK());
		loopUserNotificationRecordImpl.setDeliveryType(getDeliveryType());

		loopUserNotificationRecordImpl.resetOriginalValues();

		return loopUserNotificationRecordImpl;
	}

	@Override
	public int compareTo(LoopUserNotificationRecord loopUserNotificationRecord) {
		long primaryKey = loopUserNotificationRecord.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoopUserNotificationRecord)) {
			return false;
		}

		LoopUserNotificationRecord loopUserNotificationRecord = (LoopUserNotificationRecord)obj;

		long primaryKey = loopUserNotificationRecord.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LoopUserNotificationRecord> toCacheModel() {
		LoopUserNotificationRecordCacheModel loopUserNotificationRecordCacheModel =
			new LoopUserNotificationRecordCacheModel();

		loopUserNotificationRecordCacheModel.loopUserNotificationRecordId = getLoopUserNotificationRecordId();

		loopUserNotificationRecordCacheModel.userId = getUserId();

		loopUserNotificationRecordCacheModel.createTime = getCreateTime();

		loopUserNotificationRecordCacheModel.classNameId = getClassNameId();

		loopUserNotificationRecordCacheModel.classPK = getClassPK();

		loopUserNotificationRecordCacheModel.deliveryType = getDeliveryType();

		return loopUserNotificationRecordCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{loopUserNotificationRecordId=");
		sb.append(getLoopUserNotificationRecordId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createTime=");
		sb.append(getCreateTime());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", deliveryType=");
		sb.append(getDeliveryType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.loop.model.LoopUserNotificationRecord");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>loopUserNotificationRecordId</column-name><column-value><![CDATA[");
		sb.append(getLoopUserNotificationRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createTime</column-name><column-value><![CDATA[");
		sb.append(getCreateTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deliveryType</column-name><column-value><![CDATA[");
		sb.append(getDeliveryType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LoopUserNotificationRecord.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LoopUserNotificationRecord.class
		};
	private long _loopUserNotificationRecordId;
	private long _userId;
	private long _createTime;
	private long _classNameId;
	private long _classPK;
	private int _deliveryType;
	private LoopUserNotificationRecord _escapedModel;
}