/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.loop.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.loop.model.LoopJobTitle;
import com.liferay.osb.loop.model.LoopJobTitleModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LoopJobTitle service. Represents a row in the &quot;LoopJobTitle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LoopJobTitleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoopJobTitleImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopJobTitleImpl
 * @generated
 */
public class LoopJobTitleModelImpl
	extends BaseModelImpl<LoopJobTitle> implements LoopJobTitleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loop job title model instance should use the <code>LoopJobTitle</code> interface instead.
	 */
	public static final String TABLE_NAME = "LoopJobTitle";

	public static final Object[][] TABLE_COLUMNS = {
		{"loopJobTitleId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("loopJobTitleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LoopJobTitle (loopJobTitleId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description STRING null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table LoopJobTitle";

	public static final String ORDER_BY_JPQL =
		" ORDER BY loopJobTitle.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY LoopJobTitle.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.loop.model.LoopJobTitle"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.loop.model.LoopJobTitle"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.loop.model.LoopJobTitle"),
		true);

	public static final long NAME_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.loop.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.loop.model.LoopJobTitle"));

	public LoopJobTitleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loopJobTitleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoopJobTitleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loopJobTitleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoopJobTitle.class;
	}

	@Override
	public String getModelClassName() {
		return LoopJobTitle.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LoopJobTitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LoopJobTitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoopJobTitle, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LoopJobTitle)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LoopJobTitle, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LoopJobTitle, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LoopJobTitle)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LoopJobTitle, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LoopJobTitle, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LoopJobTitle>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LoopJobTitle.class.getClassLoader(), LoopJobTitle.class,
			ModelWrapper.class);

		try {
			Constructor<LoopJobTitle> constructor =
				(Constructor<LoopJobTitle>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LoopJobTitle, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LoopJobTitle, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LoopJobTitle, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LoopJobTitle, Object>>();
		Map<String, BiConsumer<LoopJobTitle, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LoopJobTitle, ?>>();

		attributeGetterFunctions.put(
			"loopJobTitleId",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getLoopJobTitleId();
				}

			});
		attributeSetterBiConsumers.put(
			"loopJobTitleId",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object loopJobTitleIdObject) {

					loopJobTitle.setLoopJobTitleId((Long)loopJobTitleIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object companyIdObject) {

					loopJobTitle.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object userIdObject) {

					loopJobTitle.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object userNameObject) {

					loopJobTitle.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object createDateObject) {

					loopJobTitle.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object modifiedDateObject) {

					loopJobTitle.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object nameObject) {

					loopJobTitle.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object descriptionObject) {

					loopJobTitle.setDescription((String)descriptionObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<LoopJobTitle, Object>() {

				@Override
				public Object apply(LoopJobTitle loopJobTitle) {
					return loopJobTitle.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<LoopJobTitle, Object>() {

				@Override
				public void accept(
					LoopJobTitle loopJobTitle, Object statusObject) {

					loopJobTitle.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getLoopJobTitleId() {
		return _loopJobTitleId;
	}

	@Override
	public void setLoopJobTitleId(long loopJobTitleId) {
		_loopJobTitleId = loopJobTitleId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LoopJobTitle.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoopJobTitle toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LoopJobTitle>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoopJobTitleImpl loopJobTitleImpl = new LoopJobTitleImpl();

		loopJobTitleImpl.setLoopJobTitleId(getLoopJobTitleId());
		loopJobTitleImpl.setCompanyId(getCompanyId());
		loopJobTitleImpl.setUserId(getUserId());
		loopJobTitleImpl.setUserName(getUserName());
		loopJobTitleImpl.setCreateDate(getCreateDate());
		loopJobTitleImpl.setModifiedDate(getModifiedDate());
		loopJobTitleImpl.setName(getName());
		loopJobTitleImpl.setDescription(getDescription());
		loopJobTitleImpl.setStatus(getStatus());

		loopJobTitleImpl.resetOriginalValues();

		return loopJobTitleImpl;
	}

	@Override
	public int compareTo(LoopJobTitle loopJobTitle) {
		int value = 0;

		value = getName().compareTo(loopJobTitle.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoopJobTitle)) {
			return false;
		}

		LoopJobTitle loopJobTitle = (LoopJobTitle)obj;

		long primaryKey = loopJobTitle.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LoopJobTitleModelImpl loopJobTitleModelImpl = this;

		loopJobTitleModelImpl._setModifiedDate = false;

		loopJobTitleModelImpl._originalName = loopJobTitleModelImpl._name;

		loopJobTitleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LoopJobTitle> toCacheModel() {
		LoopJobTitleCacheModel loopJobTitleCacheModel =
			new LoopJobTitleCacheModel();

		loopJobTitleCacheModel.loopJobTitleId = getLoopJobTitleId();

		loopJobTitleCacheModel.companyId = getCompanyId();

		loopJobTitleCacheModel.userId = getUserId();

		loopJobTitleCacheModel.userName = getUserName();

		String userName = loopJobTitleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			loopJobTitleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			loopJobTitleCacheModel.createDate = createDate.getTime();
		}
		else {
			loopJobTitleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			loopJobTitleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			loopJobTitleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		loopJobTitleCacheModel.name = getName();

		String name = loopJobTitleCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			loopJobTitleCacheModel.name = null;
		}

		loopJobTitleCacheModel.description = getDescription();

		String description = loopJobTitleCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			loopJobTitleCacheModel.description = null;
		}

		loopJobTitleCacheModel.status = getStatus();

		return loopJobTitleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LoopJobTitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LoopJobTitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoopJobTitle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LoopJobTitle)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LoopJobTitle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LoopJobTitle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LoopJobTitle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LoopJobTitle)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LoopJobTitle>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _loopJobTitleId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _description;
	private int _status;
	private long _columnBitmask;
	private LoopJobTitle _escapedModel;

}