/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.loop.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.loop.model.LoopTopicAssignment;
import com.liferay.osb.loop.model.LoopTopicAssignmentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LoopTopicAssignment service. Represents a row in the &quot;LoopTopicAssignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LoopTopicAssignmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoopTopicAssignmentImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopTopicAssignmentImpl
 * @see LoopTopicAssignment
 * @see LoopTopicAssignmentModel
 * @generated
 */
@ProviderType
public class LoopTopicAssignmentModelImpl extends BaseModelImpl<LoopTopicAssignment>
	implements LoopTopicAssignmentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loop topic assignment model instance should use the {@link LoopTopicAssignment} interface instead.
	 */
	public static final String TABLE_NAME = "LoopTopicAssignment";
	public static final Object[][] TABLE_COLUMNS = {
			{ "loopTopicAssignmentId", Types.BIGINT },
			{ "loopPersonId", Types.BIGINT },
			{ "loopTopicId", Types.BIGINT },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusByDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("loopTopicAssignmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("loopPersonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("loopTopicId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusByDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table LoopTopicAssignment (loopTopicAssignmentId LONG not null primary key,loopPersonId LONG,loopTopicId LONG,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusByDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table LoopTopicAssignment";
	public static final String ORDER_BY_JPQL = " ORDER BY loopTopicAssignment.loopTopicAssignmentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LoopTopicAssignment.loopTopicAssignmentId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.loop.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.loop.model.LoopTopicAssignment"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.loop.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.loop.model.LoopTopicAssignment"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.loop.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.loop.model.LoopTopicAssignment"));

	public LoopTopicAssignmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loopTopicAssignmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoopTopicAssignmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loopTopicAssignmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoopTopicAssignment.class;
	}

	@Override
	public String getModelClassName() {
		return LoopTopicAssignment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("loopTopicAssignmentId", getLoopTopicAssignmentId());
		attributes.put("loopPersonId", getLoopPersonId());
		attributes.put("loopTopicId", getLoopTopicId());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusByDate", getStatusByDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long loopTopicAssignmentId = (Long)attributes.get(
				"loopTopicAssignmentId");

		if (loopTopicAssignmentId != null) {
			setLoopTopicAssignmentId(loopTopicAssignmentId);
		}

		Long loopPersonId = (Long)attributes.get("loopPersonId");

		if (loopPersonId != null) {
			setLoopPersonId(loopPersonId);
		}

		Long loopTopicId = (Long)attributes.get("loopTopicId");

		if (loopTopicId != null) {
			setLoopTopicId(loopTopicId);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusByDate = (Date)attributes.get("statusByDate");

		if (statusByDate != null) {
			setStatusByDate(statusByDate);
		}
	}

	@Override
	public long getLoopTopicAssignmentId() {
		return _loopTopicAssignmentId;
	}

	@Override
	public void setLoopTopicAssignmentId(long loopTopicAssignmentId) {
		_loopTopicAssignmentId = loopTopicAssignmentId;
	}

	@Override
	public long getLoopPersonId() {
		return _loopPersonId;
	}

	@Override
	public void setLoopPersonId(long loopPersonId) {
		_loopPersonId = loopPersonId;
	}

	@Override
	public long getLoopTopicId() {
		return _loopTopicId;
	}

	@Override
	public void setLoopTopicId(long loopTopicId) {
		_loopTopicId = loopTopicId;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusByDate() {
		return _statusByDate;
	}

	@Override
	public void setStatusByDate(Date statusByDate) {
		_statusByDate = statusByDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LoopTopicAssignment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoopTopicAssignment toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LoopTopicAssignment)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoopTopicAssignmentImpl loopTopicAssignmentImpl = new LoopTopicAssignmentImpl();

		loopTopicAssignmentImpl.setLoopTopicAssignmentId(getLoopTopicAssignmentId());
		loopTopicAssignmentImpl.setLoopPersonId(getLoopPersonId());
		loopTopicAssignmentImpl.setLoopTopicId(getLoopTopicId());
		loopTopicAssignmentImpl.setStatus(getStatus());
		loopTopicAssignmentImpl.setStatusByUserId(getStatusByUserId());
		loopTopicAssignmentImpl.setStatusByUserName(getStatusByUserName());
		loopTopicAssignmentImpl.setStatusByDate(getStatusByDate());

		loopTopicAssignmentImpl.resetOriginalValues();

		return loopTopicAssignmentImpl;
	}

	@Override
	public int compareTo(LoopTopicAssignment loopTopicAssignment) {
		long primaryKey = loopTopicAssignment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoopTopicAssignment)) {
			return false;
		}

		LoopTopicAssignment loopTopicAssignment = (LoopTopicAssignment)obj;

		long primaryKey = loopTopicAssignment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LoopTopicAssignment> toCacheModel() {
		LoopTopicAssignmentCacheModel loopTopicAssignmentCacheModel = new LoopTopicAssignmentCacheModel();

		loopTopicAssignmentCacheModel.loopTopicAssignmentId = getLoopTopicAssignmentId();

		loopTopicAssignmentCacheModel.loopPersonId = getLoopPersonId();

		loopTopicAssignmentCacheModel.loopTopicId = getLoopTopicId();

		loopTopicAssignmentCacheModel.status = getStatus();

		loopTopicAssignmentCacheModel.statusByUserId = getStatusByUserId();

		loopTopicAssignmentCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = loopTopicAssignmentCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			loopTopicAssignmentCacheModel.statusByUserName = null;
		}

		Date statusByDate = getStatusByDate();

		if (statusByDate != null) {
			loopTopicAssignmentCacheModel.statusByDate = statusByDate.getTime();
		}
		else {
			loopTopicAssignmentCacheModel.statusByDate = Long.MIN_VALUE;
		}

		return loopTopicAssignmentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{loopTopicAssignmentId=");
		sb.append(getLoopTopicAssignmentId());
		sb.append(", loopPersonId=");
		sb.append(getLoopPersonId());
		sb.append(", loopTopicId=");
		sb.append(getLoopTopicId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusByDate=");
		sb.append(getStatusByDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.loop.model.LoopTopicAssignment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>loopTopicAssignmentId</column-name><column-value><![CDATA[");
		sb.append(getLoopTopicAssignmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loopPersonId</column-name><column-value><![CDATA[");
		sb.append(getLoopPersonId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loopTopicId</column-name><column-value><![CDATA[");
		sb.append(getLoopTopicId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByDate</column-name><column-value><![CDATA[");
		sb.append(getStatusByDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LoopTopicAssignment.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LoopTopicAssignment.class
		};
	private long _loopTopicAssignmentId;
	private long _loopPersonId;
	private long _loopTopicId;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusByDate;
	private LoopTopicAssignment _escapedModel;
}