/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.loop.model.impl;

import com.liferay.osb.loop.model.LoopExternalReferenceRel;
import com.liferay.osb.loop.service.LoopExternalReferenceRelLocalServiceUtil;

/**
 * The extended model base implementation for the LoopExternalReferenceRel service. Represents a row in the &quot;LoopExternalReferenceRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoopExternalReferenceRelImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopExternalReferenceRelImpl
 * @see LoopExternalReferenceRel
 * @generated
 */
public abstract class LoopExternalReferenceRelBaseImpl
	extends LoopExternalReferenceRelModelImpl
	implements LoopExternalReferenceRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loop external reference rel model instance should use the <code>LoopExternalReferenceRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LoopExternalReferenceRelLocalServiceUtil.
				addLoopExternalReferenceRel(this);
		}
		else {
			LoopExternalReferenceRelLocalServiceUtil.
				updateLoopExternalReferenceRel(this);
		}
	}

}