/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.loop.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.loop.model.LoopPersonRel;
import com.liferay.osb.loop.model.LoopPersonRelModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the LoopPersonRel service. Represents a row in the &quot;LoopPersonRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LoopPersonRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LoopPersonRelImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see LoopPersonRelImpl
 * @see LoopPersonRel
 * @see LoopPersonRelModel
 * @generated
 */
@ProviderType
public class LoopPersonRelModelImpl extends BaseModelImpl<LoopPersonRel>
	implements LoopPersonRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a loop person rel model instance should use the {@link LoopPersonRel} interface instead.
	 */
	public static final String TABLE_NAME = "LoopPersonRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "loopPersonRelId", Types.BIGINT },
			{ "childLoopPersonId", Types.BIGINT },
			{ "parentLoopPersonId", Types.BIGINT },
			{ "type_", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("loopPersonRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("childLoopPersonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentLoopPersonId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table LoopPersonRel (loopPersonRelId LONG not null primary key,childLoopPersonId LONG,parentLoopPersonId LONG,type_ INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table LoopPersonRel";
	public static final String ORDER_BY_JPQL = " ORDER BY loopPersonRel.loopPersonRelId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LoopPersonRel.loopPersonRelId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.loop.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.loop.model.LoopPersonRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.loop.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.loop.model.LoopPersonRel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.loop.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.loop.model.LoopPersonRel"));

	public LoopPersonRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _loopPersonRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLoopPersonRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _loopPersonRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LoopPersonRel.class;
	}

	@Override
	public String getModelClassName() {
		return LoopPersonRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("loopPersonRelId", getLoopPersonRelId());
		attributes.put("childLoopPersonId", getChildLoopPersonId());
		attributes.put("parentLoopPersonId", getParentLoopPersonId());
		attributes.put("type", getType());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long loopPersonRelId = (Long)attributes.get("loopPersonRelId");

		if (loopPersonRelId != null) {
			setLoopPersonRelId(loopPersonRelId);
		}

		Long childLoopPersonId = (Long)attributes.get("childLoopPersonId");

		if (childLoopPersonId != null) {
			setChildLoopPersonId(childLoopPersonId);
		}

		Long parentLoopPersonId = (Long)attributes.get("parentLoopPersonId");

		if (parentLoopPersonId != null) {
			setParentLoopPersonId(parentLoopPersonId);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}
	}

	@Override
	public long getLoopPersonRelId() {
		return _loopPersonRelId;
	}

	@Override
	public void setLoopPersonRelId(long loopPersonRelId) {
		_loopPersonRelId = loopPersonRelId;
	}

	@Override
	public long getChildLoopPersonId() {
		return _childLoopPersonId;
	}

	@Override
	public void setChildLoopPersonId(long childLoopPersonId) {
		_childLoopPersonId = childLoopPersonId;
	}

	@Override
	public long getParentLoopPersonId() {
		return _parentLoopPersonId;
	}

	@Override
	public void setParentLoopPersonId(long parentLoopPersonId) {
		_parentLoopPersonId = parentLoopPersonId;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LoopPersonRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LoopPersonRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LoopPersonRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LoopPersonRelImpl loopPersonRelImpl = new LoopPersonRelImpl();

		loopPersonRelImpl.setLoopPersonRelId(getLoopPersonRelId());
		loopPersonRelImpl.setChildLoopPersonId(getChildLoopPersonId());
		loopPersonRelImpl.setParentLoopPersonId(getParentLoopPersonId());
		loopPersonRelImpl.setType(getType());

		loopPersonRelImpl.resetOriginalValues();

		return loopPersonRelImpl;
	}

	@Override
	public int compareTo(LoopPersonRel loopPersonRel) {
		long primaryKey = loopPersonRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LoopPersonRel)) {
			return false;
		}

		LoopPersonRel loopPersonRel = (LoopPersonRel)obj;

		long primaryKey = loopPersonRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LoopPersonRel> toCacheModel() {
		LoopPersonRelCacheModel loopPersonRelCacheModel = new LoopPersonRelCacheModel();

		loopPersonRelCacheModel.loopPersonRelId = getLoopPersonRelId();

		loopPersonRelCacheModel.childLoopPersonId = getChildLoopPersonId();

		loopPersonRelCacheModel.parentLoopPersonId = getParentLoopPersonId();

		loopPersonRelCacheModel.type = getType();

		return loopPersonRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{loopPersonRelId=");
		sb.append(getLoopPersonRelId());
		sb.append(", childLoopPersonId=");
		sb.append(getChildLoopPersonId());
		sb.append(", parentLoopPersonId=");
		sb.append(getParentLoopPersonId());
		sb.append(", type=");
		sb.append(getType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.loop.model.LoopPersonRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>loopPersonRelId</column-name><column-value><![CDATA[");
		sb.append(getLoopPersonRelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>childLoopPersonId</column-name><column-value><![CDATA[");
		sb.append(getChildLoopPersonId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentLoopPersonId</column-name><column-value><![CDATA[");
		sb.append(getParentLoopPersonId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LoopPersonRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LoopPersonRel.class
		};
	private long _loopPersonRelId;
	private long _childLoopPersonId;
	private long _parentLoopPersonId;
	private int _type;
	private LoopPersonRel _escapedModel;
}