endpoints.enabled=false
endpoints.health.enabled=false
endpoints.prometheus.enabled=false
management.security.enabled=false
osb.asah.security.token=9ZPgFSdEntvRPjgRcstSgkUCBzKyjz4hbuaGbdW9h3BHcJbZLuuSqd6BpFLhRErS