ALTER TABLE ExperimentMetric ADD CONSTRAINT EXPERIMENTID_FKEY FOREIGN KEY (experimentId) REFERENCES Experiment ON DELETE CASCADE;

ALTER TABLE ExperimentVariant ADD CONSTRAINT EXPERIMENTID_FKEY FOREIGN KEY (experimentId) REFERENCES Experiment ON DELETE CASCADE;

ALTER TABLE ExperimentVariantMetric ADD CONSTRAINT EXPERIMENTMETRICID_FKEY FOREIGN KEY (experimentMetricId) REFERENCES ExperimentMetric ON DELETE CASCADE;

ALTER TABLE Job ADD CONSTRAINT ASAHTASKID_FKEY FOREIGN KEY (asahTaskId) REFERENCES AsahTask;

ALTER TABLE JobParameter ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;

ALTER TABLE JobRun ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;

ALTER TABLE RunLog ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE Segment ADD CONSDataSourceHttpTestTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel;