ALTER TABLE ChannelDataSource ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE DataSourceOrganization ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceSite ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceUserGroup ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE EventAnalysis ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;