ALTER TABLE Job ADD CONSTRAINT ASAHTASKID_FKEY FOREIGN KEY (asahTaskId) REFERENCES AsahTask;

ALTER TABLE JobParameter ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;

ALTER TABLE JobRun ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;