ALTER TABLE CustomAssetDashboard ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE Experiment ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;