ALTER TABLE CustomAssetDashboard ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE Experiment ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS AuditEvent (
	id BIGSERIAL PRIMARY KEY,
	createDate TIMESTAMPTZ,
	type TEXT,
	userId TEXT,
	userName TEXT
);