include-and-override=portlet-ext.properties

api.version.current=9
api.version.minimum=2

email.prefix=loop-

external.facebook.url=https://www.facebook.com
external.github.url=https://github.com
external.linkedin.url=https://www.linkedin.com/in
external.twitter.url=https://twitter.com

featured.content.max.count=10

image.cover.max.size[thumbnail]=320x320
image.cover.max.size[web]=960x1280

image.cover.types=raw,thumbnail,web

image.extensions=.gif,.jpeg,.jpg,.png

image.profile.max.size[email]=120x120
image.profile.max.size[mobile]=960x960
image.profile.max.size[web]=180x180

image.profile.types=email,mobile,raw,web

loop.autocomplete.max.results=5

loop.child.posts.display.max=1000

loop.cron.trigger.home.controller=0 0 22 * * ? *
loop.cron.trigger.notifications.controller=0 0 23 * * ? *
loop.cron.trigger.people.controller=0 0 21 * * ? *

loop.email.addresses.admin=

loop.email.notification.attached.content=dependencies/attached_content.tmpl
loop.email.notification.body=dependencies/email_notification_body.tmpl
loop.email.notification.comment=dependencies/comment.tmpl
loop.email.notification.feedback=dependencies/feedback.tmpl
loop.email.notification.feedback.enabled=true
loop.email.notification.from.address=
loop.email.notification.from.name=
loop.email.notification.message.length=10000
loop.email.notification.read.more.link=dependencies/read_more_link.tmpl
loop.email.notification.subject.max.char.count=78

loop.feed.page.default.delta=7

loop.file.uploader.count.max=50

loop.help.journal.article.id=

loop.konami.redirect.url=https://www.liferay.com

loop.notification.setting.defaults[commentsOnMyPosts]=inApp,push
loop.notification.setting.defaults[following]=
loop.notification.setting.defaults[groupMember]=inApp
loop.notification.setting.defaults[likedCommentsAndReplies]=inApp
loop.notification.setting.defaults[likedPost]=inApp
loop.notification.setting.defaults[mentioned]=email,inApp,push
loop.notification.setting.defaults[postsICommentedOn]=inApp
loop.notification.setting.defaults[repliesToMyComments]=inApp,push
loop.notification.setting.defaults[showWarning]=true
loop.notification.setting.defaults[topicExpert]=inApp

loop.notifications.toolbar.page.default.delta=6

loop.page.default.delta=24

loop.person.disabled.fields.loop.person=departmentLoopDivisionIds,emailAddress,employmentType,firstName,jobResponsibilities,lastName,locationLoopDivisionIds,loopJobTitleId,managerLoopPersonIds,preferredName,primaryManagerLoopPersonIds,startDateDay,startDateMonth,startDateYear,teamLoopDivisionIds
loop.person.disabled.fields.loop.person.admin=emailAddress,firstName,lastName

loop.person.top.level.icon=
loop.person.top.level.manager.name=
loop.person.top.level.screen.names=

loop.post.privacy.change.allowed=false

loop.stats.entry.score.decay.multiplier=0.5
loop.stats.entry.score.decay.threshold=0.1
loop.stats.entry.score.decay.time=10080
loop.stats.entry.score.value.add.post=1
loop.stats.entry.score.value.like=1

loop.tests.enabled=false

loop.topic.feedback.name=

loop.topic.page.default.delta=40

loop.truncated.feed.line.char.count[page]=75
loop.truncated.feed.line.char.count[post]=75
loop.truncated.feed.line.char.count.table.element[page]=10
loop.truncated.feed.line.char.count.table.element[post]=10
loop.truncated.feed.line.count[page]=3
loop.truncated.feed.line.count[post]=15
loop.truncated.feed.line.count.grace[page]=2
loop.truncated.feed.line.count.grace[post]=5
loop.truncated.feed.line.count.image[page]=2
loop.truncated.feed.line.count.image[post]=5
loop.truncated.feed.line.count.image.table.element[page]=1
loop.truncated.feed.line.count.image.table.element[post]=3
loop.truncated.feed.line.count.max[page]=3
loop.truncated.feed.line.count.max[post]=50

loop.ui.kit.page.enabled=true

loop.user.notification.clean.time=262800

new.division.age.threshold=14
new.hire.age.threshold=14

poll.index.max.count=20
poll.index.wait.interval=250

rabbit.mq.consume.enabled=false

rabbit.mq.exchange.hostname=
rabbit.mq.exchange.name=
rabbit.mq.exchange.password=
rabbit.mq.exchange.username=

rabbit.mq.publish.enabled=false

rabbit.mq.queue=

rabbit.mq.routing.key.loop.division.add=loop.division.add
rabbit.mq.routing.key.loop.division.delete=loop.division.delete
rabbit.mq.routing.key.loop.division.remove.participant=loop.division.remove_participant
rabbit.mq.routing.key.loop.division.set.child=loop.division.set_child
rabbit.mq.routing.key.loop.division.set.parent=loop.division.set_parent
rabbit.mq.routing.key.loop.division.set.participant=loop.division.set_participant
rabbit.mq.routing.key.loop.division.update=loop.division.update

rabbit.mq.sync.loop.person.birthday_enabled=false

resource.actions.configs=resource-actions/default.xml