/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.lcs.client.event;

/**
 * @author Igor Beslic
 */
public enum LCSEvent {

	HANDSHAKE_FAILED, HANDSHAKE_SUCCESS, LCS_CLUSTER_ENTRY_TOKEN_CHECK_FAILED,
	LCS_CLUSTER_ENTRY_TOKEN_CHECK_SUCCESS,
	LCS_CLUSTER_ENTRY_TOKEN_CHECK_TOKEN_CORRUPTED,
	LCS_CLUSTER_ENTRY_TOKEN_ENVIRONMENT_MISMATCH,
	LCS_CLUSTER_ENTRY_TOKEN_INVALID,
	LCS_CLUSTER_ENTRY_TOKEN_INVALID_USER_CREDENTIALS,
	LCS_CLUSTER_ENTRY_TOKEN_INVALIDATED, LCS_CLUSTER_ENTRY_TOKEN_MISSING,
	LCS_CLUSTER_ENTRY_TOKEN_MULTIPLE_TOKENS, LCS_CLUSTER_NODE_UNREGISTERED,
	LCS_GATEWAY_UNAVAILABLE, SIGN_OFF_FAILED, SIGN_OFF_SUCCESS

}