include-and-override=portlet-ext.properties

file.repository.host[server-1]=http://127.0.0.1:8080
file.repository.host[server-2]=http://127.0.0.1:8081
file.repository.ids=server-1,server-2
file.repository.name[server-1]=server-west
file.repository.name[server-2]=server-east
file.repository.support.region.ids[server-1]=
file.repository.support.region.ids[server-2]=