include-and-override=portlet-ext.properties

file.repository.host[us-1]=https://lesa-files-uat.us.liferay.com/
file.repository.host[hu-1]=https://lesa-files-uat.hu.liferay.com/
file.repository.ids=us-1,hu-1
file.repository.name[us-1]=united-states
file.repository.name[hu-1]=hungary
file.repository.support.regions[us-1]=Australia,Brazil,China,India,Japan,United States
file.repository.support.regions[hu-1]=Hungary,Spain