include-and-override=portlet-ext.properties

file.repository.access.organization.names[br-1]=Data Access EU
file.repository.access.organization.names[hu-1]=Data Access EU
file.repository.access.organization.names[jp-1]=Data Access EU
file.repository.access.organization.names[us-1]=Data Access US
file.repository.data.regions[br-1]=Brazil
file.repository.data.regions[hu-1]=Hungary
file.repository.data.regions[jp-1]=Japan
file.repository.data.regions[us-1]=United States
file.repository.default.id=us-1
file.repository.host[br-1]=https://lesa-files-uat.br.liferay.com/
file.repository.host[hu-1]=https://lesa-files-uat.hu.liferay.com/
file.repository.host[jp-1]=https://lesa-files-uat.jp.liferay.com/
file.repository.host[us-1]=https://lesa-files-uat.us.liferay.com/
file.repository.ids=br-1,hu-1,jp-1,us-1
file.repository.name[br-1]=Brazil
file.repository.name[hu-1]=Hungary
file.repository.name[jp-1]=Japan
file.repository.name[us-1]=United States