/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.zendesk.documentation.sync.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskSection;
import com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskSectionModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ZendeskSection service. Represents a row in the &quot;OSBCustomer_ZendeskSection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ZendeskSectionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ZendeskSectionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ZendeskSectionImpl
 * @see ZendeskSection
 * @see ZendeskSectionModel
 * @generated
 */
@ProviderType
public class ZendeskSectionModelImpl extends BaseModelImpl<ZendeskSection>
	implements ZendeskSectionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a zendesk section model instance should use the {@link ZendeskSection} interface instead.
	 */
	public static final String TABLE_NAME = "OSBCustomer_ZendeskSection";
	public static final Object[][] TABLE_COLUMNS = {
			{ "zendeskSectionId", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "zendeskCategoryId", Types.BIGINT },
			{ "documentationKey", Types.VARCHAR },
			{ "remoteId", Types.BIGINT },
			{ "remoteHtmlURL", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("zendeskSectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("zendeskCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("documentationKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("remoteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("remoteHtmlURL", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OSBCustomer_ZendeskSection (zendeskSectionId LONG not null primary key,modifiedDate DATE null,zendeskCategoryId LONG,documentationKey VARCHAR(150) null,remoteId LONG,remoteHtmlURL VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OSBCustomer_ZendeskSection";
	public static final String ORDER_BY_JPQL = " ORDER BY zendeskSection.zendeskSectionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSBCustomer_ZendeskSection.zendeskSectionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskSection"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskSection"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskSection"),
			true);
	public static final long DOCUMENTATIONKEY_COLUMN_BITMASK = 1L;
	public static final long ZENDESKCATEGORYID_COLUMN_BITMASK = 2L;
	public static final long ZENDESKSECTIONID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.customer.zendesk.documentation.sync.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskSection"));

	public ZendeskSectionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _zendeskSectionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setZendeskSectionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _zendeskSectionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ZendeskSection.class;
	}

	@Override
	public String getModelClassName() {
		return ZendeskSection.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("zendeskSectionId", getZendeskSectionId());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("zendeskCategoryId", getZendeskCategoryId());
		attributes.put("documentationKey", getDocumentationKey());
		attributes.put("remoteId", getRemoteId());
		attributes.put("remoteHtmlURL", getRemoteHtmlURL());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long zendeskSectionId = (Long)attributes.get("zendeskSectionId");

		if (zendeskSectionId != null) {
			setZendeskSectionId(zendeskSectionId);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long zendeskCategoryId = (Long)attributes.get("zendeskCategoryId");

		if (zendeskCategoryId != null) {
			setZendeskCategoryId(zendeskCategoryId);
		}

		String documentationKey = (String)attributes.get("documentationKey");

		if (documentationKey != null) {
			setDocumentationKey(documentationKey);
		}

		Long remoteId = (Long)attributes.get("remoteId");

		if (remoteId != null) {
			setRemoteId(remoteId);
		}

		String remoteHtmlURL = (String)attributes.get("remoteHtmlURL");

		if (remoteHtmlURL != null) {
			setRemoteHtmlURL(remoteHtmlURL);
		}
	}

	@Override
	public long getZendeskSectionId() {
		return _zendeskSectionId;
	}

	@Override
	public void setZendeskSectionId(long zendeskSectionId) {
		_zendeskSectionId = zendeskSectionId;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getZendeskCategoryId() {
		return _zendeskCategoryId;
	}

	@Override
	public void setZendeskCategoryId(long zendeskCategoryId) {
		_columnBitmask |= ZENDESKCATEGORYID_COLUMN_BITMASK;

		if (!_setOriginalZendeskCategoryId) {
			_setOriginalZendeskCategoryId = true;

			_originalZendeskCategoryId = _zendeskCategoryId;
		}

		_zendeskCategoryId = zendeskCategoryId;
	}

	public long getOriginalZendeskCategoryId() {
		return _originalZendeskCategoryId;
	}

	@Override
	public String getDocumentationKey() {
		if (_documentationKey == null) {
			return "";
		}
		else {
			return _documentationKey;
		}
	}

	@Override
	public void setDocumentationKey(String documentationKey) {
		_columnBitmask |= DOCUMENTATIONKEY_COLUMN_BITMASK;

		if (_originalDocumentationKey == null) {
			_originalDocumentationKey = _documentationKey;
		}

		_documentationKey = documentationKey;
	}

	public String getOriginalDocumentationKey() {
		return GetterUtil.getString(_originalDocumentationKey);
	}

	@Override
	public long getRemoteId() {
		return _remoteId;
	}

	@Override
	public void setRemoteId(long remoteId) {
		_remoteId = remoteId;
	}

	@Override
	public String getRemoteHtmlURL() {
		if (_remoteHtmlURL == null) {
			return "";
		}
		else {
			return _remoteHtmlURL;
		}
	}

	@Override
	public void setRemoteHtmlURL(String remoteHtmlURL) {
		_remoteHtmlURL = remoteHtmlURL;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ZendeskSection.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ZendeskSection toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ZendeskSection)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ZendeskSectionImpl zendeskSectionImpl = new ZendeskSectionImpl();

		zendeskSectionImpl.setZendeskSectionId(getZendeskSectionId());
		zendeskSectionImpl.setModifiedDate(getModifiedDate());
		zendeskSectionImpl.setZendeskCategoryId(getZendeskCategoryId());
		zendeskSectionImpl.setDocumentationKey(getDocumentationKey());
		zendeskSectionImpl.setRemoteId(getRemoteId());
		zendeskSectionImpl.setRemoteHtmlURL(getRemoteHtmlURL());

		zendeskSectionImpl.resetOriginalValues();

		return zendeskSectionImpl;
	}

	@Override
	public int compareTo(ZendeskSection zendeskSection) {
		long primaryKey = zendeskSection.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ZendeskSection)) {
			return false;
		}

		ZendeskSection zendeskSection = (ZendeskSection)obj;

		long primaryKey = zendeskSection.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ZendeskSectionModelImpl zendeskSectionModelImpl = this;

		zendeskSectionModelImpl._originalZendeskCategoryId = zendeskSectionModelImpl._zendeskCategoryId;

		zendeskSectionModelImpl._setOriginalZendeskCategoryId = false;

		zendeskSectionModelImpl._originalDocumentationKey = zendeskSectionModelImpl._documentationKey;

		zendeskSectionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ZendeskSection> toCacheModel() {
		ZendeskSectionCacheModel zendeskSectionCacheModel = new ZendeskSectionCacheModel();

		zendeskSectionCacheModel.zendeskSectionId = getZendeskSectionId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			zendeskSectionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			zendeskSectionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		zendeskSectionCacheModel.zendeskCategoryId = getZendeskCategoryId();

		zendeskSectionCacheModel.documentationKey = getDocumentationKey();

		String documentationKey = zendeskSectionCacheModel.documentationKey;

		if ((documentationKey != null) && (documentationKey.length() == 0)) {
			zendeskSectionCacheModel.documentationKey = null;
		}

		zendeskSectionCacheModel.remoteId = getRemoteId();

		zendeskSectionCacheModel.remoteHtmlURL = getRemoteHtmlURL();

		String remoteHtmlURL = zendeskSectionCacheModel.remoteHtmlURL;

		if ((remoteHtmlURL != null) && (remoteHtmlURL.length() == 0)) {
			zendeskSectionCacheModel.remoteHtmlURL = null;
		}

		return zendeskSectionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{zendeskSectionId=");
		sb.append(getZendeskSectionId());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", zendeskCategoryId=");
		sb.append(getZendeskCategoryId());
		sb.append(", documentationKey=");
		sb.append(getDocumentationKey());
		sb.append(", remoteId=");
		sb.append(getRemoteId());
		sb.append(", remoteHtmlURL=");
		sb.append(getRemoteHtmlURL());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.osb.customer.zendesk.documentation.sync.model.ZendeskSection");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>zendeskSectionId</column-name><column-value><![CDATA[");
		sb.append(getZendeskSectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zendeskCategoryId</column-name><column-value><![CDATA[");
		sb.append(getZendeskCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentationKey</column-name><column-value><![CDATA[");
		sb.append(getDocumentationKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteId</column-name><column-value><![CDATA[");
		sb.append(getRemoteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remoteHtmlURL</column-name><column-value><![CDATA[");
		sb.append(getRemoteHtmlURL());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ZendeskSection.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ZendeskSection.class, ModelWrapper.class
		};
	private long _zendeskSectionId;
	private Date _modifiedDate;
	private long _zendeskCategoryId;
	private long _originalZendeskCategoryId;
	private boolean _setOriginalZendeskCategoryId;
	private String _documentationKey;
	private String _originalDocumentationKey;
	private long _remoteId;
	private String _remoteHtmlURL;
	private long _columnBitmask;
	private ZendeskSection _escapedModel;
}