ALTER TABLE ChannelDataSource ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE DataSource ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE DataSourceOrganization ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceSite ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceUserGroup ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE Event ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel;
ALTER TABLE Event ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;

ALTER TABLE EventAttribute ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventAttribute ADD CONSTRAINT EVENTID_FKEY FOREIGN KEY (eventId) REFERENCES Event ON DELETE CASCADE;

ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;

ALTER TABLE Job ADD CONSTRAINT ASAHTASKID_FKEY FOREIGN KEY (asahTaskId) REFERENCES AsahTask;

ALTER TABLE JobParameter ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;

ALTER TABLE JobRun ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;