ALTER TABLE Event ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;

ALTER TABLE EventAttribute ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventAttribute ADD CONSTRAINT EVENTID_FKEY FOREIGN KEY (eventId) REFERENCES Event ON DELETE CASCADE;

ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;