ALTER TABLE Account ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE Asset ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE AssetKeyword ADD CONSTRAINT ASSETID_FKEY FOREIGN KEY (assetId) REFERENCES Asset ON DELETE CASCADE;

ALTER TABLE BlockedEventDefinition ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition ON DELETE CASCADE;

ALTER TABLE ChannelDataSource ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE CSVIndividual ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceFieldMapping ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource;
ALTER TABLE DataSourceFieldMapping ADD CONSTRAINT FIELDMAPPINGID_FKEY FOREIGN KEY (fieldMappingId) REFERENCES FieldMapping ON DELETE CASCADE;

ALTER TABLE DataSourceOrganization ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceSite ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceUserGroup ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DXPEntity ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE Event ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel;
ALTER TABLE Event ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;

ALTER TABLE EventAttribute ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventAttribute ADD CONSTRAINT EVENTID_FKEY FOREIGN KEY (eventId) REFERENCES Event ON DELETE CASCADE;

ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;

ALTER TABLE ExperimentMetric ADD CONSTRAINT EXPERIMENTID_FKEY FOREIGN KEY (experimentId) REFERENCES Experiment ON DELETE CASCADE;

ALTER TABLE ExperimentVariant ADD CONSTRAINT EXPERIMENTID_FKEY FOREIGN KEY (experimentId) REFERENCES Experiment ON DELETE CASCADE;

ALTER TABLE ExperimentVariantMetric ADD CONSTRAINT EXPERIMENTMETRICID_FKEY FOREIGN KEY (experimentMetricId) REFERENCES ExperimentMetric ON DELETE CASCADE;

ALTER TABLE Job ADD CONSTRAINT ASAHTASKID_FKEY FOREIGN KEY (asahTaskId) REFERENCES AsahTask;

ALTER TABLE JobParameter ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;

ALTER TABLE JobRun ADD CONSTRAINT JOBID_FKEY FOREIGN KEY (jobId) REFERENCES Job;

ALTER TABLE Membership ADD CONSTRAINT SEGMENTID_FKEY FOREIGN KEY (individualSegmentId) REFERENCES Segment ON DELETE CASCADE;

ALTER TABLE MembershipChange ADD CONSTRAINT SEGMENTID_FKEY FOREIGN KEY (individualSegmentId) REFERENCES Segment ON DELETE CASCADE;

ALTER TABLE Organization ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE RunLog ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE SalesforceEntity ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE Segment ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel;