ALTER TABLE ChannelDataSource ADD CONSTRAINT CHANNELID_FKEY FOREIGN KEY (channelId) REFERENCES Channel ON DELETE CASCADE;

ALTER TABLE DataSourceOrganization ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceSite ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE DataSourceUserGroup ADD CONSTRAINT DATASOURCEID_FKEY FOREIGN KEY (dataSourceId) REFERENCES DataSource ON DELETE CASCADE;

ALTER TABLE Event ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;

ALTER TABLE EventAnalysis ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;

ALTER TABLE EventAttribute ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventAttribute ADD CONSTRAINT EVENTID_FKEY FOREIGN KEY (eventId) REFERENCES Event ON DELETE CASCADE;

ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTATTRIBUTEDEFINITIONID_FKEY FOREIGN KEY (eventAttributeDefinitionId) REFERENCES EventAttributeDefinition;
ALTER TABLE EventDefinitionEventAttributeDefinition ADD CONSTRAINT EVENTDEFINITIONID_FKEY FOREIGN KEY (eventDefinitionId) REFERENCES EventDefinition;