INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'articleId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'assetId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'category') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'className') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'classPK') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'commentId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('number', 'depth') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'elementId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'entryId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'fieldName') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'fileEntryId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'fileEntryUUID') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('duration', 'focusDuration') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'formId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'groupId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'href') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('number', 'numberOfWords') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'page') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('duration', 'pageLoadTime') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('boolean', 'preview') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'ratingType') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('number', 'score') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'sessionId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'src') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'tagName') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'text') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'title') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'type') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('string', 'version') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(dataType, name) VALUES('duration', 'viewDuration') ON CONFLICT DO NOTHING;

INSERT INTO EventDefinition(name, type) VALUES('assetClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetDownloaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetDepthReached', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetSubmitted', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('blogClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('blogDepthReached', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('blogViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('ctaClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('documentDownloaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('documentPreviewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('fieldBlurred', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('fieldFocused', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('formSubmitted', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('formViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageDepthReached', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageLoaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageUnloaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('posted', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('shared', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('vote', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('webContentClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('webContentViewed', 'default') ON CONFLICT DO NOTHING;

INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='articleId'), (SELECT id from EventDefinition WHERE name='webContentClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='assetId'), (SELECT id from EventDefinition WHERE name='assetClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='assetId'), (SELECT id from EventDefinition WHERE name='assetDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='assetId'), (SELECT id from EventDefinition WHERE name='assetDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='assetId'), (SELECT id from EventDefinition WHERE name='assetSubmitted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='assetId'), (SELECT id from EventDefinition WHERE name='assetViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='category'), (SELECT id from EventDefinition WHERE name='assetClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='category'), (SELECT id from EventDefinition WHERE name='assetDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='category'), (SELECT id from EventDefinition WHERE name='assetDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='category'), (SELECT id from EventDefinition WHERE name='assetSubmitted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='category'), (SELECT id from EventDefinition WHERE name='assetViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='className'), (SELECT id from EventDefinition WHERE name='posted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='className'), (SELECT id from EventDefinition WHERE name='vote')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='className'), (SELECT id from EventDefinition WHERE name='shared')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='classPK'), (SELECT id from EventDefinition WHERE name='posted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='classPK'), (SELECT id from EventDefinition WHERE name='vote')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='classPK'), (SELECT id from EventDefinition WHERE name='shared')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='commentId'), (SELECT id from EventDefinition WHERE name='posted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='depth'), (SELECT id from EventDefinition WHERE name='blogDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='depth'), (SELECT id from EventDefinition WHERE name='assetDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='depth'), (SELECT id from EventDefinition WHERE name='pageDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='elementId'), (SELECT id from EventDefinition WHERE name='ctaClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='entryId'), (SELECT id from EventDefinition WHERE name='blogClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='entryId'), (SELECT id from EventDefinition WHERE name='blogDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='entryId'), (SELECT id from EventDefinition WHERE name='blogViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='fieldName'), (SELECT id from EventDefinition WHERE name='fieldBlurred')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='fieldName'), (SELECT id from EventDefinition WHERE name='fieldFocused')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='fileEntryId'), (SELECT id from EventDefinition WHERE name='documentDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='fileEntryId'), (SELECT id from EventDefinition WHERE name='documentPreviewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='fileEntryUUID'), (SELECT id from EventDefinition WHERE name='documentPreviewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='focusDuration'), (SELECT id from EventDefinition WHERE name='fieldBlurred')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='formId'), (SELECT id from EventDefinition WHERE name='fieldBlurred')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='formId'), (SELECT id from EventDefinition WHERE name='fieldFocused')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='formId'), (SELECT id from EventDefinition WHERE name='formSubmitted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='formId'), (SELECT id from EventDefinition WHERE name='formViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='formId'), (SELECT id from EventDefinition WHERE name='pageViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='groupId'), (SELECT id from EventDefinition WHERE name='documentDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='groupId'), (SELECT id from EventDefinition WHERE name='documentPreviewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='href'), (SELECT id from EventDefinition WHERE name='blogClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='href'), (SELECT id from EventDefinition WHERE name='assetClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='href'), (SELECT id from EventDefinition WHERE name='webContentClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='numberOfWords'), (SELECT id from EventDefinition WHERE name='blogViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='numberOfWords'), (SELECT id from EventDefinition WHERE name='webContentViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='page'), (SELECT id from EventDefinition WHERE name='fieldBlurred')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='page'), (SELECT id from EventDefinition WHERE name='fieldFocused')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='page'), (SELECT id from EventDefinition WHERE name='pageViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='pageLoadTime'), (SELECT id from EventDefinition WHERE name='pageLoaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='preview'), (SELECT id from EventDefinition WHERE name='documentDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='ratingType'), (SELECT id from EventDefinition WHERE name='vote')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='score'), (SELECT id from EventDefinition WHERE name='vote')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='sessionId'), (SELECT id from EventDefinition WHERE name='blogDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='sessionId'), (SELECT id from EventDefinition WHERE name='assetDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='src'), (SELECT id from EventDefinition WHERE name='blogClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='src'), (SELECT id from EventDefinition WHERE name='assetClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='src'), (SELECT id from EventDefinition WHERE name='webContentClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='tagName'), (SELECT id from EventDefinition WHERE name='blogClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='tagName'), (SELECT id from EventDefinition WHERE name='assetClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='tagName'), (SELECT id from EventDefinition WHERE name='webContentClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='text'), (SELECT id from EventDefinition WHERE name='blogClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='text'), (SELECT id from EventDefinition WHERE name='assetClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='text'), (SELECT id from EventDefinition WHERE name='posted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='text'), (SELECT id from EventDefinition WHERE name='webContentClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='blogClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='blogDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='blogViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='assetClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='assetDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='assetDepthReached')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='assetSubmitted')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='assetViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='documentDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='documentPreviewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='formViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='pageViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='webContentClicked')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='title'), (SELECT id from EventDefinition WHERE name='webContentViewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='type'), (SELECT id from EventDefinition WHERE name='shared')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='version'), (SELECT id from EventDefinition WHERE name='documentDownloaded')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='version'), (SELECT id from EventDefinition WHERE name='documentPreviewed')) ON CONFLICT DO NOTHING;
INSERT INTO EventDefinitionEventAttributeDefinition(eventAttributeDefinitionId, eventDefinitionId) VALUES((SELECT id from EventAttributeDefinition WHERE name='viewDuration'), (SELECT id from EventDefinition WHERE name='pageUnloaded')) ON CONFLICT DO NOTHING;