INSERT INTO EventDefinition(name, type) VALUES('assetClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetDownloaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetDepthReached', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetSubmitted', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('assetViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('blogClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('blogDepthReached', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('blogViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('ctaClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('documentDownloaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('documentPreviewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('fieldBlurred', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('fieldFocused', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('formSubmitted', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('formViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageDepthReached', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageViewed', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageLoaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('pageUnloaded', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('posted', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('shared', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('vote', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('webContentClicked', 'default') ON CONFLICT DO NOTHING;
INSERT INTO EventDefinition(name, type) VALUES('webContentViewed', 'default') ON CONFLICT DO NOTHING;

INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'articleId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'assetId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'category') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'className') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'classPK') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'commentId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'number', 'depth') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'elementId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'entryId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'fieldName') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'fileEntryId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'fileEntryUUID') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'duration', 'focusDuration') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'formId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'groupId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'href') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'number', 'numberOfWords') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'page') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'duration', 'pageLoadTime') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'ratingType') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'number', 'score') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'sessionId') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'src') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'title') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'tagName') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'text') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'preview') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'title') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'type') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'string', 'version') ON CONFLICT DO NOTHING;
INSERT INTO EventAttributeDefinition(eventDefinitionIds, dataType, name) VALUES('{}', 'duration', 'viewDuration') ON CONFLICT DO NOTHING;