ESAPI.Logger=org.owasp.esapi.logging.java.JavaLogFactory

Logger.ApplicationName=AnalyticsCloud
Logger.ClientInfo=false
Logger.LogApplicationName=false
Logger.LogEncodingRequired=false
Logger.LogFileName=ESAPI_log
Logger.LogServerIP=false
Logger.MaxLogFileSize=10000000
Logger.UserInfo=false