CREATE SCHEMA IF NOT EXISTS hive.default;

USE hive.default;

CREATE TABLE IF NOT EXISTS Blog (
	assetId VARCHAR,
	assetPrimaryKey VARCHAR,
	browserName VARCHAR,
	canonicalUrl VARCHAR,
	channelId BIGINT,
	city VARCHAR,
	clicks BIGINT,
	comments BIGINT,
	country VARCHAR,
	dataSourceId BIGINT,
	deviceType VARCHAR,
	eventDate TIMESTAMP,
	individualId BIGINT,
	knownIndividual BOOLEAN,
	platformName VARCHAR,
	projectId VARCHAR,
	ratings BIGINT,
	ratingsScore REAL,
	readPercentile BIGINT,
	readTime BIGINT,
	region VARCHAR,
	sessionId VARCHAR,
	title VARCHAR,
	userId VARCHAR,
	variantId VARCHAR,
	views BIGINT
);

CREATE TABLE IF NOT EXISTS CustomAsset (
	abandonments BIGINT,
	assetId VARCHAR,
	assetPrimaryKey VARCHAR,
	category VARCHAR,
	channelId BIGINT,
	clicks BIGINT,
	downloads BIGINT,
	eventDate TIMESTAMP,
	projectId VARCHAR,
	readTime BIGINT,
	submissionTime BIGINT,
	submissions BIGINT,
	userId VARCHAR,
	variantId VARCHAR,
	views BIGINT
);

CREATE TABLE IF NOT EXISTS DocumentLibrary (
	assetId VARCHAR,
	assetPrimaryKey VARCHAR,
	browserName VARCHAR,
	canonicalUrl VARCHAR,
	channelId BIGINT,
	city VARCHAR,
	comments BIGINT,
	country VARCHAR,
	dataSourceId BIGINT,
	deviceType VARCHAR,
	downloads BIGINT,
	eventDate TIMESTAMP,
	individualId BIGINT,
	knownIndividual BOOLEAN,
	platformName VARCHAR,
	previews BIGINT,
	projectId VARCHAR,
	ratings BIGINT,
	ratingsScore REAL,
	region VARCHAR,
	sessionId VARCHAR,
	title VARCHAR,
	userId VARCHAR,
	variantId VARCHAR
);

CREATE TABLE IF NOT EXISTS Journal (
	assetId VARCHAR,
	assetPrimaryKey VARCHAR,
	browserName VARCHAR,
	canonicalUrl VARCHAR,
	channelId BIGINT,
	city VARCHAR,
	clicks BIGINT,
	country VARCHAR,
	dataSourceId BIGINT,
	deviceType VARCHAR,
	eventDate TIMESTAMP,
	individualId BIGINT,
	knownIndividual BOOLEAN,
	platformName VARCHAR,
	projectId VARCHAR,
	region VARCHAR,
	sessionId VARCHAR,
	title VARCHAR,
	userId VARCHAR,
	variantId VARCHAR,
	views BIGINT
);