CREATE INDEX IF NOT EXISTS IX_EVENT_CIEDEDI ON Event (channelId, eventDate, eventDefinitionId);

CREATE INDEX IF NOT EXISTS IX_EVENT_CIEDEDII ON Event (channelId, eventDate, eventDefinitionId, id);

CREATE INDEX IF NOT EXISTS IX_EVENT_CIEDII ON Event (channelId, eventDate, individualId);

CREATE INDEX IF NOT EXISTS IX_EVENT_EVENTDATE ON Event (eventDate);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTE_NAME ON EventAttribute (eventId);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTEDEFINITION_NAME ON EventAttributeDefinition (name);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_HI ON EventDefinition (hidden, id);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_HIDDEN ON EventDefinition (hidden);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_NAME ON EventDefinition (name);

CREATE UNIQUE INDEX IF NOT EXISTS IX_ACTIVITYGROUP_ATCIDSIDDUI ON ActivityGroup (activityType, channelId, dataSourceId, dayDate, userId);

CREATE UNIQUE INDEX IF NOT EXISTS IX_EVENTATTRIBUTE_EADIEDEI ON EventAttribute (eventAttributeDefinitionId, eventDate, eventId);

CREATE UNIQUE INDEX IF NOT EXISTS IX_MEMBERSHIP_IIDISIDS ON Membership (individualId, individualSegmentId, status);

CREATE INDEX IF NOT EXISTS IX_MEMBERSHIPCHANGE_INDIVIDUALSEGMENTID ON MembershipChange (individualSegmentId);

CREATE INDEX IF NOT EXISTS IX_MEMBERSHIPCHANGE_ISIICMD ON MembershipChange (individualsegmentid, individualscount, modifieddate);

