CREATE INDEX IF NOT EXISTS IX_EVENT_CIEDEDI ON Event (channelId, eventDate, eventDefinitionId);

CREATE INDEX IF NOT EXISTS IX_EVENT_CIEDII ON Event (channelId, eventDate, individualId);

CREATE INDEX IF NOT EXISTS IX_EVENT_EVENTDATE ON Event (eventDate);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTE_EADIED ON EventAttribute (eventattributeDefinitionId, eventDate);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTE_EADIEI ON EventAttribute (eventAttributeDefinitionId, eventId);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTE_EVENTID ON EventAttribute (eventId);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTEDEFINITION_NAME ON EventAttributeDefinition (name);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_NAME ON EventDefinition (name);

CREATE UNIQUE INDEX IF NOT EXISTS IX_EVENTATTRIBUTE_EADIEDEI ON EventAttribute (eventAttributeDefinitionId, eventDate, eventId);