CREATE INDEX IF NOT EXISTS IX_EVENT_EVENTDATE ON Event (eventDate);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTEDEFINITION_NAME ON EventAttributeDefinition (name);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_HIDDEN ON EventDefinition (hidden);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_NAME ON EventDefinition (name);