CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_NAME ON EventDefinition (name);

CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTEDEFINITION_NAME ON EventAttributeDefinition (name);

CREATE UNIQUE INDEX IF NOT EXISTS IX_ACTIVITYGROUP_ATCIDSIDDUI ON ActivityGroup (activityType, channelId, dataSourceId, dayDate, userId);