CREATE INDEX IF NOT EXISTS IX_EVENTATTRIBUTEDEFINITION_NAME ON EventAttributeDefinition (name);

CREATE INDEX IF NOT EXISTS IX_EVENTDEFINITION_NAME ON EventDefinition (name);

CREATE INDEX IF NOT EXISTS IX_INTEREST_OIOT ON Interest (ownerId, ownerType);

CREATE INDEX IF NOT EXISTS IX_MEMBERSHIPCHANGE_ISIMD ON MembershipChange (individualsegmentid, modifieddate);

CREATE UNIQUE INDEX IF NOT EXISTS IX_ACTIVITYGROUP_ATCIDSIDDUI ON ActivityGroup (activityType, channelId, dataSourceId, dayDate, userId);

CREATE UNIQUE INDEX IF NOT EXISTS IX_EVENTANALYSIS_CIN ON EventAnalysis (channelId, name);

CREATE UNIQUE INDEX IF NOT EXISTS IX_INTEREST_NOIOTRD ON Interest (name, ownerId, ownerType, recordedDate);

CREATE UNIQUE INDEX IF NOT EXISTS IX_MEMBERSHIP_IIDISIDS ON Membership (individualId, individualSegmentId, status);