/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.pulpo.connector.de.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ConnectorTransaction service. Represents a row in the &quot;PULPO_ConnectorTransaction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.pulpo.connector.de.model.impl.ConnectorTransactionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.pulpo.connector.de.model.impl.ConnectorTransactionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConnectorTransaction
 * @see com.liferay.pulpo.connector.de.model.impl.ConnectorTransactionImpl
 * @see com.liferay.pulpo.connector.de.model.impl.ConnectorTransactionModelImpl
 * @generated
 */
@ProviderType
public interface ConnectorTransactionModel extends AttachedModel,
	BaseModel<ConnectorTransaction>, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a connector transaction model instance should use the {@link ConnectorTransaction} interface instead.
	 */

	/**
	 * Returns the primary key of this connector transaction.
	 *
	 * @return the primary key of this connector transaction
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this connector transaction.
	 *
	 * @param primaryKey the primary key of this connector transaction
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this connector transaction.
	 *
	 * @return the uuid of this connector transaction
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this connector transaction.
	 *
	 * @param uuid the uuid of this connector transaction
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the connector transaction ID of this connector transaction.
	 *
	 * @return the connector transaction ID of this connector transaction
	 */
	public long getConnectorTransactionId();

	/**
	 * Sets the connector transaction ID of this connector transaction.
	 *
	 * @param connectorTransactionId the connector transaction ID of this connector transaction
	 */
	public void setConnectorTransactionId(long connectorTransactionId);

	/**
	 * Returns the company ID of this connector transaction.
	 *
	 * @return the company ID of this connector transaction
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this connector transaction.
	 *
	 * @param companyId the company ID of this connector transaction
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this connector transaction.
	 *
	 * @return the user ID of this connector transaction
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this connector transaction.
	 *
	 * @param userId the user ID of this connector transaction
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this connector transaction.
	 *
	 * @return the user uuid of this connector transaction
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this connector transaction.
	 *
	 * @param userUuid the user uuid of this connector transaction
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this connector transaction.
	 *
	 * @return the user name of this connector transaction
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this connector transaction.
	 *
	 * @param userName the user name of this connector transaction
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this connector transaction.
	 *
	 * @return the create date of this connector transaction
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this connector transaction.
	 *
	 * @param createDate the create date of this connector transaction
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this connector transaction.
	 *
	 * @return the modified date of this connector transaction
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this connector transaction.
	 *
	 * @param modifiedDate the modified date of this connector transaction
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this connector transaction.
	 *
	 * @return the fully qualified class name of this connector transaction
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this connector transaction.
	 *
	 * @return the class name ID of this connector transaction
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this connector transaction.
	 *
	 * @param classNameId the class name ID of this connector transaction
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this connector transaction.
	 *
	 * @return the class pk of this connector transaction
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this connector transaction.
	 *
	 * @param classPK the class pk of this connector transaction
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the operation of this connector transaction.
	 *
	 * @return the operation of this connector transaction
	 */
	@AutoEscape
	public String getOperation();

	/**
	 * Sets the operation of this connector transaction.
	 *
	 * @param operation the operation of this connector transaction
	 */
	public void setOperation(String operation);

	/**
	 * Returns the status of this connector transaction.
	 *
	 * @return the status of this connector transaction
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this connector transaction.
	 *
	 * @param status the status of this connector transaction
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ConnectorTransaction connectorTransaction);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ConnectorTransaction> toCacheModel();

	@Override
	public ConnectorTransaction toEscapedModel();

	@Override
	public ConnectorTransaction toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}