endpoints.enabled=false
endpoints.health.enabled=true
endpoints.prometheus.enabled=true
management.security.enabled=false
osb.asah.backend.admin.rest.controller.enabled=false
osb.asah.data.dog.query.response.threshold=10000
osb.asah.security.enabled=true
osb.asah.security.token=9ZPgFSdEntvRPjgRcstSgkUCBzKyjz4hbuaGbdW9h3BHcJbZLuuSqd6BpFLhRErS