/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.release.tool.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ModuleVersion service. Represents a row in the &quot;OSBCustomer_ModuleVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.customer.release.tool.model.impl.ModuleVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.customer.release.tool.model.impl.ModuleVersionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ModuleVersion
 * @generated
 */
@ProviderType
public interface ModuleVersionModel extends BaseModel<ModuleVersion> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a module version model instance should use the {@link ModuleVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this module version.
	 *
	 * @return the primary key of this module version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this module version.
	 *
	 * @param primaryKey the primary key of this module version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the module version ID of this module version.
	 *
	 * @return the module version ID of this module version
	 */
	public long getModuleVersionId();

	/**
	 * Sets the module version ID of this module version.
	 *
	 * @param moduleVersionId the module version ID of this module version
	 */
	public void setModuleVersionId(long moduleVersionId);

	/**
	 * Returns the release asset category ID of this module version.
	 *
	 * @return the release asset category ID of this module version
	 */
	public long getReleaseAssetCategoryId();

	/**
	 * Sets the release asset category ID of this module version.
	 *
	 * @param releaseAssetCategoryId the release asset category ID of this module version
	 */
	public void setReleaseAssetCategoryId(long releaseAssetCategoryId);

	/**
	 * Returns the group of this module version.
	 *
	 * @return the group of this module version
	 */
	@AutoEscape
	public String getGroup();

	/**
	 * Sets the group of this module version.
	 *
	 * @param group the group of this module version
	 */
	public void setGroup(String group);

	/**
	 * Returns the name of this module version.
	 *
	 * @return the name of this module version
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this module version.
	 *
	 * @param name the name of this module version
	 */
	public void setName(String name);

	/**
	 * Returns the version of this module version.
	 *
	 * @return the version of this module version
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this module version.
	 *
	 * @param version the version of this module version
	 */
	public void setVersion(String version);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ModuleVersion moduleVersion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ModuleVersion> toCacheModel();

	@Override
	public ModuleVersion toEscapedModel();

	@Override
	public ModuleVersion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}