cerebro.data.dog.query.response.threshold=10000
management.endpoint.health.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.enabled-by-default=false
management.security.enabled=false
osb.asah.security.enabled=true
osb.asah.security.token=9ZPgFSdEntvRPjgRcstSgkUCBzKyjz4hbuaGbdW9h3BHcJbZLuuSqd6BpFLhRErS