INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 1, timestamp '${now}', 'USD', 123, 1, timestamp '${now}', timestamp '${now}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (2, 1, timestamp '${now}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-1d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 1, timestamp '${now-1d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-2d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (4, 1, timestamp '${now-2d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (7, 1, timestamp '${now-3d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 1, 10.0);

INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (10, 2, timestamp '${now-2d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-3d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (17, 2, timestamp '${now-3d}', 'EUR', 123, 1, timestamp '${now}', timestamp '${now-6d}', null, 1, 10.0);

INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (3, 1, timestamp '${now-7d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-7d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (3, 1, timestamp '${now-7d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-8d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (8, 1, timestamp '${now-8d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-9d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 1, timestamp '${now-10d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-11d}', null, 1, 10.0);
INSERT INTO BQOrder (accountId, channelId, createDate, currencyCode, datasourceId, id, modifiedDate, orderDate, orderItems, orderStatus, total) VALUES (1, 1, timestamp '${now-11d}', 'USD', 123, 1, timestamp '${now}', timestamp '${now-14d}', null, 1, 10.0);