#
# Files that are allowed to surpass the 80 column limit.
#
docroot/WEB-INF/src/com/liferay/osb/util/PortletPropsKeys.java
docroot/WEB-INF/src/com/liferay/osb/util/PortletPropsValues.java
docroot/WEB-INF/src/com/liferay/osb/hook/upgrade/v3_0_1/Upgrade_20140522110450821_SalesPartnership.java
docroot/WEB-INF/src/com/liferay/osb/hook/upgrade/v3_1_0/Upgrade_20140926155021193_SalesPartnershipTerritories_SalesPartnershipCountries.java
docroot/WEB-INF/src/com/liferay/osb/hook/upgrade/v3_4_7/Upgrade_20160419113858448_OfferingBundle.java