/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.testray.model.TestrayAssignment;
import com.liferay.osb.testray.model.TestrayAssignmentModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TestrayAssignment service. Represents a row in the &quot;OSB_TestrayAssignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TestrayAssignmentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestrayAssignmentImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayAssignmentImpl
 * @generated
 */
@ProviderType
public class TestrayAssignmentModelImpl
	extends BaseModelImpl<TestrayAssignment> implements TestrayAssignmentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray assignment model instance should use the <code>TestrayAssignment</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TestrayAssignment";

	public static final Object[][] TABLE_COLUMNS = {
		{"testrayAssignmentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"assignedUserId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("testrayAssignmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("assignedUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_TestrayAssignment (testrayAssignmentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,assignedUserId LONG,classNameId LONG,classPK LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table OSB_TestrayAssignment";

	public static final String ORDER_BY_JPQL =
		" ORDER BY testrayAssignment.testrayAssignmentId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_TestrayAssignment.testrayAssignmentId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.testray.model.TestrayAssignment"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.testray.model.TestrayAssignment"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.testray.model.TestrayAssignment"));

	public TestrayAssignmentModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _testrayAssignmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTestrayAssignmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _testrayAssignmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TestrayAssignment.class;
	}

	@Override
	public String getModelClassName() {
		return TestrayAssignment.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TestrayAssignment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TestrayAssignment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayAssignment, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TestrayAssignment)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TestrayAssignment, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TestrayAssignment, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TestrayAssignment)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TestrayAssignment, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TestrayAssignment, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TestrayAssignment, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TestrayAssignment, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TestrayAssignment, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TestrayAssignment, Object>>();
		Map<String, BiConsumer<TestrayAssignment, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TestrayAssignment, ?>>();

		attributeGetterFunctions.put(
			"testrayAssignmentId",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getTestrayAssignmentId();
				}

			});
		attributeSetterBiConsumers.put(
			"testrayAssignmentId",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment,
					Object testrayAssignmentId) {

					testrayAssignment.setTestrayAssignmentId(
						(Long)testrayAssignmentId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object groupId) {

					testrayAssignment.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object companyId) {

					testrayAssignment.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object userId) {

					testrayAssignment.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object userName) {

					testrayAssignment.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object createDate) {

					testrayAssignment.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object modifiedDate) {

					testrayAssignment.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"assignedUserId",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getAssignedUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"assignedUserId",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment,
					Object assignedUserId) {

					testrayAssignment.setAssignedUserId((Long)assignedUserId);
				}

			});
		attributeGetterFunctions.put(
			"classNameId",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getClassNameId();
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object classNameId) {

					testrayAssignment.setClassNameId((Long)classNameId);
				}

			});
		attributeGetterFunctions.put(
			"classPK",
			new Function<TestrayAssignment, Object>() {

				@Override
				public Object apply(TestrayAssignment testrayAssignment) {
					return testrayAssignment.getClassPK();
				}

			});
		attributeSetterBiConsumers.put(
			"classPK",
			new BiConsumer<TestrayAssignment, Object>() {

				@Override
				public void accept(
					TestrayAssignment testrayAssignment, Object classPK) {

					testrayAssignment.setClassPK((Long)classPK);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTestrayAssignmentId() {
		return _testrayAssignmentId;
	}

	@Override
	public void setTestrayAssignmentId(long testrayAssignmentId) {
		_testrayAssignmentId = testrayAssignmentId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAssignedUserId() {
		return _assignedUserId;
	}

	@Override
	public void setAssignedUserId(long assignedUserId) {
		_assignedUserId = assignedUserId;
	}

	@Override
	public String getAssignedUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAssignedUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setAssignedUserUuid(String assignedUserUuid) {
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TestrayAssignment.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TestrayAssignment toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TestrayAssignment)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TestrayAssignmentImpl testrayAssignmentImpl =
			new TestrayAssignmentImpl();

		testrayAssignmentImpl.setTestrayAssignmentId(getTestrayAssignmentId());
		testrayAssignmentImpl.setGroupId(getGroupId());
		testrayAssignmentImpl.setCompanyId(getCompanyId());
		testrayAssignmentImpl.setUserId(getUserId());
		testrayAssignmentImpl.setUserName(getUserName());
		testrayAssignmentImpl.setCreateDate(getCreateDate());
		testrayAssignmentImpl.setModifiedDate(getModifiedDate());
		testrayAssignmentImpl.setAssignedUserId(getAssignedUserId());
		testrayAssignmentImpl.setClassNameId(getClassNameId());
		testrayAssignmentImpl.setClassPK(getClassPK());

		testrayAssignmentImpl.resetOriginalValues();

		return testrayAssignmentImpl;
	}

	@Override
	public int compareTo(TestrayAssignment testrayAssignment) {
		long primaryKey = testrayAssignment.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TestrayAssignment)) {
			return false;
		}

		TestrayAssignment testrayAssignment = (TestrayAssignment)obj;

		long primaryKey = testrayAssignment.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TestrayAssignmentModelImpl testrayAssignmentModelImpl = this;

		testrayAssignmentModelImpl._setModifiedDate = false;
	}

	@Override
	public CacheModel<TestrayAssignment> toCacheModel() {
		TestrayAssignmentCacheModel testrayAssignmentCacheModel =
			new TestrayAssignmentCacheModel();

		testrayAssignmentCacheModel.testrayAssignmentId =
			getTestrayAssignmentId();

		testrayAssignmentCacheModel.groupId = getGroupId();

		testrayAssignmentCacheModel.companyId = getCompanyId();

		testrayAssignmentCacheModel.userId = getUserId();

		testrayAssignmentCacheModel.userName = getUserName();

		String userName = testrayAssignmentCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			testrayAssignmentCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			testrayAssignmentCacheModel.createDate = createDate.getTime();
		}
		else {
			testrayAssignmentCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			testrayAssignmentCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			testrayAssignmentCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		testrayAssignmentCacheModel.assignedUserId = getAssignedUserId();

		testrayAssignmentCacheModel.classNameId = getClassNameId();

		testrayAssignmentCacheModel.classPK = getClassPK();

		return testrayAssignmentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TestrayAssignment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TestrayAssignment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayAssignment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TestrayAssignment)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TestrayAssignment, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TestrayAssignment, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayAssignment, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TestrayAssignment)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		TestrayAssignment.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		TestrayAssignment.class, ModelWrapper.class
	};

	private long _testrayAssignmentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _assignedUserId;
	private long _classNameId;
	private long _classPK;
	private TestrayAssignment _escapedModel;

}