/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.testray.model.TestrayTask;
import com.liferay.osb.testray.model.TestrayTaskModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TestrayTask service. Represents a row in the &quot;OSB_TestrayTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TestrayTaskModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestrayTaskImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayTaskImpl
 * @generated
 */
public class TestrayTaskModelImpl
	extends BaseModelImpl<TestrayTask> implements TestrayTaskModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray task model instance should use the <code>TestrayTask</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TestrayTask";

	public static final Object[][] TABLE_COLUMNS = {
		{"testrayTaskId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"testrayBuildId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"statusUpdateDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("testrayTaskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("testrayBuildId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusUpdateDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_TestrayTask (testrayTaskId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,testrayBuildId LONG,name VARCHAR(150) null,statusUpdateDate DATE null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table OSB_TestrayTask";

	public static final String ORDER_BY_JPQL = " ORDER BY testrayTask.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_TestrayTask.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.testray.model.TestrayTask"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.testray.model.TestrayTask"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final String
		MAPPING_TABLE_OSB_TESTRAYTASKS_TESTRAYCASETYPES_NAME =
			"OSB_TestrayTasks_TestrayCaseTypes";

	public static final Object[][]
		MAPPING_TABLE_OSB_TESTRAYTASKS_TESTRAYCASETYPES_COLUMNS = {
			{"companyId", Types.BIGINT}, {"testrayCaseTypeId", Types.BIGINT},
			{"testrayTaskId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_OSB_TESTRAYTASKS_TESTRAYCASETYPES_SQL_CREATE =
			"create table OSB_TestrayTasks_TestrayCaseTypes (companyId LONG not null,testrayCaseTypeId LONG not null,testrayTaskId LONG not null,primary key (testrayCaseTypeId, testrayTaskId))";

	public static final boolean
		FINDER_CACHE_ENABLED_OSB_TESTRAYTASKS_TESTRAYCASETYPES =
			GetterUtil.getBoolean(
				com.liferay.osb.testray.service.util.ServiceProps.get(
					"value.object.finder.cache.enabled.OSB_TestrayTasks_TestrayCaseTypes"),
				true);

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.testray.model.TestrayTask"));

	public TestrayTaskModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _testrayTaskId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTestrayTaskId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _testrayTaskId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TestrayTask.class;
	}

	@Override
	public String getModelClassName() {
		return TestrayTask.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TestrayTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TestrayTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayTask, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TestrayTask)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TestrayTask, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TestrayTask, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TestrayTask)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TestrayTask, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TestrayTask, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TestrayTask>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TestrayTask.class.getClassLoader(), TestrayTask.class,
			ModelWrapper.class);

		try {
			Constructor<TestrayTask> constructor =
				(Constructor<TestrayTask>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TestrayTask, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TestrayTask, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TestrayTask, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TestrayTask, Object>>();
		Map<String, BiConsumer<TestrayTask, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TestrayTask, ?>>();

		attributeGetterFunctions.put(
			"testrayTaskId",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getTestrayTaskId();
				}

			});
		attributeSetterBiConsumers.put(
			"testrayTaskId",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object testrayTaskIdObject) {

					testrayTask.setTestrayTaskId((Long)testrayTaskIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object groupIdObject) {

					testrayTask.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object companyIdObject) {

					testrayTask.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object userIdObject) {

					testrayTask.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object userNameObject) {

					testrayTask.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object createDateObject) {

					testrayTask.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object modifiedDateObject) {

					testrayTask.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"testrayBuildId",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getTestrayBuildId();
				}

			});
		attributeSetterBiConsumers.put(
			"testrayBuildId",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object testrayBuildIdObject) {

					testrayTask.setTestrayBuildId((Long)testrayBuildIdObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(TestrayTask testrayTask, Object nameObject) {
					testrayTask.setName((String)nameObject);
				}

			});
		attributeGetterFunctions.put(
			"statusUpdateDate",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getStatusUpdateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusUpdateDate",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object statusUpdateDateObject) {

					testrayTask.setStatusUpdateDate(
						(Date)statusUpdateDateObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<TestrayTask, Object>() {

				@Override
				public Object apply(TestrayTask testrayTask) {
					return testrayTask.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<TestrayTask, Object>() {

				@Override
				public void accept(
					TestrayTask testrayTask, Object statusObject) {

					testrayTask.setStatus((Integer)statusObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTestrayTaskId() {
		return _testrayTaskId;
	}

	@Override
	public void setTestrayTaskId(long testrayTaskId) {
		_testrayTaskId = testrayTaskId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getTestrayBuildId() {
		return _testrayBuildId;
	}

	@Override
	public void setTestrayBuildId(long testrayBuildId) {
		_testrayBuildId = testrayBuildId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public Date getStatusUpdateDate() {
		return _statusUpdateDate;
	}

	@Override
	public void setStatusUpdateDate(Date statusUpdateDate) {
		_statusUpdateDate = statusUpdateDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TestrayTask.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TestrayTask toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TestrayTask>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TestrayTaskImpl testrayTaskImpl = new TestrayTaskImpl();

		testrayTaskImpl.setTestrayTaskId(getTestrayTaskId());
		testrayTaskImpl.setGroupId(getGroupId());
		testrayTaskImpl.setCompanyId(getCompanyId());
		testrayTaskImpl.setUserId(getUserId());
		testrayTaskImpl.setUserName(getUserName());
		testrayTaskImpl.setCreateDate(getCreateDate());
		testrayTaskImpl.setModifiedDate(getModifiedDate());
		testrayTaskImpl.setTestrayBuildId(getTestrayBuildId());
		testrayTaskImpl.setName(getName());
		testrayTaskImpl.setStatusUpdateDate(getStatusUpdateDate());
		testrayTaskImpl.setStatus(getStatus());

		testrayTaskImpl.resetOriginalValues();

		return testrayTaskImpl;
	}

	@Override
	public int compareTo(TestrayTask testrayTask) {
		int value = 0;

		value = getName().compareTo(testrayTask.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TestrayTask)) {
			return false;
		}

		TestrayTask testrayTask = (TestrayTask)object;

		long primaryKey = testrayTask.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;
	}

	@Override
	public CacheModel<TestrayTask> toCacheModel() {
		TestrayTaskCacheModel testrayTaskCacheModel =
			new TestrayTaskCacheModel();

		testrayTaskCacheModel.testrayTaskId = getTestrayTaskId();

		testrayTaskCacheModel.groupId = getGroupId();

		testrayTaskCacheModel.companyId = getCompanyId();

		testrayTaskCacheModel.userId = getUserId();

		testrayTaskCacheModel.userName = getUserName();

		String userName = testrayTaskCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			testrayTaskCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			testrayTaskCacheModel.createDate = createDate.getTime();
		}
		else {
			testrayTaskCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			testrayTaskCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			testrayTaskCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		testrayTaskCacheModel.testrayBuildId = getTestrayBuildId();

		testrayTaskCacheModel.name = getName();

		String name = testrayTaskCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			testrayTaskCacheModel.name = null;
		}

		Date statusUpdateDate = getStatusUpdateDate();

		if (statusUpdateDate != null) {
			testrayTaskCacheModel.statusUpdateDate = statusUpdateDate.getTime();
		}
		else {
			testrayTaskCacheModel.statusUpdateDate = Long.MIN_VALUE;
		}

		testrayTaskCacheModel.status = getStatus();

		return testrayTaskCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TestrayTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TestrayTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayTask, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TestrayTask)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TestrayTask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TestrayTask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayTask, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TestrayTask)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TestrayTask>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _testrayTaskId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _testrayBuildId;
	private String _name;
	private Date _statusUpdateDate;
	private int _status;
	private TestrayTask _escapedModel;

}