/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model.impl;

import com.liferay.osb.testray.model.TestrayTeam;
import com.liferay.osb.testray.service.TestrayTeamLocalServiceUtil;

/**
 * The extended model base implementation for the TestrayTeam service. Represents a row in the &quot;OSB_TestrayTeam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestrayTeamImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayTeamImpl
 * @see TestrayTeam
 * @generated
 */
public abstract class TestrayTeamBaseImpl
	extends TestrayTeamModelImpl implements TestrayTeam {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray team model instance should use the <code>TestrayTeam</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TestrayTeamLocalServiceUtil.addTestrayTeam(this);
		}
		else {
			TestrayTeamLocalServiceUtil.updateTestrayTeam(this);
		}
	}

}