/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.osb.testray.model.TestraySuite;
import com.liferay.osb.testray.service.TestraySuiteLocalServiceUtil;

/**
 * The extended model base implementation for the TestraySuite service. Represents a row in the &quot;OSB_TestraySuite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestraySuiteImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestraySuiteImpl
 * @see TestraySuite
 * @generated
 */
@ProviderType
public abstract class TestraySuiteBaseImpl
	extends TestraySuiteModelImpl implements TestraySuite {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray suite model instance should use the <code>TestraySuite</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TestraySuiteLocalServiceUtil.addTestraySuite(this);
		}
		else {
			TestraySuiteLocalServiceUtil.updateTestraySuite(this);
		}
	}

}