/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.testray.model.TestrayFactorCategory;
import com.liferay.osb.testray.model.TestrayFactorCategoryModel;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TestrayFactorCategory service. Represents a row in the &quot;OSB_TestrayFactorCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TestrayFactorCategoryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestrayFactorCategoryImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayFactorCategoryImpl
 * @generated
 */
public class TestrayFactorCategoryModelImpl
	extends BaseModelImpl<TestrayFactorCategory>
	implements TestrayFactorCategoryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray factor category model instance should use the <code>TestrayFactorCategory</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TestrayFactorCategory";

	public static final Object[][] TABLE_COLUMNS = {
		{"testrayFactorCategoryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("testrayFactorCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_TestrayFactorCategory (testrayFactorCategoryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OSB_TestrayFactorCategory";

	public static final String ORDER_BY_JPQL =
		" ORDER BY testrayFactorCategory.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_TestrayFactorCategory.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.testray.model.TestrayFactorCategory"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.testray.model.TestrayFactorCategory"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.osb.testray.model.TestrayFactorCategory"),
		true);

	public static final long GROUPID_COLUMN_BITMASK = 1L;

	public static final long NAME_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.testray.model.TestrayFactorCategory"));

	public TestrayFactorCategoryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _testrayFactorCategoryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTestrayFactorCategoryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _testrayFactorCategoryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TestrayFactorCategory.class;
	}

	@Override
	public String getModelClassName() {
		return TestrayFactorCategory.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TestrayFactorCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TestrayFactorCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayFactorCategory, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TestrayFactorCategory)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TestrayFactorCategory, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TestrayFactorCategory, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TestrayFactorCategory)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TestrayFactorCategory, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TestrayFactorCategory, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TestrayFactorCategory>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TestrayFactorCategory.class.getClassLoader(),
			TestrayFactorCategory.class, ModelWrapper.class);

		try {
			Constructor<TestrayFactorCategory> constructor =
				(Constructor<TestrayFactorCategory>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TestrayFactorCategory, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TestrayFactorCategory, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TestrayFactorCategory, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TestrayFactorCategory, Object>>();
		Map<String, BiConsumer<TestrayFactorCategory, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<TestrayFactorCategory, ?>>();

		attributeGetterFunctions.put(
			"testrayFactorCategoryId",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getTestrayFactorCategoryId();
				}

			});
		attributeSetterBiConsumers.put(
			"testrayFactorCategoryId",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object testrayFactorCategoryIdObject) {

					testrayFactorCategory.setTestrayFactorCategoryId(
						(Long)testrayFactorCategoryIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object groupIdObject) {

					testrayFactorCategory.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object companyIdObject) {

					testrayFactorCategory.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object userIdObject) {

					testrayFactorCategory.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object userNameObject) {

					testrayFactorCategory.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object createDateObject) {

					testrayFactorCategory.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object modifiedDateObject) {

					testrayFactorCategory.setModifiedDate(
						(Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<TestrayFactorCategory, Object>() {

				@Override
				public Object apply(
					TestrayFactorCategory testrayFactorCategory) {

					return testrayFactorCategory.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<TestrayFactorCategory, Object>() {

				@Override
				public void accept(
					TestrayFactorCategory testrayFactorCategory,
					Object nameObject) {

					testrayFactorCategory.setName((String)nameObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTestrayFactorCategoryId() {
		return _testrayFactorCategoryId;
	}

	@Override
	public void setTestrayFactorCategoryId(long testrayFactorCategoryId) {
		_testrayFactorCategoryId = testrayFactorCategoryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TestrayFactorCategory.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TestrayFactorCategory toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TestrayFactorCategory>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TestrayFactorCategoryImpl testrayFactorCategoryImpl =
			new TestrayFactorCategoryImpl();

		testrayFactorCategoryImpl.setTestrayFactorCategoryId(
			getTestrayFactorCategoryId());
		testrayFactorCategoryImpl.setGroupId(getGroupId());
		testrayFactorCategoryImpl.setCompanyId(getCompanyId());
		testrayFactorCategoryImpl.setUserId(getUserId());
		testrayFactorCategoryImpl.setUserName(getUserName());
		testrayFactorCategoryImpl.setCreateDate(getCreateDate());
		testrayFactorCategoryImpl.setModifiedDate(getModifiedDate());
		testrayFactorCategoryImpl.setName(getName());

		testrayFactorCategoryImpl.resetOriginalValues();

		return testrayFactorCategoryImpl;
	}

	@Override
	public int compareTo(TestrayFactorCategory testrayFactorCategory) {
		int value = 0;

		value = getName().compareTo(testrayFactorCategory.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TestrayFactorCategory)) {
			return false;
		}

		TestrayFactorCategory testrayFactorCategory =
			(TestrayFactorCategory)obj;

		long primaryKey = testrayFactorCategory.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TestrayFactorCategoryModelImpl testrayFactorCategoryModelImpl = this;

		testrayFactorCategoryModelImpl._originalGroupId =
			testrayFactorCategoryModelImpl._groupId;

		testrayFactorCategoryModelImpl._setOriginalGroupId = false;

		testrayFactorCategoryModelImpl._setModifiedDate = false;

		testrayFactorCategoryModelImpl._originalName =
			testrayFactorCategoryModelImpl._name;

		testrayFactorCategoryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TestrayFactorCategory> toCacheModel() {
		TestrayFactorCategoryCacheModel testrayFactorCategoryCacheModel =
			new TestrayFactorCategoryCacheModel();

		testrayFactorCategoryCacheModel.testrayFactorCategoryId =
			getTestrayFactorCategoryId();

		testrayFactorCategoryCacheModel.groupId = getGroupId();

		testrayFactorCategoryCacheModel.companyId = getCompanyId();

		testrayFactorCategoryCacheModel.userId = getUserId();

		testrayFactorCategoryCacheModel.userName = getUserName();

		String userName = testrayFactorCategoryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			testrayFactorCategoryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			testrayFactorCategoryCacheModel.createDate = createDate.getTime();
		}
		else {
			testrayFactorCategoryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			testrayFactorCategoryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			testrayFactorCategoryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		testrayFactorCategoryCacheModel.name = getName();

		String name = testrayFactorCategoryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			testrayFactorCategoryCacheModel.name = null;
		}

		return testrayFactorCategoryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TestrayFactorCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TestrayFactorCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayFactorCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((TestrayFactorCategory)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TestrayFactorCategory, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TestrayFactorCategory, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayFactorCategory, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((TestrayFactorCategory)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TestrayFactorCategory>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _testrayFactorCategoryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private TestrayFactorCategory _escapedModel;

}