/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.testray.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.testray.model.TestrayArchive;
import com.liferay.osb.testray.model.TestrayArchiveCompressedDataBlobModel;
import com.liferay.osb.testray.model.TestrayArchiveModel;
import com.liferay.osb.testray.service.TestrayArchiveLocalServiceUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TestrayArchive service. Represents a row in the &quot;OSB_TestrayArchive&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TestrayArchiveModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestrayArchiveImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayArchiveImpl
 * @generated
 */
public class TestrayArchiveModelImpl
	extends BaseModelImpl<TestrayArchive> implements TestrayArchiveModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray archive model instance should use the <code>TestrayArchive</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TestrayArchive";

	public static final Object[][] TABLE_COLUMNS = {
		{"testrayArchiveId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"compressedData", Types.BLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("testrayArchiveId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("compressedData", Types.BLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSB_TestrayArchive (testrayArchiveId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,compressedData BLOB)";

	public static final String TABLE_SQL_DROP = "drop table OSB_TestrayArchive";

	public static final String ORDER_BY_JPQL =
		" ORDER BY testrayArchive.testrayArchiveId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSB_TestrayArchive.testrayArchiveId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.osb.testray.model.TestrayArchive"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.osb.testray.model.TestrayArchive"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.osb.testray.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.osb.testray.model.TestrayArchive"));

	public TestrayArchiveModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _testrayArchiveId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTestrayArchiveId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _testrayArchiveId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TestrayArchive.class;
	}

	@Override
	public String getModelClassName() {
		return TestrayArchive.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TestrayArchive, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TestrayArchive, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TestrayArchive, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TestrayArchive)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TestrayArchive, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TestrayArchive, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TestrayArchive)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TestrayArchive, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TestrayArchive, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TestrayArchive>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TestrayArchive.class.getClassLoader(), TestrayArchive.class,
			ModelWrapper.class);

		try {
			Constructor<TestrayArchive> constructor =
				(Constructor<TestrayArchive>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TestrayArchive, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TestrayArchive, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TestrayArchive, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TestrayArchive, Object>>();
		Map<String, BiConsumer<TestrayArchive, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TestrayArchive, ?>>();

		attributeGetterFunctions.put(
			"testrayArchiveId",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getTestrayArchiveId();
				}

			});
		attributeSetterBiConsumers.put(
			"testrayArchiveId",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive,
					Object testrayArchiveIdObject) {

					testrayArchive.setTestrayArchiveId(
						(Long)testrayArchiveIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object groupIdObject) {

					testrayArchive.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object companyIdObject) {

					testrayArchive.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object userIdObject) {

					testrayArchive.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object userNameObject) {

					testrayArchive.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object createDateObject) {

					testrayArchive.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object modifiedDateObject) {

					testrayArchive.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"classNameId",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getClassNameId();
				}

			});
		attributeSetterBiConsumers.put(
			"classNameId",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object classNameIdObject) {

					testrayArchive.setClassNameId((Long)classNameIdObject);
				}

			});
		attributeGetterFunctions.put(
			"classPK",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getClassPK();
				}

			});
		attributeSetterBiConsumers.put(
			"classPK",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive, Object classPKObject) {

					testrayArchive.setClassPK((Long)classPKObject);
				}

			});
		attributeGetterFunctions.put(
			"compressedData",
			new Function<TestrayArchive, Object>() {

				@Override
				public Object apply(TestrayArchive testrayArchive) {
					return testrayArchive.getCompressedData();
				}

			});
		attributeSetterBiConsumers.put(
			"compressedData",
			new BiConsumer<TestrayArchive, Object>() {

				@Override
				public void accept(
					TestrayArchive testrayArchive,
					Object compressedDataObject) {

					testrayArchive.setCompressedData(
						(Blob)compressedDataObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getTestrayArchiveId() {
		return _testrayArchiveId;
	}

	@Override
	public void setTestrayArchiveId(long testrayArchiveId) {
		_testrayArchiveId = testrayArchiveId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@Override
	public Blob getCompressedData() {
		if (_compressedDataBlobModel == null) {
			try {
				_compressedDataBlobModel =
					TestrayArchiveLocalServiceUtil.getCompressedDataBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_compressedDataBlobModel != null) {
			blob = _compressedDataBlobModel.getCompressedDataBlob();
		}

		return blob;
	}

	@Override
	public void setCompressedData(Blob compressedData) {
		if (_compressedDataBlobModel == null) {
			_compressedDataBlobModel =
				new TestrayArchiveCompressedDataBlobModel(
					getPrimaryKey(), compressedData);
		}
		else {
			_compressedDataBlobModel.setCompressedDataBlob(compressedData);
		}
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TestrayArchive.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TestrayArchive toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TestrayArchive>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TestrayArchiveImpl testrayArchiveImpl = new TestrayArchiveImpl();

		testrayArchiveImpl.setTestrayArchiveId(getTestrayArchiveId());
		testrayArchiveImpl.setGroupId(getGroupId());
		testrayArchiveImpl.setCompanyId(getCompanyId());
		testrayArchiveImpl.setUserId(getUserId());
		testrayArchiveImpl.setUserName(getUserName());
		testrayArchiveImpl.setCreateDate(getCreateDate());
		testrayArchiveImpl.setModifiedDate(getModifiedDate());
		testrayArchiveImpl.setClassNameId(getClassNameId());
		testrayArchiveImpl.setClassPK(getClassPK());

		testrayArchiveImpl.resetOriginalValues();

		return testrayArchiveImpl;
	}

	@Override
	public int compareTo(TestrayArchive testrayArchive) {
		int value = 0;

		if (getTestrayArchiveId() < testrayArchive.getTestrayArchiveId()) {
			value = -1;
		}
		else if (getTestrayArchiveId() > testrayArchive.getTestrayArchiveId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TestrayArchive)) {
			return false;
		}

		TestrayArchive testrayArchive = (TestrayArchive)obj;

		long primaryKey = testrayArchive.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TestrayArchiveModelImpl testrayArchiveModelImpl = this;

		testrayArchiveModelImpl._setModifiedDate = false;

		testrayArchiveModelImpl._compressedDataBlobModel = null;
	}

	@Override
	public CacheModel<TestrayArchive> toCacheModel() {
		TestrayArchiveCacheModel testrayArchiveCacheModel =
			new TestrayArchiveCacheModel();

		testrayArchiveCacheModel.testrayArchiveId = getTestrayArchiveId();

		testrayArchiveCacheModel.groupId = getGroupId();

		testrayArchiveCacheModel.companyId = getCompanyId();

		testrayArchiveCacheModel.userId = getUserId();

		testrayArchiveCacheModel.userName = getUserName();

		String userName = testrayArchiveCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			testrayArchiveCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			testrayArchiveCacheModel.createDate = createDate.getTime();
		}
		else {
			testrayArchiveCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			testrayArchiveCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			testrayArchiveCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		testrayArchiveCacheModel.classNameId = getClassNameId();

		testrayArchiveCacheModel.classPK = getClassPK();

		return testrayArchiveCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{testrayArchiveId=");
		sb.append(getTestrayArchiveId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.testray.model.TestrayArchive");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>testrayArchiveId</column-name><column-value><![CDATA[");
		sb.append(getTestrayArchiveId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TestrayArchive>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _testrayArchiveId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private TestrayArchiveCompressedDataBlobModel _compressedDataBlobModel;
	private TestrayArchive _escapedModel;

}