/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.testray.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.testray.model.TestrayBuildMetric;
import com.liferay.osb.testray.model.TestrayBuildMetricModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TestrayBuildMetric service. Represents a row in the &quot;OSB_TestrayBuildMetric&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TestrayBuildMetricModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestrayBuildMetricImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayBuildMetricImpl
 * @see TestrayBuildMetric
 * @see TestrayBuildMetricModel
 * @generated
 */
@ProviderType
public class TestrayBuildMetricModelImpl extends BaseModelImpl<TestrayBuildMetric>
	implements TestrayBuildMetricModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray build metric model instance should use the {@link TestrayBuildMetric} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TestrayBuildMetric";
	public static final Object[][] TABLE_COLUMNS = {
			{ "testrayBuildMetricId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "testrayBuildId", Types.BIGINT },
			{ "testrayCaseTypeId", Types.BIGINT },
			{ "status", Types.INTEGER },
			{ "count", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("testrayBuildMetricId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("testrayBuildId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("testrayCaseTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("count", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_TestrayBuildMetric (testrayBuildMetricId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,testrayBuildId LONG,testrayCaseTypeId LONG,status INTEGER,count LONG)";
	public static final String TABLE_SQL_DROP = "drop table OSB_TestrayBuildMetric";
	public static final String ORDER_BY_JPQL = " ORDER BY testrayBuildMetric.testrayBuildMetricId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_TestrayBuildMetric.testrayBuildMetricId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.testray.model.TestrayBuildMetric"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.testray.model.TestrayBuildMetric"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.testray.model.TestrayBuildMetric"),
			true);
	public static final long STATUS_COLUMN_BITMASK = 1L;
	public static final long TESTRAYBUILDID_COLUMN_BITMASK = 2L;
	public static final long TESTRAYCASETYPEID_COLUMN_BITMASK = 4L;
	public static final long TESTRAYBUILDMETRICID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.testray.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.testray.model.TestrayBuildMetric"));

	public TestrayBuildMetricModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _testrayBuildMetricId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTestrayBuildMetricId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _testrayBuildMetricId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TestrayBuildMetric.class;
	}

	@Override
	public String getModelClassName() {
		return TestrayBuildMetric.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("testrayBuildMetricId", getTestrayBuildMetricId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("testrayBuildId", getTestrayBuildId());
		attributes.put("testrayCaseTypeId", getTestrayCaseTypeId());
		attributes.put("status", getStatus());
		attributes.put("count", getCount());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long testrayBuildMetricId = (Long)attributes.get("testrayBuildMetricId");

		if (testrayBuildMetricId != null) {
			setTestrayBuildMetricId(testrayBuildMetricId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long testrayBuildId = (Long)attributes.get("testrayBuildId");

		if (testrayBuildId != null) {
			setTestrayBuildId(testrayBuildId);
		}

		Long testrayCaseTypeId = (Long)attributes.get("testrayCaseTypeId");

		if (testrayCaseTypeId != null) {
			setTestrayCaseTypeId(testrayCaseTypeId);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long count = (Long)attributes.get("count");

		if (count != null) {
			setCount(count);
		}
	}

	@Override
	public long getTestrayBuildMetricId() {
		return _testrayBuildMetricId;
	}

	@Override
	public void setTestrayBuildMetricId(long testrayBuildMetricId) {
		_testrayBuildMetricId = testrayBuildMetricId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getTestrayBuildId() {
		return _testrayBuildId;
	}

	@Override
	public void setTestrayBuildId(long testrayBuildId) {
		_columnBitmask |= TESTRAYBUILDID_COLUMN_BITMASK;

		if (!_setOriginalTestrayBuildId) {
			_setOriginalTestrayBuildId = true;

			_originalTestrayBuildId = _testrayBuildId;
		}

		_testrayBuildId = testrayBuildId;
	}

	public long getOriginalTestrayBuildId() {
		return _originalTestrayBuildId;
	}

	@Override
	public long getTestrayCaseTypeId() {
		return _testrayCaseTypeId;
	}

	@Override
	public void setTestrayCaseTypeId(long testrayCaseTypeId) {
		_columnBitmask |= TESTRAYCASETYPEID_COLUMN_BITMASK;

		if (!_setOriginalTestrayCaseTypeId) {
			_setOriginalTestrayCaseTypeId = true;

			_originalTestrayCaseTypeId = _testrayCaseTypeId;
		}

		_testrayCaseTypeId = testrayCaseTypeId;
	}

	public long getOriginalTestrayCaseTypeId() {
		return _originalTestrayCaseTypeId;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public long getCount() {
		return _count;
	}

	@Override
	public void setCount(long count) {
		_count = count;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TestrayBuildMetric.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TestrayBuildMetric toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TestrayBuildMetric)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TestrayBuildMetricImpl testrayBuildMetricImpl = new TestrayBuildMetricImpl();

		testrayBuildMetricImpl.setTestrayBuildMetricId(getTestrayBuildMetricId());
		testrayBuildMetricImpl.setGroupId(getGroupId());
		testrayBuildMetricImpl.setCompanyId(getCompanyId());
		testrayBuildMetricImpl.setUserId(getUserId());
		testrayBuildMetricImpl.setUserName(getUserName());
		testrayBuildMetricImpl.setCreateDate(getCreateDate());
		testrayBuildMetricImpl.setModifiedDate(getModifiedDate());
		testrayBuildMetricImpl.setTestrayBuildId(getTestrayBuildId());
		testrayBuildMetricImpl.setTestrayCaseTypeId(getTestrayCaseTypeId());
		testrayBuildMetricImpl.setStatus(getStatus());
		testrayBuildMetricImpl.setCount(getCount());

		testrayBuildMetricImpl.resetOriginalValues();

		return testrayBuildMetricImpl;
	}

	@Override
	public int compareTo(TestrayBuildMetric testrayBuildMetric) {
		long primaryKey = testrayBuildMetric.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TestrayBuildMetric)) {
			return false;
		}

		TestrayBuildMetric testrayBuildMetric = (TestrayBuildMetric)obj;

		long primaryKey = testrayBuildMetric.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TestrayBuildMetricModelImpl testrayBuildMetricModelImpl = this;

		testrayBuildMetricModelImpl._setModifiedDate = false;

		testrayBuildMetricModelImpl._originalTestrayBuildId = testrayBuildMetricModelImpl._testrayBuildId;

		testrayBuildMetricModelImpl._setOriginalTestrayBuildId = false;

		testrayBuildMetricModelImpl._originalTestrayCaseTypeId = testrayBuildMetricModelImpl._testrayCaseTypeId;

		testrayBuildMetricModelImpl._setOriginalTestrayCaseTypeId = false;

		testrayBuildMetricModelImpl._originalStatus = testrayBuildMetricModelImpl._status;

		testrayBuildMetricModelImpl._setOriginalStatus = false;

		testrayBuildMetricModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TestrayBuildMetric> toCacheModel() {
		TestrayBuildMetricCacheModel testrayBuildMetricCacheModel = new TestrayBuildMetricCacheModel();

		testrayBuildMetricCacheModel.testrayBuildMetricId = getTestrayBuildMetricId();

		testrayBuildMetricCacheModel.groupId = getGroupId();

		testrayBuildMetricCacheModel.companyId = getCompanyId();

		testrayBuildMetricCacheModel.userId = getUserId();

		testrayBuildMetricCacheModel.userName = getUserName();

		String userName = testrayBuildMetricCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			testrayBuildMetricCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			testrayBuildMetricCacheModel.createDate = createDate.getTime();
		}
		else {
			testrayBuildMetricCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			testrayBuildMetricCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			testrayBuildMetricCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		testrayBuildMetricCacheModel.testrayBuildId = getTestrayBuildId();

		testrayBuildMetricCacheModel.testrayCaseTypeId = getTestrayCaseTypeId();

		testrayBuildMetricCacheModel.status = getStatus();

		testrayBuildMetricCacheModel.count = getCount();

		return testrayBuildMetricCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{testrayBuildMetricId=");
		sb.append(getTestrayBuildMetricId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", testrayBuildId=");
		sb.append(getTestrayBuildId());
		sb.append(", testrayCaseTypeId=");
		sb.append(getTestrayCaseTypeId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", count=");
		sb.append(getCount());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.testray.model.TestrayBuildMetric");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>testrayBuildMetricId</column-name><column-value><![CDATA[");
		sb.append(getTestrayBuildMetricId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testrayBuildId</column-name><column-value><![CDATA[");
		sb.append(getTestrayBuildId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testrayCaseTypeId</column-name><column-value><![CDATA[");
		sb.append(getTestrayCaseTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>count</column-name><column-value><![CDATA[");
		sb.append(getCount());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TestrayBuildMetric.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TestrayBuildMetric.class
		};
	private long _testrayBuildMetricId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _testrayBuildId;
	private long _originalTestrayBuildId;
	private boolean _setOriginalTestrayBuildId;
	private long _testrayCaseTypeId;
	private long _originalTestrayCaseTypeId;
	private boolean _setOriginalTestrayCaseTypeId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _count;
	private long _columnBitmask;
	private TestrayBuildMetric _escapedModel;
}