/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.testray.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.testray.model.TestrayIssue;
import com.liferay.osb.testray.model.TestrayIssueModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TestrayIssue service. Represents a row in the &quot;OSB_TestrayIssue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TestrayIssueModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TestrayIssueImpl}.
 * </p>
 *
 * @author Ethan Bustad
 * @see TestrayIssueImpl
 * @see TestrayIssue
 * @see TestrayIssueModel
 * @generated
 */
@ProviderType
public class TestrayIssueModelImpl extends BaseModelImpl<TestrayIssue>
	implements TestrayIssueModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a testray issue model instance should use the {@link TestrayIssue} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_TestrayIssue";
	public static final Object[][] TABLE_COLUMNS = {
			{ "testrayIssueId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("testrayIssueId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table OSB_TestrayIssue (testrayIssueId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(150) null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_TestrayIssue";
	public static final String ORDER_BY_JPQL = " ORDER BY testrayIssue.testrayIssueId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_TestrayIssue.testrayIssueId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.testray.model.TestrayIssue"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.testray.model.TestrayIssue"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.testray.model.TestrayIssue"),
			true);
	public static final long NAME_COLUMN_BITMASK = 1L;
	public static final long TESTRAYISSUEID_COLUMN_BITMASK = 2L;
	public static final String MAPPING_TABLE_OSB_TESTRAYCASERESULTS_TESTRAYISSUES_NAME =
		"OSB_TestrayCaseResults_TestrayIssues";
	public static final Object[][] MAPPING_TABLE_OSB_TESTRAYCASERESULTS_TESTRAYISSUES_COLUMNS =
		{
			{ "companyId", Types.BIGINT },
			{ "testrayCaseResultId", Types.BIGINT },
			{ "testrayIssueId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_TESTRAYCASERESULTS_TESTRAYISSUES_SQL_CREATE =
		"create table OSB_TestrayCaseResults_TestrayIssues (companyId LONG not null,testrayCaseResultId LONG not null,testrayIssueId LONG not null,primary key (testrayCaseResultId, testrayIssueId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_TESTRAYCASERESULTS_TESTRAYISSUES =
		GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_TestrayCaseResults_TestrayIssues"),
			true);
	public static final String MAPPING_TABLE_OSB_TESTRAYSUBTASKS_TESTRAYISSUES_NAME =
		"OSB_TestraySubtasks_TestrayIssues";
	public static final Object[][] MAPPING_TABLE_OSB_TESTRAYSUBTASKS_TESTRAYISSUES_COLUMNS =
		{
			{ "companyId", Types.BIGINT },
			{ "testrayIssueId", Types.BIGINT },
			{ "testraySubtaskId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_TESTRAYSUBTASKS_TESTRAYISSUES_SQL_CREATE =
		"create table OSB_TestraySubtasks_TestrayIssues (companyId LONG not null,testrayIssueId LONG not null,testraySubtaskId LONG not null,primary key (testrayIssueId, testraySubtaskId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_TESTRAYSUBTASKS_TESTRAYISSUES =
		GetterUtil.getBoolean(com.liferay.osb.testray.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_TestraySubtasks_TestrayIssues"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.testray.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.testray.model.TestrayIssue"));

	public TestrayIssueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _testrayIssueId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTestrayIssueId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _testrayIssueId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TestrayIssue.class;
	}

	@Override
	public String getModelClassName() {
		return TestrayIssue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("testrayIssueId", getTestrayIssueId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long testrayIssueId = (Long)attributes.get("testrayIssueId");

		if (testrayIssueId != null) {
			setTestrayIssueId(testrayIssueId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@Override
	public long getTestrayIssueId() {
		return _testrayIssueId;
	}

	@Override
	public void setTestrayIssueId(long testrayIssueId) {
		_testrayIssueId = testrayIssueId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TestrayIssue.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TestrayIssue toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TestrayIssue)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TestrayIssueImpl testrayIssueImpl = new TestrayIssueImpl();

		testrayIssueImpl.setTestrayIssueId(getTestrayIssueId());
		testrayIssueImpl.setGroupId(getGroupId());
		testrayIssueImpl.setCompanyId(getCompanyId());
		testrayIssueImpl.setUserId(getUserId());
		testrayIssueImpl.setUserName(getUserName());
		testrayIssueImpl.setCreateDate(getCreateDate());
		testrayIssueImpl.setModifiedDate(getModifiedDate());
		testrayIssueImpl.setName(getName());

		testrayIssueImpl.resetOriginalValues();

		return testrayIssueImpl;
	}

	@Override
	public int compareTo(TestrayIssue testrayIssue) {
		long primaryKey = testrayIssue.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TestrayIssue)) {
			return false;
		}

		TestrayIssue testrayIssue = (TestrayIssue)obj;

		long primaryKey = testrayIssue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TestrayIssueModelImpl testrayIssueModelImpl = this;

		testrayIssueModelImpl._setModifiedDate = false;

		testrayIssueModelImpl._originalName = testrayIssueModelImpl._name;

		testrayIssueModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TestrayIssue> toCacheModel() {
		TestrayIssueCacheModel testrayIssueCacheModel = new TestrayIssueCacheModel();

		testrayIssueCacheModel.testrayIssueId = getTestrayIssueId();

		testrayIssueCacheModel.groupId = getGroupId();

		testrayIssueCacheModel.companyId = getCompanyId();

		testrayIssueCacheModel.userId = getUserId();

		testrayIssueCacheModel.userName = getUserName();

		String userName = testrayIssueCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			testrayIssueCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			testrayIssueCacheModel.createDate = createDate.getTime();
		}
		else {
			testrayIssueCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			testrayIssueCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			testrayIssueCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		testrayIssueCacheModel.name = getName();

		String name = testrayIssueCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			testrayIssueCacheModel.name = null;
		}

		return testrayIssueCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{testrayIssueId=");
		sb.append(getTestrayIssueId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.testray.model.TestrayIssue");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>testrayIssueId</column-name><column-value><![CDATA[");
		sb.append(getTestrayIssueId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TestrayIssue.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TestrayIssue.class
		};
	private long _testrayIssueId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private TestrayIssue _escapedModel;
}