/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.customer.metrics.sync.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.osb.customer.metrics.sync.model.SyncState;
import com.liferay.osb.customer.metrics.sync.model.SyncStateModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SyncState service. Represents a row in the &quot;OSBCustomer_SyncState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SyncStateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SyncStateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SyncStateImpl
 * @see SyncState
 * @see SyncStateModel
 * @generated
 */
@ProviderType
public class SyncStateModelImpl extends BaseModelImpl<SyncState>
	implements SyncStateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sync state model instance should use the {@link SyncState} interface instead.
	 */
	public static final String TABLE_NAME = "OSBCustomer_SyncState";
	public static final Object[][] TABLE_COLUMNS = {
			{ "syncStateId", Types.BIGINT },
			{ "model", Types.VARCHAR },
			{ "lastRunTime", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("syncStateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("model", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastRunTime", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table OSBCustomer_SyncState (syncStateId LONG not null primary key,model VARCHAR(75) null,lastRunTime LONG)";
	public static final String TABLE_SQL_DROP = "drop table OSBCustomer_SyncState";
	public static final String ORDER_BY_JPQL = " ORDER BY syncState.syncStateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSBCustomer_SyncState.syncStateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.metrics.sync.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.customer.metrics.sync.model.SyncState"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.metrics.sync.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.customer.metrics.sync.model.SyncState"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.osb.customer.metrics.sync.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.customer.metrics.sync.model.SyncState"),
			true);
	public static final long MODEL_COLUMN_BITMASK = 1L;
	public static final long SYNCSTATEID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.osb.customer.metrics.sync.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.customer.metrics.sync.model.SyncState"));

	public SyncStateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _syncStateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSyncStateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _syncStateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SyncState.class;
	}

	@Override
	public String getModelClassName() {
		return SyncState.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SyncState, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SyncState, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<SyncState, Object> attributeGetterFunction = entry.getValue();

			attributes.put(attributeName,
				attributeGetterFunction.apply((SyncState)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SyncState, Object>> attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SyncState, Object> attributeSetterBiConsumer = attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((SyncState)this,
					entry.getValue());
			}
		}
	}

	public Map<String, Function<SyncState, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SyncState, Object>> getAttributeSetterBiConsumers() {
		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SyncState, Object>> _attributeGetterFunctions;
	private static final Map<String, BiConsumer<SyncState, Object>> _attributeSetterBiConsumers;

	static {
		Map<String, Function<SyncState, Object>> attributeGetterFunctions = new LinkedHashMap<String, Function<SyncState, Object>>();
		Map<String, BiConsumer<SyncState, ?>> attributeSetterBiConsumers = new LinkedHashMap<String, BiConsumer<SyncState, ?>>();


		attributeGetterFunctions.put(
			"syncStateId",
			new Function<SyncState, Object>() {

				@Override
				public Object apply(SyncState syncState) {
					return syncState.getSyncStateId();
				}

			});
		attributeSetterBiConsumers.put(
			"syncStateId",
			new BiConsumer<SyncState, Object>() {

				@Override
				public void accept(SyncState syncState, Object syncStateId) {
					syncState.setSyncStateId((Long)syncStateId);
				}

			});
		attributeGetterFunctions.put(
			"model",
			new Function<SyncState, Object>() {

				@Override
				public Object apply(SyncState syncState) {
					return syncState.getModel();
				}

			});
		attributeSetterBiConsumers.put(
			"model",
			new BiConsumer<SyncState, Object>() {

				@Override
				public void accept(SyncState syncState, Object model) {
					syncState.setModel((String)model);
				}

			});
		attributeGetterFunctions.put(
			"lastRunTime",
			new Function<SyncState, Object>() {

				@Override
				public Object apply(SyncState syncState) {
					return syncState.getLastRunTime();
				}

			});
		attributeSetterBiConsumers.put(
			"lastRunTime",
			new BiConsumer<SyncState, Object>() {

				@Override
				public void accept(SyncState syncState, Object lastRunTime) {
					syncState.setLastRunTime((Long)lastRunTime);
				}

			});


		_attributeGetterFunctions = Collections.unmodifiableMap(attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap((Map)attributeSetterBiConsumers);
	}

	@Override
	public long getSyncStateId() {
		return _syncStateId;
	}

	@Override
	public void setSyncStateId(long syncStateId) {
		_syncStateId = syncStateId;
	}

	@Override
	public String getModel() {
		if (_model == null) {
			return "";
		}
		else {
			return _model;
		}
	}

	@Override
	public void setModel(String model) {
		_columnBitmask |= MODEL_COLUMN_BITMASK;

		if (_originalModel == null) {
			_originalModel = _model;
		}

		_model = model;
	}

	public String getOriginalModel() {
		return GetterUtil.getString(_originalModel);
	}

	@Override
	public long getLastRunTime() {
		return _lastRunTime;
	}

	@Override
	public void setLastRunTime(long lastRunTime) {
		_lastRunTime = lastRunTime;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SyncState.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SyncState toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SyncState)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SyncStateImpl syncStateImpl = new SyncStateImpl();

		syncStateImpl.setSyncStateId(getSyncStateId());
		syncStateImpl.setModel(getModel());
		syncStateImpl.setLastRunTime(getLastRunTime());

		syncStateImpl.resetOriginalValues();

		return syncStateImpl;
	}

	@Override
	public int compareTo(SyncState syncState) {
		long primaryKey = syncState.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SyncState)) {
			return false;
		}

		SyncState syncState = (SyncState)obj;

		long primaryKey = syncState.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SyncStateModelImpl syncStateModelImpl = this;

		syncStateModelImpl._originalModel = syncStateModelImpl._model;

		syncStateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SyncState> toCacheModel() {
		SyncStateCacheModel syncStateCacheModel = new SyncStateCacheModel();

		syncStateCacheModel.syncStateId = getSyncStateId();

		syncStateCacheModel.model = getModel();

		String model = syncStateCacheModel.model;

		if ((model != null) && (model.length() == 0)) {
			syncStateCacheModel.model = null;
		}

		syncStateCacheModel.lastRunTime = getLastRunTime();

		return syncStateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SyncState, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((4 * attributeGetterFunctions.size()) +
				2);

		sb.append("{");

		for (Map.Entry<String, Function<SyncState, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<SyncState, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((SyncState)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SyncState, Object>> attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler((5 * attributeGetterFunctions.size()) +
				4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SyncState, Object>> entry : attributeGetterFunctions.entrySet()) {
			String attributeName = entry.getKey();
			Function<SyncState, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SyncState)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SyncState.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SyncState.class, ModelWrapper.class
		};
	private long _syncStateId;
	private String _model;
	private String _originalModel;
	private long _lastRunTime;
	private long _columnBitmask;
	private SyncState _escapedModel;
}